### PR TITLE
nut 2.7.3: fix usb option

### PR DESCRIPTION
**Pull request by reitermarkus**
Signed-off-by: Markus Reiter <me@reitermark.us>

### CODE REVIEW

**Comment by dunn** [comment]
Since `depends_on "libusb-compat" => :recommended` is still present, this is going to create two options.  We should just fix the second line to read:
```ruby
args << (build.with?("libusb-compat") ? "--with-usb" : "--without-usb")
```

**Comment by DomT4** [comment]
If we're changing an option name it should be `deprecated` onto the new name as well.

**Comment by reitermarkus** [comment]
Ok, I reverted the first line and only changed the second line.

**Comment by dunn** [comment]
Thanks! Merged in 86fc06d2a060c55650375e3761dd2cd9086948eb.

**Pull request closed without merging**
