### PR TITLE
gmp: use SSL/TLS mirror and homepage

### PR DESCRIPTION
**Pull request by vszakats**

### CODE REVIEW

**Comment by jacknagel** [comment]
We used to use this site, but it's much, much slower than the gnu.org mirrors, plus we lose geolocation. I'll merge the homepage chnage if you update the PR, though.

**Comment by vszakats** [comment]
Thanks for the information. Reordered both formulae.

**Comment by vszakats** [comment]
Failure unrelated to this patch:
```
Calling: ghc -O -Werror -i/private/tmp/agda20150514-22240-cr920n /private/tmp/agda20150514-22240-cr920n/MAlonzo/Code/QsimpleZ45Ztest.hs --make -fwarn-incomplete-patterns -fno-warn-overlapping-patterns
ghc: createProcess: runInteractiveProcess: exec: does not exist (No
such file or directory)
Error: agda: failed
Failed executing: /usr/local/Cellar/agda/2.4.2.2_1/bin/agda -c --no-main --safe /private/tmp/agda20150514-22240-cr920n/simple-test.agda
```

**Comment by mikemcquaid** [comment]
Thanks again @vszakats!

**Pull request closed without merging**
