### PR TITLE
Add mcrypt dependency

### LINKED ISSUE #48489: yle-dl 2.9.0: missing dependency PHP mcrypt
As far as I can tell, yle-dl formula is not usable unless PHP mcrypt extension is installed.

```
$ yle-dl http://areena.yle.fi/1-3065619
yle-dl 2.9.0: Download media files from Yle Areena and Elävä Arkisto
Copyright (C) 2009-2015 Antti Ajanki <antti.ajanki@iki.fi>, license: GPLv3
Output file: Yle Uutiset-2016-01-24T09:55:00+02:00.flv

                            KSV Adobe HDS Downloader

You have to install and enable the following extension(s) to continue: 'mcrypt'
Failed to import youtube_dl
```

The error message is not obvious, but AdobeHDS is a PHP implementation called by yle-dl and it depends on PHP mcrypt being available, which is not the case on my OS X 10.11. I installed yle-dl from bottle and PHP is OS X built-in, not from brew. My homebrew is 720cdef19ab3ee7f5c89ebebe7c95f0247d74d45

```
$ brew doctor
Your system is ready to brew.
```
There should at minimum be a caveat in yle-dl Formula with info how to install PHP mcrypt extension. I have no idea how to install PHP extensions.

### PR DESCRIPTION
**Pull request by javian**
Fixes #48489

### CODE REVIEW

**Comment by DomT4** [comment]
We can't have mandatory cross-tap dependencies in the core. It causes problems, and it's not great on the end-user to be "surprised" to find the whole PHP tap is suddenly a dependency for one formula.

Realistically, our options are probably:
* This moves to the PHP tap.
* We don't enforce the dependency and just add a very shouty caveat telling people what they need to do for this to be functional as expected.
* We add some custom requirement logic and stop bottling the formula.

**Comment by javian** [comment]
It is not a pure PHP program since its a mix between python and PHP so I would not put it in the php tap. I'll change the PR into an informative caveat to start with.

Requirements
- python (2.6 or newer)
- pycrypto
- PHP interpreter
- PHP extensions: bcmath, curl, mcrypt and SimpleXML`


I asked in the IRC channel the other day about depending on other taps and the answer I got said that it should work so that's why I put it in. I'll fix it later today and push.

**Comment by javian** [comment]
I made an update and added optional dependencies. I only found one other formula that had an optional dependency to the php tap so its not very common practice it seems. We can leave at this or remove the optionals as well and just point it out in the caveat text.

**Comment by DomT4** [comment]
I'm fine with the way you've re-written it. That seems a good compromise to me.

Merged in https://github.com/Homebrew/homebrew/commit/4d93e32a66e797cffb44d73e9e6e51f16f6478ea. Thank you for another contribution to Homebrew @javian! :smiley_cat:

**Pull request closed without merging**
