### PR TITLE
mariadb 10.0.18

### PR DESCRIPTION
**Pull request by makigumo**

### CODE REVIEW

**Comment by makigumo** [comment]
Clang crashes in ML build, but I don't think it's a problem in mariadb's source :/
```
Linking C executable comp_sql
cd /tmp/mariadb20150506-28564-1ak2zpe/mariadb-10.0.18/scripts && /usr/local/Cellar/cmake/3.2.2/bin/cmake -E cmake_link_script CMakeFiles/comp_sql.dir/link.txt --verbose=1
/usr/local/Library/ENV/4.3/clang  -O2 -g -DNDEBUG -DDBUG_OFF -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/comp_sql.dir/comp_sql.c.o  -o comp_sql  
clang: error: unable to execute command: Segmentation fault: 11
clang: error: linker command failed due to signal (use -v to see invocation)
make[2]: *** [scripts/comp_sql] Error 254
make[1]: *** [scripts/CMakeFiles/comp_sql.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by tdsmith** [comment]
Kicked off a rebuild.

**Comment by makigumo** [comment]
Thanks, this time it worked :)

**Comment by asparagui** [comment]
Thanks!

**Pull request closed without merging**
