### PR TITLE
mkvtoolnix 8.5.1 (depends on libmatroska 1.4.4)

### PR DESCRIPTION
**Pull request by jamesyc**
Update from 8.3.0 to 8.5.1.

(**WARNING**) The checks for this pull request will fail until the libmatroska formula is updated to version 1.4.4.

### CODE REVIEW

**Comment by bfontaine** [comment]
We need to wait for #45454 then.

**Comment by bfontaine** [comment]
@BrewTestBot test this please

**Comment by jamesyc** [comment]
Bump

**Comment by DomT4** [comment]
I was already in the process of merging before you bumped; please give us a while before bumping.

Merged in https://github.com/Homebrew/homebrew/commit/4cccd5bf16dc646d3b343efbc9dc7d79510c3157. Thank you once more @jamesyc!

**Pull request closed without merging**
