### PR TITLE
pgpdump: use secure source url

### PR DESCRIPTION
**Pull request by vszakats**
### All Submissions:

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew/pulls) for the same update/change?

### CODE REVIEW

**Comment by LinusU** [comment]
Why has the sha-sum changed? Is it no longer the same file?

**Comment by vszakats** [comment]
See my commit message. The old/manual release missed the hidden `.gitignore` file.

**Comment by LinusU** [comment]
Ah, sorry, missed that...

**Comment by vszakats** [comment]
Double-checked with a diff on the two trees, and it confirmed there is no other difference.

**Comment by DomT4** [comment]
Thanks for explaining the checksum change! Merged in https://github.com/Homebrew/homebrew/commit/f790b0bc49d78211af10f142b7a7efa1db1269da :rocket:

**Pull request closed without merging**
