### PR TITLE
cmd/info: show time of last commit to formula

### PR DESCRIPTION
**Pull request by dunn**
This is (imo) a nice way to check how likely it is that a formula is up-to-date.  It does have a noticeable impact on speed on formulae that haven't been updated in a while, though, so I get if that's a deal-breaker.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Could you use the file modified time instead?

**Comment by dunn** [comment]
so `--pretty=format:%ad` instead of `--pretty=format:%cd`?

**Comment by dunn** [comment]
or did you mean replace the `git log` command with something like `date -r $(stat -f "%m" #{formula_path})` to get the local modification time?  That would be affected by uncommitted local changes to formula, which might be OK, but it would also mean the date listed would never be older than when the Homebrew repo was cloned to that computer.

**Comment by mikemcquaid** [comment]
I wasn't sure if Git would preserve those dates, it seems it doesn't. Is it possible to e.g. scope log so it only looks in the last 30 days for speed?

**Comment by dunn** [comment]
Yeah, that makes the delay much less noticeable (I found some really old formulae to test on and the original delay was way longer than I expected); but it's also more complicated and not quite as useful now so it might not be worthwhile after all :/

**Comment by mikemcquaid** [comment]
I'm happy for you to play around with the number of days to find a happy medium.

**Comment by dunn** [comment]
`z.rb` was last edited in Jul 2013.  Here's how long `brew info z` takes with no limit on how far we look back:
```
real    0m6.387s
user    0m6.239s
sys     0m0.141s
```

If we only go back 90 days:
```
real    0m1.498s
user    0m1.395s
sys     0m0.097s
```

60 days:
```
real    0m1.163s
user    0m1.066s
sys     0m0.091s
```

30 days:
```
real    0m0.823s
user    0m0.732s
sys     0m0.086s
```

So no matter what it's going to take at least almost a second.  Compare that to the original `info` command:
```
real    0m0.150s
user    0m0.119s
sys     0m0.029s
```

For me the 1.5 second delay is worth it for being able to look back 90 days, but that might not be OK for anyone else.  What's the biggest delay you and the other maintainers are willing to accept?

**Comment by mikemcquaid** [comment]
It looks like it's a non-starter I think; just the speed :(

**Comment by dunn** [comment]
Yeah, makes sense.  No problem!

**Pull request closed without merging**
