### PR TITLE
thefuck 2.7

### PR DESCRIPTION
**Pull request by scorphus**
Hello, *homebrewers*! Here we go again!

This new release, 2.7, brings a number of improvements:

* Support to sudo with pipes
* Support to options --version, --alias and --help
* Suggest more than one result in *_no_command rules
* Ability to chose one of a number of matched rules
* Fixes/improvements of many rules

Formula tested on Yosemite.

Thanks!

### CODE REVIEW

**Comment by dunn** [comment]
Unfortunately the test is failing:
```
==> /usr/local/Cellar/thefuck/2.7/bin/thefuck echho ok
[1K
[1mecho ok[0m [[32menter[0m/[34m↑[0m/[34m↓[0m/[31mctrl+c[0m]Traceback (most recent call last):
  File "/usr/local/Cellar/thefuck/2.7/libexec/bin/thefuck", line 9, in <module>
    load_entry_point('thefuck==2.7', 'console_scripts', 'thefuck')()
  File "/usr/local/Cellar/thefuck/2.7/libexec/lib/python2.7/site-packages/thefuck/main.py", line 129, in main
    fix_command()
  File "/usr/local/Cellar/thefuck/2.7/libexec/lib/python2.7/site-packages/thefuck/main.py", line 95, in fix_command
    selected_command = select_command(corrected_commands, settings)
  File "/usr/local/Cellar/thefuck/2.7/libexec/lib/python2.7/site-packages/thefuck/ui.py", line 94, in select_command
    for action in read_actions():
  File "/usr/local/Cellar/thefuck/2.7/libexec/lib/python2.7/site-packages/thefuck/ui.py", line 35, in read_actions
    ch = getch()
  File "/usr/local/Cellar/thefuck/2.7/libexec/lib/python2.7/site-packages/thefuck/ui.py", line 14, in getch
    old = termios.tcgetattr(fd)
termios.error: (25, 'Inappropriate ioctl for device')
Error: thefuck: failed
<0> expected but was
<1>.
```
I was actually surprised the test was passing for the last few releases, since it changed to requiring confirmation from the user as to whether the new command was correct.

**Comment by scorphus** [comment]
Yeah, I'm on it. I'll fix it and update this pull request.

**Comment by scorphus** [comment]
The thing is, latest checkins into TheFuck made the test `thefuck echoo ok` require user input. I know `thefuck --version` is a bad test but this is the only kind of test we can do now.

I'll soon propose a change into TheFuck to accept a new option – such as `--no-input` – to skip user input. Not exactly to make it pass a *good* test but to support an idea I have in mind to make it work better/faster with Fish Shell.

Let's see if I correctly wrote that test this late in the night :smile:

**Comment by dunn** [comment]
This should work until a `--no-input` option is available:
```ruby
  test do
    IO.popen("#{bin}/thefuck echho ok", "r+") do |pipe|
      pipe.puts "\n"
      assert_equal "echo ok", pipe.gets.chomp
      pipe.close_write
    end
  end
```

**Comment by scorphus** [comment]
That's awesome! Let me update this pull request.

**Comment by scorphus** [comment]
Thanks, @dunn! I'm really better learn some Ruby.

**Comment by scorphus** [comment]
I managed to run that test locally and it fails with that same error: `termios.error: (25, 'Inappropriate ioctl for device') `. Should we stick to `thefuck --version` until the next release?

**Comment by mikemcquaid** [comment]
@scorphus Yeh, :+1:

**Comment by scorphus** [comment]
Oh, my bad, I just found out `thefuck --version` outputs to `stderr`. I'm trying to correctly assert that instead.

**Comment by scorphus** [comment]
How do I run the test in the same (or almost the same) conditions as the build bot?

**Comment by mikemcquaid** [comment]
@scorphus I suspect setting `ENV["LC_ALL"] = "en_US.UTF-8"` in the test may fix this.

**Comment by scorphus** [comment]
Yeah, I thought the same, I just wanted to bot-like test locally prior to triggering another lengthy build. `brew test --verbose thefuck` tells me I need the latest version of thefuck. Same goes for `brew test --verbose thefuck`.

I'm update this PR just now. Thanks, @mikemcquaid.

**Comment by scorphus** [comment]
Those up/down arrows are messing with the encoding. Let's stick to testing `--version` and `--alias` and wait for an upcoming release with a `--no-input` or `--no-confirmation` option.

**Comment by scorphus** [comment]
Do we have `git` available in the test bot? We could use it to test `thefuck git branchh` as this would offer just one correction – `git branch` – with no up/down arrows.

**Comment by dunn** [comment]
Yep, git is available.

**Comment by scorphus** [comment]
YAY!

**Comment by dunn** [comment]
Merged in c72d6f2f267c020b1aea51dd34e208ffcf3bbba7 \o/ 

I simplified the first two tests a bit.  Thanks for putting in the time on this!

**Pull request closed without merging**
