### PR TITLE
adobe-air-sdk 16.0.0.272

### PR DESCRIPTION
**Pull request by vpmedia**
Hi,

I've updated the Adobe AIR SDK package with the latest version.

Thank You!

### CODE REVIEW

**Comment by vpmedia** [comment]
Thanks!

**Comment by pasviegas** [comment]
I'm an error while trying to download the latest version:

Error: SHA1 mismatch
Expected: ee487b3c0456ba825dd6af48682ba81802ef0300
Actual: 5ed2481de822e7f557db33c1bbff9b30e7df4735
Archive: /Library/Caches/Homebrew/adobe-air-sdk-16.0.0.272.tbz2
To retry an incomplete download, remove the file above.

**Comment by vpmedia** [comment]
Hi,
I'm pretty sure Adobe did switch the packages off while keeping the build no., I'll send a pull request with an update soon..

**Comment by vpmedia** [comment]
Hi,
I've downloaded the latest packages and the hashes are matching..
3feaadf534f5f186286eb33cb4461d7e78cdb91d *AdobeAIRSDK.tbz2
5ed2481de822e7f557db33c1bbff9b30e7df4735 *AIRSDK_Compiler.tbz2
https://github.com/Homebrew/homebrew/blob/master/Library/Formula/adobe-air-sdk.rb
Maybe try to doctor/update/upgrade brew..

**Comment by DomT4** [comment]
They always use a static download link, so whenever they update the SHA breaks. Homebrew manually inserts the ` version ` into the formula so ` brew ` knows to update it. A ` brew update && brew upgrade ` should get you an installable Air-SDK formula again.

**Pull request closed without merging**
