### PR TITLE
cdrtools 3.02a06 (devel)

### PR DESCRIPTION
**Pull request by fbrosson**

### CODE REVIEW

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/5f7d2e8cd357a5b70526410f8d7baebbcdf52d81. Thank you for your contribution to Homebrew @fbrosson! :smiley_cat:

**Comment by fbrosson** [comment]
Hi @DomT4 ! I noticed that PRs that get merged on other projects become purple (with a "Merged" label), whereas on Homebrew (and Tigerbrew) PRs become red (with a "Closed" label). This is not important, but it would be nice to be able to distinguish those PRs that have been closed without a merge from those which have been merged before closure. Was it on purpose that the configuration of the workflow of the PRs on Homebrew was changed compared to the standard configuration? I contribute from time to time to a few other projects on GitHub, and all of them have standard workflows for their PRs. Having purple "Merged" labels for one's PRs is much more exciting than having a red "Closed" label, don't you agree? I'm bringing the subject in case you would like to discuss it with the Homebrew staff. Anyway, thanks for the merge :)

**Comment by fbrosson** [comment]
Hmm, the message above is
> __Closed with unmerged commits__ This pull request is closed, but the `fbrosson:cdrtools` branch has unmerged commits.

On all other projects staff members do not merge __copies__ of the commits but the __original__ commits. That's why, on those projects, we don't get the warning message telling that the branch has unmerged commits. There is probably a reason why Homebrew is not using standard workflows and/or processes, but I don't know what these reasons are... But don't worry. I won't stop contributing just because my PRs become red :)

**Comment by DomT4** [comment]
We cherry-pick commits because it's cleaner and means we're not spamming up our commit tree with merge commits every five seconds, essentially. It also means we can sign-off on those commits to establish a chain of trust.

Cherry-picking rather than merging also means when applicable we can pull bottles without messing around with separate commands.

There's reference to this [here](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Maintainer-Guidelines.md#merging-rebasing-cherry-picking) and you can read the command that executes it [here](https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/cmd/pull.rb).

You can see the PR has been merged and closed rather than just closed because the commit closes the PR and references it, as you can see here:
screen shot 2016-01-30 at 17 46 17

**Comment by fbrosson** [comment]
OK, thanks for your detailed answer and for the pointers. Now I understand why things are done this way. Cheers!

**Pull request closed without merging**
