### PR TITLE
azure-cli 0.9.18

### PR DESCRIPTION
**Pull request by yous**
Bump [azure-cli](https://github.com/azure/azure-xplat-cli) to 0.9.18.

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew/pulls) for the same update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>`?
- [x] Have you successfully ran `brew test <formula>` with your changes locally?

### CODE REVIEW

**Comment by yous** [comment]
Homebrew think the version of azure-cli is `hotfix`.

```
==> brew audit azure-cli
==> FAILED
Error: 1 problem in 1 formula
azure-cli:
 * Stable: version (hotfix) is set to a string without a digit
```

**Comment by DomT4** [comment]
Need to add an explicit `version "0.9.18"` line underneath the `url` to fix that :)

**Comment by yous** [comment]
Thanks, updated.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/f3d505b9d8d7977a045ccfd2c7695d837d9e7b7b. Thanks!

**Pull request closed without merging**
