### PR TITLE
jboss-forge 2.18.0.Final

### PR DESCRIPTION
**Pull request by gastaldi**

### CODE REVIEW

**Comment by dunn** [comment]
We've started running the tests in a sandbox, and it's trying to write outside it: http://bot.brew.sh/job/Homebrew%20Pull%20Requests/31821/version=yosemite/testReport/junit/brew-test-bot/yosemite/test_jboss_forge/

Mind tweaking the test to fix that?

**Comment by gastaldi** [comment]
I might need some help on Ruby syntax. This environment variable needs to be set before executing Forge

     export FORGE_OPTS=-Duser.home=/path/to/writeable-dir

**Comment by dunn** [comment]
This should work:
```ruby
ENV["FORGE_OPTS"] = "-Duser.home=#{testpath}"`
```

**Comment by gastaldi** [comment]
Thanks! Just copy/pasted your command before executing the test. Hope that fixes the problem

**Comment by gastaldi** [comment]
There was an extra ` in your example. I removed it and committed again

**Comment by gastaldi** [comment]
Looks like all is good now. Thanks for your help

**Comment by dunn** [comment]
Awesome! Merged in e9c213f6b2b55bcb325139a310fa07129c28f0ce 💥

**Pull request closed without merging**
