### PR TITLE
test-bot testing (Ignore)

### PR DESCRIPTION
**Pull request by DomT4**
See https://github.com/Homebrew/homebrew-devel-only/pull/10

### CODE REVIEW

**Comment by DomT4** [comment]
@mikemcquaid Interestingly, with the tap stuff commented out, it looks like it's failing the bot here too. Still passing locally.

**Comment by DomT4** [comment]
Trying something a little bit different. Wondering if the ` def ` is the problem. Maybe placement is wrong or it's not activating an element correctly, so trying something a little different.

**Comment by DomT4** [comment]
That failed too. Interestingly, it looks like it's failing to properly detect the tap on the Bot, even though it's succeeding locally.

**Comment by DomT4** [comment]
And that failed too. Going as basic as I can with this latest test.

**Comment by DomT4** [comment]
@mikemcquaid Testing seems to show the tap detection element is the failure. Any call to ` puts formula.tap ` or ` if tap == ` or ` formula.tap == ` breaks the bot. Without the call to the tap there, it inserts the ` devel ` element as expected on the test-bot:

```
==> brew install --verbose --build-bottle --devel mlite			 PASSED
```

Failure is the lack of being bottled, which we've fixed in the other bot PR, and the audit, which I'll look at again in a bit.

Any thoughts on the calls to tap failing here?

**Comment by DomT4** [comment]
@mikemcquaid Sorry to be a pain in the arse. Any thoughts here?

**Comment by mikemcquaid** [comment]
> Testing seems to show the tap detection element is the failure. Any call to puts formula.tap or if tap == or formula.tap == breaks the bot. Without the call to the tap there, it inserts the devel element as expected on the test-bot:

Can you paste a backtrace or something for this breakage?

**Comment by DomT4** [comment]
Not really. It works fine locally, but breaks on the bot, which makes it difficult to backtrace. All I can show to prove it is the failure to pass ` --devel ` to install here every time we include a ` formula.tap ` reference and a success every time we skip around making that ` formula.tap ` call. If you like, I can tee up another PR with the ` formula.tap ` method included to show it failing compared to the most recent test here? That wouldn't provide a backtrace but it would show where my theory is coming from.

**Comment by mikemcquaid** [comment]
Sounds good. Shout when there's error output to look at, thanks.

**Comment by DomT4** [comment]
Just in case the test here drops off the Bot because it's a few days old, this was the most recent test with no calls to ` formula.tap ` made:

```
==> brew update								 PASSED
==> git checkout 22e10f5						 PASSED
==> brew pull --clean https://github.com/Homebrew/homebrew/pull/36327	 PASSED
==> brew doctor								 PASSED
==> brew --env								 PASSED
==> brew config								 PASSED
==> brew tests								 PASSED
==> brew readall							 PASSED
==> brew uses mlite							 PASSED
==> brew fetch --retry --build-bottle --force mlite			 PASSED
Homebrew/homebrew
==> brew install --verbose --build-bottle --devel mlite			 PASSED
==> brew audit mlite --strict						 FAILED
==> brew style mlite

1 file inspected, no offenses detected
Error: 1 problems in 1 formulae

==> audit problems
mlite:
 * Devel-only (no stable download)

==> brew bottle --rb mlite						 FAILED
Error: Formula has no stable version: mlite
==> brew test --verbose mlite						 PASSED
==> brew uninstall --force mlite					 PASSED
==> git clean -fdx							 PASSED
==> git checkout -f master						 PASSED
==> git reset --hard							 PASSED
==> brew cleanup							 PASSED
```

**Pull request closed without merging**
