### PR TITLE
wine 1.7.52 (devel)

### PR DESCRIPTION
**Pull request by uyjulian**

### CODE REVIEW

**Comment by uyjulian** [comment]
Hmm, patch is broken. Let's try again.

**Comment by dunn** [comment]
Merged in b45825e59bf2981340e4ef1297c28428b622ec13, thank you! 🍷

**Comment by LinusU** [comment]
The patch is still very necessary and this upgrade now broke most of my games :( Please don't just remove it because it didn't apply cleanly or because it wasn't needed for the app you are using wine for.

I'm sending a pull request to address this shortly.

**Comment by LinusU** [comment]
#44551

**Pull request closed without merging**
