### PR TITLE
wine 1.8-rc1（devel）

### PR DESCRIPTION
**Pull request by uyjulian**

### CODE REVIEW

**Comment by uyjulian** [comment]
all fine on my side √

**Comment by DomT4** [comment]
Why the move away from Sourceforge here? Is that an upstream thing?

**Comment by uyjulian** [comment]
wine switched to dl.winehq.org in the release notes: https://www.winehq.org/announce/1.8-rc1

**Comment by DomT4** [comment]
Cool, don't mind the change away if that's an upstream thing. Thanks for restoring the `https` upstream link!

**Comment by uyjulian** [comment]
It seems like there is still new versions published on the sourceforge. Oh, well I'll include that as a mirror anyway.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/2bbfd03937b8cd2c612da64508f52443938422ba. Thank you for another Homebrew contribution @uyjulian! :smiley_cat:

**Pull request closed without merging**
