### PR TITLE
Don't link fontforge extension modules to libpython

### PR DESCRIPTION
**Pull request by tdsmith**
Let's just pull this for now since it's been discussed upstream in fontforge/fontforge#2353 and fontforge/fontforge#2356.

### CODE REVIEW

**Comment by DomT4** [comment]
Any chance you can chuck the version bump in here as well from #40631?

**Comment by tdsmith** [comment]
I think I won't, but you may ;)

**Comment by tdsmith** [comment]
(I'm worried that we'll have to fuss with the detection code and I should be doing other things today.)

**Comment by DomT4** [comment]
Since we're not adding a revision or anything here I'll chase in your PR with the version bump once this is merged :)

**Comment by tdsmith** [comment]
Oh, the detection code is already in this version; I'll go for the newer version.

**Comment by DomT4** [comment]
@tdsmith :heart:

**Pull request closed without merging**
