### PR TITLE
ruby-build 20150303

### PR DESCRIPTION
**Pull request by sferik**
* Add Ruby 2.2.1

### CODE REVIEW

**Comment by xu-cheng** [comment]
Dupe of #37353

**Comment by sferik** [comment]
@xu-cheng This pull request came first, so I’m not sure how it can be a dupe of something that came after it. Either way, can you please merge one or the other?

**Comment by xu-cheng** [comment]
@sferik Sorry, I didn't pay much attention on which one comes first.

**Comment by xu-cheng** [comment]
Thanks your contribution. I have merged it.

**Pull request closed without merging**
