### PR TITLE
imagemagick 6.9.3

### PR DESCRIPTION
**Pull request by nijikon**
Please upload source file to dl.bintray.com/homebrew/mirror/

### CODE REVIEW

**Comment by DomT4** [comment]
Done!

Merged in https://github.com/Homebrew/homebrew/commit/692816998ff7a7d6791305f6a32fefebb1fe6ac4. Thank you @nijikon!

**Comment by gaming-hacker** [comment]
you might want to update the perlmagick formula as well, it's out of date

**Comment by DomT4** [comment]
@gaming-hacker As far as I can see it's not out-of-date per se? There's no new release?

**Comment by gaming-hacker** [comment]
perlmagick still uses old libs, did you just update the formula?  mine shows

  desc "Objected-oriented Perl interface to ImageMagick"
  homepage "http://www.imagemagick.org/script/perl-magick.php"
  url "http://www.imagemagick.org/download/perl/PerlMagick-6.89.tar.gz"

**Comment by bfontaine** [comment]
@gaming-hacker The `Makefile` hardcodes `/usr/local`; the formula replaces (see the `gsub!`s) these hardcoded paths with dynamic Homebrew ones.

**Comment by gaming-hacker** [comment]
@bfontaine i'm still trying to build imagemagick libs with bits then i'll fix perlmagick

**Comment by DomT4** [comment]
> desc "Objected-oriented Perl interface to ImageMagick"
homepage "http://www.imagemagick.org/script/perl-magick.php"
url "http://www.imagemagick.org/download/perl/PerlMagick-6.89.tar.gz"

6.89 is current, is it not?

**Comment by DomT4** [comment]
Oh I see. They've discontinued supplying it separately and now it's part of ImageMagick. Interesting.

**Comment by gaming-hacker** [comment]
correct 6.9.3.0 is current

**Comment by DomT4** [comment]
Possibly just worth deleting the formula and merging it into ImageMagick then, making it an optional option.

**Comment by DomT4** [comment]
It's already in the ImageMagick formula, as `--with-perl`. At this point I have no idea why the PerlMagick formula is still around. Will go look through some old PRs to see if it was mentioned.

**Comment by gaming-hacker** [comment]
looks like the perl magick wants 16bit libs so you need to build 16/32 libs?

**Comment by DomT4** [comment]
Yeah. Working on it.

**Comment by DomT4** [comment]
https://github.com/Homebrew/homebrew/pull/47873

**Pull request closed without merging**
