### PR TITLE
isync 1.1.2

### PR DESCRIPTION
**Pull request by DomT4**
Related: #37600

### CODE REVIEW

**Comment by asparagui** [comment]
@mikemcquaid 

==> Downloading https://homebrew.bintray.com/bottles/isync-1.1.2.yosemite.bottle.tar.gz
curl: (22) The requested URL returned error: 401 Unauthorized
Error: Failed to download resource "isync"
Download failed: https://homebrew.bintray.com/bottles/isync-1.1.2.yosemite.bottle.tar.gz

**Comment by asparagui** [comment]
@BrewTestBot test this please

**Comment by mikemcquaid** [comment]
Thanks for picking this up so quickly @DomT4!

**Comment by DomT4** [comment]
Thanks Mike. Regardless of version bump, the OpenSSL element needed to be fixed, so it made sense to do everything at once :smiley_cat:

**Pull request closed without merging**
