### PR TITLE
swagger-codegen: No Java 1.7 in recent OSX, should be 1.7+

### PR DESCRIPTION
**Pull request by chroneus**

### CODE REVIEW

**Comment by DomT4** [comment]
You'll need to set:

```ruby
ENV["_JAVA_OPTIONS"] = "-Duser.home=#{buildpath}"
```
At the top of `def install` here as well.

We tend to get the Java requirements from upstream, so unless upstream now support Java 1.8 this isn't likely to actually build against it. Upstream do say [Java 7](https://github.com/swagger-api/swagger-codegen#os-x-users) is still required.

**Comment by DomT4** [comment]
Closing per the above, but feel free to check with upstream if they support Java 1.8 yet and resubmit if they do. Thanks for your submission to Homebrew :heart:

**Comment by arnested** [comment]
Just for the record. Swagger Codegen supports Java 8 and and now it is documented upstream as well. The formula has incorporated this in #47805 which was merged just now.

**Comment by DomT4** [comment]
@arnested Thanks for the update!

**Pull request closed without merging**
