### PR TITLE
b43-fwcutter: add https mirror, use https homepage

### PR DESCRIPTION
**Pull request by vszakats**

### CODE REVIEW

**Comment by vszakats** [comment]
Intermittent checkout error on Mavericks only:
```
 > git checkout -f c831f67095960f8992f245f00f3dd4ad06ed81af
FATAL: Could not checkout null with start point c831f67095960f8992f245f00f3dd4ad06ed81af
hudson.plugins.git.GitException: Could not checkout null with start point c831f67095960f8992f245f00f3dd4ad06ed81af
```

**Comment by bfontaine** [comment]
Restarted.

**Comment by vszakats** [comment]
Thanks @bfontaine!

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/5ae83d40239afdb1f373ec9244eb0d6a31f7eb69. Thanks @vszakats!

**Pull request closed without merging**
