### PR TITLE
kafka: set JAVA_HOME, remove windows scripts

### PR DESCRIPTION
**Pull request by xu-cheng**
Also modernize and add test

### CODE REVIEW

**Comment by xu-cheng** [comment]
Test failed on Mountain Lion as it requires matplotlib and numpy (which are shipped with 10.9+) for test case. What's best solution for this? If I use `resource`, there will be at least half of a dozen resources to install matplotlib and numpy. Is it acceptable?

**Comment by xu-cheng** [comment]
Or can I just simple skip the test if `matplotlib` is unavailable?

**Comment by tdsmith** [comment]
Is matplotlib needed for the normal operation of the software? Can you skip the test that needs matplotlib (possibly with an inreplace) or run a simpler test? It'd be nice to have a fallback test for 10.8.

**Comment by xu-cheng** [comment]
I fixed it by turning matplotlib related method into dummy one.

**Pull request closed without merging**
