### PR TITLE
Updates selenium-server-standalone to 2.45.0

### PR DESCRIPTION
**Pull request by epixa**
2.45.0 is the current latest stable version of selenium server. It was released about a week ago.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

For future reference the preferred commit message format for simple version updates is `selenium-server-standalone 2.45.0`.

**Comment by epixa** [comment]
@mikemcquaid That actually is the commit message format that I used.  Should I also use that for the PR message in the future?

**Comment by mikemcquaid** [comment]
My apologies, I misread! Yeh for the PR message would be ideal (just to stop me being an idiot again :grimacing:).

**Comment by epixa** [comment]
Grand. Thanks for the merge!

**Pull request closed without merging**
