### PR TITLE
Update fibjs to 0.1.7, fix version number

### PR DESCRIPTION
**Pull request by xicilion**

### CODE REVIEW

**Comment by DomT4** [comment]
Slightly odd error. Looks like it might be trying to break free of the sandbox, maybe.

```
==> ./build Release -j4
CMake Error: The current CMakeCache.txt directory /tmp/fibjs20151025-47307-pwa1ap/out/Darwin_Release/exlib/CMakeCache.txt is different than the directory /Users/lion/Downloads/fibjs-0.1.7/out/Darwin_Release/exlib where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
CMake Error: The source "/tmp/fibjs20151025-47307-pwa1ap/vender/exlib/CMakeLists.txt" does not match the source "/Users/lion/Downloads/fibjs-0.1.7/vender/exlib/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.
```

**Comment by DomT4** [comment]
Does this need a revision bump if there are upstream changes to the `0.1.7` release?

**Comment by xicilion** [comment]
No need, just a version number

**Comment by DomT4** [comment]
Alright, merged in https://github.com/Homebrew/homebrew/commit/4a2f225ba6a99d74f5e3e9d7794f1e9e6b69653e. Thanks @xicilion!

**Pull request closed without merging**
