### PR TITLE
Add s v1.0, a tool to simplify ssh login.

### PR DESCRIPTION
**Pull request by haosdent**
s is a tool for ssh like z for cd. It could simplify user ssh login. More details could found from https://github.com/haosdent/s .

### CODE REVIEW

**Comment by mikemcquaid** [comment]
I think this may be worth maintaining in your own tap.

**Comment by haosdent** [comment]
so let me close this pull request?

**Comment by mikemcquaid** [comment]
Do you know everything you'd need to maintain your own tap? Happy to keep this open to help either get review on this formula and/or help you get your tap sorted.

**Comment by haosdent** [comment]
sorry, i don't know. any documents about this? Thank you.

**Comment by haosdent** [comment]
oh, i see now. Thank you very much, let me keep it in my tap.

**Comment by mikemcquaid** [comment]
https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/brew-tap.md

**Comment by mikemcquaid** [comment]
Thanks for understanding!

**Pull request closed without merging**
