### PR TITLE
libpagemaker 0.0.2

### PR DESCRIPTION
**Pull request by luzpaz**

### CODE REVIEW

**Comment by luzpaz** [comment]
please commit.. thx!

**Comment by bfontaine** [comment]
We need a :+1: / :-1: from @Homebrew/owners here.

**Comment by mistydemeo** [comment]
@luzpaz Please be patient! It's been less than 24 hours since you submitted this.

**Comment by mistydemeo** [comment]
Bottle upload failed, retrying.

**Comment by mistydemeo** [comment]
@BrewTestBot test this please

**Comment by luzpaz** [comment]
@mistydemeo sorry. was too excited :|

**Comment by luzpaz** [comment]
@mikemcquaid would you kindly green light this? Thanks

**Comment by mikemcquaid** [comment]
Hmm, this PR isn't building for some odd reason.

**Comment by mikemcquaid** [comment]
This file needs to be in `Library/Formula` not `Library`

**Comment by luzpaz** [comment]
closing and resubmitting as https://github.com/Homebrew/homebrew/pull/40738

**Pull request closed without merging**
