### PR TITLE
rust 1.0.0-alpha

### PR DESCRIPTION
**Pull request by kesla**

### CODE REVIEW

**Comment by remear** [comment]
Worked great on my machine.

```bash
$ brew upgrade rust
==> Upgrading 1 outdated package, with result:
rust 1.0.0-alpha
==> Upgrading rust
==> Downloading https://static.rust-lang.org/dist/rustc-1.0.0-alpha-src.tar.gz
######################################################################## 100.0%
==> Patching
==> ./configure --prefix=/usr/local/Cellar/rust/1.0.0-alpha --enable-clang
==> make
==> make install
🍺  /usr/local/Cellar/rust/1.0.0-alpha: 11708 files, 445M, built in 45.2 minutes
$ rustc --version
rustc 1.0.0-dev
```

**Comment by tdsmith** [comment]
`brew install foo` should never install a prerelease version; we can add a `devel` block for this (like in `wine.rb`) to allow `brew install --devel rust`.

**Comment by jacknagel** [comment]
@tdsmith I think an exception can be made since *all* rust releases thus far are pre-releases.

**Comment by tdsmith** [comment]
Heh, fair. Their note re release schedule is interesting; they expect 1.0-beta1 in six weeks. http://blog.rust-lang.org/2015/01/09/Rust-1.0-alpha.html

**Pull request closed without merging**
