### PR TITLE
open-ocd: update to 0.9.0-rc1

### PR DESCRIPTION
**Pull request by paulfertser**
Signed-off-by: Paul Fertser <fercerpav@gmail.com>

### CODE REVIEW

**Comment by bonniebonic** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<feed xmlns="http://www.w3.org/2005/Atom" xmlns:media="http://search.yahoo.com/mrss/" xml:lang="en-US">
  <id>tag:github.com,2008:/bonniebonic.private</id>
  <link type="text/html" rel="alternate" href="https://github.com/bonniebonic"/>
  <link type="application/atom+xml" rel="self" href="https://github.com/bonniebonic.private.atom?token=ALgCgHMVZ02c46FpGPdNvMieFk_tw1ubks6zR7mHwA=="/>
  <title>Private Feed for bonniebonic</title>
  <updated>2015-04-22T00:35:47Z</updated>
</feed>

**Comment by asparagui** [comment]
How long till an official release?

**Comment by paulfertser** [comment]
Hey asparagui,

I can't tell for sure as the release process depends on user testing and feedback a lot. It might take as long as few months. But the codebase is usually quite stable (every patch goes through Gerrit code review) and many active users are always following git HEAD anyway. That's not enough however (as the project supports a lot of very different targets and boards), so we'd very much like to get a wider testing for 0.9.0-rc1.

**Comment by mikemcquaid** [comment]
@paulfertser It should either be added as a `devel do` block or we should wait until we have a non-RC release.

**Comment by paulfertser** [comment]
I've made the requested change but Jenkins failed the Yosemite build due to some temporary unavailability of the SF.net servers, the file was available before and is available right ATM.

**Comment by asparagui** [comment]
@BrewTestBot test this please

**Comment by xu-cheng** [comment]
Thanks for the pull request! 🎉 Homebrew depends on contributions from community members like you and we're grateful for your support.

**Pull request closed without merging**
