### PR TITLE
neo4j-2.3.0-M03 (devel)

### PR DESCRIPTION
**Pull request by mindrones**

### CODE REVIEW

**Comment by dunn** [comment]
One of the resources has shifted under us:
```
==> Downloading http://dist.neo4j.org/jexp/shell/neo4j-shell-tools_2.2.zip
Warning: Resource neo4j-shell-tools reports different SHA256: a84bd306754701c1748a26dcf207c136c9859f60cdd60e003771f0df0a83fb00
Downloaded to: /Library/Caches/Homebrew/neo4j--neo4j-shell-tools-2.2.zip
SHA1: eb6ccc064ef17a25278f2bc017c513218331f9b9
SHA256: e295f724b6c5e35db5d471eefc976bd5adcd002763722c726885455e3f38f2ca
```
Would you mind poking the developers about whether this is benign or not?

**Comment by mindrones** [comment]
@dunn you're right, I have fixed this now, thanks for pointing this out.
From now on I'll clear the resources cache before testing the installation :)

**Comment by dunn** [comment]
I'd still like to know that it was an intentional change by the developers, and that we're not downloading anything malicious.

**Comment by mindrones** [comment]
neo4j-shell-tools is developed by Michael Hunger, which works for Neo Technology so I doubt that he is releasing a malicious neo4j plugin :)
You can find his latest commits at https://github.com/jexp/neo4j-shell-tools/commits/2.2

**Comment by DomT4** [comment]
There's no accusation that the upstream developer would release anything malicious, but in this day and age it is easy enough to compromise accounts & impersonate Git commit attribution. It's also pretty easy to push onto a branch accidentally and cause problems that way.

We ask about checking upstream on checksum changes to ensure it originated from them and was intended. 'Tis all :)

**Comment by mindrones** [comment]
I see. As stated in my latest commit the problem is he committed some new code and re-packed the distribution zip file with the same name, hence the checksum change.

**Comment by mindrones** [comment]
Now that I think about it maybe we can ask @jexp himself?

**Comment by jexp** [comment]
I'm fine if you remove it. 
People that need it can install it if they want to, no need to add another dependency.

**Comment by mindrones** [comment]
@dunn @DomT4 I'd say up to you to decide: I'd prefer to keep it as it's easier to install but if this breaks any homebrew policy then of course I'll remove it.

**Comment by DomT4** [comment]
It's fine unless the checksum changes regularly; we just wanted confirmation that the checksum change was "legit".

**Comment by jexp** [comment]
Yup it was legit, I can going forward also provide exactly versioned files.

**Comment by mindrones** [comment]
@jexp that would be awesome :)

@DomT4 @dunn the [Formula cookbook](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md) doesn't mention it, but from [resource.rb](https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/resource.rb) it would seem that we can add a version field in the resource right?

**Comment by DomT4** [comment]
> Yup it was legit, I can going forward also provide exactly versioned files

Thank you for the confirmation, and versioned files in future would be absolutely perfect!

> but from resource.rb it would seem that we can add a version field in the resource right?

Yup.

**Comment by mindrones** [comment]
@jexp if you are going to release a versioned file (say "2.2.02.zip") I could wait and add a version to the resource so that the SHA change would be justified and we can follow version changes from now on, what do you think?

**Comment by jexp** [comment]
shasum neo4j-shell-tools_2.3.0-M03.zip 
d8783e04625c0a215351a0b5cca9d62ecd37e044  neo4j-shell-tools_2.3.0-M03.zip

http://dist.neo4j.org/jexp/shell/neo4j-shell-tools_2.3.0-M03.zip

**Comment by mindrones** [comment]
@jexp thanks! I was expecting you to version the 2.2 file though, otherwise I should add a version both to the stable and the development resource.
Would it be OK to have a version for the stable release (say 2.2.03) and have a versioned zip file (say neo4j-shell-tools_2.2.03.zip) and use it for 2.3.0-M03 too?
This way from now on I'd just change the version to the stable one assuming it would work for the development release.

**Comment by jexp** [comment]
It is probably not compatible with the 2.2.5 version i can generate a separate one

Von meinem iPhone gesendet

**Comment by mindrones** [comment]
@jexp Thanks. To best setup would be to tag neo4j-shell-tools releases (like 2.2.01, 2.2.02, ..., 2.3.01, 2.3.02, ...) and provide correspondent zip files
- http://dist.neo4j.org/jexp/shell/neo4j-shell-tools_2.2.01.zip
- ...
- http://dist.neo4j.org/jexp/shell/neo4j-shell-tools_2.3.01.zip
- ...

so that the last one of correspondent branch would apply.

@domT4 would it be OK to do this?

```ruby
  devel do
    url "http://dist.neo4j.org/neo4j-community-2.3.0-M03-unix.tar.gz"
    sha256 "cd47ae541a0c5da0d82212c30c1c2fb19ea91ddb1b174346c120e596e04b5dfc"
    version "2.3.0-M03"

    resource "neo4j-shell-tools" do
      url "http://dist.neo4j.org/jexp/shell/neo4j-shell-tools_2.3.01.zip"
      sha256 "60ca25046dfe3040d57f41809db0b1c6e1c506af77a710d8aa94d8eaa0aaf105"
    end
  end

  option "with-neo4j-shell-tools", "Add neo4j-shell-tools to the standard neo4j-shell"

  resource "neo4j-shell-tools" do
    url "http://dist.neo4j.org/jexp/shell/neo4j-shell-tools_2.2.01.zip"
    sha256 "e295f724b6c5e35db5d471eefc976bd5adcd002763722c726885455e3f38f2ca"
  end
```

**Comment by DomT4** [comment]
@mindrones You'd want to create a `stable do` block there as well, i.e.:

```ruby
class Neo4j < Formula
  desc "Robust (fully ACID) transactional property graph database"
  homepage "http://neo4j.com"

  stable do
    url "http://dist.neo4j.org/neo4j-community-2.2.5-unix.tar.gz"
    sha256 "7fadc119f465a3d6adceb610401363fb158a5ed25081f9893d4f56ac4989a998"

   resource "example" do
     url ""
     version ""
     sha256 ""
   end
  end

  devel do
    url ""
    version ""
    sha256 ""

   resource "example" do
     url ""
     version ""
     sha256 ""
   end
  end
```

**Comment by mindrones** [comment]
@DomT4 nice! I'll wait Michael's opinion about tagging/releasing though, then eventually I'll try that patch.

**Comment by mindrones** [comment]
Hey @jexp any news about this? neo4j 2.2.6 and 2.3.0-RC1 are out now and the only way we can update the formula now is:

- have neo4j-sheel-tools released with versions
- remove neo4j-sheel-tools :/

What should we do?

**Comment by mindrones** [comment]
@jexp maybe releasing neo4j-shell-tools with versions is too much of a hassle, do you prefer we remove it from this formula?

**Comment by mindrones** [comment]
@DomT4 it seems like we have to remove this pluging to move on (I'd like to push the new versions of neo4j), what do you think?

**Comment by DomT4** [comment]
I don't mind it being removed. We can always add it back later.

**Comment by mindrones** [comment]
OK then I'll remove it.
In order to maintain `neo4j` history, after this PR will be in homebrew I'll push another PR with a new stable and devel version (`neo4j 2.2.6` and `2.3.0-RC1`), ok?

**Comment by DomT4** [comment]
Sure.

**Comment by mindrones** [comment]
OK thanks, should I push 2 different PRs, one for `2.2.6` and one for `2.3.0-RC1`, or can they be a single PR?

**Comment by DomT4** [comment]
They can be a single PR.

**Comment by mindrones** [comment]
OK, I'll wait for you guys to merge this PR then I'll do.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/4b5ecb0b9816be25bf7080300b952fe75a28df0a & https://github.com/Homebrew/homebrew/commit/416e1c8541b70dd71e0b0a29a0840338a573fad0. Thank you for sticking with this @mindrones! :smiley_cat:

**Pull request closed without merging**
