### PR TITLE
ccextractor 0.75

### PR DESCRIPTION
**Pull request by bfontaine**

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Just merged https://github.com/Homebrew/homebrew/pull/36485 but would accept the other, rebased changes.

**Comment by bfontaine** [comment]
Oops just saw that, I rebased and changed the commit message.

**Comment by bfontaine** [comment]
Works on my Mac, fails on the bot. [Bot output](http://bot.brew.sh/job/Homebrew%20Pull%20Requests/20846/version=yosemite/testReport/junit/brew-test-bot/yosemite/install_ccextractor/) with simplified paths:

``` 
[ 10%] Building C object lib_ccx/CMakeFiles/ccx.dir/cc_bitstream.c.o
cd /ccextractor.0.75/lib_ccx && /usr/local/Library/ENV/4.3/clang   -O0 -Wall -g -std=gnu99 -I/ccextractor.0.75/src -I/ccextractor.0.75/src/lib_ccx -I/ccextractor.0.75/src/gpacmp4 -I/ccextractor.0.75/src/libccx_common    -o CMakeFiles/ccx.dir/cc_bitstream.c.o   -c /ccextractor.0.75/src/lib_ccx/cc_bitstream.c
/ccextractor.0.75/src/lib_ccx/608_smptett.cIn file included from /ccextractor.0.75/src/lib_ccx/608_spupng.c:3:4::
In file included from /ccextractor.0.75/src/lib_ccx/608_spupng.h:4:
/ccextractor.0.75/src/lib_ccx/spupng_encoder.h:6:10: fatal error: 'png.h' file not found
#include "png.h"
         ^
10: fatal error: 'png.h' file not found
#include "png.h"
         ^
/ccextractor.0.75/src/lib_ccx/608_sami.c:4:10: fatal error: 'png.h' file not found
#include "png.h"
         ^
```

While [on my Mac](https://gist.github.com/bfontaine/456174840ede21d95ae5), with the exact same `cmake` command, in `brew install -i ccextractor`:

```
[ 10%] Building C object lib_ccx/CMakeFiles/ccx.dir/cc_bitstream.c.o
cd /ccextractor.0.75/lib_ccx && /usr/local/Library/ENV/4.3/clang   -O0 -Wall -g -std=gnu99 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.10 -I/ccextractor.0.75/src -I/ccextractor.0.75/src/lib_ccx -I/ccextractor.0.75/src/gpacmp4 -I/ccextractor.0.75/src/libccx_common    -o CMakeFiles/ccx.dir/cc_bitstream.c.o   -c /ccextractor.0.75/src/lib_ccx/cc_bitstream.c
/usr/local/Cellar/cmake/3.1.1_1/bin/cmake -E cmake_progress_report /ccextractor.0.75/CMakeFiles 11
[ 11%] Building C object lib_ccx/CMakeFiles/ccx.dir/ccx_common_char_encoding.c.o
(…)
```

Note I get a `-isysroot` arguments, not sure where it comes from.

**Comment by mikemcquaid** [comment]
Looks like a missing `libpng` dependency?

**Comment by bfontaine** [comment]
@mikemcquaid Right, it works now. I assumed that it would have to use `#include <png.h>` instead of `#include "png.h"` for an external dependency, and there’s a `png.h` in the archive.

**Pull request closed without merging**
