### PR TITLE
luvit: version bump to 2.3.0

### PR DESCRIPTION
**Pull request by tzudot**
luvit: version bump to 2.3.0

### CODE REVIEW

**Comment by DomT4** [comment]
Last time I checked they'd completely changed the build process here, so the formula may need *drastic* changes.

**Comment by DomT4** [comment]
Any interest in chasing this around?

**Comment by tzudot** [comment]
Yes, I had looked into the luvit (,lit and luvi) build process. Need to try out the build process for `release` packages instead of the procedure in docs to build from git `master`. I'll comment here, shortly, on whether I would be interested in pursuing this PR. By the way, is it a good idea to move `luvit` and the other two formulae to a Hombrew tap?

**Comment by tzudot** [comment]
Chatted with @creationix on IRC. He already has formulae for luvi, lit, and luvit. He'll carry on with this process.

**Comment by tzudot** [comment]
Luvit team is currently working to solve two [issues](https://github.com/luvit/luvit/issues/787) for luvit installation in Homebrew.

**Comment by creationix** [comment]
Should probably close this in favor to #42525.

**Pull request closed without merging**
