### PR TITLE
FoBiS.py 1.7.4 (new formula)

### PR DESCRIPTION
**Pull request by zbeekman**
A powerful build tool for modern Fortran

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Test is failing: http://bot.brew.sh/job/Homebrew%20Pull%20Requests/31537/version=yosemite/testReport/junit/brew-test-bot/yosemite/test_fobis/

**Comment by zbeekman** [comment]
oops, thanks for pinging me...

**Comment by zbeekman** [comment]
To clarify why the tests were failing: I  had forgotten to specify the  gnu fortran compiler, and FoBiS.py defaults to the Intel compiler. This is installed on my system, so tests passed when I ran them locally, but is clearly not going to be installed on many systems. Since we require `:fortran` we can anticipate, AFAICT, that most users should have gfortran, and certainly testbot will. (FoBiS.py will work with any number of compilers, but in rare circumstances it is conceivable that users could NOT have gfortran installed, but use a different compiler through the `FC` environment variable. In this latter case, the test will fail on their system, due to the lack of gfortran, even though FoBiS.py is still useable.)

**Comment by zbeekman** [comment]
Should be good to go now

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

For future reference the preferred commit message format for new formulae is `fobis 1.7.4 (new formula)`.

**Pull request closed without merging**
