### PR TITLE
mercurial 3.7

### PR DESCRIPTION
**Pull request by ngoldbaum**

### CODE REVIEW

**Comment by apjanke** [comment]
Hmm. I'm getting a SHA mismatch on the bottle.

```
[/usr/local on ⇄ master]
$ brew pull --bottle 48752
######################################################################## 100.0%
==> Applying patch
Applying: mercurial 3.7
==> Patch closes issue #48752
Switched to a new branch 'pull-bottle-48752'
######################################################################## 100.0%
==> Applying patch
Applying: mercurial 3.7
Applying: mercurial: update 3.7 bottle.
First, rewinding head to replay your work on top of it...
Applying: mercurial: update 3.7 bottle.
Switched to branch 'master'
Updating b4097fd..6e07e8a
Fast-forward
 Library/Formula/mercurial.rb | 6 +++---
 1 file changed, 3 insertions(+), 3 deletions(-)
Deleted branch pull-bottle-48752 (was 6e07e8a).
==> Publishing on Bintray:
{"files":3}
==> Patch changed:
 Library/Formula/mercurial.rb | 10 +++++-----
 1 file changed, 5 insertions(+), 5 deletions(-)
==> Downloading https://homebrew.bintray.com/bottles/mercurial-3.7.mavericks.bot

curl: (22) The requested URL returned error: 401 Unauthorized
Error: Failed to download resource "mercurial"
Download failed: https://homebrew.bintray.com/bottles/mercurial-3.7.mavericks.bottle.tar.gz
==> That didn't work; sleeping 2 seconds and trying again...
==> Downloading https://homebrew.bintray.com/bottles/mercurial-3.7.mavericks.bot

curl: (22) The requested URL returned error: 401 Unauthorized
Error: Failed to download resource "mercurial"
Download failed: https://homebrew.bintray.com/bottles/mercurial-3.7.mavericks.bottle.tar.gz
==> That didn't work; sleeping 4 seconds and trying again...
==> Downloading https://homebrew.bintray.com/bottles/mercurial-3.7.mavericks.bot

curl: (22) The requested URL returned error: 401 Unauthorized
Error: Failed to download resource "mercurial"
Download failed: https://homebrew.bintray.com/bottles/mercurial-3.7.mavericks.bottle.tar.gz
==> That didn't work; sleeping 8 seconds and trying again...
==> Downloading https://homebrew.bintray.com/bottles/mercurial-3.7.mavericks.bottle.tar
######################################################################## 100.0%
Downloaded to: /Library/Caches/Homebrew/mercurial-3.7.mavericks.bottle.tar.gz
SHA1: 9cb06a9cfc21f1ba4501ae5662793c0cdd685fd5
SHA256: ea346bcde66d9192b13d30d471dbbbe41e628a83c5821290b8576bf2a065ad5d
Warning: Formula reports different SHA256: 29ddda0c5b7d17fa2399c68c561e5c7121c074c4eee5d3f5d26001071e1dd9a5
==> That didn't work; sleeping 16 seconds and trying again...
==> Downloading https://homebrew.bintray.com/bottles/mercurial-3.7.mavericks.bottle.tar
Already downloaded: /Library/Caches/Homebrew/mercurial-3.7.mavericks.bottle.tar.gz
SHA1: 9cb06a9cfc21f1ba4501ae5662793c0cdd685fd5
SHA256: ea346bcde66d9192b13d30d471dbbbe41e628a83c5821290b8576bf2a065ad5d
Warning: Formula reports different SHA256: 29ddda0c5b7d17fa2399c68c561e5c7121c074c4eee5d3f5d26001071e1dd9a5
==> That didn't work; sleeping 32 seconds and trying again...
```

@Homebrew/maintainers can anyone help me out here? Haven't seen this before. (BTW, do we have a GitHub label for "needs attention from another maintainer"?)

**Comment by tdsmith** [comment]
I would try deleting the bottles from bintray, re-running the bottle job, and then pulling again.

**Comment by UniqMartin** [comment]
This can happen if there are multiple PRs that update the same formula to the same version, revision, and bottle revision. It depends on the order in which they complete. The last one to succeed uploads and overwrites any preexisting bottles on Bintray. This one probably clashed with #48747.

**Comment by ngoldbaum** [comment]
Looks like @luser beat me to it. Should I just close this?

**Comment by apjanke** [comment]
Sounds like. I asked on the other PR; let's see if that was the case.

**Comment by UniqMartin** [comment]
> Sounds like. I asked on the other PR; let's see if that was the case.

@apjanke The conflict already happens when the CI finishes building and before anyone attempts to pull. If you have a look at [the Jenkins build queue](http://bot.brew.sh/job/Homebrew%20Pull%20Requests/) and filter the list for “mercurial”, you'll see three CI jobs. The 1st (job 41169) and 3rd (job 41182) belong to #48747, the 2nd (job 41175) to this PR. So the binaries on Bintray are the ones from job 41182, because that one finished last. Naturally, BrewTestBot's `pr-48752` tag still contains the hashes resulting from the job associated with this PR, so that's causing the mismatch you see during `brew pull`. (I hope I was able to explain the situation sufficiently clearly.)

**Comment by luser** [comment]
Hah, sorry! I don't care which one gets merged, as long as it gets fixed. :) I've been hitting an annoying Mercurial bug that my coworker fixed for 3.7, and I'd like to just update my Homebrew copy vs. building a one-off.

**Comment by DomT4** [comment]
Alright, merging this one :smile:.

Merged in https://github.com/Homebrew/homebrew/commit/a305ebd932afe942620601b5195d105ee7343154. Thank you for the submission in the other PR @luser and thank you for another contribution to Homebrew @ngoldbaum! :smiley_cat:

**Comment by apjanke** [comment]
@UniqMartin > The conflict already happens when...

Yep, that makes sense. I ended up getting git merge conflicts the next time I did a `brew update` from that box I did the original `brew pull` from; a few `git reset`s fixed it and all's good now. Thanks.

**Pull request closed without merging**
