### PR TITLE
macosvpn 0.1.4 (new formula)

### PR DESCRIPTION
**Pull request by MatzFan**

### CODE REVIEW

**Comment by MatzFan** [comment]
Looks like the install was ok but the test failed with a timeout. I see the test (to output the version number) was executed correctly, so might this be a Travis problem? Test ran fine (instantaneously) on my local build (OS X 10.11.3)

**Comment by DomT4** [comment]
```
==> /usr/local/Cellar/macosvpn/0.1.4/bin/macosvpn version
0.1.4
Error: macosvpn: failed
```
Doesn't look like a timeout. I suspect the executable returns a "bad" exit code on version checks. You can peek locally by doing something like:
```bash
macosvpn version
$?
```

**Comment by MatzFan** [comment]
```
$ macosvpn version
0.1.4
```
all good locally

**Comment by DomT4** [comment]
And the output of running `$?` after running `macosvpn version`?

**Comment by MatzFan** [comment]
```
$?
-bash: 98: command not found
```
Ah, I see - not being a command line king what does this do/mean & how do I fix it?!

**Comment by DomT4** [comment]
The [98](https://github.com/halo/macosvpn/blob/master/macosvpn/Classes/VPNHelp.m#L78-L86) looks to be hardcoded upstream, which is nice, because it means we can do something like:

```ruby
assert_match version.to_s, shell_output("#{bin}/macosvpn version", 98)
```
As the `test do` stage.

**Comment by MatzFan** [comment]
Got it: Most recent exit status. Will take it up with the author & see if next release can fix it.

Many thanks @DomT4

**Comment by MatzFan** [comment]
Ah, OK, shall l update the formula then?

**Comment by DomT4** [comment]
Aye. My suggestion should work, but CI will let you know one way or another :wink:

**Comment by MatzFan** [comment]
Awesome, I'll pray to the Travis Gods..

**Comment by MatzFan** [comment]
Can this be merged now? Thanks

**Comment by DomT4** [comment]
Seems alright to me; It passed CI.

Merged in https://github.com/Homebrew/homebrew/commit/a397e1107cead6b71c218170149d01beca7f9cd1. Thank you for another contribution to Homebrew @MatzFan! :smiley_cat:

**Pull request closed without merging**
