### PR TITLE
wordwarvi 1.0.2

### PR DESCRIPTION
**Pull request by jeebak**
### All Submissions:

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew/pulls) for the same update/change?

### New Formulae Submissions:

- [ ] Does your submission pass
`brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting)?

There were no offenses, but a problem was reported.

```
==> brew style wordwarvi

1 file inspected, no offenses detected

==> audit problems
wordwarvi:
 * GitHub repository not notable enough (<20 forks, <20 watchers and <50 stars)
```

- [x] Have you built your formula locally prior to submission with `brew install <formula>`?

### CODE REVIEW

**Comment by jeebak** [comment]
I just read up on the `* GitHub repository not notable enough (<20 forks, <20 watchers and <50 stars)` audit problem, and in doing so also learned of the `homebrew-games` tap. Would I be correct in guessing that this Formula would be more appropriate there?

**Comment by mikemcquaid** [comment]
Passing on this for notability reasons, sorry.

**Comment by mikemcquaid** [comment]
Please consider [creating your own tap](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-to-Create-and-Maintain-a-Tap.md) instead. Thanks!

**Comment by jeebak** [comment]
No worries. I have (re: my own tap.) This was a learning process for making a Formula, and PR for me, so thanks for that :).

**Pull request closed without merging**
