### PR TITLE
test-bot: use Ruby Macho.

### PR DESCRIPTION
**Pull request by mikemcquaid**
The new code paths have been used for the existing `otool`/`install_name_tool` for a while now without issue so let's start testing out Ruby Macho on the bot.

CC @woodruffw @UniqMartin

### CODE REVIEW

**Comment by woodruffw** [comment]
Awesome :+1:

**Comment by UniqMartin** [comment]
I guess if there needs to be a guy who always raises concerns, that guy can as well be me. :confused: 

My main concern is that the code in its current form will fail to successfully parse a wide range<sup>(1)</sup> of Mach-O files and because how the code is used in Homebrew this will make our code silently skip over Mach-O files it previously would have inspected (and acted upon). To be honest, this kind of silent failure is really troubling me even though I'm not aware of a formula that is actually affected by this.

I'm trying to work with @woodruffw in the `ruby-macho` repository to address these issues, but I wasn't able to make much progress this week because I'm not the fastest guy and, unsurprisingly, my time is limited. (Read: I'm the bottleneck.) I think by early next week (possibly sooner) I can provide you with a tool that will allow to assess the extent of “failure” that I've talked about in the above paragraph. Then you can decide for yourself whether you consider that acceptable or not. How does that sound?

----

<sup>(1)</sup>Wide range doesn't necessarily mean a significant portion of files found on a modern OS X system, particularly the stuff compiled by Homebrew that is mostly x86_64-only nowadays.

**Comment by woodruffw** [comment]
@UniqMartin's concerns are very valid.

Do we have any statistics on how many people are still on 10.6 and below? They're the ones who are most likely to be affected by current deficiencies in the parser. Until `ruby-macho` can work reliably on PPC binaries as well, it may be wise to roll it in to users on a per-version basis (i.e., 10.7 and above to minimize potential fallout).

**Comment by mikemcquaid** [comment]
> it may be wise to roll it in to users on a per-version basis (i.e., 10.7 and above to minimize potential fallout).

So, here we're not rolling it out to any users but only on our CI which will be only 10.9 and above.



> To be honest, this kind of silent failure is really troubling me even though I'm not aware of a formula that is actually affected by this.

Yeh, that seems reasonable; we should probably fail hard for now on this stuff.

**Comment by woodruffw** [comment]
> So, here we're not rolling it out to any users but only on our CI which will be only 10.9 and above.

Sorry, misread earlier. This works for me!

**Comment by UniqMartin** [comment]
> Yeh, that seems reasonable; we should probably fail hard for now on this stuff.

This is now implemented in #48817, thus I'd say this PR should be merged **only after** #48817 has been merged. One issue that remains and that *will* cause failure is PPC support. Now we're obviously not building such binaries on our bots ourselves, but at least `cmake` packages a pre-compiled fat binary (i386/PPC) that will trip up the code.

Here's something you can try (this only tests reading Mach-O files):

- Merge PR #48817 into your local working copy.
- `brew tap UniqMartin/tools`
- `unset HOMEBREW_RUBY_MACHO; brew macho-dump -w "$(brew --cellar)"`
- `export HOMEBREW_RUBY_MACHO=1; brew macho-dump -w "$(brew --cellar)"`
- (Read `brew macho-dump --help` if the output doesn't make sense.)
- Compare the output of those commands. (Note that some of the differences are caused by improperly handled edge cases in the existing `cctools`-based code, not by `ruby-macho`.)

**Comment by mikemcquaid** [comment]
@UniqMartin That sounds good; we can deal with those specific edge-cases when we hit them. Thanks!

**Comment by UniqMartin** [comment]
> That sounds good; we can deal with those specific edge-cases when we hit them.

*Lazily copied from #48817, but:* I'm a bit hesitant to pull this PR yet as it *will* break things, e.g. for the next `cmake` version bump (and the next release seems to be imminent). Would you mind waiting a bit longer until the endian-related PPC issues are sorted out in `ruby-macho`? (At least I see no simple way to temporarily disable this if we hit the mentioned issue on the bots.)

**Comment by mikemcquaid** [comment]
> I'm a bit hesitant to pull this PR yet as it will break things, e.g. for the next cmake version bump (and the next release seems to be imminent). Would you mind waiting a bit longer until the endian-related PPC issues are sorted out in ruby-macho? (At least I see no simple way to temporarily disable this if we hit the mentioned issue on the bots.)

To be a bit more explicit: does `HOMEBREW_RUBY_MACHO=1 brew install cmake` fail currently? If so: :cool: to wait, otherwise let's :ship:

**Comment by UniqMartin** [comment]
> does `HOMEBREW_RUBY_MACHO=1 brew install cmake` fail currently?

Yes, now that #48817 is merged and assuming `HOMEBREW_DEVELOPER=1` is also set, it does:

```
$ HOMEBREW_RUBY_MACHO=1 brew install cmake
[…]
==> Installing cmake
==> Downloading https://cmake.org/files/v3.4/cmake-3.4.3.tar.gz
######################################################################## 100.0%
==> ./bootstrap --prefix=/opt/brewery/tests/Cellar/cmake/3.4.3 --no-system-libs --parallel=2 --datadir=/share/cmake --do
==> make
==> make install
Error: Failed to read Mach-O binary: /opt/brewery/tests/Cellar/cmake/3.4.3/share/cmake/Modules/CPack.OSXScriptLauncher.in
Error: Unrecognized CPU type: 0x12000000
```

**Comment by mikemcquaid** [comment]
@UniqMartin Cool, thanks. Yeh, I guess it's worth fixing that case, thanks.

**Comment by woodruffw** [comment]
@UniqMartin re the PPC changes to `ruby-macho`: if you're particularly busy, I'm happy to look at your changes and begin incremental merges/work on incomplete parts.

**Comment by mikemcquaid** [comment]
Closing this out as @woodruffw can/will do it in future when it's ready.

**Pull request closed without merging**
