### PR TITLE
dnscrypt-proxy 1.4.3 modernize and add test

### PR DESCRIPTION
**Pull request by xu-cheng**

### CODE REVIEW

**Comment by DomT4** [comment]
There's a new version out we can bump to whilst here as well, the new release closes off a CVE.

**Comment by xu-cheng** [comment]
Ok, thanks for heads up.

**Comment by xu-cheng** [comment]
The test failed on mountain lion CI. Is there any unusual network setting on that machine?

**Comment by DomT4** [comment]
Don't think so. I'd presume the bots are set up relatively similarly to avoid making Mike want to destroy them every time a major update is required, heh. Mike should be able to say though.

**Comment by xu-cheng** [comment]
@mikemcquaid may need help to troubleshoot the CI problem.

**Comment by mikemcquaid** [comment]
There's nothing special going on on the 10.8 box. It's possible this tool just doesn't work there.

**Comment by DomT4** [comment]
Unless there's definite confirmation this *does* work on 10.8, I suppose we could cap it above that. At worst, someone will rush to complain and we can debug it with them and get the answer we need on how to fix the failure.

**Pull request closed without merging**
