### PR TITLE
sfk 1.7.6

### PR DESCRIPTION
**Pull request by FrankSansC**
### All Submissions:

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew/pulls) for the same update/change?

### CODE REVIEW

**Comment by FrankSansC** [comment]
Ok, I'm not quite to understand what the error is. Did I messed up somewhere?

**Comment by dunn** [comment]
Looks more like a Jenkins error; re-queuing.

**Comment by G-Square** [comment]
@dunn @FrankSansC  I had the same error "UTF-8 parsing" #50596, [CI report](http://bot.brew.sh/job/Homebrew%20Pull%20Requests/43976/) it only fails on el_capitan & yosemite. 
I updated formula from Github's web editor and it appears to have change the file type to none UTF-8 format. 

You **must** run ` brew audit sfk` to convert it to "UTF-8" then do a pull request on that. This should be documented in guidelines or better yet checked/converted on CI.

Thanks, for your contribution!

**Comment by mikemcquaid** [comment]
You can ignore this Jenkins error.

Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
