### PR TITLE
sdelta3: migrate to boneyard

### PR DESCRIPTION
**Pull request by bfontaine**
The original website doesn’t exist anymore, the download URL doesn’t work and there are no mirrors. Debian doesn’t provide any package for it, like Fedora and MacPorts.

https://github.com/Homebrew/homebrew-boneyard/pull/50

### CODE REVIEW

**Comment by mikemcquaid** [comment]
:+1:

**Comment by bfontaine** [comment]
@mikemcquaid Does `brew pull` work in taps?

**Comment by DomT4** [comment]
^ Yes.

**Comment by bfontaine** [comment]
Thanks @DomT4, we need to use the PR URL (not just its number) for taps but it works :+1:

**Pull request closed without merging**
