### PR TITLE
jfrog-cli-go

### PR DESCRIPTION
**Pull request by jainishshah17**
### All Submissions:

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew/pulls) for the same update/change?

_You can erase any parts of this template not applicable to your Pull Request._

### New Formulae Submissions:

- [x] Does your submission pass
`brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Have you built your formula locally prior to submission with `brew install <formula>`?

### Changes to Homebrew's Core:

- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your core changes, as applicable? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031) if you'd like one.
- [x] Have you successfully ran `brew tests` with your changes locally?

New Formula for Jfrog-Cli-Go. A command line interface for Jfrog Products Artifactory and Bintray.

### CODE REVIEW

**Comment by jainishshah17** [comment]
Version 1.0.1 for Jfrog-cli-go

**Comment by apjanke** [comment]
Something a bit weird is going on with the test here. I noticed you put in an amendment to expect an empty output from `jfrog rt config show` instead of the normal output.

It looks like the sandbox is causing `jfrog rt config` to not store its settings. When I run the test steps as a normal user, or do `brew test --debug jfrog-cli-go`, which disables the sandbox, then I get an output with url, user, and password.

```
$ brew test --debug jfrog-cli-go
/usr/local/Library/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Formula/jfrog-cli-go.rb
Testing jfrog-cli-go
Warning: The sandbox cannot be used in debug or interactive mode.
/usr/local/Library/Homebrew/test.rb (Formulary::FromPathLoader): loading /usr/local/Library/Formula/jfrog-cli-go.rb
==> /usr/local/Cellar/jfrog-cli-go/1.0.1/bin/jfrog rt config --interactive=false --enc-p
==> /usr/local/Cellar/jfrog-cli-go/1.0.1/bin/jfrog rt config show
/usr/local/Library/Homebrew/debrew.rb:11:in `raise'
MiniTest::Assertion: <""> expected but was
<"Url: \"http://loaclhost:8081/artifactory\" --user=\"admin\" --password=\"password\"/\n">.
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action: 5
When you exit this shell, you will return to the menu.
spiffy% jfrog rt config show
Url: "http://loaclhost:8081/artifactory" --user="admin" --password="password"/
spiffy%
```

Let's see if we can figure out what's going on here.

It looks like maybe it's ignoring `$HOME` and locating the user's home directory, and thus the `~/.jfrog` config directory, through other means.

```
spiffy% pwd
/private/tmp/jfrog-cli-go20160316-19343-1inkrru
spiffy% echo $HOME
/private/tmp/jfrog-cli-go20160316-19343-1inkrru
spiffy% ls -a
.       ..      .zshrc  Library
spiffy% ls -a /Users/janke/.jfrog
.              ..             jfrog-cli.conf
spiffy%
```

**Comment by apjanke** [comment]
Ah, here, in [`jfrog-cli-go`'s `ioutils.go`](https://github.com/JFrogDev/jfrog-cli-go/blob/d2a9bffd5f22fdde88f236bc61c5fbb1341786bd/cliutils/ioutils.go#L352-L362):

```
func GetHomeDir() string {
	user, err := user.Current()
	if err == nil {
		return user.HomeDir
	}
	home := os.Getenv("HOME")
	if home != "" {
		return home
	}
	return ""
}
```

It's using Go's `user.Current()` lookup before using `$HOME`. The [user.Current() function](https://golang.org/pkg/os/user/#Current) doesn't say exactly how it looks up the user, but probably makes a system call to `getpwent` or some OS equivalent.

So I think it's still trying to write the config to your actual home directory instead of the `$HOME` set up by the test sandbox, which is prohibited under sandboxing and results in an empty config, which is then read back.

I'm not sure how we handle this situation in Homebrew. Doesn't look like there's any other configuration variable we can use to repoint `jfrog-cli-go`'s configuration dir.

**Comment by jainishshah17** [comment]
@apjanke: I have updated Test please check.

**Comment by apjanke** [comment]
Looks good now. Normally we like to test at least some functionality beyond just getting the version, but since this is incompatible with the sandbox due to that home directory detection stuff, this is fine.

Merged. Thank you for your contribution to Homebrew!

**Comment by apjanke** [comment]
Merged in bc21be78e6feefcad99cad5a2a7f4eb86dbf111c. Closing manually since the auto-close didn't seem to work.

**Pull request closed without merging**
