### PR TITLE
mvnvm: set JAVA_HOME in the script

### PR DESCRIPTION
**Pull request by xu-cheng**

### CODE REVIEW

**Comment by furgin** [comment]
This changed has broken mvnvn in the case where I have set JAVA_HOME to use a different java besides the default.   The resulting script sets JAVA_HOME even if its already set.   I will put together a PR

**Comment by xu-cheng** [comment]
Ping @mikemcquaid for comments.

There's an easy way to let users set their own JAVA_HOME. The fix is as follow:
```ruby
def self.java_home_env(version=nil)
  version_flag = " --version #{version}" if version
  java_home = "$(/usr/libexec/java_home#{version_flag})"
  { :JAVA_HOME => "$(if [ -z $JAVA_HOME ]; then echo #{java_home}; else echo $JAVA_HOME; fi)" }
end
```

However, the question is whether we should support such feature. On the one hand, users may set JAVA_HOME incorrectly. On the other hand, the original design allows formula choose JVM based on version. While users' custom JAVA_HOME will overwrite all, if we introduce such feature.

@furgin It's very unusual that you need a different JVM other than the result of `/usr/libexec/java_home`. Can you be more specific about your needs? Why do you want a different JAVA_HOME?

**Comment by mikemcquaid** [comment]
I think with any such changes we'll need more than one user to request it before making changes. It's better for us to avoid things such as e.g. users setting a wrong/invalid JAVA_HOME, as you point out @xu-cheng.

**Comment by furgin** [comment]
@mikemcquaid We have a complex set of libraries that have been developed independently over the last few years and therefore have different requirements for things like maven versions and java, building with the right versions become important.  I need a way to set which version of java to use, I don't change it often but need to often enough to want to keep them both installed.  If there is another way to tell ```/usr/libexec/java_home``` which java version to use, I'd happily use that.  The only way that I know to switch is to use JAVA_HOME.  Overwriting it when starting mvnvm breaks that pattern.

**Comment by mikemcquaid** [comment]
Just so I understand: why does the version used to start `mvnvm` affect what version you build with?

**Comment by xu-cheng** [comment]
@furgin `/usr/libexec/java_home` can return JVM with specific version. Namely `/usr/libexec/java_home --version <version>`. c.f. [java_home manual](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/java_home.1.html)

**Comment by furgin** [comment]
@mikemcquaid the version of java that starts mvn is used to compile the code that maven is managing.  Most people who are using mvnvm are not getting this problem (yet) because they had already installed 1.0.3 before this change was made.  The people who reinstalled it or only recently upgraded have reported the problem to me (through mvnvm).

@xu-cheng the if statement protecting updates JAVA_HOME if its already set would be perfect for us.

**Comment by PatrickRoumanoff** [comment]
The use case is  straight forward. I build lots of projects which require lots of different java version.
I understand it is useful to provide a default if no JAVA_HOME is already present, but overriding a provided one just breaks mvnvm for me - or anyone who want to control which java version is used to run maven.
I have currently 4 jvm installed (6,7,8 and 9) and I want to be able to choose which one to use to run my builds independently from which one is the default.

**Comment by tdsmith** [comment]
If mvnvm does a reasonable thing in the absence of JAVA_HOME I think it makes sense to revert this to avoid freezing JAVA_HOME at install time when choosing a Java VM at runtime is desirable. Does it make more sense to add doctor checks for broken JAVA_HOMEs instead?

**Comment by xu-cheng** [comment]
@tdsmith if we want to support custom JAVA_HOME, we don't need to revert this. We can either update `Language::Java.java_home_env` to the version I mentioned above. Or we can add new argument to disable override.

**Comment by tdsmith** [comment]
Oh, I see now; thanks.

**Comment by furgin** [comment]
I created a PR to add the guard around the JAVA_HOME setting.

**Comment by mikemcquaid** [comment]
@xu-cheng Just so I understand: what was the motivation for the original change? If `mvnvm` doesn't require `JAVA_HOME` to be set at runtime I don't think we should be setting it at all. We should save the `bin.env_script_...` approach for things where we're instructing users that they _need_ to set `JAVA_HOME` (or similar) for the application to work. The original use-case was e.g. `ansible.rb` where you had to set `PYTHONPATH` for it to find the libraries at all.

**Comment by xu-cheng** [comment]
@mikemcquaid `mvnvm` does require JAVA_HOME at runtime, as you can see from the original test in this very PR. 

The motivation is to set JAVA_HOME for users rather than ask them to do so in the caveats. Moreover, there're formulae requiring different version Java in runtime. `Language::Java.java_home_env` can be helpful in this case.

**Comment by mikemcquaid** [comment]
@xu-cheng Sorry, misread the first case, got it now. I'm hesistant to let every formulae override `JAVA_HOME` but in this case I can see how it's useful. Perhaps we add a `overridable_java_home_env` function that we use in these cases?

**Comment by xu-cheng** [comment]
:+1: for overriable function.

**Pull request closed without merging**
