### PR TITLE
Added SwiftLint

### PR DESCRIPTION
**Pull request by jpsim**
First version. Based on `sourcekitten.rb`.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Passing on this; a self-submission of a 2-day old project. I recommend running your own tap in the mean-time. Sorry!

**Comment by jpsim** [comment]
That's unfortunate.

Is it Homebrew policy to only accept either 1) older projects, 2) projects that have gained a certain level of popularity or 3) projects submitted by non-authors? I'm just trying to understand the rationale there.

When *would* it be appropriate to submit this to Homebrew's main tap? Should I avoid personally submitting this in the future?

Thanks. Again, I'm just trying to understand the rationale.

**Comment by DomT4** [comment]
It's usually both 2 & 3. If a project is new but enjoys rampaging popularity it'll probably be accepted. Likewise it being submitted by a non-author helps show interest is a little more broad. [There's some documentation here](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Acceptable-Formulae.md#niche-or-self-submitted-stuff). The recommendation is usually to set up your own tap for the project for a while.

**Comment by danilobuerger** [comment]
:+1: for integrating, great project.

**Comment by beanieboi** [comment]
:+1:

**Comment by mikemcquaid** [comment]
Will leave this open for a wee while to see how the project goes in the next few weeks.

**Comment by mattdelves** [comment]
:+1: this is amazing

**Comment by Hs-Yeah** [comment]
+1

**Comment by jpsim** [comment]
Thanks for clarifying @DomT4, it makes total sense, but came as a bit of a surprise.

I'll point people to the .pkg installer rather than host a custom tap to avoid an eventual migration to the main tap.

Thanks for keeping this open, @mikemcquaid.

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

For future reference the preferred commit message format for new formulae is `swiftlint 0.1.0 (new formula)`.

**Comment by jpsim** [comment]
Thanks for merging, and for the tips, @mikemcquaid!

**Pull request closed without merging**
