### PR TITLE
latexmk 4.43a (new formula)

### PR DESCRIPTION
**Pull request by herrbischoff**
Very useful (and required) for `vimtex` for example.

### CODE REVIEW

**Comment by ilovezfs** [comment]
The installation is incomplete. There is also a man page and example rc files to be installed.

You may want to consider adding (or abbreviating) as a caveat what is mentioned in the INSTALL file specifically about OS X:

> You may also want to change the defaults on what kinds of output file latexmk makes.  By default latexmk makes dvi files, but not postscript or pdf files.  If you (or people on your system) generally make pdf files using pdflatex, it would be a good idea to put the following in an appropriate initialization file:
```
            $pdf_mode = 1;
            $postscript_mode = 0;
            $dvi_mode = 0;
```
This change is particularly useful for Mac OS-X.  See step 6 for the locations of the initialization/configuration files (under UNIX-like systems), where you should put this lines.

**Comment by DomT4** [comment]
It's also in the wrong tap. Formulae that have a hard TeX dependency go in the TeX tap. There's a very similarly named formula there [already](https://github.com/Homebrew/homebrew-tex/blob/master/Formula/latex-mk.rb) but it looks like they may be different projects. Please resubmit this to that tap as desired, Thank you!

**Comment by herrbischoff** [comment]
Thanks for the comments. I probably overlooked this due to the fact that I used it in combination with `vimtex`, which works like a charm. I will fix and resubmit to the TeX tap.

**Comment by herrbischoff** [comment]
@ilovezfs What is the preferred location and/or process to add example rc files? I couldn't find a recipe with this workflow.

**Comment by ilovezfs** [comment]
Here are some I have installed by formulae
```
-rw-r--r--  1 joe  admin  3643 Apr 19  2015 ./Cellar/dar/2.4.17/etc/darrc
-rw-r--r--  1 joe  admin  1487 Apr 19  2015 ./Cellar/dar/2.4.17/share/dar/samples/JH_darrc
-rw-r--r--  1 joe  admin  1622 Feb 13 21:30 ./Cellar/gettext/0.19.7/share/gettext/intl/libintl.rc
-rw-r--r--  1 joe  admin  817 Sep 11  2014 ./Cellar/libmagic/5.25/share/misc/magic/sharc
-rw-r--r--  1 joe  admin  595 Sep 11  2014 ./Cellar/libmagic/5.25/share/misc/magic/warc
-r--r--r--  1 joe  admin  5972 Feb  3 13:59 ./Cellar/mercurial/3.7.1/lib/python2.7/site-packages/mercurial/default.d/mergetools.rc
lrwxr-xr-x  1 joe  admin  30 Feb 10 01:23 ./etc/darrc -> ../Cellar/dar/2.4.17/etc/darrc
-rw-r--r--  1 joe  admin  4944 Jul  5  2014 ./etc/mercurial/hgrc.d/mergetools.rc
-rw-r--r--  1 joe  admin  4815 Dec 20  2014 ./etc/wgetrc
lrwxr-xr-x  1 joe  admin  99 Feb  6 22:32 ./lib/python2.7/site-packages/mercurial/default.d/mergetools.rc -> ../../../../../Cellar/mercurial/3.7.1/lib/python2.7/site-packages/mercurial/default.d/mergetools.rc

```

**Comment by herrbischoff** [comment]
@ilovezfs Thanks, I'm going to check those out. Just out of curiosity: what would be the approach for dotfiles, rc files in the user home?

**Comment by ilovezfs** [comment]
You can copy values directly into your .bash_profile, or source entire files.

So ~/.bash_profile might have a line like this: 
```
source ~/.my_special_commands_settings.rc
```
or equivalently
```
. ~/.my_special_commands_settings.rc
```

If the file is one from brew, unless the path is already compiled into the program, you could
```
source "$(brew --prefix)"/etc/my_special_brew_commands_settings.rc
```
or
```
ln -s "$(brew --prefix)"/etc/my_special_brew_commands_settings.rc ~/.my_special_brew_commands_settings.rc
```
and then in .bash_profile
```
source ~/.my_special_brew_commands_settings.rc
```

**Pull request closed without merging**
