### PR TITLE
puddletag 1.0.5 (new formula)

### PR DESCRIPTION
**Pull request by chincheta0815**
Powerful, simple, audio tag editor.
(Deleted old pull request and reopened it with "depends_on :python if MacOS.version <= :snow_leopard", was comment by mikemcquaid).
Sorry for the confusion. git sometimes confuses me.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
@chincheta0815 Please just force-push this change to the last pull request, thanks.

**Comment by chincheta0815** [comment]
@mikemcquaid: Due to some misunderstanding by me, I closed the old pull request (#43632) and deleted the fork in my repo. Now I readded the pull request under this number with the changes asked by you before. I was thinking a new formula request has to contain just one commit. So I messed up my local repos which resulted in deleting them would be the easiest solution... Is it okay to leave it as it is, please? I promise to get better.

**Comment by mikemcquaid** [comment]
Yeh, ok, no worries. For future reference you probably want to create off a non-`master` branch (but you can leave it as-is now)

**Comment by chincheta0815** [comment]
Thanks a lot!

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
