### PR TITLE
lua 5.3.2

### PR DESCRIPTION
**Pull request by bfontaine**

### CODE REVIEW

**Comment by DomT4** [comment]
I do think it's worth not doing this yet. There's still an awful awful lot of incompatibility with Lua 5.3 in the wild, particularly with Luarocks packages, etc. I'd prefer to keep us on 5.2 in the core for a little while longer yet, personally.

**Comment by bfontaine** [comment]
Got it @DomT4 :smile:

**Comment by DomT4** [comment]
If people are super-keen to help upstreams migrate to the new Lua there's a package in Versions :smile:

**Comment by daurnimator** [comment]
> If people are super-keen to help upstreams migrate to the new Lua there's a package in Versions :smile:
 
What upstreams aren't lua 5.3 compatible?
I can't think of any lua projects that work with 5.2 but not 5.3. (usually they're either stuck back on 5.1 or on 5.3 already)

**Comment by DomT4** [comment]
> What upstreams aren't lua 5.3 compatible?

Almost _all_ of them, at last check. Locally check out a branch, then upgrade your `lua` formula to match the `lua53` one in Versions, then do:
```
brew upgrade lua -s
```
Then do things like:
```
brew install gnuplot -s
brew install highlight -s
```
And so on and you'll discover a bunch of stuff that just refuses to compile against it. Although upstreams in general may have started to move towards it, that's not a guarantee those are necessarily in released versions yet sadly.

**Comment by daurnimator** [comment]
> Almost all of them, at last check. Locally check out a branch, then upgrade your lua formula to match the lua53 one in Versions, then ............

I tried doing that; but installing gnuplot just brought in lua 5.2 again. I really don't know how brew works here.

> you'll discover a bunch of stuff that just refuses to compile against it.

Did you compile lua 5.3 with `-DLUA_COMPAT_5_2 -DLUA_COMPAT_5_1` for maximum compatibility?

**Pull request closed without merging**
