### PR TITLE
ec2-api-tools: depend on java

### PR DESCRIPTION
**Pull request by vszakats**

### CODE REVIEW

**Comment by vszakats** [comment]
```
/usr/local/Cellar/ec2-api-tools/1.7.3.0/libexec/bin/ec2-cmd: line 18: JAVA_HOME: JAVA_HOME is not set
Error: ec2-api-tools: failed
```

**Comment by vszakats** [comment]
Whilst the same update works for `ec2-ami-tools`, here: http://bot.brew.sh/job/Homebrew%20Pull%20Requests/21954/

**Comment by xu-cheng** [comment]
`depends_on :java` only sets JAVA_HOME in superenv. So `ENV["JAVA_HOME"]` only presents in `install` not the `test`. I suggest you overwrite the `install` part to install the binary into `libexec/"bin"`. Then call thing like this: `(bin/"<binary>").write_env_script libexec/"bin/<binary>", :JAVA_HOME => ENV["JAVA_HOME"`

**Comment by xu-cheng** [comment]
I'm not familiar to `AmazonWebServicesFormula`. If all of them are java formula, I would suggest to rewrite `AmazonWebServicesFormula` itself. Ping @Homebrew/owners.

**Comment by vszakats** [comment]
Thanks a lot. Though, I don't feel confident to make such an update, so I'd prefer closing this and watch the exact pattern from an expert. (I've seen lots of mentions of "libexec", but so far couldn't figure what it means.)

What is unclear is why the other very similar formula works OK after this exact patch (test included).

**Comment by vszakats** [comment]
Plus, the intent of this patch was to make the formula simpler. After all these updates, it would be much more complex :)

**Comment by xu-cheng** [comment]
> I've seen lots of mentions of "libexec", but so far couldn't figure what it means.

`libexec` is the folder to `/usr/local/Cellar/<formula>/<version>/libexec` 

> What is unclear is why the other very similar formula works OK after this exact patch (test included).

Some of them require JAVA_HOME set while others don't.

**Comment by vszakats** [comment]
Hmm, you must be right, even though I specifically had to add the `JAVA_HOME` envvar just recently to make the tests run. Maybe it was overdone, I'll make a test.

**Comment by vszakats** [comment]
I'll look into `libexec`, too.

**Comment by vszakats** [comment]
`libexec`: I now understand the purpose. Thanks!

**Comment by vszakats** [comment]
Sorry for pushing this further, but: After https://github.com/Homebrew/homebrew/commit/62ff66cb21a6937f47ab475c823bb087523081b0, this formula doesn't pass strict audit due to the error:
```
==> audit problems
ec2-api-tools:
 * Use `depends_on :java` to set JAVA_HOME

Error: 1 problems in 1 formulae
```

To fix this, it appears the above suggested update is not enough and things need to be made more complicated than before, to comply.

Would it be possible to extend the logic to set `JAVA_HOME` for `test`, too?
Or, would it be possible to avoid this audit error if `JAVA_HOME` is referenced in `test` only?

**Comment by xu-cheng** [comment]
https://github.com/Homebrew/homebrew/commit/62ff66cb21a6937f47ab475c823bb087523081b0 only complains if `depends_on :java` is missing. Using JAVA_HOME on test doesn't affect this.

**Comment by vszakats** [comment]
Okay, I'll make updates accordingly.

**Comment by vszakats** [comment]
Depend on java, and kept `JAVA_HOME` in test.

**Comment by xu-cheng** [comment]
Close this as I will do some major change on `AmazonWebServicesFormula` in #37192.

Thanks for contribution @vszakats.

**Pull request closed without merging**
