### PR TITLE
babl 0.1.16

### PR DESCRIPTION
**Pull request by fbrosson**

### CODE REVIEW

**Comment by fbrosson** [comment]
Curious about whether or not the changes in **`babl-cpuaccel.c`** could allow us to drop the following warning in  **`def install`** ?
```Ruby
    if build.universal?
      ENV.universal_binary
      opoo "Compilation may fail at babl-cpuaccel.c using gcc for a universal build" if ENV.compiler == :gcc
    end
```
Well, I don't think so, but please correct me if you think we should drop the **`opoo`** warning.
```Diff
diff -up babl-0.1.14/babl/babl-cpuaccel.c babl-0.1.16/babl/babl-cpuaccel.c
--- babl-0.1.14/babl/babl-cpuaccel.c	2015-08-31 07:30:17.000000000 +0000
+++ babl-0.1.16/babl/babl-cpuaccel.c	2016-01-08 02:07:19.000000000 +0000
@@ -114,7 +114,12 @@ enum
 
 enum
 {
-  ARCH_X86_INTEL_FEATURE_PNI      = 1 << 0
+  ARCH_X86_INTEL_FEATURE_PNI      = 1 << 0,
+  ARCH_X86_INTEL_FEATURE_SSSE3    = 1 << 9,
+  ARCH_X86_INTEL_FEATURE_SSE4_1   = 1 << 19,
+  ARCH_X86_INTEL_FEATURE_SSE4_2   = 1 << 20,
+  ARCH_X86_INTEL_FEATURE_AVX      = 1 << 28,
+  ARCH_X86_INTEL_FEATURE_F16C     = 1 << 29,
 };
 
 #if !defined(ARCH_X86_64) && (defined(PIC) || defined(__PIC__))
@@ -234,6 +239,15 @@ arch_accel_intel (void)
 
     if (ecx & ARCH_X86_INTEL_FEATURE_PNI)
       caps |= BABL_CPU_ACCEL_X86_SSE3;
+
+    if (ecx & ARCH_X86_INTEL_FEATURE_SSSE3)
+      caps |= BABL_CPU_ACCEL_X86_SSSE3;
+
+    if (ecx & ARCH_X86_INTEL_FEATURE_SSE4_1)
+      caps |= BABL_CPU_ACCEL_X86_SSE4_1;
+
+    if (ecx & ARCH_X86_INTEL_FEATURE_F16C)
+      caps |= BABL_CPU_ACCEL_X86_F16C;
 #endif /* USE_SSE */
   }
 #endif /* USE_MMX */
@@ -399,7 +413,11 @@ arch_accel (void)
 
 #ifdef USE_SSE
   if ((caps & BABL_CPU_ACCEL_X86_SSE) && !arch_accel_sse_os_support ())
-    caps &= ~(BABL_CPU_ACCEL_X86_SSE | BABL_CPU_ACCEL_X86_SSE2);
+    caps &= ~(BABL_CPU_ACCEL_X86_SSE   |
+              BABL_CPU_ACCEL_X86_SSE2  |
+              BABL_CPU_ACCEL_X86_SSE3  |
+              BABL_CPU_ACCEL_X86_SSSE3 |
+              BABL_CPU_ACCEL_X86_SSE4_1);
 #endif
 
   return caps;
```

**Comment by tdsmith** [comment]
Does it work?

**Comment by tdsmith** [comment]
(where "it" means "building a universal build with gcc")

**Comment by fbrosson** [comment]
Short answer: universal builds (of babl) with gcc probably do not work with the standard method.
Long answer:
Sorry for the delay. The only Mac where I have gcc is a powerpc-based machine running Leopard, so I cannot test building babl with gcc+Homebrew. And the only recent Mac I have access to is a remote machine running El Capitan and which does not have gcc installed (and I don't have permission to install it there).
I was able, however, to build a stand-alone babl for a single arch (`-arch ppc`) with gcc 4.0.1 (`powerpc-apple-darwin9-gcc-4.0.1 (GCC) 4.0.1 (Apple Inc. build 5490)`) on my Mac.
But if I try to do a universal build by specifing more than one architecture (e.g. with `-arch ppc -arch i386`), then the build fails because `CPP = gcc -std=gnu99 -E` and `LDFLAGS = -arch ppc -arch i386` get written to babl/base/Makefile and then produce the following error:
```
gcc-4.0: -E, -S, -save-temps and -M options are not allowed with multiple -arch flags
```

I know we could still create a universal build with gcc by compiling for each arch and then merging the libs with lipo, but I don't think that would make sense because clang is already able to create universal builds of babl without the need to make separate builds for each arch.

Hence this question: Should I remove the `opoo` warning and place the following line (or anything more apropriate) just below the `bottle do` block ?
```Ruby
fails_with :gcc if build.universal? # Compilation fails for universal builds when ENV.compiler == :gcc
``` 
BTW, is this the correct syntax and way to handle this problem? Thanks!

**Comment by tdsmith** [comment]
Thanks for checking! I made the change you suggested and pulled this; it looks like this: https://github.com/Homebrew/homebrew/commit/a7973103b57c6eedd16c434b715e63125bb1d07c#diff-75401701cf73703c8be788acc1d4aa83R27

**Pull request closed without merging**
