### PR TITLE
llvm 3.6.0

### PR DESCRIPTION
**Pull request by DomT4**
New LLVM release.

### CODE REVIEW

**Comment by jacknagel** [comment]
Looks like this needs some accompanying revision bumps.

**Comment by DomT4** [comment]
Ah, should have seen that coming. Will bump a few of the failing things now.

**Comment by DomT4** [comment]
The ` kubernetes-cli ` failure was unrelated. For some reason, the bot tagged that build failure as an ` llvm ` failure, despite not actually having built LLVM on Yosemite yet. Hmm. Will revision ` Pure ` though, as that broke on the other two bots.

**Comment by DomT4** [comment]
Rats. ` Pure ` fails to compile against the new LLVM. Will go a-hunting for an upstream bug reporter.

**Comment by alexchandel** [comment]
Does LLD build in 3.6 stable yet? Because as of last week the LLD head (leading into 3.6) was failing to build in homebrew. I opened an issue but it was hastily closed.

**Comment by Noctem** [comment]
@alexchandel LLD fails to build for me on Yosemite at least.

**Comment by Noctem** [comment]
Homebrew doesn't seem to accept forcing using this through `HOMEBREW_CC` or `HOMEBREW_CXX`, is there any reason that support for that can't or shouldn't be added?

**Comment by DomT4** [comment]
> Does LLD build in 3.6 stable yet? Because as of last week the LLD head (leading into 3.6) was failing to build in homebrew.

There's LLVM36 in Homebrew/Versions already, if you feel like doing some testing.

> Edit - Someone beat me to it.

No activity in this bug report yet, and no activity in that repo at all for ~3 months. Sadly LLVM is probably a little huge and complicated to vendor inside the ` pure ` formula, so I guess we're on a hold here for now.

**Comment by mikemcquaid** [comment]
@DomT4 Any movement here? Just #39192 is depending on it. If we have to remove Pure for this: so bet it.

**Comment by DomT4** [comment]
None at all. Has been reported upstream at Pure for the last 2 months, with no movement or reply at all. There hasn't actually been a single commit made to the Pure codebase since the end of 2014. Do you want Pure boneyarded, left broken or vendor the old LLVM into Pure?

**Comment by mikemcquaid** [comment]
Sounds like boneyard time.

**Comment by DomT4** [comment]
Done. Rebased, changed SHA1 to SHA256, PRs pending here and in the Boneyard for ` pure `.

**Comment by DomT4** [comment]
Rats, ` creduce ` is failing now. Sigh.

**Comment by tamird** [comment]
@DomT4 I filed ^ upstream. Probably boneyard for now?

**Comment by DomT4** [comment]
Upstream committed some fixes to the master branch. They've asked you to confirm the fixes work. Guess they might be willing to do a release if it does, hopefully.

**Comment by tamird** [comment]
Waiting on upstream to cut a release.

**Comment by tamird** [comment]
@DomT4 upstream has released a new version! https://github.com/csmith-project/creduce/releases/tag/creduce-2.3.0 will need to be updated in lockstep with LLVM in this PR because 2.3 doesn't support LLVM 3.5

**Comment by DomT4** [comment]
I'm not sure how well the test-bot is going to cope with `creduce`'s special dependency if done in this PR. It'll build LLVM in a normal vanilla configuration, but `creduce` requires LLVM built `with-clang`. I'll give it a go though and see what happens.

**Comment by DomT4** [comment]
Thanks for getting upstream to cut the new release by the way! May finally be able to get this done :smile_cat:.

**Comment by DomT4** [comment]
Colour my concerns wrong, It actually passed the bot, finally :cake:.

**Comment by tamird** [comment]
:confetti_ball:

**Comment by sblessing** [comment]
Hey guys, this formula actually has some issues. #39609

**Pull request closed without merging**
