### PR TITLE
Add youtube-dl-parallel.

### PR DESCRIPTION
**Pull request by simono**
A small utility program to spawn a number of youtube-dl processes in
parallel

### CODE REVIEW

**Comment by simono** [comment]
I couldn't figure out a useful test block for this formula, because it's just a wrapper around two tools.

And although it may not have many stars, I think it's still useful.

**Comment by bfontaine** [comment]
@BrewTestBot test this please.

**Comment by dunn** [comment]
```
==> audit problems
youtube-dl-parallel:
 * A `test do` test block should be added
 * GitHub repository not notable enough (<10 forks, <10 watchers and <20 stars)
```
It might be a little young for us.  We want to make sure a package is popular enough to support continued development before taking on the work of supporting a formula for it.

**Comment by mikemcquaid** [comment]
Passing on this for now, sorry!

**Comment by simono** [comment]
Ok, thanks.

If anybody else is interested, I added youtube-dl-parallel to simono/homebrew-simono

**Pull request closed without merging**
