### PR TITLE
gptfdisk: boneyard

### PR DESCRIPTION
**Pull request by dunn**
See #46378 and https://github.com/Homebrew/homebrew-boneyard/pull/76.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
:+1:

**Comment by ilovezfs** [comment]
I don't think this makes sense despite what the homepage says. It still works fine on El Capitan with SIP enabled. Can we please put it back?

**Comment by ilovezfs** [comment]
@mikemcquaid 

Here's a demo:
```
ilovezfss-Mac:~ ilovezfs$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.11.1
BuildVersion:	15B42
bash-3.2$ csrutil status
System Integrity Protection status: enabled.
bash-3.2$ sudo touch /usr/sbin/SIP_is_on
touch: /usr/sbin/SIP_is_on: Operation not permitted
bash-3.2$ diskutil list disk0 | grep disk0s1
   1:                  Apple_HFS                         5.4 GB     disk0s1
bash-3.2$ sudo sgdisk -t 1:0700 /dev/disk0
Warning: The kernel may continue to use old or deleted partitions.
You should reboot or remove the drive.
The operation has completed successfully.
bash-3.2$ diskutil list disk0 | grep disk0s1
   1:       Microsoft Basic Data                         5.4 GB     disk0s1
bash-3.2$ diskutil unmountDisk disk0
Unmount of all volumes on disk0 was successful
bash-3.2$ sudo sgdisk -Z /dev/disk0
Warning: The kernel may continue to use old or deleted partitions.
You should reboot or remove the drive.
GPT data structures destroyed! You may now partition the disk using fdisk or
other utilities.
bash-3.2$ diskutil list disk0 | grep disk0s1
bash-3.2$ diskutil info /|grep Node
   Device Node:              /dev/disk2s2
bash-3.2$ diskutil list disk2 | grep disk2s2
   2:                  Apple_HFS El Capitan HD           63.6 GB    disk2s2
bash-3.2$ sudo sgdisk -t 2:0700 /dev/disk2
Warning: Devices opened with shared lock will not have their
partition table automatically reloaded!
Warning: Devices opened with shared lock will not have their
partition table automatically reloaded!
Unable to open device '/dev/disk2' for writing! Errno is 1! Aborting write!
bash-3.2$ diskutil list disk2 | grep Recovery
   3:                 Apple_Boot Recovery HD             650.0 MB   disk2s3
bash-3.2$ sudo sgdisk -t 3:0700 /dev/disk2
Warning: Devices opened with shared lock will not have their
partition table automatically reloaded!
Warning: Devices opened with shared lock will not have their
partition table automatically reloaded!
Unable to open device '/dev/disk2' for writing! Errno is 1! Aborting write!
```
Notice that Apple's /usr/sbin/gpt has the exact same limitation with respect to disk2 (system disk) and only disk2 when is SIP is enabled.
 ```
bash-3.2$ sudo gpt -r show /dev/disk0
     start      size  index  contents
         0  10485760         
bash-3.2$ sudo gpt create /dev/disk0
bash-3.2$ sudo gpt add -i 1 -t 48465300-0000-11AA-AA11-00306543ECAC /dev/disk0
/dev/disk0s1 added
bash-3.2$ diskutil list disk0 | grep disk0s1
   1:                  Apple_HFS                         5.4 GB     disk0s1
bash-3.2$ sudo gpt remove -i 1 /dev/disk0
/dev/disk0s1 removed
bash-3.2$ sudo gpt add -i 1 -t windows /dev/disk0
/dev/disk0s1 added
bash-3.2$ diskutil list disk0 | grep disk0s1
   1:       Microsoft Basic Data                         5.4 GB     disk0s1
bash-3.2$ sudo gpt -r show disk2
      start       size  index  contents
          0          1         PMBR
          1          1         Pri GPT header
          2         32         Pri GPT table
         34          6         
         40     409600      1  GPT part - C12A7328-F81F-11D2-BA4B-00A0C93EC93B
     409640  124149904      2  GPT part - 48465300-0000-11AA-AA11-00306543ECAC
  124559544    1269536      3  GPT part - 426F6F74-0000-11AA-AA11-00306543ECAC
  125829080          7         
  125829087         32         Sec GPT table
  125829119          1         Sec GPT header
bash-3.2$ sudo gpt remove -i 3 /dev/disk2
gpt remove: unable to open device '/dev/disk2': Operation not permitted
bash-3.2$ 
```

**Comment by vitorgalvao** [comment]
Just so we’re on the same page, @ilovezfs [asked for this on homebrew-cask](https://github.com/caskroom/homebrew-cask/issues/15476) since you removed it here (we’re still pondering it).

Would I be right in assuming that if @ilovezfs can contact the developer and prove this does work in El Capitan and subsequently have them remove the message saying it doesn’t work, that you’d then readd this formula?

**Comment by ilovezfs** [comment]
Yes, I can contact upstream about this, but the empirical evidence that it does indeed work with SIP on is readily available to anyone who cares to test it.

**Comment by vitorgalvao** [comment]
> Yes, I can contact upstream about this, but the empirical evidence that it does indeed work with SIP on is readily available to anyone who cares to test it.

I currently do not have the availability to do it, and perhaps neither does anyone in homebrew’s team. Also, that is looking at it in the wrong way. If that is fixed upstream *everyone benefits*: users of homebrew (they get the formula), users who do not use homebrew (they won’t be put off by the message, the developer (learns something), not to mention it will continue to be developed (which will not happen currently if the developers think it cannot work).

So many times people ask us (in homebrew-cask, but perhaps in homebrew as well) to make workarounds for stuff that should be really fixed upstream. I’ll say it again: **that is the wrong way to go about it**. We should fix the issue at the source, where it’ll benefit more people and trickle down, not put a band-aid where it’s convenient; that should only be a last resort.

**Comment by dunn** [comment]
> Would I be right in assuming that if @ilovezfs can contact the developer and prove this does indeed work in El Capitan and subsequently have them remove the message saying it doesn’t work, that you’d then readd this formula?

Fine with me.

While you're at it, it'd be nice to let the developer know that `Makefile.mac` is looking for ncurses in a non-standard location: https://github.com/Homebrew/homebrew/pull/46378#discussion_r45946670

**Comment by ilovezfs** [comment]
@dunn @vitorgalvao @mikemcquaid New language added to the homepage by the upstream developer as a result of our correspondence: "Specifically, low-level access to the system disk is forbidden, so you cannot repartition it. Access to USB flash drives remains possible, though."

His response below:

>On Dec 30, 2015, at 08:09 PM, Rod Smith <rodsmith@rodsbooks.com> wrote:

>>On 12/30/2015 10:26 PM, ilove zfs wrote:
>>>Hi Rod,

>>>The Homebrew developers asked that I contact you about this. I'm
not sure if you're aware that as of November 26, gptfdisk was moved from
the main Homebrew repository to the Homebrew boneyard repository.

>>I've updated the wording of my notice to reflect my current
understanding of the issue:

>>http://www.rodsbooks.com/gdisk/
>>http://www.rodsbooks.com/gdisk/walkthrough.html

No word yet about the ncurses path problem.

**Comment by dunn** [comment]
Thanks! If you can get Rod to accept a patch for ncurses, we can re-accept the formula and backport the patch.

**Pull request closed without merging**
