### PR TITLE
zenity moved into x11

### PR DESCRIPTION
**Pull request by bfontaine**
Original text:

---

Note: this depends on X11, but I don’t know how we are supposed to move formulae to homebrew/x11. Do we submit one PR here to remove the formula plus another on the other repo to add it? Do we try to extract the formula’s history from the git repo when moving the formula?

(edit: head doesn’t install, I’m on it)
(edit 2: I removed the head, because it depends on another lib not in Homebrew, which itself depends on another lib not in Homebrew, etc)

### CODE REVIEW

**Comment by mikemcquaid** [comment]
> Do we submit one PR here to remove the formula plus another on the other repo to add it?

Yup. No history needed, thanks!

**Comment by bfontaine** [comment]
@mikemcquaid thanks, I edited this PR to remove Zenity from here, and [made a PR](https://github.com/Homebrew/homebrew-x11/pull/14) on homebrew/x11.

**Comment by DomT4** [comment]
Chuck it in [tap-migrations](https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/tap_migrations.rb) as well :).

**Comment by bfontaine** [comment]
@DomT4 Thanks, done.

**Comment by bfontaine** [comment]
@mikemcquaid Any reason not to merge this one? Homebrew/homebrew-x11#14 can’t build while this one isn’t merged.

**Comment by mikemcquaid** [comment]
@bfontaine Well spotted, sorry, just missed this earlier. Pushing now, thanks!

**Pull request closed without merging**
