### PR TITLE
Adds gollum, a n:m message multiplexer written in Go

### PR DESCRIPTION
**Pull request by andreis**
Binary for now, someone with more time can write a proper godep formula.

Examples of formulas for godep installs:
* [wellington](https://github.com/Homebrew/homebrew/blob/62bbf66e03ff98f7f724475e12596d3db72b0c23/Library/Formula/wellington.rb)
* [docker-machine](https://github.com/Homebrew/homebrew/blob/0cb76904291560fc6f874a2da54fcea272e3509d/Library/Formula/docker-machine.rb)
* [cig](https://github.com/Homebrew/homebrew/blob/aa5718d3120e776573de28ea5e078c85e68189c5/Library/Formula/cig.rb)
* [vault](https://github.com/Homebrew/homebrew/blob/9e47d8cda74b7ab96a7ef99368bb12a5d6cf10d6/Library/Formula/vault.rb)

### CODE REVIEW

**Comment by mistydemeo** [comment]
Thanks! However, we don't binary packages in this repository - this'll need to be built from source.

**Comment by andreis** [comment]
Aye. I'll do it tomorrow unless someone will write it until then.

**Comment by mistydemeo** [comment]
Thanks!

**Comment by DomT4** [comment]
Formula was merged in https://github.com/Homebrew/homebrew/commit/e50a64bfcb0fed1fb71c79cf121c99ca03764860.

**Pull request closed without merging**
