### PR TITLE
Build OpenNI2 driver for libfreenect

### PR DESCRIPTION
**Pull request by xionglingfeng**
Build `libfreenect` with `OpenNI2` support by default

### CODE REVIEW

**Comment by dunn** [comment]
Is there any downside to this? Is it something that someone might want to build libfreenect without?

**Comment by xionglingfeng** [comment]
@dunn  I don't think there are any downside here. I previously added a switch for this (PR #41476), but @mikemcquaid   suggests make this default.

**Comment by dunn** [comment]
Oh, I did see that discussion, but I must have forgotten. Sorry about that, but should be good, then!

**Comment by dunn** [comment]
And merged in 3d904164a39692cc96ef04bfedc79ab696d7452d. Thank you!!

**Pull request closed without merging**
