### PR TITLE
gnuradio: use https url

### PR DESCRIPTION
**Pull request by vszakats**

### CODE REVIEW

**Comment by vszakats** [comment]
There was an intermittent-looking download failure under Mountain Lion.

**Comment by bfontaine** [comment]
@BrewTestBot test this please.

**Comment by vszakats** [comment]
Thanks @bfontaine.

Strange, the error is unchanged, still on Mountain Lion only:
```
==> brew fetch --retry --build-bottle --force gnuradio			 FAILED
==> Downloading https://gnuradio.org/releases/gnuradio/gnuradio-3.7.8.tar.gz
==> Retrying download
==> Downloading https://gnuradio.org/releases/gnuradio/gnuradio-3.7.8.tar.gz
Error: Failed to download resource "gnuradio"
Download failed: https://gnuradio.org/releases/gnuradio/gnuradio-3.7.8.tar.gz
```

Certificate is a Comodo/PositiveSSL one for CloudFlare CDN.

**Comment by vszakats** [comment]
No idea what's going on, should work, but it doesn't, closing this.

**Pull request closed without merging**
