### PR TITLE
Relocate images used in documentation (and remove unused ones)

### PR DESCRIPTION
**Pull request by UniqMartin**
Removed some images that were never referenced since the wiki contents have been imported into `share/doc/homebrew/` and relocated the remaining images into the ~~`resources`~~ `images` subdirectory to get a cleaner/shorter listing on GitHub. (~~I went with the more general term `resources` in case we ever want to add something other than images to our documentation.~~)

### CODE REVIEW

**Comment by mikemcquaid** [comment]
> (I went with the more general term resources in case we ever want to add something other than images to our documentation.)

Can we go for `images`? YAGNI otherwise :wink:

**Comment by DomT4** [comment]
It'd be nice to update the images so they aren't relics of what Jenkins looked like in 2012, but I'll understand if you pass :wink:

**Comment by UniqMartin** [comment]
> Can we go for `images`? YAGNI otherwise :wink:

Sure, if that's needed to get acceptance. :wink: I'm not particularly tied to one name or the other.

> It'd be nice to update the images so they aren't relics of what Jenkins looked like in 2012, but I'll understand if you pass :wink:

They share the fate of all screenshots of quickly becoming outdated. I'm not convinced the extra bits in our Git history are warranted just to get them updated …

**Comment by UniqMartin** [comment]
Updated to use the `images` directory.

**Comment by mikemcquaid** [comment]
:+1: :shipit:

**Pull request closed without merging**
