### PR TITLE
tor 0.2.7.6

### PR DESCRIPTION
**Pull request by alexmerkel**
Updated tor to 0.2.7.6

### CODE REVIEW

**Comment by alexmerkel** [comment]
removed devel completely because there is currently no version in beta

**Comment by mikemcquaid** [comment]
@BrewTestBot test this please

**Comment by mikemcquaid** [comment]
@BrewTestBot test this please

**Comment by DomT4** [comment]
On the Tor website this is still listed as the `unstable` version.

**Comment by DomT4** [comment]
Source code => Download source code => https://www.torproject.org/dist/tor-0.2.6.10.tar.gz

Source code => Download source code (unstable) => https://www.torproject.org/dist/tor-0.2.7.6.tar.gz

> The current stable version of Tor is 0.2.6.10. Its release notes are available

> The current unstable/alpha version of Tor is 0.2.7.6. Its Changelog is available.

**Comment by alexmerkel** [comment]
In [this](https://blog.torproject.org/blog/tor-0275-released-and-stable) blog post from Nov. 22nd, they announced 0.2.7.5 as the first stable release in the 0.2.7.x series and it is also the most recent stable version you get from [deb.torproject.org]() (see e.g. [here](https://deb.torproject.org/torproject.org/dists/jessie/main/binary-amd64/Packages)).
So I think the website is just not updated yet...

**Comment by DomT4** [comment]
Yes, I'm aware of both. I thought the same about the 0.2.7.5 release whether it'd been placed in the wrong place, but it'd seem strange for them to then release a 0.2.7.6 release and *still* have it stuck in the unstable download location.

It'd be good to get some kind of upstream clarification on this. It looks like a mislabel, but.

**Comment by alexmerkel** [comment]
https://twitter.com/nickm_tor/status/675349137169231872 I checked with Nick, 0.2.7.6 is stable (as is 0.2.6.10)

**Comment by DomT4** [comment]
Ah, I was going to reach out to Isis. You beat me to it. Alright, Tor's problematic website aside, looks fine `¯\_(ツ)_/¯`.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/0190c9360d3f934190276ce658d99a4a5c6be724. Thank you for your contribution to Homebrew @alexmerkel; we appreciate it! :smiley_cat:

**Pull request closed without merging**
