### PR TITLE
i2cssh 1.0

### PR DESCRIPTION
**Pull request by djui**
Multiterminal for iTerm2.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
This project is an hour old. Passing on this until it's more established, thanks!

**Comment by djui** [comment]
Ok. So, shall I just wait or reopen the PR again? It's just a simple AppleScript that won't evolve much above that.

**Comment by DomT4** [comment]
It's generally a good idea to host a Homebrew tap for super-new tools like this, and then reconsider resubmitting to Homebrew/homebrew a few months down the line if the project has gained popularity/has ironed out kinks/etc.

**Comment by mikemcquaid** [comment]
Wait for one of your users to submit this in the future (and what @DomT4 said).

**Pull request closed without merging**
