### PR TITLE
texwrapper: migrate to homebrew/tex

### PR DESCRIPTION
**Pull request by L2G**

### CODE REVIEW

**Comment by tdsmith** [comment]
Thinking maybe this should depend on :tex and live in homebrew-tex, where we could give it a better test; what do you think?

**Comment by L2G** [comment]
I have no problem with that. If you want it migrated to the TeX tap, that makes logical sense since it's a TeX utility. :-) I can make that a part of this PR or I can make a new one, whichever you prefer.

**Comment by L2G** [comment]
So... this PR or a new PR?

**Comment by L2G** [comment]
Actually, I'm of two minds about migrating this to homebrew/tex. On the one hand, it serves no purpose without a TeX installation. On the other hand, it's a wrapper, so it doesn't have a "hard" dependency on TeX (which seems to be the chief requirement for inclusion in homebrew/tex).

**Comment by L2G** [comment]
Oh, but I could make the dependency `depends_on :tex => :run`, couldn't I?

**Comment by tdsmith** [comment]
`:run` is a no-op used to clarify that sometimes things need tools which are usually build deps, e.g. `pkg-config`, at runtime as well as at build time. I'd prefer to kick this to homebrew-tex.

**Comment by L2G** [comment]
https://github.com/Homebrew/homebrew-tex/pull/7

**Comment by xu-cheng** [comment]
Thanks @L2G

**Pull request closed without merging**
