### PR TITLE
embulk 0.6.12

### PR DESCRIPTION
**Pull request by cosmo0920**

### CODE REVIEW

**Comment by cosmo0920** [comment]
Hmm, http://bot.brew.sh 's `Jenkins` is curiously angered....
It seems to be failing log in.

Here is stack trace: https://gist.github.com/cosmo0920/c497e31692b03f1b8df6

**Comment by DomT4** [comment]
We're looking at this now. Will re-queue any builds necessary once we've ironed it out. Thanks!

**Comment by cosmo0920** [comment]
It seems to be ironed Homebrew Jenkins problem out.
I've rebased and force pushed.

**Comment by cosmo0920** [comment]
Hmm..., tests does not execute in this PR....
It's curious. :(

**Comment by DomT4** [comment]
It's good, the bot got there in the end :fireworks:.

Merged in https://github.com/Homebrew/homebrew/commit/971e2863c2ba180c16313614553ed27e1bdf8168. Thank you for your contribution to Homebrew, we appreciate it! :smiley_cat:.

**Comment by cosmo0920** [comment]
Thanks!

**Pull request closed without merging**
