### PR TITLE
python3 3.5.0b1 (devel)

### PR DESCRIPTION
**Pull request by youtux**

### CODE REVIEW

**Comment by DomT4** [comment]
Can you remove the `setuptools` and `pip` bumps please? They'll be merged in #40034 relatively soon and that'll cause a merge conflict here. Thanks!

**Comment by youtux** [comment]
Sure! Should I rebase? However not clear why they would conflict.

**Comment by DomT4** [comment]
No need to rebase. If it's just the simple `devel` bump it won't conflict with the existing PR, even when the other Python PR is merged.

They'd conflict because the pip/setuptools bump will have been applied in `master` once the other PR is merged, but git will still treat them like a new addition in this PR and try to override the updated links regardless.

**Comment by jab** [comment]
@DomT4 but this is python3.rb not python.rb, so different formula/file?

**Comment by DomT4** [comment]
Sorry, I'm apparently an idiot :smiley_cat:; The title of this PR just said "Python" so my brain skipped the version number and presumed it was the same as the other Python. Sorry. This PR is fine as it is, please ignore me.

**Comment by youtux** [comment]
@DomT4 Your brain actually works fine, I should have written pyhon3 as title. Ooops!

**Comment by DomT4** [comment]
Not your fault, I should have drunk more :coffee: before looking over this PR. Thanks for changing the title!

**Comment by DomT4** [comment]
Strange error. Is the new `setuptools` incompatible with Python3 devel in some way? Didn't impact the stable build.

```
==> /usr/local/Cellar/python3/3.5.0b1/bin/python3 -s setup.py --no-user-cfg install --force --verbose --install-scripts=/usr/local/Cellar/python3/3.5.0b1/bin --install-lib=/usr/local/lib/python3.5/site-packages
error in setuptools setup command: Invalid environment marker: sys_platform=='win32'
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall python3`
```

**Comment by youtux** [comment]
I think it's caused by setuptools to not being [PEP-0426](https://www.python.org/dev/peps/pep-0426/#environment-markers)-aware. But I have very little knowledge about that.

**Comment by tdsmith** [comment]
Pulled without the pip bump (7 has a bunch of new changes I don't want to risk yet) and the setuptools bump (since it's apparently broken). Someone should open a bug against setuptools, I think? I'll try to get around to it today unless someone beats me to it.

**Comment by tdsmith** [comment]
Setuptools issue: https://bitbucket.org/pypa/setuptools/issue/388/install-from-sdist-fails-on-python-350b1

**Pull request closed without merging**
