### PR TITLE
Formula#to_hash: add bottle info

### PR DESCRIPTION
**Pull request by xu-cheng**

### CODE REVIEW

**Comment by xu-cheng** [comment]
As a bonus, this will also solve #43171.

**Comment by xu-cheng** [comment]
Output example:
```json
    ...
    "bottle": {
      "stable": {
        "revision": 0,
        "cellar": ":any",
        "prefix": "/usr/local",
        "root_url": "https://homebrew.bintray.com/bottles",
        "files": {
          "mavericks": {
            "url": "https://homebrew.bintray.com/bottles/tree-1.7.0.mavericks.bottle.tar.gz",
            "sha1": "d2e9699fce73145917f2b15f7f932765a47e1be6"
          },
          "mountain_lion": {
            "url": "https://homebrew.bintray.com/bottles/tree-1.7.0.mountain_lion.bottle.tar.gz",
            "sha1": "7bdbb4ca0cc98d12c7fae1926c654786600beb0d"
          },
          "lion": {
            "url": "https://homebrew.bintray.com/bottles/tree-1.7.0.lion.bottle.tar.gz",
            "sha1": "c92ed70a7a7d15f7ce5ee75a6851b59de11cf431"
          }
        }
      }
```

**Comment by justmao945** [comment]
@xu-cheng  Does it support Linux ? I prefer to run  `brew info` on my Linux server.

**Comment by xu-cheng** [comment]
>  Does it support Linux ? I prefer to run brew info on my Linux server.

@justmao945 If you mean getting Homebrew bottles information, yes it supports as long as you are running `brew` command from Homebrew repo instead of Linuxbrew.

**Comment by justmao945** [comment]
@xu-cheng  Yes, use `brew info` to get download URL for Homebrew bottles. OK, got it.

**Comment by mikemcquaid** [comment]
:+1:

**Pull request closed without merging**
