### PR TITLE
zbackup 1.4.2

### PR DESCRIPTION
**Pull request by Firefishy**
Update to zbackup 1.4.2

zbackup changelog:
* File descriptors leak fixed

### CODE REVIEW

**Comment by DomT4** [comment]
Are the patches still necessary? It says they're fine to remove on the next release, which is presumably this one?

**Comment by Firefishy** [comment]
The patches are still needed. Does not compile without them. The 1.4.2 release is a minimal release to fix a major issue with zbackup leaking file descriptors, which is particularly easy to trigger on OSX as the default process file descriptor limit is only 256.

**Comment by DomT4** [comment]
Alright. Could you possibly bump those to use `sha256` as well, Thanks.

**Comment by Firefishy** [comment]
Updated with sha256 for the patches too.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/7f4d4ac715ad64fb08b04a9d37dd5cc37a474a55. Thank you for your contribution to Homebrew, we appreciate it! :smiley_cat:

**Pull request closed without merging**
