### PR TITLE
nodenv-update 0.2.0

### PR DESCRIPTION
**Pull request by jawshooah**
Moved from [jawshooah/homebrew-nodenv](https://github.com/jawshooah/homebrew-nodenv)

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Please run `brew audit --strict --online`!

**Comment by jawshooah** [comment]
Sorry, I wasn't aware of the `--online` flag. Shall I close this and the other nodenv plugin PRs, then?

**Comment by mikemcquaid** [comment]
If they are all running for the same reason: yeh, sorry :sob:

**Comment by jawshooah** [comment]
No worries. I should have double-checked the Formula Cookbook before submitting. Apparently the `--online` flag for `brew audit` was introduced relatively recently.

**Comment by mikemcquaid** [comment]
Yeh, it was, no worries about it, the `!` was overkill and just was copy-pasting the same message over a few PRs. Thanks :heart:

**Pull request closed without merging**
