### PR TITLE
neo4j 2.3.0-M02 (devel)

### PR DESCRIPTION
**Pull request by mindrones**

### CODE REVIEW

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/649f42acf648ac2e9c989012f635597ee98c3a9e. Thanks for your contribution to Homebrew, we appreciate it! :smiley_cat:.

Nit for future, `sha256` is now the preferred checksum, Thanks!

**Comment by mindrones** [comment]
Hey @DomT4 I've committed a new patch to use sha256 thanks for letting me know.
As a suggestion, it would be nice to let us know about these preferences via `brew audit` what do you think?

**Comment by bfontaine** [comment]
@mindrones you can run `brew audit --strict`.

**Comment by mindrones** [comment]
@bfontaine ah didn't know about it, thanks! I've updated #40545.

**Pull request closed without merging**
