### PR TITLE
progress 0.8

### PR DESCRIPTION
**Pull request by dunn**
Renamed from 'cv'.

cc @vladshablinsky @xu-cheng

### CODE REVIEW

**Comment by vladshablinsky** [comment]
Maybe we should wait with merging renames a little, because there are some bugs that are being fixed now. But :+1: after they are fixed.

**Comment by dunn** [comment]
Gotcha, thanks.

**Comment by DomT4** [comment]
Does it not need adding to [this file](https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/formula_renames.rb)?

**Comment by DomT4** [comment]
Ignore my briefly existing comment there. My mind wandered off somewhere else.

**Comment by xu-cheng** [comment]
:+1:

**Comment by dunn** [comment]
@BrewTestBot test this please

**Comment by dunn** [comment]
Need a new build to see what it's naming the bottles.

**Pull request closed without merging**
