### PR TITLE
tap: support fast clone

### LINKED ISSUE #37592: brew tap --fast
@DomT4 @mikemcquaid @jacknagel

1. When you first install homebrew clone full history tree,  sometimes you need only **master** (`git --depth 1`):

    ```ruby
echo "--fast" | ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/install/master/install)"
```
    https://github.com/Homebrew/install/commit/ff9a35d980dd80f93883344a7cb278eeee5175f6

2. Command `brew tap` is not supported at the moment `--fast`, what would be removed only master shot without all the history (longer time the clone Cask)   
    If I'm not the developer of one of the Taps would be wonderful to only clone master-HEAD

### PR DESCRIPTION
**Pull request by xu-cheng**
Closes #37592

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Do we support `--fast` elsewhere? I'm a bit dubious about stuff like this because I think just adding an option is much easier than thinking about the default behaviour and whether it needs tweaked.

**Comment by xu-cheng** [comment]
> Do we support --fast elsewhere?

We support it in the install script.

**Comment by xu-cheng** [comment]
Or we can do it the other way around. Default to shallow clone. And using full clone if `HOMEBREW_DEVELOPER` presents.

**Comment by mikemcquaid** [comment]
> Or we can do it the other way around. Default to shallow clone. And switch to full clone if HOMEBREW_DEVELOPER presents.

That sounds interesting to me. Perhaps we even want an argument to be specified for it? I know personally I rarely care about history and am often tapping/untapping with enough regularity that the delay annoys me. Others may disagree.

**Comment by xu-cheng** [comment]
>  Perhaps we even want an argument to be specified for it? 

We already have one `ARGV.homebrew_developer?`.

**Comment by mikemcquaid** [comment]
Sorry, I mean `brew tap --full`

**Comment by xu-cheng** [comment]
So `args << "--depth=1" unless ARGV.homebrew_developer? || ARGV.include?("--full")` ?

**Comment by mikemcquaid** [comment]
I'm thinking we don't enable it by default for `homebrew_developer?` either.

**Comment by xu-cheng** [comment]
> I'm thinking we don't enable it by default for homebrew_developer? either.

OK. Updated.

**Comment by chdiza** [comment]
I normally *love* to make shallow clones.  But in this case, I'm not sure I see the benefit.  Taps aren't loaded down with tons and tons of history that one would want to avoid downloading.  They're tiny repos.

So I don't see a benefit, and I do see a potential harm.   I've had nothing but problems trying to make PRs when my local clone is shallow.  So unless I've just beein doing this wrong, if someone wants to contribute to a tap, they'll either need to `cd` to the relevant dir buried under `Taps` and do `git fetch --unshallow` first, or just make a totally separate clone of the tap repo.

**Comment by xu-cheng** [comment]
@chdiza It's trivial to run `brew untap <tap> && brew tap --full <tap>`. So I'm not worrying about that.

@mikemcquaid Should we :ship: it?

**Comment by DomT4** [comment]
Kinda with @chdiza on this one FWIW.

**Comment by denji** [comment]
@chdiza Try clone Homebrew-Cask repo...

**Comment by mikemcquaid** [comment]
@xu-cheng I'm OK with it but maybe worth waiting a bit longer to see if other @Homebrew/owners have thoughts.

**Pull request closed without merging**
