### PR TITLE
galen 2.0.8

### PR DESCRIPTION
**Pull request by alexandregz**

### CODE REVIEW

**Comment by dunn** [comment]
Thank you for contributing! Feel like improving the existing test a little, while you're at it? We'd love something that checks the software's functionality a little more.

**Comment by alexandregz** [comment]
Yep, I know, but when I tried with first version, BotBrew returns some errors, because app needs visual environment to works.

**Comment by dunn** [comment]
Got it, that's fine then!

**Comment by dunn** [comment]
Merged in 28d1f024399b248a3b0b322a311154db1c14711f. Thanks again!

**Comment by alexandregz** [comment]
thx :smiley:

**Pull request closed without merging**
