### PR TITLE
libgit2 0.24.0

### PR DESCRIPTION
**Pull request by raizyr**
### All Submissions:

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew/pulls) for the same update/change?

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Looks like there's API changes that warrant `brew uses libgit2` to get a `revision` added or incremented.

**Comment by DomT4** [comment]
The one firm `brew uses` doesn't build. We'll need to wait for a new release of `libgit2-glib` as is becoming fairly standard.

**Comment by tschoonj** [comment]
A new version of `libgit2-glib` is out now that supports this new release of `libgit2`. 

@raizyr Would you mind adding a commit for this to your PR?

**Comment by raizyr** [comment]
Sure, I'll do that shortly.

**Comment by DomT4** [comment]
It looks like `gitg` and `gnome-builder` need their `revision`s increased. Would you mind doing that as well? We should finally be good to ship after that.

**Comment by raizyr** [comment]
It looks like `gnome-builder` has a `mirror` that does not have the new version. Is it better to remove the `mirror` or wait until the file exists in both places?

`mirror "https://launchpad.net/ubuntu/+archive/primary/+files/gnome-builder_3.18.1.orig.tar.xz"`

**Comment by DomT4** [comment]
`3.18.1` is the latest stable `gnome-builder` as far as I'm aware, which should exist on the Ubuntu mirror?

**Comment by raizyr** [comment]
~~Yes, `3.18.1` is on the Ubuntu mirror, and it's also what's in the Formula,  perhaps I'm not understanding what...~~

Nevermind, I went back to the docs and learned what you meant by increasing the `revision`.  New commits incoming shortly.

**Comment by raizyr** [comment]
It looks like `gitg-3.18.0` depends on `libgit2-glib < 0.24.0`.  There is a recent commit in `HEAD` to bump that but it hasn't made it to a release yet.

**Comment by tschoonj** [comment]
Best to wait a little bit longer then before merging this one in. Next week Gnome 3.20.0 will be released...

**Comment by tschoonj** [comment]
I have taken your two commits and put them into my Gnome 3.20 PR. 

You can close this PR now.

Thanks!

**Comment by DomT4** [comment]
Closing in favour of #50257.

Your two commits have simply been moved into that PR @raizyr so you won't lose the work you've done here or the commit credit. Thank you in advance for your contributions to Homebrew :smiley_cat:.

**Pull request closed without merging**
