### PR TITLE
kubernetes-cli 1.2.0

### PR DESCRIPTION
**Pull request by antoineco**

### CODE REVIEW

**Comment by apjanke** [comment]
Do you want to just fold #50176 in to this PR? It's fine to bump both the stable and devel versions in a single commit. That should make the audit pass. I'm having a bit of trouble combining them with `brew pull`.

**Comment by antoineco** [comment]
Last time I did that I was told to push 2 separate commits (#46842), that's why. I'll merge both

**Comment by apjanke** [comment]
Oh, sorry about that! Let me go hop on that thread and ask for clarification before you do extra work. Maybe I've got our policy wrong here.

You can still have two separate commits in a single PR - bumping the dev version first and then stable - which will still give two separate items in the commit history, but run in the test bot in a single build and pass the audit checks. Maybe that's what bfontaine was asking for.

Or I could just merge the dev version bump PR and then you could rebase this one on master.

**Comment by apjanke** [comment]
Or we could just ignore the audit failure and merge both. But I'd like to figure out the right process for stuff like this that doesn't get red Xs in the PR queue and doesn't cause unnecessary work for contributors. Sorry about the inconvenience!

**Comment by huggsboson** [comment]
Would love to see this merged.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/241a4eff1c1f91ad2a30cbbb571be327539913db & https://github.com/Homebrew/homebrew/commit/4394dfc9f8059f9b45bc847a6f8000a3aa4a876b. Thank you for your contributions to Homebrew @antoineco! :smiley_cat:

**Pull request closed without merging**
