### PR TITLE
brew.rb: complain if out-of-date

### PR DESCRIPTION
**Pull request by dunn**
I can't remember if I've seen discussion of doing this before; if someone else has an implementation in progress, go ahead and close this.

There's no performance impact.

### CODE REVIEW

**Comment by jacknagel** [comment]
>There's no performance impact.

Shelling out (to git, in this case) will always have a performance impact.

A single additional call may not be noticeable for *you*, but it will be for others, and if we are not vigilant they will add up over time. Running the `brew` tool on a no-op command used to be super slow because of this, and it's only because I spent several months figuring out how to avoid shelling out that it is as fast as it is today.

I don't want to start adding this kind of stuff back.

**Comment by mikemcquaid** [comment]
Perhaps a fast way of doing this would be to check the `mtime` of the `master` pointer file.

**Comment by xu-cheng** [comment]
This change has potential to break the existing tools/script which invokes brew command. At least, it will print this message in a strange and confused place for these tools.

Another thing is `.git` directory may not always exist as we allow users to just download and extract the tarball. A even worse case is that git may not exist. For example, when I bootstrap linuxbrew on CentOS 5, I would install linuxbrew using curl first then use brew to install the git.

**Comment by dunn** [comment]
Gotcha, all good things to know, thanks!

**Pull request closed without merging**
