### PR TITLE
unarj: https resource and sha256

### PR DESCRIPTION
**Pull request by vszakats**

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Please don't submit PRs to just change things to `sha256`; we'll update them incrementally.

**Comment by mikemcquaid** [comment]
(I'll pull this one, though)

**Comment by vszakats** [comment]
I know, the point was to clear up one of the remaining plaintext s3.amazonaws.com urls (there are ony 4 of them after this series of commit).

**Comment by mikemcquaid** [comment]
Ok, cool.

**Comment by mikemcquaid** [comment]
Thanks @vszakats!

**Pull request closed without merging**
