### PR TITLE
qt5 5.5.1

### PR DESCRIPTION
**Pull request by UniqMartin**
Following the discussion in #44998, here's the version bump and a few improvements to the formula itself.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Nice :+1:

**Comment by luzpaz** [comment]
brew bot reports: 
```ERROR: Publisher 'Publish JUnit test result report' failed: No test report files were found. Configuration error?```

**Comment by DomT4** [comment]
The failure is slightly above that line; It hit the timeout of 70 minutes or so. We'll reschedule with a longer timeout when the CI isn't quite so rammed.

**Comment by DomT4** [comment]
@BrewTestBot test this please

**Comment by UniqMartin** [comment]
The build succeeded. :sunglasses: 

However, if we can wait committing this for a day or two, I might have an elegant fix that also solves the `brew install qt5 --with-docs` issue (confirmed) and the broken `macdeployqt` (unconfirmed, have yet to do some testing). If that turns out to be the case, we could spare people a revision bump with the ensuing rebuild or bottle download.

**Comment by mikemcquaid** [comment]
Decided to pull as-is because when I was a Qt developer I wouldn't have wanted to wait :grinning:. Looking forward to the follow-up PR(s) though. Nice work @UniqMartin and thanks!

**Comment by DomT4** [comment]
@UniqMartin Both the Qt and Qt5 formulae install the same `.app` bundles with the same names and overwrite each other on `brew linkapps`. It might be an idea to tweak the `qt5` in-formula mechanism so those app bundles are appended with a `5` and don't overwrite the `qt` formula's apps, similar to how we do for [Python3](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/python3.rb#L168-L169).

Would file a PR myself but you seem to be working on the two remaining `qt5` issues and it's nice to spare the CI multiple Qt5 builds very quickly, heh. Let me know if you have no immediate plans and I'll push it though :smiley:

**Comment by UniqMartin** [comment]
Will keep that in mind. If you've already made that change locally, push it to your clone and I'll cherry-pick it into the branch that will eventually become my next Qt 5 PR.

**Comment by DomT4** [comment]
Haven't pushed it yet. You're more than welcome to include it in one of your PRs; not fussed about whether or not I get commit credit for the thought :)

**Comment by UniqMartin** [comment]
Alright. :)

**Pull request closed without merging**
