### PR TITLE
antlr: add classpath to antlr4 wrapper script

### LINKED ISSUE #45292: Antlr isn't ready to use after brew install
Logs: https://gist.github.com/anonymous/d2418a95612900f3315e

Should probably add a message saying to add the jar to your CLASSPATH (or do it automatically if you can)

### PR DESCRIPTION
**Pull request by dunn**
Fixes #45292.

### CODE REVIEW

**Comment by xu-cheng** [comment]
I'm not sure that we should add this.

Looks to me that users have to set `classpath` anyway. If I removed `classpath` setting in the [test](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/antlr.rb#L31-L32), it will fail.

*P.S.* I don't use java much and have little knowledge on this matter.

**Comment by mikemcquaid** [comment]
I think we probably should add it to the wrapper script.

**Comment by dunn** [comment]
Should we have the wrapper script set `CLASSPATH` as an environment variable instead?

**Comment by mikemcquaid** [comment]
> Should we have the wrapper script set CLASSPATH as an environment variable instead?

If it works :+1:

**Comment by dunn** [comment]
@vermiculus do you foresee any issue using `CLASSPATH` instead?

**Comment by vermiculus** [comment]
As far as I understand, they have the same effect.

**Comment by dunn** [comment]
Oops, pushed to the wrong remote.

**Comment by dunn** [comment]
Ugh, lazy mistake.  Fix in #45411.

**Pull request closed without merging**
