### PR TITLE
erlang-versions: bottle regex fix

### PR DESCRIPTION
**Pull request by DomT4**
Note: This isn’t a fix yet. It’s still detecting just the R14 part and ignoring the latter.

Mike just asked me to push to a remote branch so he can giggle at how bad my regexes are/help me get it solved :).

### CODE REVIEW

**Comment by DomT4** [comment]
CC @mikemcquaid RE: https://github.com/Homebrew/homebrew-versions/pull/638

**Comment by mikemcquaid** [comment]
Merged in 332b6fe.

**Comment by mikemcquaid** [comment]
@DomT4 A few things that will help next time: you may need to play with the ordering in the `bottle_version` file as it was being matched before it ever reached your match. Also, you were using `O` in the place of `0` in some places. Finally, http://rubular.com is the easiest way I've found to quickly write and test these.

**Comment by DomT4** [comment]
@mikemcquaid Thanks Mike, Appreciate you fixing this.

> you may need to play with the ordering in the bottle_version file as it was being matched before it ever reached your match.

Had absolutely no idea this was happening. Is it a safe bet to stick the new regexes at the top rather than clumped in the middle somewhere?

>  Also, you were using O in the place of 0 in some places.

That was particularly stupid of me.

> Finally, http://rubular.com is the easiest way I've found to quickly write and test these.

That looks neat, have stuck it in my favourites :smile_cat:, Thanks!

**Comment by mikemcquaid** [comment]
> Had absolutely no idea this was happening. Is it a safe bet to stick the new regexes at the top rather than clumped in the middle somewhere?

You want to keep them as low as possible but as high as they need to be. Trial and error with `brew tests`, basically :trollface:

**Pull request closed without merging**
