### PR TITLE
librsvg: fix #40833

### LINKED ISSUE #40833: librsvg fails to build under sandboxing
```
libtool: install: chmod 644 /usr/local/Cellar/librsvg/2.40.9_1/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.a
libtool: install: ranlib /usr/local/Cellar/librsvg/2.40.9_1/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.a
/Applications/Xcode.app/Contents/Developer/usr/bin/make  install-data-hook
if test -z ""; then \
		/bin/sh /private/tmp/librsvg20150617-17982-1u5c7pe/librsvg-2.40.9/install-sh -d /usr/local/Cellar/librsvg/2.40.9_1/lib/gdk-pixbuf-2.0/2.10.0/loaders ; \
		/usr/local/opt/gdk-pixbuf/bin/gdk-pixbuf-query-loaders > /usr/local/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache ; \
	fi
/bin/sh: /usr/local/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache: Operation not permitted
make[4]: *** [install-data-hook] Error 1
make[3]: *** [install-data-am] Error 2
make[2]: *** [install-am] Error 2
make[1]: *** [install-recursive] Error 1
make: *** [install] Error 2
```

CC @xu-cheng

### PR DESCRIPTION
**Pull request by xu-cheng**
cc @DomT4.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
:+1: when this is working.

**Comment by DomT4** [comment]
Looks like this is breaking on the test at the moment, but the approach is solid :bow:.

**Comment by xu-cheng** [comment]
Test now fails on an unrelated formula `lablgtk`. I can reproduce locally. Ping @tschoonj for solution.
```
        Testing lablgtk
==> ocamlc -I /usr/local/opt/lablgtk/lib/ocaml/lablgtk2 lablgtk.cma gtkInit.cmo test.ml -o test
File "test.ml", line 1:
Error: Error on dynamically loaded library: dlllablgtk2.so: dlopen(dlllablgtk2.so, 138): image not found
Error: lablgtk: failed
```

**Comment by tschoonj** [comment]
I know about this already. It works on my machine though. 

I don't know the first thing about OCaml, so I am not sure I will be able to come up with a fix.

**Comment by xu-cheng** [comment]
Ok I will then merge this PR as it was unrelated error. Feel free to send PR when you find how to fix it.

**Pull request closed without merging**
