### PR TITLE
Add conf2kube formula

### PR DESCRIPTION
**Pull request by antoineco**

### CODE REVIEW

**Comment by dunn** [comment]
```
==> audit problems
conf2kube:
 * GitHub repository not notable enough (<10 forks, <10 watchers and <20 stars)
 * GitHub repository too new (<30 days old)
```
Might sit on this for a little bit to make sure it's not a flash in the pan and worth adding to our maintenance burden, hope you understand!

**Comment by antoineco** [comment]
Yes of course, I ignored this rule and totally understand it. Should we close this, wait for the repo to get a little bit more traction and reopen a PR?

**Comment by bfontaine** [comment]
@antoineco Yeah, you can maintain the formula in a separate tap in the meantime: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-to-Create-and-Maintain-a-Tap.md

**Comment by DomT4** [comment]
Closing per the above. More than happy to re-review when those audit requirements are met.

You can check locally with `brew audit --strict --online xyz`.

**Pull request closed without merging**
