### PR TITLE
aacgain: test added

### PR DESCRIPTION
**Pull request by bfontaine**

### CODE REVIEW

**Comment by tdsmith** [comment]
The test should make a copy of the fixture, per discussion in #37080.

**Comment by tdsmith** [comment]
(I know you saw this, just adding a note for my own recordkeeping! :smile:)

**Comment by bfontaine** [comment]
I didn’t saw this because most of the activity on Homebrew happens when I’m sleeping :wink: (done!)

**Comment by mikemcquaid** [comment]
Thanks again @bfontaine!

**Pull request closed without merging**
