### PR TITLE
add option to build ffmpeg without jack

### PR DESCRIPTION
**Pull request by MartinDelille**
Last ffmpeg version build ffmpeg with jack dependency which makes impossible to deploy my software on non dev machine. This new option enable the possibility to build ffmpeg without jack. This PR is very similar to this: https://github.com/Homebrew/homebrew/commit/5972821454017ab4900fe13b05d37a7fae319822

### CODE REVIEW

**Comment by MartinDelille** [comment]
My question is: why module like jac and qtkit are available by default?

**Comment by mikemcquaid** [comment]
Why do you need to disable `jack`? How are you deploying software to a non-development machine?

**Comment by MartinDelille** [comment]
If Jack is not installed on my customer machine, my software crashes: https://github.com/Phonations/Joker/releases/latest

**Comment by mikemcquaid** [comment]
I don't mind adding options to the Homebrew formula but you should be checking the libraries your software links against with `otool` and I'd recommend not distributing libraries built with Homebrew.

**Comment by MartinDelille** [comment]
Why? My software is distributed with travis-ci and github release which makes it very simple.

**Comment by mikemcquaid** [comment]
It makes it very simple but also error-prone (as demonstrated by this PR being required). You've released software that crashes because you've not handled libraries properly.

**Comment by MartinDelille** [comment]
You are totally right. Now I'm wondering how should I handle dependencies... Shall I make ffmpeg a project submodule? What about this PR? Do you want me to close it?

**Comment by mistydemeo** [comment]
This PR should probably turn Jack off altogether - it's not an intended feature that it will opportunistically pick up on a non-Homebrew installed Jack without it being accounted for. (The alternative would be for the `--with-jack` case to actually ensure that Jack is installed and fail the build otherwise.)

**Comment by mikemcquaid** [comment]
> This PR should probably turn Jack off altogether - it's not an intended feature that it will opportunistically pick up on a non-Homebrew installed Jack without it being accounted for. (The alternative would be for the --with-jack case to actually ensure that Jack is installed and fail the build otherwise.)

Yep, either sounds good.

**Comment by mikemcquaid** [comment]
> You are totally right. Now I'm wondering how should I handle dependencies... Shall I make ffmpeg a project submodule? What about this PR? Do you want me to close it?

Yeh, I'd recommend building your own dependencies outside Homebrew and check all the libraries are installed in the application bundle.

**Comment by MartinDelille** [comment]
@mistydemeo I agree with you and will change the PR so it is possible to add jack and qtkit explicitely without installing them by default. I'm just wondering how to do it? I commit 5fec5a6 but I'm not sure if I'll work. Any proposition?

**Comment by mikemcquaid** [comment]
@MartinDelille The Jack change is fine but I don't think we want to change the defaults for `qtkit`.

**Comment by MartinDelille** [comment]
Event if it is deprecated?

**Comment by mikemcquaid** [comment]
Yes, we'd rather not change the defaults without notice.

**Comment by MartinDelille** [comment]
Is there a way to notice?

**Comment by mikemcquaid** [comment]
Why do we need to change that?

**Comment by MartinDelille** [comment]
A deprecated API shall not be installed by default, at least after a certain date. I faced a problem with qtkit dependency when trying to deploy my app on the Mac AppStore witch refuse it if linked with deprecated qtkit. I would find more convenient to distribute ffmpeg via brew with a configuration compatible with MacOS development.

**Comment by mikemcquaid** [comment]
With respect, we can't change the defaults in a formula just because it makes it easier for you to distribute your software.

**Comment by jacknagel** [comment]
So, what is the status here? The title of the issue is "add option to build ffmpeg without jack", but the patch adds an option to build *with* jack.

**Comment by DomT4** [comment]
Update on this?

**Comment by MartinDelille** [comment]
No I think the current behaviour is ok.

**Pull request closed without merging**
