### PR TITLE
syncthing 0.10.27. Also log stdout/err to a logfile

### PR DESCRIPTION
**Pull request by mbi**

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Comment by guictx** [comment]
Regarding log stdout/err to a logfile.

Both my machines failed to start syncthing after the upgrade from 0.10.26 due to the fact that /usr/local/var/log was owned by root.
I had to chown /usr/local/var/log to make it work.

**Comment by mbi** [comment]
@guictx I was under the impression that everything under `/usr/local` should be owned by the user running Homebrew, so having `/usr/local/var/log` owned by root shouldn't happen™.

**Comment by claudiodsf** [comment]
Same problem here: all my machines had `/usr/local/var/log` owned by root.
Maybe `brew doctor` should warn about this kind of problems.

**Comment by mbi** [comment]
The syncthing formula follows the same pattern as the [40 or so](https://github.com/Homebrew/homebrew/search?utf8=%E2%9C%93&q=%3Cstring%3E%23{var}%2Flog%2F) others in assuming that `var/log` is user-writable. I imagine all these formulas share the same problem. 

Maybe related issue: https://github.com/Homebrew/homebrew/issues/3960

Maybe @mikemcquaid could shed some light on this?

**Comment by mikemcquaid** [comment]
This issue was fixed in https://github.com/Homebrew/homebrew/pull/37967

**Pull request closed without merging**
