### PR TITLE
Ceylon: Don't delete the .bat file, it's needed for Ceylon Bootstrap

### PR DESCRIPTION
**Pull request by quintesse**
### All Submissions:

- [X] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew/blob/master/.github/CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew/pulls) for the same update/change?

### CODE REVIEW

**Comment by apjanke** [comment]
Strictly speaking, should this get a `revision 1` bump, since it changes the files that end up being installed? We're not building bottles for it, but users with it installed should get automatic upgrades to the new fixed revision.

**Comment by quintesse** [comment]
True, but I didn't see any way to set any "revision" in the formula. The original release hasn't changed of course, given the fact it was a bug in the packaging. So if you could explain how to set a revision I'll be happy to oblige :)

**Comment by apjanke** [comment]
Just add a line that says `revision 1` after the `sha256` line. You can add a revision to any formula; it defaults to `0` if you don't specify one. The `revision` is a property of the formula to indicate exactly that: a bugfix or other change in the packaging, with no change in the software being packaged.

**Comment by mikemcquaid** [comment]
@quintesse Why does the bootstrap need a Windows batch file?

**Comment by quintesse** [comment]
@mikemcquaid : 

Before we would delete any WIndows batch files because we didn't need them for the Mac (of course).
But since 1.2.2 we have a `ceylon bootstrap` command which works like `gradle wrapper` in providing a very simple way for people to distribute Ceylon projects to people who don't have Ceylon installed. It generates two scripts, `ceylonb` for the unices and `ceylonb.bat` for Windows. Users on any OS can run these scripts and they will automatically install Ceylon if necessary.
So even if the file will never be used on a Mac it needs to be available so the `ceylon bootstrap` command can *copy* it (it will never be executed of course for obvious reasons).

**Comment by mikemcquaid** [comment]
@quintesse Ok, thanks.

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

For future reference the preferred commit message format is `ceylon: .bat file is needed for Ceylon Bootstrap.`. This format is detailed in the linked [Contributing guidelines](https://github.com/Homebrew/homebrew/blob/master/.github/CONTRIBUTING.md). Thanks!

**Pull request closed without merging**
