### PR TITLE
scamper 20141211d

### PR DESCRIPTION
**Pull request by nijikon**

### CODE REVIEW

**Comment by DomT4** [comment]
Looks like we need an explicit version here, it's not reading correctly:
```
 Stable: version (cvs) is set to a string without a digit
```

**Comment by DomT4** [comment]
Can we make the `openssl` dep mandatory for all platforms here? It's still trying to use it, just fails because the system provides no headers. Presumably still important for functionality if it tries to built it in by default.

You'll likely need a `pkg-config => :build` dep as well.

```
checking for pkg-config... no
checking for openssl/ssl.h in /usr/local/ssl... no
checking for openssl/ssl.h in /usr/lib/ssl... no
checking for openssl/ssl.h in /usr/ssl... no
checking for openssl/ssl.h in /usr/pkg... no
checking for openssl/ssl.h in /usr/local... no
checking for openssl/ssl.h in /usr... no
checking whether compiling and linking against OpenSSL works... no
```

**Comment by nijikon** [comment]
@DomT4 done

**Comment by bfontaine** [comment]
Thank you @nijikon! :tada:

**Pull request closed without merging**
