### PR TITLE
postgis 2.1.8

### PR DESCRIPTION
**Pull request by nijikon**

### CODE REVIEW

**Comment by nijikon** [comment]
@xu-cheng question, when ```brew install postgis``` with all the flags, a do get this.

```
(deny file-write*) ; deny non-whitelist file write operations
(allow default) ; allow everything else
syslog -F '$((Time)(local)) $(Sender)[$(PID)]: $Message' -k Time ge 1437470972 -k Sender kernel -o -k Time ge 1437470972 -k Sender sandboxd | grep deny > /Users/n/Library/Logs/Homebrew/postgis/sandbox.build.log
Error: Operation not permitted - (stage/usr/local/Cellar/postgresql/9.4.4/lib/postgis-2.1.so, /usr/local/Cellar/postgresql/9.4.4/lib/postgis-2.1.so)
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:519:in `rename'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:519:in `block in mv'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1552:in `block in fu_each_src_dest'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1568:in `fu_each_src_dest0'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1550:in `fu_each_src_dest'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:508:in `mv'
/usr/local/Library/Homebrew/extend/pathname.rb:53:in `install_p'
/usr/local/Library/Homebrew/extend/pathname.rb:24:in `block (2 levels) in install'
/usr/local/Library/Homebrew/extend/pathname.rb:24:in `each'
/usr/local/Library/Homebrew/extend/pathname.rb:24:in `block in install'
/usr/local/Library/Homebrew/extend/pathname.rb:13:in `each'
/usr/local/Library/Homebrew/extend/pathname.rb:13:in `install'
/usr/local/Library/Formula/postgis.rb:110:in `install'
/usr/local/Library/Homebrew/debrew.rb:22:in `block in install'
/usr/local/Library/Homebrew/debrew.rb:97:in `debrew'
/usr/local/Library/Homebrew/debrew.rb:22:in `install'
/usr/local/Library/Homebrew/build.rb:129:in `block in install'
/usr/local/Library/Homebrew/formula.rb:546:in `block in brew'
/usr/local/Library/Homebrew/formula.rb:955:in `block in stage'
/usr/local/Library/Homebrew/resource.rb:91:in `block in unpack'
/usr/local/Library/Homebrew/extend/fileutils.rb:17:in `mktemp'
/usr/local/Library/Homebrew/resource.rb:88:in `unpack'
/usr/local/Library/Homebrew/resource.rb:81:in `stage'
/usr/local/Library/Homebrew/formula.rb:947:in `stage'
/usr/local/Library/Homebrew/formula.rb:542:in `brew'
/usr/local/Library/Homebrew/build.rb:107:in `install'
/usr/local/Library/Homebrew/build.rb:179:in `<main>'
```

**Comment by xu-cheng** [comment]
That's because postgis is trying to install its files to postgresql's cellar. Sandbox prevents such operations which are also against the way homebrew handles files.

To solve it, we should turn postgis into postgresql's optional resource. That is to create a new option in  postgresql as `--with-postgis`. After that, we can delete this formula. Can you submit a PR to make such change? Thanks.

**Comment by cosmo0920** [comment]
Hey, any response for this PR?
I don't know what I should to create `--with-pgroonga` that is for PGroonga. Thanks.

**Comment by nijikon** [comment]
@cosmo0920 I will pick this up tomorrow, a bit busy today.

**Comment by cosmo0920** [comment]
@nijikon Thanks! I'm looking for your work.

**Comment by xu-cheng** [comment]
Ping

**Comment by cosmo0920** [comment]
Ping again.

**Comment by nijikon** [comment]
I will work on this today, sorry for the delay.

**Comment by jsheedy** [comment]
[postgis 2.2](http://postgis.net/2015/10/07/postgis-2.2.0) was announced today.

**Comment by jsheedy** [comment]
I've submitted a [pull request for postgis 2.2.0](https://github.com/Homebrew/homebrew/pull/44728).

**Comment by DomT4** [comment]
Closing in favour of #44728, but the core sandboxing issue remains.

**Pull request closed without merging**
