### PR TITLE
nginx: Add "--with-realip" option

### PR DESCRIPTION
**Pull request by malthejorgensen**
Adds option to configure Nginx with the `--with-http_realip_module`
(http://nginx.org/en/docs/http/ngx_http_realip_module.html)

### CODE REVIEW

**Comment by mikemcquaid** [comment]
We're not adding more options to the `nginx` formula. Please submit this to `homebrew-nginx` instead. Thanks!

**Comment by malthejorgensen** [comment]
Aah, I see they already have this option in [homebrew-nginx](https://github.com/Homebrew/homebrew-nginx) – sorry for the disturbance.

Maybe we should write a note at the top of `nginx.rb`, saying that the formula is not accepting new options/flags? (and that the `homebrew-nginx` tap should be used in those cases)

e.g.
```ruby
### Note: The Nginx formula is not accepting new options via Pull
### Requests. For an nginx formula with all build flags available
### please see homebrew-nginx.
### (https://github.com/homebrew/homebrew-nginx)

class Nginx < Formula
  homepage "http://nginx.org/"
...
```
– or the reference to `homebrew-nginx` could be shown in `brew info nginx`

Thanks!

**Comment by DomT4** [comment]
There's something similar on line 22 already.

**Comment by malthejorgensen** [comment]
How did I not see that :(

**Pull request closed without merging**
