### PR TITLE
physfs: use https urls

### PR DESCRIPTION
**Pull request by vszakats**

### CODE REVIEW

**Comment by vszakats** [comment]
That's a timeout on the Mountain Lion build while downloading.

**Comment by vszakats** [comment]
Can a maintainer please relaunch the bot?

**Comment by dunn** [comment]
Already did!

**Comment by vszakats** [comment]
Thanks @dunn! Quite strange I can only see the first results still and no indication of a job pending. Maybe I'm overlooking something. All in all it's still the timeout error under ML.

**Comment by vszakats** [comment]
Patience resolved it :) It's greened out now.

**Comment by dunn** [comment]
And merged in 3511faeda9a82faff01b990afbcc9d4fe347134e 🚠

**Pull request closed without merging**
