### PR TITLE
Update flatbuffers to 1.2.0

### PR DESCRIPTION
**Pull request by rw**

### CODE REVIEW

**Comment by dunn** [comment]
You might have used the SHA1 by accident, instead of SHA256:
```
Warning: Formula reports different SHA256: e1f5990bc312646531394c85b78d4a61e13e2e90
Downloaded to: /Library/Caches/Homebrew/flatbuffers-1.2.0.tar.gz
SHA1: e1f5990bc312646531394c85b78d4a61e13e2e90
SHA256: a6cacab3cbcc99e2308d8aa328bff060ba19061ce6eb23be85eccb63fb3446b5

**Comment by rw** [comment]
How do I see why it failed on 1 of 2 tests?

**Comment by rw** [comment]
Jenkins was being wonky, this worked when I retried the build!

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/ec4bd7247a1951f68b1045b747fb43d3ea18b469. Thank you for your contribution to Homebrew @rw; we appreciate it! :smiley_cat:

**Pull request closed without merging**
