### PR TITLE
mongodb 3.2.0 (stable)

### PR DESCRIPTION
**Pull request by damirv**

### CODE REVIEW

**Comment by DomT4** [comment]
Build failed:

```
Checking for C header file x86intrin.h... yes
scons: done reading SConscript files.
usage: scons [OPTION] [TARGET] ...

SCons Error: no such option: --cc
==> Formula
```

And an audit nit:
```
        Error: 1 problem in 1 formula
mongodb:
 * devel version 3.1.9 is older than stable version 3.2.0
```

**Comment by damirv** [comment]
Tried to fix the compile error. About the `devel` version: I can't find `devel` version > 3.2.0 (I guess they haven't started/released it yet). Should `devel` be removed then?

**Comment by mikemcquaid** [comment]
> Tried to fix the compile error. About the devel version: I can't find devel version > 3.2.0 (I guess they haven't started/released it yet). Should devel be removed then?

Yup!

**Comment by damirv** [comment]
`devel` is now removed. I also compacted everything into one commit and rebased it on the current master commit. Builds should pass now (locally it works for me).

**Pull request closed without merging**
