### PR TITLE
bzr-extmerge erik@plero.se-20100728145225-et6ipg7cjbshiz8f (new formula)

### PR DESCRIPTION
**Pull request by fmccann**

### CODE REVIEW

**Comment by mistydemeo** [comment]
Does this software have stable releases?

**Comment by fmccann** [comment]
There's no tagged revisions or release tarballs. The plugin has been around and finished since 2010, and it's still referenced as active in all the docs as the method for using external merge tools with bzr:

http://doc.bazaar.canonical.com/latest/en/user-guide/resolving_conflicts.html
http://doc.bazaar.canonical.com/plugins/en/extmerge-plugin.html

I don't think they're going to be cutting a versioned release.

**Comment by fmccann** [comment]
Is there a way to get more detailed feedback on the CI failure?

==> brew fetch --retry bzr-extmerge
==> Cloning lp:bzr-extmerge
==> Retrying download
==> Cloning lp:bzr-extmerge
Error: Failed to download resource "bzr-extmerge"
Failure while executing:  checkout --lightweight lp:bzr-extmerge /Library/Caches/Homebrew/bzr-extmerge--bzr
==> FAILED

This is working when I run locally:

fmccann@hobbes /u/local> brew fetch --retry bzr-extmerge --verbose
==> Cloning lp:bzr-extmerge
Updating /Library/Caches/Homebrew/bzr-extmerge--bzr
/usr/local/bin/bzr update
Tree is up to date at revision 16 of branch bzr+ssh://bazaar.launchpad.net/+branch/bzr-extmerge

**Comment by tdsmith** [comment]
I wonder if we're failing to install bazaar before trying to check out the repository.

**Comment by tdsmith** [comment]
Sorry, but Homebrew/homebrew doesn't accept software without versioned release tarballs. We have some [guidelines for acceptable formulæ](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Acceptable-Formulae.md#acceptable-formulae) if you'd like to learn more.

One way you could use Homebrew to install this software is to [maintain your own tap](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-to-Create-and-Maintain-a-Tap.md#how-to-create-and-maintain-a-tap). The linked document has some advice; please let us know if you have any questions and we'll be happy to help you set things up.

If you do host a tap, a synthetic version like the release date in `YYYYMMDD` format could be more useful than the string you're using now because Homebrew does a relatively simple check to see if a version has incremented and `upgrade` won't work unless Homebrew can tell there's a newer version available.

**Pull request closed without merging**
