### PR TITLE
docker 1.9.1, docker-machine 0.5.1, docker-machine-parallels 1.1.0

### PR DESCRIPTION
**Pull request by kad**
Atomic update of docker, docker-machine and docker-machine-parallels
as docker-machine v0.5.1 release broke binary driver interface

### CODE REVIEW

**Comment by kad** [comment]
Passes my local tests:

```
$ docker-machine create --driver=parallels test
Running pre-create checks...
Creating machine...
(test) OUT | Creating SSH key...
(test) OUT | Creating Parallels Desktop VM...
(test) OUT | Starting Parallels Desktop VM...
(test) OUT | Waiting for VM to come online...
Waiting for machine to be running, this may take a few minutes...
Machine is running, waiting for SSH to be available...
Detecting operating system of created instance...
Detecting the provisioner...
Provisioning created instance...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
To see how to connect Docker to this machine, run: docker-machine env test
$ eval "$(docker-machine env test)"
$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.5.1
 Git commit:   a34a1d5
 Built:        Fri 20 Nov 2015 20:41:22 UTC
 OS/Arch:      darwin/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      linux/amd64
$ docker-machine upgrade test
Detecting the provisioner...
Downloading latest boot2docker iso...
Latest release for github.com/boot2docker/boot2docker is v1.9.1
Downloading https://github.com/boot2docker/boot2docker/releases/download/v1.9.1/boot2docker.iso to /Users/kad/.docker/machine/cache/boot2docker.iso...
0%....10%....20%....30%....40%....50%....60%....70%....80%....90%....100%
Stopping machine to do the upgrade...
Upgrading machine "test"...
Starting machine back up...
(test) OUT | Waiting for VM to start...
$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.5.1
 Git commit:   a34a1d5
 Built:        Fri 20 Nov 2015 20:41:22 UTC
 OS/Arch:      darwin/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64
$
```

Test environment: MacOS X 10.11.1, Parallels Desktop 11.1.0 (32202)

```
$ brew info docker
docker: stable 1.9.0 (bottled), HEAD
Pack, ship and run any application as a lightweight container
https://www.docker.com/
/usr/local/Cellar/docker/1.9.0 (10 files, 9.6M)
  Poured from bottle
/usr/local/Cellar/docker/1.9.1 (10 files, 9.6M) *
  Built from source
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/docker.rb
==> Dependencies
Build: go ✔
==> Options
--with-experimental
	Enable experimental features
--without-completions
	Disable bash/zsh completions
--HEAD
	Install HEAD version
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completion has been installed to:
  /usr/local/share/zsh/site-functions
$ brew info docker-machine
docker-machine: stable 0.5.0 (bottled), HEAD
Create Docker hosts locally and on cloud providers
https://docs.docker.com/machine
/usr/local/Cellar/docker-machine/0.5.0 (20 files, 133M)
  Poured from bottle
/usr/local/Cellar/docker-machine/0.5.1 (23 files, 133M) *
  Built from source
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/docker-machine.rb
==> Dependencies
Build: go ✔, automake ✔
akanevsk-mac09:~ akanevsk$ brew info docker-machine-parallels
docker-machine-parallels: stable 1.0.1 (bottled), HEAD
Docker Machine Parallels Driver
https://github.com/Parallels/docker-machine-parallels
/usr/local/Cellar/docker-machine-parallels/1.1.0 (4 files, 11M) *
  Built from source
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/docker-machine-parallels.rb
==> Dependencies
Build: go ✔
Required: docker-machine ✔
$
```

**Comment by bfontaine** [comment]
Would it be possible that you break down this into 3 commits (but one PR)?

**Comment by kad** [comment]
Sure. will do in few mins.

**Comment by kad** [comment]
Supersedes #46221, #46199, #46065

**Comment by kad** [comment]
CI failure seems to be unrelated. @bfontaine is there way to re-trigger it ?

**Comment by bfontaine** [comment]
@kad Don’t worry about Travis; The “default” CI job is the one to watch :wink:

**Comment by DomT4** [comment]
Nit, but please don't include the `v` for version in commit messages.

Merged in https://github.com/Homebrew/homebrew/commit/ff659b2338de29fc6ceb7d90a187a5b8c8945c52, https://github.com/Homebrew/homebrew/commit/f1c1a2e0adda481e7f7a9e36bf707839faafe391 & https://github.com/Homebrew/homebrew/commit/13bb9bd700e865c0170709806d9912aedf21b0f3. Thank you for your further contributions to Homebrew @kad; we appreciate them :smiley_cat:

**Pull request closed without merging**
