### PR TITLE
test: add/improve miscellaneous tests

### PR DESCRIPTION
**Pull request by UniqMartin**

### CODE REVIEW

**Comment by mikemcquaid** [comment]
:+1:

**Comment by mikemcquaid** [comment]
That said, obviously it's up to you what you work on but I'd personally prioritise coverage given that we still have a lot of the code base with no tests at all.

**Comment by UniqMartin** [comment]
> That said, obviously it's up to you what you work on but I'd personally prioritise coverage given that we still have a lot of the code base with no tests at all.

Are you referring to the second commit that attempts to exhaustively test version comparison? If so, it actually also improves coverage, because it tests previously untested combinations.

**Comment by mikemcquaid** [comment]
@UniqMartin I'm suggesting adding 50 lines of tests for +0.1% coverage improvement is perhaps not the best use of additional code. I'm happy with this PR as-is but that's just a thought for future ones.

**Comment by UniqMartin** [comment]
Understood. Thanks! :bow:

**Pull request closed without merging**
