### PR TITLE
upgrade protocols (1)

### PR DESCRIPTION
**Pull request by vszakats**

### CODE REVIEW

**Comment by vszakats** [comment]
The space in the URL seems to cause some trouble:
```
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20160227-83184-103db4d.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Library/Homebrew -- /usr/local/Library/Homebrew/test.rb /usr/local/Library/Formula/mdxmini.rb --verbose
==> Downloading http://ftp.modland.com/pub/modules/MDX/Popful Mail/pop-00.mdx
/usr/bin/curl -fLA Homebrew 0.9.5 (Ruby 2.0.0-645; OS X 10.11.3) http://ftp.modland.com/pub/modules/MDX/Popful Mail/pop-00.mdx -C 0 -o /Library/Caches/Homebrew/mdxmini--test_song-00.mdx.incomplete --silent
Error: mdxmini: failed
Failed to download resource "mdxmini--test_song"
Download failed: http://ftp.modland.com/pub/modules/MDX/Popful Mail/pop-00.mdx
```

**Comment by DomT4** [comment]
If this actually passes CI, which it looks very much like it will do (colour me pleasantly surprised all of these compiles still work :smile:) note to self to pull :baby_bottle:s.

**Comment by DomT4** [comment]
Merged! Thanks for going through these @vszakats :star2:

**Comment by vszakats** [comment]
Thank you!

**Pull request closed without merging**
