### PR TITLE
gqrx 2.3.2 gnuradio 3.7.8rc1 gnuradio-osmosdr 0.1.4 uhd 003_008_005

### PR DESCRIPTION
**Pull request by jiegec**

### CODE REVIEW

**Comment by jiegec** [comment]
Oh i forgot to make a separate commit for each formula

**Comment by jiegec** [comment]
Wait a minute

**Comment by jiegec** [comment]
Fixing according to audit..

**Comment by Neal** [comment]
Why'd you close this?

**Comment by jiegec** [comment]
@Neal It takes a long time to build all these formulas at one time, so it will stuck the test bot for about 45 minutes.

**Comment by zmre** [comment]
I was excited to see this and thought I'd test it out locally.  Alas, installing gnuradio fails with:

```
% brew install https://raw.githubusercontent.com/jiegec/homebrew/2076cebc4534296d63a0325e81459c9cb96047be/Library/Formula/gnuradio.rb                                                                                                                                    
######################################################################## 100.0%
==> Downloading http://gnuradio.org/releases/gnuradio/gnuradio-3.7.8rc1.tar.gz
Already downloaded: /Library/Caches/Homebrew/gnuradio-3.7.8rc1.tar.gz
==> cmake .. -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/gnuradio/3.7.8rc1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev
  Cheetah templates required to build VOLK


-- Configuring incomplete, errors occurred!
See also "/tmp/gnuradio20150811-51137-67p99g/gnuradio-3.7.8rc1/build/CMakeFiles/CMakeOutput.log".
couldn't understand kern.osversion `14.4.0'
```

Unfortunately, the referenced log file is not there.  Any suggestions?

**Comment by jiegec** [comment]
@zmre That's a bug, and I am fixing it.

**Comment by jiegec** [comment]
@zmre try my new one but it still can't pass the tests.

**Comment by zmre** [comment]
@jiegec I don't see your new commit.  I'll try it out if you point me to the updated file.

**Comment by roddi** [comment]
I'd really like to see Gnuradio in Homebrew! Can you make it happen?

**Comment by jiegec** [comment]
This is done in this pull request: https://github.com/Homebrew/homebrew/pull/42796

**Comment by jiegec** [comment]
Still need to fix, but i wonder how

**Comment by godber** [comment]
So GQRX and GnuradioOsmosdr are the two remaining things that need to be built here since #42796 handles gnuradio (looks like v3.7.8) and UHD?

**Comment by jiegec** [comment]
@godber Gqrx has only a .app so it should not be in homebrew main tap. The GnuradioOsmosdr repo has only 5 watch and 8 stars. It cannot pass audit --online

**Comment by kevinelliott** [comment]
@jiegec What is the status of this? Many of us are waiting for a brew based solution.

**Comment by jiegec** [comment]
@kevinelliott gnuradio and uhd are already done. gqrx is .app only so it should go to brew-cask or else. Hmm i find gnuradio-osmosdr has the same python linking problem, but it does not have a issue tracker and i do not know where to place that patch.

**Comment by godber** [comment]
I've created my own formulas to address their absence:

https://github.com/godber/homebrew-godber

http://uberhip.com/rtlsdr/osx/gqrx/2015/10/17/OS_X_El_Capitan_GQRX_HackRF/

**Comment by jiegec** [comment]
@godber That's ok. By the way, if i press 'start' in gqrx, it freezes, and i have to kill it.

**Pull request closed without merging**
