### PR TITLE
nifi 0.3.0

### PR DESCRIPTION
**Pull request by apiri**
Updating Apache NiFi formula to reflect released version 0.3.0.

### CODE REVIEW

**Comment by apiri** [comment]
Not sure what caused the failure on build given that it was just version updates.  Is there currently an issue with Travis CI that is causing errors?  Thanks for any insight into a resolution.

**Comment by tdsmith** [comment]
Yes, Travis is a work in progress.

**Comment by apiri** [comment]
Thanks for the info!

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/b2a6646d667af77bfa37835594629a430ccd09a9. Thank you for your contribution to Homebrew; we appreciate it! :smiley_cat:

**Pull request closed without merging**
