### PR TITLE
Clone of gccxml formula; adds 0.6.0 as a stable release, better formula(?)

### PR DESCRIPTION
**Pull request by launisch**

### CODE REVIEW

**Comment by mistydemeo** [comment]
Does this build okay with clang? Does it only require GCC at runtime?

**Comment by tdsmith** [comment]
Please revise the existing gccxml.rb formula.

**Comment by launisch** [comment]
I’m embarrassed to say that I made this because I tried installing the gccxml.rb formula and it wasn’t working; probably PEBKAC on my part.

I built it on Yosemite 10.10.5.

Here’s the otool outputs:

otool -L /usr/local/bin/gccxml

/usr/local/bin/gccxml:
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)

otool -L /usr/local/bin/gccxml_cc1plus

/usr/local/bin/gccxml_cc1plus:
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)

Best regards,

Jordan

**Comment by dunn** [comment]
If there is now a stable release, we can move `gccxml.rb` from the head-only repository.  Keep the name the same (no dash), and open another pull request at homebrew-head-only, deleting `gccxml.rb` from that repository: https://github.com/Homebrew/homebrew-head-only

**Comment by tdsmith** [comment]
Oops, what Alex said. Sorry for the confusion!

**Comment by launisch** [comment]
Hm, to be honest, I'm not sure if it's stable; it was the last packaged release before the project moved to Github.

It says it's been succeeded by CastXML. I was just building it for some other software I was trying to run.

Jordan

**Comment by bfontaine** [comment]
@launisch Would you mind removing the dash from the formula name as Alex asked? You’ll also need to rename the class to `Gccxml` (not `GccXml`). We’ll then be able to merge this version and remove the one from `head-only`.

**Comment by bfontaine** [comment]
It has indeed been suceeded by CastXML, see also https://github.com/Homebrew/homebrew-head-only/issues/186#issuecomment-182967897; Thank you anyway!

**Pull request closed without merging**
