### PR TITLE
follow perm redirect for savannah.nongnu.org urls

### PR DESCRIPTION
**Pull request by vszakats**
* also update an url in comment to https

### CODE REVIEW

**Comment by vszakats** [comment]
Fails while testing `normalize`. Doesn't seem to be related to this update:
```
Testing normalize
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20151006-20940-qtxdzr.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Library/Homebrew -- /usr/local/Library/Homebrew/test.rb /usr/local/Library/Formula/normalize.rb --verbose
==> /usr/local/Cellar/normalize/0.7.7/bin/normalize
.
Last 150 lines from /Users/travis/Library/Logs/Homebrew/normalize/01.normalize:
2015-10-06 18:03:11 +0000
/usr/local/Cellar/normalize/0.7.7/bin/normalize
Usage: normalize [OPTION]... [FILE]...
Try `normalize --help' for more information.
Error: normalize: failed
Failed executing: /usr/local/Cellar/normalize/0.7.7/bin/normalize 
/usr/local/Library/Homebrew/formula.rb:1342:in `block in system'
/usr/local/Library/Homebrew/formula.rb:1279:in `open'
/usr/local/Library/Homebrew/formula.rb:1279:in `system'
/usr/local/Library/Formula/normalize.rb:27:in `block in <class:Normalize>'
/usr/local/Library/Homebrew/formula.rb:1188:in `block in run_test'
/usr/local/Library/Homebrew/extend/fileutils.rb:17:in `mktemp'
/usr/local/Library/Homebrew/formula.rb:1184:in `run_test'
/usr/local/Library/Homebrew/test.rb:28:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/usr/local/Library/Homebrew/test.rb:27:in `<main>'
==> FAILED
brew.uninstall.64
```

**Comment by DomT4** [comment]
https://github.com/Homebrew/homebrew/commit/cb3c3b414d28cd51193e0a79d8f7bdbbd3467ca2

**Comment by vszakats** [comment]
Thanks @DomT4. Rebased to latest master, let's see how it continues.

**Comment by DomT4** [comment]
Merged in a whole bunch of commits :wink:. Thanks again Viktor.

**Pull request closed without merging**
