### PR TITLE
Erlang 18.1

### PR DESCRIPTION
**Pull request by MSch**

### CODE REVIEW

**Comment by MSch** [comment]
Looks like something went wrong with Travis, can someone restart the build or should I just force push to trigger Travis again?

**Comment by mikemcquaid** [comment]
You can ignore Travis and focus on the (passing) default build.

**Comment by DomT4** [comment]
I presume there's no compatibility issues between 18.0.x & 18.1? It's usually fine, but `¯\_(ツ)_/¯`.

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
