### PR TITLE
jetty: use ssl/tls homepage

### PR DESCRIPTION
**Pull request by vszakats**
(homepage has mixed content)

### CODE REVIEW

**Comment by DomT4** [comment]
We're not really adding descriptions to existing formulae at this time :cry:. We're planning to do them all en-mass as soon as the update mechanism tweak is merged.

**Comment by vszakats** [comment]
Does it mean I should stop adding them when touching formulae for other reasons? (f.e. in this case an `url` update?)

**Comment by DomT4** [comment]
Yeah, for now. We're only accepting them for new formulae at this point. Essentially the `desc` warning is fine to ignore for current formulae until after the add-descs-to-everything PR that's pending is merged.

**Comment by vszakats** [comment]
Thanks. Removed them. Except for the pending mecab PRs, where it would be messy.

**Comment by vszakats** [comment]
Can a maintainer please ask the bot for a new build? (it seems the squash confused it)

**Comment by bfontaine** [comment]
@BrewTestBot test this please.

**Comment by vszakats** [comment]
Thanks!

**Comment by bfontaine** [comment]
Thanks @vszakats, merged!

**Pull request closed without merging**
