### PR TITLE
aptly: Update to version 0.9.1

### PR DESCRIPTION
**Pull request by md5**
I've used this locally to build myself a copy of `aptly` 0.9.1. I updated the commit refs based on the `Gomfile`, but this is my first update to a Homebrew formula, much less a Go-based formula, so I'm not 100% sure I got everything right.

cc/ @jfarrell

### CODE REVIEW

**Comment by jfarrell** [comment]
+1, builds as well as passes brew audit and test

**Comment by vszakats** [comment]
Would you update `homepage` to use https protocol? (it's mixed content, but anyway)

**Comment by md5** [comment]
@vszakats done

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

For future reference the preferred commit message format for simple version updates is `aptly 0.9.1` and please don't sign-off your own commits.

**Comment by md5** [comment]
Noted :notebook: :notes:

**Pull request closed without merging**
