### PR TITLE
miller 3.1.0

### PR DESCRIPTION
**Pull request by johnkerl**
Miller 3.1.0 release https://github.com/johnkerl/miller/releases/tag/v3.1.0

### CODE REVIEW

**Comment by DomT4** [comment]
Looks like there's a merge conflict or something here. Mind rebasing and squashing to resolve that? Thanks!

**Comment by johnkerl** [comment]
will do

**Comment by johnkerl** [comment]
rebased

**Comment by johnkerl** [comment]
resubmitting as https://github.com/Homebrew/homebrew/pull/46720

**Pull request closed without merging**
