### PR TITLE
hg-flow 0.9.8

### PR DESCRIPTION
**Pull request by xu-cheng**
Also fix the install and add test

### CODE REVIEW

**Comment by mikemcquaid** [comment]
:+1:

**Comment by xu-cheng** [comment]
@mikemcquaid this test just failed on `Don't use mercurial as a dependency. We allow non-Homebrew mercurial installations.` I already fixed that.

However I have a question on it. AFAIK, OS X doesn't ship with mercurial by default. If a user install `hg-flow` directly without installing mercurial, mercurial would be missing. Should we add a dependency `:hg`? Or it is a minor situation and I'm over thinking.

**Comment by mikemcquaid** [comment]
Yeh, I'd add `depends_on :hg`

**Comment by jacknagel** [comment]
Will changing the install location break this for people who are currently using it? How are users supposed to know they need to alter their hg config?

**Comment by xu-cheng** [comment]
> Will changing the install location break this for people who are currently using it? How are users supposed to know they need to alter their hg config?

The origin hg config is wrong. I cannot make it work at the first place.

**Comment by jacknagel** [comment]
Even if you install Homebrew python or add HOMEBREW_PREFIX/lib/python2.7/site-packages to PYTHONPATH?

I don't disagree that this is probably a better way to do it, but presumably the existing formula was working for someone at some point.

**Comment by xu-cheng** [comment]
> presumably the existing formula was working for someone at some point.

According to `git history`, original config file is from v0.4(which is so old, it's not available for download). And I do some dig on the wiki page. As you can see from [here](https://bitbucket.org/yujiewu/hgflow/wiki/commits/98c1f85c5c755db20199f028339cccad4cd99b7b), the author decided to make the name changing in the config file from 0.8 to 0.9. That's when forward compatibility is broken.

**Comment by jacknagel** [comment]
Thanks.

**Pull request closed without merging**
