### PR TITLE
Add compiler-rt to the llvm build

### PR DESCRIPTION
**Pull request by agentsim**
Without compiler-rt the sanitizers, like address-sanitizer don't work due to a missing dylib.

### CODE REVIEW

**Comment by jacknagel** [comment]
>llvm:
 * Use spaces instead of tabs for indentation

**Comment by agentsim** [comment]
@jacknagel, fixed

**Comment by abroekhuis** [comment]
I know this PR is closed, but this addition has been reverted so that now compiler-rt is not build anymore, which as a result also means that "address-sanitizer" cannot be used.
Is there already any plan or PR to enable this again so that "address-sanitizer" can be used?
Thanks

**Comment by agentsim** [comment]
Xcode 7 will include address sanitizer... finally!

**Pull request closed without merging**
