### PR TITLE
librsvg 2.40.11

### PR DESCRIPTION
**Pull request by tschoonj**

### CODE REVIEW

**Comment by xu-cheng** [comment]
Thanks for the pull request! 🎉 Homebrew depends on contributions from community members like you and we're grateful for your support.

**Comment by EugeneDae** [comment]
2.40.11 breaks  `--keep-aspect-ratio` (or `-a`) feature of `librsvg-convert`.

Easy to test from command-line:

    $ wget -O test.svg https://upload.wikimedia.org/wikipedia/en/8/80/Wikipedia-logo-v2.svg
    $ rsvg-convert test.svg -a -w 1000 > test.png
    $ du -hs test.png
    24K	test.png

Compare with the output of `rsvg-convert version 2.40.2` on Ubuntu:
    $ wget -O test.svg https://upload.wikimedia.org/wikipedia/en/8/80/Wikipedia-logo-v2.svg
    $ rsvg-convert test.svg -a -w 1000 > test.png
    $ du -hs test.png
    376K	test.png

The latter results in a properly resized image that weights 376KB.

I wish I knew how to revert the version on OS X.

**Comment by EugeneDae** [comment]
I've managed to downgrade librsvg to 2.40.10 and that fixed the issue.

    cd /usr/local
    git checkout 7a58ff6e07dd35d438193a2e551cf282c2088a44 /usr/local/Library/Formula/librsvg.rb
    git install librsvg
    git checkout master
    brew pin librsvg

Now:

    $ rsvg-convert test.svg -a -w 1000 > test.png
    $ du -hs test.png
    376K    test.png

**Bottom line:** 2.40.10 works much better for me on El Cap than the newer one 2.40.11.

**Comment by tschoonj** [comment]
@EugeneDae this is an upstream issue. I assume this [bugreport](https://bugzilla.gnome.org/show_bug.cgi?id=756340) covers your problem?

**Comment by EugeneDae** [comment]
@tschoonj Yes, exactly.

**Comment by haio** [comment]
@EugeneDae the commands should be
```sh
cd /usr/local
git checkout 7a58ff6e07dd35d438193a2e551cf282c2088a44 /usr/local/Library/Formula/librsvg.rb
brew install librsvg
git checkout master /usr/local/Library/Formula/librsvg.rb
brew pin librsvg
```

**Comment by EugeneDae** [comment]
This no longer works after `brew upgrade`. 

@haio @tschoonj  Could you please help downgrade librsvg to 2.40.10?

**Comment by EugeneDae** [comment]
Ah, figured out I can just do

```
brew install librsvg.rb
```

with librsvg.rb downloaded from [7a58ff6](https://github.com/Homebrew/legacy-homebrew/blob/7a58ff6e07dd35d438193a2e551cf282c2088a44/Library/Formula/librsvg.rb).

**Pull request closed without merging**
