### PR TITLE
youtube-dl 2015.02.09.3

### PR DESCRIPTION
**Pull request by dstftw**

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Duplicate of #36672. Sorry but thanks for the submission!

**Comment by dstftw** [comment]
That's not a duplicate, it's already 2015.02.09.**3** against 2015.02.09.**2**.

**Comment by mikemcquaid** [comment]
Ah, it'll need rebased then. Reopened!

**Comment by asparagui** [comment]
Thanks!

**Pull request closed without merging**
