### PR TITLE
libsigc++ 2.6.2

### PR DESCRIPTION
**Pull request by tschoonj**

### CODE REVIEW

**Comment by tschoonj** [comment]
Something happened to the El Cap bot?

**Comment by bfontaine** [comment]
@BrewTestBot test this please.

**Comment by bfontaine** [comment]
@tschoonj Yes but it should be up now.

**Comment by DomT4** [comment]
> Something happened to the El Cap bot?

There's a backlog to get through since El Cap fell over. You'll be in there somewhere I suspect :wink:

**Comment by tschoonj** [comment]
Ok, thanks

**Comment by dunn** [comment]
Merged in 5fcb4951e06dd83cc94b04ca0538df7ea2db0d37, thanks again!

**Pull request closed without merging**
