### PR TITLE
rubberband audit fixes

### PR DESCRIPTION
**Pull request by enilsen16**

### CODE REVIEW

**Comment by enilsen16** [comment]
Looks like the tests are failing because tuohela.net is down.

**Comment by DomT4** [comment]
We should reassemble the patch using the two linked commits above the patch, submit the new one to https://github.com/Homebrew/patches & then update the link to that and update the checksum to SHA256.

**Comment by enilsen16** [comment]
Retest once https://github.com/Homebrew/patches/pull/6 is merged.

**Comment by DomT4** [comment]
@BrewTestBot test this please

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/bee65311490bdce05011429436aebeceb2c87df3. Thanks again @enilsen16! :smiley_cat:

**Pull request closed without merging**
