### PR TITLE
capstone: fix pkg-config references

### LINKED ISSUE #36871: `pkg-config --cflags` capstone returns wrong path
```
$ brew install capstone
...
$ pkg-config --cflags capstone
-I/usr/include/capstone
$ file /usr/include/capstone
/usr/include/capstone: cannot open `/usr/include/capstone' (No such file or directory)
$ file /usr/local/include/capstone
/usr/local/include/capstone: directory
```

The problem is probably related to the install note:
```
	# Capstone's Make script ignores the prefix env and was installing
    # in /usr/local directly. So just inreplace the prefix for less pain.
    # https://github.com/aquynh/capstone/issues/228
```

### PR DESCRIPTION
**Pull request by DomT4**
Closes #36871.

### CODE REVIEW

**Comment by aquynh** [comment]
Dominyk, will you please merge this fix for Capstone to upstream (Homebrew:master)?

Thanks.

**Comment by DomT4** [comment]
Afraid I don't have the privileges necessary to merge things into Homebrew/Homebrew, only devel-only and versions. One of the maintainers here will need to take a look at this, probably Jack or Mike. It'll be done soon :)

**Comment by aquynh** [comment]
great! some users reported this issue, so hopefully Jack & Mike will look at this soon!

thanks.

**Comment by mikemcquaid** [comment]
Thanks @DomT4!

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
