### PR TITLE
pinentry-mac 0.9.4

### PR DESCRIPTION
**Pull request by chdiza**

### CODE REVIEW

**Comment by chdiza** [comment]
I also removed a patch that appears to no longer be necessary.

**Comment by DomT4** [comment]
Should be safe to remove the resource as well now: https://github.com/GPGTools/pinentry-mac/commit/f2433d688448f5e5e633d305e4f654756083b628

**Comment by chdiza** [comment]
> Should be safe to remove the resource as well now: GPGTools/pinentry-mac@f2433d6

Yeah, caught that right after I PR'd.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/cb6c8dbce7ba7773aafaaae0f0d05a393ca7dfaa. Thanks @chdiza!

**Pull request closed without merging**
