### PR TITLE
gst-python 1.6.1

### PR DESCRIPTION
**Pull request by tschoonj**

### CODE REVIEW

**Comment by DomT4** [comment]
@BrewTestBot test this please

**Comment by DomT4** [comment]
This one still failed on Mavericks, for some reason :confused:.

```
libtool: install: /usr/bin/install -c .libs/_gi_gst.so /usr/local/lib/python2.7/site-packages/gi/overrides/_gi_gst.so
install: /usr/local/lib/python2.7/site-packages/gi/overrides/_gi_gst.so: Operation not permitted
make[3]: *** [install-pygioverridesexecLTLIBRARIES] Error 71
make[2]: *** [install-am] Error 2
make[1]: *** [install-recursive] Error 1
make: *** [install-recursive] Error 1
```

**Comment by tschoonj** [comment]
This probably has to do with `gobject-introspection` bringing in that `:python` dependency on Mavericks. Will look into it...

**Comment by tschoonj** [comment]
fixed!

**Comment by mikemcquaid** [comment]
Thanks @tschoonj!

**Pull request closed without merging**
