### PR TITLE
cake 0.7.0

### PR DESCRIPTION
**Pull request by gep13**
Updated to latest released version of cake

### CODE REVIEW

**Comment by Redth** [comment]
Just to note, I've been sending PR's to update homebrew, however @gep13 is an official maintainer of Cake, and is now taking this task over as part of their release process - good news for all!

**Comment by gep13** [comment]
@Redth :+1:  thanks for all your work in keeping it up to date so far.  Creating these PR's is now a documented part of our release process.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/f3ee93f6b8f5bb37e3dfe9a3b2a740aabe7374ef. Thank you for your contribution to Homebrew @gep13; we appreciate it! :santa: :christmas_tree:.

Thanks also to @Redth for letting us know to expect PRs from someone other than you in future. Cheers for keeping the formula up-to-date in Homebrew thus far!

**Comment by gep13** [comment]
@DomT4 not a problem at all, happy to help!

You may see some PR's from @patriksvensson or @devlead as well, they are the other maintainers of Cake.  It just depends on who is doing the release of Cake.  Thanks.

**Pull request closed without merging**
