### PR TITLE
Updated htop-osx to version 0.8.2.6

### PR DESCRIPTION
**Pull request by max-horvath**

### CODE REVIEW

**Comment by mistydemeo** [comment]
Do you mind squashing this down to one commit?

**Comment by max-horvath** [comment]
Done.

**Comment by DomT4** [comment]
@BrewTestBot test this please

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/d0f491609567c1057ecc51689ce4a13f721171b0. Thank you for your contribution to Homebrew, we appreciate it! :smiley_cat:.

Couple of future nits: `sha256` is now the preferred checksum and version bumps should have their commit message styled `htop-osx 0.8.2.6` or similar, Thanks!

**Pull request closed without merging**
