### PR TITLE
postgresql 9.4.1

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by alex** [comment]
This resolves 5 CVEs: http://www.postgresql.org/about/news/1569/

**Comment by alex** [comment]
Tests fail on mountain lion because the header files shadow the system headers. I don't know how to fix that, or why it's an issue with 9.4.1 but not 9.4.0?

**Comment by DomT4** [comment]
> why it's an issue with 9.4.1 but not 9.4.0?

It is an issue on 9.4.0 as well. Homebrew has just ignored it to date.

**Comment by alex** [comment]
Ah!

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

Also, I've tweaked the audit check in 71b6f44 so it won't happen again.

**Pull request closed without merging**
