### PR TITLE
pull: wait for Bintray publish, don't sleep.

### PR DESCRIPTION
**Pull request by mikemcquaid**
Doesn't seem to work yet but if we can figure out why that'd be handy CC @DomT4 @tdsmith

### CODE REVIEW

**Comment by DomT4** [comment]
It'll probably get lost on the chat, so for reference: https://bintray.com/docs/api/#_publish_discard_uploaded_content

**Comment by mikemcquaid** [comment]
@DomT4 could you point bintray to this and let them know it's not working?

**Comment by DomT4** [comment]
Sure, will do.

**Comment by DomT4** [comment]
screen shot 2015-07-09 at 21 50 11

**Comment by mikemcquaid** [comment]
@DomT4 The script returns a `{"files":3}` but the files aren't published so the feature is working as it was before the documentation.

**Comment by mikemcquaid** [comment]
Just pulled this with the sleep if it doesn't work (it never seems to)

**Comment by DomT4** [comment]
Hmm. Yeah, they do publish, but still with the delay there that requires a sleep. Still trying to debug this with Bintray; Reproduced the error we see with uploads and then immediate fetches and sent them verbose logs of the upload, as well as verbose logs of the curl command we use to retrieve packages.

**Pull request closed without merging**
