### PR TITLE
asciinema 1.0.0

### PR DESCRIPTION
**Pull request by vitorgalvao**

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Looks like the stable checksum changed too. Can you file an issue upstream to ask them why they've changed their tag (and to check they weren't hacked)? Thanks!

**Comment by sickill** [comment]
Tag hasn't been changed but the repo has been renamed from `asciinema/asciinema-cli` to `asciinema/asciinema`. Given that tarballs generated by Github include repo name (as top dir) the checksum should have changed.

**Comment by mikemcquaid** [comment]
@sickill Gotcha, thanks. @vitorgalvao can you update the stable `sha1` too?

**Comment by sickill** [comment]
I have released rc2 today, so please use it for "devel" version instead of rc1. https://github.com/asciinema/asciinema/releases/tag/v1.0.0.rc2

All URLs in this formula should be changed from `https://github.com/asciinema/asciinema-cli/*` to `https://github.com/asciinema/asciinema/*`, including the symlink (https://github.com/vitorgalvao/homebrew/blob/patch-1/Library/Formula/asciinema.rb#L42).

Also, `-v` option has been removed, `--version` should be used in test here https://github.com/vitorgalvao/homebrew/blob/patch-1/Library/Formula/asciinema.rb#L52 .

**Comment by vitorgalvao** [comment]
Thank you, @sickill.

@mikemcquaid Should be done, now.

**Comment by sickill** [comment]
@vitorgalvao thanks!

One thing I realized now is that we also need the old symlink in install step so we still support 0.9.9. I guess creating 2 symlinks would do the trick.

**Comment by vitorgalvao** [comment]
@sickill Good point. Fixed.

**Comment by vitorgalvao** [comment]
@mikemcquaid Not sure what the error is on the second commit, as going to the bot’s page shows everything as passing. Could you guide me here?

**Comment by mikemcquaid** [comment]
@vitorgalvao I've restarted the build, should work this time.

**Comment by vitorgalvao** [comment]
@mikemcquaid Yep, everything looks fine now, thank you. Please let me know if anything more is needed before merging.

**Comment by mnuessler** [comment]
Please note: [v1.0.0](https://github.com/asciinema/asciinema/releases/tag/v1.0.0) has been released recently.

**Comment by vitorgalvao** [comment]
Updated and squashed.

**Comment by sickill** [comment]
Resource definitions can be removed now as all deps are vendored now.

**Comment by vitorgalvao** [comment]
> Resource definitions can be removed now as all deps are vendored now.

I don’t usually write homebrew formulas, so I’m not sure what exactly should be the change.

**Comment by asparagui** [comment]
Thanks!

**Pull request closed without merging**
