### PR TITLE
thefuck 1.40

### PR DESCRIPTION
**Pull request by dunn**

### CODE REVIEW

**Comment by L2G** [comment]
Looks like a @BrewTestBot hiccup to me, but I'm a layman…

**Comment by tdsmith** [comment]
@BrewTestBot wtf

**Comment by DomT4** [comment]
Guys, we overdid it on the requeuing :smile_cat: 

```
Started by user Xu Cheng
Started by user tim smith
Started by user Dominyk Tiller
```

http://bot.brew.sh/job/Homebrew%20Pull%20Requests/25977/

**Comment by xu-cheng** [comment]
Thanks @dunn

**Pull request closed without merging**
