### PR TITLE
Adding a --copy option to linkapps

### PR DESCRIPTION
**Pull request by voiser**

### CODE REVIEW

**Comment by mikemcquaid** [comment]
What's the reasoning for this? I'm not convinced it'll work consistently across apps due to relative linking to libraries.

**Comment by voiser** [comment]
The reason is that Spotlight does not follow symlinks. When using Brew to install a ".app" application (like Emacs or MacVim) it won't be accessible via Spotlight. Many people complain about having to perform extra steps like Automator actions or AppleScript scripts to launch these apps. 

OS X apps should contain all libraries in the .app bundle. If they are well-formed there shouldn't be any linking issues, I think. 

Greetings

**Comment by mikemcquaid** [comment]
> The reason is that Spotlight does not follow symlinks. When using Brew to install a ".app" application (like Emacs or MacVim) it won't be accessible via Spotlight. Many people complain about having to perform extra steps like Automator actions or AppleScript scripts to launch these apps.

We'll need to work on using e.g. Finder aliases. @xu-cheng is working on this in https://github.com/Homebrew/homebrew/pull/35050.

> OS X apps should contain all libraries in the .app bundle. If they are well-formed there shouldn't be any linking issues, I think.

I don't think this is something we can rely on. I know for a fact this doesn't apply to all bundles we install.

**Comment by voiser** [comment]
OK Finder aliases seem to be a good solution.

thanks

**Pull request closed without merging**
