### PR TITLE
scala 2.12.0-M3 (devel)

### PR DESCRIPTION
**Pull request by dpoggi**

### CODE REVIEW

**Comment by dpoggi** [comment]
Errr... brew test works fine locally, looks like it's missing scala-library from org.scala-lang in the Jenkins environment... but whyyyyy...

**Comment by mikemcquaid** [comment]
Does `brew test --devel --verbose --sandbox scala` pass? You can see there's a sandbox write issue in the test: https://travis-ci.org/Homebrew/homebrew/jobs/94924895

**Comment by dpoggi** [comment]
screen shot 2015-12-04 at 2 24 12 pm

**Comment by mikemcquaid** [comment]
Not sure what's going on, I'm afraid, but we'll need to fix this issue before it can be merge :sob:

**Comment by dunn** [comment]
See also #41807 :crying_cat_face:

**Comment by DomT4** [comment]
Passes here as well, on a machine that has never had `scala` installed before:
```
 ~> brew test -v scala --devel
Testing scala
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20151227-75071-xke1b4.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Library/Homebrew -- /usr/local/Library/Homebrew/test.rb /usr/local/Library/Formula/scala.rb -v --devel --devel
==> /usr/local/Cellar/scala/2.12.0-M3/bin/scala /private/tmp/scala20151227-75072-9s7z4k/hello.scala
```

I'd maybe try setting `ENV.java_cache` in `test do` here as a complete hunch, but eh.

**Comment by dpoggi** [comment]
Figured this one out. You can replicate the result of the test locally by installing devel, uninstalling it, then installing stable - it will produce the same error. Running a Scala program as a script (`scala Foo.scala`) starts a Scala CompileServer process in the background. When the tests run on Travis, stable is installed, the tests are run, then stable is uninstalled, devel is installed, and the tests are run again. The problem is, the stable version of CompileServer is still running in the background, so when the tests are run for devel, the newer version of the "scala" command-line tool tries to talk to an older version of the CompileServer, and this error happens. Let's see if this fixes it...

**Comment by dpoggi** [comment]
Wooooooo! That's a pass. @mikemcquaid, I think this is finally ready for merge.

**Comment by DomT4** [comment]
Great sleuthing on chasing the error down here!

Merged in https://github.com/Homebrew/homebrew/commit/bc5581d22e62dca4e5d22b2bc024bf3d0d72c385. Thank you for another contribution to Homebrew @dpoggi! :smiley_cat:

**Pull request closed without merging**
