### PR TITLE
antlr 4.5.1

### PR DESCRIPTION
**Pull request by makigumo**

### CODE REVIEW

**Comment by makigumo** [comment]
This PR should be on hold until https://github.com/antlr/antlr4/issues/961 is resolved.

**Comment by mikemcquaid** [comment]
> This PR should be on hold until antlr/antlr4#961 is resolved.

:+1:

**Comment by parrt** [comment]
i updated the jar via maven for 4.5.1 to 4.5.1-1. will copy to my website as well.

**Comment by makigumo** [comment]
Thanks @parrt
PR is updated with sha256 of corrected version.

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
