### PR TITLE
Woff2 compress and decompress

### PR DESCRIPTION
**Pull request by prieb**
Compile woff2_compress and woff2_decompress from [Google Woff2 Github repository](https://github.com/google/woff2)

### CODE REVIEW

**Comment by DomT4** [comment]
We don't accept private forks. The release here would actually need to come from Google's upstream repo. Google have been good about tagging releases when requested by Homebrew, so it's worthwhile asking.

**Comment by prieb** [comment]
Hi @DomT4 !
I make an repository to add test.
I've to add a font to test woff2_compress. The only arg that woff2_compress accept its a font file.

**Comment by mikemcquaid** [comment]
Passing on this as it's a personal fork, sorry!

**Comment by deathbaba** [comment]
So no woff2 in homebrew yet.

**Comment by DomT4** [comment]
Waiting on an [upstream release](https://github.com/google/woff2/issues/40). You can use the formula in `head-only` at the moment if desired:
```
brew install homebrew/head-only/woff2
```

**Comment by deathbaba** [comment]
Thanks!

**Pull request closed without merging**
