### PR TITLE
move formula_specialties to compat

### PR DESCRIPTION
**Pull request by xu-cheng**
@jacknagel I don't know how to handle `formula_specialties` references from `audit` and test. Ping for help.

### CODE REVIEW

**Comment by jacknagel** [comment]
I think we need to continue requiring it from `formula.rb`, otherwise it will break downstream formulae that reference these classes. So I don't know that moving it is the right thing to do at this point.

**Comment by jacknagel** [comment]
Or perhaps we can just define a dummy `class Formula; end` at the top of the file. I'll look at it later.

**Comment by xu-cheng** [comment]
> I think we need to continue requiring it from formula.rb, otherwise it will break downstream formulae that reference these classes.

No, it won't. There is a `compat/formula.rb`.

What's really broken is if a user chooses `--no-compat`, it will break the reference from `audit.rb`. So should I add a `no-compat` check in `audit.rb` and possible homebrew test?

**Comment by jacknagel** [comment]
I don't think anyone has ever used `--no-compat`, so I wouldn't worry about it. I'm not sure why it even exists to be honest.

**Comment by jacknagel** [comment]
As far as the tests go, you should be able to just require compat/formula_specialties from test_formula_install.rb

**Comment by xu-cheng** [comment]
Ready to merge, or more comment ?

**Comment by jacknagel** [comment]
lgtm

**Comment by xu-cheng** [comment]
:ship:

**Pull request closed without merging**
