### PR TITLE
Move ticcutils, timbl, wopr to homebrew/science.

### PR DESCRIPTION
**Pull request by dpo**
See #36773.

### CODE REVIEW

**Comment by xu-cheng** [comment]
Shouldn't you do the actually moving besides updating tap_migrations.rb?

**Comment by mikemcquaid** [comment]
Yeh, this needs to delete those formulae from here, thanks!

**Comment by dpo** [comment]
Duh. Sorry. Is anything else needed to migrate formulas?

**Comment by mikemcquaid** [comment]
A link to the corresponding science PR would be handy too, thanks!

**Comment by dpo** [comment]
Will do. Is there a smart way to move the formulas along with their history?

**Comment by xu-cheng** [comment]
http://tomrobertshaw.net/2013/09/migrate-file-to-a-new-git-repository-while-preserving-version-history/

However, what's homebrew policy on this? should we preserve history?

**Comment by mikemcquaid** [comment]
We don't preserve history for imported formulae.

**Comment by dpo** [comment]
homebrew/science PR: https://github.com/Homebrew/homebrew-science/pull/1913

**Comment by xu-cheng** [comment]
Sorry about the late. :ship:ed.

**Pull request closed without merging**
