### PR TITLE
sourcekitten 0.7.3

### PR DESCRIPTION
**Pull request by jpsim**
Thanks!

### CODE REVIEW

**Comment by apjanke** [comment]
Test failed on Jenkins Yosemite only.

```

*** Bootstrapping Carthage/Checkouts/Commandant...
xcodebuild -workspace 'SourceKitten.xcworkspace' -scheme 'sourcekitten' DSTROOT=/private/tmp/sourcekitten20151230-17765-1u2d9oh/SourceKitten.dst install
Build settings from command line:
    DSTROOT = /private/tmp/sourcekitten20151230-17765-1u2d9oh/SourceKitten.dst

Could not find service "com.apple.CoreSimulator.CoreSimulatorService" in domain for uid: 502
2015-12-30 17:27:18.120 xcodebuild[21212:1987766] launchctl print returned an error code: 28928
2015-12-30 17:27:18.120 xcodebuild[21212:1987766] Failed to locate a valid instance of CoreSimulatorService in the bootstrap.  Adding it now.
Could not find service "com.apple.CoreSimulator.CoreSimulatorService" in domain for uid: 502
2015-12-30 17:27:18.129 xcodebuild[21212:1987766] launchctl print returned an error code: 28928
2015-12-30 17:27:18.129 xcodebuild[21212:1987766] *** Assertion failure in -[SimServiceContext reloadServiceIfMovedOrAbortIfWeAreInvalid], /BuildRoot/Library/Caches/com.apple.xbs/Sources/CoreSimulator/CoreSimulator-201.3/CoreSimulator/SimServiceContext.m:451
** INTERNAL ERROR: Uncaught exception **
Exception: Unable to lookup com.apple.CoreSimulator.CoreSimulatorService in the bootstrap.  This can happen if running with a sandbox profile.  When running with a sandbox profile, make sure that com.apple.CoreSimulator.CoreSimulatorService.xpc is owned by root, not group writable, and not world writable.  See <rdar://problem/22142915>.
Stack:
=== BUILD TARGET SWXMLHash OSX OF PROJECT SWXMLHash WITH CONFIGURATION Release ===

Check dependencies
  0  0x00007fff8d80c024 __exceptionPreprocess (in CoreFoundation)
  1  0x00007fff8dcd976e objc_exception_throw (in libobjc.A.dylib)
  2  0x00007fff8d80be1a +[NSException raise:format:arguments:] (in CoreFoundation)
  3  0x00007fff8faae99b -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] (in Foundation)
  4  0x000000010db932e5 -[SimServiceContext reloadServiceIfMovedOrAbortIfWeAreInvalid] (in CoreSimulator)
  5  0x000000010db93c03 -[SimServiceContext connect] (in CoreSimulator)
  6  0x000000010db928bc -[SimServiceContext initWithConnectionType:] (in CoreSimulator)
  7  0x000000010db9241a +[SimServiceContext simContextWithConnectionType:] (in CoreSimulator)
  8  0x000000010db923cb __41+[SimServiceContext sharedServiceContext]_block_invoke (in CoreSimulator)
  9  0x00007fff98476e73 _dispatch_client_callout (in libdispatch.dylib)
 10  0x00007fff98476d86 dispatch_once_f (in libdispatch.dylib)
 11  0x000000010db923a9 +[SimServiceContext sharedServiceContext] (in CoreSimulator)
 12  0x000000010dbb241a +[SimDeviceSet setForSetPath:] (in CoreSimulator)
 13  0x000000010dbb23b6 +[SimDeviceSet defaultSet] (in CoreSimulator)
 14  0x0000000111491fe0 __42-[DVTiPhoneSimulatorLocator startLocating]_block_invoke (in IDEiOSSupportCore)
 15  0x0000000107bcda58 __DVTDispatchAsync_block_invoke (in DVTFoundation)
 16  0x00007fff9847a700 _dispatch_call_block_and_release (in libdispatch.dylib)
 17  0x00007fff98476e73 _dispatch_client_callout (in libdispatch.dylib)
 18  0x00007fff98479dc7 _dispatch_root_queue_drain (in libdispatch.dylib)
 19  0x00007fff98479a1c _dispatch_worker_thread3 (in libdispatch.dylib)
 20  0x00007fff92558a9d _pthread_wqthread (in libsystem_pthread.dylib)
 21  0x00007fff925563dd start_wqthread (in libsystem_pthread.dylib)

make: *** [installables] Abort trap: 6
==> Formula
Path: /usr/local/Library/Formula/sourcekitten.rb
```

That's kind of interesting, and I don't know what to make of it. Any thoughts, folks?

**Comment by jpsim** [comment]
Given this is a command line OS X app, I think a failure to launch the iOS simulator is unrelated. I've seen several other such CI environment failures in Homebrew PRs in the last few months.

**Comment by apjanke** [comment]
It's a command line app, but it's building with an .xcodeproj file, which isn't a basic command-line build tool, AFAIK. Xcode 6.2 on 10.9 crashes when I try to open this project file. I think maybe we should take a closer look at the build/project files in this distribution. Maybe there's an unneeded reference to iOS stuff in the project definition; we've seen unneeded framework etc references in Xcode-project-based distributions before, too.

**Comment by mikemcquaid** [comment]
Regardless, it either needs to build on 10.9 or marked as a depending on 10.10 before it can be merged.

**Comment by apjanke** [comment]
It does build on 10.9; it's only 10.10 where the failure happened. Reason to take a closer look imho.

**Comment by apjanke** [comment]
(The 10.9 Xcode crash was only when I tried to open the project file locally in interactive Xcode. I didn't reproduce the error from the CI machine.)

**Comment by mikemcquaid** [comment]
Sorry, misread with another PR :+1:

**Comment by mikemcquaid** [comment]
Kicked off a rebuild.

**Comment by jpsim** [comment]
For reference, #47151 passed all CI tests about two weeks ago and there have been no changes relating to this project's build system since: https://github.com/jpsim/SourceKitten/compare/0.7.2...0.7.3.

Also for reference, previous PRs that succeeded all CI checks for this project: #45872, #46300, #46953, #46981.

**Comment by DomT4** [comment]
The Yosemite CI hard crashed yesterday and the failure here was a consequence of that. I've fixed it, build should pass now.

**Comment by DomT4** [comment]
There ya go, we're golden. Or green, perhaps, more accurately.

Merged in https://github.com/Homebrew/homebrew/commit/526eb9ea69b1d71a93c61ff81dd3b0183e0fdcdf. Thank you for another Homebrew contribution @jpsim! :smiley_cat:

**Pull request closed without merging**
