### PR TITLE
[mono] properly support HEAD building

### PR DESCRIPTION
**Pull request by haf**
http://www.mono-project.com/docs/compiling-mono/mac/#building-mono-from-a-release-package

### CODE REVIEW

**Comment by mistydemeo** [comment]
Can you provide build logs (`brew gist-logs mono`) for the build that failed in #36766? Thanks!

**Comment by mistydemeo** [comment]
The error is:

```
*** The compiler 'mcs' doesn't appear to be usable.
*** Trying the 'monolite' directory.
Corlib not in sync with this runtime: expected corlib version 117, found 111.
Loaded from: /private/tmp/mono-nEz281/mcs/class/lib/monolite/mscorlib.dll
Download a newer corlib or a newer runtime at http://www.mono-project.com/download.
```

Looks like `HEAD` requires a newer monolite to build.

**Comment by haf** [comment]
I'm not getting that error message https://gist.github.com/anonymous/797deb26ad692fbf60ba 

To fix your error I can change this piece of the formula:

```
  1 ¬
  2   resource "monolite" do¬
  3     magic_number = "111"¬
  4     url "http://storage.bos.xamarin.com/mono-dist-master/cb/cb33b94c853049a43222288ead1e0cb059b227    83/monolite-111-latest.tar.gz"¬
  5     sha1 "a674c47cd60786c49185fb3512410c43689be43e"¬
  6   end¬
```

However, do we have the same error, to start with?

The builds are taking from here: https://wrench.mono-project.com/Wrench/ViewWorkTable.aspx?lane_id=4&host_id=21&command_id=374

I could code ruby to pick the latest version based on the link -- the magic number is the [`MONO_CORLIB_VERSION`](http://wrench.mono-project.com/Wrench/WebServices/Download.aspx?workfile_id=3726729) which needs to be 117 in your case.

Can I get the sha1-commit-hash of the HEAD from the formula DSL, somehow? That would solve the problem of finding the path, given that I can make `monolite-latest.tgz` the name o the file.

I'm having a conversation in general about [making this build more repeatable](https://bugzilla.xamarin.com/show_bug.cgi?id=26842) - if you would comment with all your experience in making homebrew work, it would add considerable value to the discussion.

**Comment by jacknagel** [comment]
PR no longer applies cleanly; what is the status here?

**Comment by haf** [comment]
You didn't respond so it became stale; the PR needs to be updated with the latest monolite.

**Comment by jacknagel** [comment]
>Can I get the sha1-commit-hash of the HEAD from the formula DSL, somehow?

You can get it at build-time (during install) by asking git for it (e.g. `git rev-parse HEAD` or similar), the full git repo is present for the build.

**Comment by DomT4** [comment]
Any update here?

**Comment by haf** [comment]
@DomT4 No time here. I suggest you pick up where I left off and send a new PR with both mine and your changes and then we'll merge that PR instead.

**Comment by mikemcquaid** [comment]
Passing on this.

**Pull request closed without merging**
