### PR TITLE
qt: bump revision for new OpenSSL linkage

### PR DESCRIPTION
**Pull request by tdsmith**
Per discussion in #44388.

### CODE REVIEW

**Comment by tdsmith** [comment]
Oof, the test is bad:
```
==> /private/tmp/qt20151003-63754-1ti2kiv/qtnetwork-test 2>&1
Error: qt: failed
invalid byte sequence in US-ASCII
```

**Comment by tdsmith** [comment]
Dunno why codequery is still broken; it works locally for me :/

**Comment by jkarneges** [comment]
It seems unlikely the problem would be in qt, unless the issue can be traced to some kind of openssl loading error (since nothing else was changed). Can the patch still be merged?

**Comment by tdsmith** [comment]
Oh! Yes, sorry, I got halfway through pulling this and then got distracted.

**Comment by tdsmith** [comment]
Revision landed as 18e7a2bb32.

**Pull request closed without merging**
