### PR TITLE
arm-none-eabi-gcc 20150921 (new formula)

### PR DESCRIPTION
**Pull request by nitsky**

### CODE REVIEW

**Comment by mikemcquaid** [comment]
This is a better fit for a tap. Sorry!

**Comment by bfontaine** [comment]
Here are the docs: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-to-Create-and-Maintain-a-Tap.md

**Comment by adzenith** [comment]
Tap already exists, if anybody comes here later: https://github.com/nitsky/homebrew-stm32

**Comment by adzenith** [comment]
@mikemcquaid: was this rejected because it's too niche? This compiler can be used for any embedded ARM core, like some Arduinos, quadcopters, electronics, etc. I recommended to @nitsky that he try to get it merged after I spent a while trying to figure out which of the various implementations of this formula worked and were up to date.
Thanks!

**Comment by mikemcquaid** [comment]
I just think a tap is a better fit for this. It doesn't look like a stable release, doesn't really have a homepage, doesn't pass `brew audit --strict --online` and it's unclear what I'd use it for (and how I'd know that).

**Comment by adzenith** [comment]
Gotcha! All valid reasons. :) Thanks for your consideration!

**Comment by kaidokert** [comment]
Good candidate for a cask : https://launchpad.net/gcc-arm-embedded

**Pull request closed without merging**
