### PR TITLE
add Formula: python-virtualenv

### PR DESCRIPTION
**Pull request by jptomo**
I want use virtualenv under homebrew.

Please merge me.

### CODE REVIEW

**Comment by xu-cheng** [comment]
It should be installed by `pip` rather than brew

**Comment by jptomo** [comment]
pip can, but use pip under homebrew, it pollute brew's site-package.

I prefar to use manage virtualenv without pip.

**Comment by tdsmith** [comment]
"pip can, but use pip under homebrew, it pollute brew's site-package."

Is this a problem?

I'd rather not package virtualenv because it'll cause confusion when new virtualenvs default to using the system Python version. You're welcome to host the formula yourself but I don't think Homebrew adds much value here.

**Comment by mikemcquaid** [comment]
Agreed with @tdsmith here: passing on this, sorry!

**Pull request closed without merging**
