### PR TITLE
Upgrade mpich to 3.2

### PR DESCRIPTION
**Pull request by jenshnielsen**

### CODE REVIEW

**Comment by bfontaine** [comment]
The build is failing on all platforms:
```
configure: error: No Fortran 77 compiler found. If you don't need to
        build any Fortran programs, you can disable Fortran support using
        --disable-fortran. If you do want to build Fortran
        programs, you need to install a Fortran compiler such as gfortran
        or ifort before you can proceed.
```

**Comment by jenshnielsen** [comment]
I guess this is the same issue as in #46461?

**Comment by jenshnielsen** [comment]
And #45730

**Comment by mikemcquaid** [comment]
The dependency issue is fixed in https://github.com/Homebrew/homebrew/issues/46916. If you rebase this pull request it should be sorted.

**Comment by jenshnielsen** [comment]
@mikemcquaid Thanks, rebase done

**Comment by jenshnielsen** [comment]
Not sure why but the test is failing on yosemite

```
/usr/local/Cellar/mpich/3.2/bin/mpirun
-np
4
./hello
Fatal error in MPI_Init: Other MPI error, error stack:
MPIR_Init_thread(474)..............: 
MPID_Init(190).....................: channel initialization failed
MPIDI_CH3_Init(89).................: 
MPID_nem_init(320).................: 
MPID_nem_tcp_init(173).............: 
MPID_nem_tcp_get_business_card(420): 
MPID_nem_tcp_init(379).............: gethostbyname failed, Traviss-Mac-95.local (errno 1)
Fatal error in MPI_Init: Other MPI error, error stack:
MPIR_Init_thread(474)..............: 
MPID_Init(190).....................: channel initialization failed
MPIDI_CH3_Init(89).................: 
MPID_nem_init(320).................: 
MPID_nem_tcp_init(173).............: 
MPID_nem_tcp_get_business_card(420): 
MPID_nem_tcp_init(379).............: gethostbyname failed, Traviss-Mac-95.local (errno 1)
Fatal error in MPI_Init: Other MPI error, error stack:
MPIR_Init_thread(474)..............: 
MPID_Init(190).....................: channel initialization failed
MPIDI_CH3_Init(89).................: 
MPID_nem_init(320).................: 
MPID_nem_tcp_init(173).............: 
MPID_nem_tcp_get_business_card(420): 
MPID_nem_tcp_init(379).............: gethostbyname failed, Traviss-Mac-95.local (errno 1)
Fatal error in MPI_Init: Other MPI error, error stack:
MPIR_Init_thread(474)..............: 
MPID_Init(190).....................: channel initialization failed
MPIDI_CH3_Init(89).................: 
MPID_nem_init(320).................: 
MPID_nem_tcp_init(173).............: 
MPID_nem_tcp_get_business_card(420): 
MPID_nem_tcp_init(379).............: gethostbyname failed, Traviss-Mac-95.local (errno 1)
Error: mpich: failed
Failed executing: /usr/local/Cellar/mpich/3.2/bin/mpirun -np 4 ./hello
/usr/local/Library/Homebrew/formula.rb:1471:in `block in system'
/usr/local/Library/Homebrew/formula.rb:1408:in `open'
/usr/local/Library/Homebrew/formula.rb:1408:in `system'
/usr/local/Library/Formula/mpich.rb:68:in `block in <class:Mpich>'
/usr/local/Library/Homebrew/formula.rb:1317:in `block in run_test'
/usr/local/Library/Homebrew/extend/fileutils.rb:17:in `mktemp'
/usr/local/Library/Homebrew/formula.rb:1313:in `run_test'
/usr/local/Library/Homebrew/test.rb:28:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/usr/local/Library/Homebrew/test.rb:27:in `<main>'
```

**Comment by smseo** [comment]
It looks like a host configure issue. The error means the hostname Traviss-Mac-95.local is unknown.

**Comment by UniqMartin** [comment]
Merged in d6baf11b42d7432e380c91e54cf86022c7ccd015. Thank you for this PR @jenshnielsen; your contribution to Homebrew is much appreciated! :tada:

**Pull request closed without merging**
