### PR TITLE
nimrod: fix sha1

### LINKED ISSUE #36868: nimrod formula gives SSL / SHA1 errors
```
$ brew install nimrod
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/nimrod-0.10

curl: (60) SSL certificate problem: Invalid certificate chain
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
Error: Failed to download resource "nimrod"
Download failed: https://downloads.sf.net/project/machomebrew/Bottles/nimrod-0.10.2.yosemite.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading http://nim-lang.org/download/nim-0.10.2.zip
######################################################################## 100.0%
Error: SHA1 mismatch
Expected: 0a54d6d7f257cdade5bf950d318066959c48a6dc
Actual: 2fdd486704931807d03d25d6846c5faee880d69e
Archive: /Library/Caches/Homebrew/nimrod-0.10.2.zip
To retry an incomplete download, remove the file above.
```
The certificate error is CloudFront:
image

And the SHA1 mismatch for the source zip? The actual SHA1 is what I get doing it manually too.

### PR DESCRIPTION
**Pull request by DomT4**
Closes #36868.

### CODE REVIEW

**Comment by tdsmith** [comment]
Can you verify this was an intentional change?

**Comment by DomT4** [comment]
https://github.com/Araq/Nim/issues/2152

**Comment by tdsmith** [comment]
Thanks!

**Comment by DomT4** [comment]
I verified the PolarSSL checksum change earlier today upstream, but got kinda lazy on Nim. My apologies :sweat_smile:.

**Comment by DomT4** [comment]
Upstream are happy with the SHA change. They repacked for docs about a month or so ago apparently.

**Pull request closed without merging**
