### PR TITLE
enable static lib for harfbuzz

### PR DESCRIPTION
**Pull request by jeroenooms**
I am trying to statically link librsvg into my application but the static library for harfbuzz is missing.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Does this still create the shared library?

**Comment by jeroenooms** [comment]
Yes, `--enable-static ` builds the static library in addition to the default (shared) libraries.

**Comment by mikemcquaid** [comment]
Thinking about this (and the other PRs) more: I think it should be behind a `with-static` option (for now at least) to avoid packages linking statically that don't intend to.

**Comment by jeroenooms** [comment]
That won't be an issue, the OSX linker always prefers dynamic linking if possible. You would really need to force it to static. It would be really nice if the static libraries were included by default in the bottles, so that my users don't have to build them locally.

**Comment by jeroenooms** [comment]
There are a few precedents, see e.g. the discussion at my previous pull request: https://github.com/Homebrew/homebrew/pull/43782

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

For future reference the preferred commit message format is `harfbuzz: install static library.`.

**Pull request closed without merging**
