### PR TITLE
Cleanup requirements

### PR DESCRIPTION
**Pull request by mikemcquaid**
- Rename all requirements named `*Dependency` because they aren't `Dependency` subclasses and it looks like they are otherwise.
- Add a `RubyRequirement` and the `depends_on :ruby` syntax.
- General requirement cleanup given the above.

CC @Homebrew/owners for review.

### CODE REVIEW

**Comment by xu-cheng** [comment]
I suggest we make `depends_on :ruby => "1.9+"` as requiring 1.9 and above, then let `depends_on :ruby => "1.9"` mean 1.9.x only.

Therefore, we will have a similar syntax with `depends_on :java`.

**Comment by mikemcquaid** [comment]
> I suggest we make depends_on :ruby => "1.9+" as requiring 1.9 and above, then let depends_on :ruby => "1.9" mean 1.9.x only.

I can't think of any reason you'd want Ruby 1.9 and not 2.0 but these cases do exist for Java. Also, the current Ruby syntax matches e.g. Xcode or XQuartz dependencies; Java is the exception rather than the rule.

**Comment by xu-cheng** [comment]
OK. Thanks for explaining.

**Comment by jacknagel** [comment]
We can't change class names of any requirements in core. It will break compatibility.

**Comment by mikemcquaid** [comment]
@jacknagel Could I alias them and print a warning?

**Comment by jacknagel** [comment]
I guess, but I don't see the upside here. `Dependency` is private and isn't something formula writers need or are allowed to subclass. Has anyone ever actually been confused by this? And did it ultimately matter?

**Comment by mikemcquaid** [comment]
> Has anyone ever actually been confused by this?

Me, multiple times.

> And did it ultimately matter?

To me it matters as much as any code refactoring does, really.

**Comment by mikemcquaid** [comment]
I'll check the official Homebrew taps but I'd be really surprised if any taps outside of them are using the internally provided Requirements rather than the `depends_on` symbol format.

**Comment by mikemcquaid** [comment]
Made this PR just about the Ruby requirement and using `:gpg` instead. Will open another to rename requirements.

**Pull request closed without merging**
