### PR TITLE
Update pebble-sdk to 2.9

### PR DESCRIPTION
**Pull request by a2**

### CODE REVIEW

**Comment by jacknagel** [comment]
relevant: https://github.com/Homebrew/homebrew/pull/35128

**Comment by a2** [comment]
@jacknagel Ah, thanks! Didn't see that.

**Comment by vszakats** [comment]
I suggest using an https `url`, this works well:
https://s3.amazonaws.com/assets.getpebble.com/sdk2/PebbleSDK-2.9.tar.gz

**Comment by jacknagel** [comment]
Looks like this will probably be removed from core (#35128) so passing on this update.

**Pull request closed without merging**
