### PR TITLE
letsencrypt 0.4.0 (new formula)

### PR DESCRIPTION
**Pull request by DomT4**
I am the latest human being _(most days)_ to attempt to work `letsencrypt` into Homebrew. So, here we go again.

CC @tdsmith, @jab, @mikemcquaid, @joneskoo & anyone else who commented in the other PRs and wants to here.

### CODE REVIEW

**Comment by DomT4** [comment]
Test is the known `.pyc` issue. Not sure if/what Tim decided we should do on that in the end.

**Comment by joneskoo** [comment]
@DomT4 Thanks. Looks like you have cleaned the formula a bit and updated
versions.

Can you comment if sudo is required to use this and if this now works with
e.g. web servers packaged in brew? What would the user have to do? I think
it's important to meet first user expectations (get LE cert to a web
server, with autorenew) by providing the next steps in caveats.

**Comment by DomT4** [comment]
> Looks like you have cleaned the formula a bit and updated versions.

Yeah, more or less. Haven't done anything drastic in terms of the last PRs here (Indeed, the last PR forms the base of this one). The only completely new change is installing the experimental `nginx` plugin as well.

> Can you comment if sudo is required to use this

I believe so, due to it wanting to write to `/etc/letsencrypt`. It wouldn't be a first in `brew`; there are formulae that are known to require `sudo` for any significant functionality.

> if this now works with e.g. web servers packaged in brew? What would the user have to do?

It seems to have that option with at least the plugins. If you do `letsencrypt --help apache` for example you can feed it overrides to alternative paths:
```
apache:
  Apache Web Server - Alpha

  --apache-enmod APACHE_ENMOD
                        Path to the Apache 'a2enmod' binary. (default:
                        a2enmod)
  --apache-dismod APACHE_DISMOD
                        Path to the Apache 'a2dismod' binary. (default:
                        a2dismod)
  --apache-le-vhost-ext APACHE_LE_VHOST_EXT
                        SSL vhost configuration extension. (default: -le-
                        ssl.conf)
  --apache-server-root APACHE_SERVER_ROOT
                        Apache server root directory. (default: /etc/apache2)
  --apache-vhost-root APACHE_VHOST_ROOT
                        Apache server VirtualHost configuration root (default:
                        /etc/apache2/sites-available)
  --apache-challenge-location APACHE_CHALLENGE_LOCATION
                        Directory path for challenge configuration. (default:
                        /etc/apache2)
```

**Comment by DomT4** [comment]
Rewrote the test fairly extensively in https://github.com/DomT4/homebrew/commit/cf62d9500296a41ea199b073bfecd1d546384c07. If that passes I'm likely to merge this, because well, I have plans for it :smile:.

**Comment by tdsmith** [comment]
dumb question: why fork?

**Comment by DomT4** [comment]
Well, I was going to say because it launches a terminal GUI that doesn't exit entirely cleanly using the normal `system` method, but then it failed CI after passing locally 6/7 times in a row. Sigh :smile:.

**Comment by felixbuenemann** [comment]
Btw. 0.4.0 is out. The fork stuff in `test` looks nasty, it also won't work on 0.4.0 because:

```bash
brew test letsencrypt
# ...
The manual plugin is not working; there may be problems with your existing configuration.
The error was: PluginError('Running manual mode non-interactively is not supported',)
```

Here's the required changes for 0.4.0:

```diff
--- letsencrypt.rb	2016-02-13 01:20:57.000000000 +0100
+++ letsencrypt.rb	2016-02-13 01:19:29.000000000 +0100
@@ -1,8 +1,8 @@
 class Letsencrypt < Formula
   desc "Tool to automatically receive and install X.509 certificates"
   homepage "https://letsencrypt.org/"
-  url "https://github.com/letsencrypt/letsencrypt/archive/v0.3.0.tar.gz"
-  sha256 "a21e496ab130cf9fcaeef69019a4eef7aaf86dad84131d601db531add4f98e1a"
+  url "https://github.com/letsencrypt/letsencrypt/archive/v0.4.0.tar.gz"
+  sha256 "d7df1faedd6f5c1ffc26fd855350fc3a107dd9fe5c1c2aa4c340024fe807a0f3"
 
   depends_on "augeas"
   depends_on "dialog"
@@ -94,6 +94,11 @@
     sha256 "f0a26070d6db0881de8bcc7846934b7c3c930d8f9c79d45883ee48984bc0d672"
   end
 
+  resource "pyparsing" do
+    url "https://pypi.python.org/packages/source/p/pyparsing/pyparsing-2.1.0.tar.gz"
+    sha256 "f6cb2bc85a491347c3c699db47f7ecc02903959156b4f92669ebf82395982901"
+  end
+
   resource "pyRFC3339" do
     url "https://pypi.python.org/packages/source/p/pyRFC3339/pyRFC3339-1.0.tar.gz"
     sha256 "8dfbc6c458b8daba1c0f3620a8c78008b323a268b27b7359e92a4ae41325f535"

```
The required version of pyparsing is `pyparsing>=1.5.5`, I just added the latest one.

**Comment by felixbuenemann** [comment]
**Regarding sudo usage:** Couldn't letsencrypt be configure to check in `/usr/local/etc` by default?

**Comment by DomT4** [comment]
> Btw. 0.4.0 is out. The fork stuff in test looks nasty, it also won't work on 0.4.0 because:

Already addressed both these things locally. Just hadn't pushed yet :wink:. It's public now.

> pyparsing

This didn't appear for me when I stuck it in a `virtualenv`. Is it definitely required for Python2?

> Regarding sudo usage: Couldn't letsencrypt be configure to check in /usr/local/etc by default?

Not easily, as far as I can see, unless we patch `constants.py` which is pretty blunt. Users can pass different directories on the command line which seems reasonable to me.

More or less though, you will need some `sudo` usage for real-world operation of LE because it wants to do things like bind port 443, which OS X will tend you to go away for trying without `sudo`.

**Comment by felixbuenemann** [comment]
You can't bind any ports below 1024 without root permissions.

Regarding pyparsing it fails for me if not installed, although I'm running python2:

```
$ python -V
Python 2.7.11
$ letsencrypt --version
An unexpected error occurred:
DistributionNotFound: The 'pyparsing>=1.5.5' distribution was not found and is required by the application
Please see the logfile 'letsencrypt.log' for more details.
```

**Comment by felixbuenemann** [comment]
Oh, and you forgot to change the version in the title of the PR.

**Comment by DomT4** [comment]
> You can't bind any ports below 1024 without root permissions.

Indeed :wink:. I was trying to be lightly humorous about it.

> Regarding pyparsing it fails for me if not installed

Huh, that's strange. I'll check out virtualenv again. It is mentioned upstream by the notation by the side of it says `# Python3 support; perhaps unnecessary?`

**Comment by felixbuenemann** [comment]
The pyparsing module is imported unconditionally by the nginx parser. The comment probably notes that at least version 1.5.5 is needed for python3 support.

**Comment by DomT4** [comment]
I'm giving up on being able to test this properly in Homebrew for now. If the terrible test passes, I'll take the terrible test temporarily.

**Comment by felixbuenemann** [comment]
Ar leas showing the version lots all python dependencies, so it's not that bad. There is a staging system that can create invalid certs for testing, but I don't think you want network connecticity in `test`.

**Comment by DomT4** [comment]
Alright, I'm perfectly happy to take further improvements here in future PRs but we've been going back and forwards on this in various PRs for months now and I'm keen to move ahead. Merged.

**Pull request closed without merging**
