### PR TITLE
libcdr 0.1.1

### PR DESCRIPTION
**Pull request by luzpaz**
Changed the target compression from tar.bz2 to tar.xz to save 94kb. 
Also future changes will keep the tar.xz

### CODE REVIEW

**Comment by bfontaine** [comment]
> Changed the target compression from tar.bz2 to tar.xz to save 94kb.

Does it really matter since the formula is bottled?

**Comment by mikemcquaid** [comment]
It also adds a dependency that's not provided by OS X. Please change it back, thanks.

**Comment by luzpaz** [comment]
Other Document Liberation of the librevenge suite use .xz and therefor will already have installed xz dependency. There is a probability that people will also install some of these:
```brew cat libetonyek | grep .xz```
Same for libmspub, libvisio, libpagemaker,

**Comment by mikemcquaid** [comment]
That's fine either way, just don't think the size factor makes a big difference and generally we prefer to avoid `xz` unless necessary. Thanks!

**Comment by luzpaz** [comment]
Ok. No problem. Cancelling PR.

**Comment by mikemcquaid** [comment]
Thanks!

**Pull request closed without merging**
