### PR TITLE
Added libiomp's include dir to clang search paths.

### PR DESCRIPTION
**Pull request by metacollin**

### CODE REVIEW

**Comment by xu-cheng** [comment]
So  `#include <libiomp/omp.h>` should be `#include <omp.h>` in test case. Right?

**Comment by metacollin** [comment]
....yes.  I can't believe I over looked that.  Sorry, fixing now.

**Comment by metacollin** [comment]
Fixed.

**Comment by xu-cheng** [comment]
Tithe build failed. You may try to change the building system to cmake. (llvm.rb has the similar change recently, if you need a reference).

**Comment by metacollin** [comment]
I've always favor of moving to cmake.  :D I am going to bed but I'll do it first thing tomorrow morning.  Thanks!

**Comment by metacollin** [comment]
Hi, I've migrated the formula to cmake.  Unfortunately, it is not quite as elegant and adds a number of lines to the formula, the min macosx version flags are vital, or compiler-rt will attempt to cross-compile for ARM (which fails hard) etc.   But I ran brew audit and built (and am using) the new binary from the updated formula and it both finds <omp.h> in its new location and all other headers it should, and seems to be issue free (at least on my system).

But I'll see what the build bot says :)

**Comment by xu-cheng** [comment]
Thanks for the pull request! 🎉 Homebrew depends on contributions from community members like you and we're grateful for your support.

**Comment by tdsmith** [comment]
:saxophone::turtle: :+1:

**Pull request closed without merging**
