### PR TITLE
postgrest 0.3.0.1

### PR DESCRIPTION
**Pull request by xDAGRONx**

### CODE REVIEW

**Comment by begriffs** [comment]
When I build the release binary I run the `strip` program on it which makes the binary smaller. Do you think you could add that step to the brew build process?

**Comment by xDAGRONx** [comment]
I can probably manage that. Does it need to run with any particular set of arguments?

**Comment by xDAGRONx** [comment]
The package uses `cabal install`. Would the `--enable-executable-stripping` or `--enable-library-stripping` options accomplish the same thing?

**Comment by begriffs** [comment]
You're right, it appears that `--enable-executable-stripping` will call `strip` for you.

**Comment by xDAGRONx** [comment]
Awesome. I'll add that to the formula.

**Comment by begriffs** [comment]
Yay it passes the tests now! Once you add `--enable-executable-stripping` and it keeps passing the tests do you know how we get somebody to merge it?

**Comment by xDAGRONx** [comment]
When I created the formula, someone merged it within a day of the tests passing. I was planning on adding the flag as a separate commit after it got merged, but I didn't expect it to take this long.

**Comment by DomT4** [comment]
Apologies. I've actually looked over this quite a few times over the last couple days and presumed I should wait on you to add the requested flag. Didn't realise you were waiting on us to merge. Will do that now :wink:

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/926b8be64718849f12ffc4ddd7af4fcb3a61f35c. Thank you for another contribution to Homebrew @xDAGRONx; we appreciate it! :smiley_cat:

**Pull request closed without merging**
