### PR TITLE
gambit-scheme 4.7.7

### PR DESCRIPTION
**Pull request by nijikon**

### CODE REVIEW

**Comment by nijikon** [comment]
Can we reschedule? This should pass and take significantly less time to build.

**Comment by DomT4** [comment]
Failed again :confused:. Builds in 10 minutes on Yosemite, but Mavericks and ML just hang.

**Comment by nijikon** [comment]
@mikemcquaid any idea what might be happening? Can we get any log why it got stuck?

**Comment by mikemcquaid** [comment]
No idea I'm afraid :(

**Comment by nijikon** [comment]
Closed in favor of #43407

**Pull request closed without merging**
