### PR TITLE
JavaDependency: ignore trailing + in the version

### PR DESCRIPTION
**Pull request by bfontaine**
See @mikemcquaid’s [comment here](https://github.com/Homebrew/homebrew/pull/35595#issuecomment-72032115).

Roadmap from [my comment here](https://github.com/Homebrew/homebrew/pull/35595#issuecomment-72101042):

> 1. Allow formulae to add a trailing `+` but ignore it in the requirement (i.e. `"1.7+"` would be the same as `"1.7"`)
> 2. Wait a couple days (weeks?) for most taps to update their formulae to the new system (i.e. add a `+` where it’s relevant)
> 3. Stop ignoring the `+` in the requirement and switch to the new system

This PR is the first step. I included a few formulae updates, but not all, because (1) that would be too much overload on your bots and (2) some of the relevant formulae need to be upgraded (I’ll make separate PRs for them). See [this comment](https://github.com/Homebrew/homebrew/pull/35595#issuecomment-72034346) for a list of the formulae which need to be updated in the main repo.

Please comment if you have any suggestion / remark / think it’s a bad idea / etc.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Looks good here. Let's see if the build is green.

**Comment by bfontaine** [comment]
@mikemcquaid got `FATAL: Could not checkout null with start point d51eb40e…` :disappointed:

**Comment by bfontaine** [comment]
Green :smile:

**Comment by jacknagel** [comment]
lgtm

**Comment by mikemcquaid** [comment]
Thanks @bfontaine!

**Pull request closed without merging**
