### PR TITLE
Rebuild libgcrypt (1.6.3) bottle to use current libgpg-error (1.19) library.

### PR DESCRIPTION
**Pull request by tzudot**
update libgcrypt to use current libgpg-error library.

### CODE REVIEW

**Comment by tzudot** [comment]
Currently, the linked libgpg-error package is 1.18.
```sh
$ libgcrypt-config --libs                                                                                                                        
-L/usr/local/Cellar/libgcrypt/1.6.3/lib -lgcrypt -L/usr/local/Cellar/libgpg-error/1.18/lib -lgpg-error
```
This update is to revise this library to use libgpg-error 1.19.

**Comment by chdiza** [comment]
I don't understand.  `libgcrypt` already depends on `libgpg-error`.  If you think your `libgpg-error` is too old, then you just need to `brew update` and rebrew `libgpg-error`.

Is there some reason why you believe that  `libgcrypt` requires a particular version of `libgpg-error` here?

Even if there is such a need (and I doubt there is), the changes you made don't accomplish that.

**Comment by tzudot** [comment]
The current version of `libgpg-error => 1.19` in Homebrew. But the current bottled version of `libgcrypt => 1.6.3` is linked to `libgpg-error => 1.18` leading to failures in compilation of applications depending on `libgcrypt`.
How to fix this?

**Comment by chdiza** [comment]
Can you post a simple, reproducible example of a compilation failure, following the troubleshooting steps in the docs?  That shouldn't happen, given the small difference between 1.18 and 1.19.

**Comment by tzudot** [comment]
For instance, while building `wireshark`, the compiler fails to find the path for `libgpg-error => 1.18`, which is not installed anymore. Sorry, couldn't get `gist-logs`, there was a [buffer error](https://github.com/Homebrew/homebrew/issues/42100) while executing the command.

**Comment by DomT4** [comment]
Wireshark is actually pulling the flags from `libgcrypt-config`, aye:

``` -I/usr/local/Cellar/libgpg-error/1.18/include -L/usr/local/Cellar/libgpg-error/1.18/lib -lgpg-error ```

Wasn't what killed my build though.

**Comment by DomT4** [comment]
Actually going to merge here. The bottle is `cellar :any` so it doesn't suck for anyone unless they actually *choose* a from source build. The incorrect flag is clearly trickling down to other formulae that use that config executable to grab paths, and may well cause build issues in certain situations. We can review this again should it happen in future.

Thank you for the contribution @tzudot, We appreciate it! :smiley_cat:

**Comment by chdiza** [comment]
What's the plan going forward?  Are we going to bump `libgcrypt`'s revision every time `libgpg-error` gets a version bump?  It smells to me like something should be done once and for all to `libgcrypt-config`.  (I wonder if it can be made to look in the /opt dir for example.)

**Comment by DomT4** [comment]
The problem is that we do set `#{Formula["libgpg-error"].opt_prefix}"` as the path here but apparently during compile `libgcrypt` resolves that symlink and instead stores the versioned path in the `libgcrypt-config` executable:

```
# File: src/libgcrypt-config.  Generated from libgcrypt-config.in by configure.

# General.
prefix="/usr/local/Cellar/libgcrypt/1.6.3_1"
exec_prefix="${prefix}"
version="1.6.3"
includedir="${prefix}/include"
libdir="${exec_prefix}/lib"
gpg_error_libs="-L/usr/local/Cellar/libgpg-error/1.19/lib -lgpg-error"
gpg_error_cflags="-I/usr/local/Cellar/libgpg-error/1.19/include"
```

A dirty hack would be to inreplace that afterwards, or to try and tweak `libgcrypt`'s make process to stop it hunting down the true location of the symlink in `opt`.

**Comment by chdiza** [comment]
Experiment reveals that `libgcrypt-config` is created simply by running the `./configure` script.  I'll see if I can figure out how to force the latter to use the `opt_prefix`.

**Comment by chdiza** [comment]
Turns out the "problem" is actually in `gpg-error-config` (part of `libgpg-error`).  `libgcrypt-config` simply queries it and receives the offending path.  And the reason `gpg-error-config` returns the realpath rather than `opt_prefix` is (AFAICT) because of `libgpg-error`'s configure script.  (As with `libgcrypt-config`, `gpg-error-config` is created merely by the `./configure` step of `libgpg-error`.)

I don't know enough about configure scripts, however, to determine how to tweak the configure script belonging to `libgpg-error`.

**Pull request closed without merging**
