### PR TITLE
add git_available? and ensure_git_installed!

### PR DESCRIPTION
**Pull request by xu-cheng**
This is mainly for users who don't install Xcode or CLT.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
:+1: but won't this fail due to the Git package needing relocation?

**Comment by mikemcquaid** [comment]
Or will it just install `cctools`?

**Comment by xu-cheng** [comment]
Looks like we need to do something to make `git`'s bottle `cellar :any`.

**Comment by mikemcquaid** [comment]
@xu-cheng It's embedded inside binaries so you might struggle :sob:

**Comment by mikemcquaid** [comment]
```
==> Detecting if git-2.3.0.yosemite.bottle.tar.gz is relocatable...
Warning: String '/usr/local/Cellar' still exists in these files:
/usr/local/Cellar/git/2.3.0/bin/git
 --> match '/usr/local/Cellar/git/2.3.0' at offset 0x148825
/usr/local/Cellar/git/2.3.0/bin/git-shell
 --> match '/usr/local/Cellar/git/2.3.0' at offset 0x95b6c
/usr/local/Cellar/git/2.3.0/bin/git-upload-pack
 --> match '/usr/local/Cellar/git/2.3.0' at offset 0x989ce
/usr/local/Cellar/git/2.3.0/libexec/git-core/git-credential-cache
 --> match '/usr/local/Cellar/git/2.3.0' at offset 0x95b05
/usr/local/Cellar/git/2.3.0/libexec/git-core/git-credential-cache--daemon
 --> match '/usr/local/Cellar/git/2.3.0' at offset 0x96909
/usr/local/Cellar/git/2.3.0/libexec/git-core/git-credential-store
 --> match '/usr/local/Cellar/git/2.3.0' at offset 0x969d2
/usr/local/Cellar/git/2.3.0/libexec/git-core/git-daemon
 --> match '/usr/local/Cellar/git/2.3.0' at offset 0x97828
/usr/local/Cellar/git/2.3.0/libexec/git-core/git-fast-import
 --> match '/usr/local/Cellar/git/2.3.0' at offset 0x9ed02
/usr/local/Cellar/git/2.3.0/libexec/git-core/git-http-backend
 --> match '/usr/local/Cellar/git/2.3.0' at offset 0x96ba3
/usr/local/Cellar/git/2.3.0/libexec/git-core/git-http-fetch
 --> match '/usr/local/Cellar/git/2.3.0' at offset 0x9c567
/usr/local/Cellar/git/2.3.0/libexec/git-core/git-http-push
 --> match '/usr/local/Cellar/git/2.3.0' at offset 0x9f625
/usr/local/Cellar/git/2.3.0/libexec/git-core/git-remote-ftp
 --> match '/usr/local/Cellar/git/2.3.0' at offset 0xa05a0
/usr/local/Cellar/git/2.3.0/libexec/git-core/git-remote-testsvn
 --> match '/usr/local/Cellar/git/2.3.0' at offset 0x98bff
/usr/local/Cellar/git/2.3.0/libexec/git-core/git-sh-i18n--envsubst
 --> match '/usr/local/Cellar/git/2.3.0' at offset 0x94c3b
/usr/local/Cellar/git/2.3.0/libexec/git-core/git-show-index
 --> match '/usr/local/Cellar/git/2.3.0' at offset 0x96d6b
```

**Comment by mikemcquaid** [comment]
Also, even if it's `cellar :any` it'll still need relocation. I'm less worried about supporting no Xcode installed and a non-`/usr/local` install.

**Pull request closed without merging**
