### PR TITLE
qbs 1.3.4

### PR DESCRIPTION
**Pull request by jakepetroules**
First time contributing to Homebrew, just a simple version update.

### CODE REVIEW

**Comment by asparagui** [comment]
@BrewTestBot test this please

**Comment by asparagui** [comment]
@mikemcquaid Could I also get "please test this" aliased the same as above so i don't have to remember what the right form is?

**Comment by mikemcquaid** [comment]
@asparagui We can't add an alias because of stupid Jenkins settings :(

**Comment by mikemcquaid** [comment]
Looks like `brew test qbs` is failing. Could you take a look? http://bot.brew.sh/job/Homebrew%20Pull%20Requests/24541/version=yosemite/testReport/junit/brew-test-bot/yosemite/test_qbs/

**Comment by jakepetroules** [comment]
Problem in your test environment? Run `qbs setup-toolchains --detect` and if clang is in your PATH it'll create a profile for it.

**Comment by mikemcquaid** [comment]
Could you try and add that to the `test do` block?

**Comment by jakepetroules** [comment]
Done.

**Comment by xu-cheng** [comment]
Thanks for the pull request! 🎉 Homebrew depends on contributions from community members like you and we're grateful for your support.

**Pull request closed without merging**
