### PR TITLE
FormulaInstaller: uncache Tab to keep it fresh

### LINKED ISSUE #48612: brew install gcc --without-multilib stucks during 'make bootstrap'
Hi guys,
I've tried everything. Unistalling gcc end instal it directly without multilib , or reinstalling it w/o multilib after installing it 'normally'. I've alsso reinstalled every dependencies from gcc
And i'm alwais getting the same problem, it stucks.

brew reinstall gcc --without-multilib
==> Reinstalling gcc with --without-multilib
==> Downloading http://ftpmirror.gnu.org/gcc/gcc-5.3.0/gcc-5.3.0.tar.bz2
Already downloaded: /Library/Caches/Homebrew/gcc-5.3.0.tar.bz2
==> Patching
patching file gcc/jit/Make-lang.in
patching file gcc/jit/jit-playback.c
Hunk #1 succeeded at 2470 with fuzz 2 (offset 54 lines).
==> ../configure --build=x86_64-apple-darwin15.2.0 --prefix=/usr/local/Cellar/gcc/5.3.0 --libdir=/usr/local/Ce
==> make bootstrap

And it stucks here for hours

Any idea of a solution?
Thank you

### LINKED ISSUE #48657: `brew reinstall` may display wrong build-option-dependent caveats
It looks like the way `Tab` is caching its input, a `brew reinstall` command with different build options than the original install may display the caveats that apply to the original installation's options, not the new one.

This will apply to formulae whose `caveats` include sections conditionalized on `build.with?`.

Caused #48612. Most of this issue is copied from the discussion there.

##   Cause   ##

Look [here in `caveats.rb`](https://github.com/Homebrew/homebrew/blob/03c925589896962938c2b1f6fec641895b0d737c/Library/Homebrew/caveats.rb#L8-L16).

```
  def caveats
    caveats = []
    begin
      build, f.build = f.build, Tab.for_formula(f)
      s = f.caveats.to_s
      caveats << s.chomp + "\n" if s.length > 0
    ensure
      f.build = build
    end
```

The formula's `build` options are swapped out for a "`Tab`" based on it before querying the formula for caveats.

And that [`Tab.for_formula(f)` initialization logic](https://github.com/Homebrew/homebrew/blob/03c925589896962938c2b1f6fec641895b0d737c/Library/Homebrew/tab.rb#L95-L129), if I'm reading it right, initializes its build options state from the receipt file in the installation, and not from the live `f` object it was passed. 

```
    paths << f.prefix
    path = paths.map { |pn| pn.join(FILENAME) }.find(&:file?)
    if path
      tab = from_file(path)
```

Then that [Tab.from_file()](https://github.com/Homebrew/homebrew/blob/03c925589896962938c2b1f6fec641895b0d737c/Library/Homebrew/tab.rb#L41) uses a cache for the build receipt file.

```
  def self.from_file(path)
    CACHE.fetch(path) { |p| CACHE[p] = from_file_content(File.read(p), p) }
  end
```

I think this means that, since a `Tab` was already built for the formula early in the `reinstall` process before the old installation was removed, the cached tab info will still have the old build options.

##   Reproducing   ##

[Here's](https://github.com/apjanke/homebrew/blob/caveats-conditionality-demo/Library/Formula/cowsay-caveats.rb) a quick way to reproduce. `cowsay-caveats` is a copy of `cowsay`, with an added `--without-foo` option, and caveats that depend on it.

```
class CowsayCaveats < Formula
...
  option "without-foo", "Build without Foo"
...
  def caveats
    if build.with?("foo")
      "Cowsay was built --with-foo."
    end
  end
...
```

Here's the results of doing `brew install -s cowsay-caveats` and two `brew reinstall cowsay-caveats --without-foo`. The first `brew reinstall cowsay-caveats --without-foo` still issues the `--with-foo` caveats. A `brew info` after the first reinstall correctly omits them.

```
[/usr/local/Library/Formula on ⇄ caveats-conditionality-demo]
$ brew install -s cowsay-caveats
==> Using the sandbox
==> Downloading http://ftp.acc.umu.se/mirror/cdimage/snapshot/Debian/pool/main/c/cowsay/
Already downloaded: /Library/Caches/Homebrew/cowsay-caveats-3.03.tar.gz
==> /bin/sh install.sh /usr/local/Cellar/cowsay-caveats/3.03
==> Caveats
Cowsay was built --with-foo.
==> Summary
🍺  /usr/local/Cellar/cowsay-caveats/3.03: 53 files, 32.6K, built in 0 seconds
[/usr/local/Library/Formula on ⇄ caveats-conditionality-demo]
$ brew reinstall -s cowsay-caveats --without-foo
==> Reinstalling cowsay-caveats with --without-foo
==> Using the sandbox
==> Downloading http://ftp.acc.umu.se/mirror/cdimage/snapshot/Debian/pool/main/c/cowsay/
Already downloaded: /Library/Caches/Homebrew/cowsay-caveats-3.03.tar.gz
==> /bin/sh install.sh /usr/local/Cellar/cowsay-caveats/3.03
==> Caveats
Cowsay was built --with-foo.
==> Summary
🍺  /usr/local/Cellar/cowsay-caveats/3.03: 53 files, 32.6K, built in 0 seconds
[/usr/local/Library/Formula on ⇄ caveats-conditionality-demo]
$ brew info cowsay-caveats
cowsay-caveats: stable 3.03 (bottled)
Configurable talking characters in ASCII art
https://web.archive.org/web/20120225123719/http://www.nog.net/~tony/warez/cowsay.shtml
Conflicts with: cowsay
/usr/local/Cellar/cowsay-caveats/3.03 (53 files, 32.6K) *
  Built from source with: --without-foo
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/cowsay-caveats.rb
==> Options
--without-foo
	Build without Foo
[/usr/local/Library/Formula on ⇄ caveats-conditionality-demo]
$ brew reinstall -s cowsay-caveats --without-foo
==> Reinstalling cowsay-caveats with --without-foo
==> Using the sandbox
==> Downloading http://ftp.acc.umu.se/mirror/cdimage/snapshot/Debian/pool/main/c/cowsay/
Already downloaded: /Library/Caches/Homebrew/cowsay-caveats-3.03.tar.gz
==> /bin/sh install.sh /usr/local/Cellar/cowsay-caveats/3.03
🍺  /usr/local/Cellar/cowsay-caveats/3.03: 53 files, 32.6K, built in 0 seconds
[/usr/local/Library/Formula on ⇄ caveats-conditionality-demo]
$
```

##  Fixes  ##

Maybe the CACHE should check the mtime of the files its caching to ensure it's using fresh data? Or as a workaround, doing an uninstall could forcibly invalidate that CACHE.

### PR DESCRIPTION
**Pull request by xu-cheng**
Fixes #48612.
Fixes #48657.

cc @apjanke

### CODE REVIEW

**Comment by mikemcquaid** [comment]
I think it'd be fine to just clear the cache, honestly but :+1:

**Comment by UniqMartin** [comment]
I also prefer to just clear the cache unless that comes with a significant performance hit. Otherwise: :+1:

**Comment by xu-cheng** [comment]
Updated

**Comment by UniqMartin** [comment]
:+1:

**Comment by apjanke** [comment]
Should we maybe do this in `FormulaInstaller`'s `prelude` or `install` instead? That seems to be where the action that makes the Tab cache stale happens, and it could take care of potential other code paths that would be affected by a stale Tab cache over the course of a `brew` invocation.

Otherwise looks good.

**Comment by apjanke** [comment]
Also if nobody cares about the "here vs `FormulaInstaller.install`" distinction, :+1: merge away! Rather fix user-facing bugs than fuss about design.

**Comment by xu-cheng** [comment]
Updated per @apjanke's advice.

**Pull request closed without merging**
