### PR TITLE
cURLpp 0.7.3

### PR DESCRIPTION
**Pull request by ProteusCortex**

### CODE REVIEW

**Comment by mistydemeo** [comment]
A few minor things noticed by `brew audit`:

```
== /usr/local/Library/Formula/curlpp.rb ==
C: 44: 47: Space found before comma.
C: 44: 48: Space missing after comma.

1 file inspected, 2 offenses detected
Error: 1 problems in 1 formulae

==> audit problems
curlpp:
 * Stable: version 0.7.3 is redundant with version scanned from URL
```

**Comment by DomT4** [comment]
This formula was removed in the past: #12757. Seems to be building okay in this PR though.

**Comment by ProteusCortex** [comment]
I tried to begin with on of the past PRs, but none of them had anything that wasn't generated automatically by `brew create`, so I thought it was easier to start with a clean fork.

**Comment by tdsmith** [comment]
Thanks for the pull request! 🎉 Homebrew depends on contributions from community members like you and we're grateful for your support.

**Comment by ProteusCortex** [comment]
Closing, because it was merged, but the PR was not closed.

**Comment by ProteusCortex** [comment]
@tdsmith, it is not marked as merged, even though it is. Maybe an owner should close this?

**Comment by DomT4** [comment]
It was merged in https://github.com/Homebrew/homebrew/commit/527ad8e4a62e593d6184a16205d6628571188989. Homebrew doesn't use the "merge" button in PRs because it creates an unnecessarily noisy commit history.

Usually the words ` Closes #39257 ` are automatically added to the commit message when pulled and this would have been closed that way. Didn't happen this time for whatever reason, but it's in, and "merged" in the Homebrew sense, so you're okay to close :).

**Comment by ProteusCortex** [comment]
Oh, OK then.

**Comment by tdsmith** [comment]
Yes, sorry, forgot to close from the commit message when I was squashing commits.

**Pull request closed without merging**
