### PR TITLE
cunit 2.1.3

### PR DESCRIPTION
**Pull request by bfontaine**

### CODE REVIEW

**Comment by bfontaine** [comment]
Works on my Mac, fails on the bot. I edited the `install` method, we’ll see if it works now.

**Comment by mikemcquaid** [comment]
Installation is failing: http://bot.brew.sh/job/Homebrew%20Pull%20Requests/20849/version=yosemite/testReport/junit/brew-test-bot/yosemite/install_cunit/

**Comment by bfontaine** [comment]
It now fails on ML only, with a far from helpful message:

```
==> ./bootstrap /usr/local/Cellar/cunit/2.1-3
Failed to execute: ./bootstrap
==> Configuration
(…)
```

**Comment by mikemcquaid** [comment]
Hmm, what's the `shebang` on the bootstrap script? Maybe that's the issue.

**Comment by bfontaine** [comment]
No shebang, I edited to run `sh bootstrap` :+1:

**Comment by bfontaine** [comment]
Doesn’t work, same message :disappointed: 

```
==> sh bootstrap /usr/local/Cellar/cunit/2.1-3
Failed to execute: sh bootstrap
```

**Pull request closed without merging**
