### PR TITLE
Portmidi: Include Cython

### PR DESCRIPTION
**Pull request by s172262**
### All Submissions:

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew/pulls) for the same update/change?

### CODE REVIEW

**Comment by ilovezfs** [comment]
@s172262 As for
`depends_on "Cython" => :python if build.with? "python"`

That just means it'll prompt you to install it with `pip`

**Comment by s172262** [comment]
Thank you for you advice.
But other Formula (reposurgeon, libplist, yasm and more) has included Cython install part.
And I wouldn't install pip.

**Comment by ilovezfs** [comment]
@s172262 I don't see anything wrong with vendoring in Cython if you'd like to reopen this. I was only pointing out that the comma thing was already fixed in master.

**Comment by s172262** [comment]
I'm making new pull-request  without commit for the comma thing .
Should I only reopen this ? or remake pull-request?

**Comment by ilovezfs** [comment]
That's up to you. Six of one, half-dozen of the other.

**Pull request closed without merging**
