### PR TITLE
bandit 2.0.0 (new formula)

### PR DESCRIPTION
**Pull request by MartinDelille**
Here is a PR for integrating this awesome C++ unit testing framework from @joakimkarlsson !

### CODE REVIEW

**Comment by MartinDelille** [comment]
Is there any objection about this formula?

**Comment by mikemcquaid** [comment]
@MartinDelille In the past we've considered whether header-only formulae are not better vendored in their relevant C++ projects.

**Comment by MartinDelille** [comment]
And in the present? Is there any discussion/argument about this? I'll be happy to learn why!

**Comment by DomT4** [comment]
I don't have a strong objection here, beside agreeing with the gut instinct that installing _just_ headers feels a bit odd.

**Comment by mikemcquaid** [comment]
Passing on this as @DomT4 agrees. Historically we've felt header-only things should be vendoring in your project rather than Homebrew.

**Pull request closed without merging**
