### PR TITLE
gnutls 3.3.13

### PR DESCRIPTION
**Pull request by DomT4**
Simple version bump. Just a bug fix release, no API/ABI changes.

### CODE REVIEW

**Comment by DomT4** [comment]
This seems to have fallen off the bot's build queue. I'll ask it to look again. Not sure if it'll ignore me here, since I don't have push rights to Homebrew/Homebrew, but guess there's only one way to find out :smile_cat:

**Comment by DomT4** [comment]
@BrewTestBot test this please

**Comment by tdsmith** [comment]
:+1:

**Comment by DomT4** [comment]
Thanks Tim! Appreciate the merge here.

**Pull request closed without merging**
