### PR TITLE
swiftlint 0.5.6

### PR DESCRIPTION
**Pull request by jpsim**
Thanks!

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Install is failing on 10.10/10.11: http://bot.brew.sh/job/Homebrew%20Pull%20Requests/39456/version=el_capitan/testReport/junit/brew-test-bot/el_capitan/install_swiftlint/

**Comment by jpsim** [comment]
Ah, interesting. Sorry about that. I'll need a bit of time to look into this, it seems a dependency I'm using has changed its build settings in a way I'm not handling properly.

**Comment by DomT4** [comment]
No worries! Give us a poke when you've pushed an update here, Cheers :)

**Comment by jpsim** [comment]
I believe the issues with 0.5.5 have been addressed in 0.5.6. Could homebrew reviewers please take another look?

Thanks!

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/0d04876452baee7f4c00aea2174918e81a777b22. Thank you for another contribution to Homebrew @jpsim! :smiley_cat:

**Comment by jpsim** [comment]
Thanks!

**Pull request closed without merging**
