### PR TITLE
uudeview: Installing provided headers and generated library

### PR DESCRIPTION
**Pull request by artlogic**
Other programs (slrn for instance) can use uudeview as a library. This change installs the headers and library by default so they are available to build against.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Are these public? It makes me wonder why they aren't installed by `make install`?

**Comment by artlogic** [comment]
For some reason the package author doesn't provide the option. However, it's common to see the headers and library pulled out and packaged as libuu. Would it be more appropriate to provide these as a libuu formula?

**Comment by mikemcquaid** [comment]
@artlogic If the package author doesn't provide it I'm a bit uneasy about doing so. Could you ask them about it on e.g. a bugtracker or mailing list?

**Comment by artlogic** [comment]
@mikemcquaid I'm not hopeful the author is going to change his package, especially with so many large distributions working around his lack of an install. Take a look at how MacPorts, Arch, and Debian package uudeview and it's libraries:

MacPorts

https://trac.macports.org/browser/trunk/dports/mail/uudeview/Portfile - MacPorts is a bit more conservative, only installing the single header. **I'd be willing to make this change, as all I really am looking for is libuu.a and uudeview.h.**

Arch

https://www.archlinux.org/packages/community/x86_64/uudeview/ - Arch installs pretty much everything as you can see from the file list. Their PKGBUILD script (https://projects.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/uudeview) copies files over after the make.

Debian
* https://packages.debian.org/source/wheezy/uudeview - the main source package for uudeview - notice that uudeview, along with both libuu0 and libuu0-dev are built from the single source package
* https://packages.debian.org/wheezy/uudeview - the binary package that includes uudeview and uuenview
* https://packages.debian.org/wheezy/libuu0 - the library package that includes libuu
* https://packages.debian.org/wheezy/libuu-dev - the header files

If you look over the changes that the Debian maintainer has made, you'll see they had to write additional scripts to install the library files.

**Comment by artlogic** [comment]
@mikemcquaid I've reduced the headers to only uudeview.h. Given my research, I think this is a reasonable request, but I am willing to package this as a new libuu formula if that's more appropriate. Let me know.

**Comment by mikemcquaid** [comment]
@artlogic Can you find anywhere upstream where the author says if this library/header are private or public? It's maybe not 100% required for me to merge it but I'm just wondering what's going on here.

**Comment by artlogic** [comment]
@mikemcquaid I'm not sure if this covers it, but here are a few links from the project's home page:

http://www.fpx.de/fp/Software/UUDeview/ - specifically the section titled "The UUDeview Library"
http://www.fpx.de/fp/Software/UUDeview/download/library.pdf - More in depth documentation

The author clearly intends others to use it. I can only assume the age of this package is why there's no library install.

I've also checked out a few more distributions (including the FreeBSD port) and I have yet to find one that's not packaging at least these file along side with uudeview or in it's own package, libuu/uulib.

I remain hesitant to email the author as he makes it pretty clear he wants to be let alone: "Support for UUDeview is not available unless you give me a really good reason for it. " However, if you're still feeling uneasy about this let me know and I'll attempt to contact him.

**Comment by mikemcquaid** [comment]
Yeh, with that explanation I'm happy to include this as-is. It'd be great if you could send him a patch to install these things and summarise that other people are doing the same.

**Comment by mikemcquaid** [comment]
Actually, sorry, last thing: when you contact him can you add a comment saying that you have, when you did and a brief summary (like a sentence or two) of our discussion here? Just makes it easier for people to understand why in future. Thanks!

**Comment by artlogic** [comment]
I've just sent Frank Pilhofer an email asking if he'd be willing to accept a patch to change his Makefile to standard the install of uulib. I will reply here if he responds to me.

To summarize the situation: uudeview provides a library meant for public consumption, but without a standard way to install it. Most distributions provide the library, but methodologies vary. I've modified the formula to manually install libuu.a and uudeview.h for the moment. I'm waiting to see if upstream changes are possible.

**Comment by mikemcquaid** [comment]
Sorry, I meant put the summary in the formula file itself as a Ruby comment. Thanks!

**Comment by DomT4** [comment]
What's the status here? Are we just waiting on a comment in the formula linking to an upstream bug report?

**Comment by artlogic** [comment]
I'm sorry for letting this go for so long. There is no upstream bug tracker. The project is basically unsupported. I spoke with Frank, and he asked me if I was willing to become the new maintainer - I am not. I'd be happy to put a comment to this effect in the source if it will move this along.

**Comment by DomT4** [comment]
Maybe add a comment along the lines of project is unsupported but this behaviour mimics Debian et al.? Thoughts @mikemcquaid?

**Comment by mikemcquaid** [comment]
I think we should probably pass on this for now, probably.

**Comment by artlogic** [comment]
@mikemcquaid - the goal here was to make the libraries available for slrn and patch the formula so it could be compiled with decoding support. If this patch is dead, how would you suggest I move forward with modifying the slrn formula?

**Comment by DomT4** [comment]
I don't have a particularly huge objection to this, even if upstream aren't supporting the project any more. The burden on us to fix issues across updates *should* be low with a simple installation of existing lib/header.

**Comment by mikemcquaid** [comment]
@artlogic Fair enough, will include this as-is.

**Comment by mikemcquaid** [comment]
@artlogic can you add a `revision 1` below `sha1`? Thanks!

**Comment by artlogic** [comment]
@mikemcquaid - will do. I'd still be happy to put a note in explaining why those two lines are included if you think it's appropriate. Let me know.

**Comment by artlogic** [comment]
@mikemcquaid and @DomT4 - I've added the revision and a brief (I hope) explanation. Please let me know if there's anything else needed. Thanks for your help with this!

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

For future reference the preferred commit message format is `uudeview: install headers and library.`.

**Pull request closed without merging**
