### PR TITLE
emscripten 1.29.2

### PR DESCRIPTION
**Pull request by mjbshaw**

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Failed to build on 10.8, will need a tweak: http://bot.brew.sh/job/Homebrew%20Pull%20Requests/19970/version=mountain_lion/testReport/junit/brew-test-bot/mountain_lion/install_emscripten/

**Comment by mjbshaw** [comment]
Is there a way to view the `config.log` file? It seems to be failing to build the file:

    #include <atomic>
    std::atomic<float> x(0.0f);
    int main() { return (float)x; }

with `clang++ -o conftest  -std=c++0x   conftest.cpp`. I need to understand better why that machine is failing on this specific test in order to know what to adjust with this commit, but I can't see where the access the test's `config.log` file.

**Comment by mikemcquaid** [comment]
There's not beyond the logs you already see. Someone may be able to test on a 10.8 machine for you. If this needs CXX11 perhaps it should have a `needs :cxx11` (and, if that doesn't work, possibly `ENV.cxx11 ` too).

**Comment by mjbshaw** [comment]
Closing in favor of #36169.

**Pull request closed without merging**
