### PR TITLE
sourcekitten 0.11.0

### PR DESCRIPTION
**Pull request by jpsim**
### New Formulae Submissions:

- [x] Does your submission pass
`brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Have you built your formula locally prior to submission with `brew install <formula>`?

---

Thanks!

### CODE REVIEW

**Comment by DomT4** [comment]
Test is failing for some reason:
```
==> /usr/local/Cellar/sourcekitten/0.11.0/bin/sourcekitten syntax --text import Foundation // Hello World
Error: sourcekitten: failed
Failed executing: /usr/local/Cellar/sourcekitten/0.11.0/bin/sourcekitten syntax --text import\ Foundation\ //\ Hello\ World
```

**Comment by jpsim** [comment]
This version of SourceKitten dynamically links its library dependencies (`libclang.dylib` & `sourcekitd.framework`) at runtime (jpsim/SourceKitten#178), so this job failure may be due to the way Xcode is configured on the CI worker. Would it be possible for you to share the following information about the CI workers on which this job failed?

1. Which versions of Xcode are installed? `e.g. 7.2.1`
2. Where are these versions of Xcode installed on the file system? `e.g. /Applications/Xcode.app`
3. What's the output of `xcode-select -p`? `e.g. /Applications/Xcode.app/Contents/Developer`
4. Are the "Command Line Tools OS X for Xcode" installed?

Thanks for helping me troubleshoot this failure! The Homebrew team is amazing :tada:

On an unrelated note, I don't know what changes were made to the Jenkins CI infrastructure recently, but  that job ran so quickly! In the last few months, there's been a consistent ~4-6 hour backlog, and this one ran within a few minutes!!

**Comment by DomT4** [comment]
> Which versions of Xcode are installed? e.g. 7.2.1

Yup.

> Where are these versions of Xcode installed on the file system? e.g. /Applications/Xcode.app

Yup!

> What's the output of xcode-select -p? e.g. /Applications/Xcode.app/Contents/Developer

The `e.g.` is correct :wink:.

> Are the "Command Line Tools OS X for Xcode" installed?

Yup!

**Comment by jpsim** [comment]
Hmm, that all looks fine then... Is there anywhere I can see the stdout/stderr output for the test command? It doesn't seem to have been included in the console output:

```
==> FAILED
Testing sourcekitten
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20160317-15090-1oo4sjm.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Library/Homebrew -- /usr/local/Library/Homebrew/test.rb /usr/local/Library/Formula/sourcekitten.rb --verbose
==> /usr/local/Cellar/sourcekitten/0.11.0/bin/sourcekitten syntax --text import Foundation // Hello World
Error: sourcekitten: failed
Failed executing: /usr/local/Cellar/sourcekitten/0.11.0/bin/sourcekitten syntax --text import\ Foundation\ //\ Hello\ World
/usr/local/Library/Homebrew/formula.rb:1481:in `block in system'
/usr/local/Library/Homebrew/formula.rb:1418:in `open'
/usr/local/Library/Homebrew/formula.rb:1418:in `system'
/usr/local/Library/Formula/sourcekitten.rb:19:in `block in <class:Sourcekitten>'
/usr/local/Library/Homebrew/formula.rb:1327:in `block in run_test'
/usr/local/Library/Homebrew/extend/fileutils.rb:37:in `mktemp'
/usr/local/Library/Homebrew/formula.rb:1323:in `run_test'
/usr/local/Library/Homebrew/test.rb:28:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/usr/local/Library/Homebrew/test.rb:27:in `<main>'
```

**Comment by jpsim** [comment]
@norio-nomura any ideas what might be causing this to fail?

**Comment by norio-nomura** [comment]
Now, I have reproduced the fail on local VM.
I'll investigate.

**Comment by DomT4** [comment]
@jpsim Apologies, I had some stuff to do this evening so abruptly vanished earlier.

> stdout/stderr output for the test command?

I'm afraid not. I see it was reproduced above so hopefully we'll have some luck there.

**Comment by norio-nomura** [comment]
On my testing:
No output is produced to both of stdout and stderr.
Loading sourcekitd succeed, but it seems sourcekitd returns unexpected result…

**Comment by jpsim** [comment]
@norio-nomura could you tell me how you've reproduced this? I'd love to investigate too.

**Comment by norio-nomura** [comment]
@jpsim run same `brew` commands on the log http://bot.brew.sh/job/Homebrew%20Pull%20Requests/43411/version=el_capitan/consoleText
```sh
==> brew pull --clean https://github.com/Homebrew/homebrew/pull/50211
==> brew doctor
==> brew --env
==> brew config
==> brew tests
==> brew tests --no-compat
==> brew readall --aliases --syntax
==> brew update-test
==> brew uses --recursive sourcekitten
==> brew fetch --retry git
==> brew fetch --retry sourcekitten --build-bottle --force
==> brew install --only-dependencies --verbose --build-bottle sourcekitten
==> brew install --verbose --build-bottle sourcekitten
==> brew audit sourcekitten
==> brew bottle --verbose --rb sourcekitten
==> brew bottle --merge --write --no-commit ./sourcekitten-0.11.0.el_capitan.bottle.rb
==> brew uninstall --force sourcekitten
==> brew uninstall --force git
==> brew install ./sourcekitten-0.11.0.el_capitan.bottle.tar.gz
==> brew test --verbose sourcekitten
```

**Comment by norio-nomura** [comment]
@jpsim we can omit most of commands:
1. download http://bot.brew.sh/job/Homebrew%20Pull%20Requests/43411/version=el_capitan/artifact/sourcekitten-0.11.0.el_capitan.bottle.tar.gz
2. run following
```sh
brew uninstall sourcekitten
brew install ~/Downloads/sourcekitten-0.11.0.el_capitan.bottle.tar.gz
brew test --verbose sourcekitten
```

**Comment by norio-nomura** [comment]
It seems `brew test --verbose sourcekitten` runs `sourcekitten` in sandbox and that affect result of sourcekitd.

**Comment by norio-nomura** [comment]
@jpsim I got reproduced error on Xcode with sandboxed sourcekitten.app.
screenshot 2016-03-18 11 42 47

**Comment by norio-nomura** [comment]
We are failing to launch `SourceKitService.xpc`.
> 2016/03/18 11:54:20.019 com.apple.xpc.launchd[1]: (com.apple.xpc.launchd.domain.pid.sourcekitten.2815) Path not allowed in target domain: type = pid, path = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/sourcekitd.framework/Versions/A/XPCServices/SourceKitService.xpc error = 147: The specified service did not ship in the requestor's bundle, origin = /Users/norio/Library/Developer/Xcode/DerivedData/SwiftLint-eangswdzvhtbxpebxskdhgwvjger/Build/Products/Debug/sourcekitten.app

**Comment by jpsim** [comment]
@DomT4 it appears this is failing because SourceKitten is creating an XPC connection with a service at a path that the sandbox doesn't think we should have access to. Is there a way to opt out of the sandbox for this formula? Or is there a better way to address this?

I don't think enabling OS X App Sandbox is the right thing to do here because that will limit where our users libraries could be installed and cause usability issues otherwise.

**Comment by DomT4** [comment]
> Is there a way to opt out of the sandbox for this formula?

For obvious enough reasons, we don't supply an opt-out to the sandbox or permit formulae to modify the sandboxed elements/permissions/entitlements on-the-fly.

It's worthwhile noting however, particularly to your latter concerns, that our sandbox applies _only_ during the installation and `test do` process. Outside of Homebrew internal usage, we don't intentionally limit the behaviour of any formula. Consequently, this isn't a problem for end-users, just us.

Is this new functionality? We've not run into this with any previous version of this formulae to my recollection.

**Comment by jpsim** [comment]
> Is this new functionality?

Yes, it's new functionality that allows SourceKitten to dynamically link the SourceKit and Clang libraries at runtime based on user preference.

> our sandbox applies only during the installation and test do process

When you say "sandbox" do you mean [OS X's App Sandbox](https://developer.apple.com/library/mac/documentation/Miscellaneous/Reference/EntitlementKeyReference/Chapters/EnablingAppSandbox.html) or something else? Is this a Homebrew-specific sandbox? If so, is this documented anywhere?

If this is a Homebrew sandbox, I think adding `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/sourcekitd.framework/Versions/A/XPCServices/SourceKitService.xpc` to the list of sandbox paths should be sufficient to getting this to work on CI.

**Comment by norio-nomura** [comment]
> I think adding `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/sourcekitd.framework/Versions/A/XPCServices/SourceKitService.xpc` to the list of sandbox paths should be sufficient to getting this to work on CI.

I tested that as https://github.com/jpsim/SourceKitten/issues/189#issuecomment-198586969 and did not resolve the issue.
I think we need another approach.

**Comment by DomT4** [comment]
>  If so, is this documented anywhere?

The mechanism is documented in the [sandbox.rb](https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/sandbox.rb) core file. It's also more fine-grained per command, such as in [test](https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/cmd/test.rb#L51-L62) here. 

@xu-cheng may be interested in this issue/have thoughts on a reasonable resolution without degrading the strength of the existing test.

**Comment by jpsim** [comment]
> The mechanism is documented in the sandbox.rb core file. It's also more fine-grained per command, such as in test here.

Thanks for clarifying!

> @xu-cheng may be interested in this issue/have thoughts on a reasonable resolution without degrading the strength of the existing test.

If there was a way to specify additional sandbox write paths in the formula DSL, we could add `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/sourcekitd.framework/Versions/A/XPCServices/SourceKitService.xpc` explicitly.

**Comment by xu-cheng** [comment]
Sorry, I'm not sure what happens that violates the sandbox access policy. Because I cannot build this formula locally. https://gist.github.com/a7d37901df53afa31370

 > If there was a way to specify additional sandbox write paths in the formula DSL, we could add /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/sourcekitd.framework/Versions/A/XPCServices/SourceKitService.xpc explicitly.

* We definitely won't allow formula to custom specify sandbox rule because security reason.
* I'm not convinced  that adding this path will fix it. Because we only enforce write only rules beside the default build-in rules for sandbox.

**Comment by norio-nomura** [comment]
@xu-cheng we can test using binary that builded by bot.brew.sh: http://bot.brew.sh/job/Homebrew%20Pull%20Requests/43411/version=el_capitan/artifact/sourcekitten-0.11.0.el_capitan.bottle.tar.gz
```sh
% brew pull --clean https://github.com/Homebrew/homebrew/pull/50211
% brew uninstall sourcekitten
% brew install ~/Downloads/sourcekitten-0.11.0.el_capitan.bottle.tar.gz
% brew test --verbose sourcekitten
```

I also did test specifying additional sandbox write paths (https://github.com/jpsim/SourceKitten/issues/189#issuecomment-198586969).
I think adding writable path does not resolve this issue.

-- quote from https://github.com/jpsim/SourceKitten/issues/189#issuecomment-198586969 --
With sandbox profile inserting line 3 into that used on `brew test --verbose sourcekitten`:
```
(version 1)
(debug deny) ; log all denied operations to /var/log/system.log
(allow file-write* (subpath "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/sourcekitd.framework"))
(allow file-write* (subpath "/private/tmp"))
(allow file-write* (subpath "/private/var/tmp"))
(allow file-write* (regex #"^/private/var/folders/[^/]+/[^/]+/[C,T]/"))
(allow file-write* (subpath "/private/tmp"))
(allow file-write* (subpath "/Library/Caches/Homebrew"))
(allow file-write* (subpath "/Users/norio/Library/Logs/Homebrew/sourcekitten"))
(allow file-write* (subpath "/Users/norio/Library/Developer/Xcode/DerivedData"))
(allow file-write* (subpath "/usr/local/var/cache"))
(allow file-write* (subpath "/usr/local/var/log"))
(allow file-write* (subpath "/usr/local/var/run"))
(allow file-write*
    (literal "/dev/ptmx")
    (literal "/dev/dtracehelper")
    (literal "/dev/null")
    (literal "/dev/zero")
    (regex #"^/dev/fd/[0-9]+$")
    (regex #"^/dev/ttys?[0-9]*$")
    )
(deny file-write*) ; deny non-whitelist file write operations
(allow process-exec
    (literal "/bin/ps")
    (with no-sandbox)
    ) ; allow certain processes running without sandbox
(allow default) ; allow everything else
```
and got following:
```sh
% /usr/bin/sandbox-exec -f ./homebrew20160319-22633-1j6kaem.sb /usr/local/Cellar/sourcekitten/0.11.0/bin/sourcekitten syntax --text import\ Foundation\ //\ Hello\ World
[1]    22829 illegal hardware instruction  /usr/bin/sandbox-exec -f ./homebrew20160319-22633-1j6kaem.sb  syntax --text
```

**Comment by jpsim** [comment]
Would it be acceptable to change the test command to something that doesn't create an XPC connection in SourceKitten? Like `sourcekitten version`? I know such minimal tests are typically discouraged but in this case, it may be sufficient until the sandbox can be adapted to support this scenario in a more comprehensive way?

**Comment by DomT4** [comment]
Feel free to go down that route until we can look into this further between our two teams. If you could add a link above the newer, minimal test to this PR so we can track it that'd be great as well.

**Comment by jpsim** [comment]
Should I open a GH issue to track the sandbox enhancements?

**Comment by DomT4** [comment]
Yeah, feel free. Would be good to try and work out what about the sandbox blocks that and whether it's actionable on our side, your's or both.

**Comment by jpsim** [comment]
Done. Thanks again for your help and patience.

**Comment by apjanke** [comment]
Can you be more specific with what SourceKitten is doing that causes the XPC activity to happen? I don't know Objective C well enough to really read the source. Is it creating an XPC connection to something in Xcode? Or is it just launching an external Xcode process that is using XPC internally? Or something else?

**Comment by jpsim** [comment]
Right, so SourceKitten dynamically links (using `dlopen`) the `sourcekitd.framework` framework that ships with Xcode. We do this at runtime with `dlopen` to have flexibility in where our users have Xcode installed on their machine. Previously, we used `rpath`s to find the frameworks and let the system do the dynamic linking for us, but this was too limiting. See jpsim/SourceKitten#178 for more details on that.

So SourceKitten `dlopen`s `sourcekitd.framework` which is located in `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/sourcekitd.framework`, then the `sourcekitd` framework establishes an XPC connection with `sourcekitd.framework/XPCServices/SourceKitService.xpc` (because that's the only interface to SourceKit that ships with Xcode).

To be clear, SourceKitten (and SwiftLint for that matter) have always used this XPC interface on Homebrew without issue, but the sandbox issues started happening when we started using `dlopen`.

**Comment by apjanke** [comment]
I suspect that usage is not supported. The fact that `sourcekitd.framework` is installed under `Xcode.app` instead of in `/System/Library/Frameworks` or `/Library/Frameworks` means it's a [private framework](https://developer.apple.com/library/mac/documentation/MacOSX/Conceptual/BPFrameworks/Tasks/InstallingFrameworks.html#//apple_ref/doc/uid/20002261-97286-BBCIHFEF), and I think specifically an ["embedded framework"](https://developer.apple.com/library/mac/documentation/MacOSX/Conceptual/BPFrameworks/Tasks/CreatingFrameworks.html#//apple_ref/doc/uid/20002258-106880). Those documents indicate that private/embedded frameworks can't be shared between applications.

> Embedding the framework also makes it clear to other developers that they should not ever link to that framework.

I think this means that the sandbox is behaving correctly by denying this behavior, and that SourceKitten can't run under the sandbox as it currently is.

Simply recognizing that and sticking with a trivial test that doesn't run against sandbox boundaries like we're doing here seems fine. This isn't the Mac App Store; we don't require applications to be sandboxed. We just use the sandbox to get a degree of safety during the build and test steps.

(If you did want to make SourceKitten sandbox-friendly, maybe the thing to do would be to copy the `sourcekitd.framework` into the `sourcekitten` package as a private embedded framework. But I don't know if that would violate Apple's license and redistribution terms for Xcode.)

This also looks like it means `sourcekitten`'s Xcode dependency is a full-time dependency, not just a build dependency, so the `:build` tag should be removed.

**Comment by apjanke** [comment]
> But I don't know if that would violate Apple's license and redistribution terms for Xcode.

Come to think of it, SourceKit is now part of Swift, not Xcode's proprietary parts, right? Which means SourceKit is Apache licensed, and you would be fine doing this. And for sure if you grabbed it from the Swift source tree instead of from Xcode.app.

**Comment by jpsim** [comment]
> Come to think of it, SourceKit is now part of Swift, not Xcode's proprietary parts, right? Which means SourceKit is Apache licensed, and you would be fine doing this. And for sure if you grabbed it from the Swift source tree instead of from Xcode.app.

Yes, but this is problematic on a few fronts:

1. Swift is rapidly changing, so it's nice to just link the same version a user is using at that point in time, hence `dlopen` from what `xcode-select` returns.
2. `sourcekitd.framework` is a large dependency, whether built from source or as a binary, so I'd rather avoid pulling that in.

**Comment by jpsim** [comment]
> Simply recognizing that and sticking with a trivial test that doesn't run against sandbox boundaries like we're doing here seems fine.

👍 understood, I just wasn't sure if such a trivial test was permitted long-term. At some point, when the Swift Package Manager is widely distributed, we'll probably deprecate the Homebrew distribution channel anyway and let people build from source themselves...

> This also looks like it means `sourcekitten`'s Xcode dependency is a full-time dependency, not just a build dependency, so the `:build` tag should be removed.

Thanks for the tip, I wasn't aware of this. I just filed Homebrew/homebrew-core#866 to do this.

**Pull request closed without merging**
