### PR TITLE
percona-server 5.7.10-3

### PR DESCRIPTION
**Pull request by nijikon**

### CODE REVIEW

**Comment by nijikon** [comment]
Question here is do we want to change current stable to this version or leave 5.6 as stable at least until next iteration?

**Comment by DomT4** [comment]
Is this version considered the stable release by upstream?

**Comment by nijikon** [comment]
https://www.percona.com/blog/2016/02/23/percona-server-5-7-10-3-ga-is-now-available/

**Comment by nijikon** [comment]
It's a GA

**Comment by DomT4** [comment]
That seems stable? It's the release the main website is linking to now, at least, and GA tends to mean stable.

**Comment by nijikon** [comment]
Yup.

**Comment by DomT4** [comment]
You can remove the lines impacted by this now:
```
Error: No such file or directory - (/usr/local/Cellar/percona-server/5.7.10-3/bin/mysqlaccess, /usr/local/Cellar/percona-server/5.7.10-3/libexec/mysqlaccess)
```
MySQL killed those executables off.

**Comment by nijikon** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
