### PR TITLE
arangodb 2.8.1

### PR DESCRIPTION
**Pull request by fceller**
Updated to ArangoDB 2.8.1

### CODE REVIEW

**Comment by apjanke** [comment]
The CI failures are timeouts, no apparent errors. Though it's weird that one (10.9) timed out during a fetch.

Jenkins succeeded, though, and only took 15 minutes. Something wrong with the CI machines today?

Merging since Jenkins succeeded. Thank you for your contribution to Homebrew!

**Comment by apjanke** [comment]
That www.arangodb.com download link seems super slow. I'm getting about 100 KB/s from it, and that one CI box timed out after 10 minutes and the download hadn't finished.

They're [tagging releases on GitHub](https://github.com/arangodb/arangodb/releases), including tarballs. Maybe we should put https://github.com/arangodb/arangodb/archive/v2.8.1.tar.gz as the main download `url` and make the current `www.arangodb.com` one just a `mirror`. The GitHub download for me was about 100x faster (10 MB/s) and finished in 20 s. Even if most users are just installing from a bottle, would make things easier on our build machines and the few users who do build from source (including whoever's updating the formula).

**Comment by fceller** [comment]
Thanks. www.arangodb.com is hosted on Azure. Currently is fast again. I will keep an eye on it.

**Comment by fceller** [comment]
@apjanke I was asked, if I can provide the release 2.7.6 (which is a bugfix release for the 2.7 version) as well. Shall I create a pull request for https://github.com/Homebrew/homebrew-versions or does that not make any sense? Thanks Frank

**Comment by apjanke** [comment]
We try to keep the amount of stuff in `homebrew-versions` to a minimum. I'm assuming the 2.8 release would have picked up the same bug fix? Unless there are hard back-compatibility problems with 2.8, let's stick with just the one current release.

**Comment by fceller** [comment]
@apjanke yes, 2.8 contains the same bug. So I assume it should be OK to only deliver 2.8.1 and not 2.7.6

**Comment by apjanke** [comment]
Yeah, that sounds fine.

**Pull request closed without merging**
