### PR TITLE
net6 and kbtin: boneyard

### PR DESCRIPTION
**Pull request by rakkesh**
https://github.com/Homebrew/homebrew-boneyard/pull/81

https://github.com/Homebrew/homebrew/issues/46562#issuecomment-162267420

### CODE REVIEW

**Comment by DomT4** [comment]
I'm fine with this but I'll leave it open another day or so so other maintainers can comment as desired.

**Comment by mikemcquaid** [comment]
:+1:

**Comment by DomT4** [comment]
If nobody files an objection I'll merge this sometime overnight.

**Comment by dunn** [comment]
Feel free to add "Closes #39167" when you do.

**Comment by bfontaine** [comment]
:+1:

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/eeb73687a14d96277f2158cb97d7fa42fbc0403d & https://github.com/Homebrew/homebrew/commit/676972bff908b4ddd9e020a0b1560bf326c467ae.

Thank you for another contribution to Homebrew @rakkesh, and to Baptiste, Alex and Mike for the :skull: feedback!

**Pull request closed without merging**
