### PR TITLE
Migrate mandatory-FUSE to Homebrew/Fuse

### PR DESCRIPTION
**Pull request by DomT4**

### CODE REVIEW

**Comment by DomT4** [comment]
CC @Homebrew/owners @bfontaine

It's likely I'll need to break it into smaller PRs to make Travis happy and to keep the commit log clean/clear, but everything has been fixed up to `brew audit --strict` (Excluding tests for a few formulae): https://github.com/Homebrew/homebrew-fuse/pull/1

**Comment by DomT4** [comment]
This would also finish up and close #38819.

**Comment by mikemcquaid** [comment]
Makes sense to me :+1:

**Comment by DomT4** [comment]
Split the one big PR into 4 in Fuse and committed each formulae individually with version numbers, migration tag, etc. Not everything will pass, mostly the `fuse4x` related stuff, but everything will pass bar the few `test do` failures.

**Comment by mikemcquaid** [comment]
@DomT4 :+1: Merge these all when ready.

**Comment by DomT4** [comment]
Has :ship:'d. Set the bot on the two PRs that were conditional on this being merged, so they should be done soon as well.

**Comment by TeresaP** [comment]
Is this change the reason why "brew install ifuse" results in the error, "No available formula for ifuse"?

**Comment by DomT4** [comment]
Yes. You want `brew install homebrew/fuse/ifuse` - That should tap the tap for you, after which you can just refer to `homebrew/fuse/ifuse` as `ifuse`.

**Comment by TeresaP** [comment]
Perfect. Thanks @DomT4

**Pull request closed without merging**
