### PR TITLE
evince: update-mime-database added to post_install

### LINKED ISSUE #45168: Evince won't open any file
After I installed evince and djvulibre, I opened evince and navigate to my pdfs. However, none of them is shown by evince with options "all documents". If I choose "All files" and click on one of the pdfs, evince won't open it. The error message was application/octet-stream type is not supported. Did I miss something?

### PR DESCRIPTION
**Pull request by tschoonj**
Closes #45168

### CODE REVIEW

**Comment by bfontaine** [comment]
Is this worth a formula revision?

**Comment by tschoonj** [comment]
Thanks, forgot about that

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/7768cb83cf9c6e61f0afc50171d74eaa57775e05. Thanks Tom!

**Comment by tschoonj** [comment]
You're most welcome, as always...

Have you already managed to extend the time-out for #47924

**Comment by DomT4** [comment]
It's on my list. There's quite a lot of heavy stuff to get done tonight, including some security issues to chase.

**Comment by tschoonj** [comment]
Thanks!

**Pull request closed without merging**
