### PR TITLE
xz 5.2.2

### PR DESCRIPTION
**Pull request by chdiza**

### CODE REVIEW

**Comment by DomT4** [comment]
Failure wasn't your fault. `dpkg` had a dud El Cap bottle. Have put it back in the CI queue.

**Comment by chdiza** [comment]
OK.  I peeked at the failure log and had no idea what that meant.

**Comment by DomT4** [comment]
We mass produced El Cap bottles prior to release and not all of them published correctly. We're still finding a few here and there that didn't.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/dbf45d6f3806256c3bac7018ef1c3da4d256fb68. Thank you @chdiza!

**Pull request closed without merging**
