### PR TITLE
utils: support curl env

### PR DESCRIPTION
**Pull request by DomT4**
Self-explanatory request. Have wanted to do this for a while, but I don’t know how the maintainers feel. The general feeling towards screwing with the download mechanism too much has seemed a little reluctant, for understandable reasons, but limiting it to using a cURL means nothing else would need to change, and would be fairly predictable.

Open to outright rejection, but I live in hope.

### CODE REVIEW

**Comment by DomT4** [comment]
Pretty sure there's nothing the bot can actually test here, so I'll presume the bot crash can be ignored.

**Comment by mistydemeo** [comment]
Personally I'd be concerned about increasing our support load by allowing additional configurations here. What's the user benefit?

**Comment by DomT4** [comment]
Thanks for the comment :).

Primarily, my angle of concern is security based, around not being quite so dependent on Apple to fix security issues, especially on the slightly less new OS X versions which Apple isn't always super-quick to patch. In those situations, a ` curl ` which is optionally built against an OpenSSL or LibreSSL framework can be optionally used by a user instead of the default, if they so desire.

It's not something I think Homebrew needs to enforce, especially the optional args, but it's a useful option to have available. I'm not fundamentally opposed to enforcing it on the older systems, but I don't think that's a discussion desired - I appreciate entirely it's not really the Homebrew way to enforce things onto users.

The other aspect is choice, I guess. Homebrew permits the use of Homebrew's ` git ` in the ` $PATH `, and ` svn `, but not ` cURL `. So there's already a choice as such to use Homebrew's git or Homebrew's SVN as download tools for resources, HEADs, etc, just by installing them, but ` /usr/bin/curl ` is hardcoded. A lot of that is probably the first two not being ` keg_only ` whereas ` cURL ` is, I appreciate. Even if you stick ` HOMEBREW_PREFIX/opt/curl/bin` at the front of your ` $PATH ` permanently, Homebrew will ignore it :smile_cat:.

The options across ` cURL ` versions have remained pretty consistent, so theoretically Homebrew can go forwards with the same options in place without needing to tweak things to cater for alternative ` cURL ` installations. That's a theoretical I appreciate. I defer to you and the other maintainers as to whether theoretical translates to reality. I managed to do about 3 weeks of testing across OS X 10.9 and 10.10 with Homebrew's ` cURL `, built against OpenSSL and LibreSSL respectively, and haven't broken anything yet, but I don't have anything older than 10.9 set up on a VM at the moment.

**Comment by DomT4** [comment]
Blurgh, Sorry for the large comment. Trying to become more concise, but failing. Appreciate I'm a nightmare :sweat_smile:

**Comment by mikemcquaid** [comment]
I'm probably :-1: on this. I'm not sure it's worth the benefits of the increased support load by people potentially breaking their `curl` used by Homebrew.

**Comment by DomT4** [comment]
Cool. I don't mind at all if it's something you, Misty, Jack and co don't want to roll in. Just thought rather than rolling it around the back of my mind for weeks more I'd see what the general feeling is :smiley_cat:.

**Comment by DomT4** [comment]
Closing per yours' and Misty's comments. Thanks for the feedback both, appreciate it always :heart:.

**Pull request closed without merging**
