### PR TITLE
znc 1.6.0

### PR DESCRIPTION
**Pull request by hachidorii**

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Doesn't seem to compile on 10.8: http://bot.brew.sh/job/Homebrew%20Pull%20Requests/21384/version=mountain_lion/testReport/junit/brew-test-bot/mountain_lion/install_znc/

**Comment by mikemcquaid** [comment]
Squash commits by running `brew update; git checkout $YOUR_BRANCH; git rebase --interactive origin/master and then mark each commit other than the first as squash or fixup then git push -f. Thanks!

**Comment by Mikaela** [comment]
What is the current status of this pull request? It seems that what was asked to be done was done two days ago, but this appears to still be open.

**Comment by mikemcquaid** [comment]
Sorry, I apologise, when people push commits to PRs we don't receive email notifications so it takes someone commenting (thanks @Mikaela!) or us coming back to it later for us to see them.

**Comment by mikemcquaid** [comment]
@hachidorii Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
