### PR TITLE
test-bot/audit: Fix case-sensitive potential errors

### PR DESCRIPTION
**Pull request by DomT4**

### CODE REVIEW

**Comment by DomT4** [comment]
Re #36505

**Comment by mikemcquaid** [comment]
This doesn't seem to be the issue as I've checked these strings locally and they are fine. f150de5 should help the final devel-only issue I've seen locally.

**Comment by DomT4** [comment]
Thanks. What was the issue you were running in to locally? Is there anything I can do to help with the debug here, send a dummy PR at devel-only or anything?

**Comment by mikemcquaid** [comment]
Oh, just that it was trying and failing to make bottles which would make the build red.

**Comment by DomT4** [comment]
Ah. Was that knocking onto the audit failures and failure to pass the correct install flags?

**Comment by mikemcquaid** [comment]
Perhaps. Let me know if you see more `devel-only` red builds and I'll take a closer look.

**Comment by DomT4** [comment]
Will keep an eye out. Thanks for working on this :heart:

**Pull request closed without merging**
