### PR TITLE
activemq 5.13.0

### PR DESCRIPTION
**Pull request by StoicNZ**
Updating from ActiveMQ 5.11.2 to 5.13.0. Tested and working fine in OSX El Capitan.

### CODE REVIEW

**Comment by DomT4** [comment]
Test is failing, mind taking a look at that?
```
==> /usr/local/Cellar/activemq/5.13.0/bin/activemq-admin browse -h
/usr/local/Cellar/activemq/5.13.0/bin/activemq-admin: line 2: /usr/local/Cellar/activemq/5.13.0/libexec/bin/activemq-admin: No such file or directory
/usr/local/Cellar/activemq/5.13.0/bin/activemq-admin: line 2: exec: /usr/local/Cellar/activemq/5.13.0/libexec/bin/activemq-admin: cannot execute: No such file or directory
Error: activemq: failed
Failed executing: /usr/local/Cellar/activemq/5.13.0/bin/activemq-admin browse -h
```

**Comment by DomT4** [comment]
Ping?

**Comment by StoicNZ** [comment]
activemq-admin no longer used in 5.13.0, changed to look at activemq dir instead

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/950c0d449c3954c14c40b60a980d49269c2153f4. Thank you for your contribution to Homebrew @StoicNZ; we appreciate it! :smiley_cat:

**Pull request closed without merging**
