### PR TITLE
libusb 1.0.20

### PR DESCRIPTION
**Pull request by fran6co**

### CODE REVIEW

**Comment by fran6co** [comment]
@BrewTestBot test this please

**Comment by DomT4** [comment]
Our CI has been having some significant issues over the last week. It's slowly plowing through the backlog now. Please bear with it, Thanks!

**Comment by fran6co** [comment]
No problem, should I send another re run now or wait some more days?

**Comment by DomT4** [comment]
The build was done. There's a testing failure on Mavericks for another formula, can you look into it? Thanks.

```
==> /usr/local/Cellar/rkflashtool/5.1/bin/rkcrc input.file output.file
Error: rkflashtool: failed
<"ABCD\xB4\xF6\a\t"> (UTF-8) expected but was
<"ABCD\xB4\xF6\a\t"> (US-ASCII).
```

**Comment by fran6co** [comment]
I think the error is unrelated to libusb, but I fixed it anyways.

**Comment by DomT4** [comment]
@BrewTestBot test this please

**Comment by fran6co** [comment]
It's working now @DomT4

**Comment by DomT4** [comment]
Indeed it is. Merged in https://github.com/Homebrew/homebrew/commit/e9f5e7e11134d895f089a64a1abbd4896b98e86f. Thank you again @fran6co!

**Pull request closed without merging**
