### PR TITLE
formula: extend InstallRenamed for formula.var

### PR DESCRIPTION
**Pull request by xu-cheng**

### CODE REVIEW

**Comment by mikemcquaid** [comment]
I think as-is this will stop overwriting files in `var`. Do we want this? I'm not sure either way. What I think we definitely want is for files written to `var` to be put inside the Cellar for the bottles.

**Comment by xu-cheng** [comment]
Honestly, I don't know.

**Comment by xu-cheng** [comment]
@BrewTestBot test this please

**Comment by xu-cheng** [comment]
Should we do such change?

**Comment by mikemcquaid** [comment]
I'll check it out some more.

**Comment by mikemcquaid** [comment]
Yeh, I don't think we need this after all actually because we already handle bottling this directory correctly and the renaming stuff doesn't seem to be necessary or requested.

**Pull request closed without merging**
