### PR TITLE
UPDATED: LibSass formula to current version

### PR DESCRIPTION
**Pull request by aarongeorge**

### CODE REVIEW

**Comment by DomT4** [comment]
The test may need looking at:
```
==> /usr/bin/clang -o test test.c -lsass
test.c:1:10: fatal error: 'sass_context.h' file not found
#include <sass_context.h>
         ^
1 error generated.
Error: libsass: failed
Failed executing: /usr/bin/clang -o test test.c -lsass
```

**Comment by DomT4** [comment]
Kind of a weird test failure. Did they rename the executable?

```
==> /usr/local/Cellar/libsass/3.3.1/bin/sassc/bin/sassc --style compressed input.scss
Error: libsass: failed
No such file or directory - /usr/local/Cellar/libsass/3.3.1/bin/sassc/bin/sassc
```

**Comment by DomT4** [comment]
Oh wait. The code is slightly off. You just want:
```ruby
shell_output("#{bin}/sassc --style compressed input.scss").strip
```

**Comment by mikemcquaid** [comment]
Closing in favour of https://github.com/Homebrew/homebrew/pull/45919

**Pull request closed without merging**
