### PR TITLE
nghttp2 1.3.3

### PR DESCRIPTION
**Pull request by 187j3x1**

### CODE REVIEW

**Comment by 187j3x1** [comment]
I don't get it, takes too long to build?

**Comment by DomT4** [comment]
There appears to be some problem with the build on OS X 10.11. Will try and find some time to look into it locally.

**Comment by mikemcquaid** [comment]
@DomT4 Note the `boost` similar issue was fixed by removing `--verbose` from the test-bot flags.

**Comment by 187j3x1** [comment]
@DomT4 Nice work, it's fixed now.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/1ffc7083eef0c3ba6734b3e0b8a862be90c9ef7f. Thank you for your contribution to Homebrew @187j3x1; we appreciate it! :smiley_cat:

**Pull request closed without merging**
