### PR TITLE
riak: update 2.0.4

### PR DESCRIPTION
**Pull request by zeckalpha**
http://docs.basho.com/riak/latest/downloads/

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Would be good if we could start compiling from source to convince this to not link against the system OpenSSL: http://bot.brew.sh/job/Homebrew%20Pull%20Requests/19795/version=yosemite/testReport/junit/brew-test-bot/yosemite/audit_riak/

**Comment by zeckalpha** [comment]
I have compiled it from source manually before. I'll see if I can update
the formula to do so.

**Comment by zeckalpha** [comment]
I added `depends_on "openssl"` as the bot suggested. I squashed the commits and rebased; not sure how to get it to re-run the test.

**Comment by mikemcquaid** [comment]
> I added depends_on "openssl" as the bot suggested. I squashed the commits and rebased; not sure how to get it to re-run the test.

It does it as soon as the contents of the PR changes so you're good :+1:

**Comment by zeckalpha** [comment]
Hmm, that didn't help. Back to building from source, I guess.

**Comment by zeckalpha** [comment]
Building from source won't work (without serious patching... I've made it work before.) unless Erlang OTP is Release 16. The formula for Erlang is R17. Installing a binary avoids this issue since it includes an Erlang (R16) image along with the installation.

**Comment by mikemcquaid** [comment]
@zeckalpha Ok, no worries. Can you remove the `openssl` line then and give us a shout if/when this can use Erlang R17.

**Comment by zeckalpha** [comment]
SSL removed.

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! For future reference the preferred commit message format for simple version updates is `riak 2.0.4`.

**Pull request closed without merging**
