### PR TITLE
PyPy 2.5.1

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by DomT4** [comment]
Would close #38088 :).

**Comment by Lukasa** [comment]
:+1: * :100:

**Comment by tdsmith** [comment]
Timed out on the build VMs; we can extend the timeout and rebuild this when the bot is idle.

**Comment by cclauss** [comment]
resource "bootstrap" still refers to pypy-2.5.0 instead of 2.5.1

  resource "setuptools" still refers to setuptools-12.0.5 instead of 14.3.1

**Comment by tdsmith** [comment]
> resource "bootstrap" still refers to pypy-2.5.0 instead of 2.5.1

bootstrap should not need to change.

This would be a useful opportunity to upgrade setuptools.

**Comment by alex** [comment]
@tdsmith this pypy now includes `ensurepip`, do we need to update anything for that?

**Comment by tdsmith** [comment]
No, thanks for asking.

**Comment by alex** [comment]
@tdsmith Okey doke. I'll go ahead and upgrade setuptools while I'm here.

**Comment by tdsmith** [comment]
Thanks Alex!

**Comment by alex** [comment]
@tdsmith thanks!

**Pull request closed without merging**
