### PR TITLE
clutter-gtk 1.6.2

### PR DESCRIPTION
**Pull request by tschoonj**
version bump

### CODE REVIEW

**Comment by DomT4** [comment]
@BrewTestBot test this please

**Comment by tschoonj** [comment]
@DomT4 could you kick of another build? it failed because it needs the new clutter you just merged in.

My `plplot` update in #41187 also appears to be stuck. Could you look at this?

Thanks!

**Comment by DomT4** [comment]
It's already back in the queue. It'll be done after the current build.

Have asked the bot to stick the other PR on the queue as well.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/935dcb5b38129483236f52735646c00facff8b85. Thanks again!

**Pull request closed without merging**
