### PR TITLE
syncthing 0.11.20

### PR DESCRIPTION
**Pull request by mbi**

### CODE REVIEW

**Comment by DomT4** [comment]
Narrowly beat you to it in #42996, Sorry! Thanks for the submission though, :heart: the enthusiasm.

**Comment by mbi** [comment]
Ah cheers! Now if only *that one* could be merged already ;-)

**Comment by DomT4** [comment]
There was a slight issue on our side that had to be fixed before it could be merged. I'll check it again shortly.

**Comment by mbi** [comment]
Cheers. You guys rock!

**Pull request closed without merging**
