### PR TITLE
qemu: Add option to increase the max nics to 32

### PR DESCRIPTION
**Pull request by mbauden**
Added a 'with-32-nics' option and an inline patch for net.h changing MAX_NICS from 8 to 32. There is probably a better way to handle the patching here.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Can you point to anywhere in the official docs that says modifying this variable is supported? I'd rather not add an option like this unless upstream is happy with it. Thanks!

**Comment by mbauden** [comment]
This issue has been around for a bit. Here are a few links discussing it. The variable is there and hard coded to prevent you from exceeding the max number of PCI devices. This patch is mainly for use with GNS3 where you are using stripped down VMs and the additional NICs are useful.

https://bugzilla.redhat.com/show_bug.cgi?id=570907
https://bugs.launchpad.net/ubuntu/+source/qemu-kvm/+bug/595873
http://comments.gmane.org/gmane.comp.emulators.kvm.devel/60457
http://forum.proxmox.com/threads/4799-QEMU-8-NIC-limit
http://comments.gmane.org/gmane.comp.emulators.kvm.devel/60496

**Comment by mbauden** [comment]
One more note on this. This option is only required due to the need to use legacy nic's such as e1000. The newer virtio-net-pic type does not have this limitation. The problem here is that when emulating systems such as JunOS or NX-OS the virtio devices do not work nearly as well.

http://lists.nongnu.org/archive/html/qemu-devel/2010-10/msg00194.html

**Comment by mikemcquaid** [comment]
I think we' should probably pass on this as-is.

**Comment by jacknagel** [comment]
Passing on this as we typically do not carry feature patches that aren't moving upstream.

**Pull request closed without merging**
