### PR TITLE
docker-swarm 1.0.0

### PR DESCRIPTION
**Pull request by pwnall**
I changed the `url` block to match the format in the docker formula. I hope that's OK.

### CODE REVIEW

**Comment by bfontaine** [comment]
Is this necessary? If not we should use the tarball.

**Comment by pwnall** [comment]
@bfontaine It's not necessary. I switched back to the tarball.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/7c21a3ecee9c2abf3b0db349e139f1a2cec0a08d. Thank you for another contribution to Homebrew @pwnall! :smiley_cat:

**Comment by pwnall** [comment]
@DomT4 @bfontaine Thank you for the quick turnaround! :heart:

**Pull request closed without merging**
