### PR TITLE
conan 0.8.2

### PR DESCRIPTION
**Pull request by lasote**
Minor version for conan.

### All Submissions:

- [X] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew/blob/master/.github/CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew/pulls) for the same update/change?

### CODE REVIEW

**Comment by DomT4** [comment]
Doesn't recognise the new compiler with Xcode 7.3's release apparently:
```
==> /usr/local/Cellar/conan/0.8.2/bin/conan install zlib/1.2.8@lasote/stable

It seems to be the first time you run conan
Auto detecting your dev setup to initialize conan.conf
CC and CXX: /usr/bin/clang, /usr/bin/clang++ 
Found apple-clang 7.3
Default conan.conf settings
	os=Macos
	arch=x86_64
	compiler=apple-clang
	compiler.version=7.3
	compiler.libcxx=libc++
	build_type=Release
*** You can change them in ~/.conan/conan.conf ***
*** Or override with -s compiler='other' -s ...s***


ERROR: '7.3' is not a valid 'settings.compiler.version' value.
Possible values are ['5.0', '5.1', '6.0', '6.1', '7.0']
```

**Comment by lasote** [comment]
Yes, but... Apple clang passes from 7.0 to 7.3??? why???

**Comment by DomT4** [comment]
I do not have the power to say why Apple does anything Apple does I'm afraid :smile:.

**Comment by lasote** [comment]
:+1:  Thanks for notice! I'm closing this PR and will submit 0.8.3 (currently making with this patch)

**Comment by DomT4** [comment]
Thanks! Will keep an eye out for the fresh PR.

**Pull request closed without merging**
