### PR TITLE
logtalk 3.02.1

### PR DESCRIPTION
**Pull request by pmoura**

### CODE REVIEW

**Comment by dunn** [comment]
Seeing a SHA mismatch:
```
==> Downloading from https://codeload.github.com/LogtalkDotOrg/logtalk3/tar.gz/lgt3020stable
Warning: Formula reports different SHA256: acc38fd1037888875bd323137b5afd123eae7513bfc54bb221b83732d34916f1
Downloaded to: /Library/Caches/Homebrew/logtalk-3.02.1.tar.gz
SHA1: dfe602c1e4818b9008589db4ea68e858227bb546
SHA256: 4d0c5ad34653eeb71b3c90c084b734cb77e0676f07aa21a5849d6d2ba41763fb

**Comment by pmoura** [comment]
Sorry about that! Should be fixed now.

**Comment by DomT4** [comment]
Would you mind squashing your commits into one? The CI is having some issues pulling it cleanly. Thanks!

**Comment by pmoura** [comment]
Sure! Sorry for all the trouble.

**Comment by pmoura** [comment]
For some reason, squashing the commits didn't work. Closing this pull request and trying again with a new fork.

**Comment by DomT4** [comment]
No worries at all. Thanks for opening a new PR!

**Pull request closed without merging**
