### PR TITLE
Remove indefinite article from description

### PR DESCRIPTION
**Pull request by afh**
The changes were made with the following shell command:
for formula in $(grep -l 'desc "[Aa]n\?\s' Library/Formula/*.rb); do
  echo $formula
  vim -c '/desc "/s/[Aa]n\? //|normal f"gU2lZZ' $formula
done

### CODE REVIEW

**Comment by mikemcquaid** [comment]
@afh Cancelling the CI build. Please don't submit PRs that change lots (e.g. 5+) formula without notifying us as it messes with the bot.

**Comment by afh** [comment]
I'll remember it for future PRs.

How would you like to be notified?

**Comment by mikemcquaid** [comment]
Create an issue, ideally. If it's something like this that's running a script paste the script and maintainers may run it locally instead.

**Comment by xu-cheng** [comment]
Thanks @afh

**Comment by afh** [comment]
@mikemcquaid That makes perfect sense.

@xu-cheng :+1: You're welcome. I'm uncertain what you mean by "submit[ting] a PR on `desc` audit rule."

**Comment by bfontaine** [comment]
@afh What I think @xu-cheng means is you can submit a PR to add a `brew audit` rule on `desc`s starting with an indefinite article.

**Comment by afh** [comment]
@bfontaine Thanks for clarifying that.

@xu-cheng Here's the PR #42404.

**Pull request closed without merging**
