### PR TITLE
libunrar (new formula)

### PR DESCRIPTION
**Pull request by beville**
A new formula for building the unrar library from RARlabs.  This library will work with this python project:
https://github.com/matiasb/python-unrar

### CODE REVIEW

**Comment by jacknagel** [comment]
We already have an `unrar` formula, shouldn't this be part of that (note that Homebrew typically does not package libraries and executables separately)?

**Comment by beville** [comment]
Sure, whatever fits in the best way for you. It's a trivial formula either way.  Just a single compile line, a rename to a "dylib" extension, and an install to the lib.  If you want me to submit it that way, let me know.

**Comment by beville** [comment]
Looking at the unrar formula now, I see there are bottles as part of it, and I don't know how deal with that...

**Comment by DomT4** [comment]
Just ignore the bottle blocks in formulae. The test bot handles that particular section.

**Comment by xu-cheng** [comment]
Closing in favor of https://github.com/Homebrew/homebrew/pull/36917

**Comment by DomT4** [comment]
@xu-cheng Congrats on becoming a maintainer/Collaborator! Hadn't noticed till now. Well deserved! :+1:

**Comment by xu-cheng** [comment]
Thanks

**Pull request closed without merging**
