### PR TITLE
wine-1.7.53 devel

### PR DESCRIPTION
**Pull request by samrussell**
Travis-ci passes for OSX 10.10 (others in progress): https://travis-ci.org/samrussell/homebrew

I can confirm that flicker patch works just like on 1.7.52

Also includes compressed texture patch to fix games like Black and White etc

### CODE REVIEW

**Comment by uyjulian** [comment]
#45037 check

**Comment by samrussell** [comment]
Sorry for the duplicate, just figured I'd mention that I have it confirmed working with the flicker patch on Yosemite, and also see if the DXT patch could be merged in

**Comment by alexchandel** [comment]
Please rerun this, or ditch the patch if it fails again

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

For future reference the preferred commit message format for simple development version updates is `wine 1.7.53 (devel)`.

**Comment by DomT4** [comment]
Was merged in https://github.com/Homebrew/homebrew/commit/8ef29e6c9ffa2fabe6b5573cbbff7ec5034032c7 but didn't auto-close.

**Pull request closed without merging**
