### PR TITLE
FStar 0.9.2.0 (fix upstream)

### PR DESCRIPTION
**Pull request by beurdouche**
The version tag was re-pushed upstream and included fixes.
This updates the formula to use those changes =)

### CODE REVIEW

**Comment by mikemcquaid** [comment]
> The version tag was re-pushed upstream and included fixes.

Please ask them to not do that; a version with changes should have the patch release incremented.

**Comment by beurdouche** [comment]
Yes I know, it was partly my fault in fact, I should have said no to do that. Next time this will not happen, sorry.

**Comment by mikemcquaid** [comment]
@beurdouche No worries, these things happen, thanks for the apology!

**Comment by DomT4** [comment]
@BrewTestBot test this please

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/d687788990d47f416c8c1054cba55fa86e263cf9. Thank you for another contribution to Homebrew @beurdouche! :smiley_cat:

**Pull request closed without merging**
