### PR TITLE
SwiftLint 0.2.0

### PR DESCRIPTION
**Pull request by jpsim**
Thanks!

### CODE REVIEW

**Comment by jpsim** [comment]
Seems to have failed due to a known bug in ghprb: https://github.com/janinko/ghprb/issues/148

Could one of the admins test this again please?

**Comment by DomT4** [comment]
Already back in the queue.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/602cf5e62bfd9f2b492262ee28797033c9950746. Thank you for your contribution to Homebrew @jpsim!

**Comment by jpsim** [comment]
Great, thanks for your help.

**Pull request closed without merging**
