### PR TITLE
tarsnap-gui 0.8 (new formula)

### PR DESCRIPTION
**Pull request by shinnok**
Hi,

I know that this might be a long shot according to the submission rules, but I'm going to try anyway. My hopes are based on the handful of *exceptions* like MacVim already present in the repo and the fact that the application can operate headless to some extent.

Here's Tarsnap GUI the cross platform GUI for the Tarsnap command line client. The app has been in development for over an year. The only dependencies are Qt 5 and Tarsnap CLI, both dependencies are already present in the Homebrew repository. The app also features a headless operation mode, where system backups can be queued via cron or launchd, providing for little need to open the GUI once backup jobs have been defined and set for automatic backup. There are no prebuilt packages at the moment and we have plans to change that once we get to 1.0 and move this to Homebrew casks, but until then, it'd be cool to have an easy and seamless installation for OS X users and Homebrew is obviously the first choice for this.

https://github.com/Tarsnap/tarsnap-gui/wiki/Tarsnap
https://www.tarsnap.com

### CODE REVIEW

**Comment by DomT4** [comment]
This seems like a good fit for the newish https://github.com/Homebrew/homebrew-gui tap.

We are in the process of moving over some things that primarily offer a GUI, since generally there's no entirely useful way to test _functionality_ of GUI tools.

**Comment by shinnok** [comment]
Updated formula, all checks passed now.

**Comment by DomT4** [comment]
Please file this over at https://github.com/Homebrew/homebrew-gui; Thank you!

I suspect `qmake` is only a `:build` dep as well FWIW :).

**Comment by shinnok** [comment]
@DomT4  I'm in the process of recreating the PR for homebrew-gui. Not sure what you mean by `:build dep` though? `qmake` is a tool installed by the qt5 package and is similar to ./configure, a prerequisite for building the Makefiles, only specific to Qt.

**Comment by DomT4** [comment]
Sorry, I was thinking of `macdeployqt` rather than `qmake`, the former copies the necessary frameworks/etc into the `.app` bundle so `qt` isn't necessary after the build is finished, but there's no `macdeployqt` step here so it'll still be required.

**Pull request closed without merging**
