### PR TITLE
hackrf update to v2015.07.2

### PR DESCRIPTION
**Pull request by gyaresu**
I have added the correct checksum which was the problem in this other PR: https://github.com/Homebrew/homebrew/pull/42577

### CODE REVIEW

**Comment by dunn** [comment]
While you're at it, would it be possible to add a better test, preferably something that doesn't exit with `1`? Thanks!

**Comment by gyaresu** [comment]
I haven't written ruby tests before but I'll have a look at some others and give it a go.

**Comment by gyaresu** [comment]
Ah. I see the problem in choosing a good way to test.
Without the board plugged in you don't have many options.

coming back with a success from `hackrf_transfer` (which just outputs the help info) seems fairly logical.

Ideas?

**Comment by dunn** [comment]
Oh, I see the issue.  I think we can live with it as it is.

**Comment by dunn** [comment]
Merged in b38ed95461f0ee3df9b27408c3ee364d0697ee4d 📯

**Pull request closed without merging**
