### PR TITLE
Revert gstreamer patches merged into upstream

### PR DESCRIPTION
**Pull request by rhendric**

### CODE REVIEW

**Comment by mikemcquaid** [comment]
If they were merged upstream we'll need a new release to be able to remove the patches.

**Comment by rhendric** [comment]
1.6.1 is that release.

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

For future reference the preferred commit message format for simple version updates is `gstreamer: revert patches merged into upstream.` and a single commit for each changed formula.

**Comment by DomT4** [comment]
@mikemcquaid *cough*, you forgot something :wink:

**Pull request closed without merging**
