### PR TITLE
erlang: update to otp-18.0

### PR DESCRIPTION
**Pull request by optikfluffel**
- [x] couchdb #41128
- [x] lfe #41121
- [x] elixir #41191
- [x] rebar #41119
- [x] geocouch - [_comment_](https://github.com/Homebrew/homebrew/pull/41035#issuecomment-122279385)
- [x] kjell #41645
- [x] mercury - [_comment_](https://github.com/Homebrew/homebrew/pull/41035#issuecomment-122512582)
- [x] syntaxerl [ten0s/syntaxerl#8](https://github.com/ten0s/syntaxerl/issues/8#issuecomment-120861613)
- [x] tsung - #41976
- [ ] wrangler [RefactoringTools/wrangler#67](https://github.com/RefactoringTools/wrangler/issues/67)
- [x] yaws #41668

### CODE REVIEW

**Comment by jacknagel** [comment]
Does elixir / couchdb / other `$(brew uses erlang)` work with this version?

**Comment by patrickdet** [comment]
Elixir will work with this version

**Comment by ACPK** [comment]
@DomT4 Any idea on when this will be committed?

**Comment by DomT4** [comment]
Just waiting on confirmation the `brew uses erlang` stuff doesn't break if we pull this really. It can be a delicate ecosystem.

**Comment by mikemcquaid** [comment]
I tested everything locally. Stuff that builds:
`couchdb disco ejabberd yaws`

Stuff that doesn't build (i.e. needs a version bump):
`elixir geocouch kjell lfe mercury rebar syntaxerl tsung wrangler yaws `

**Comment by nijikon** [comment]
#41119

**Comment by nijikon** [comment]
#41119

**Comment by nijikon** [comment]
#41121

**Comment by dch** [comment]
CouchDB needs some patches, https://github.com/apache/couchdb/commit/95cb436be30305efa091809813b64ef31af968c8 which are not in an official release tarball yet. @mikemcquaid the configure script should bail out well before the build finishes BTW, so not sure how. How about we apply the minimal patch? https://gist.github.com/dch/75e95dd69837fe73e0aa

**Comment by dch** [comment]
See #41128 for CouchDB patch.

**Comment by tyre** [comment]
Elixir support in #41191 by @thecodeboss

**Comment by dch** [comment]
A minor patch for OTP-18.0.1 http://erlang.org/download/OTP-18.0.1.README that fixes a serious but rare ERTS bug released yesterday. @optikfluffel can you add this into your PR please? man and html don't change from 18.0. files.

```
    url "https://github.com/erlang/otp/archive/OTP-18.0.1.tar.gz"
    sha256 "6d8ad3c1e93d3226d1837e2b55435174d084fa4eb720d98cc3858f44a3f14176"
```

**Comment by optikfluffel** [comment]
@dch sure and thanks :heart_decoration:

**Comment by orendon** [comment]
@dch @optikfluffel great, thx!

**Comment by DomT4** [comment]
Where are we on this? What still needs new versions/patching/etc to build?

**Comment by thecodeboss** [comment]
Looking forward to seeing this committed, OTP 18 has a lot of cool stuff!

**Comment by optikfluffel** [comment]
It seems the build bot is stuck(?), does anybody know how to re-trigger it?

**Comment by xu-cheng** [comment]
@BrewTestBot test this please

**Comment by optikfluffel** [comment]
Something is [still wrong with CouchDB](http://bot.brew.sh/job/Homebrew%20Pull%20Requests/29234/testReport/) here, seems the script tries to download a bottle that isn't built yet.

**Comment by mikemcquaid** [comment]
@optikfluffel that's fixed now, thanks

**Comment by optikfluffel** [comment]
Citing @DomT4:
> Where are we on this? What still needs new versions/patching/etc to build?

Anything missing for a merge?

**Comment by mikemcquaid** [comment]
Stuff that needs updated:
- [x] couchdb
- [x] lfe
- [x] elixir
- [x] rebar
- [ ] geocouch
- [ ] kjell
- [ ] mercury
- [ ] syntaxerl
- [ ] tsung
- [ ] wrangler
- [ ] yaws

**Comment by tyre** [comment]
@vmx Issues aren't public for geocouch, do you have plans on upgrading to OTP 18 or need help doing so?

**Comment by vmx** [comment]
@tyre I've compiled GeoCouch (the branch you want its 1.3.x) and it compiled well, it just emitted two warnings. Is that good enough?

**Comment by dch** [comment]
FWIW we now have OTP 18.0.2 already:

```
url "https://github.com/erlang/otp/archive/OTP-18.0.2.tar.gz"
sha256 "b8c4af95376cd8a67b1f3cfb54ce4cbc7a548cac2293e9a0e865f2c058402a8e"
```

**Comment by tyre** [comment]
@vmx 
Is 1.3.x stable and on homebrew already?

As for warnings, what were they?

**Comment by tyre** [comment]
@optikfluffel How do you see the output for @BrewTestBot ?
[Searching for the PR](http://bot.brew.sh/search/?q=PR+%2341035) doesn't show anything.

**Comment by optikfluffel** [comment]
@BrewTestBot test this please

**Comment by mikemcquaid** [comment]
@BrewTestBot test this please

**Comment by mikemcquaid** [comment]
The output is removed after 7 days (or a certain number of builds). It's up again.

**Comment by DomT4** [comment]
> his trick doesn't seem to work for me xD

The test-bot is supposed to ignore requests from people who don't have push access to the Repo, which is why you didn't trigger it :)

**Comment by tyre** [comment]
Awesome thank you. I'm getting in touch with different library maintainers and it is helpful to have the raw output.

Where do you see what has failed? The raw output (e.g. http://bot.brew.sh/job/Homebrew%20Pull%20Requests/29238/version=mavericks/console) looks fine.

**Comment by mikemcquaid** [comment]
There's no failures, we need these packages all confirmed to work: https://github.com/Homebrew/homebrew/pull/41035#issuecomment-119550179

**Comment by tyre** [comment]
yaws was just updated to work with 18.0 => https://github.com/klacke/yaws/issues/226

**Comment by vmx** [comment]
@tyre I don't know which branch of GeoCouch is in Homebrew, but I would expect it to be 1.3.x. The warnings are about the new time functions.

**Comment by tyre** [comment]
`kjell` has been verified: https://github.com/karlll/kjell/issues/26#issuecomment-120704434

**Comment by optikfluffel** [comment]
`syntaxerl` [should be ok](https://github.com/ten0s/syntaxerl/issues/8#issuecomment-120861613) for now.

**Comment by optikfluffel** [comment]
@vmx yes [it's the 1.3 version](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/geocouch.rb#L6) would it be hard to use the new time functions, when running on OTP18, to remove those warning?

**Comment by vmx** [comment]
@optikfluffel I pushed a new commit to the 1.3.x branch which should compile without warnings.

**Comment by optikfluffel** [comment]
tsung should be ready next week. ircleak:

> The current git version works fine with R18; i'm not so sure for the current release (1.5.1)
> it's definitely time to release a new tsung version ...
> maybe next week

PS: @vmx Thanks :heart_decoration:

**Comment by optikfluffel** [comment]
Mercury is also good to go, mailleak:

> Mercury's Erlang backend is still an experimental feature, but as far as it goes it (i.e. Mercury 14.01.1) works with OTP18.

**Comment by aposto** [comment]
Do you still check the Wragler?
It is waiting too long.

**Comment by DomT4** [comment]
There has been no additional upstream activity at `wrangler` since we reported it doesn't build against the new Erlang there.

**Comment by reset** [comment]
Is there a policy on leaving behind packages which aren't updating in a timely manner?

**Comment by DomT4** [comment]
Per upstream, the last straggler here should be ready to go next week, at which point we can ship the new Erlang.

**Comment by reset** [comment]
@DomT4 great news :+1:

**Comment by dch** [comment]
thanks @mikemcquaid for keeping everybody on track. this is clearly a big job shepherding all these through.

for future we could consider how FreeBSD ports handles it:

- there's a "default" erlang.rb which slowly moves along as & when all dependencies are capable
- when OTP 19.0 appears, a new erlang-19.0.rb would be created, and apps can switch to that either during testing, or when they're stable
- when they're all switched over to OTP 19.0, we update erlang.rb & all the dependencies

I am not sure how well this works wrt bottles and people on older systems where they need to build everything from source, but it might help keep things moving.

**Comment by dch** [comment]
erm and obviously there's an erlang-17.0.rb for stragglers...

**Comment by mikemcquaid** [comment]
The way we tend to handle this is that the stragglers just vendor their own copy of Erlang inside the formula.

**Comment by felixbuenemann** [comment]
@optikfluffel There were a bunch of deprecation warnings, but I could brew install **wrangler** 1.1.01 successfully on OTP 18.0.2. What build errors were you seeing?

**Comment by thecodeboss** [comment]
How much longer is this going to take? It sounds as though this PR is ready to merge.

**Comment by DomT4** [comment]
Upstream think Wrangler is [fine](https://github.com/RefactoringTools/wrangler/issues/67#issuecomment-128644605). If it is, we can go.

**Comment by DomT4** [comment]
@BrewTestBot test this please

**Comment by bbhoss** [comment]
Looking good! Can we merge? Ready to be able to do brew install erlang and have 18 :)

**Comment by DomT4** [comment]
I guess with Wrangler confirming there should be no issues on their end and everything else being checked off the list we can pull this.

On the timeline: Erlang is used widely enough that even small breakages cause major headaches, and that necessitates a certain hang time whilst upstream projects are readied. If Wrangler had taken a while longer it's possible we'd vendor the old Erlang into the Wrangler formulae. We appreciate the wait can be a little frustrating, but we do everything within our power to be as quick as possible without making users suddenly install 15 vendored versions of Erlang :smile:.

Merged in https://github.com/Homebrew/homebrew/commit/ddfed35952da232f7603923cd13364975a6f8226. Thank you for your contribution to Homebrew @optikfluffel, and sticking with us on chasing up with the various projects. We appreciate that.

**Pull request closed without merging**
