### PR TITLE
Remove (dead) coremod formula.

### PR DESCRIPTION
**Pull request by geoff-codes**
The https://github.com/cmatsuoka/coremod repository no longer exists.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Could you add this to `tap_migrations.rb` and add a pull request to `homebrew-boneyard` too? No worries if not!

**Comment by geoff-codes** [comment]
Sure — I've also found "dbslayer" seems dead too... the entire codes.nytimes.com subdomain is gone. Same thing?

**Comment by geoff-codes** [comment]
And "dromeaudio"... tell you what, I'll close this for now and come back with a full list.

**Comment by mikemcquaid** [comment]
With these things if we can find a new source for them that'd be ideal but if not: no worries. Thanks!

**Pull request closed without merging**
