### PR TITLE
manpages: post-reformatting fixups

### PR DESCRIPTION
**Pull request by apjanke**
DO NOT MERGE YET. This is work in progress, made a PR so people can comment on it.

#46676 introduced a couple issues with spacing and markup. This PR will resolve them.

### CODE REVIEW

**Comment by UniqMartin** [comment]
Could you address the spacing issues [we talked about](https://github.com/Homebrew/homebrew/commit/4dca01fc791d352116f7657ce46b7f1d59abc84c#commitcomment-14804782) so that we can get this merged soon?

**Comment by apjanke** [comment]
I've pushed a commit for the spacing issues, changing in to no spaces inside `[...]` brackets, and no spaces around `|` for alternations. Think I got them all.

**Comment by apjanke** [comment]
Maybe we should also consider switching to non-hard-wrapped paragraphs. The current code is a mix of long lines and manually hard-wrapped lines. Removing the hard wrapping would make it look nicer in an editor.

**Comment by dunn** [comment]
> Removing the hard wrapping would make it look nicer in an editor.
Depends on the editor! 👹👹👹

**Comment by apjanke** [comment]
Since there are already some super-long lines in the existing page, I think you're stuck viewing it with word wrapping. But there's only a few of them, and they're mostly the headers for per-command sections. This would be a pretty big change and I guess it should probably be tabled.

**Comment by UniqMartin** [comment]
> Think I got them all.

What about `search <text> | /<text>/` in the `ESSENTIAL COMMANDS` section? You also haven't run `brew man` to update the other two files.

> Maybe we should also consider switching to non-hard-wrapped paragraphs. The current code is a mix of long lines and manually hard-wrapped lines.

I'd keep the hard-wrapped text to keep the changes small, as the benefits are debatable. I only saw two lines that are long and could be adjusted to match the rest: The description of `--verbose` in the `ESSENTIAL COMMANDS` section and the list of maintainers in the `AUTHORS` section. The other long lines are all either links or lines showing the command syntax and those should not be wrapped (IMO).

Another thing I have noticed:

- `search --debian|--fedora|--fink|--macports|--opensuse|--ubuntu <text>`: I think we should put parentheses around those alternatives, like in `tap-info --json=<version> (--installed|<taps>)`.

**Comment by apjanke** [comment]
I've updated those extra items under `search` and regenerated the output files with `brew man`.

**Comment by UniqMartin** [comment]
I found two entries with missing colons and another superfluous backtick. Instead of describing them verbally, [here's a patch for `brew.1.md`](https://gist.github.com/UniqMartin/d7db0d006b949c109f17) you can apply on top of your changes. (And you'll have to rerun `brew man` of course.)

**Comment by apjanke** [comment]
Pulled in that patch.

**Comment by UniqMartin** [comment]
I think this should be squashed to a single commit, but then it's ready to be merged.

**Comment by mikemcquaid** [comment]
:+1:

**Comment by apjanke** [comment]
Squashed & merged.

**Pull request closed without merging**
