### PR TITLE
keybase 0.7.8

### PR DESCRIPTION
**Pull request by dunn**

### CODE REVIEW

**Comment by dunn** [comment]
Bot goof on Mavericks and Yosemite:
```
==> brew cleanup --prune=30						Error: invalid byte sequence in US-ASCII
 PASSED
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/cmd/test-bot.rb:858:in `delete'
/usr/local/Library/Homebrew/cmd/test-bot.rb:858:in `block (2 levels) in test_bot'
/usr/local/Library/Homebrew/cmd/test-bot.rb:850:in `each'
/usr/local/Library/Homebrew/cmd/test-bot.rb:850:in `block in test_bot'
/usr/local/Library/Homebrew/cmd/test-bot.rb:845:in `each'
/usr/local/Library/Homebrew/cmd/test-bot.rb:845:in `test_bot'
/usr/local/Library/brew.rb:140:in `<main>'
Build step 'Execute shell' marked build as failure
```

**Comment by DomT4** [comment]
That's happened a few times today. We need to hunt down the root cause ideally. (In general, not specifically in this PR).

**Comment by mikemcquaid** [comment]
I may have fixed it.

**Comment by DomT4** [comment]
Issue seems to be persisting.

**Comment by jacknagel** [comment]
I fixed this a long time ago, but recent changes removed my fix. I fixed it again.

**Pull request closed without merging**
