### PR TITLE
thefuck 2.3

### PR DESCRIPTION
**Pull request by scorphus**
Update TheFuck formula form 1.48 to 2.3

### CODE REVIEW

**Comment by dunn** [comment]
Looks like the alias setup has been [changed again](https://github.com/nvbn/thefuck#installation):
```shell
eval "$(thefuck-alias)"
# You can use whatever you want as an alias, like for Mondays:
eval "$(thefuck-alias FUCK)"
```

**Comment by scorphus** [comment]
Yes! I am sorry for not paying attention to that. I'll update this PR.

**Comment by scorphus** [comment]
Done so. Thanks, @dunn.

How about that build failure?

**Comment by dunn** [comment]
Most of the failures are just a style issue; we prefer `assert_match` to `assert "".include?`  But I'm not sure yet what this error on the Yosemite build means:
```
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/thefuck/2.2/libexec --single-version-externally-managed --record=installed.txt
error in thefuck setup command: Invalid environment marker: python_version<"3.4"
```

**Comment by scorphus** [comment]
I'll fix those style issues, try to understand and fix that *error in thefuck setup command* and update this PR.

**Comment by scorphus** [comment]
I can reproduce the error. I'm trying to fix it.

**Comment by scorphus** [comment]
I can see what's wrong. Fixing it.

**Comment by dunn** [comment]
Why does setuptools need to be vendored here? Might want @tdsmith to sign off on this change.

**Comment by tdsmith** [comment]
The commit message explains; OS X ships an antediluvian version of setuptools. It may sometimes be possible to install setuptools to buildpath instead of installing it into the package's prefix with the other dependencies but I don't think that's usually worth the extra complexity. This LGTM.

**Comment by dunn** [comment]
Woops, didn't see that. Thanks!

**Comment by scorphus** [comment]
As detailed in 83cda02274c03e94ebae99de172204eeeb9dfc34:
> Since 17.1.1, setuptools [supports range operators on environment marker evaluation](https://bitbucket.org/pypa/setuptools/src/4d9f9b165476ffd77a2feeb24b232a633ee46aff/CHANGES.txt#CHANGES.txt-46).

According to TheFuck's [setup.py](https://github.com/nvbn/thefuck/blob/6c534c52bca30f36a9b4bcb26ef9784ed6bba76d/setup.py#L17), it requires [pathlib](https://pypi.python.org/pypi/pathlib) only for Python versions < 3.4:
```python
extras_require = {':python_version<"3.4"': ['pathlib']}
```
This notation is only supported by setuptools>=17.1.1

Regarding this, I have a question: should pathlib be conditionally (i.e. python<3.4) added as a resource?

**Comment by tdsmith** [comment]
The dependency `depends_on :python if MacOS.version <= :snow_leopard` always gives you Python 2.7. (In the absence of a :python dependency, formulas use Apple's system python, which has been 2.7.x since Lion.)

**Comment by scorphus** [comment]
Understood. Thanks, @tdsmith.

**Comment by scorphus** [comment]
In time, let me fix that typo :relaxed:

**Comment by Anahkiasen** [comment]
2.3 is out now :d

**Comment by DomT4** [comment]
I was about to merge this as well :laughing:. Let's update this to 2.3 and one of us will merge it in this afternoon.

**Comment by scorphus** [comment]
Oh... I saw that but focused on that problem and totally forgot it. Updating the formula.

**Comment by scorphus** [comment]
Oh... I should have changed the first commit and rephrased the subsequent! Let me fix that!

**Comment by Anahkiasen** [comment]
Could just squash all the commits

**Comment by scorphus** [comment]
Do you really prefer? I mean, wouldn't it be important to maintain this history?

**Comment by DomT4** [comment]
I'll squash them on pull this time, there's no point making the bot do it over again just for a squash.

Our preference is to only merge one commit per formula change, yes. The history of what happened prior to the final product being ready isn't important enough to justify spamming up the Homebrew commit tree, which enough people read that we'd get complaints about.

**Comment by scorphus** [comment]
Understood and agreed. Thanks, @DomT4.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/231128b29c8ad5ba241b96092853c5256ceed808. Thank you for your contribution to Homebrew, and sticking around to figure out the encountered build errors, we appreciate it! :smiley_cat:.

**Comment by scorphus** [comment]
My pleasure! I'm glad to contribute. It was really nice interacting with you and learning new things. Thank you all for that! :+1:

**Comment by DomT4** [comment]
Thanks! Happy we could be useful. Always welcome to ping us if you have any questions on this sort of thing.

**Pull request closed without merging**
