### PR TITLE
Apache TomEE 1.7.3

### PR DESCRIPTION
**Pull request by cchacin**

### CODE REVIEW

**Comment by DomT4** [comment]
@BrewTestBot test this please

**Comment by dunn** [comment]
Jenkins is being finicky about merging the patch.  Can you rebase against `origin/master` and squash down to one commit? Thanks!

**Comment by cchacin** [comment]
@dunn Done!

**Comment by DomT4** [comment]
Aha, I'm not about to become your favourite person here, but slight miscommunication. Should be one commit per changed formula :cry:.

**Comment by dunn** [comment]
My fault, though; I didn't look closely enough at the diff. Sorry!

**Comment by cchacin** [comment]
@DomT4 @dunn but could be the same PR? or 4 different PRs with 1 commit each?

**Comment by DomT4** [comment]
It's alright to be in the same PR here. Just has to be one commit per formula changed.

**Comment by cchacin** [comment]
@DomT4 @dunn Done!

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

For future reference the preferred commit message format for simple version updates is `tomee-webprofile 1.7.3`.

**Pull request closed without merging**
