### PR TITLE
autocode: rename from crystal

### PR DESCRIPTION
**Pull request by ctate**
Hi - we have renamed our project as `autocode` to resolve conflicts with `crystal` which should be used for crystal-lang (manastech/crystal) instead.

### CODE REVIEW

**Comment by dunn** [comment]
Just two audit failures;
```
==> audit problems
autocode:
 * File should end with a newline
 * Non-executables were installed to "/usr/local/Cellar/autocode/0.20.2/bin"
The offending files are:
  /usr/local/Cellar/autocode/0.20.2/bin/cli
```

**Comment by xu-cheng** [comment]
You should delete `Library/Formula/crystal.rb` and update `Library/Homebrew/formula_renames.rb`

More doc: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Rename-A-Formula.md

**Comment by ctate** [comment]
@xu-cheng Thanks - will that make `crystal` available for someone else to use? I'd like to make sure manastech/crystal can use it for the Crystal language.

**Comment by xu-cheng** [comment]
>  will that make crystal available for someone else to use?

Yes, it will.

**Comment by ctate** [comment]
Awesome, thanks.

**Comment by xu-cheng** [comment]
Sorry, but can you rebase this? Thanks.

**Comment by ctate** [comment]
Done!

**Comment by xu-cheng** [comment]
Thanks for the pull request! 🎉 Homebrew depends on contributions from community members like you and we're grateful for your support.

**Pull request closed without merging**
