### PR TITLE
add `bottle :disable` DSL

### PR DESCRIPTION
**Pull request by xu-cheng**
cc @Homebrew/owners

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Can we go for `:unneeded` perhaps? We could maybe add a `:disabled:` too for the case where the bottling process is known to be broken for that package.

**Comment by mikemcquaid** [comment]
Code changes look good :+1:

**Comment by mikemcquaid** [comment]
Also perhaps having the second argument be a reason wouldn't be a bad thing.

**Comment by xu-cheng** [comment]
> Can we go for :unneeded perhaps? 

Done.

> Also perhaps having the second argument be a reason wouldn't be a bad thing.

I'm thinking `bottle :unneeded` strictly means no compile is required, so we can use it for no Xcode/CLT system. We can consider add reason for `bottle :disable`.

**Comment by mikemcquaid** [comment]
> I'm thinking bottle :unneeded strictly means no compile is required, so we can use it for no Xcode/CLT system. We can consider add reason for bottle :disable.

Yep, that sounds good :+1:

**Comment by mikemcquaid** [comment]
`:disable` works for me :+1:

**Comment by xu-cheng** [comment]
I will work on this maybe this weekend.

**Comment by xu-cheng** [comment]
Updated. The DSL will be looked like these:
```ruby
bottle :unneeded # doesn't need compiling, useful for non-Xcode/CLT install.

bottle :disable, "the reason"
```

@mikemcquaid, could you help to double check that this PR won't break the bottle hooks used by Boxen?

**Comment by mikemcquaid** [comment]
Looks good to me :+1:

**Pull request closed without merging**
