### PR TITLE
Gnome 3.18.1 updates

### PR DESCRIPTION
**Pull request by tschoonj**

### CODE REVIEW

**Comment by dunn** [comment]
A couple different test failures: http://bot.brew.sh/job/Homebrew%20Pull%20Requests/34739/

**Comment by tschoonj** [comment]
This looks quite suspicious to me: it's showing failures due to cogl and gtk+3 missing but those packages are listed as dependencies, either directly or recursively.

I noticed that the test is now running in a sandbox. What does this do exactly?

**Comment by mikemcquaid** [comment]
@tschoonj The sandbox verifies that the test doesn't try to write any files in weird locations, it won't cause this failure. My thought is that a library version or something has changed?

**Comment by tschoonj** [comment]
No I don't think so actually. If I run `brew test libchamplain` locally with these updates installed everything runs fine.

It looks like a Homebrew issue to me. This happened on Mavericks:

````
==> brew uses clutter
==> brew fetch --retry atk cairo cogl docbook docbook-xsl fontconfig freetype gdbm gdk-pixbuf gettext git glib gnome-doc-utils gobject-introspection gtk-doc harfbuzz icu4c itstool jpeg json-glib libffi libpng libtiff libxml2 makedepend openssl pango pixman pkg-config python readline sqlite
==> brew fetch --retry --build-bottle --force clutter
==> brew uninstall --force clutter
==> brew install --only-dependencies --verbose --build-bottle clutter
==> brew install --verbose --build-bottle clutter
==> brew audit clutter
==> brew bottle --verbose --rb clutter
==> brew uninstall --force clutter
==> brew uninstall --force git gnome-doc-utils itstool makedepend
==> brew install ./clutter-1.24.2.mavericks.bottle.tar.gz
==> brew test --verbose clutter
==> brew fetch --retry clutter-gst
==> brew install clutter-gst
==> brew test --verbose clutter-gst
==> brew test --verbose libchamplain
==> FAILED
Testing libchamplain
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20151014-11339-nxb55c.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Library/Homebrew -- /usr/local/Library/Homebrew/test.rb /usr/local/Library/Formula/libchamplain.rb --verbose
==> /usr/bin/clang test.c -o test -Os -w -pipe -march=native -mmacosx-version-min=10.9 -F/usr/local/Frameworks -I/usr/include/libxml2 -L/usr/local/lib -F/usr/local/Frameworks -Wl,-headerpad_max_install_names -I/usr/local/opt/atk/include/atk-1.0 -I/usr/local/opt/cairo/include/cairo -I/usr/local/opt/clutter/include/clutter-1.0 -I/usr/local/opt/cogl/include/cogl -I/usr/local/opt/fontconfig/include -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/opt/gdk-pixbuf/include/gdk-pixbuf-2.0 -I/usr/local/opt/gettext/include -I/usr/local/opt/glib/include/gio-unix-2.0/ -I/usr/local/opt/glib/include/glib-2.0 -I/usr/local/opt/glib/lib/glib-2.0/include -I/usr/local/opt/gtk+3/include/gtk-3.0 -I/usr/local/Cellar/libchamplain/0.12.11/include/libchamplain-0.12 -I/usr/local/opt/json-glib/include/json-glib-1.0 -I/usr/local/opt/libepoxy/include -I/usr/local/opt/libpng/include/libpng16 -I/usr/local/opt/libsoup/include/libsoup-2.4 -I/usr/local/opt/pango/include/pango-1.0 -I/usr/local/opt/pixman/include/pixman-1 -D_REENTRANT -L/usr/local/opt/atk/lib -L/usr/local/opt/cairo/lib -L/usr/local/opt/clutter/lib -L/usr/local/opt/cogl/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/glib/lib -L/usr/local/opt/json-glib/lib -L/usr/local/Cellar/libchamplain/0.12.11/lib -L/usr/local/opt/pango/lib -latk-1.0 -lcairo -lcairo-gobject -lchamplain-0.12 -lclutter-1.0 -lcogl -lcogl-pango -lcogl-path -lgio-2.0 -lglib-2.0 -lgmodule-2.0 -lgobject-2.0 -lintl -ljson-glib-1.0 -lpango-1.0 -lpangocairo-1.0
==> ./test
dyld: Library not loaded: /usr/local/lib/libgdk-3.0.dylib
  Referenced from: /usr/local/lib/libchamplain-0.12.0.dylib
  Reason: image not found
Error: libchamplain: failed
Failed executing: ./test 
/usr/local/Library/Homebrew/formula.rb:1353:in `block in system'
/usr/local/Library/Homebrew/formula.rb:1290:in `open'
/usr/local/Library/Homebrew/formula.rb:1290:in `system'
/usr/local/Library/Formula/libchamplain.rb:105:in `block in <class:Libchamplain>'
/usr/local/Library/Homebrew/formula.rb:1199:in `block in run_test'
/usr/local/Library/Homebrew/extend/fileutils.rb:17:in `mktemp'
/usr/local/Library/Homebrew/formula.rb:1195:in `run_test'
/usr/local/Library/Homebrew/test.rb:28:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/usr/local/Library/Homebrew/test.rb:27:in `<main>'
````

It is trying to test libchamplain but doesn't install its gtk+3 dependency, though it's :recommended in the libchamplain formula.

**Comment by tschoonj** [comment]
I fixed the libchamplain problem. It had indeed something to with dependencies.

But now the bottling goes wrong on Mavericks :cry:

**Comment by DomT4** [comment]
It's doing the thing where it attempts to fetch bottles that haven't yet been published. I don't know why this keeps happening for GTK related projects exclusively on Mavericks.

**Comment by DomT4** [comment]
Maybe it's worth trying moving the `glib` commit to before the `clutter` commit here, so the `glib` bottle is cached locally before the `clutter` build starts.

**Comment by tschoonj** [comment]
nope didn't make any difference :-(

**Comment by DomT4** [comment]
I don't quite understand what's going on. Yosemite and El Cap are doing the `glib` build first and consequently already have the bottle available for the `clutter` compile and pass the build, but the Mavericks bot is still doing `clutter` before `glib` and dying. Why would that behaviour be different across the CI.

**Comment by tschoonj** [comment]
It's quite strange indeed. I will close this PR and create individual PRs

**Pull request closed without merging**
