### PR TITLE
swiftlint 0.7.0

### PR DESCRIPTION
**Pull request by jpsim**
Thanks!

### CODE REVIEW

**Comment by jpsim** [comment]
It seems the Yosemite build on Jenkins failed due to simulator issues unrelated to this patch:

```
  0  0x00007fff8de64024 __exceptionPreprocess (in CoreFoundation)
  1  0x00007fff8e33176e objc_exception_throw (in libobjc.A.dylib)
  2  0x00007fff8de63e1a +[NSException raise:format:arguments:] (in CoreFoundation)
  3  0x00007fff9010699b -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] (in Foundation)
  4  0x000000010f2592e5 -[SimServiceContext reloadServiceIfMovedOrAbortIfWeAreInvalid] (in CoreSimulator)
  5  0x000000010f259c03 -[SimServiceContext connect] (in CoreSimulator)
  6  0x000000010f2588bc -[SimServiceContext initWithConnectionType:] (in CoreSimulator)
  7  0x000000010f25841a +[SimServiceContext simContextWithConnectionType:] (in CoreSimulator)
  8  0x000000010f2583cb __41+[SimServiceContext sharedServiceContext]_block_invoke (in CoreSimulator)
  9  0x00007fff98acee73 _dispatch_client_callout (in libdispatch.dylib)
 10  0x00007fff98aced86 dispatch_once_f (in libdispatch.dylib)
 11  0x000000010f2583a9 +[SimServiceContext sharedServiceContext] (in CoreSimulator)
 12  0x000000010f27841a +[SimDeviceSet setForSetPath:] (in CoreSimulator)
 13  0x000000010f2783b6 +[SimDeviceSet defaultSet] (in CoreSimulator)
 14  0x0000000112b7dfe0 __42-[DVTiPhoneSimulatorLocator startLocating]_block_invoke (in IDEiOSSupportCore)
 15  0x0000000109223a58 __DVTDispatchAsync_block_invoke (in DVTFoundation)
 16  0x00007fff98ad2700 _dispatch_call_block_and_release (in libdispatch.dylib)
 17  0x00007fff98acee73 _dispatch_client_callout (in libdispatch.dylib)
 18  0x00007fff98ad1dc7 _dispatch_root_queue_drain (in libdispatch.dylib)
 19  0x00007fff98ad1a1c _dispatch_worker_thread3 (in libdispatch.dylib)
 20  0x00007fff92bb0a9d _pthread_wqthread (in libsystem_pthread.dylib)
 21  0x00007fff92bae3dd start_wqthread (in libsystem_pthread.dylib)
```

Same as #47539.

**Comment by DomT4** [comment]
Ugh, sorry about that. I'll try and take a look tonight or tomorrow morning and push this build through CI again afterwards.

**Comment by DomT4** [comment]
Waiting for the CI queue to ease up so I can pause it and go poke the boxes with a stick. Should hopefully be done in the next few hours; apologies for the delay here.

**Comment by jpsim** [comment]
No worries about the delay, I appreciate you looking into this!

By the way, simulator issues like these are common enough to have several commonly used workarounds, which you may be interested in applying:

* [Realm's `reset-simulators.sh`](https://github.com/realm/realm-cocoa/blob/master/scripts/reset-simulators.sh)
* [Fastlane's `reset_simulators` command](https://github.com/fastlane/snapshot#completely-reset-all-simulators)

I'm sure there are others...

**Comment by DomT4** [comment]
@BrewTestBot test this please

**Comment by apjanke** [comment]
test bot looks happy this time.

Merged. Thank you for your contribution to Homebrew!

**Pull request closed without merging**
