### PR TITLE
graphicsmagick 1.3.21

### PR DESCRIPTION
**Pull request by longlho**
New version of graphicsmagick just came out 02/28

### CODE REVIEW

**Comment by chdiza** [comment]
I see the following in the tarball's `NEWS.txt`:
```
  * Magick++: Any libraries or applications using Magick++ should be
    rebuilt in order to use this new release.  Libraries and
    applications will be able to continue to use prior versions of
    Magick++ without being re-built, while benefiting from updated C
    libraries, provided that the system supports library versioning.
```

I also see that `brew uses graphicsmagick` says `dgtal` and `xastir` both depend_on graphicsmagick, though only in `xastir`'s case is it a required dep.

Does this mean that one or both of those formulas need a revision bump to force rebrewing?  I honestly don't know.  E.g., I don't know whether `xastir` uses "Magick++".

**Comment by longlho** [comment]
Hmm got it! What do you think would be the recommended solution for this? `1.3.21` has these:
```
 * Magick++ Geometry: New methods limitPixels() and fillArea() to
    support '@' and '^' geometry qualifiers.  This enancement breaks
    the ABI due to previous use of inline methods and no place to put
    the new flags.

  * Magick++ Image::extent(): New method to place image on sized
    canvas of constant color using gravity.

  * Magick++ Image::formatExpression(): New method format a string
    based on a format similar to command-line -format.

  * Magick++ Image::resize(): New method to resize image specifying
    geometry, filter, and blur.

  * Magick++ STL extentImage: New New function object to invoke image
    extent method.
```
which are the new driver methods I was looking to use. Let me know how I can assist!

**Comment by chdiza** [comment]
I know almost nothing about graphicsmagick.  I only occasionally use it for basic conversion.  I don't even know what Magick++ is, still less whether `dgtal` and `xastir` use it.  But *if* they do, the graphicsmagick formula *might* need a revision bump.

I only brought this up so that someone who knows more about this can weigh in.

**Comment by longlho** [comment]
`1.3.21` does change `Magick++` (the GM C++ driver) interface (ABI) but it's not backwards-incompatible. Plus it's a patch version also. Yeah if someone maybe can vet this decision? I personally think it should be fine.

**Comment by tdsmith** [comment]
dgtal can use Magick++ and should be revisioned; xastir is a C project. Thanks for catching that note, @chdiza. We're migrating dgtal to homebrew/science eventually; maybe we should land the revision first.

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
