### PR TITLE
radare2: Fix Python install path

### PR DESCRIPTION
**Pull request by dholm**
By default the Makefile attempts to construct an installation path for
the Python bindings that is based on the Python version in Homebrew
instead of using the generic version "2.7".

### CODE REVIEW

**Comment by DomT4** [comment]
```
 * python modules have explicit framework links
These python extension modules were linked directly to a Python
framework binary. They should be linked with -undefined dynamic_lookup
instead of -lpython or -framework Python.
  /usr/local/Cellar/radare2/0.9.9_1/lib/python2.7/site-packages/r2/_r_asm.so
  /usr/local/Cellar/radare2/0.9.9_1/lib/python2.7/site-packages/r2/_r_bin.so
  /usr/local/Cellar/radare2/0.9.9_1/lib/python2.7/site-packages/r2/_r_core.so
```

**Comment by dholm** [comment]
@DomT4 Fixed!

**Comment by dunn** [comment]
Sorry for the delay. Are some of these `inreplace`s issues that could be fixed in the Makefile and patched upstream?

**Comment by dholm** [comment]
@dunn Yes, but I'm not sure why `CFLAGS=-undefined dynamic_lookup` is needed, it was Homebrew audit that suggested it, so I'm not sure how to explain that to upstream.

**Comment by DomT4** [comment]
Apologies for the delay here. I'd been meaning to bat my eyelashes at @tdsmith and ask for a review of the python tweaks.

**Comment by tdsmith** [comment]
No complaints.

**Comment by bfontaine** [comment]
This PR needs to be rebased on top of `master`.

**Comment by bfontaine** [comment]
Ping?

**Comment by DomT4** [comment]
Closing as dead. Please feel free to resubmit rebased if desired. Thank for your submission to Homebrew!

**Pull request closed without merging**
