### PR TITLE
planck 1.4

### PR DESCRIPTION
**Pull request by mfikes**
Update to 1.4; allow Mavericks

### CODE REVIEW

**Comment by mfikes** [comment]
I botched the hash (forgot `-L` when doing `curl`). Will fix and resubmit.

**Comment by mfikes** [comment]
Looks like the tests passed, but the overall indicator here is fail.

**Comment by dunn** [comment]
Our Mountain Lion bot is acting up; once we sort it out I'll re-run the tests.

**Comment by dunn** [comment]
Thanks for waiting! Merged in b5006fac627dba636411caa9eb4918fc822f08f5.

**Pull request closed without merging**
