### PR TITLE
bind: use https homepage

### PR DESCRIPTION
**Pull request by vszakats**

### CODE REVIEW

**Comment by mikemcquaid** [comment]
@vszakats Perhaps a strange suggestion but: is there any chance you could watch this repo? It'd be helpful if you could suggest these changes on PRs as they come in rather than needing to be rebuilt each time. Thanks!

**Comment by vszakats** [comment]
I can make a try and see how much the load is that way, though the current "pull" style seems easier to fit into occasional spots of free time near a computer. I've made an attempt recently to scan open PRs and left a batch of suggestions, but got just a low amount of follow-up.

I keep wondering if it'd be possible to automatize this at least to an extent at the audit stage. For `url`/`mirror` it often just means replacing `^http:` with `^https:` and verifying if it returns the same file as before.

**Comment by mikemcquaid** [comment]
I guess I'm just wondering also what we're trying to achieve with making all these links https? I'm OK with audit rules being added but at some point I think it's worth stopping making dedicated changes just for URLs/homepages (and I'm wondering if that time is now).

**Comment by vszakats** [comment]
My last impression was that this issue is important to this project, but if it isn't it won't cost me anything to stop it right now.

**Comment by mikemcquaid** [comment]
@vszakats I think it's useful for the bigger packages but I think it does have diminishing returns. The problem is that our CI infrastructure (which is currently experiencing other issues) is not well equipped to test things like this that don't actually result in any e.g. code changes.

**Comment by vszakats** [comment]
It's not trivial to tell what a bigger package is. Anyhow the best would be to automate as much as possible and catch the rest in PR review stage.

**Comment by mikemcquaid** [comment]
Sorry, I mean more popular packages.

**Pull request closed without merging**
