### PR TITLE
libgit2 0.23.0

### PR DESCRIPTION
**Pull request by tkelman**
(not locally tested, ~~relying on your buildbots~~)

### CODE REVIEW

**Comment by mikemcquaid** [comment]
> (not locally tested, relying on your buildbots)

Please test things locally, thanks.

**Comment by tkelman** [comment]
would if I could, don't own a mac

**Comment by tkelman** [comment]
I take that back, I can test, sort of. Thanks, Travis: https://travis-ci.org/tkelman/homebrew/builds/70413319

**Comment by DomT4** [comment]
`libgit2-glib` failed on testing. Probably needs a revision if there isn't a version bump available.

**Comment by tkelman** [comment]
Thanks, I don't see a newer tag than 0.22.8 yet at https://github.com/GNOME/libgit2-glib/releases. It looks like adding `revision 1` to libgit2-glib would cause a build failure against latest libgit2 (https://travis-ci.org/tkelman/homebrew/builds/70429110), so will this have to wait until libgit2-glib puts out a new release?

**Comment by DomT4** [comment]
Yup, looks like it. They're usually fairly in-sync.

**Pull request closed without merging**
