### PR TITLE
add wren scripting language.

### PR DESCRIPTION
**Pull request by paxos1977**
Wren is a scripting language made to be embedded, similar to Lua. https://munificent.github.io/wren/index.html 
This is my first attempt at creating a brew formula, so any pointers are appreciated.

### CODE REVIEW

**Comment by mistydemeo** [comment]
Thank you very much for the submission!

Where did you get the version number from? Has this software had a release yet?

**Comment by paxos1977** [comment]
@mistydemeo as there hasn't been an actual release yet... I'm afraid I made up the version number. What is the appropriate way to handle that?

**Comment by mistydemeo** [comment]
We don't accept software without an official release in this repository, sorry! You can however submit to [homebrew-headonly](https://github.com/Homebrew/homebrew-headonly/), which accepts software with only a "head" spec, indicating that the only way to install is from the latest commit in the specified VCS repository.

**Comment by mistydemeo** [comment]
Closing here since there isn't a stable release, but please feel free to submit to that repository. Thank you!

**Pull request closed without merging**
