### PR TITLE
Request to add formula: io.js 1.0.0

### PR DESCRIPTION
**Pull request by smockle**
[io.js](https://github.com/iojs/io.js) is an [npm](https://www.npmjs.org/) compatible platform originally based on [node.js](https://nodejs.org/)™. This formula is needed to ease installation of io.js, so that more people can build things.

### CODE REVIEW

**Comment by DomT4** [comment]
Please see my comment in #35853.

**Comment by smockle** [comment]
@DomT4 Thanks for the feedback!

**Comment by DomT4** [comment]
@smockle No worries. :heart: for the ` iojs ` project and team, I just want to tread carefully here to avoid breaking absolutely everything, heh. The Node ecosystem is a little temperamental alas.

**Comment by smockle** [comment]
Closing this pull request, to focus on work in https://github.com/Homebrew/homebrew/pull/35853.

**Pull request closed without merging**
