### PR TITLE
Update to Maven 3.3.9

### PR DESCRIPTION
**Pull request by dadoonet**
I also changed `mirror` as it gives for now a `404` error but it's may be only because it takes some time to sync?

### CODE REVIEW

**Comment by DomT4** [comment]
Apologies, I merged #46113 because I'm working from newest to oldest through open PRs rather than vice versa. Will try to double check next time; we have a policy of trying to merge whoever filed the PR first. Thank you for the submission to Homebrew nonetheless @dadoonet.

**Comment by dadoonet** [comment]
The funny thing is that @jasontedor and me are working in the same team :p

**Comment by DomT4** [comment]
You should probably feel feel to berate him for ignoring a team-mate then :wink:

**Comment by jasontedor** [comment]
Apologies @dadoonet, I did not see this.

@DomT4 Out of curiosity, I was under the impression from #25962 that `brew search maven` would me tell if there was an open pull request for the Maven formula. I ran that this morning before opening #46113 and it didn't show any open pull requests?

**Comment by DomT4** [comment]
> Out of curiosity, I was under the impression from #25962 that brew search maven would me tell if there was an open pull request for the Maven formula. 

It seems to only do so if `brew search` doesn't already return a result:

```
~> brew search getdns
getdns
```

```
~> brew search getdns1
No formula found for "getdns1".
==> Searching pull requests...
```

**Comment by jasontedor** [comment]
> It seems to only do so if brew search doesn't already return a result

Thanks. I will keep that in mind in the future.

**Pull request closed without merging**
