### PR TITLE
pcre1: add alias for pcre

### PR DESCRIPTION
**Pull request by vszakats**
`pcre1` is the new canonical name after the release of `pcre2`.

### CODE REVIEW

**Comment by dunn** [comment]
I don't think aliases need the `.rb` extension.

**Comment by vszakats** [comment]
Corrected, apologize (it's my first).

**Comment by tdsmith** [comment]
This should be a symlink, not a literal file. Do you have a reference for this? If you could squash it to a single commit that'd be great.

**Comment by vszakats** [comment]
I was hoping it is not a symlink. I'll redo this outside the GitHub web UI.

**Comment by vszakats** [comment]
Redone in https://github.com/Homebrew/homebrew/issues/39399

**Pull request closed without merging**
