### PR TITLE
clang-format 2015-04-02

### PR DESCRIPTION
**Pull request by mprobst**

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Fails on 10.8: http://bot.brew.sh/job/Homebrew%20Pull%20Requests/23654/version=mountain_lion/testReport/junit/brew-test-bot/mountain_lion/install_clang_format/

Will need to coax it to use the right compiler somehow.

**Comment by mprobst** [comment]
PTAL.

I changed this to not use GCC to build (but rather clang), and use the supplied `libcxx`, which had kept us from using clang before. That simplifies the build a bit and seems to have fixed the mountain_lion issue.

**Comment by mprobst** [comment]
This is not ready to merge - there's a messup in the upstream library with the version tags. Please stand by while I sort that out.

**Comment by mprobst** [comment]
This should be ready to merge now, sorry about the confusion.

**Comment by tdsmith** [comment]
Cool! Thanks for the pull request! 🎉

**Pull request closed without merging**
