### PR TITLE
tomcat 8.0.24

### PR DESCRIPTION
**Pull request by nijikon**

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Merged in 8b772b7.

**Comment by nijikon** [comment]
@mikemcquaid is there a way to search from the command line for a pr?

**Comment by mikemcquaid** [comment]
@nijikon Could probably use `hub` or write a script to use the GitHub API?

**Comment by nijikon** [comment]
Write a separate script or we could extend ```search``` command?

**Comment by mikemcquaid** [comment]
Could be added to search; show the results like we do on build failures.

**Comment by nijikon** [comment]
Exactly. I will create a pr. Thanks!

**Pull request closed without merging**
