### PR TITLE
mariadb 10.0.17

### PR DESCRIPTION
**Pull request by makigumo**

### CODE REVIEW

**Comment by tdsmith** [comment]
devel version is failing on Mountain Lion: http://bot.brew.sh/job/Homebrew%20Pull%20Requests/22051/version=mountain_lion/testReport/junit/brew-test-bot/mountain_lion/install___devel_mariadb/

Do you know what the `wsrep_sst_common` the devel version installs to prefix/bin is, and if it should be there or be executable? It's causing an audit failure: http://bot.brew.sh/job/Homebrew%20Pull%20Requests/22051/version=mavericks/testReport/junit/brew-test-bot/mavericks/audit___devel_mariadb/

**Comment by makigumo** [comment]
Thank you for your feedback. The audit failure is harmless as the file in question is sourced from the other ```wsrep_sst_*``` scripts (see #34788). Which will otherwise break. The compilation error seems to be stemming from the TokuDB plugin, which, last I heard, isn't currently supported on Mac, so I will disable it and will see what happens ;)

**Comment by mikemcquaid** [comment]
We should still try and move those scripts elsewhere to avoid the audit failure.

**Comment by makigumo** [comment]
To followup on this. All seems fine after the latest change, although there was a spurious segmentation fault with clang in mavericks after 9af81f5. I moved the offending file to libexec and replaced the references. Maybe someone can have as look if this is a feasible approach or something other is more idiomatic. Thanks.

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
