### PR TITLE
Bump vala version to 0.27

### PR DESCRIPTION
**Pull request by Tyilo**
I don't know how to handle the outdated bottles.

### CODE REVIEW

**Comment by Tyilo** [comment]
I would also like to add support for building for head, however vala head depends on a non-head vala.
Is that possible to specify with homebrew?

**Comment by DomT4** [comment]
Is 0.27 stable? GNOME usually roll with even = stable, odd = dev. Maybe doesn't apply for 0.x versions though.

> I don't know how to handle the outdated bottles.

The block can be ignored :). The bot generates new bottles automatically, and the maintainers pull those when PRs are merged.

> Is that possible to specify with homebrew?

It's not completely impossible, but a bit of a pain. Hombrew came close to something like this with ` PyPy ` recently but it didn't happen. Basically, you'd have to use a pre-generated binary and stick it in the buildpath temporarily, either from one of HB's bottles or an upstream generated binary that could be curled as a resource. You'd have to poll the maintainers though on how they feel about the build x with an already functional x arrangement.

**Comment by jacknagel** [comment]
It's a development release, and we package the stable releases.

It could be added as a `--devel` install if it's useful.

**Comment by Tyilo** [comment]
>It's a development release, and we package the stable releases.

Do you have a source for that? [Wikipedia says](https://en.wikipedia.org/wiki/Vala_%28programming_language%29) that 0.27.1 is a stable version.

**Comment by jacknagel** [comment]
My source is that every gnome project follows this versioning scheme ;)

**Comment by DomT4** [comment]
I wouldn't trust Wikipedia to necessary grasp the nuances of GNOME versioning to be honest :wink:

**Comment by Tyilo** [comment]
Added it as devel instead of stable.

**Comment by mikemcquaid** [comment]
Change the homepage to be HTTPS, thanks! http://bot.brew.sh/job/Homebrew%20Pull%20Requests/20238/version=yosemite/testReport/junit/brew-test-bot/yosemite/audit_vala/

**Comment by Tyilo** [comment]
It only works over HTTP:

```
$ curl -O https://ftp.gnome.org/pub/GNOME/sources/vala/0.27/vala-0.27.1.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  curl: (7) Failed to connect to ftp.gnome.org port 443: Connection refused
```

**Comment by jacknagel** [comment]
The homepage, not the download URL.

**Comment by Tyilo** [comment]
Ok

**Pull request closed without merging**
