### PR TITLE
pcre 8.38

### PR DESCRIPTION
**Pull request by vszakats**

### CODE REVIEW

**Comment by dunn** [comment]
Test getting blocked by the sandbox; not sure why El Cap isn't: http://bot.brew.sh/job/Homebrew%20Pull%20Requests/37366/#showFailuresLink

**Comment by vszakats** [comment]
Even worse, it's a test of a dependency. This `pcre` update is a purely bugfix release (there won't be any more non-bugfix releases for the `8.*` series), so it's not supposed to create much build trouble in itself.

**Comment by mikemcquaid** [comment]
Thanks @vszakats!

**Comment by mikemcquaid** [comment]
@dunn It'll be that El Cap doesn't have a bottle for that reverse dep so doesn't run the test.

**Pull request closed without merging**
