### PR TITLE
Fix for issue #41740

### PR DESCRIPTION
**Pull request by mtpereira**
Updated SHA256 sum for VENOM patch file on qemu recipe. This fixes issue #41740.

### CODE REVIEW

**Comment by dunn** [comment]
Will this happen again, though? Maybe we should host our own gist.

**Comment by mtpereira** [comment]
You're absolutely right! How does this look? https://gist.githubusercontent.com/mtpereira/77dd144343bf24552aad/raw/0f22e76e50013f40a4c4d6dee1a6ec2a1ffea18b/qemu-venom.patch

**Comment by dunn** [comment]
Looks good to me!

**Comment by mtpereira** [comment]
Ok, just pushed that change.

**Comment by dunn** [comment]
And merged in 62030edb65966f9097d2a9b98b60e594e4e82379. Thanks for fixing this!

**Pull request closed without merging**
