### PR TITLE
Watchman 3.8.0

### PR DESCRIPTION
**Pull request by wez**
Tested via:

```
brew install watchman
brew audit watchman
brew test watchman
```

### CODE REVIEW

**Comment by wez** [comment]
Any idea what happened on the mountain lion run?

**Comment by mikemcquaid** [comment]
@BrewTestBot test this please

**Comment by mikemcquaid** [comment]
@wez Sorry, we've been having some CI issues. I'm rerunning this

**Comment by DomT4** [comment]
It's trying to break out of the sandbox we now run on our CI. Can you take a look at this, Thanks!

```
==> /usr/local/Cellar/watchman/3.8.0/bin/watchman shutdown-server
2015-09-18T14:46:29,537: [1939804928] failed to create /usr/local/Cellar/watchman/3.8.0/var/run/watchman/brew-state: Operation not permitted
Error: watchman: failed
Failed executing: /usr/local/Cellar/watchman/3.8.0/bin/watchman shutdown-server
```

**Comment by wez** [comment]
How does the sandbox work?  Watchman launches itself via launchd.  If we can't use that in the sandbox, we'll have to remove the test portion of the formula.  I'm fine with that; we have CI that runs our integration tests on multiple platforms before we deem a revision good enough to push downstream from us.

**Comment by DomT4** [comment]
It uses OS X's sandbox utility to ensure no process inside `test do` can *write* outside of the `testpath`. In this case it's trying to write a file outside of the `testpath` and being denied permission to do so. It fails earlier if the `plist` isn't already installed.

As you explain `watchman` creates the `plist` at runtime, which ties our hands here a bit. For various reasons I don't particularly want to set the precedent of allowing our `test do` blocks to write permanent `plists` on the system and set them running.

**Comment by DomT4** [comment]
We may have to scale the test back here a bit, I guess. I'd like to keep something around, even a version check if necessary.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/86acff193799fca66c2f5ffc80195cab29fc9e15. Thank you @wez!

**Pull request closed without merging**
