### PR TITLE
qt: fix a build issue and some improvements

### LINKED ISSUE #46974: pyqt issue on Yosemite with no outdated packages installed
Wanted to muck around with the Electrum Package, which has brew dependencies upon python pyqt, and ran into the issue documented below with pyqt. 

Trouble shot this issue as much as without digging into the bowels. [Per](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/External-Commands.md) been successful at building or deploying brew managed packages for over a year.  

             setenv HOMEBREW_PREFIX       ~/usr/local
             setenv HOMEBREW_REPOSITORY   ~/usr/local/Homebrew
             setenv HOMEBREW_CELLAR       ~/usr/local/Homebrew/Cellar
             setenv HOMEBREW_LIBRARY_PATH ~/usr/local/Homebrew/Library/Homebrew
             setenv HOMEBREW_CACHE        ~/usr/local/cache
 
After [following](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting) I took the additional step of git cloning the today's Homebrew package and reset the variables above to point to a /usr2 directory with the same structure.

Here are a set of background results that may assist with trouble shooting:

```
% uname -a
```
```
Darwin bozo 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64
```
```
% xcode-select --version
```
```
xcode-select version 2339.
```

```
% brew doctor
```
```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Your Homebrew is not installed to /usr/local
You can install Homebrew anywhere you want, but some brews may only build
correctly if you install in /usr/local. Sorry!
```
```
% ./brew update
```
```
Already up-to-date.
```
```
% brew list
```
```
autoconf	cloog		curl		gmp		isl		makedepend	pkg-config	readline	wget		xz
automake	cmake		gdbm		gnupg		libtool		openssl		python		sqlite		xmltoman
```
```
% brew outdated 
```
```
RETURNS NOTHING:-)
```
```
% brew install pyqt
```
```
==> Installing dependencies for pyqt: qt, sip
==> Installing pyqt dependency: qt
==> Downloading https://download.qt.io/official_releases/qt/4.8/4.8.7/qt-everywhere-opensource-src-4.8.7.tar.gz
==> Downloading from http://anychimirror101.mirrors.tds.net/pub/Qt/official_releases/qt/4.8/4.8.7/qt-everywhere-opensource-src-4.8.7.tar.gz
######################################################################## 100.0%
==> ./configure -prefix /Users/Scott/usr2/local/homebrew/Cellar/qt/4.8.7_1 -system-zlib -qt-libtiff -qt-libpng -qt-libjpeg -confirm-license -opensource -nomake demos -nomake ex
==> make
Last 15 lines from /Users/Scott/Library/Logs/Homebrew/qt/02.make:
clang++ -c -pipe -stdlib=libc++ -mmacosx-version-min=10.7 -I/Users/Scott/usr2/local/opt/openssl/include -O2 -arch x86_64 -fvisibility=hidden -fvisibility-inlines-hidden -Wall -W -fPIC -DQT_SHARED -DQT_BUILD_GUI_LIB -DQT_NO_USING_NAMESPACE -DQT_NO_CAST_TO_ASCII -DQT_ASCII_CAST_WARNINGS -DQT_MOC_COMPAT -DQT_USE_QSTRINGBUILDER -DQT_USE_BUNDLED_LIBPNG -DPNG_ARM_NEON_OPT=0 -DQT_NO_CUPS -DQT_NO_LPR -DQT_NO_OPENTYPE -DQT_NO_STYLE_WINDOWSVISTA -DQT_NO_STYLE_WINDOWSXP -DQT_NO_STYLE_GTK -DQT_NO_STYLE_WINDOWSCE -DQT_NO_STYLE_WINDOWSMOBILE -DQT_NO_STYLE_S60 -DQ_INTERNAL_QAPP_SRC -DQT_NO_DEBUG -DQT_CORE_LIB -DQT_HAVE_MMX -DQT_HAVE_3DNOW -DQT_HAVE_SSE -DQT_HAVE_MMXEXT -DQT_HAVE_SSE2 -DQT_HAVE_SSE3 -DQT_HAVE_SSSE3 -DQT_HAVE_SSE4_1 -DQT_HAVE_SSE4_2 -DQT_HAVE_AVX -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -I../../mkspecs/unsupported/macx-clang-libc++ -I. -I../../include/QtCore -I../../include -I../../include/QtGui -I.rcc/release-shared -Iimage -I../3rdparty/libpng -I../3rdparty/harfbuzz/src -Idialogs -I.moc/release-shared -I.uic/release-shared -F/private/tmp/qt20151213-15380-nlieo4/qt-everywhere-opensource-src-4.8.7/lib -o .obj/release-shared/qfont.o text/qfont.cpp
clang++ -c -pipe -stdlib=libc++ -mmacosx-version-min=10.7 -I/Users/Scott/usr2/local/opt/openssl/include -O2 -arch x86_64 -fvisibility=hidden -fvisibility-inlines-hidden -Wall -W -fPIC -DQT_SHARED -DQT_BUILD_GUI_LIB -DQT_NO_USING_NAMESPACE -DQT_NO_CAST_TO_ASCII -DQT_ASCII_CAST_WARNINGS -DQT_MOC_COMPAT -DQT_USE_QSTRINGBUILDER -DQT_USE_BUNDLED_LIBPNG -DPNG_ARM_NEON_OPT=0 -DQT_NO_CUPS -DQT_NO_LPR -DQT_NO_OPENTYPE -DQT_NO_STYLE_WINDOWSVISTA -DQT_NO_STYLE_WINDOWSXP -DQT_NO_STYLE_GTK -DQT_NO_STYLE_WINDOWSCE -DQT_NO_STYLE_WINDOWSMOBILE -DQT_NO_STYLE_S60 -DQ_INTERNAL_QAPP_SRC -DQT_NO_DEBUG -DQT_CORE_LIB -DQT_HAVE_MMX -DQT_HAVE_3DNOW -DQT_HAVE_SSE -DQT_HAVE_MMXEXT -DQT_HAVE_SSE2 -DQT_HAVE_SSE3 -DQT_HAVE_SSSE3 -DQT_HAVE_SSE4_1 -DQT_HAVE_SSE4_2 -DQT_HAVE_AVX -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -I../../mkspecs/unsupported/macx-clang-libc++ -I. -I../../include/QtCore -I../../include -I../../include/QtGui -I.rcc/release-shared -Iimage -I../3rdparty/libpng -I../3rdparty/harfbuzz/src -Idialogs -I.moc/release-shared -I.uic/release-shared -F/private/tmp/qt20151213-15380-nlieo4/qt-everywhere-opensource-src-4.8.7/lib -o .obj/release-shared/qfontengine.o text/qfontengine.cpp
clang++ -c -pipe -stdlib=libc++ -mmacosx-version-min=10.7 -I/Users/Scott/usr2/local/opt/openssl/include -O2 -arch x86_64 -fvisibility=hidden -fvisibility-inlines-hidden -Wall -W -fPIC -DQT_SHARED -DQT_BUILD_GUI_LIB -DQT_NO_USING_NAMESPACE -DQT_NO_CAST_TO_ASCII -DQT_ASCII_CAST_WARNINGS -DQT_MOC_COMPAT -DQT_USE_QSTRINGBUILDER -DQT_USE_BUNDLED_LIBPNG -DPNG_ARM_NEON_OPT=0 -DQT_NO_CUPS -DQT_NO_LPR -DQT_NO_OPENTYPE -DQT_NO_STYLE_WINDOWSVISTA -DQT_NO_STYLE_WINDOWSXP -DQT_NO_STYLE_GTK -DQT_NO_STYLE_WINDOWSCE -DQT_NO_STYLE_WINDOWSMOBILE -DQT_NO_STYLE_S60 -DQ_INTERNAL_QAPP_SRC -DQT_NO_DEBUG -DQT_CORE_LIB -DQT_HAVE_MMX -DQT_HAVE_3DNOW -DQT_HAVE_SSE -DQT_HAVE_MMXEXT -DQT_HAVE_SSE2 -DQT_HAVE_SSE3 -DQT_HAVE_SSSE3 -DQT_HAVE_SSE4_1 -DQT_HAVE_SSE4_2 -DQT_HAVE_AVX -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -I../../mkspecs/unsupported/macx-clang-libc++ -I. -I../../include/QtCore -I../../include -I../../include/QtGui -I.rcc/release-shared -Iimage -I../3rdparty/libpng -I../3rdparty/harfbuzz/src -Idialogs -I.moc/release-shared -I.uic/release-shared -F/private/tmp/qt20151213-15380-nlieo4/qt-everywhere-opensource-src-4.8.7/lib -o .obj/release-shared/qfontsubset.o text/qfontsubset.cpp
clang++ -c -pipe -stdlib=libc++ -mmacosx-version-min=10.7 -I/Users/Scott/usr2/local/opt/openssl/include -O2 -arch x86_64 -fvisibility=hidden -fvisibility-inlines-hidden -Wall -W -fPIC -DQT_SHARED -DQT_BUILD_GUI_LIB -DQT_NO_USING_NAMESPACE -DQT_NO_CAST_TO_ASCII -DQT_ASCII_CAST_WARNINGS -DQT_MOC_COMPAT -DQT_USE_QSTRINGBUILDER -DQT_USE_BUNDLED_LIBPNG -DPNG_ARM_NEON_OPT=0 -DQT_NO_CUPS -DQT_NO_LPR -DQT_NO_OPENTYPE -DQT_NO_STYLE_WINDOWSVISTA -DQT_NO_STYLE_WINDOWSXP -DQT_NO_STYLE_GTK -DQT_NO_STYLE_WINDOWSCE -DQT_NO_STYLE_WINDOWSMOBILE -DQT_NO_STYLE_S60 -DQ_INTERNAL_QAPP_SRC -DQT_NO_DEBUG -DQT_CORE_LIB -DQT_HAVE_MMX -DQT_HAVE_3DNOW -DQT_HAVE_SSE -DQT_HAVE_MMXEXT -DQT_HAVE_SSE2 -DQT_HAVE_SSE3 -DQT_HAVE_SSSE3 -DQT_HAVE_SSE4_1 -DQT_HAVE_SSE4_2 -DQT_HAVE_AVX -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -I../../mkspecs/unsupported/macx-clang-libc++ -I. -I../../include/QtCore -I../../include -I../../include/QtGui -I.rcc/release-shared -Iimage -I../3rdparty/libpng -I../3rdparty/harfbuzz/src -Idialogs -I.moc/release-shared -I.uic/release-shared -F/private/tmp/qt20151213-15380-nlieo4/qt-everywhere-opensource-src-4.8.7/lib -o .obj/release-shared/qfontmetrics.o text/qfontmetrics.cpp
painting/qpaintengine_mac.cpp:345:19: error: use of undeclared identifier 'CMGetProfileByAVID'
    CMError err = CMGetProfileByAVID((CMDisplayIDType)displayID, &displayProfile);
                  ^
painting/qpaintengine_mac.cpp:348:9: error: use of undeclared identifier 'CMCloseProfile'
        CMCloseProfile(displayProfile);
        ^
2 errors generated.
make[2]: *** [.obj/release-shared/qpaintengine_mac.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [release] Error 2
make: *** [sub-gui-make_default-ordered] Error 2

READ THIS: https://git.io/brew-troubleshooting
```

### PR DESCRIPTION
**Pull request by UniqMartin**
The primary motivation is to fix #46974 (last commit), but I added a few not very controversial changes that are already in effect for the `qt5` formula. Neither a formula revision bump nor a bottle update should be needed, as the changes only affect users building from source or with non-standard options.

### CODE REVIEW

**Comment by DomT4** [comment]
Is a revision necessary to fix existing Qt installs on 10.10? That question otherwise, :+1:

**Comment by UniqMartin** [comment]
> Is a revision necessary to fix existing Qt installs on 10.10?

No, that's not necessary. The patch removes references to two functions that have been removed from the 10.11 SDK, because they have been deprecated in/after 10.6. But they are still available in the corresponding framework, even in 10.11, so the existing installs are not broken.

The only real reason for revision bumping and rebottling would be that we really want the `qt` builds to match across different OS X versions and to be consistent with the build recipe in the formula.

**Comment by DomT4** [comment]
Cool. Don't think the equal build issue is necessarily important enough to force a general rebuild on everyone given `qt` is kind of beefy to build, personally. Probably a good idea to pull new bottles, but otherwise.

**Comment by UniqMartin** [comment]
Thanks for chiming in! I agree with you and will pull new bottles once this PR is good to go.

As this PR isn't particularly urgent, I'll wait until the two formulae that are responsible for the test failures are fixed. (First one addressed in #47086. Second one depends on first, thus not submitted yet.)

**Comment by UniqMartin** [comment]
@DomT4 I believe this is ready to be merged to make the build fix available to the general public. Any objections? (I think a possible relocation of the plugin path, such that it can be extended by other formulae like `qscintilla2`, is worth a separate PR – and probably need some discussion.)

**Comment by DomT4** [comment]
Yeah, agree on the plugin issue. Feel free to :shipit:.

**Pull request closed without merging**
