### PR TITLE
ipfs 0.3.11

### PR DESCRIPTION
**Pull request by eelcocramer**

### CODE REVIEW

**Comment by eelcocramer** [comment]
This release is already tagged on the ipfs repo but not yet released as binary on their website. Lets wait for that...

**Comment by dignifiedquire** [comment]
The release is out http://dist.ipfs.io/#go-ipfs

**Comment by DomT4** [comment]
This release was merged by, er, me apparently a couple weeks back: https://github.com/Homebrew/homebrew/commit/2dd1c6052da3fa15b9c5ef079cc3107ad7497bca. Because this had been closed I missed it.

**Comment by eelcocramer** [comment]
Yeah, I've checked if it is formula ok and it is. The ipfs guys tagged the the 0.3.11 release a couple of weeks ago but just released it yesterday. They did not move the tag so the hash in the Formula is good to go.

**Pull request closed without merging**
