### PR TITLE
geos 3.5.0

### PR DESCRIPTION
**Pull request by nijikon**

### CODE REVIEW

**Comment by dunn** [comment]
Needs rebasing after some GDAL changes; thanks!

**Comment by gfairchild** [comment]
What exactly is preventing this from being merged?

**Comment by DomT4** [comment]
It needs rebasing against the master; there be merge conflicts at the moment.

**Comment by gfairchild** [comment]
I just rebased and submitted a PR to the @nijikon's repo, so hopefully he'll accept it so that this can be merged.

**Comment by gfairchild** [comment]
Ok, if @nijikon accepts https://github.com/polishgeeks/homebrew/pull/2, then we should be good to go....

**Comment by DomT4** [comment]
Will close in favour of https://github.com/Homebrew/homebrew/pull/46295. Thanks for the submission @nijikon!

**Pull request closed without merging**
