### PR TITLE
formula: delete git-encrypt

### PR DESCRIPTION
**Pull request by maletor**
This package is deprecated and no longer used.

### CODE REVIEW

**Comment by DomT4** [comment]
Should be "migrated" to Homebrew/boneyard, rather than deleted outright. See https://github.com/Homebrew/homebrew/pull/46489/files for an example.

**Comment by maletor** [comment]
@DomT4, updated and [added related pull request](https://github.com/Homebrew/homebrew-boneyard/pull/79).

**Comment by bfontaine** [comment]
I don’t think we should remove it from the core if it still builds. The boneyard is for formulae that don’t build anymore.

**Comment by DomT4** [comment]
Normally I'd agree, but the author force pushed over the source code and added a note to the README that essentially hints it may not be secure:

> Please consider using AGWA/git-crypt instead. AGWA's tool has a proven security and is much better than this tool.

**Comment by maletor** [comment]
Right, this tool is insecure and unsupported by most other package managers.

**Comment by bfontaine** [comment]
Thanks; it makes sense.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/74dbae0ec95d756ec78c1f1fae852e95317eb6af. Thank you for your contribution to Homebrew @maletor; we appreciate it! :smiley_cat:

**Pull request closed without merging**
