### PR TITLE
opensc 0.15.0

### PR DESCRIPTION
**Pull request by nijikon**

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Failing on 10.8: http://bot.brew.sh/job/Homebrew%20Pull%20Requests/27921/version=mountain_lion/testReport/junit/brew-test-bot/mountain_lion/install_opensc/

**Comment by nijikon** [comment]
@mikemcquaid is there a way to reproduce environment for 10.8 that brew bot is building on?

**Comment by mikemcquaid** [comment]
@nijikon Without 10.8: not really. Might need a `fails_with :clang` line for 10.8's compiler (you can see that through http://bot.brew.sh/job/Homebrew%20Pull%20Requests/27921/version=mountain_lion/testReport/brew-test-bot/mountain_lion/config/).

**Comment by nijikon** [comment]
@mikemcquaid how does brew bot build on 10.8, virtualbox image?

**Comment by mikemcquaid** [comment]
VMware Fusion, yep.

**Comment by nijikon** [comment]
Can I obtain that images? It would be easier if I could reproduce it locally.

**Comment by mikemcquaid** [comment]
Sadly not; we can't redistribute them for both legal reasons and because they contain potentially sensitive credentials.

**Comment by nijikon** [comment]
@mikemcquaid Ok, will figure out something, thanks.

**Comment by carlhoerberg** [comment]
Was a bug in opensc, but one solution is: https://github.com/OpenSC/OpenSC/pull/485

**Comment by nijikon** [comment]
@carlhoerberg still breaks with the patch

**Comment by nijikon** [comment]
@DomT4 @mikemcquaid any clue what can be wrong here? I can compile it locally without issues.

**Comment by dunn** [comment]
Try adding `depends_on "pkg-config" => :build`.

**Comment by nijikon** [comment]
Finally :dancer: Please merge, thank you :)

**Comment by mikemcquaid** [comment]
Thanks @nijikon!

**Pull request closed without merging**
