### PR TITLE
bottle: revision is digits rather than string in the merge regex

### PR DESCRIPTION
**Pull request by xu-cheng**

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Oh great, this has been bugging me for a while :+1:

**Comment by xu-cheng** [comment]
:smile_cat:

**Comment by xu-cheng** [comment]
@mikemcquaid Why I get the feeling I haven't fix all the problem. What will happen if there is a `stable do end` block?

**Comment by xu-cheng** [comment]
It seems I am right. Look at [this formula](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/unittest-cpp.rb)

**Comment by mikemcquaid** [comment]
> IMHO, this problem cannot be properly parsed by regular expressions.

Yes, I agree. It doesn't really matter though; it's something we can fix up ourselves pretty easily. The `revision` case was the one that annoyed me though so :+1: for that.

**Comment by xu-cheng** [comment]
I just come up the idea to put the indent into consideration. See https://github.com/Homebrew/homebrew/pull/37024

**Pull request closed without merging**
