### PR TITLE
awscli 1.7.37

### PR DESCRIPTION
**Pull request by nijikon**

### CODE REVIEW

**Comment by mikemcquaid** [comment]
@nijikon Why did you force push this, out of interest?

**Comment by nijikon** [comment]
@mikemcquaid I saw that there is a new version of pyasn1, but I noticed that it did not get commited. So I pushed again now.

**Comment by mikemcquaid** [comment]
@nijikon Ah ok.

**Comment by mikemcquaid** [comment]
Thanks @nijikon!

**Pull request closed without merging**
