### PR TITLE
pdksh: patches + fix install name

### PR DESCRIPTION
**Pull request by geoff-codes**
- Add important patches from upstream.
- Install as `pdksh` instead of `ksh`, which conflicts with [AT&T] ksh.
- Install template .kshrc and .profile files in `etc`.
- Cleanup, add test.

### CODE REVIEW

**Comment by tdsmith** [comment]
What do the patches do, why are they important, and when can we remove them?

I think I'd rather not change the name of the installed executable.

**Comment by geoff-codes** [comment]
> What do the patches do


From [the patch preamble](http://www.cs.mun.ca/~michael/pdksh/files/pdksh-5.2.14-patches.1):
```
Here are patches for 3 significant bugs in pdksh-5.2.14:
  - set -x dumps core (shf.c);
  - output of "jobs" command is filled with ^A characters (jobs.c);
  - "typeset -r foo=bar" fails saying foo is readonly (var.c).
```
 > why are they important

They are important because they patch critical bugs. They are mentioned on the pdksh homepage.

> when can we remove them

Probably never. The newest of these patches is dated 2001; pdksh 5.2.14 was released it 1999. It is not an actively maintained project, having largely been supplanted by shells like mksh and AT&T (a.k.a. the _real_) ksh, when it was open sourced in 2005.

> I think I'd rather not change the name of the installed executable.

Well, obviously, that's your call to make, but it would make homebrew the only [package](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=294592)  [manager](http://ftp.netbsd.org/pub/pkgsrc/current/pkgsrc/shells/pdksh/PLIST) that I know of to **not** do this, since having this piece of antiquity on your path as "ksh" _will_ break stuff (it is roughly equivalent to ksk88, not ksh93 like AT&T ksh or mksh). IMO, its a useful tool for testing the "lowest common denominator" for shell script compatibility, but that's about all.

In any case, it conflicts with the [ksh formula](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/ksh.rb), so if you elect to keep it as-is, I believe it should have a `conflicts_with` added, or be made keg-only.

**Comment by tdsmith** [comment]
Thanks for the history lesson; renaming sounds reasonable.

What about the other patches (i.e. the macports one)? I'm not sure what the comment refers to.

Please add newlines between the `patch` blocks.

**Comment by tdsmith** [comment]
Oh, we already applied that one, durr. Okay, thanks.

**Comment by geoff-codes** [comment]
@tdsmith Newlines added.

**Comment by tdsmith** [comment]
Thanks again!

**Pull request closed without merging**
