### PR TITLE
+opam.1.2.2

### PR DESCRIPTION
**Pull request by avsm**

### CODE REVIEW

**Comment by xu-cheng** [comment]
Please fix these problems thanks.
```
        Error: 2 problems in 1 formulae
opam:
 * Stable resource "extlib": Use https:// URLs for downloads from Google Code (url is http://ocaml-extlib.googlecode.com/files/extlib-1.5.3.tar.gz).
 * HEAD resource "extlib": Use https:// URLs for downloads from Google Code (url is http://ocaml-extlib.googlecode.com/files/extlib-1.5.3.tar.gz).
```

**Comment by DomT4** [comment]
Ping.

**Comment by amirmc** [comment]
I submitted https://github.com/avsm/homebrew/pull/2 to @avsm's fork - not sure if that's sufficient to deal with the issue (I assume the tests would be kicked off again if he merges it).

**Comment by DomT4** [comment]
@amirmc If you'd like to, we'd welcome a PR to replace this one given the silence here.

**Comment by avsm** [comment]
My apologies for the delay responding to this. For some reason I was unsubscribed from the update email stream and only noticed the activity when I went to check up on its status...

**Pull request closed without merging**
