### PR TITLE
tika 1.8

### PR DESCRIPTION
**Pull request by Fil**
cc: @robsonpeixoto @anjackson

### CODE REVIEW

**Comment by jacknagel** [comment]
Checksums seem wrong?

**Comment by Fil** [comment]
I'm not sure what the first should be. The second is what I got downloading
the package. Is it incorrect?

On Sunday, May 10, 2015, Jack Nagel <notifications@github.com> wrote:

> Checksums seem wrong?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/Homebrew/homebrew/pull/39580#issuecomment-100668615>.
>


-- 
-- Fil

**Comment by jacknagel** [comment]
```
$ brew fetch --force tika
==> Downloading http://www.apache.org/dyn/closer.cgi?path=tika/tika-app-1.8.jar
==> Best Mirror http://apache.cs.utah.edu/tika/tika-app-1.8.jar
######################################################################## 100.0%
Downloaded to: /Library/Caches/Homebrew/tika-1.8.jar
SHA1: 071448fd1f6e71cdf42abc6971c2fd129e3a4543
SHA256: 9346cf68c00a46b2e6189794d5fb2e127bf9b60ef6d216edf06e01917f7deaef
Warning: Formula reports different SHA1: 0acf5fd2fd7ff410120d6d698b3c762d8bea83f1
```

(May as well update to sha256 while we're here.)

**Comment by jacknagel** [comment]
FYI, when you `@` someone in a commit message, they get a notification every time you re-push that commit.

**Comment by Fil** [comment]
Sorry!  Thanks for guiding me through -- next time I'll do better :)

-- Fil

**Pull request closed without merging**
