### PR TITLE
pandoc-citeproc 0.7.3

### PR DESCRIPTION
**Pull request by adunning**

### CODE REVIEW

**Comment by adunning** [comment]
Sorry about this; these builds always seem to come out a touch differently than one expects …

**Comment by mikemcquaid** [comment]
Don't worry, not your fault! Retrying it.

**Comment by adunning** [comment]
It failed at a different point that time, while building yaml rather than texmath. My local test was on Yosemite, which didn't raise any errors.

**Comment by dunn** [comment]
@BrewTestBot test this please

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/62c7db033446c3dcfb49aeb16905fb4a336983be. Thank you for your contribution to Homebrew, we appreciate it! :smiley_cat:

**Pull request closed without merging**
