### PR TITLE
apparix: test added

### PR DESCRIPTION
**Pull request by bfontaine**

### CODE REVIEW

**Comment by xu-cheng** [comment]
@mikemcquaid Seems something wrong in the bottle url detection:
```
==> Publishing on Bintray:
Error: Failure while executing: /usr/bin/curl -f#LA Homebrew\ 0.9.5\ (Ruby\ 2.0.0-481;\ Mac\ OS\ X\ 10.10.2) --silent --fail -u****:**** -X POST https://api.bintray.com/content/homebrew/bottles/apparix/11-0../publish
```

```
[1] brew(main)> f=:apparix.f;
[2] brew(main)> b=Bottle.new(f, f.bottle_specification);
[3] brew(main)> b.url
=> "https://homebrew.bintray.com/bottles/apparix-11-0..bottle.tar.gz"
```

I will manually publish bottle instead.

**Comment by mikemcquaid** [comment]
@xu-cheng Please don't manually publish bottles but instead fix the underlying problem. Otherwise we won't be able to pull updates and third-party bottle users won't be able to bottle this.

**Comment by xu-cheng** [comment]
@mikemcquaid I have find the cause, will send PR to fix this soon.

**Comment by xu-cheng** [comment]
Sorry, I found the problem is larger than I thought. I have to revert b4a8235 in b8a812e43ac2de39fcea304cf4fc1e6a457f01b0 as the version is completely wrong.

Deeply sorry about this. I need to more carefully next time.

**Comment by mikemcquaid** [comment]
No worries, thanks.

**Pull request closed without merging**
