### PR TITLE
jq 1.5rc2 (devel)

### PR DESCRIPTION
**Pull request by nicowilliams**
Update jq devel to 1.5rc2.

### CODE REVIEW

**Comment by dunn** [comment]
Seeing a SHA mismatch:
```
Warning: Formula reports different SHA256: 25dfe32295f96bd019d373d9d145b6f6c23e4006d5fdb176d3080731f3a2d791
Downloaded to: /Library/Caches/Homebrew/jq-1.5rc2.tar.gz
SHA1: 473b6f8d497486922d192d6e366ebafd8dea1332
SHA256: f78844c89940e98f47205f617763e2d3c2cfddb9420f59a988612ec70f55ee24
```

**Comment by nicowilliams** [comment]
On Sun, Jul 26, 2015 at 11:27:34PM -0700, Alex Dunn wrote:
> Seeing a SHA mismatch:
> ```
> Warning: Formula reports different SHA256: 25dfe32295f96bd019d373d9d145b6f6c23e4006d5fdb176d3080731f3a2d791
> Downloaded to: /Library/Caches/Homebrew/jq-1.5rc2.tar.gz
> SHA1: 473b6f8d497486922d192d6e366ebafd8dea1332
> SHA256: f78844c89940e98f47205f617763e2d3c2cfddb9420f59a988612ec70f55ee24
> ```

Ah, it's a redirect, so curl | sha256sum doesn't work.  PR updated.

**Comment by bfontaine** [comment]
Yes, you should use `curl -sL <url> | sha256sum`.

**Comment by dtolnay** [comment]
@nicowilliams, jq.1.prebuilt is missing from 1.5rc2. It was included in 1.5rc1. This is causing the build failure because there is no Ruby with which to rebuild jq.1.prebuilt.

**Comment by nicowilliams** [comment]
On Mon, Jul 27, 2015 at 09:46:03AM -0700, David Tolnay wrote:
> @nicowilliams, jq.1.prebuilt is missing from 1.5rc2. It was included in 1.5rc1. This is causing the build failure because there is no Ruby with which to rebuild jq.1.prebuilt.

Various other things were also missing.  All fixed (manually tested).

**Comment by dunn** [comment]
Merged as cb441ffefd115d37765c4efabc5f1cb9d0fd79be, thanks!

**Comment by nicowilliams** [comment]
> Merged as cb441ffefd115d37765c4efabc5f1cb9d0fd79be, thanks!

Thank you!

**Pull request closed without merging**
