### PR TITLE
gtk+ and gtk+3: hicolor-icon-theme added as dependency

### PR DESCRIPTION
**Pull request by tschoonj**
default fallback icon theme

### CODE REVIEW

**Comment by tschoonj** [comment]
@DomT4 this one could use a re-queue... I cannot imagine what could have caused this build to fail.

**Comment by DomT4** [comment]
`gtk-mac-integration`'s test failed, which I can't repro locally. Have re-queued in case it was a glitch.

**Comment by tschoonj** [comment]
No idea why the test fails. The gtk+ include path is clearly there

It should be safe to merge this in anyway

**Comment by DomT4** [comment]
Weirdly it fails on the test-bot:

```
Testing gtk-mac-integration
==> /usr/bin/clang test.c -o test -Os -w -pipe -march=native -mmacosx-version-min=10.10 -F/usr/local/Frameworks -L/usr/local/lib -F/usr/local/Frameworks -Wl,-headerpad_max_install_names -I/usr/local/opt/atk/include/atk-1.0 -I/usr/local/opt/cairo/include/cairo -I/usr/local/opt/fontconfig/include -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/opt/gdk-pixbuf/include/gdk-pixbuf-2.0 -I/usr/local/opt/gettext/include -I/usr/local/opt/glib/include/glib-2.0 -I/usr/local/opt/glib/lib/glib-2.0/include -I/usr/local/opt/gtk+/include/gtk-2.0 -I/usr/local/opt/gtk+/lib/gtk-2.0/include -I/usr/local/Cellar/gtk-mac-integration/2.0.8/include/gtkmacintegration -I/usr/local/opt/libpng/include/libpng16 -I/usr/local/opt/pango/include/pango-1.0 -I/usr/local/opt/pixman/include/pixman-1 -DMAC_INTEGRATION -D_REENTRANT -L/usr/local/opt/atk/lib -L/usr/local/opt/cairo/lib -L/usr/local/opt/gdk-pixbuf/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/glib/lib -L/usr/local/opt/gtk+/lib -L/usr/local/Cellar/gtk-mac-integration/2.0.8/lib -L/usr/local/opt/pango/lib -latk-1.0 -lcairo -lgdk-quartz-2.0 -lgdk_pixbuf-2.0 -lgio-2.0 -lglib-2.0 -lgobject-2.0 -lgtk-quartz-2.0 -lgtkmacintegration-gtk2 -lintl -lpango-1.0 -lpangocairo-1.0
In file included from test.c:1:
/usr/local/Cellar/gtk-mac-integration/2.0.8/include/gtkmacintegration/gtkosxapplication.h:26:10: fatal error: 'gtk/gtk.h' file not found
#include <gtk/gtk.h>
         ^
1 error generated.
Error: gtk-mac-integration: failed
```

But I can't get it to break locally despite running it 10 times consecutively earlier. Maybe it's some kind of race condition :octopus:

**Comment by tschoonj** [comment]
It gets weirder... I added gtk-mac-integration to the PR with one debugging line added in the test block and then it works fine...

Will revert this and see what that changes in the build

**Comment by tschoonj** [comment]
And then it fails again...

I am beginning to understand what's going on after reading the console output. The `gtk-mac-integration` test fails during the `gtk+3` build, not the `gtk+` one. In this case `gtk+` is not 'loaded' before the test runs though it should since it is a hard `gtk-mac-integration` dependency, explaining why it fails.

@mikemcquaid what do you think about this?

**Comment by mikemcquaid** [comment]
Thanks @tschoonj! Seems unrelated to this PR so merged as-is

**Pull request closed without merging**
