### PR TITLE
htop-osx 2.0.0

### PR DESCRIPTION
**Pull request by gecgooden**
Updated the htop-osx formula to 2.0.0

### CODE REVIEW

**Comment by rfinnie** [comment]
There is also #49062 which proposes removing the htop alias and replacing it with a new htop formula using this same 2.0.0 version.  There should probably be a consensus on which way to go with this before proceeding.

**Comment by gecgooden** [comment]
I think going the route of one of the other two pull requests would be better, because my proposed changes modify this formula from being about the htop-osx fork to the actual version of htop, and so the need for an alias is gone.

**Comment by jamesyc** [comment]
This pull request replaces htop-osx, which is a **fork** of htop not operated by the developers of htop itself. Notably, the current homepage is https://github.com/max-horvath/htop-osx and the actual code itself is based off of htop v0.8.x circa 2009. 

Although having `htop` aliased to the new htop 2.0 is a good idea, htop-osx and htop should exist separately, as they are basically different programs at this point. Notice that the title of this pull request is "htop-osx 2.0.0"... which doesn't exist. Again, "htop" != "htop-osx" and they should be treated as separate programs with separate homebrew formulae. 

I don't think this pull request is a good idea. 
Optimally, I feel that "htop 2.0.0" should be added in a way such that 1: it becomes the new default installation for `brew install htop`, 2: `htop` should be aliased to htop 2.0.0 by default, and 3: htop-osx is not removed. 

If nobody bothers makes a PR that does that, I'll do it tomorrow or something.

**Comment by Ambroos** [comment]
@jamesyc Pull request #49057 does not delete `htop-osx`, it just removes the alias that turns `brew install htop` into `brew install htop-osx`. If #49057 is merged you will be able to do both those commands,  where `install htop` will install the original `htop 2.0.0`, and `install htop-osx` will install the classic fork.

**Comment by jamesyc** [comment]
@Ambroos Oh, ok I misread the commit diff. I also just noticed #49062 as well. Those two PRs look mostly the same to me, 62 has a warning for sudo usage but 57 doesn't.

Which one should be pulled? The earlier one or the "more complete" one?

**Comment by Ambroos** [comment]
htop 2.0.0 no longer requires sudo access on OSX to give meaningful process data, so there's no need for the warning. Which means #49057 is the only correct/complete pull request and should be merged, while #49062 and this pull request should be closed.

**Comment by jamesyc** [comment]
@Ambroos I don't think that sounds right. 

> htop requires root privileges to correctly display all running processes.
so you will need to run `sudo htop`.
You should be certain that you trust any software you grant root privileges.

There's no way an unprivileged process should be able to get info or kill processes running as root. To confirm, I just installed htop 2.0.0 and ran it without sudo and with sudo. Look at the difference:   
https://www.dropbox.com/s/u2ori9o80gfr1ml/Screenshot%202016-02-11%2002.46.01.png?dl=0  
https://www.dropbox.com/s/ezkyxzeccwgwsfr/Screenshot%202016-02-11%2002.45.46.png?dl=0  

The warning label is correct, "htop requires root privileges to correctly display all running processes".

**Comment by UniqMartin** [comment]
Closing in favor of #49057 as it was the first one (to my knowledge) and to keep the confusion for other maintainers to a minimum. Thanks for the discussion. I would really appreciate if could direct everything that hasn't been addressed yet to the linked PR to make it awesome!

**Pull request closed without merging**
