### PR TITLE
couchpotato 2.6.3

### PR DESCRIPTION
**Pull request by stuwil**
Sorry, messed up rebasing in #42442. Opening a new pull request.

### CODE REVIEW

**Comment by DomT4** [comment]
The test is hanging here, quite badly. I let it go on for over [three hours last night](http://bot.brew.sh/job/Homebrew%20Pull%20Requests/30834/) and the test still didn't complete. Does that reproduce for you locally at all?

**Comment by stuwil** [comment]
I can't reproduce locally, passes fine. I did initially notice the test hung when sending a SIGINT to kill the process, so I changed it to a SIGTERM. Let me play around with it this evening and try another commit...

**Comment by stuwil** [comment]
Test was passing locally as I was being silly and not actually calling the child process being invoked by the startup script... so it was killing a process that didn't exist. Should have it fixed now.

**Comment by DomT4** [comment]
Resolved the error on two of our test-bots, but is now apparently hanging on Yosemite :sweat_smile:

**Comment by stuwil** [comment]
Rewrote the shutdown approach, let's see if that helps...

**Comment by mikemcquaid** [comment]
@stuwil Seems not, unfortunately. Can always go for a simple `--help` or `--version` test for now to get this merged.

**Comment by DomT4** [comment]
Yeah, let's give up on this for now. I think it took up about 24 hours of build/test time over the last week, so if it's not working by this point let's keep it simple.

**Comment by stuwil** [comment]
Agreed, reverted back to the initial test. Still really curious as to why the process is getting stuck on only the Yosemite box, can't reproduce that locally on 10.10.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/3779be3828642aead7e25b1dba2ecaedb4294ace. Thank you for your contribution to Homebrew, we appreciate it! :smiley_cat:

**Pull request closed without merging**
