### PR TITLE
curl 7.42.1

### PR DESCRIPTION
**Pull request by vszakats**
@DomT4 It'd nice to update your mirrored copy.

### CODE REVIEW

**Comment by DomT4** [comment]
Sure. Will do this evening if not sooner.

**Comment by vszakats** [comment]
Thank you!

**Comment by DomT4** [comment]
It's up.

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
