### PR TITLE
Teamcity 9.1.4

### PR DESCRIPTION
**Pull request by kenorb**

### CODE REVIEW

**Comment by kenorb** [comment]
> 65 tests run, 0 skipped, 3 failed.

Where I can see these 3 failed tests?

**Comment by DomT4** [comment]
http://bot.brew.sh/job/Homebrew%20Pull%20Requests/38132/

```
        Error: 3 problems in 1 formula

==> audit problems
teamcity:
 * A `test do` test block should be added
 * Stable: version 9.1.4 is redundant with version scanned from URL
 * Description is too long. "name: desc" should be less than 80 characters.
Length is calculated as teamcity + desc. (currently 140)

```

**Comment by bfontaine** [comment]
Ping?

**Comment by bfontaine** [comment]
Closing due to no response. Feel free to open another PR addressing the audit issues. Thanks!

**Pull request closed without merging**
