### PR TITLE
cconv: added test

### PR DESCRIPTION
**Pull request by DomT4**
Test added, modernised the formulae, scrapped the patch in favour of an inreplace.

### CODE REVIEW

**Comment by DomT4** [comment]
Any of the maintainers have any idea why the test is blowing up on Yosemite and Mavericks? It's working fine locally, and on ML on the Bot :cry:

**Comment by mikemcquaid** [comment]
Some Ruby 2.0 UTF-8 issue that I'm not sure how to resolve I'm afraid.

**Comment by DomT4** [comment]
Ah, okay. I've simplified the test so we don't have to try and debug encoding issues then.

**Comment by mikemcquaid** [comment]
Thanks @DomT4!

**Pull request closed without merging**
