### PR TITLE
Adding choose 1.0

### PR DESCRIPTION
**Pull request by sdegutis**

### CODE REVIEW

**Comment by DomT4** [comment]
```
==> audit problems
choose:
 * Formula name conflicts with homebrew/head-only/choose
 * A `test do` test block should be added
 * Stable: version 1.0 is redundant with version scanned from URL
```
You can ignore the top error there, but the other two need addressing, Thanks!

**Comment by sdegutis** [comment]
@DomT4 Okay, thanks. I've force-pushed the changes you asked for.

**Comment by DomT4** [comment]
Looks like @bfontaine stole your formula name in https://github.com/Homebrew/homebrew/commit/aca507dc82aadbb00703a1e257ee2b47e3e51c53 :trollface:.

Mind finding an alternative name here? `sdegutis-choose` or `fuzzy-choose` or something maybe.

**Comment by sdegutis** [comment]
@DomT4 I had to do it on a different pull request (because the formula name & branch name changed) so I'm closing this one.

**Comment by bfontaine** [comment]
@sdegutis technically you can keep the same branch and just force-push to edit your PR :wink:

**Comment by sdegutis** [comment]
@bfontaine I thought the rules of PRs required them to have the same branch name as the formula name, and I wanted to make sure I covered all the bases of what could come up as further issues needing to be addressed before it would be merged.

**Comment by bfontaine** [comment]
> Don't worry too much about branch names; I fairly often name mine after songs.

:laughing:

**Comment by DomT4** [comment]
Get bored of formula names after seeing hundreds a day :relaxed:

**Pull request closed without merging**
