### PR TITLE
duplicity 0.7.06 (devel)

### PR DESCRIPTION
**Pull request by reelsense**
0.7.06 adds support for Backblaze B2 service

### CODE REVIEW

**Comment by DomT4** [comment]
Looks like `devel` expects a `python2` binary which doesn't natively exist on OS X:
```
env: python2: No such file or directory
Error: duplicity: failed
```

**Comment by reelsense** [comment]
I'm not sure if this is a new dependency as of 0.7.06. Last devel 0.7.05 compiles fine from brew. I just wanted to get this new update in brew because Backblaze B2 is super cheap and I wanted to use this with it. I figured others would too.

**Comment by DomT4** [comment]
It'll be a new thing, I suspect. You can just `inreplace` the executable similar to how we have [here](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/src.rb#L24-L27)

**Comment by tdsmith** [comment]
This was accomplished by 416a60bfd2f0. Thanks for the PR!

**Comment by reelsense** [comment]
Thank you, I had no idea what I was doing. I'll learn from your work.

**Pull request closed without merging**
