### PR TITLE
gwenhywfar: fix build with gnutls 3.4.x

### PR DESCRIPTION
**Pull request by rakkesh**
https://github.com/Homebrew/homebrew/issues/46562

### CODE REVIEW

**Comment by bfontaine** [comment]
Could you please [report it upstream](https://devel.aqbanking.de/trac/aqbanking)? Even if they don’t respond at least there’s a ticket in their bug tracker.

**Comment by rakkesh** [comment]
Yes, I had reported it upstream, and updated the link in this PR.

**Comment by bfontaine** [comment]
Oh right sorry :smile:

**Comment by bfontaine** [comment]
Thank you @rakkesh; we appreciate your contribution :wink:

**Comment by rakkesh** [comment]
> Oh right sorry

I apologise for not making it obvious; I should have written a better comment.  😅
No, problem. My motive is to get `GnuTLS` 3.4.7 in `Homebrew` core. 👍

**Pull request closed without merging**
