### PR TITLE
aptly: add missing dependencies

### LINKED ISSUE #43901: aptly failed to build on 10.11
https://gist.github.com/4a65dc41fa7d760879c3

Looks like the formula is missing some dependencies.

### PR DESCRIPTION
**Pull request by apjanke**
Fixes #43901.

### CODE REVIEW

**Comment by DomT4** [comment]
```
        Error: 5 problems in 1 formula
aptly:
 * 132: Trailing whitespace was found
 * 136: Trailing whitespace was found
 * 140: Trailing whitespace was found
 * Use `assert_match` instead of `assert ...include?`
 * Use `assert_match` instead of `assert ...include?`
```

**Comment by apjanke** [comment]
Fixed audit failures. Will try to be better about remembering to do `brew audit` before submitting PRs in the first place.

**Comment by DomT4** [comment]
Pretty sure you're a third of our commit history today :smile:. Merged in https://github.com/Homebrew/homebrew/commit/d795d00b1dab82e2ba0ab003ed7780b55a9ce082. Thank you again!

**Comment by apjanke** [comment]
Oooh, look at that pretty dark green dot!

screen shot 2015-09-15 at 10 26 09 pm


You're welcome.

**Pull request closed without merging**
