### PR TITLE
cassandra 3.0.2

### PR DESCRIPTION
**Pull request by davidcaseria**
Upgrade the cassandra fomula to 3.0.2.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Comment by fogleman** [comment]
`cqlsh` no longer works with this update, even with a completely fresh install.

    Connection error: ('Unable to connect to any servers', {'127.0.0.1': InvalidRequest(u'code=2200 [Invalid query] message="unconfigured table schema_keyspaces"',)})

Also, per the cassandra webpage:

    The most stable release of Apache Cassandra is 2.2.4 (released on 2015-12-07).

Not sure what homebrew's policy is on leading-edge software.

**Comment by mikemcquaid** [comment]
> The latest release of Apache Cassandra is 3.0.2 (released on 2015-12-21). If you're just starting out and not yet in production, download this one.

http://cassandra.apache.org/download/

This sounds like we should be packaging that version. @fogleman Please see if you can reproduce that outside Homebrew and, if so, report it to Cassandra and, if not, create a new issue here. Thanks!

**Comment by shanexu** [comment]
The wrong version of cassandra-driver cause cqlsh failure. I think you should change the version to 3.0.0
Or, just remove /usr/local/Cellar/cassandra/3.0.2/libexec/vendor/lib/python2.7/site-packages/cassandra-driver and install cassandra-driver manually.
```bash
pip install cassandra-driver
```

**Comment by mikemcquaid** [comment]
@shanexu Updating it in https://github.com/Homebrew/homebrew/pull/47639, thanks.

**Pull request closed without merging**
