### PR TITLE
use secure protocol for sourceforge.net homepages

### PR DESCRIPTION
**Pull request by vszakats**
* it will be redirected by SourceForge to cleartext unless logged in
* follow some URL redirects
* update some moved homepages

### CODE REVIEW

**Comment by DomT4** [comment]
If you wanted to take a crack at the build failures and audit errors that'd be cool :wink:

**Comment by vszakats** [comment]
Reverted `watch` formula update because of an existing/pending issue. I'll have a second look to the rest a bit later.

**Comment by vszakats** [comment]
`libcdr` and `libvision`, two dependents of `librevenge` are failing due to `boost` reasons:
```
==> ./test
dyld: Library not loaded: /usr/local/opt/boost/lib/libboost_system-mt.dylib
  Referenced from: /usr/local/opt/libcdr/lib/libcdr-0.1.1.dylib
  Reason: image not found
```
```
==> ./test
dyld: Library not loaded: /usr/local/opt/boost/lib/libboost_system-mt.dylib
  Referenced from: /usr/local/opt/libvisio/lib/libvisio-0.1.1.dylib
  Reason: image not found
```

I removed `librevenge` from this PR for the time being.

**Comment by mikemcquaid** [comment]
> I removed librevenge from this PR for the time being.

@vszakats I know that the main thing that interests you is just HTTPS fixes but it would be really great if you could try and dig in a little harder to failures like this.

**Comment by vszakats** [comment]
@mikemcquaid I'm trying to when seeing hope to get to the bottom of the problem (like with `libcue`) in reasonable amount of free time. `librevenge`s dependents were out of this realm unfortunately, with not much clues from the Internet. Probably it'll take much less time for someone who is already familiar either with these tools or this class of issues. As for `watch`, there was already a PR for it (added a link to document that).

**Comment by mikemcquaid** [comment]
@vszakats Ok, thanks. In the case of `librevenge` it looks like `libcdr` and `libvisio` require a `revision` bump.

**Comment by vszakats** [comment]
Thanks for the clue! I'm going to commit this in a few.

**Comment by vszakats** [comment]
There appears to be some intermittent CI error:
```
==> brew pull --clean https://github.com/Homebrew/homebrew/pull/45914
==> FAILED
fatal: ref HEAD is not a symbolic ref
```
```
Auto packing the repository in background for optimum performance.
See "git help gc" for manual housekeeping.
error: Unable to create '/usr/local/.git/logs/refs/remotes/origin/pr/44728/head.lock': File exists.

If no other git process is currently running, this probably means a
git process crashed in this repository earlier. Make sure no other git
process is running and remove the file manually to continue.
error: failed to run reflog
Resolve operation not in progress, we are not resuming.
Error: Patch failed to apply: aborted.
```

**Comment by DomT4** [comment]
Re-queued.

**Comment by vszakats** [comment]
Thank you @DomT4. Revision bumping didn't seem to have helped with `librevenge`, so I pulled the 3 related commits to reopen them in a separate PR later.

**Comment by DomT4** [comment]
Merged! You will pretty much own the commit tree today :wink:.

Thank you once more @vszakats!

**Comment by vszakats** [comment]
👍🏻It was also a nice week for familiarising the various `git rebase` scenarios, learned a lot! :) Thanks a lot folks!

**Pull request closed without merging**
