### PR TITLE
rancher-compose 0.3.0

### PR DESCRIPTION
**Pull request by alex88**
Instead of #43261 since this is the updated version

### CODE REVIEW

**Comment by ablyler** [comment]
@mikemcquaid this build looks stuck, been running for 6+ hours: http://bot.brew.sh/job/Homebrew%20Pull%20Requests/version=mavericks/33532/console

**Comment by mikemcquaid** [comment]
@ablyler Have rebooted the machine, thanks.

**Comment by alex88** [comment]
@mikemcquaid something that I need to do?

**Comment by alex88** [comment]
Updated to 0.4.0, rebased and squashed

**Comment by alex88** [comment]
Why you don't integrate jenkins builds with github's commit status api?

**Comment by mikemcquaid** [comment]
@alex88 We have, our bots are just overloaded currently.

**Comment by alex88** [comment]
Oh the default one, right

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/3076c637aba85806fa73583816f3baab7c49f75a. Thank you for your contribution to Homebrew @alex88!

**Pull request closed without merging**
