### PR TITLE
Subversion: add devel option for 1.9.0-beta1

### PR DESCRIPTION
**Pull request by brainy**

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Can this be rebased and squashed into a single commit, please?

Squash commits by running `brew update; git checkout $YOUR_BRANCH; git rebase --interactive origin/master and then mark each commit other than the first as squash or fixup then git push -f. Thanks!

**Comment by DomT4** [comment]
SHA256 on the checksum would be :heart:.

**Comment by brainy** [comment]
There's only the one commit (cbdf56a) on the branch ... I have no idea why all of these were included in the pull request. 'git rebase' only shows that commit; will read up on (censored) git docs to see what the big deal is.

**Comment by mikemcquaid** [comment]
Did you `git rebase master` or `git rebase origin/master`?

**Pull request closed without merging**
