### PR TITLE
mpw: use secure urls

### PR DESCRIPTION
**Pull request by vszakats**
### All Submissions:

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew/pulls) for the same update/change?

### CODE REVIEW

**Comment by vszakats** [comment]
CI was having a hard time fetching the Homebrew repo:
```
> git -c core.askpass=true fetch --tags --progress https://github.com/Homebrew/homebrew.git +refs/heads/master:refs/remotes/origin/master +refs/pull/50490/*:refs/remotes/origin/pr/50490/*
Checking out Revision 8ba89406a2cfee7e4ddc605c402b5b3ef5a721a6 (refs/remotes/origin/pr/50490/merge)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 8ba89406a2cfee7e4ddc605c402b5b3ef5a721a6
FATAL: Could not checkout 8ba89406a2cfee7e4ddc605c402b5b3ef5a721a6
```

**Comment by mikemcquaid** [comment]
@vszakats You don't need to resubmit PRs to `homebrew/core` FYI.

**Comment by vszakats** [comment]
Thanks for the info, I had deleted the other copy.

**Comment by mikemcquaid** [comment]
Thanks again @vszakats!

**Pull request closed without merging**
