### PR TITLE
yap: use secure urls

### PR DESCRIPTION
**Pull request by vszakats**

### CODE REVIEW

**Comment by vszakats** [comment]
It seems this formula had already been broken (due to C compilation errors).

**Comment by vszakats** [comment]
Breakage unrelated to present updates.

**Comment by mikemcquaid** [comment]
@vszakats Would you mind trying to fix them?

**Comment by vszakats** [comment]
@mikemcquaid Spent an hour on it, found out at least 3 different fatal build issues: 
- int size detection failure - in Jenkins results (OK locally)
- undeclared `Clause_new()` error - in local build and also #44628
- link failure - in Travis CI results and also #41558
- plus an immense amount of warnings

I'm afraid I won't be able to fix any of these, sorry :(

**Comment by vszakats** [comment]
Another (different) problem report here, regarding Mountain Lion: https://sourceforge.net/p/yap/discussion/131077/thread/04971fbb/

**Comment by DomT4** [comment]
I *suspect* this might build against GCC-4.9.

**Comment by vszakats** [comment]
@DomT4 That seems like a safe bet. Is there any way to force that in the formula?

**Comment by vszakats** [comment]
Closing this one due to the too many problems with this formula.

**Pull request closed without merging**
