### PR TITLE
dmd 2.069.0-b1 (devel)

### PR DESCRIPTION
**Pull request by John-Colvin**
the patch should go away for the next beta

### CODE REVIEW

**Comment by DomT4** [comment]
Any chance we can add a small comment above the patch explaining in brief what it's doing?

**Comment by John-Colvin** [comment]
Done.

These betas often become rapidly obsolete, so it would be very useful if they could be merged quicker seeing as they are very much uncontroversial.
I understand that there is always limited person-power available to check things, but do you have any 'auto-merge' system* that could be used? So when someone has manually reviewed a pull it can be pre-approved assuming the auto-tester passes. This functionality has been found very useful in dmd/druntime/phobos development.

* E.g. hook into the Github API from Travis-CI using `after_success`

**Comment by DomT4** [comment]
Normally the turn around on these PRs is significantly quicker. Your last one for this formula got merged inside 24 hours, and [most of your commits](https://github.com/Homebrew/homebrew/commits/master?author=John-Colvin) do get merged within that timeframe.

The situation is particularly bad this week because we have two or three maintainers handling the extreme majority of the Issues & PRs; there are normally six around regularly. I also had to spend 3 unplanned hours yesterday working on CI issues, and as you can see we've had Travis downtime as well which is out of our control.

Consequent to Travis falling over this PR still shows in the main list as pending CI verification which makes it difficult to glance through the PR list and see it as passing. I appreciate the delay this week will have been very frustrating, but things will be resuming normal service again relatively soon. There are no plans at this time to remove the requirement for a human to do the last manual verification of the PR before merge.

Merged in https://github.com/Homebrew/homebrew/commit/d699f79385567705c671a2d96ba65aa7a46a1fd1. Thank you for another contribution to Homebrew.

**Comment by John-Colvin** [comment]
Ok, I understand. Thanks for replying in such detail. Onwards and upwards :)

**Pull request closed without merging**
