### PR TITLE
docker-machine-parallels: rebuild with newer dependencies

### PR DESCRIPTION
**Pull request by kad**
Rebuild against included and tested by maintainers dependencies

### All Submissions:

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew/pulls) for the same update/change?

### CODE REVIEW

**Comment by tdsmith** [comment]
Dumb question: is this useful? cc @legal90

**Comment by kad** [comment]
Potentially, it would help users with similar problems like in Parallels/docker-machine-parallels#43
However, I haven't seen confirmation from reporter that rebuilding from sources instead of using brewed binary actually helps. So, this PR is more just a precaution measure.

**Comment by legal90** [comment]
I'd recommend to build docker-machine-parallels using `make build`, because we manage dependencies in the repo itself using `godep` and `GO15VENDOREXPERIMENT ` enabled. https://github.com/Parallels/docker-machine-parallels/blob/master/Makefile
So, you don't have to manage dependencies by yourself, because such build could not be officially supported.

@kad Is is possible to change the brew formula to make it similar to `docker-machine`'s one ([link](https://github.com/Homebrew/homebrew/blob/ba840a56523b956649df91e07c58284b7cf67bea/Library/Formula/docker-machine.rb#L32-L36))? We use the similar approach for dependency management and binary building.

**Comment by kad** [comment]
@legal90 possible, but last time I've tried, it was still trying to fetch something over network during build time. will try again tonight.

**Comment by kad** [comment]
@legal90 @tdsmith formula re-written to use vendored dependencies.

**Comment by tdsmith** [comment]
Looks good, thanks! Pulled in 365e791cc1903 with a few additional changes.

**Comment by legal90** [comment]
@kad Great! Thank you very much :+1:

**Pull request closed without merging**
