### PR TITLE
mercury 14.01.1

### PR DESCRIPTION
**Pull request by bfontaine**
TBH I didn’t test this locally because the last time I compiled Mercury it took more than 1h50.

### CODE REVIEW

**Comment by bfontaine** [comment]
```
Homebrew Pull Requests » yosemite completed with result ABORTED
Homebrew Pull Requests » mountain_lion completed with result ABORTED
Homebrew Pull Requests » mavericks completed with result ABORTED
```

**Comment by xu-cheng** [comment]
```
==> brew install --verbose --build-bottle mercury			Build timed out (after 60 minutes). Marking the build as aborted.
```

**Comment by bfontaine** [comment]
Yes it takes 118 minutes on my machine.

**Comment by mikemcquaid** [comment]
I'll kick this off another time when the is bot is quiet.

**Comment by mikemcquaid** [comment]
Thanks @bfontaine!

**Pull request closed without merging**
