### PR TITLE
Audit fixes: part 2

### PR DESCRIPTION
**Pull request by mrjbq7**
Breaking #39061 into smaller pieces.

This fixes apache.org URLs to use https.

### CODE REVIEW

**Comment by DomT4** [comment]
>  Files changed 34

Per Jack:

> I would say no more than 10 changed formula per PR, per day.

:wink: 

If you're going to do a load of update PRs though - If you could fix everything highlighted by ` brew audit --strict ` rather than just the URLs that'd be super-cool.

**Comment by mrjbq7** [comment]
@DomT4 Yeah, I know this is a few more, but the apache.org URLs kinda go together as a group.

**Comment by mrjbq7** [comment]
(I broke the other PR into 8 chunks, this is part 2 of 8).

I'll look at the ``--strict`` next, didn't know about that option.

**Comment by mrjbq7** [comment]
Okay, then closing these PRs. Will change approach and open another later.

**Pull request closed without merging**
