### PR TITLE
brew-bumps

### PR DESCRIPTION
**Pull request by DomT4**
I’ve been keeping this list private forever. I don’t know whether there’s any use for it in Homebrew or not, but if so, here’s a PR to include it.

It might be useful. No idea. I'll let the maintainers decide.

### CODE REVIEW

**Comment by jacknagel** [comment]
Now that we're running tests on dependents, should we close this, or...?

**Comment by DomT4** [comment]
No complaints from me on closing this if maintainers are happy with the ` test-bot `'s testing at this point.

**Comment by mikemcquaid** [comment]
Yeh, I think so. Thanks for the idea @DomT4. For any @Homebrew/owners wondering what's going on: now when you build a formula it will install all its dependents (e.g. `brew uses`) that have a bottle, a test and aren't changed in this PR. This allows us to do some quick tests to avoid massively breaking dependents (it also gives us a good incentive to get tests for as many formulae as possible which @xu-cheng and @bfontaine have been doing a great job with recently).

**Comment by DomT4** [comment]
Cool. Closing :+1:.

**Pull request closed without merging**
