### PR TITLE
webkitgtk 2.12.0

### PR DESCRIPTION
**Pull request by WebReflection**
This is the latest stable release and it should have fixed shared libraries problems too.
https://github.com/Homebrew/homebrew/issues/47000

### CODE REVIEW

**Comment by tschoonj** [comment]
Before submitting a PR, please confirm that it actually builds locally.

If you would have done that, you would have noticed that the patch in the Formula needs to be removed.

**Comment by WebReflection** [comment]
Apologies, I've used the previous PR as example and didn't check properly. Do you want me to close this first? it might take a while before I can confirm it builds locally.

**Comment by tschoonj** [comment]
What I do in a case like this is undo the commit (with `git reset --mixed HEAD~1`), modify the formula, make sure it builds, commit and then `git push --force`

No need to close the PR if you do it like this.

I know webkitgtk takes forever to build, but I don't think there can be any exception to ensuring it builds locally before filing a PR.

**Comment by WebReflection** [comment]
just to be sure I understand, are hyou saying `patch: DATA` is all I need to remove? I've done that and I'm trying to build it now, I just don't know much about formulas and stuff.

Thanks

**Comment by tschoonj** [comment]
That will allow the build to start but you should also remove everything in the file starting with and including the __END__ tag

**Comment by WebReflection** [comment]
building from here: https://github.com/WebReflection/homebrew-gnome/blob/master/webkitgtk.rb

also the PR was created from web, making `--reset` not so easy.

I rather close this one and do a better PR once verified.

Thanks for the help.

**Comment by tschoonj** [comment]
Why are you using homebrew-gnome? Just fork this repository and work on that one.

**Comment by WebReflection** [comment]
> Why are you using homebrew-gnome?

I've forked that one a while ago in order to have custom formulas for `gjs` and stuff. I just trash stuff in there and I use it as tap.

I've already forked this one and replicated the changes in there, that is just what I'm testing before filing another PR.

I don't use Mac as primary machine, so I work on Linux and push on "my tap" my tests.
Hope I've answered your question.

**Comment by tschoonj** [comment]
Well it's definitely an usual workflow but if it works for you that's fine.

**Comment by WebReflection** [comment]
FYI, so, after about 3 days, this happened:

```txt
==> Downloading http://webkitgtk.org/releases/webkitgtk-2.12.0.tar.xz
Already downloaded: /Library/Caches/Homebrew/webkitgtk-2.12.0.tar.xz
==> cmake . -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/webkitgtk/2.12.0 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMA
==> make install
Last 15 lines from /Users/webreflection/Library/Logs/Homebrew/webkitgtk/02.make:
Scanning dependencies of target WebKit2WebExtension-4-gir
/Library/Developer/CommandLineTools/usr/bin/make -f Source/WebKit2/CMakeFiles/WebKit2WebExtension-4-gir.dir/build.make Source/WebKit2/CMakeFiles/WebKit2WebExtension-4-gir.dir/build
/Library/Developer/CommandLineTools/usr/bin/make -f Source/WebKit2/CMakeFiles/WebKit2-4-gir.dir/build.make Source/WebKit2/CMakeFiles/WebKit2-4-gir.dir/build
[ 98%] Generating ../../WebKit2-4.0.gir
[ 98%] Generating ../../WebKit2-4.0.gir
cd /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2 && CC=/usr/local/Library/ENV/4.3/clang CFLAGS=-Wno-deprecated-declarations LDFLAGS= DYLD_LIBRARY_PATH="/tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/lib:" /usr/local/Cellar/gobject-introspection/1.46.0_1/bin/g-ir-scanner --quiet --warn-all --symbol-prefix=webkit --identifier-prefix=WebKit --namespace=WebKit2 --nsversion=4.0 --include=GObject-2.0 --include=Gtk-3.0 --include=Soup-2.4 --include-uninstalled=/tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/JavaScriptCore-4.0.gir --library=webkit2gtk-4.0 --library=javascriptcoregtk-4.0 -L/tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/lib -L/path/to/nonexistent/folder --no-libtool --pkg=gobject-2.0 --pkg=gtk+-3.0 --pkg=libsoup-2.4 --pkg-export=webkit2gtk-4.0 --output=/tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/WebKit2-4.0.gir --c-include="webkit2/webkit2.h" -DBUILDING_WEBKIT -DWEBKIT2_COMPILATION -I/tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source -I/tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2 -I/tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/JavaScriptCore -I/tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/JavaScriptCore/ForwardingHeaders -I/tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/DerivedSources -I/tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/DerivedSources/webkit2gtk -I/tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/DerivedSources/ForwardingHeaders/webkit2gtk /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/DerivedSources/webkit2gtk/webkit2/WebKitEnumTypes.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/DerivedSources/webkit2gtk/webkit2/WebKitVersion.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitAuthenticationRequest.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitAutocleanups.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitBackForwardList.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitBackForwardListItem.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitColorChooserRequest.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitCredential.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitContextMenu.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitContextMenuActions.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitContextMenuItem.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitCookieManager.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitDefines.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitDownload.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitEditingCommands.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitEditorState.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitError.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitFaviconDatabase.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitFileChooserRequest.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitFindController.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitFormSubmissionRequest.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitForwardDeclarations.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitGeolocationPermissionRequest.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitHitTestResult.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitInstallMissingMediaPluginsPermissionRequest.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitJavascriptResult.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitMimeInfo.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitNavigationAction.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitNavigationPolicyDecision.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitNotificationPermissionRequest.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitNotification.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitPermissionRequest.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitPlugin.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitPolicyDecision.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitPrintOperation.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitResponsePolicyDecision.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitScriptDialog.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitSecurityManager.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitSettings.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitURIRequest.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitURIResponse.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitURISchemeRequest.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitUserContent.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitUserContentManager.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitUserMediaPermissionRequest.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitWebContext.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitWebInspector.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitWebResource.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitWebView.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitWebViewBase.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitWebViewSessionState.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitWebsiteDataManager.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitWindowProperties.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/webkit2.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/*.cpp
cd /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2 && CC=/usr/local/Library/ENV/4.3/clang CFLAGS=-Wno-deprecated-declarations LDFLAGS= DYLD_LIBRARY_PATH="/tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/lib:" /usr/local/Cellar/gobject-introspection/1.46.0_1/bin/g-ir-scanner --quiet --warn-all --symbol-prefix=webkit --identifier-prefix=WebKit --namespace=WebKit2 --nsversion=4.0 --include=GObject-2.0 --include=Gtk-3.0 --include=Soup-2.4 --include-uninstalled=/tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/JavaScriptCore-4.0.gir --library=webkit2gtk-4.0 --library=javascriptcoregtk-4.0 -L/tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/lib -L/path/to/nonexistent/folder --no-libtool --pkg=gobject-2.0 --pkg=gtk+-3.0 --pkg=libsoup-2.4 --pkg-export=webkit2gtk-4.0 --output=/tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/WebKit2-4.0.gir --c-include="webkit2/webkit2.h" -DBUILDING_WEBKIT -DWEBKIT2_COMPILATION -I/tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source -I/tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2 -I/tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/JavaScriptCore -I/tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/JavaScriptCore/ForwardingHeaders -I/tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/DerivedSources -I/tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/DerivedSources/webkit2gtk -I/tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/DerivedSources/ForwardingHeaders/webkit2gtk /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/DerivedSources/webkit2gtk/webkit2/WebKitEnumTypes.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/DerivedSources/webkit2gtk/webkit2/WebKitVersion.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitAuthenticationRequest.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitAutocleanups.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitBackForwardList.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitBackForwardListItem.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitColorChooserRequest.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitCredential.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitContextMenu.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitContextMenuActions.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitContextMenuItem.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitCookieManager.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitDefines.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitDownload.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitEditingCommands.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitEditorState.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitError.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitFaviconDatabase.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitFileChooserRequest.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitFindController.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitFormSubmissionRequest.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitForwardDeclarations.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitGeolocationPermissionRequest.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitHitTestResult.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitInstallMissingMediaPluginsPermissionRequest.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitJavascriptResult.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitMimeInfo.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitNavigationAction.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitNavigationPolicyDecision.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitNotificationPermissionRequest.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitNotification.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitPermissionRequest.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitPlugin.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitPolicyDecision.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitPrintOperation.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitResponsePolicyDecision.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitScriptDialog.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitSecurityManager.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitSettings.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitURIRequest.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitURIResponse.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitURISchemeRequest.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitUserContent.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitUserContentManager.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitUserMediaPermissionRequest.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitWebContext.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitWebInspector.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitWebResource.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitWebView.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitWebViewBase.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitWebViewSessionState.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitWebsiteDataManager.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/WebKitWindowProperties.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/webkit2.h /tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/UIProcess/API/gtk/*.cpp
Command '['/private/tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/tmp-introspectZXLyWa/WebKit2-4.0', '--introspect-dump=/private/tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/tmp-introspectZXLyWa/functions.txt,/private/tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/tmp-introspectZXLyWa/dump.xml']' returned non-zero exit status -5
make[2]: *** [WebKit2-4.0.gir] Error 1
make[1]: *** [Source/WebKit2/CMakeFiles/WebKit2WebExtension-4-gir.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Command '['/private/tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/tmp-introspectfNZSiV/WebKit2-4.0', '--introspect-dump=/private/tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/tmp-introspectfNZSiV/functions.txt,/private/tmp/webkitgtk20160331-3610-1nrdq1a/webkitgtk-2.12.0/Source/WebKit2/tmp-introspectfNZSiV/dump.xml']' returned non-zero exit status -5
make[2]: *** [WebKit2-4.0.gir] Error 1
make[1]: *** [Source/WebKit2/CMakeFiles/WebKit2-4-gir.dir/all] Error 2
make: *** [all] Error 2

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/webreflection/homebrew-gnome/issues

These open issues may also help:
webkitgtk fails to load shared libraries https://github.com/Homebrew/homebrew/issues/47000
```

Any idea if it's a formula issue that could be fixed or a gir one?

**Comment by tschoonj** [comment]
This is exactly the same problem as with 2.11.92 I told you about before. It looks like a g-ir-scanner problem to me

**Comment by WebReflection** [comment]
well, if nothing, we have a double confirmation there is a problem affecting even the stable release.

**Comment by jeremyhu** [comment]
It's not exactly a problem with g-ir-scanner.  The issue is most likely that HomeBrew's gnome-introspection scripts are using the system python interpreter.  Using the system python with SIP enabled will cause DYLD_LIBRARY_PATH to be ignored and thus not passed on to the child process.  Thus, the invocation will fail.

To confirm this, just look at the shebang of /usr/local/Cellar/gobject-introspection/1.46.0_1/bin/g-ir-scanner.  If it's using /usr/bin/env or /usr/bin/python, that's exactly the problem.

**Comment by WebReflection** [comment]
thanks a lot @jeremyhu , any hint on how the formula could look like to solve this problem?

**Comment by jeremyhu** [comment]
This is how we solved it in MacPorts: https://trac.macports.org/changeset/146565

**Comment by tschoonj** [comment]
Hi Jeremy,

It's not the shebang. I made sure it was set to `/usr/local/bin/python` in `g-ir-scanner` and I ended up with the same error:

````
Command '[u'/private/tmp/webkitgtk20160403-84053-178fdjp/webkitgtk-2.12.0/Source/WebKit2/tmp-introspectVesxqR/WebKit2-4.0', u'--introspect-dump=/private/tmp/webkitgtk20160403-84053-178fdjp/webkitgtk-2.12.0/Source/WebKit2/tmp-introspectVesxqR/functions.txt,/private/tmp/webkitgtk20160403-84053-178fdjp/webkitgtk-2.12.0/Source/WebKit2/tmp-introspectVesxqR/dump.xml']' returned non-zero exit status -5
Command '[u'/private/tmp/webkitgtk20160403-84053-178fdjp/webkitgtk-2.12.0/Source/WebKit2/tmp-introspect8z5vz2/WebKit2-4.0', u'--introspect-dump=/private/tmp/webkitgtk20160403-84053-178fdjp/webkitgtk-2.12.0/Source/WebKit2/tmp-introspect8z5vz2/functions.txt,/private/tmp/webkitgtk20160403-84053-178fdjp/webkitgtk-2.12.0/Source/WebKit2/tmp-introspect8z5vz2/dump.xml']' returned non-zero exit status -5
````

Interestingly, the subdirectory `tmp-introspect8z5vz2` does not exist at the time of this call, which is what I think triggers this.

I did notice that the MacPorts formula has more patches. I will see what happens with these added as well. 

For what it's worth, I have seen a very similar failure when building glade, which is why I ended up filing a gobject-introspection bug over this at https://bugzilla.gnome.org/show_bug.cgi?id=764072

**Comment by WebReflection** [comment]
hey folks, WebKitGTK is 2.12.1 now. What's the current status here? any progress whatsoever?

Thanks

**Comment by mikemcquaid** [comment]
CC @tschoonj who I guess is being asked here.

**Comment by tschoonj** [comment]
Haven't built it yet but I doubt it will work. For now I recommend disabling the gobject-introspection support.

**Pull request closed without merging**
