### PR TITLE
boost 1.58

### PR DESCRIPTION
**Pull request by denji**

### CODE REVIEW

**Comment by DomT4** [comment]
Looks like several formulae need revision, at least: freeling, libswiften, metaproxy, points2grid and rcssserver. Knowing the breakage Boost causes, that may not be enough, but start with a revision and see where it takes us :smile_cat:.

If you could change the ` SHA1 ` to `SHA256` on the Boost formulae as well that'd be awesome. No worries if you don't wish to.

**Comment by peterhuene** [comment]
`SHA256` should be `fdfc204fc33ec79c99b9a74944c3e54bd78be4f7f15e260c0e2700a36dc7d3e5` I believe.

**Comment by peterhuene** [comment]
Do the bottle shas need updating too?  I get a SHA of `47d815371c177fcd07021c4865a43fe4a055ee84` for Yosemite, at least.

**Comment by DomT4** [comment]
> Do the bottle shas need updating too?

Nope. The test bot will generate new bottles for everything involved, and they'll have SHA256 hashes rather than SHA1.

**Comment by peterhuene** [comment]
Cool, just wanted to check (never really looked into the formulas, but wanted to test out Boost 1.58 with something).  Thanks!

**Comment by mikemcquaid** [comment]
Looks like a few things may need `revision`ed on Mountain Lion: http://bot.brew.sh/job/Homebrew%20Pull%20Requests/24408/version=mountain_lion/testReport/

**Comment by jacknagel** [comment]
Closing in favor of #39323

**Pull request closed without merging**
