### PR TITLE
Add option for building wxmac statically

### PR DESCRIPTION
**Pull request by ryanjmulder**

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Seems good :+1: . Will just wait on CI.

**Comment by DomT4** [comment]
Test bot is happy. If you wanted to fix the couple things flagged by `brew audit --strict` that'd be cool, but it's in no way mandatory, etc.

**Comment by ryanjmulder** [comment]
`brew audit --strict wxmac` now reports "no offenses detected"

**Comment by DomT4** [comment]
You rock, Thanks! :tada:. Will merge this once the bot is happy again.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/0c313365f958707a22814a971ebceb2a0484afea. Thanks for your contribution to Homebrew, we appreciate it! :smiley_cat:.

Couple of tiny notes, commit messages that aren't version bumps should be styled `formula: thing i changed` and ideally commits should be squashed. Thanks!

**Pull request closed without merging**
