### PR TITLE
ENV.deparallelize: add block form for temporary change

### PR DESCRIPTION
**Pull request by mistydemeo**
Closes #39026.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
:+1:

**Comment by geoff-codes** [comment]
Hmmm, isn't a comment (by a repo maintainer/owner) that says "Closes #1234" supposed to _close_ that issue? Or does that not apply to PRs?

**Comment by mikemcquaid** [comment]
@geoff-codes It's not merged yet as generally we don't merge other maintainers PRs.

**Comment by geoff-codes** [comment]
Sorry, I simply meant this: https://help.github.com/articles/closing-issues-via-commit-messages/#closing-an-issue-in-the-same-repository, which apparently only applies to commit messages, so never mind. Anyway, I'll go ahead and close #39026 manually.

**Comment by asparagui** [comment]
@geoff-codes The issue gets closed after the commit is pushed to master, so for right now it's still pending, fwiw.

**Comment by jacknagel** [comment]
"Around" methods should use the following idiom:

```rb
def foo
  # modify state

  if block_given?
    begin
      yield
    ensure
      # restore state
    end
  end

  # return value
end
```

**Comment by mistydemeo** [comment]
Updated, and tests pass on the bots, so merging!

**Pull request closed without merging**
