### PR TITLE
pgbadger 6.4

### PR DESCRIPTION
**Pull request by dunn**

### CODE REVIEW

**Comment by asparagui** [comment]
+1 on adding a test, -1 on downloading random files to make said test work.  Will defer to somebody else's opinion.

**Comment by xu-cheng** [comment]
Can you just create a smallest log file using `(testpath/"log").write ...`

**Comment by dunn** [comment]
Obvious in retrospect. Thanks!

**Comment by xu-cheng** [comment]
Thanks.

**Pull request closed without merging**
