### PR TITLE
swiftgen 0.7.6

### PR DESCRIPTION
**Pull request by AliSoftware**
### All Submissions:

- [X] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew/blob/master/.github/CONTRIBUTING.md) document?

### Formulae Updates/Changes:

- [X] ~~If your changes include a new `patch` have you submitted the patch upstream & included a brief explanation/link to the upstream submission in the formula?~~

### CODE REVIEW

**Comment by apjanke** [comment]
Merged. Thank you for your contribution to Homebrew!

**Comment by DomT4** [comment]
@apjanke This wasn't merged? :smile:

**Comment by AliSoftware** [comment]
> Merged

Or maybe not :joy:

**Comment by DomT4** [comment]
Merged (for realsies :wink:) in https://github.com/Homebrew/homebrew/commit/ebbedc27e9e06f624cbdfcfdd5047ededc24ed67. Thank you for another contribution to Homebrew @AliSoftware! :smile:

**Comment by AliSoftware** [comment]
Thx @DomT4

**Comment by apjanke** [comment]
My bad; I forgot the final `git push` to get it back to the main GitHub repo. Sorry!

**Pull request closed without merging**
