### PR TITLE
embulk 0.6.19

### PR DESCRIPTION
**Pull request by cosmo0920**

### CODE REVIEW

**Comment by dunn** [comment]
Let's use `write_jar_script` instead of `write_exec_script`; see [`htmlcompressor.rb`](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/htmlcompressor.rb) for an example of how that works.

And in the test block, would you mind changing `system "embulk"` to `system bin/"embulk"` on each line? Thanks!

**Comment by cosmo0920** [comment]
Thanks, reviewing dunn! I've reflected your advise.

**Comment by dunn** [comment]
Thank you! Merged in 1bac057b4398698a77f48eec2a301243249a56b4.

**Comment by cosmo0920** [comment]
Thanks!

**Pull request closed without merging**
