### PR TITLE
libbluray, libdca, libdvdpsi: ssl/tls urls, modernize, sha256 hashes

### PR DESCRIPTION
**Pull request by vszakats**

### CODE REVIEW

**Comment by vszakats** [comment]
This happened on Mountain Lion:
```
==> brew fetch --retry --build-bottle --force libbluray			Build timed out (after 60 minutes). Marking the build as aborted.
Build was aborted
Recording test results
ERROR: Publisher hudson.tasks.junit.JUnitResultArchiver aborted due to exception
hudson.AbortException: No test report files were found. Configuration error?
	at hudson.tasks.junit.JUnitParser$ParseResultCallable.invoke(JUnitParser.java:116)
	at hudson.tasks.junit.JUnitParser$ParseResultCallable.invoke(JUnitParser.java:93)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:2677)
	at hudson.remoting.UserRequest.perform(UserRequest.java:121)
	at hudson.remoting.UserRequest.perform(UserRequest.java:49)
	at hudson.remoting.Request$2.run(Request.java:324)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at ......remote call to mountain_lion(Native Method)
	at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1356)
	at hudson.remoting.UserResponse.retrieve(UserRequest.java:221)
	at hudson.remoting.Channel.call(Channel.java:752)
	at hudson.FilePath.act(FilePath.java:970)
	at hudson.FilePath.act(FilePath.java:959)
	at hudson.tasks.junit.JUnitParser.parseResult(JUnitParser.java:90)
	at hudson.tasks.junit.JUnitResultArchiver.parse(JUnitResultArchiver.java:120)
	at hudson.tasks.junit.JUnitResultArchiver.perform(JUnitResultArchiver.java:137)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:74)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:770)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:734)
	at hudson.model.Build$BuildExecution.post2(Build.java:183)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:683)
	at hudson.model.Run.execute(Run.java:1783)
	at hudson.matrix.MatrixRun.run(MatrixRun.java:146)
	at hudson.model.ResourceController.execute(ResourceController.java:89)
	at hudson.model.Executor.run(Executor.java:240)
```

**Comment by mikemcquaid** [comment]
The build took more than 60m to run: http://bot.brew.sh/job/Homebrew%20Pull%20Requests/26805/version=mountain_lion/console

Also, any chance of adding some `test do` blocks here? Thanks!

**Comment by vszakats** [comment]
I have to pass on the tests this time, sorry.

**Comment by vszakats** [comment]
No :heart: for this one due to missing examples? They seem useful updates to me nevertheless.

**Comment by mikemcquaid** [comment]
Need to get a green build first.

**Comment by vszakats** [comment]
What can I do to fix a build timeout?

**Comment by vszakats** [comment]
Thanks guys for nudging the bot, it is now green-green.

**Comment by bfontaine** [comment]
Thanks you @vszakats, how could we run this repo without people like you submitting PRs? :tada:

**Pull request closed without merging**
