### PR TITLE
gor 0.8.4

### PR DESCRIPTION
**Pull request by hanxue**
New formula

### CODE REVIEW

**Comment by hanxue** [comment]
I'm going to need help with this formula. Brewing failed, with error log at https://gist.github.com/6d2a456ea6b32bf24018

I have fetched the go resource `github.com/mattbaird/elastigo`, but go is complaining about

`cannot find package "github.com/mattbaird/elastigo/api"`
`cannot find package "github.com/mattbaird/elastigo/core"`

Error log

https://gist.github.com/6d2a456ea6b32bf24018

**Comment by bfontaine** [comment]
You need to use a `go_resource` for each of these packages.

**Comment by dunn** [comment]
[Hugo](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/hugo.rb) is one example of a formula that uses `go_resource`; I don't think we have an formal documentation for it yet.

**Comment by DomT4** [comment]
Ping.

**Comment by DomT4** [comment]
Closed via https://github.com/Homebrew/homebrew/commit/372fa2b7ee70ca695c01b3ecb956e2d1204458ad.

**Pull request closed without merging**
