### PR TITLE
Cppcheck 1.69

### PR DESCRIPTION
**Pull request by Marzelpan**

### CODE REVIEW

**Comment by Marzelpan** [comment]
Gna! Downloading Xcode 5.1.1…

**Comment by DomT4** [comment]
It looks like a `cxx11` failure. Try adding `needs :cxx11` to the main body, one empty line after `depends_on "qt"`, and then just underneath `def install` add `ENV.cxx11`.

**Comment by Marzelpan** [comment]
Yes, clang++ on ML seems to default to libstdc++, which lacks cbegin/cend etc. for std::map. Thank you!

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/e2f157cf75536e23356ad228c4d14680e7145f6f. Thank you for your contribution to Homebrew, we appreciate it! :smiley_cat:

**Pull request closed without merging**
