### PR TITLE
jpeg: Upgrade to 9a

### PR DESCRIPTION
**Pull request by JaySon-Huang**
libjpeg version 9a

### CODE REVIEW

**Comment by xu-cheng** [comment]
https://github.com/Homebrew/homebrew/issues/35371

**Comment by JaySon-Huang** [comment]
I am sorry that I didn't notice that before I create this pull request

**Comment by jacknagel** [comment]
We're going to wait for the next version.

**Comment by DomT4** [comment]
Note that whenever we do do this, we're going to need to test and revision a chunk of the ` brew uses ` formula. Sadly, a simple bump will just break a ton of stuff :crying_cat_face:

**Pull request closed without merging**
