### PR TITLE
diff-so-fancy 0.5.2

### PR DESCRIPTION
**Pull request by stevemao**

### CODE REVIEW

**Comment by bfontaine** [comment]
The test fails:
```
==> /usr/local/Cellar/diff-so-fancy/0.5.2/bin/diff-so-fancy
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
/usr/local/Cellar/diff-so-fancy/0.5.2/bin/diff-so-fancy: line 74: /usr/local/Cellar/diff-so-fancy/0.5.2/bin/libs/header_clean/header_clean.pl: No such file or directory
Error: diff-so-fancy: failed
```

The `tput` message can be fixed by using e.g. `ENV["TERM"] = "xterm"` at the beginning of the test but for the other error the test needs to be changed.

**Comment by scottchiefbaker** [comment]
I'm not really sure what I'm looking at here. The tests are failing on OS X? 

That appears to be a tput error. All we're using tput for is to calculate the width of the terminal. Does a simple `tput cols` work for you on that system? I don't have OS X to test with.

**Comment by paulirish** [comment]
Going to move this bug here for the moment: https://github.com/so-fancy/diff-so-fancy/issues/101

**Comment by OJFord** [comment]
Probably nobody cares (i.e. has used diff-so-fancy for long enough to unwittingly rely on it) but a side-effect of ae402b9 is that diff-highlight is no longer installed to an on-`$PATH` location.

As I say I don't think this matters, it's just maybe worth noting/acknowledging.

**Comment by OJFord** [comment]
1/3 Travis seems to fail due to a network error installing gems.

@bfontaine Original issue is fixed, can you re-run the test (or ignore if you're happy to)? :)

**Comment by bfontaine** [comment]
@OJFord Don’t worry about Travis, only the “default” build counts :smiley:

**Comment by bfontaine** [comment]
Thank you for your contribution to Homebrew @stevemao; we appreciate it! :tada:

**Pull request closed without merging**
