### PR TITLE
snescom 1.7.4.1

### PR DESCRIPTION
**Pull request by dholm**

### CODE REVIEW

**Comment by mistydemeo** [comment]
Do you think it might make more sense for this to go in [homebrew-games](https://github.com/Homebrew/homebrew-games/)?

**Comment by mistydemeo** [comment]
Install is failing on all platforms:

```
==> make
Checking dependencies...
make: *** No rule to make target `boost/shared_ptr.hpp', needed by `assemble.o'.  Stop.
```

**Comment by mistydemeo** [comment]
Audit suggests changes to the patch URL:

```
==> audit problems
snescom:
 * GitHub/Gist patches should specify a revision:
https://gist.githubusercontent.com/protomouse/31335db2fe5c11978faf/raw/snescom-disasm-missing-cstdlib.diff
```

**Comment by dholm** [comment]
@mistydemeo 
It's an assembler that can be used to build software for the Super Nintendo so I don't think it would make sense in `homebrew-games`?

I have fixed the missing boost dependency.  Completely missed it since it wasn't a link-time dependency.

Patch URL fixed!

**Comment by mikemcquaid** [comment]
@dholm I still think it probably makes more sense in `games`

**Comment by dholm** [comment]
Ok, I will resubmit it to `homebrew-games` then.

**Pull request closed without merging**
