### PR TITLE
Apache NiFi 0.2.1

### PR DESCRIPTION
**Pull request by apiri**
Providing a new formula to support Apache NiFi release version 0.2.1.

### CODE REVIEW

**Comment by apiri** [comment]
Closing to fix style errors in build.

**Comment by mikemcquaid** [comment]
@apiri You can just push changes to this branch instead?

**Comment by apiri** [comment]
@mikemcquaid Ah, most projects I've worked with strongly prefer the squashed commits, and was trying to get the PR nicely wrapped up in one commit.  Already opened another #43153 and have iterated through there now that I am aware of --strict for audit locally.

Let me know if that is suitable, otherwise I can attempt to revive this PR/branch.

**Comment by mikemcquaid** [comment]
@apiri You can squash commits and then force-push them to the same branch, FYI. No worries for now, though, thanks!

**Pull request closed without merging**
