### PR TITLE
rabbitmq 3.5.7

### PR DESCRIPTION
**Pull request by bartj3**
Not sure if we should keep postponing building from source as is mentioned in the last couple of version upgrades (and in #33616), but for me this is the fastest way to get rabbitmq up to date on my dev machine so here it is.

### CODE REVIEW

**Comment by bfontaine** [comment]
The audit is failing:
```
        Error: 2 problems in 1 formula
rabbitmq:
 * Non-executables were installed to "/usr/local/Cellar/rabbitmq/3.5.7/bin"
The offending files are:
  /usr/local/Cellar/rabbitmq/3.5.7/bin/start.boot
 * object files were linked against system openssl
These object files were linked against the deprecated system OpenSSL.
Adding `depends_on "openssl"` to the formula may help.
  /usr/local/Cellar/rabbitmq/3.5.7/lib/crypto-3.5/priv/lib/crypto.so
```

**Comment by bartj3** [comment]
@bfontaine correct, same as in the previous rabbitmq versions, thats why I mentioned PR #33616. I was told that building from scratch should fix this, but I'm not sure how to update the formula for that. In the last couple of versions it was decided to merge anyways as the current build is failing already, this doesn't add any new failures. We should stop postponing at some point though to get this fixed.

**Comment by mikemcquaid** [comment]
@bartj3 If you could try building from source we'd be super grateful :bow:

**Comment by DomT4** [comment]
Will take it for now. I've added a notation to the formula that we'd *really* like a from-source build here, so perhaps someone will give that to Homebrew for Christmas :christmas_tree:. @bartj3, if you're interested, please do feel free to follow up with that.

Merged in https://github.com/Homebrew/homebrew/commit/612290fb817405b926978e83942daa60b3325c6c. Thank you for another contribution to Homebrew!

**Comment by MerelyAPseudonym** [comment]
@DomT4 I actually looked into building RabbitMQ from source and IIRC it required an Erlang plugin/feature/thing that the Erlang formula doesn't (didn't?) offer. I'd be happy to take another look though, so I'll try to fit it in tonight.

**Pull request closed without merging**
