### PR TITLE
maven: add depends_on :java, mirror and modernize

### PR DESCRIPTION
**Pull request by xu-cheng**

### CODE REVIEW

**Comment by brfrn169** [comment]
Hi xu-cheng,

I think that I can't change java version of maven by manually setting JAVA_HOME because of this commit.
How Can I change java version of maven?

**Comment by xu-cheng** [comment]
@brfrn169 Fixed in https://github.com/Homebrew/homebrew/commit/1ebb60b6e5762beb26cfb62a8a1f4ef1692f6540

**Comment by xu-cheng** [comment]
Sorry by the inconvenience. Feel free to ask if you have any other problem.

**Comment by brfrn169** [comment]
@xu-cheng Thanks!

**Pull request closed without merging**
