### PR TITLE
bashtasklog 0.1.0 (new formula)

### PR DESCRIPTION
**Pull request by Zearin**

### CODE REVIEW

**Comment by Zearin** [comment]
I don’t understand why the build isn’t passing…

**Comment by Zearin** [comment]
Oops.  Forgot to rebase my fork.  Will reopen a new PR shortly.

**Comment by bfontaine** [comment]
Note that you can force-push on your branch to update it.

**Comment by Zearin** [comment]
> Note that you can force-push on your branch to update the PR.

Unfortunately the request was rejected.  I wasted my time. :(

**Comment by bfontaine** [comment]
Note that you can make a personal tap to provide formulae that don’t fit in the core repo. See https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-to-Create-and-Maintain-a-Tap.md

**Comment by Zearin** [comment]
> Note that you can make a personal tap to provide formulae that don’t fit in the core repo. See:
> https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-to-Create-and-Maintain-a-Tap.md

Thanks.  I know. :)  But I don’t have the time to create and maintain a full tap, sadly.

**Comment by bfontaine** [comment]
> I don’t have the time to create and maintain a full tap, sadly.

It’s just a matter of creating a repo and putting your formulae in it, nothing else :wink:

**Pull request closed without merging**
