### PR TITLE
Poppler 0.38.0

### PR DESCRIPTION
**Pull request by luzpaz**

### CODE REVIEW

**Comment by mikemcquaid** [comment]
All of `brew uses poppler` will need their `revision` bumped.

**Comment by luzpaz** [comment]
- [ ] diff-pdf
- [ ] frescobaldi
- [ ] pdfgrep
- [ ] dspdfviewer
- [ ] pdf2htmlex
- [ ] evince
- [ ] pdf2svg
- [ ] homebrew/x11/gimp
- [ ] homebrew/x11/xournal
- [ ] homebrew/x11/inkscape

**Comment by luzpaz** [comment]
@mikemcquaid I've added a list of the formulas that use poppler. Once the build successfully builds, is there a expedited way to revision bump them ?

**Comment by UniqMartin** [comment]
@luzpaz Check out previous PRs (#45244, #44238) on how to best handle this. To my knowledge, they were pretty successful in only bumping what needs bumping without breaking anything.

> All of `brew uses poppler` will need their `revision` bumped.

Not necessarily true if the install name doesn't change and there is no API/ABI breakage.

**Comment by UniqMartin** [comment]
Merged in ccc7ddd86f0829d360f307dd780b51c460bcc5bd. Thanks @luzpaz! We couldn't run Homebrew without contributions from people like you! :smiley_cat:

**Pull request closed without merging**
