### PR TITLE
Updated link to the ACE homepage and removed note about configure sup…

### PR DESCRIPTION
**Pull request by jwillemsen**
…port, we don't have that in ACE for some time now

### CODE REVIEW

**Comment by DomT4** [comment]
@BrewTestBot test this please

**Comment by jwillemsen** [comment]
Looks travis-ci timed out and didn't start compiling ACE at all, any idea?

**Comment by DomT4** [comment]
Can ignore Travis. It's only in testing at the moment. Jenkins is the important one.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/8856695651c2467103668d35548d00b72f62719f. Thank you for your contribution to Homebrew @jwillemsen!

**Pull request closed without merging**
