### PR TITLE
use more https in urls and updated some lost links (in brew app)

### PR DESCRIPTION
**Pull request by vszakats**

### CODE REVIEW

**Comment by jacknagel** [comment]
I'd prefer to avoid churn and not change all the URLs in the test suite.

**Comment by vszakats** [comment]
I was debating that internally. Would you agree on restoring http://example.com, but leaving the rest? I saw inconsistent use of http vs https in certain github/sourceforge test urls, so maybe getting them to https wouldn't hurt? (and they don't seem to effect actual test results)

**Comment by jacknagel** [comment]
My main concern is preserving the git blame for the affected lines. I spend quite a bit of time digging through the history, and it's fairly annoying to end up at commits that are not relevant to the origin of the code.

**Comment by vszakats** [comment]
Restored http in test code. Squashed too (success!).

**Comment by jacknagel** [comment]
Thanks.

I dropped the changes to vendor/okjson.rb, since that file is the unmodified upstream source (other than being wrapped in the `Vendor` module).

**Pull request closed without merging**
