### PR TITLE
gnu-which 2.21

### PR DESCRIPTION
**Pull request by dunn**
Is it worth making sure the test works for when formulae are built with non-default options?

### CODE REVIEW

**Comment by DomT4** [comment]
Homebrew tends to ignore options in testing, even ` default-names ` options, otherwise tests would likely end up huge as each individual option gets tested :smile_cat:.

One of the biggest use cases for testing is for the test-bot to see whether bumping certain things breaks others, but the bot will always use or build a bottle with the default options.

**Comment by dunn** [comment]
OK, I've been assuming the goal is making a test that passes whatever options are used.  Should I put the test back to how it was?

**Comment by mikemcquaid** [comment]
Aye, may as well, thanks!

**Comment by dunn** [comment]
Gotcha, back to normal.

**Comment by xu-cheng** [comment]
Thanks for the pull request! 🎉 Homebrew depends on contributions from community members like you and we're grateful for your support.

**Pull request closed without merging**
