### PR TITLE
Updated GHC to 7.8.4

### PR DESCRIPTION
**Pull request by pthariensflame**
Also, deleted the replacement-Cabal system, since that issue has now been resolved in the base GHC download.

I'm not sure what to do with the binary download for 7.8.3, since one for 7.8.4 doesn't seem to exist.  Is there a way to tell Homebrew that the binary download is for a different (earlier) version than the source download?

### CODE REVIEW

**Comment by mikemcquaid** [comment]
> I'm not sure what to do with the binary download for 7.8.3, since one for 7.8.4 doesn't seem to exist.

Let's just wait for it to appear.

**Comment by pthariensflame** [comment]
I just realized what the `binary` resource is all about.  GHC needs to be bootstrapped with another (possible earlier) version of itself in order to be built from source; *that's* the purpose of the binary download being used here.  No user of this formula is going to get the binary download as their resulting GHC; it's only used for the bootstrapping process.  As such, we shouldn't need to wait for a 7.8.4 binary download to appear; the 7.8.3 one does just as well (seeing as 7.4.* and up are all acceptable for this role).

**Comment by jacknagel** [comment]
@mikemcquaid there's a bad interaction when a formula that is updated in a pull request is also used in the test phase of another formula: http://bot.brew.sh/job/Homebrew%20Pull%20Requests/19250/version=mavericks/consoleText

In any case, I killed the build for now, as updating ghc and cabal install in the same pull request is going to cause ghc to be compiled from source twice, and that's going to back up the bots quite a bit.

**Comment by pthariensflame** [comment]
Oh, wow!  I didn't know.  When I next have access to my laptop tomorrow, I'll redo this as two seperate pull requests, then.  I guess I'll close this one now.

**Pull request closed without merging**
