### PR TITLE
upgrade protocols (3)

### PR DESCRIPTION
**Pull request by vszakats**

### CODE REVIEW

**Comment by DomT4** [comment]
Looks like a upstream website decided to fail briefly during CI testing; it's fine locally. I'll requeue later tonight when things are quiet.

**Comment by vszakats** [comment]
Sadly, I couldn't find a proper mirror for this. (The URL works from here now.)

**Comment by vszakats** [comment]
Took out the two formulae with unstable ibiblio URLs. Will resubmit them separately.

**Comment by vszakats** [comment]
Clean now! Travis CI timeout out, which seems expected.

**Comment by DomT4** [comment]
Merged. Thanks @vszakats!

**Pull request closed without merging**
