### PR TITLE
tor 0.2.6.8

### PR DESCRIPTION
**Pull request by DomT4**
Bugfix release.

### CODE REVIEW

**Comment by DomT4** [comment]
Only a minor version bump, so merged my own PR here, per discussions with Mike yesterday I think I'm okay to merge my own simple version bump/minor change PRs. If the other maintainers do see this, Thank you for the opportunity to contribute more. Hopefully I'll be more useful than annoying; I'll certainly try and aim for the former.

**Comment by mikemcquaid** [comment]
Yeh, that's cool, thanks @DomT4. Ideally I'd still use `brew pull` to pull it though so we get the nices `Closed by`

**Comment by DomT4** [comment]
Thanks for the confirmation Mike. Used `brew pull` https://github.com/Homebrew/homebrew/commit/779aaf51d7ae7d0b07ff58b446fc30e628bdc0d1.

I think the reason this PR isn't showing it as `Closed by` is because before Github/the CI had realised I'd pushed to the master I'd deleted the local branch and pushed the deleted branch, there seems to be a couple minutes delay between push to master and it being auto-closed.

I'll try and give it a few more minutes before deleting and pushing the deleted branch to my remote so it looks properly closed.

**Comment by mikemcquaid** [comment]
It's actually just pretty delayed with the Homebrew/homebrew repository (takes sometimes ~5m) compared to other repos I guess due to the size and activity compared to other GitHub repos.

**Pull request closed without merging**
