### PR TITLE
libgit2 0.22.0

### PR DESCRIPTION
**Pull request by cvrebert**

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Looks like `libgit2-glib` (and maybe `gitfs`) need a `revision` bump: http://bot.brew.sh/job/Homebrew%20Pull%20Requests/19971/version=yosemite/testReport/junit/brew-test-bot/yosemite/test_libgit2_glib/

**Comment by cvrebert** [comment]
The new version has backward-incompatible changes. Not sure how to put an upper-bound on the version depended on by the dependent packages.

**Comment by mikemcquaid** [comment]
> Not sure how to put an upper-bound on the version depended on by the dependent packages.

We can't do this. We'll need to wait until those packages are fixed.

**Comment by cvrebert** [comment]
I am very surprised that Brew has such a significant limitation.

**Pull request closed without merging**
