### PR TITLE
wla-dx: update to 9.6 and set new homepage

### PR DESCRIPTION
**Pull request by martinlindhe**

### CODE REVIEW

**Comment by dunn** [comment]
Thanks for helping us keep things up-to-date! Would you be willing to also add a test while you're at it? [`closure-compiler.rb`](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/closure-compiler.rb) and [`cmake.rb`](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/cmake.rb) are good examples of application tests.

**Comment by martinlindhe** [comment]
@dunn: Thanks, I'll give it a shot

**Comment by martinlindhe** [comment]
Tested like:

"brew test wla-dx"
and
"brew test wla-dx --HEAD"

Is this sufficient?

```
brew test --HEAD wla-dx
==> /usr/local/Cellar/wla-dx/HEAD/bin/wla-gb -o /private/tmp/wla-dx20150724-19344-1lupu3q/test-gb-asm.s
```

```
 brew test wla-dx
Testing wla-dx
==> /usr/local/Cellar/wla-dx/9.6/bin/wla-gb -o /private/tmp/wla-dx20150724-19834-sqq78z/test-gb-asm.s
```

**Comment by dunn** [comment]
Looks great, thank you! Merged in 1acc1db0d7df4e378661906b64b77d648eae86bf.

**Pull request closed without merging**
