### PR TITLE
Moreutils 0.56

### PR DESCRIPTION
**Pull request by QuinnyPig**
Upstream sources of 0.55 aren't present.

### CODE REVIEW

**Comment by DomT4** [comment]
Failed to build:

```
==> make all
clang -O2 -g -Wall    isutf8.c   -o isutf8
clang -O2 -g -Wall    ifdata.c   -o ifdata
clang -O2 -g -Wall    ifne.c   -o ifne
clang -O2 -g -Wall    pee.c   -o pee
ifdata.c:1:10: fatal error: 'error.h' file not found
#include <error.h>
         ^
1 error generated.
make: *** [ifdata] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by QuinnyPig** [comment]
Hmm. This (the CPAN dependency) didn't change as a part of my pull request. I'm wondering if this was broken, but is only now coming to light, or if there's something else going on here.

**Comment by DomT4** [comment]
The `make all` step of `moreutils` is the step throwing the error here. Possibly a build system error, or a parallel build failure. Those would seem the most likely potential candidates. Does it build locally?

**Comment by QuinnyPig** [comment]
I can replicate the error here-- outside of Homebrew. Will talk to upstream. Sorry for the false alarm.

**Comment by QuinnyPig** [comment]
In the interim I've found a working mirror for the 0.55 package, updated the checksums to SHA256, and fixed the URLs for CPAN as per 'brew audit'.

**Pull request closed without merging**
