### PR TITLE
Update bgpq3 to v0.1.27

### PR DESCRIPTION
**Pull request by job**

### CODE REVIEW

**Comment by job** [comment]
I don't know why this fails

**Comment by mikemcquaid** [comment]
It took too long to build. Our CI infrastructure is currently degraded so we'll retry when it's fixed.

**Comment by mistydemeo** [comment]
@BrewTestBot test this please

**Comment by mistydemeo** [comment]
Thanks! For future reference, our preferred commit message format for version bumps is `formula version`, e.g. `bgpq3 0.1.27`. I've adjusted the commit message when pulling.

**Pull request closed without merging**
