### PR TITLE
passpie: Update Formula to 0.3.0

### PR DESCRIPTION
**Pull request by marcwebbie**

### CODE REVIEW

**Comment by tdsmith** [comment]
Tests are failing:

> Testing passpie
==> /usr/local/Cellar/passpie/0.3.0/bin/passpie -D temp_db init --passphrase s3cr3t
WARNING:gnupg:Ignoring '/usr/local/bin/gpg' (path is a symlink)
ERROR:gnupg:Could not find binary for 'gpg'.

Can be be made to like symlinks? :)

**Comment by marcwebbie** [comment]
Strange it is not working anymore. But on the other hand it is good to catch this kind of behavior early on.

I will be updating this pull request soon. ;)

**Comment by marcwebbie** [comment]
@tdsmith Everything looks good again. One question, is there a way to run the test bot using head?

Thanks

**Comment by tdsmith** [comment]
Great! Thanks for the pull request. :tada:  There isn't a way to run our bot against HEAD, sorry. Just for reference, our preferred commit message header is like "somepackage 1.2.3" for version bumps like this. Thanks again!

**Comment by marcwebbie** [comment]
Thanks @tdsmith

**Pull request closed without merging**
