### PR TITLE
scrypt 1.2.0

### PR DESCRIPTION
**Pull request by koenrh**

### CODE REVIEW

**Comment by dunn** [comment]
Any chance of a test, while you're at it? Anything that checks basic functionality would be great!

**Comment by DomT4** [comment]
```ruby
  test do
    (testpath/"test.sh").write <<-EOS.undent
      #!/usr/bin/expect -f
      set timeout -1
      spawn #{bin}/scrypt enc homebrew.txt homebrew.txt.enc
      expect -exact "Please enter passphrase: "
      send -- "Testing\n"
      expect -exact "\r
      Please confirm passphrase: "
      send -- "Testing\n"
      expect eof
    EOS
    chmod 0755, testpath/"test.sh"
    touch "homebrew.txt"

    system "./test.sh"
    assert File.exist?("homebrew.txt.enc")
  end
```

**Comment by mikemcquaid** [comment]
@DomT4 If that works maybe just pull this and add a commit yourself with the test?

**Comment by DomT4** [comment]
Yeah, just about to.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/9ad70d102c3ca74cef77c1fc19a0e5dde3fc5e76. Thank you for your contribution to Homebrew, we appreciate it! :smiley_cat:

**Pull request closed without merging**
