### PR TITLE
Ceylon supports JDK 8

### PR DESCRIPTION
**Pull request by gavinking**
Ceylon 1.1 is actually compatible with JDK 8.

### CODE REVIEW

**Comment by dunn** [comment]
We're running tests in a sandbox now, and it's preventing Ceylon from writing to user home directory:
```
==> /usr/local/Cellar/ceylon/1.1.0/bin/ceylon compile --encoding UTF-8 com.example.helloworld
ceylon compile: com.redhat.ceylon.cmr.api.RepositoryException: Cannot create
Ceylon cache repository directory: /Users/brew/.ceylon/cache
Error: ceylon: failed
```
Could you look into tweaking the test to write to the temporary test directory? Setting `ENV["_JAVA_OPTIONS"] = "-Duser.home=#{env_home}"` at the start of the test might do it.

**Comment by gavinking** [comment]
So wait, @dunn, it's not allowed to write to the cwd either?

**Comment by dunn** [comment]
`testpath` is the directory the tests are run from. I'm not sure what the default is for `--out` in Cylon.

**Comment by gavinking** [comment]
@dunn looks good now.

**Comment by dunn** [comment]
And merged in 0d392986f24505d2af69cc846f694be6ea9be84d, thank you!

**Comment by gavinking** [comment]
Thanks!

**Pull request closed without merging**
