### PR TITLE
sourceforge.jp is now osdn.jp

### PR DESCRIPTION
**Pull request by vszakats**
Plus related updates.

### CODE REVIEW

**Comment by vszakats** [comment]
Error seems unrelated to this update:
```
==> brew audit mecab-unidic						 FAILED
Error: 1 problems in 1 formulae
mecab-unidic:
 * The installation seems to be empty. Please ensure the prefix
is set correctly and expected files are installed.
The prefix configure/make argument may be case-sensitive.
```

**Comment by vszakats** [comment]
`mecab-unidic` build will create these four binary data files:
```
char.bin
matrix.bin
sys.dic
unk.dic
```

**Comment by xu-cheng** [comment]
Looks like `mecab-unidic` will attempt to write file inside `mecab`'s Cellar.
```
May 30 17:09:59 kernel[0]: Sandbox: mkdir(98661) deny file-write-create /Users/xucheng/Coding/Github/homebrew/Cellar/mecab/0.996/lib/mecab
```

This is against Homebrew's policy. @vszakats Can you make `mecab-unidic` as a part of `mecab` formula. Otherwise we should boneyard it.

**Comment by vszakats** [comment]
First I split `mecab-unidic` from this pull, so this can pass and be accepted.

**Comment by mikemcquaid** [comment]
Thanks @vszakats!

**Pull request closed without merging**
