### PR TITLE
sbcl 1.2.15

### PR DESCRIPTION
**Pull request by auvi**
sbcl updated to 1.2.15

### CODE REVIEW

**Comment by dunn** [comment]
womp womp:
```
==> Downloading https://trac.macports.org/export/88830/trunk/dports/lang/sbcl/files/patch-base-target-features.diff
==> Retrying download
==> Downloading https://trac.macports.org/export/88830/trunk/dports/lang/sbcl/files/patch-base-target-features.diff
Error: Failed to download resource "sbcl--patch"
Download failed: https://trac.macports.org/export/88830/trunk/dports/lang/sbcl/files/patch-base-target-features.diff
```
Will re-queue the build when Trac is back on its feet.

**Comment by dunn** [comment]
The SVN server is still up, so you should be able to replace that first patch with `https://svn.macports.org/repository/macports/trunk/dports/lang/sbcl/files/patch-base-target-features.diff`, and so on for the rest.  The SHAs should remain the same.

**Comment by DomT4** [comment]
You will probably need to add `:using => :curl` to any `svn.macports` links to avoid making `svn` checkouts.

**Comment by mikemcquaid** [comment]
Failing `audit` but not sure if that's valid: http://bot.brew.sh/job/Homebrew%20Pull%20Requests/32647/version=yosemite/testReport/junit/brew-test-bot/yosemite/audit_sbcl/

**Comment by DomT4** [comment]
Trac is back up, so I think we're fine to revert the links here. The audit warning is accurate in some cases, I've stumbled across a decent number of things in trunk that have different checksums from the expected one.

**Comment by auvi** [comment]
okay I'll revert the links to trac when I can get in front of my computer.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/a089a877b05c8432f6edba85c0f8d49f025f8353. Thank you for your contribution to Homebrew, we appreciate it! :smiley_cat:

**Pull request closed without merging**
