### PR TITLE
wine 1.7.44 --devel

### PR DESCRIPTION
**Pull request by makigumo**

### CODE REVIEW

**Comment by makigumo** [comment]
Seems like ML's notorious ```clang: error: unable to execute command: Segmentation fault: 11``` has appeared again.

**Comment by bfontaine** [comment]
The build succeeds on ML and Yosemite but fails on Mavericks: http://bot.brew.sh/job/Homebrew%20Pull%20Requests/26957/version=mavericks/testReport/junit/brew-test-bot/mavericks/install___devel_wine/

**Comment by jacknagel** [comment]
This is an intermittent segfault, last time I just kept starting new builds until it passed.

**Comment by DomT4** [comment]
Went green after Jack kicked the bot.

Merged in https://github.com/Homebrew/homebrew/commit/0099e5e5da718a4608fe78f0b9a5d34068308059. Thanks for your contribution to Homebrew, we appreciate it! :smiley_cat:.

**Pull request closed without merging**
