### PR TITLE
openssl: Use native openssl in post_install()

### PR DESCRIPTION
**Pull request by docwhat**
This is faster and allows extra checking in the future if we want.

We can also pretty up the `certs.pem`.

I'll submit some more changes to add the Subject into the `cert.pem` so
you can tell if a specific certificate is there or not.

How would you guys feel about adding the work around for the jruby-openssl bug
number 56?

https://github.com/jruby/jruby-openssl/issues/56#issuecomment-123474865

### CODE REVIEW

**Comment by DomT4** [comment]
I'm not sure writing it this way makes it any easier for the "casual" contributor to understand what on earth we're doing, which is something I worry about.

I'm fairly against removing certificates which are not yet valid. It's not uncommon for people to not regenerate their PEM file outside of Homebrew's OpenSSL updates, which barring security problems upstream or changes downstream don't come around massively often.

If a cert comes online during that time and starts being relied on, people are going to see difficult to debug failure. Expecting people to periodically do `brew postinstall openssl` to regenerate that PEM isn't great UX, and the future ban could do that.

**Comment by docwhat** [comment]
Well it's easy to remove that `reject`. 

I don't like the current UX either. If you have a suggestion, I'd happily implement it. E.g. Moving it to an external command or something. 

I feel like the pure ruby version is easier to understand because the `openssl` command line flags are as opaque as mud.

**Comment by mikemcquaid** [comment]
> This is faster

How much faster?

**Comment by DomT4** [comment]
> I don't like the current UX either. If you have a suggestion, I'd happily implement it.

There's not a better one really. Either people do `brew postinstall openssl` every so often, or they replace the PEM every so often manually. We replace it every time OpenSSL is updated, but I'm not going to start automatically regenerating the PEM outside of that cycle. Drop the kill "Not yet valid" certs part and I'm happy with the status quo.

I presume the current failure here is the need to add `require "openssl"` to the formula. It probably isn't naturally invoked by Ruby.

**Comment by DomT4** [comment]
Going to pass on this for now. Thanks for the submission though!

**Pull request closed without merging**
