### PR TITLE
apt-cacher-ng 0.8.8

### PR DESCRIPTION
**Pull request by ericvw**
Notable changes from upstream's CHANGELOG:
  * FIX: check-all checkbox in cleanup assistant functionality, and minor HTML
    format fixes
  * Refactored setting of complex option, added their printing with acngtool

### CODE REVIEW

**Comment by dunn** [comment]
The build is failing on Mavericks; http://bot.brew.sh/job/Homebrew%20Pull%20Requests/39204/version=mavericks/testReport/junit/brew-test-bot/mavericks/install_apt_cacher_ng/

**Comment by ericvw** [comment]
Thanks for the update.  I will take a look and see what is going on.

**Comment by ericvw** [comment]
What is recommended for testing with the Mavericks toolchain when your host OS is El Capitan?  I think I know the root issue, but I want to validate my hypothesis first before updating the PR and potentially submitting a patch to upstream.

**Comment by ericvw** [comment]
I was able to `brew tap homebrew/versions && brew install llvm35` to get (roughly) the same toolchain as Xcode 6.2 to reproduce the issue.

**Comment by DomT4** [comment]
@BrewTestBot test this please

**Comment by ericvw** [comment]
Re-pushed an amended commit that includes a patch.  Details are in the commit message and in the comments where the upstream source is patched for `<= :mavericks`.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/ee0f29124a549e63fa9353f602732b452b604fee. Thank you for another contribution to Homebrew @ericvw! :smiley_cat:

**Pull request closed without merging**
