### PR TITLE
cabal-install 1.22.0.1

### PR DESCRIPTION
**Pull request by pthariensflame**
Also modernize the formula and its contents a bit.

### CODE REVIEW

**Comment by vszakats** [comment]
Can you please change `homepage` to use https?

**Comment by pthariensflame** [comment]
@vszakats Done!

**Comment by vszakats** [comment]
Thanks!

**Comment by tdsmith** [comment]
Thanks for the pull request! 🎉 Homebrew depends on contributions from community members like you and we're grateful for your support.

**Pull request closed without merging**
