### PR TITLE
updating osquery to 1.3.0

### PR DESCRIPTION
**Pull request by marpaia**
Bumping the version of osquery in homebrew to version 1.3.0

### CODE REVIEW

**Comment by marpaia** [comment]
Jenkins seems to be failing on the clone of this but I'm not really sure why. It seems to be failing here:

```
==> Patching
Error: inreplace failed
CMakeLists.txt:
  expected replacement of "-Wl,-all_load" with "-Wl,-force_load"
```

We do add `-Wl,-force_load` as a linker argument here: https://github.com/facebook/osquery/blob/master/CMakeLists.txt#L10

In between 1.2.1 and 1.3, we changed `all_load` to be `force_load`, but that shouldn't be a patch/merge conflict?

Is there any additional insight into what the build system is doing there?

**Comment by marpaia** [comment]
Here's the commit where `all_load` was changed to `force_load`: https://github.com/facebook/osquery/commit/20259af57dc1429b9aec9b6ceb5804b9dfeef77c

**Comment by jacknagel** [comment]
The error indicates that a textual replacement in the formula is failing; if it was fixed upstream, then the relevant code needs to be removed from the formula.

**Comment by jacknagel** [comment]
To be more specific, [these lines](https://github.com/Homebrew/homebrew/blob/d2d470f0088086a817adc6565c4783a64fdf0949/Library/Formula/osquery.rb#L39-44) need to be deleted.

**Comment by marpaia** [comment]
Bah, facepalm, totally forgot that was happening in the formula. Many thanks, @jacknagel.

**Comment by mikemcquaid** [comment]
Needs patched to not try and write to `/var`: http://bot.brew.sh/job/Homebrew%20Pull%20Requests/20234/version=yosemite/testReport/junit/brew-test-bot/yosemite/install_osquery/

**Comment by marpaia** [comment]
Got it, fixed on master (https://github.com/facebook/osquery/commit/b4a2ca1afa33b769b409d815d31bdcfef9939c7d) and cut a new tag. Should be good now (fingers crossed).

**Comment by marpaia** [comment]
Build passed, just squashed into one commit.

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! For future reference the preferred commit message format for simple version updates is `osquery 1.3.1`.

**Comment by marpaia** [comment]
Cool, thanks @mikemcquaid!

**Pull request closed without merging**
