### PR TITLE
Gauge update 0.0.5

### PR DESCRIPTION
**Pull request by prateekbaheti**

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Fails to build: http://bot.brew.sh/job/Homebrew%20Pull%20Requests/22283/version=yosemite/testReport/junit/brew-test-bot/yosemite/install_gauge/

**Comment by prateekbaheti** [comment]
fixed now

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

For future reference the preferred commit message format for simple version updates is `gauge 0.0.5`.

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
