### PR TITLE
libjson-rpc-cpp: deparallelize build

### LINKED ISSUE #49278: libjson-rpc-cpp --build-from-source failed to build on 10.11.3
https://gist.github.com/e0add90085c6680fe43e

### PR DESCRIPTION
**Pull request by ilovezfs**
Deparallelize the build.
Add the head url.

Fixes #49278

### CODE REVIEW

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/52fc769cd7edf2e855e94c4742a45a64a67eb432. Thanks again @ilovezfs!

**Comment by DomT4** [comment]
(Also if you could report the need to do this upstream I'd greatly appreciate that :wink:)

**Comment by ilovezfs** [comment]
@DomT4 As requested :) https://github.com/cinemast/libjson-rpc-cpp/issues/153

**Comment by DomT4** [comment]
Thanks! Added it to the formula in https://github.com/Homebrew/homebrew/commit/1ab62c4344f891f046cde3b6c420ef8940956585.

**Pull request closed without merging**
