### PR TITLE
add Keg#empty_installation?

### PR DESCRIPTION
**Pull request by xu-cheng**
Avoid using `FormulaAuditor` in `FormulaInstaller`.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
:+1:

**Comment by bfontaine** [comment]
Do you mind adding a test for it? :wink:

**Comment by xu-cheng** [comment]
> Do you mind adding a test for it? :wink:

I can, but in a new PR.

**Comment by xu-cheng** [comment]
@bfontaine Here you are https://github.com/Homebrew/homebrew/commit/fe0b4b40b4602b5d91d22f1efa6eef97ece5d776
:smile:

**Comment by bfontaine** [comment]
Thank you!

**Pull request closed without merging**
