### PR TITLE
Update imagemagick to 6.9.2-7

### PR DESCRIPTION
**Pull request by MartinDelille**
Since 6.9.2-6 return a 404 error

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

For future reference the preferred commit message format for simple version updates is `imagemagick 6.9.2-7`.

**Comment by MartinDelille** [comment]
I realized I forgot to update the mirror link. Shall I make a new PR?

**Comment by mikemcquaid** [comment]
I'll do it.

**Comment by mikemcquaid** [comment]
4779064

**Pull request closed without merging**
