### PR TITLE
pylucene: allow Java 1.8.

### LINKED ISSUE #39492: formula pylucene asks for pre-req java 1.7 but 1.8 already installed
PyLucene brew says Java 1.7 is required. But Java 1.8 is already installed via the Oracle JDK installer.
Also the caskroom would install 1.8 anyway. The formula should accept both 1.7 and 1.8:
http://jaxenter.com/apache-lucene-and-solr-4-8-join-the-java-8-compatibility-club-107748.html

Brew install error:

```
$ brew install pylucene
pylucene: Java 1.7 is required to install this formula.
You can install with Homebrew Cask:
  brew install Caskroom/cask/java

You can download from:
  http://www.oracle.com/technetwork/java/javase/downloads/index.html
Error: An unsatisfied requirement failed this build.
```

Java is already installed:

```
$ java -version
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
```

Env variables are properly set:

```
export JAVA_HOME=`/usr/libexec/java_home`
export JCC_JDK=$JAVA_HOME

$ export | grep JAVA
declare -x JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home"

$ export | grep JCC
declare -x JCC_JDK="/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home"
```

### PR DESCRIPTION
**Pull request by coady**
Fixes #39492.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Any idea if there's a way to convince this not to write to `/Users/brew/.ant/lib`?

**Comment by acoady** [comment]
If `ant` is already installed `--with-ivy`, then the check will pass.

**Comment by mikemcquaid** [comment]
We need to work out some sort of workaround. Can we set an environment variable to tell Ant to write elsewhere?

**Comment by bfontaine** [comment]
@BrewTestBot test this please.

**Comment by dunn** [comment]
http://bot.brew.sh/job/Homebrew%20Pull%20Requests/33858/

**Comment by coady** [comment]
Updated to no longer write to ~/.ant or ~/.ivy2.

**Comment by dunn** [comment]
Getting this error when testing the bottle installation:
```
🌰  brew test -v pylucene
Testing pylucene
==> python -c import lucene; assert lucene.initVM()
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/lucene/__init__.py", line 2, in <module>
    import os, _lucene
ImportError: dlopen(/usr/local/lib/python2.7/site-packages/lucene/_lucene.so, 2): Library not loaded: @rpath/libjava.dylib
  Referenced from: /usr/local/lib/python2.7/site-packages/lucene/_lucene.so
  Reason: image not found
```
Configuration:
```
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew.git
HEAD: 31748733d6c4038c8deb958ef40a16e038e561fa
Last commit: 2 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
OS X: 10.11-x86_64
Xcode: 7.0.1
CLT: N/A
Clang: 7.0 build 700
X11: 2.7.7 => /opt/X11
System Ruby: 2.0.0-p645
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.2.3/bin/ruby
Java: 1.8.0_20

**Comment by bfontaine** [comment]
Ping re Alex’ comment.

**Comment by dunn** [comment]
@BrewTestBot test this please

**Comment by bfontaine** [comment]
@BrewTestBot test this please.

**Comment by DomT4** [comment]
Closing as dead. Please do feel free to reopen if you wish to with the comments addressed. Thank you for your submission to Homebrew :heart:

**Pull request closed without merging**
