### PR TITLE
Update open-mpi.rb

### PR DESCRIPTION
**Pull request by janmolnar**
Added fortran compiler awareness

### CODE REVIEW

**Comment by mikemcquaid** [comment]
What is this fixing?

**Comment by janmolnar** [comment]
If you set the FC Environment Variable to eg ifort then open mpi is built against that fortan compiler

**Comment by jacknagel** [comment]
What does passing it to configure accomplish that is not accomplished by it already being set in the ENV var?

**Comment by DomT4** [comment]
Jack's question needs answering before this can be considered for merge, Thanks!

**Comment by DomT4** [comment]
Presuming dead.

**Pull request closed without merging**
