### PR TITLE
scala 2.12.0-M3 (devel)

### PR DESCRIPTION
**Pull request by AtkinsChang**
scala 2.12.0-M2, java version requirement to 1.8+.

The release note of 2.12.0-M2:
```
Beginning with 2.12.0-M2, the Scala 2.12 series targets Java 8. Programs written in Scala 2.12, including the Scala 2.12 compiler, can only be executed on Java 8 or newer.
```

### CODE REVIEW

**Comment by dunn** [comment]
Any idea why this only happened on Mavericks? 
```
        Testing scala
==> /usr/local/Cellar/scala/2.12.0-M2/bin/scala /private/tmp/scala20150716-65428-1ltwcxu/hello.scala
error: error while loading Object, Missing dependency 'object scala in compiler mirror', required by /Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/jre/lib/rt.jar(java/lang/Object.class)
error: fatal error: object scala in compiler mirror not found.
two errors found
Error: scala: failed
<0> expected but was
<1>.
```

**Comment by AtkinsChang** [comment]
I can't reproduce it with java 1.8.0_40 on my mac.
```
Testing scala
==> /usr/local/Cellar/scala/2.12.0-M2/bin/scala /private/tmp/scala20150717-64615-1g6q7il/hello.scala
```

**Comment by bfontaine** [comment]
Ping?

**Comment by AtkinsChang** [comment]
Still can't re-produce the error for debugging. I pass the test on my mac (10.11) with same idk (1.8.0_60).

**Comment by dunn** [comment]
Did you try installing and testing with `--sandbox`?

**Comment by AtkinsChang** [comment]
```
$ brew test --devel --verbose --sandbox  /Users/atkins/Code/github/homebrew_atkins/Library/Formula/scala.rb
Testing scala
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20151019-38023-11aqr0s.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Library/Homebrew -- /usr/local/Library/Homebrew/test.rb /Users/atkins/Code/github/homebrew_atkins/Library/Formula/scala.rb --devel --verbose --sandbox --devel
==> /usr/local/Cellar/scala/2.12.0-M3/bin/scala /private/tmp/scala20151019-38024-v320ed/hello.scala
```

**Comment by dunn** [comment]
Installed with the sandbox too?  That's probably not what's happening here, but I'm out of ideas.

**Pull request closed without merging**
