### PR TITLE
treeline 2.0.0

### PR DESCRIPTION
**Pull request by dunn**

### CODE REVIEW

**Comment by dunn** [comment]
`with-python3` isn't getting passed down to sip:
```
==> python3 configure.py --confirm-license --bindir=/usr/local/Cellar/pyqt/4.11.3/bin --destdir=/usr/local/Cellar/pyqt/4.11.3/lib/python3.4/site-packages --sipdir=/usr/local/Cellar/pyqt/4.11.3/share/sip
Traceback (most recent call last):
  File "configure.py", line 32, in <module>
    import sipconfig
ImportError: No module named 'sipconfig'
```
Should I just make sip an explicit dependency in order to make the `with-python3` explicit?

**Comment by mikemcquaid** [comment]
> Should I just make sip an explicit dependency in order to specify with-python3 directly?

Yeh, probably, thanks!

**Comment by dunn** [comment]
Weird:
```
==> ./install.py -p/usr/local/Cellar/treeline/2.0.0
Checking dependencies...
  Python Version 3.4.3 -> OK
  PyQt not found -> Sorry, PyQt 4.x is required and must be built for Python 3
```

**Comment by dunn** [comment]
Removed all the dependencies and still couldn't replicate this.

**Comment by DomT4** [comment]
@tdsmith may have some ideas on this.

**Pull request closed without merging**
