### PR TITLE
emacs-clang-complete-async: audit fixes

### PR DESCRIPTION
**Pull request by nijikon**

### CODE REVIEW

**Comment by DomT4** [comment]
Note to self: needs :baby_bottle:

**Comment by nijikon** [comment]
What is this note to self about if I may know? :)

**Comment by DomT4** [comment]
The formula currently lacks bottles, but has a compile stage and consequently needs them. As you've probably noticed we've added DSL for not building bottles and applied that to many formulae that require no compile, but everything else is supposed _in an ideal world_ to be bottled.

Long-term our goal is for people to be able to run Homebrew without any Xcode or CLT installation if they wish to and to get there we need to bottle pretty much everything that invokes a build tool, which in this case is `make` from the system.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/39684d6e774da52d2b399ba9cf40a3d869fa0467. Thanks @nijikon!

**Comment by nijikon** [comment]
@DomT4 Thanks for explaining!

**Pull request closed without merging**
