### PR TITLE
keg: explicitly create cmake folder under lib

### PR DESCRIPTION
**Pull request by drbenmorgan**
Packages supporting CMake may install configuration files for use with CMake's `find_package` command. One location recommended by CMake for installing these is `<prefix>/lib/cmake` which is not unique across packages. This may cause issues for Formulae using this location if more than one Keg tries to create links under this location.

As with pkg-config, this fix explicitly creates the `lib/cmake` folder when linking a Keg that has installed folders/files under this location.

I haven't added a test for this in `test_keg.rb` like `test_pkgconfig_is_mkpathed` as other created folders aren't tested. However, I'll add this if it's required.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
A test would be great if you wouldn't mind.

CC other @Homebrew/owners to check there's no objections but this makes sense to me.

**Comment by drbenmorgan** [comment]
Test added in `test_keg.rb`, basically a carbon copy of the one for explicit creation of the `pkgconfig` folder. This runs through `brew tests` o.k. for me.

**Comment by xu-cheng** [comment]
:+1:

**Comment by xu-cheng** [comment]
Thanks for the pull request! 🎉 Homebrew depends on contributions from community members like you and we're grateful for your support.

**Pull request closed without merging**
