### PR TITLE
caveats: add instruction on let spotlight index app bundles

### PR DESCRIPTION
**Pull request by xu-cheng**
credit: @elyscape @zzamboni

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Can we make it more specific so e.g. `/usr/local/Cellar` instead? There's an awful lot in `/usr` people probably don't want indexed.

**Comment by xu-cheng** [comment]
No, we can't. Because the only thing which is hidden is `/usr`. Once a root is hidden, all the files in the leaves wouldn't be indexed.

**Comment by mikemcquaid** [comment]
I'm probably :-1: on this just because I think it's a relatively niche case with surprising results.

**Comment by xu-cheng** [comment]
This is by far the simplest and cleanest way to make spotlight index app bundles. And this is just a  caveat. It's up to users to decide what they want.

**Comment by mikemcquaid** [comment]
Yeh, the problem there is that a lot of users will end up running it without understanding what it does and what the effects will be. I'd prefer we work on getting the `linkapps` stuff to be improved instead so that spotlight can use that.

**Comment by xu-cheng** [comment]
> There's an awful lot in /usr people probably don't want indexed.

Or ask users to unhide `/usr`, then hide everything except `/usr/local/opt` or `/usr/local/Cellar`.

**Comment by xu-cheng** [comment]
> I'd prefer we work on getting the linkapps stuff to be improved instead so that spotlight can use that.

That approach isn't too promise. Creating alias without duplicated items is easy. Or we have to do is create an alias in a temp folder then move it into the right place. However to get the origin of an alias file is hard. And this is important in `unlinks`.

**Comment by mikemcquaid** [comment]
Is there another open PR for that? I think the unlinking isn't worth worrying about too much, to be honest. It's OK to just remove aliases/symlinks on unlinking even if we didn't create them.

**Comment by xu-cheng** [comment]
> Is there another open PR for that.

No, I just closed mine. If you want, I can create a new one for linking using alias. But to be honest, I'm not sure that leaving broken alias as it is or removing broken alias is the right approach.

**Comment by mikemcquaid** [comment]
We can just overwrite them every time, no?

**Comment by mikemcquaid** [comment]
Or does the alias need updated every time the package is upgraded?

**Comment by xu-cheng** [comment]
Usually, we don't need update them every time. But there are times such as a package changes its app bundle. Or a user want to unlink apps (maybe after he or she uninstalled it, hence broken links.)

If we leave the broken alias as it is, we may end up with creating lots of junk files. If we just remove them general, we may false remove the alias created by users themselves or other program. In both way, it's unreliable.

**Comment by mikemcquaid** [comment]
Honestly I think users would prefer something that works sometimes than never works. Homebrew doesn't have a good story around clearing stuff up at `uninstall` time so I'm not hugely worried about that.

**Comment by mikemcquaid** [comment]
As we can always clean up on future `linkapps`, `unlinkapps` and `cleanup` runs.

**Comment by elyscape** [comment]
I think a better option might be to change the default install location from `/usr/local/Cellar` to `/opt/homebrew/Cellar`.

**Comment by xu-cheng** [comment]
> As we can always clean up on future linkapps, unlinkapps and cleanup runs.

Current problem is without knowing the alias origin we will never clean up them.

**Comment by mikemcquaid** [comment]
> I think a better option might be to change the default install location from /usr/local/Cellar to /opt/homebrew/Cellar.

That's never going to happen.

**Comment by mikemcquaid** [comment]
> Current problem is without knowing the alias origin we will never clean up them.

We can just delete them if the package is uninstalled.

**Comment by xu-cheng** [comment]
> We can just delete them if the package is uninstalled.

But you don't know which package do they belong to? Again origin problem.

**Comment by xu-cheng** [comment]
To be informative, there are two ways to know the origin of a broken alias.
* OS X Object-C API. It's simple to use. However, it requires us to ship binary files with homebrew.
* Read alias file directly in binary form. Dependency free but no public spec available.

**Comment by mikemcquaid** [comment]
Hmm, yeh, tricky.

**Comment by xu-cheng** [comment]
> OS X Object-C API. It's simple to use. However, it requires us to ship binary files with homebrew.

Or make it as dependency. When unlinking apps, we need to install a formula first?

**Comment by xu-cheng** [comment]
> Hmm, yeh, tricky.

That's why I think this PR is best solution so far.

**Comment by mikemcquaid** [comment]
I don't think it is as it brings in a bunch of other side-effects and changes default system behaviour.

**Comment by xu-cheng** [comment]
I just come up with a new idea. Instead trying to read alias origin, we store the origin in the first place when we create them. Maybe a json file inside the cellar. What's your opinion?

**Comment by mikemcquaid** [comment]
Sounds good.

**Comment by xu-cheng** [comment]
Close this PR to pursue my new idea

**Comment by DomT4** [comment]
It's not Ruby, but you can get the Finder via a shell to cough out the Alias origin path. There's a script here which may be useful referencing: [Clicky](http://hints.macworld.com/article.php?story=20021218054210294)

**Comment by xu-cheng** [comment]
@DomT4 I'm well known such or similar script. It won't work for broken alias(alias file whose origin file is deleted or unreachable).

**Comment by DomT4** [comment]
Aye, I know. Could wrap it in a ruby script and then assert_match the output and rm the alias if no origin path is detected. Meh. I'll leave you to it.

**Comment by elyscape** [comment]
> That's never going to happen.

Why's that?

**Comment by mikemcquaid** [comment]
> Why's that?

It was one of the original Homebrew design choices and all our binary packages are built for that location and because none of the maintainers see a good reason to try and migrate everyone.

**Comment by elyscape** [comment]
> It was one of the original Homebrew design choices and all our binary packages are built for that location and because none of the maintainers see a good reason to try and migrate everyone.

That makes sense.  I'll see if I can work out another solution to the issue that doesn't require running `chflags`, then.

**Comment by elyscape** [comment]
Okay, after doing a bunch of research, I'm pretty sure that using directory hardlinks (and falling back to symlinks when they aren't possible, e.g. because /Applications and the Cellar are on different volumes) are the way to go.  These can be created directly from Ruby with `File::link()`.  Aliases are a bad solution because Spotlight sorts them into the Other section:

Spotlight sorting an alias into Other

There is precedent to using directory hard links; Time Machine uses them.  So long as we're careful about removing them with `File::unlink()` before upgrading or uninstalling, it should be fine.  I'll start on a PR shortly.

**Pull request closed without merging**
