### PR TITLE
osquery 1.7.2

### PR DESCRIPTION
**Pull request by theopolis**
### All Submissions:

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew/pulls) for the same update/change?

### CODE REVIEW

**Comment by DomT4** [comment]
Failed to build on all three platforms, which is interesting because https://github.com/Homebrew/homebrew/pull/50132 didn't fail a few days ago. Hmm. Thoughts on that @theopolis & @ilovezfs?

**Comment by ilovezfs** [comment]
@DomT4 @theopolis This is why #50132 includes cpp-netlib 0.12.0-rc1 as well. Also, 1.7.2 is pre-release, which is why #50132 has it in devel.

@DomT4 Hence, https://github.com/Homebrew/homebrew/pull/50132#issuecomment-199875253

**Comment by ilovezfs** [comment]
@theopolis Is 1.7.2 correct for Homebrew :stable despite the note at https://github.com/facebook/osquery/releases? I don't personally object to moving it to :stable but wasn't sure based on that note.

**Comment by theopolis** [comment]
You can mark it :stable, I keep pre-release for a 24/48 hour period while I deploy and test on a larger scale than 3 build hosts. :) I will update that note and remove the checkbox later tonight, as well as fill in the release notes.

**Comment by ilovezfs** [comment]
@theopolis Thanks! I'll close #50132 in favor of this PR and one just bumping cpp-netlib.

**Comment by ilovezfs** [comment]
@DomT4 @theopolis if #50375 is merged first and then CI retriggered here, this should pass.

**Comment by tdsmith** [comment]
It would be unusual for us to land a -rc version (of cpp-netlib) in stable. The last netlib candidate was tagged about two weeks ago. Can you ask them if they're ready to release?

**Comment by DomT4** [comment]
:+1: on Tim's comment.

**Comment by theopolis** [comment]
A non RC release is a question for @deanberris. From the OS X client perspective I've tested on 10 thousand+ machines and everything is working ok. Also keep in mind, in Homebrew osquery is the only forward dependency.

Alternatively, @ilovezfs, can you mark 1.7.2 as dependent on the :devel cpp-netlib? If it seems there's blockage we can forgo adding 1.7.2 for now.

**Comment by DomT4** [comment]
> Alternatively, @ilovezfs, can you mark 1.7.2 as dependent on the :devel cpp-netlib?

At present we don't support mandating people install `devel` or `HEAD` versions of a dependency.

**Comment by ilovezfs** [comment]
@DomT4 Unless you want to merge 0.12.0-rc1 as stable (which would be my recommendation, whence the PR), maybe 0.12.0-rc1 should be vendored into this formula?

**Comment by DomT4** [comment]
It'd be nice to at least ask upstream if they're ready to go stable yet before we start jumping around alternatives.

**Comment by ilovezfs** [comment]
@DomT4 @theopolis https://github.com/cpp-netlib/cpp-netlib/issues/620

**Comment by ilovezfs** [comment]
Upstream has responded:
>Hi -- The only showstoppers are documentation updates. As its the Easter long weekend here down under, I intend to get back to the documentation updates around Wednesday. Hopefully by end of the week we'll have a 0.12.0-rc2 that will be -final after another round of testing.
>
>Does that work?

(https://groups.google.com/d/msg/cpp-netlib/wKwJ2vZUXjs/2usy51VhCAAJ)

@DomT4 @tdsmith So sounds like merging https://github.com/Homebrew/homebrew/pull/50375 as `stable` should be fine for the time being, no?

**Comment by theopolis** [comment]
@ilovezfs I may have an alternative. Technically osquery is API compatible with 0.11 but CMake expects 0.12, thankfully without forcing an exception otherwise. If we add the correct linker flags in the brew formula we can build 1.7.2+ with 0.11. Give me a few to play around with the build.

**Comment by ilovezfs** [comment]
@theopolis Cool, thanks

**Comment by tdsmith** [comment]
@ilovezfs That sounds like a reason to wait for a release to me :) Sorry to be a stick in the mud; glad there's a workaround to try.

**Comment by ilovezfs** [comment]
RC2 which will then become final is now in the works here: https://github.com/cpp-netlib/cpp-netlib/pull/622

**Comment by ilovezfs** [comment]
https://github.com/Homebrew/homebrew/pull/50375 updated with 0.12.0-rc2

**Comment by ilovezfs** [comment]
I'm sure this is already known to @theopolis but same issue for 1.7.3
```
==> cmake . -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFI
==> make
Last 15 lines from /Users/joe/Library/Logs/Homebrew/osquery/05.make:
      boost::detail::thread_data_base::thread_data_base() in libosquery_additional.a(tls.cpp.o)
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "boost::thread::join_noexcept()", referenced from:
      boost::network::http::impl::async_client<boost::network::http::tags::http_async_8bit_udp_resolve, 1u, 1u>::wait_complete() in libosquery_additional.a(tls.cpp.o)
  "boost::thread::start_thread_noexcept()", referenced from:
      boost::thread::start_thread() in libosquery_additional.a(tls.cpp.o)
  "boost::thread::detach()", referenced from:
      boost::thread::~thread() in libosquery_additional.a(tls.cpp.o)
  "boost::thread::native_handle()", referenced from:
      boost::network::http::impl::async_client<boost::network::http::tags::http_async_8bit_udp_resolve, 1u, 1u>::wait_complete() in libosquery_additional.a(tls.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [osquery/osqueryi] Error 1
make[1]: *** [osquery/CMakeFiles/shell.dir/all] Error 2
make: *** [all] Error 2

READ THIS: https://git.io/brew-troubleshooting


```

Any reason not to just rename this PR and update with the 1.7.3 tag and revision?

**Pull request closed without merging**
