### PR TITLE
verilator 3.872

### PR DESCRIPTION
**Pull request by dunn**

### CODE REVIEW

**Comment by dunn** [comment]
ML bot timed out: 
```
        Testing verilator
==> /usr/local/Cellar/verilator/3.872/bin/verilator -Wall --cc test.v --exe test.cpp
Failed to execute: /usr/local/Cellar/verilator/3.872/bin/verilator
Error: verilator: failed
Failed executing: /usr/local/Cellar/verilator/3.872/bin/verilator -Wall --cc test.v --exe test.cpp
/usr/local/Library/Homebrew/formula.rb:885:in `system'
/usr/local/Library/Homebrew/formula.rb:842:in `open'
/usr/local/Library/Homebrew/formula.rb:842:in `system'
/usr/local/Library/Formula/verilator.rb:44:in `test'
/usr/local/Library/Homebrew/formula.rb:785:in `run_test'
/usr/local/Library/Homebrew/extend/fileutils.rb:17:in `mktemp'
/usr/local/Library/Homebrew/formula.rb:781:in `run_test'
/usr/local/Library/Homebrew/test.rb:28
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/timeout.rb:67:in `timeout'
/usr/local/Library/Homebrew/test.rb:27
```
Odd since the entire test takes under 3 seconds on Yosemite, for me.

**Comment by mikemcquaid** [comment]
Kicked off the build again, let's see what happens.

**Comment by bfontaine** [comment]
Same result.

**Comment by mikemcquaid** [comment]
Might want to verify this software actually works on 10.8?

**Comment by dunn** [comment]
Trying to open a ticket on their site but having trouble just making an account 😾

The documentation makes no mention of OSX at all, though, so the developers may not know that it builds on the Mac at all.

**Comment by mistydemeo** [comment]
Testing on a 10.6 machine, verilator itself installed fine and works, it's just the test that's failing.

**Comment by mistydemeo** [comment]
It looks like the issue is the shebang:

```shell
: # -*-Mode: perl;-*- use perl, wherever it is
```
This is accepted by the shell, but Ruby 1.8's `exec` rejects it - hence the test failure. Replacing the call with `system "/usr/bin/perl", # ...` works fine.

**Comment by dunn** [comment]
Thanks!

Should've added a comment explaining, huh...

**Comment by mistydemeo** [comment]
Thanks!

**Pull request closed without merging**
