### PR TITLE
offline-imap 6.6.1

### PR DESCRIPTION
**Pull request by nijikon**

### CODE REVIEW

**Comment by nijikon** [comment]
Homebrew/homebrew#42946

**Comment by nijikon** [comment]
@mikemcquaid  What can we do with "GitHub fork (not canonical repository)" (https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/cmd/audit.rb#L510) error?

**Comment by DomT4** [comment]
Ignore it, or whitelist it hackily.

**Comment by nijikon** [comment]
Maybe we could change that to warning for now?

**Comment by mikemcquaid** [comment]
Thanks @nijikon! Don't worry about the warning, I'll file an issue upstream.

**Comment by mikemcquaid** [comment]
It's no longer a fork.

**Pull request closed without merging**
