### PR TITLE
Update rethinkdb to 2.1.5

### PR DESCRIPTION
**Pull request by mbrevda**

### CODE REVIEW

**Comment by mbroadst** [comment]
how can I help with this :smile:

**Comment by mbrevda** [comment]
@mbroadst get the tests to pass :)

**Comment by DomT4** [comment]
The build failure on all three tested platforms is:

```
   [402/402] LD build/release_clang/rethinkdb
Undefined symbols for architecture x86_64:
  "_u_charType_55", referenced from:
      std::__1::__function::__func<std::__1::__wrap_iter<char const*> ql::find_non_combining<std::__1::__wrap_iter<char const*> >(std::__1::__wrap_iter<char const*>, std::__1::__wrap_iter<char const*>)::'lambda'(char32_t), std::__1::allocator<std::__1::__wrap_iter<char const*> ql::find_non_combining<std::__1::__wrap_iter<char const*> >(std::__1::__wrap_iter<char const*>, std::__1::__wrap_iter<char const*>)::'lambda'(char32_t)>, bool (char32_t)>::operator()(char32_t&&) in string.o
  "_u_isUWhiteSpace_55", referenced from:
      ql::is_whitespace_character(char32_t) in string.o
      std::__1::__function::__func<std::__1::__wrap_iter<char const*> ql::find_non_space<std::__1::__wrap_iter<char const*> >(std::__1::__wrap_iter<char const*>, std::__1::__wrap_iter<char const*>)::'lambda'(char32_t), std::__1::allocator<std::__1::__wrap_iter<char const*> ql::find_non_space<std::__1::__wrap_iter<char const*> >(std::__1::__wrap_iter<char const*>, std::__1::__wrap_iter<char const*>)::'lambda'(char32_t)>, bool (char32_t)>::operator()(char32_t&&) in string.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [build/release_clang/rethinkdb] Error 1
make: *** [make] Error 2
```

**Comment by danielmewes** [comment]
Note that we are temporarily pulling RethinkDB 2.1.5 from our repositories because some users are experiencing crashes with it (https://github.com/rethinkdb/rethinkdb/issues/4917).
So I recommend not merging this yet.

We'll also investigate the build failure. It's probably related to a change in how we build ICU in this release.

**Comment by larkost** [comment]
I suspect that the problem is on line 17 of the pull request. As of [this version](https://github.com/rethinkdb/rethinkdb/issues/4602) RethinkDB now always uses the version of `icu` supplied by `v8`. I was the one who made this change, and it just turned out to be the best solution after the change in how `DYLD_LIBRARY_PATH` changed in 10.11.

If you remove `depends_on "icu4c"` (line 17) from the recipe it should work (at least it does for me).

**Comment by mbrevda** [comment]
Thanks @larkost, local builds work for me, too. Waiting on travis now

**Comment by mbroadst** [comment]
@mbrevda it does seem that we should hold off on merging this until rethink actually releases 2.1.5 again, the sha will change. At the moment it appears the release has been pulled from the ubuntu repo at least

**Comment by mbrevda** [comment]
Definitely should hold off! I just wanted to ensure the pieces are in place.

**Comment by DomT4** [comment]
Have tagged this `upstream issue` so it doesn't get accidentally merged. Let us know when this is good for review.

**Comment by danielmewes** [comment]
@mbrevda The updated https://download.rethinkdb.com/dist/rethinkdb-2.1.5-2.tgz is now available.

**Comment by mbrevda** [comment]
Thanks, I'm testing it local first. I'll (hopefully) push shortly.

**Comment by mbrevda** [comment]
Is Travis based on the West coast? Seems to still be sleeping...

**Comment by bfontaine** [comment]
@mbrevda Don’t worry about the Travis build; only the “default” one is important here.

**Comment by mbrevda** [comment]
@bfontaine thanks, this is ready to be merged then (upstream was fixes, this is based on their rerelease)

**Comment by bfontaine** [comment]
Thank you @mbrevda; we appreciate your contribution! :tada:

**Comment by dalanmiller** [comment]
Can we reopen this @danielmewes ?

**Comment by bfontaine** [comment]
@dalanmiller this PR has been merged; why do you want to reopen it?

**Comment by dalanmiller** [comment]
@bfontaine Thought we were still awaiting 2.1.5-2 release, missed the part where everything worked out and is :ok: :+1:  :D Thanks for checking.

**Pull request closed without merging**
