### PR TITLE
ghc: try allowing `-Wno-unicode`. See #41777

### PR DESCRIPTION
**Pull request by geoff-codes**
Discussion in #41777.

### CODE REVIEW

**Comment by geoff-codes** [comment]
@BrewTestBot test this please

**Comment by geoff-codes** [comment]
@mikemcquaid are you guys the only ones who can say the magic words above? Or am I doing it wrong?

I wanted to follow up on this but the test results are gone since I've been slacking a bit.

**Comment by bfontaine** [comment]
@BrewTestBot test this please.

**Comment by bfontaine** [comment]
@geoff-codes Yes, only maintainers can do that :wink:

**Comment by geoff-codes** [comment]
@bfontaine Ah. I was gonna say "too bad", but its probably better that way in the end :smirk:. Anyway, thanks!

**Comment by geoff-codes** [comment]
Sorry to hog the bot again. :cry:

**Comment by DomT4** [comment]
Is this good to go?

**Comment by geoff-codes** [comment]
@DomT4 IMO, yes, and #41777 should be able to be closed as well.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/b3e52c7b5342d3f017560e269d4dee9a27091825. Thanks for the speedy confirmation @geoff-codes, Appreciate that and the contribution!

**Comment by geoff-codes** [comment]
@bfontaine ack... should this be rev bumped? The issue in #41777 was preventing users from bootstrapping GHC... and that won't be fixed unless we bump it. What's your thought?

**Comment by DomT4** [comment]
Unless we get more than a few people reporting the issue I'm tempted to hold off on that for now. People can access the fix now manually by doing `brew update && brew reinstall ghc`.

Building `ghc` in non-`/usr/local` locations where the bottle isn't available is a painful experience, and a revision would force that on people, which is my hesitation. You're our go-to expert on GHC though - If you feel it's pressing enough to merit a general bump I wouldn't shoot you down.

**Comment by geoff-codes** [comment]
I opened a PR, just in case. Myself, I don't feel strongly either way... its not like a huge number of people are going to be doing stage 0 ghc bootstraps from homebrew. :smirk:

**Comment by geoff-codes** [comment]
> Building ghc in non-/usr/local locations where the bottle isn't available is a painful experience

Doing this right now... tell me about it. On 8 cores its still gonna be over an hour.

**Pull request closed without merging**
