### PR TITLE
Setup Ant lib folder and install ant-contrib to it

### LINKED ISSUE #41469: ant-contrib not installing to ant lib folder
Just recently attempting to put together a build script in ant that uses ant-contrib.  Installed using homebrew.

Ant seems unable to locate the contrib jar.  See this stackoverflow answer for more details: http://stackoverflow.com/questions/31277698/how-to-abstract-ant-contrib-cross-platform/31277896#31277896

### PR DESCRIPTION
**Pull request by mikemcquaid**
Closes #41469

@atrauzzi can you test this and let me know if it works for you?

### CODE REVIEW

**Comment by atrauzzi** [comment]
What's the best way to test?

**Comment by mikemcquaid** [comment]
`brew pull 41514 && brew reinstall ant ant-contrib && brew test ant-contrib` and then just trying your own tests that you suggested in the issue (as `ant-contrib` should be behaving there). Please test `ant` a bit on some projects with classpaths set to make sure nothing has broken there.

**Comment by atrauzzi** [comment]
Just ran it and it works!  Used both syntaxes to globally include:

`<taskdef resource="net/sf/antcontrib/antcontrib.properties"/>`
`<taskdef resource="net/sf/antcontrib/antlib.xml"/>`

Both work.

I also ensured that there was no `ant-contrib.jar` file anywhere in my project to be accidentally picked up.

**Comment by mikemcquaid** [comment]
Great. Can you give the diff a final check over and make sure the approach makes sense to you?

**Comment by atrauzzi** [comment]
Yes, as I can best tell, you're:

 - Setting up a lib dir
 - Wrapping the ant executable
 - Specifying the lib dir as a parameter to the executable

Straightforward and is likely all that needed to be done in this case :)

**Comment by mikemcquaid** [comment]
Great, merging, thanks!

**Comment by atrauzzi** [comment]
Awesome stuff, thanks so much! :+1:

**Pull request closed without merging**
