### PR TITLE
test-bot: better fold id for travis

### PR DESCRIPTION
**Pull request by xu-cheng**
* Only use first two word in command to keep id short
* Append unique number in the id.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
> Only use first two word in command to keep id short

Makes sense :+1: 



> Append unique number in the id.

I don't object, just curious why?

**Comment by xu-cheng** [comment]
> > Append unique number in the id.
> I don't object, just curious why?

I found travis will merge two fold together if they share same id.

**Comment by mikemcquaid** [comment]
> I found travis will merge two folds together if they share same id.

Ah, ok. Do we not just have to do that for names that are the same rather than for all steps?

**Comment by xu-cheng** [comment]
>  Do we not just have to do that for names that are the same rather than for all steps?

It's simple to do for all steps. And it can show us building order in case the log rendered incorrect.

**Comment by mikemcquaid** [comment]
OK.

**Pull request closed without merging**
