### PR TITLE
shell completion of official taps added to 'brew tap'

### PR DESCRIPTION
**Pull request by bfontaine**
cc @xu-cheng for the zsh part; I wasn’t able to test it.

I copied the file as `/usr/local/share/zsh/functions/_brew`, made sure it was in `$fpath`, but zsh doesn’t complete the commands when I type `brew <tab>`.

It works as expected in Bash.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
:+1:

**Comment by bfontaine** [comment]
@mikemcquaid Does your comment mean you successfully tested the ZSH part?

**Comment by mikemcquaid** [comment]
@bfontaine Nope, just that the diff looks good.

**Comment by bfontaine** [comment]
Thanks, I [fixed](http://stackoverflow.com/a/26479426/735926) my `~/.zshrc` and was able to use the completion feature.

**Pull request closed without merging**
