### PR TITLE
stoken 0.9

### PR DESCRIPTION
**Pull request by bcg62**
updating version from 0.81 to 0.9

### CODE REVIEW

**Comment by DomT4** [comment]
Please don't change the bottle checksums, we'll pull new ones when we merge this. Thanks!

**Comment by bfontaine** [comment]
@DomT4 we might have an issue with the version number here, since 9<81.

**Comment by DomT4** [comment]
Argh, yeah, possibly.

**Comment by DomT4** [comment]
Yup. Installing `stoken`, pulling this and then running `brew outdated` and `brew upgrade` produces no change. We'll probably need to fake the version a bit here.

**Comment by dunn** [comment]
How about `version "0.90"`

**Comment by bcg62** [comment]
Followed the revision numbers used in the project by @cernekee  Feel free to change it as you see fit or let me know what it needs to be and I can update the branch

**Comment by cernekee** [comment]
Yeah, sorry about that.  The v0.81 -> v0.9 transition seemed to confuse all of the package managers.  I have re-released the same code as v0.90 and will continue using the x.xx format from here on out.

**Comment by DomT4** [comment]
@cernekee Thanks for that. Eventually Homebrew will be able to handle versions as flexibly as Debian does with epochs, but at the moment our versioning system is pretty much "Is yz bigger than xy". Appreciate your flexibility on the tag.

@bcg62 If you could switch to the new 0.90 tag that'd be perfect, Thanks.

**Comment by bcg62** [comment]
@DomT4 fixed and rebased

**Comment by dunn** [comment]
Thank you @bcg62 and @cernekee! Merged in dfa47f4cf5e8673657dfd4b2945b9e1bb2f4d7c7.

**Pull request closed without merging**
