### PR TITLE
python, python3, pypy, pypy3: update pip 6.0.6 and setuptools 11.3.1

### PR DESCRIPTION
**Pull request by youtux**
This update also fixes the compilation error of the `distribute` package from pypi (thanks to the new setuptools).

Should I increase the revision number of the formulae?

### CODE REVIEW

**Comment by jacknagel** [comment]
Dupe of #35506; @tdsmith will address this eventually (pypy builds consume CI resources for extend periods of time).

**Comment by tdsmith** [comment]
Preferring this over #35506 since the setuptools is newer.

**Comment by mikemcquaid** [comment]
@tdsmith If we're going to keep updating setuptools and pip on `pypy` and `pypy3` we either need to work out a way to dramatically improve the build time or perhaps blacklist them on the bot and install the resources in post-install. These builds are taking 3-4 hours and it massively affects our PR flow. I realise this totally isn't your fault but I'd love us to work together on sorting this out.

**Comment by tdsmith** [comment]
I'm hoping that Python packaging will be boring again soon but I appreciate that this is painful.

The single easiest option is to switch to using the upstream binary to bootstrap translation, which should cut build times in half at the cost of a little purity and making life a little harder for Linuxbrew. Is that acceptable?

Blacklisting and handling in post-install also sounds fine. Is `--ci-testing` always passed for the testing queue?

**Comment by mikemcquaid** [comment]
> The single easiest option is to switch to using the upstream binary to bootstrap translation, which should cut build times in half at the cost of a little purity and making life a little harder for Linuxbrew. Is that acceptable?

Yeh, that works for me. We can always make it sufficiently optional that it doesn't make things any worse for Linuxbrew.

> Blacklisting and handling in post-install also sounds fine. Is --ci-testing always passed for the testing queue?

Being stupid but not quite sure what you mean here.

**Pull request closed without merging**
