### PR TITLE
saltstack 2015.8.0

### PR DESCRIPTION
**Pull request by ianbrandt**
This is my first attempt at updating a Homebrew formula.  All feedback welcomed.

The latest formula for Swig reportedly includes the fix for M2Crypto compatibility (swig/swig#344).  I'm not clear on whether this means Swig should still be installed as a resource, or should be reverted to a dependency?

### CODE REVIEW

**Comment by DomT4** [comment]
See #44189. As far as I can see, the original error reported upstream is still present when built against newer `swig` versions. It doesn't flag up in the CI testing as it has to be triggered by messing with `PYTHONPATH`s and such, although I am tempted to do something about that.

**Comment by DomT4** [comment]
If you did something like this in the `test do` you'd see the failure occur:

```ruby
test do
  ENV.prepend_path "PYTHONPATH", libexec/"vendor/lib/python2.7/site-packages"
  system "python", "-c", "import M2Crypto"

  system "#{bin}/salt", "--version"
end
```

**Comment by ianbrandt** [comment]
@DomT4 Thanks for the feedback.  I completely missed #44189.  I didn't realize pull requests are filtered by default when searching issues.

I've reverted to Swig 3.0.4 and added the suggested test case.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/f8890ebe0352f99423296e5e8bb2278b1f435b1f. Thank you for your contribution to Homebrew @ianbrandt!

**Pull request closed without merging**
