### PR TITLE
babeld 1.5.1

### PR DESCRIPTION
**Pull request by DomT4**
Version bump.

No practical test possible, sadly, due to the cumbersome requirements necessary to run the executable.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
> No practical test possible, sadly, due to the cumbersome requirements necessary to run the executable.

What's that, out of interest?

**Comment by DomT4** [comment]
There's no easy way to specify the var paths for the logfile and pid at runtime, there's switches but they aren't very cooperative, and natively it tries to create the var at ` /var ` with obviously requires ` sudo `, so you just run into ` creat(/var/run/babeld.pid): Permission denied `.

I can do something like:

```
babeld -L /usr/local/var/test1 -I /usr/local/var/test2
```

But the logfile it generates contains:

```
Couldn't tweak forwarding knob.: Operation not permitted
kernel_setup failed.
```

Which I get the feeling may not be a clean exit that we generally require/want.

**Comment by DomT4** [comment]
Yup, running with ` sudo ` generates a better message:

```
Eek... asked to run on no interfaces!
```

Sudo required then, by the looks of it.

**Comment by mikemcquaid** [comment]
Ok. Maybe that warrants a caveat? If you could send the patch upstream that'd be :heart: too.

**Comment by DomT4** [comment]
Have added a caveat. Not sure if it's worth pushing upstream tbh, it modifies network interfaces, so I think the ` sudo ` requirement is a hard OS X demand rather than something we can 'fix', alas.

**Comment by mikemcquaid** [comment]
I mean the `install` patch.

**Comment by DomT4** [comment]
Oh, done :+1:. Sent it to the mailing list.

**Comment by DomT4** [comment]
Currently awaiting approval, apparently:

```
our mail to 'Babel-users' with the subject

    Makefile Patch

Is being held until the list moderator can review it for approval.

The reason it is being held:

    Post by non-member to a members-only list
```

**Comment by mikemcquaid** [comment]
@DomT4 You might want to just sign up to the list and resend. In my experience rarely do the moderators approve them :grimacing:

**Comment by DomT4** [comment]
Heh. Solid point. Will temporarily subscribe and re-send the message and then include a link to the archive post as soon as it appears :+1:

**Comment by DomT4** [comment]
It reached the mailing list. Have added a link to the formula.

**Pull request closed without merging**
