### PR TITLE
tests: remove the coverage cache before each run

### LINKED ISSUE #48182: tests --coverage fails when a cached file is larger than its original
The title may not be clear; here is how to reproduce.
I assume you’re in `$(brew --prefix)/Library/Homebrew`.

1. Make sure the coverage cache doesn’t exist: `rm -rf test/coverage`
2. Run `brew tests --coverage`. It shouldn’t fail and it’ll create the `test/coverage` directory.
3. Edit a core file and remove some code. I, for example, edited `diagnostic.rb` and removed the `check_for_latest_xquartz` method. I’m not sure if it works with any piece of code.
4. Run `brew tests --coverage` again.

Expected output: it shouldn’t fail, like the first time.
Actual output:

```
$ brew tests --coverage
[Coveralls] Set up the SimpleCov formatter.
[Coveralls] Using SimpleCov's default settings.
Run options: --seed 21032

# Running:

..............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................F..........FFF....F......................................................................................

Finished in 113.719134s, 6.5336 runs/s, 15.6702 assertions/s.

  1) Failure:
IntegrationCommandTests#test_prefix [/usr/local/Library/Homebrew/test/test_integration_cmds.rb:60]:
--- expected
+++ actual
@@ -1 +1,2 @@
-"/var/folders/0d/mmrjgs1n0zdfdr386xlnx61h0000gn/T/homebrew_tests20160117-62729-2hlotn/prefix"
+"/var/folders/0d/mmrjgs1n0zdfdr386xlnx61h0000gn/T/homebrew_tests20160117-62729-2hlotn/prefix
+Warning: coverage data provided by Coverage [1352] exceeds number of lines in /usr/local/Library/Homebrew/diagnostic.rb [1336]"

  2) Failure:
IntegrationCommandTests#test_desc [/usr/local/Library/Homebrew/test/test_integration_cmds.rb:264]:
--- expected
+++ actual
@@ -1 +1,2 @@
-"testball: Some test"
+"testball: Some test
+Warning: coverage data provided by Coverage [1352] exceeds number of lines in /usr/local/Library/Homebrew/diagnostic.rb [1336]"
...snip...
```

Don’t forget to reset the file to its pristine state.

---
I digged in the `test/coverage` directory and it contains a `.resultset.json` file that might be the source of this issue. Maybe we should `rm_f` it before running the tests?

### PR DESCRIPTION
**Pull request by bfontaine**
Fixes #48182.

### CODE REVIEW

**Comment by UniqMartin** [comment]
There must be something broken in my setup, but I cannot figure out what. Anyway, since this change revealed the problem to me, please forgive me for posting this here:

Before this change (i.e. without removing the cache) I get:

- 49.71%, 122 files, 9088 lines (4518 covered, 4570 missed) – 1st run
- 63.77%, 124 files, 9573 lines (6105 covered, 3468 missed) – every consecutive run

After this change I get:

- 49.71%, 122 files, 9088 lines (4518 covered, 4570 missed) – all runs

These are the results if I don't touch any Homebrew files between runs of `brew tests --coverage`. The low coverage that I get after cleaning the cache also seems quite wrong … any ideas?

**Comment by bfontaine** [comment]
There is probably an issue with the way we `require` files when testing; a file that’s not `require`d is not covered. I’m not really sure how the coverage cache changes that but Mike pointed this out yesterday and I think this is it.

I also get a low coverage locally (49.76%); I’ll poke around tomorrow (it’s 1.40 AM here).

**Comment by mikemcquaid** [comment]
> There is probably an issue with the way we require files when testing; a file that’s not required is not covered. I’m not really sure how the coverage cache changes that but Mike pointed this out yesterday and I think this is it.

Yeh, for Ruby coverage checking we need to make sure that we `require` every Ruby file under `Library/Homebrew` with something like `Dir.glob("Library/Homebrew**/*.rb").each { |f| require f }`

**Comment by bfontaine** [comment]
The full list of missing file:
```
Homebrew/build.rb
Homebrew/cmd/audit.rb
Homebrew/cmd/cat.rb
Homebrew/cmd/create.rb
Homebrew/cmd/deps.rb
Homebrew/cmd/diy.rb
Homebrew/cmd/edit.rb
Homebrew/cmd/gist-logs.rb
Homebrew/cmd/home.rb
Homebrew/cmd/info.rb
Homebrew/cmd/irb.rb
Homebrew/cmd/leaves.rb
Homebrew/cmd/link.rb
Homebrew/cmd/linkapps.rb
Homebrew/cmd/list.rb
Homebrew/cmd/log.rb
Homebrew/cmd/man.rb
Homebrew/cmd/migrate.rb
Homebrew/cmd/options.rb
Homebrew/cmd/outdated.rb
Homebrew/cmd/pin.rb
Homebrew/cmd/prune.rb
Homebrew/cmd/pull.rb
Homebrew/cmd/reinstall.rb
Homebrew/cmd/sh.rb
Homebrew/cmd/style.rb
Homebrew/cmd/switch.rb
Homebrew/cmd/tap-readme.rb
Homebrew/cmd/test-bot.rb
Homebrew/cmd/test.rb
Homebrew/cmd/tests.rb
Homebrew/cmd/unlink.rb
Homebrew/cmd/unlinkapps.rb
Homebrew/cmd/unpack.rb
Homebrew/cmd/unpin.rb
Homebrew/cmd/update-report.rb
Homebrew/cmd/update.rb
Homebrew/cmd/upgrade.rb
Homebrew/cmd/uses.rb
Homebrew/compat/dependency_collector.rb
Homebrew/compat/download_strategy.rb
Homebrew/compat/fails_with_llvm.rb
Homebrew/compat/formula.rb
Homebrew/compat/formula_specialties.rb
Homebrew/compat/hardware.rb
Homebrew/compat/keg.rb
Homebrew/compat/macos.rb
Homebrew/compat/md5.rb
Homebrew/compat/pathname.rb
Homebrew/compat/requirements.rb
Homebrew/compat/version.rb
Homebrew/config.rb
Homebrew/dev-cmd/aspell-dictionaries.rb
Homebrew/dev-cmd/update-test.rb
Homebrew/formula_assertions.rb
Homebrew/language/go.rb
Homebrew/language/haskell.rb
Homebrew/os/linux/hardware.rb
Homebrew/postinstall.rb
Homebrew/test.rb
```

I think instead of `require`-ing all of them with a glob we should ensure we have tests that `require` them. It’ll take more time but will force us to write test.

**Comment by mikemcquaid** [comment]
@bfontaine I don't agree; it's standard practice on coverage testing to require all of them with a glob as otherwise our coverage % will be consistently wrong (which is bad).

**Comment by bfontaine** [comment]
@mikemcquaid OK, I’ll do a PR.

**Comment by mikemcquaid** [comment]
@bfontaine :bow: :+1: :metal:

**Pull request closed without merging**
