### PR TITLE
Add json-c dependency to bind

### PR DESCRIPTION
**Pull request by tg90nor**
Fixes issue #41823

Not sure how I would go about adding a test for this.

### CODE REVIEW

**Comment by dunn** [comment]
It installs a number of executables so we could just run a few, `system bin/"dig", "http://brew.sh`, and so on

**Comment by tg90nor** [comment]
I added a test.

Note that bind compiles and works just fine without json-c, but since the yosemite bottle was built with it, it must be present when using the bottle.

**Comment by dunn** [comment]
> Note that bind compiles and works just fine without json-c, but since the yosemite bottle was built with it, it must be present when using the bottle.

Not sure what you mean.  Are you saying if you install bind from source, `dig` works without json-c being installed?

**Comment by tg90nor** [comment]
Yes. It is only needed when using the binary bottle. Bind will automatically be built with json-c if it is present at compile time, but works fine without it.

**Comment by tdsmith** [comment]
Does bind's configure script accept an option that tells it not to look for json-c?

**Comment by dunn** [comment]
Yeah, looks like a better fix might be `--with-libjson=no`.

Are there advantages to building with json-c?

**Comment by tg90nor** [comment]
> Are there advantages to building with json-c?

It enables generating statistics in json. Might want to make it optional? I don't personally need it.

**Comment by dunn** [comment]
Yeah, `depends_on "json-c" => :optional` then pass `--with-libjson=no` to the configure script otherwise.  Thanks!

**Comment by dunn** [comment]
Merged in 0ec46291a52c42e26a3467671e6ee02eaefd2104, thanks for fixing this!

**Pull request closed without merging**
