### PR TITLE
autocode: use secure url in test

### PR DESCRIPTION
**Pull request by vszakats**

### CODE REVIEW

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/80c2ff1dbac44e62e42557ca12252f73eeef21e3. Your talent for spotting even minor insecure URLs is both impressive and slightly terrifying :wink:. Thanks!

**Comment by vszakats** [comment]
`grep` is to blame :)

**Comment by DomT4** [comment]
I'm a fan of `ack` personally for mass huntings. Extremely handy tool.

**Comment by vszakats** [comment]
Yeah, tried to give `ack` a chance but the muscle memory didn't moved on just yet. It is planned along some other mid-term retooling.

**Comment by vszakats** [comment]
I'm going to give `ack` another go. It's so much faster and works without much manual tweaking.

**Comment by DomT4** [comment]
Despite being targeted towards programmers it's useful pretty widely. I used it the other day to find a quote I was looking for in my study notes, spread out across a bunch of word documents, where I couldn't remember which file it was in.

**Comment by vszakats** [comment]
I hope to remember this next time I need it. [ In theory, Spotlight should be able to do that :) El Capitan does search somewhat better than previous iterations. ]

**Comment by DomT4** [comment]
I use "Alfred" as well, but `ack` has proved pretty useful for finding snippets of text. Don't ever really use the Spotlight in terms of GUI; use `mdfind` from the CLI a lot though.

**Comment by vszakats** [comment]
`mdfind` noted, thanks! I use Spotlight only as an app starter really.

**Pull request closed without merging**
