### PR TITLE
aws-elasticbeanstalk: basic test added + modernize

### PR DESCRIPTION
**Pull request by bfontaine**
I can’t add a better test since it needs to connect to AWS.

### CODE REVIEW

**Comment by DomT4** [comment]
Do you want to bump whilst we're here? #35473

**Comment by bfontaine** [comment]
Aren’t we supposed to not write formulae for [stuff already provided by Pypi](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Acceptable-Formulae.md#we-try-hard-to-avoid-dupes-in-homebrewhomebrew)? I guess there’s an exception here since earlier versions weren’t.

**Comment by mikemcquaid** [comment]
@bfontaine We can include applications but not libraries.

**Comment by bfontaine** [comment]
Thanks, I’m on it.

**Comment by DomT4** [comment]
Might look at explicitly saying we're cool with applications in the docs. We've had the library/application question quite a bit lately.

**Comment by bfontaine** [comment]
Done.

**Pull request closed without merging**
