### PR TITLE
jenkins 1.625

### PR DESCRIPTION
**Pull request by asaph**

### CODE REVIEW

**Comment by dunn** [comment]
The test failed because we're running tests in a sandbox now, and the test tries to write outside of the sandbox.  Not your fault, but would you mind seeing if you can tweak the test?

**Comment by DomT4** [comment]
Looks like if we set `ENV["JENKINS_HOME"] = testpath` in `test do` it should work.

**Comment by asaph** [comment]
@DomT4 Yep, that seems to have worked. Thanks!

**Comment by xu-cheng** [comment]
Thanks for the pull request! 🎉 Homebrew depends on contributions from community members like you and we're grateful for your support.

**Pull request closed without merging**
