### PR TITLE
ghc: make gmp a build-time dependency.

### PR DESCRIPTION
**Pull request by mikemcquaid**
Link against the static libraries instead.

CC @adamv in case you can remember why this was added in 7153db0a9e0f1f7057548cc7defd3f8a2ac753af.

### CODE REVIEW

**Comment by adamv** [comment]
Sorry, I really don't remember.

**Comment by pthariensflame** [comment]
GMP is needed at runtime for any GHC-built program because GHC uses (by default) a GMP-based backend for Haskell's built-in `Integer` type (*c.f.* [the `Integer` implementation commentary on the GHC Trac wiki](https://ghc.haskell.org/trac/ghc/wiki/Commentary/Libraries/Integer)).  That being said, we could definitely swap over to using `integer-simple` instead of `integer-gmp` (but such a decision would have to be made by altering GHC's formula appropriately, and all Haskell programs built with that GHC would have no more choice in the matter than they do now.)

**Comment by mikemcquaid** [comment]
@pthariensflame Good to know. I'll statically link against `gmp` instead then. Thanks!

**Comment by mikemcquaid** [comment]
Need to wait until we sort out the bots (e.g. get them off VMs) before trying again.

**Comment by DomT4** [comment]
@mikemcquaid What is the situation with the bots? Notice we're consistently losing at least one a day lately, is the machine croaking?

**Comment by mikemcquaid** [comment]
@DomT4 Two out of the four machines we have are having issues. I'm limited in how much debugging I can do until the remote power switch we have gets hooked up (well, it's hooked up but I need to get access) as the machines are currently going down on git operations.

**Comment by mikemcquaid** [comment]
Closing in favour of #38131.

**Pull request closed without merging**
