### PR TITLE
mpv 0.8.0 (new formula)

### PR DESCRIPTION
**Pull request by chrisaljoudi**
new formula: `mpv`. [See homepage](https://github.com/mpv-player/mpv).

Current stable is 0.8.0. Support for HEAD included.

### CODE REVIEW

**Comment by tdsmith** [comment]
This looks like an updated version of mpv.rb from the tap the mpv developers maintain: https://github.com/mpv-player/homebrew-mpv

It looks like we haven't discussed adding mpv to core before.

**Comment by vszakats** [comment]
As pulled [here](https://github.com/mpv-player/homebrew-mpv/pull/50), please update the http `url` to https:
http://ftp.waf.io/pub/release/#{WAF_VERSION}
to
https://ftp.waf.io/pub/release/#{WAF_VERSION}

**Comment by pigoz** [comment]
`0.8.0` is already slightly outdated (`0.8.2` is available now). It will probably be hard to keep a fast moving project like mpv in Homebrew's mainline (patch releases are biweekly most of the time).

**Comment by tdsmith** [comment]
I see you maintain homebrew-mpv. If you're happy maintaining the tap that's fine with us; you're also welcome to start sending us PRs whenever you'd like. Will close this for now; thanks for using Homebrew!

**Pull request closed without merging**
