### PR TITLE
use updated yaws release for otp 18 support

### PR DESCRIPTION
**Pull request by optikfluffel**
More details: [klacke/yaws#226](https://github.com/klacke/yaws/issues/226)

### CODE REVIEW

**Comment by DomT4** [comment]
Does this appear under `brew outdated`? The change of versioning could cause problems.

**Comment by optikfluffel** [comment]
@DomT4 we're duscussing this [in here](https://github.com/klacke/yaws/issues/226#issuecomment-120997920) and I'd guess there will be a new commit with `yaws-2.0` and then everything should be fine, right?

**Comment by DomT4** [comment]
Yup, if the next tag is `2.0` that'll be understood as greater than `1.99` whereas `yaws-erlang-18` probably won't be. (We can always put in a fake version if necessary though).

**Comment by optikfluffel** [comment]
I'll update this and ping you for re-running the tests when ready, ok? :)

**Comment by DomT4** [comment]
Thanks! It should automatically kick off a new CI run when you push :)

**Comment by optikfluffel** [comment]
smile and nod

**Comment by optikfluffel** [comment]
@DomT4 This should be ready to merge.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/c94e25b7745b2d4e1f534e4b79c14cc374bae611. Thank you for your contribution to Homebrew, we appreciate it! :smiley_cat:

**Pull request closed without merging**
