### PR TITLE
depqbf 4.0

### PR DESCRIPTION
**Pull request by bfontaine**

### CODE REVIEW

**Comment by tdsmith** [comment]
Should we install the library that depqbf builds?

I don't know if you want to amend your PR, but ideally the library would use OS X naming conventions, like libqdpll.1.0.dylib.

**Comment by bfontaine** [comment]
I can edit this PR to install the library, but I don’t know anything about libraries on OS X. Is `*.dylib` the same as `*.so`, i.e. is it’s only about naming, there’s nothing more to do?

**Comment by tdsmith** [comment]
In this case, yeah. Dynamic libraries (things you build with `-shared` and link with `-lfoo`) are named like foo.1.0.dylib on OS X and foo.so.1.0 on Linux.

(OS X also has a concept of a bundle, which is a plugin thing loaded into another process, which are built with `-bundle` and named .so; Linux doesn't distinguish. I think on modern OS X systems you can use dylibs for everything and forget about bundles but the system APIs used to force a distinction.)

**Comment by bfontaine** [comment]
Thanks for the explanation! I amended both the upstream PR and this one to install the library using OS X conventions.

**Comment by tdsmith** [comment]
It looks like version 4.0 was re-tagged; can you update the hash?

**Comment by bfontaine** [comment]
Done! Upstream merged my patch so I removed it from the formula :+1:

**Comment by bfontaine** [comment]
Sorry I “updated” the hash without clearing my cache, meaning I didn’t update anything. This should be ok now.

**Comment by bfontaine** [comment]
@tdsmith ping?

**Comment by tdsmith** [comment]
Oops! @BrewTestBot test this please

**Comment by tdsmith** [comment]
Thanks; sorry for the delay here!

**Pull request closed without merging**
