### PR TITLE
tup: fix compilation of HEAD version in Yosemite

### PR DESCRIPTION
**Pull request by flyingmutant**
Do not try to apply an outdated patch.

### CODE REVIEW

**Comment by DomT4** [comment]
Was just about to do this :wink:. You might as well remove the unused patch totally and apply the actual upstream commit instead, since they went about it a different way in the end.

**Comment by flyingmutant** [comment]
That might be cleaner, for sure, but this change is less invasive, while guaranteeing to still work everywhere without additional testing.

Once new version of tup will be released, all of this patch madness can be cleaned up (dropped).

**Comment by DomT4** [comment]
It's up to the maintainers to make the call, but generally, if upstream rejects a PR in favour of committing something else and we notice *and* have to make a change to the formula anyway, we often switch. Just happens to be the case that most of the time either the PR is merged, or nobody checks again till the next release :smile_cat:.

I'll let the maintainers make the call. I am blissfully powerless to make requests in the core.

**Comment by mikemcquaid** [comment]
> It's up to the maintainers to make the call, but generally, if upstream rejects a PR in favour of committing something else and we notice and have to make a change to the formula anyway, we often switch. Just happens to be the case that most of the time either the PR is merged, or nobody checks again till the next release .

Yes, I agree, this would be good if you wouldn't mind.

**Comment by flyingmutant** [comment]
Done — should be good to merge now.

**Pull request closed without merging**
