### PR TITLE
audit fixes: D 02: dfix - djvulibre

### PR DESCRIPTION
**Pull request by apjanke**

### CODE REVIEW

**Comment by DomT4** [comment]
You may want to drop `disco` here for now and try to debug that in its own PR; It's breaking the build in a fun way.

**Comment by apjanke** [comment]
Pulled out disco.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/decc4dda4ba0b975cb2caab11066cfddcc855bfd. Thanks again :beer:

**Comment by apjanke** [comment]
You're welcome!

**Pull request closed without merging**
