### PR TITLE
pyenv v20151124

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/616290d41d35eb28e94cc506ac090cb57652079d. Thanks Alex!

**Comment by alex** [comment]
@DomT4 intentional that this wasn't closed?

**Comment by alex** [comment]
Looks like github was just slow to close. :+1:

**Comment by DomT4** [comment]
Yeah, It takes a few minutes in the core.

**Pull request closed without merging**
