### PR TITLE
mutt: install mutt_dotlock

### LINKED ISSUE #45400: Mutt 1.5.24 (bottled) Missing mutt_dotlock
Hello,

I installed mutt: stable 1.5.24 (bottled), HEAD with homebrew, but I am unable to write to my inbox when using mutt. When I try and delete a message I see: _Mailbox is read-only._

I have ensured that folder and spool file permissions are correct for /var/spool/username. I found that `mutt_dotlock` is needed by mutt to lock the mail spool file to allow editing. See _I can't modify my inbox folder, Mutt claims it's read-only, but permissions are ok?_ here: http://dev.mutt.org/trac/wiki/MuttFaq/Folder. But it seems that `mutt_dotlock` was never installed by homebrew. Am I missing something?

### PR DESCRIPTION
**Pull request by DomT4**
Presuming we get confirmation this doesn't break "all the things" this would:

Closes #45400.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
:+1:

**Comment by DomT4** [comment]
Just waiting on anyone who actually uses `mutt` to test this change prior to merge.

**Comment by dunn** [comment]
🙋🏼

**Comment by DomT4** [comment]
@dunn Was that a you use `mutt` notification? :wink:

**Comment by dunn** [comment]
Ahaha, yeah.  I'm running this version now, and nothing obviously bad has happened yet.

**Comment by DomT4** [comment]
Alright. If everything goes wrong will blame @dunn for confirmation that it works :trollface:. Thanks for the review and test! Merged in https://github.com/Homebrew/homebrew/commit/60595085dd25b19397cdcae1bca2f871236ce0ce.

**Pull request closed without merging**
