### PR TITLE
deisctl v1.10.0

### PR DESCRIPTION
**Pull request by protomouse**
This PR updates deisctl to version [1.10.0](https://github.com/deis/deis/releases/tag/v1.10.0).

### CODE REVIEW

**Comment by bfontaine** [comment]
Install is failing: `go install net: open /usr/local/Cellar/go/1.5/libexec/pkg/darwin_amd64/net.a: operation not permitted`

**Comment by protomouse** [comment]
Is the CI build stuck in limbo?

**Comment by DomT4** [comment]
@BrewTestBot test this please

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/efc1cb0e032d167a43cb7aa4066dd6e401b68681. Thank you for your contribution to Homebrew @protomouse!

**Pull request closed without merging**
