### PR TITLE
dnscrypt-proxy: new test

### PR DESCRIPTION
**Pull request by xu-cheng**
Test a new(and much more complex) test case as the old test case keeps failing on CI bot.

### CODE REVIEW

**Comment by xu-cheng** [comment]
Now I'm pretty sure CI's network setting is the cause. It times out for a simple `dig` command. There's nothing I can do. @mikemcquaid

**Comment by DomT4** [comment]
Worst-case scenario, if the network settings are the root cause of the issues, we could go *way* back to basics and just implement ` bin/"hostip" -V `. That should work whatever the network settings are or aren't.

**Comment by mikemcquaid** [comment]
There's weird DNS issues on the bot machines that I've never quite been able to work out why. Maybe it's our ISP.

**Comment by DomT4** [comment]
You could try moving the DNS away from the ISP to something like Google's Public DNS? Could be an interesting experiment.

```
sudo networksetup -setdnsservers Ethernet 8.8.8.8 8.8.4.4
```

Should work, presuming they're hooked to ethernet and not wifi, which I presume they are if they're sat in a data center.

**Comment by mikemcquaid** [comment]
Tried that, similar issues.

**Comment by DomT4** [comment]
That's strange. Perhaps worth flagging up to the hosting provider, I guess it's possible if the bots are having issues that others also hosted with them could be too :confused:

**Pull request closed without merging**
