### PR TITLE
pycd 0.3.0: new formula

### PR DESCRIPTION
**Pull request by wkentaro**

### CODE REVIEW

**Comment by DomT4** [comment]
@mikemcquaid Thoughts on this? There are some style nits that need cleaning up, but:

```
==> audit problems
pycd:
 * GitHub repository not notable enough (<10 forks, <10 watchers and <20 stars)
```

The Github repository isn't watched/starred/forked enough, but a quick check on pypi [reveals](https://pypi.python.org/pypi/pycd/0.3.0) over 1100 downloads a week on average. How strictly do we want to enforce the Github notability here?

**Comment by mikemcquaid** [comment]
@wkentaro We recommend you create your own tap for this repository instead of submitting it to Homebrew. Sorry and thanks!

@DomT4 Self-submissions we'll probably be a bit stricter on.

**Comment by DomT4** [comment]
@mikemcquaid Cool, Thanks for the review!

**Comment by wkentaro** [comment]
I see. Thanks.

**Pull request closed without merging**
