### PR TITLE
emacs: default to --with-cocoa

### PR DESCRIPTION
**Pull request by dunn**
To make things easier for people switching from Aquamacs and other
GUI-centric builds.

This also matches upstream, which defaults to building --with-ns.  If
--with-ns and --with-x are both specified, it uses the nextstep window
system; but issue a warning in caveats since now `brew install
--with-x11` will actually build a Cocoa app.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
I'd rather we didn't do this due to the `--with-x11` confusion and because I'd rather we had fewer apps in Homebrew than build GUIs by default rather than more.

**Comment by dunn** [comment]
I guess the only big advantage of this change is bottling the Cocoa version, since I'm willing to bet that it's what most people want.

**Comment by mikemcquaid** [comment]
https://github.com/caskroom/homebrew-cask/issues/15603 is worth a read for my thoughts around this. I'd really like a future where we ship no `.app`s and those all live in Homebrew Cask.

**Comment by dunn** [comment]
Ah, fair enough.

**Pull request closed without merging**
