### PR TITLE
PEGTL 1.1.0

### PR DESCRIPTION
**Pull request by guoxiao**

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Given this is only a single header I wonder if it's more useful to have it in Homebrew or just have projects vendor it?

**Comment by guoxiao** [comment]
So we don't accept header-only library in homebrew now?

**Comment by guoxiao** [comment]
> Given this is only a single header

It's a header `pegtl.hh` and a folder of many headers.

**Comment by mikemcquaid** [comment]
> So we don't accept header-only library in homebrew now?

I haven't decided either way; I'm waiting for other maintainers to give their thoughts.

**Comment by DomT4** [comment]
What is the upstream `Makefile` intended to do, and why aren't we using it, out of curiosity?

**Comment by guoxiao** [comment]
@DomT4 The upstream `Makefile` is used by travis-ci to build all examples and unittests.

**Comment by DomT4** [comment]
Alright.

I guess I'm not fundamentally opposed to header-only libraries in Homebrew, but I'm not sure how widely used they'll ever be.

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

For future reference the preferred commit message format for simple version updates is `pegtl 1.1.0 (new formula)`.

**Pull request closed without merging**
