### PR TITLE
Update task to 2.5.0

### PR DESCRIPTION
**Pull request by KevinSjoberg**
Remove devel-block since 2.5.0 is stable now. Bump head-block to make
use of branch 2.5.1.

### CODE REVIEW

**Comment by bfontaine** [comment]
The build is failing:

```
==> Downloading https://taskwarrior.org/download/task-2.5.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/task-2.5.0.tar.gz
==> Verifying task-2.5.0.tar.gz checksum
tar xf /Library/Caches/Homebrew/task-2.5.0.tar.gz
==> cmake . -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/task/2.5.0 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev
-- The C compiler identification is AppleClang 6.0.0.6000057
-- The CXX compiler identification is AppleClang 6.0.0.6000057
-- Check for working C compiler: /usr/local/Library/ENV/4.3/clang
-- Check for working C compiler: /usr/local/Library/ENV/4.3/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/Library/ENV/4.3/clang++
-- Check for working CXX compiler: /usr/local/Library/ENV/4.3/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMAKE_SYSTEM_NAME Darwin
-- Performing Test _HAS_CXX11
-- Performing Test _HAS_CXX11 - Success
-- Performing Test _HAS_CXX0X
-- Performing Test _HAS_CXX0X - Success
-- Performing Test _HAS_GNU0X
-- Performing Test _HAS_GNU0X - Success
-- Looking for SHA1 references
-- Looking for GnuTLS
-- Could NOT find GnuTLS (missing:  GNUTLS_LIBRARY GNUTLS_INCLUDE_DIR) 
CMake Error at CMakeLists.txt:124 (message):
  Cannot find GnuTLS.  Use -DENABLE_SYNC=OFF to build Taskwarrior without
  sync support.  See INSTALL for more information.


-- Configuring incomplete, errors occurred!
```
http://bot.brew.sh/job/Homebrew%20Pull%20Requests/35502/version=mavericks/testReport/junit/brew-test-bot/mavericks/install_task/

**Comment by KevinSjoberg** [comment]
@bfontaine I've looked into it and it looks like GnuTLS is mandatory since `2.5.0.`. See https://taskwarrior.org/news/news.20151021.html.

I can update the `depends_on` statement. Should I use `depends_on "gnutls" => :build` or ` depends_on "gnutls"`?

**Comment by bfontaine** [comment]
@KevinSjoberg use `depends_on "gnutls"` unless it’s only necessary for the build and not after.

**Comment by KevinSjoberg** [comment]
@bfontaine I've updated the pull request with a proper `depends_on` statement. I also noticed that `GnuTLS` isn't required, but it's opt-out instead of opt-in since 2.5.0.

The installation instructions says the following:

> 	"sync" command
> 	--------------
>	
> 	By default, GnuTLS support is required, which enables the "sync" command.
> 	For Debian based distributions, installing "libgnutls-dev" is sufficient.
> 	
> 	In order to build Taskwarrior without "sync" support, call cmake with the
> 	"-DENABLE_SYNC=OFF" flag:
> 	
> 	   $ cmake . -DENABLE_SYNC=OFF

**Comment by chdiza** [comment]
Ideally the formula would gain an option that skips the `gnutls` dep.

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

@chdiza Can you submit a PR? Thanks!

**Comment by chdiza** [comment]
> Can you submit a PR? Thanks!

If I can figure out how to disable the thing in question, sure.  I know nothing about cmake, so it might be a bit of an adventure.

**Pull request closed without merging**
