### PR TITLE
openjpeg 1.5.2

### PR DESCRIPTION
**Pull request by dunn**

### CODE REVIEW

**Comment by dunn** [comment]
These are the formula in taps that depend on openjpeg and might need revisions:
```
homebrew/games/ppsspp
homebrew/head-only/pdftoipe
homebrew/science/butterflow
homebrew/science/cvblob
homebrew/science/insighttoolkit
homebrew/science/nip2
homebrew/science/openalpr
homebrew/science/openbr
homebrew/science/opencv
homebrew/science/opencv3
homebrew/science/openimageio
homebrew/science/osgearth
homebrew/science/paraview
homebrew/science/shogun
homebrew/science/simpleitk
homebrew/science/statismo
homebrew/science/vips
homebrew/science/vips7
homebrew/science/visp
homebrew/x11/gimp
homebrew/x11/inkscape
homebrew/x11/xournal
homebrew/x11/yarp
```

**Comment by dunn** [comment]
cc @Homebrew/science

**Comment by dunn** [comment]
Haha, `--recursive` was not correct there.  The only formulae that need to be checked are:
```
ffmpeg
gpac
grib-api
leptonica
libav
openslide
poppler
homebrew/science/openimageio
```

**Comment by scribblemaniac** [comment]
@dunn It seems that openjpeg has a [2.1.0 version](https://github.com/uclouvain/openjpeg/releases). Is there any reason why you decided to only upgrade to 1.5.2?

**Comment by dunn** [comment]
openjpeg [2.0.x](https://github.com/Homebrew/homebrew-versions/blob/master/openjpeg20.rb) and [2.1.x](https://github.com/Homebrew/homebrew-versions/blob/master/openjpeg21.rb) exist in our Versions tap already.

**Comment by scribblemaniac** [comment]
I thought there would be a reason for it, thanks!

**Pull request closed without merging**
