### PR TITLE
tig: Render UTF-8 correctly

### PR DESCRIPTION
**Pull request by ptzz**

### CODE REVIEW

**Comment by mistydemeo** [comment]
ncurses isn't available in the default Homebrew repository, so tig can't depend on this unconditionally. (The name will also need to be `homebrew/dupes/ncurses`, to reflect where it comes from.)

**Comment by ptzz** [comment]
Btw, what's the policy on what goes to `homebrew/dupes`? I noted that `readline` is in default Homebrew even though also provided by OS X.

**Comment by mistydemeo** [comment]
Readline is a bit of a different case. OS X provides libedit, which is not 100% compatible with GNU readline; some software will not work, or will be missing notable features, using libedit. Since there's a lot of software to which this applies, we include readline in the main repository. (And since libedit and readline are different packages, it's not 100% a "dupe.")

However, most software works just fine using the system ncurses. We only have a single package in the main repository which (optionally) uses a newer ncurses; that's not really enough demand for us to consider migrating it into the main repository.

**Comment by mistydemeo** [comment]
Looking at the configure script, I think this could be made to work with the system ncurses.

Apple builds their ncurses with wide-character support, but doesn't install the library as `ncursesw`. It may be compatible with tig if tig can be made to accept it. Can you give me an example of a test I could perform to confirm wide character support is available?

**Comment by ptzz** [comment]
Thanks for the comprehensive answers! I checked and the current Homebrew tig version does display UTF-8 correctly. I was trying to get rid of warnings from tig `configure` but didn't check if UTF-8 display already worked.
```
configure: WARNING: The found ncurses library does not support wide-char.
configure: WARNING: This means that tig will not correctly render UTF-8.
```

**Comment by mistydemeo** [comment]
From a cursory glance at the code, it looks like that warning is from the section of the configure script that determines the lib name to pass in LDFLAGS, but it doesn't actually define any macros that are used within tig to determine whether or not to use wide functions. Seems like the warning is misleading, but harmless.

Since tig seems to work fine with wide characters, I'm going to close this - thanks very much for the report!

**Pull request closed without merging**
