### PR TITLE
jboss-forge 3.0.0.Alpha1

### PR DESCRIPTION
**Pull request by gastaldi**

### CODE REVIEW

**Comment by bfontaine** [comment]
If this is not a stable version please use a `devel` block.

**Comment by gastaldi** [comment]
How can I use this block? Can you help me?

**Comment by bfontaine** [comment]
Sure, keep the existing sha256/URL and add the following in the formula:

```rb
devel do
  url "https://the-url-of-the-alpha-version"
  sha256 "the-sha256-of-the-alpha-version"
end
```

See [the docs](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md#devel) and [`linklint.rb`](https://github.com/Homebrew/homebrew/blob/8f5db0371422ae45a871def8b1cfe668d9aeb919/Library/Formula/linklint.rb#L9-L12), [`pianod.rb`](https://github.com/Homebrew/homebrew/blob/8c6777b2b8e847d5f2b447eae532fa8ecffa6467/Library/Formula/pianod.rb#L7-L10) or [`epic5.rb`](https://github.com/Homebrew/homebrew/blob/8c6777b2b8e847d5f2b447eae532fa8ecffa6467/Library/Formula/epic5.rb#L15-L18) for examples.

**Comment by bfontaine** [comment]
Feel free to ask if you have any question :smiley:

**Comment by gastaldi** [comment]
Added devel block in https://github.com/Homebrew/homebrew/pull/45756 as instructed by @bfontaine.

Thank you very much! You guys rock.
Closing this PR now.

**Pull request closed without merging**
