### PR TITLE
Clean whitespace

### PR DESCRIPTION
**Pull request by aarzee**
Remove leading newlines; replace lines containing only whitespace with empty lines; replace multiple trailing newlines with a single newline.

This PR was created semiautomatically.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Have you checked all these formulae still install with whitespace removed from their patches?

**Comment by DomT4** [comment]
Is this not extremely likely to break a lot of the patches?

**Comment by aarzee** [comment]
No, but I can do it now. Give me a few minutes and I’ll get back with an answer.

**Comment by aarzee** [comment]
This is going to take a while, but so far nothing's breaking. It would be quite helpful if there were specific formulae which I should be checking; should I only check those with patches?

**Comment by aarzee** [comment]
I realized that doing `brew install [...] --build-from-source` was also going to build each package's dependencies from source, so I'm currently doing `brew install [...] --only-dependencies`. It looks like I'm about halfway through the packages (this probably has little to no bearing on how much longer the dependency installation will take), and once that's done I'm going to do the first command again. FWIW, I did start doing the first command before I had this realization, and it got through the first 6 packages without any failed installations.

**Comment by aarzee** [comment]
The fontconfig formula broke. https://ghostbin.com/paste/576fg
This is really odd as every single formula before that one installed fine.

**Comment by dunn** [comment]
What's the rationale for this PR?

**Comment by mikemcquaid** [comment]
I'm going to pass on this PR. We're not really interested in changes like this and it has merge conflicts now. Sorry!

**Pull request closed without merging**
