### PR TITLE
SDL2 2.0.4

### PR DESCRIPTION
**Pull request by LRFLEW**

### CODE REVIEW

**Comment by LRFLEW** [comment]
The place that the travis test failed seems kind of odd. Looking at the log, it looks like it locked up building ffmpeg and never made it to sdl2. That couldn't be caused by this sort of change, right?

I also realized that the devel version in the config is now older than the stable version. The devel version seems to have been a workaround while we waited for this version to go stable, so it should probably be safe to remove. Unless I'm told otherwise, though, I'll leave that change for another PR.

**Comment by dunn** [comment]
Let's go ahead and remove the `devel` block entirely unless there's a new development release. Thanks!

**Comment by LRFLEW** [comment]
It errors at the same location again. I know that the contributing readme says I should resolve any build failures, but I have no clue why it would be here. The log suggests that it's failing (or at least timing out) building ffmpeg, which is not dependent on SDL2. If this error isn't caused by the changes here, do I need to still try to fix it?

**Comment by dunn** [comment]
Oh, it's just Travis being impatient with the long build.  Jenkins (the "default" CI) passed, so we're good!

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
