### PR TITLE
Nomad 0.3.1

### PR DESCRIPTION
**Pull request by MerelyAPseudonym**
### All Submissions:

- [X] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew/blob/master/.github/CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew/pulls) for the same update/change?

### CODE REVIEW

**Comment by DomT4** [comment]
You'll make life easier for yourself if you merge https://github.com/Homebrew/homebrew/pull/50267 into this or vice versa.

**Comment by MerelyAPseudonym** [comment]
@DomT4 I only split it up into two PRs because I figured it would be easier for the maintainers. So if you’d prefer everything to be in a single PR, I’d be happy to combine them.

**Comment by DomT4** [comment]
Doesn't make much difference to us either way, but the CI can get temperamental about competing PRs for the same formula. If you wouldn't mind combining them that'd be magical, Thanks!

**Comment by MerelyAPseudonym** [comment]
This PR has been rendered obsolete by https://github.com/Homebrew/homebrew/pull/50267/commits/5dd908757c0859db45f920e1675bf9084848dd5b.

**Pull request closed without merging**
