### PR TITLE
irrlicht 1.8.3

### PR DESCRIPTION
**Pull request by bfontaine**
I don’t know how to test this.

### CODE REVIEW

**Comment by bfontaine** [comment]
The patch needs to be adapted to the new source.

**Comment by bfontaine** [comment]
The build is failing on Yosemite:
```
==> xcodebuild -project source/Irrlicht/MacOSX/MacOSX.xcodeproj -configuration Release -target libIrrlicht.a SYMROOT=build -sdk macosx10.10
xcodebuild: error: SDK "macosx10.10" cannot be located.
```

According to [this SO thread](http://stackoverflow.com/q/25941243/735926) it seems to be an issue with Xcode’s version.

**Comment by neoascetic** [comment]
Works well on El Capitan. May it be resubmitted?

**Comment by bfontaine** [comment]
@neoascetic Feel free to open a pull-request :wink:

**Pull request closed without merging**
