### PR TITLE
test-bot: run `git gc` on cleanup.

### PR DESCRIPTION
**Pull request by mikemcquaid**
CC @xu-cheng @DomT4

### CODE REVIEW

**Comment by xu-cheng** [comment]
:+1:

**Comment by DomT4** [comment]
:+1: here as well. `git gc` can be kind of sluggish, but if the alternative is manual plumbing every couple days this is a nicer solution.

**Comment by mikemcquaid** [comment]
> here as well. git gc can be kind of sluggish, but if the alternative is manual plumbing every couple days this is a nicer solution.

@DomT4 `--auto` means it'll only run if needed (i.e. relatively infrequently)

**Comment by DomT4** [comment]
Yeah, I have the same setting run locally. I guess my point was more that the test-bots get to see more Git action than most machines, so it could run fairly frequently, but there's zero harm in trying and seeing how it goes.

**Pull request closed without merging**
