### PR TITLE
disque: add very first alpha release

### PR DESCRIPTION
**Pull request by ear**
From the author of [Redis](http://redis.io/) a new project: [Disque, an in-memory, distributed job queue](https://github.com/antirez/disque).

The `HEAD` version is the only available one right now. The project is in alpha status.

This formula follows the same track as the one for [`redis`](https://github.com/Homebrew/homebrew/blob/5599ee994ed56c93e2544f1c595af9d9b836e68e/Library/Formula/redis.rb)

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Needs to be submitted to homebrew-head-only until there's a stable release.

**Comment by ear** [comment]
Thank you, done: Homebrew/homebrew-head-only#115

**Comment by xyb** [comment]
@mikemcquaid, disque [1.0-rc1 released](https://github.com/antirez/disque/releases/tag/1.0-rc1), is it ok to be added into main repo now?

**Comment by mikemcquaid** [comment]
@xyb We need a stable version e.g. 1.0/1.0.0

**Comment by xyb** [comment]
@mikemcquaid, understand it, thank you.

**Pull request closed without merging**
