### PR TITLE
kubernetes-cli 1.0.6

### PR DESCRIPTION
**Pull request by antoineco**
[Latest release](https://github.com/kubernetes/kubernetes/releases/tag/v1.0.6)

### CODE REVIEW

**Comment by dunn** [comment]
Install is failing on all platforms: http://bot.brew.sh/job/Homebrew%20Pull%20Requests/33462/

**Comment by antoineco** [comment]
Might be related to kubernetes/kubernetes#11580 since the Formula uses [Go 1.5.1](https://travis-ci.org/Homebrew/homebrew/jobs/81257806#L262)

Would it be an option to use the pre-built binaries?

**Comment by dunn** [comment]
I'm afraid not. Since the fix has been merged upstream, though, we can use the commit as a patch:
```
stable do
  url "https://github.com/kubernetes/kubernetes/archive/v1.0.6.tar.gz"
  sha256 "cb6d03ddc920ef5eca13d12688419dff0b21daf3bf45ad731bfcae57f15ce8ea"

  patch do
    url "https://github.com/kubernetes/kubernetes/commit/defe0f82bf99ce2ec5179d92475c00ce9beaf318.diff"
    sha256 "????"
  end
end
```

**Comment by antoineco** [comment]
Thanks for pointing this out, it works! Amending my commit right away.

**Comment by antoineco** [comment]
Jenkins job #3​35​39 will break (amended commit), whoever reads that, feel free to remove it from the queue.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/18011bafca395f062ae1e4642328ff40e94a85d4. Thank for your contribution to Homebrew @antoineco!

**Pull request closed without merging**
