### PR TITLE
qpdf 5.1.3

### PR DESCRIPTION
**Pull request by chdiza**

### CODE REVIEW

**Comment by bfontaine** [comment]
@BrewTestBot test this please.

**Comment by DomT4** [comment]
@bfontaine Already requeued the last 4 failures on the bot. There's a little `Rebuild` button on the left-hand side which you can use without calling the bot publicly.

**Comment by bfontaine** [comment]
@DomT4 Thanks, I’m not familiar with the Web interface.

**Comment by bfontaine** [comment]
Thanks @chdiza!

**Pull request closed without merging**
