### PR TITLE
libetonyek 0.1.6

### PR DESCRIPTION
**Pull request by luzpaz**

### CODE REVIEW

**Comment by luzpaz** [comment]
@dtardon what's the issue? https://travis-ci.org/Homebrew/homebrew/jobs/102503942#L868
```
checking for LANGTAG... no

configure: error: Package requirements (

    liblangtag

) were not met:

No package 'liblangtag' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables LANGTAG_CFLAGS
and LANGTAG_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```

**Comment by luzpaz** [comment]
Heads up: should probably merge https://github.com/Homebrew/homebrew/pull/48099 before this formula

**Comment by bfontaine** [comment]
@BrewTestBot test this please.

**Comment by luzpaz** [comment]
from dev: 
> liblangtag (https://bitbucket.org/tagoh/liblangtag/wiki/Home) is a new dependency of libetonyek

**Comment by mikemcquaid** [comment]
> Need to add this as a separate block in the formula

Yep :+1:

**Comment by luzpaz** [comment]
This is as far as I've gotten: https://gist.github.com/luzpaz/4a67318ab247dcc08217

**Comment by DomT4** [comment]
What help do you need?

**Comment by luzpaz** [comment]
@DomT4 2 things:

1) The instructions say that the library needs to be built:  

> % gnome-autogen.sh --prefix=/usr --sysconfdir=/etc
% make
% make install

> gnome-autogen.sh command is available in gnome-common.   

I understand there is a formula for gnome-common in homebrew. But must i use this as a dependency ? Meaning it will add many more dependencies to it? Actually, no, after doing ```brew deps gnome-common``` I found that ```xz``` is the only dependency. So that leads me to the next issue

2) How do I translate the above in to the resource block ? (including the ```gnome-common``` dep)

**Comment by bfontaine** [comment]
@luzpaz See also my comment over here about the the `stage do` block: https://github.com/Homebrew/homebrew/pull/45682#discussion_r50645379

**Comment by DomT4** [comment]
> I understand there is a formula for gnome-common in homebrew. But must i use this as a dependency ? 

You can make `gnome-common` a `:build` dependency to handle this. A `:build` dependency means in reality few will actually end up with it installed because the vast majority of the Homebrew userbase pours bottles.

**Comment by luzpaz** [comment]
@DomT4 Thanks! 
I've added ``depends_on "gnome-common" => :build``

What I'm stuck on is the ```resource("liblangtag").stage``` block
https://gist.github.com/luzpaz/4a67318ab247dcc08217#file-gistfile1-txt-L27-L31
```
  def install
    resource("liblangtag").stage 
      system "gnome-autogen.sh", "--prefix=#{prefix}", "--sysconfdir=/etc"
      system "make"
      system "make install"
    end
    system "./configure", "--without-docs",
                          "--disable-dependency-tracking",
                          "--enable-static=no",
                          "--disable-werror",
                          "--disable-tests",
                          "--prefix=#{prefix}"
    system "make", "install"
  end
```

**Comment by bfontaine** [comment]
@luzpaz you need to add `do` after `.stage` to have a block:
```rb
resource("liblangtag").stage do
```

**Comment by luzpaz** [comment]
@bfontaine what about the ---sysconfig flag ? What does that need to be set to ?
```system "gnome-autogen.sh", "--prefix=#{prefix}", "--sysconfdir=/etc"```

**Comment by DomT4** [comment]
> What does that need to be set to ?

Usually `"--sysconfdir=#{etc}"`

**Comment by dtardon** [comment]
On Sat, Jan 23, 2016 at 03:24:06PM -0800, luzpaz wrote:
> @DomT4 2 things:
> 
> 1) The instructions say that the library needs to be built:  
> 
> > % gnome-autogen.sh --prefix=/usr --sysconfdir=/etc
> % make
> % make install

Note that gnome-autogen.sh is only necessary if one is building a git checkout. Released tarballs contain configure.

**Comment by luzpaz** [comment]
@dtardon So in other words, I can swap ``configure`` for ``gnome-autogen.sh``
If so then do i pass the flags to configure as well, like so:
``` system "configure", "--prefix=#{prefix}", "--sysconfdir=#{etc}"

reference: https://gist.github.com/luzpaz/4a67318ab247dcc08217#file-gistfile1-txt-L28

**Comment by dtardon** [comment]
Yes, for both questions. Although I doubt it very much you need to pass --sysconfdir, as it is normally determined from --prefix.

Note: you should probably use

system "make", "install"

for consistency with the following code.

**Comment by luzpaz** [comment]
Ok, so here is the most up to date version of the formula implementing feedback from @dtardon 
https://gist.github.com/luzpaz/4a67318ab247dcc08217

I tried to install it and didn't succeed. See below:
gist logs: https://gist.github.com/luzpaz/63323320480e752c1602

The gist logs don't show all the info AFAICT, so I'm adding more below:
https://gist.github.com/luzpaz/3f3b2c8ea72580e41b38#file-libetonyek-error-L278-L280
```
==> ./configure --prefix=/usr/local/Cellar/libetonyek/0.1.6
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
/private/tmp/libetonyek--liblangtag20160209-17798-9glcqj/liblangtag-0.5.8/missing: Unknown `--is-lightweight' option
Try `/private/tmp/libetonyek--liblangtag20160209-17798-9glcqj/liblangtag-0.5.8/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
checking for a thread-safe mkdir -p... ./install-sh -c -d
```

https://gist.github.com/luzpaz/3f3b2c8ea72580e41b38#file-libetonyek-error-L433-L437
```
checking for the suffix of module shared libraries... error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: unknown option character `-' in: --config
Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -static [-] file [...] [-filelist listfile[,dirname]] [-arch_only arch] [-sacLT] [-no_warning_for_no_symbols]
Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -dynamic [-] file [...] [-filelist listfile[,dirname]] [-arch_only arch] [-o output] [-install_name name] [-compatibility_version #] [-current_version #] [-seg1addr 0x#] [-segs_read_only_addr 0x#] [-segs_read_write_addr 0x#] [-seg_addr_table <filename>] [-seg_addr_table_filename <file_system_path>] [-all_load] [-noall_load]
.
configure: error: Unable to determine shared libreary suffix from libtool
```

**Comment by ilovezfs** [comment]
@DomT4 OK, we got it working together on IRC:
https://gist.github.com/ilovezfs/99eba9ff5e1c415f9693

Only question I had is whether it's all right that the vendored liblangtag is installed into the same prefix as libetonyek, or if it should be sequestered in lib/liblangtag, libexec, libexec/lib, libexec/lib/liblangtag, libexec/liblangtag, libexec/liblangtag/lib. Ditto with respect to its includes.

**Comment by DomT4** [comment]
> Only question I had is whether it's all right that the vendored liblangtag is installed into the same prefix as libetonyek,

Anything vendored should live in `libexec`. If they need to be in the same path vendor into `libexec` and then symlink the main elements back into the top-level prefixes.

**Comment by luzpaz** [comment]
closing

**Pull request closed without merging**
