### PR TITLE
elasticsearch 2.2.0 logstash 2.2.0 kibana 4.4.0

### PR DESCRIPTION
**Pull request by jasontedor**
This pull request updates: 
 - the Elasticsearch formula from version 2.1.1 to version 2.2.0, the [latest stable version of Elasticsearch](https://www.elastic.co/blog/elasticsearch-2-2-0-and-2-1-2-and-1-7-5-released) as of 2016-02-02
 - the Logstash formula from version 2.1.1 to version 2.2.0, the [latest stable version of Logstash](https://www.elastic.co/blog/logstash-2-2-0-and-2-1-2-released) as of 2016-02-02
 - the Kibana formula from version 4.3.1 to version 4.4.0, the [latest stable version of Kibana](https://www.elastic.co/blog/kibana-4-4-0) as of 2016-02-02

### CODE REVIEW

**Comment by jasontedor** [comment]
It looks like two of the builds hung in the download phase (not sure why) but I think the build on 10.9 shows the commits are okay.

**Comment by jasontedor** [comment]
> It looks like two of the builds timed out but I think the build on OS X 10.9 shows the commits are okay.

Thinking about this some more, I'm guess that it's because the the kibana formula takes some time when installing not from a bottle, and since the build is trying to test the elasticsearch and logstash and kibana formulae all in one build, that's why it times out?

**Comment by DomT4** [comment]
> since the build is trying to test the elasticsearch and logstash and kibana formulae all in one build, that's why it times out?

Yup. Don't worry about it too much; Jenkins will get around to it at some point tonight and you won't hit a timeout there.

**Comment by apjanke** [comment]
Yep, Jenkins is happy.

Merged. Thank you for your contribution to Homebrew!

**Pull request closed without merging**
