### PR TITLE
Ntopng

### PR DESCRIPTION
**Pull request by Drewshg312**
HEAD issue fixed.

### CODE REVIEW

**Comment by bfontaine** [comment]
Please rebase your branch on top of master.

**Comment by Drewshg312** [comment]
Thanx for reply. How would I do that?

**Comment by Drewshg312** [comment]
New to git here…
So I've done this:

    $ cd /usr/local
    $ git checkout ntopng
    $ git rebase master
 
do I have to resubmit my pull request? Or it's going to apply automatically?

**Comment by dunn** [comment]
This should work:
```
cd /usr/local
git checkout ntopng
git fetch origin
git rebase origin/master
git push -f 
```

**Comment by Drewshg312** [comment]
Thanx!
I've got:

    $ git push -f
    Username for 'https://github.com': Drewshg312
    Password for 'https://Drewshg312@github.com':
    remote: Permission to Homebrew/homebrew.git denied to Drewshg312.
    fatal: unable to access 'https://github.com/Homebrew/homebrew.git/': The requested URL returned error: 403

So I've done:

$ git remote set-url origin https://github.com/Drewshg312/homebrew.git && git push -f

So now it should work? No resubmitting PR reqired, right?

**Comment by dunn** [comment]
Yep! The new build is in the queue.

**Comment by Drewshg312** [comment]
Thanx! Could you tell me how do you see the new build in the queue (sorry for being such a newbie)

**Comment by dunn** [comment]
No problem! Click "Show all checks" below then "Details" to see the build summary: http://bot.brew.sh/job/Homebrew%20Pull%20Requests/32352/

**Comment by Drewshg312** [comment]
thanx!

**Comment by Drewshg312** [comment]
Well seems like everything should be ok now, but even after I've done `$ brew up` my `ntopng.rb` is still old one… what am I missing now?

**Comment by dunn** [comment]
Merged in b0f4b25f9583b2c9a7684ec200ec1154d7893ca8, thank you for contributing to Homebrew!

**Pull request closed without merging**
