### PR TITLE
walkmod 2.2.0

### PR DESCRIPTION
**Pull request by rpau**

### CODE REVIEW

**Comment by UniqMartin** [comment]
Merged in 3353430e4a560c9f5bc025c6525755caf071c103. Thank you for this contribution to Homebrew, @rpau! :tada:

For future reference, you can omit the colon (`:`) between the formula name and the version for simple version bumps. By the way, you put the old version number in the commit message (can easily happen with such a similar version). :wink:

**Comment by bfontaine** [comment]
Thank you for your contribution to Homebrew, @rpau; we appreciate it! :tada:

**Comment by bfontaine** [comment]
@UniqMartin went faster :smile:

**Comment by rpau** [comment]
xD

**Pull request closed without merging**
