### PR TITLE
mutt 1.5.24

### PR DESCRIPTION
**Pull request by nijikon**

### CODE REVIEW

**Comment by xu-cheng** [comment]
Thanks for the pull request! 🎉 Homebrew depends on contributions from community members like you and we're grateful for your support.

**Comment by guoxiao** [comment]
`brew install mutt --with-trash-patch` fails after this PR.
```
Error: Failure while executing: /usr/bin/patch -g 0 -f -p1 -i /private/tmp/mutt--patch20150907-57210-2c9njc/trashfolder-1.5.22.diff0
```

**Comment by xu-cheng** [comment]
@guoxiao Could you try and open a pull request to fix it? Thanks.

**Comment by dunn** [comment]
I have a PR open to just remove that patch (#43647), but I'm open to alternative solutions.

**Pull request closed without merging**
