### PR TITLE
yank: Fix issue with terminal output

### PR DESCRIPTION
**Pull request by elyscape**
This provides a workaround for mptre/yank#22.

### CODE REVIEW

**Comment by DomT4** [comment]
It looks like upstream are proposing a different solution here. What's the status on that?

**Comment by elyscape** [comment]
Still in the evaluation phase. We could skip this PR if you'd like, though, as it looks like there's going to be a solution in the next release. Your call.

**Comment by DomT4** [comment]
How soon is the next release, and how severe is the issue?

**Comment by elyscape** [comment]
No idea how soon the next release will be but the issue does make it so that it doesn't display correctly. Every time you move, it reprints all the options again below the old ones, instead of printing them over the old ones.

**Comment by DomT4** [comment]
Alright. I'm happy enough to take it whilst you talk to upstream about a more permanent solution, but can you edit the formula to include a link to the upstream bug submission and include a short one or two line summary as to what the patch fixes.

You can't assume any future contributors will come back to find this issue, sadly.

**Comment by elyscape** [comment]
Sure. I'll get that in probably tomorrow.

**Comment by elyscape** [comment]
How's this look, @DomT4?

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/1848c1c1d03995d137dc4be0a2b40ee0120c7d67. Thank you for another Homebrew contribution @elyscape! :smiley_cat:

**Comment by elyscape** [comment]
You're very welcome!

**Pull request closed without merging**
