### PR TITLE
gsl 2.1

### PR DESCRIPTION
**Pull request by dunn**

### CODE REVIEW

**Comment by tschoonj** [comment]
see #45812

This new version is a disaster IMHO and will break probably every single formula that depends on it.

**Comment by dunn** [comment]
Oh yeah, forgot about that. Thanks!

**Comment by bfontaine** [comment]
@tschoonj #45812 is about gsl 2.0; is gsl 2.1 affected by these issues too?

**Comment by tschoonj** [comment]
yep it is

If you really want to provide support for this release, I suggest you create a formula `gsl2`, and explicitly mark it as conflicting with the original `gsl`

**Pull request closed without merging**
