### PR TITLE
go 1.4.2

### PR DESCRIPTION
**Pull request by nicolai86**
The bottle SHA's are still wrong, not quite sure how I can get the brew test bot to generate new ones yet…

### CODE REVIEW

**Comment by ahmetalpbalkan** [comment]
ah that's fast! I was just gonna start on this.

**Comment by nicolai86** [comment]
@ahmetalpbalkan still need the bottle sha's to be complete tho :)

**Comment by nicolai86** [comment]
bottle SHA1s are correct now as well. Good to go :)

**Comment by jacknagel** [comment]
The bottle checksums are updated automatically, so you can undo any changes there.

**Comment by nicolai86** [comment]
@jacknagel done

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

For future reference the preferred commit message format for simple version updates is `go 1.4.2`.

**Comment by nicolai86** [comment]
@mikemcquaid will keep that in mind for future PRs. thanks :)

**Pull request closed without merging**
