### PR TITLE
leiningen 2.5.2

### PR DESCRIPTION
**Pull request by brunchboy**
Updates Leiningen to the newly released version 2.5.2

### CODE REVIEW

**Comment by mistydemeo** [comment]
Can you update the URL and checksum for the leiningen script, too?

**Comment by brunchboy** [comment]
Whoops, sorry about missing that, I will fix that right away.

**Comment by mistydemeo** [comment]
Thanks!

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/ceb07f09372a1f2edb9f19c73cf893540532d05d. Thank you for your contribution to Homebrew, we appreciate it! :smiley_cat:

**Pull request closed without merging**
