### PR TITLE
telepathy-gabble 0.99.11

### PR DESCRIPTION
**Pull request by bfontaine**
See #46168.

### CODE REVIEW

**Comment by bfontaine** [comment]
```
...snip...
clang -DHAVE_CONFIG_H -I. -I.. -I../wocky   -Wall -Wextra -Wdeclaration-after-statement -Wshadow -Wstrict-prototypes -Wmissing-prototypes -Wsign-compare -Wnested-externs -Wpointer-arith -Wformat-security -Winit-self -Wno-missing-field-initializers -Wno-unused-parameter  -D_REENTRANT -I/usr/local/Cellar/glib/2.46.2/include/glib-2.0 -I/usr/local/Cellar/glib/2.46.2/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/include/libxml2 -I/usr/local/Cellar/openssl/1.0.2d_1/include -I.. -I.. -g -O2 -c wocky-bare-contact-test.c
wocky-test-sasl-auth-server.c:53:15: error: typedef redefinition with different types ('int (*)(void)' vs 'int (*)()')
typedef int (*sasl_callback_ft)(void);
              ^
/usr/include/sasl/saslplug.h:36:15: note: previous definition is here
typedef int (*sasl_callback_ft)(); // APPLE: remove void
              ^
1 error generated.
```

**Comment by bfontaine** [comment]
#44014

**Comment by bfontaine** [comment]
It depends on `telepathy-glib` ≥0.99.11; I’ll make another PR for it.

**Comment by mikemcquaid** [comment]
:+1:

**Pull request closed without merging**
