### PR TITLE
poppler 0.39.0

### PR DESCRIPTION
**Pull request by afh**

### CODE REVIEW

**Comment by apjanke** [comment]
The `brew test` step for dependent formulae `diff-pdf` and `pdf2htmlex` are failing with a link error.

```
        Testing diff-pdf
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20151217-10322-1tkroxf-0.sb /usr/local/Cellar/ruby187/1.8.7-p374_1/bin/ruby -W0 -I /usr/local/Library/Homebrew -- /usr/local/Library/Homebrew/test.rb /usr/local/Library/Formula/diff-pdf.rb --verbose
==> /usr/local/Cellar/diff-pdf/0.2_5/bin/diff-pdf -h
dyld: Library not loaded: /usr/local/opt/poppler/lib/libpoppler.57.dylib
  Referenced from: /usr/local/Cellar/diff-pdf/0.2_5/bin/diff-pdf
  Reason: image not found
Error: diff-pdf: failed
Failed executing: /usr/local/Cellar/diff-pdf/0.2_5/bin/diff-pdf -h
/usr/local/Library/Homebrew/formula.rb:1471:in `system'
/usr/local/Library/Homebrew/formula.rb:1408:in `open'
/usr/local/Library/Homebrew/formula.rb:1408:in `system'
/usr/local/Library/Formula/diff-pdf.rb:33:in `test'
/usr/local/Library/Homebrew/formula.rb:1317:in `run_test'
/usr/local/Library/Homebrew/extend/fileutils.rb:17:in `mktemp'
/usr/local/Library/Homebrew/formula.rb:1313:in `run_test'
/usr/local/Library/Homebrew/test.rb:28
/usr/local/Cellar/ruby187/1.8.7-p374_1/lib/ruby/1.8/timeout.rb:67:in `timeout'
/usr/local/Library/Homebrew/test.rb:27
```

It looks like they were linked against the exact dylib version of the `poppler` library they were built against, which got incremented by this version bump, from `libpoppler.57.dylib` to `libpoppler.58.dylib`.

This could probably be fixed, by bumping the revisions for `diff-pdf` and `pdf2htmlex` in this PR. Looks like [that's what's been done for previous `poppler` updates](https://github.com/Homebrew/homebrew/commits/master/Library/Formula/diff-pdf.rb). That would force a rebuild for both bottle users and folks building from source. (Bumping the bottle revision would fix the bottles, but users who built `diff-pdf` or `pdf2htmlex` from source would still be linking to the old `poppler` lib.) There's also a new version of `diff-pdf` out, which you could just pull in to get the same effect.

Poppler seems odd in that it increments the major dylib version number on each release. [But this bug from MacPorts](https://trac.macports.org/ticket/25495) suggests that it's called for, since the API changes in incompatible ways.

> At least they incremented the version number this time -- poppler has a really annoying habit of changing its API in every version and breaking things that depend on it.

**Comment by luzpaz** [comment]
@afh do you mind bumping the revision # for diff-pdf and pdf2htmlex? 
As @apjanke mentioned, see https://github.com/Homebrew/homebrew/commit/ad78f01dce924e5c2a2aae11b9c6cda5dcea5933 and https://github.com/Homebrew/homebrew/commit/ccc7ddd86f0829d360f307dd780b51c460bcc5bd

**Comment by afh** [comment]
For 10.10 and 10.11 the Travis CI jobs "exceeded the maxmimum time limit for jobs, and [were] terminated."

**Comment by apjanke** [comment]
Yeah; it's just a long set of builds. 10.9 CI is passing, and Jenkins is passing, so we'll go ahead and merge this anyway.

**Comment by apjanke** [comment]
Merged. Thank you for your contribution to Homebrew!

**Comment by afh** [comment]
Thanks for merging.

**Pull request closed without merging**
