### PR TITLE
Changed Docker tag to 1.7.0

### PR DESCRIPTION
**Pull request by mijndert**
Has to wait for Boot2Docker before getting merged.

### CODE REVIEW

**Comment by DomT4** [comment]
The `revision` (commit) needs updating as well here.

**Comment by ahmetalpbalkan** [comment]
@mijndert why wait for boot2docker? It's totally independent of b2d.

**Comment by DomT4** [comment]
^ https://github.com/homebrew/homebrew/blob/master/Library/Formula/docker.rb#L4-L5

**Comment by ahmetalpbalkan** [comment]
alright but it's not a dependency?

it's just telling maintainer to not to forget to update boot2docker as well.

**Comment by DomT4** [comment]
Users generally expect `docker` and `boot2docker` to be kept in-check with each other - Differing versions can be incompatible - We try to respect that expectation. Whilst not a formal dependency it is popular enough and requested enough that we tie the two.

**Comment by mijndert** [comment]
I updated the revision. Sorry about that.

**Comment by dunn** [comment]
#40889 has also been opened, FYI

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/2b84adc1557bca5326344ba5a6a3fee683ab0e7f. Thank you for your contribution to Homebrew, we appreciate it! :smiley_cat:

**Pull request closed without merging**
