### PR TITLE
go 1.5

### PR DESCRIPTION
**Pull request by mistydemeo**
Another take at #43095.

### CODE REVIEW

**Comment by googollee** [comment]
+1

**Comment by wsvn53** [comment]
+1

**Comment by pilwon** [comment]
:+1:  x 1000

**Comment by yurykozyrev** [comment]
+1

**Comment by sleeper** [comment]
+1, can't wait ;)

**Comment by Arkan** [comment]
:+1:

**Comment by mikemcquaid** [comment]
Stop :+1:ing please.

**Comment by lloeki** [comment]
To +1ers, if you're that much in a hurry, just do:

    brew unlink go
    brew install https://raw.githubusercontent.com/mistydemeo/homebrew/go_15/Library/Formula/go.rb

BTW, if that's on anyone's radar, tested this on 10.11 and it works fine.

**Pull request closed without merging**
