### PR TITLE
ploticus: add prefabs to installation

### PR DESCRIPTION
**Pull request by bikeNomad**
The existing formula for Ploticus 2.42 omits the installation of
the "prefabs" directory, which most users will need.

This patch ensures that the prefabs are installed into ${pkgshare},
and that ploticus knows where to find them without having to set
the PREFABS_DIR environment variable.

### CODE REVIEW

**Comment by DomT4** [comment]
Is it worth bumping the revision if this is something most users will expect to already have/need for functionality?

**Comment by DomT4** [comment]
> that ploticus knows where to find them without having to set the PREFABS_DIR environment variable.

We could env script the binaries instead, which might possibly be a bit nicer than the patch? See an example [here](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/gmail-backup.rb#L14-L15).

**Comment by apjanke** [comment]
The Ploticus header files, at least this one, expect to be edited at build/install time.

From `src/pl.h`:
```
#define PREFABS_DIR ""  	 /* INSTALLERS can set this to a valid pathname, so that users don't need to set PLOTICUS_PREFABS env var */
```

To my reading, that means that as a packager, the right thing for us to do is to patch that, and still leave `PLOTICUS_PREFABS` as a user-settable variable. A distribution with a more advanced build script would do this with a `./configure` option, but Ploticus doesn't have a `./configure`, just a `Makefile`, which is also intended for manual editing. 

IMHO, it's worth an upstream bug report suggesting that all the variables intended to be edited or overridden at build time be collected in the `Makefile` or another central location, so you don't have to go through multiple headers to find out what's configurable. (I think `pl.h` is the only such configurable header, but it still feels odd to be messing directly with header files as part of the build process.)

Do we also need to do the same thing in `src/pl.h+`, which has some of the same defines?

And yeah, should have a revision bump, at least to get this in to the bottle.

**Comment by bfontaine** [comment]
Ping re Andrew’s comment?

**Comment by m000** [comment]
@DomT4 Prefabs are an absolute must-have for ploticus. AFAIK, this is how most users use the tool. With the situatuon as it is now, I'd consider the formula broken.

There are two issues here: (a) prefab copying, (b) automatic prefab discovery. (The patch fixes both.)

IMHO, if there is no consensus on a "proper" way to fix (b), this should not be a blocker for fixing (a). Personally, I find patching the header acceptable. But I'm also fine with having to manually set PLOTICUS_PREFABS.

@apjanke The `Makefile` mentions that PREFABS_DIR should be set in `pl.h`. If there was something else that had to be set, I guess it would have also been mentioned in the `Makefile`. `pl.h+` doesn't seem to be used anywhere.

**Comment by bikeNomad** [comment]
@apjanke OK, bumped revision.
My own preference is for patching pl.h rather than making folks remember to have their PREFABS_DIR environment variable set correctly, or generating wrapper scripts.

**Comment by DomT4** [comment]
You'll need to rebase against the master here. You've accidentally pulled in a large number of unrelated commits and the CI can no longer pull this cleanly for testing.

**Comment by bikeNomad** [comment]
Rebased; sorry.
oops. pushing before coffee.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/5f3c67d6817cf722d81775120a8e3954a35cb8eb. Thank you for your contribution to Homebrew @bikeNomad; we appreciate it! :smiley:

**Pull request closed without merging**
