### PR TITLE
add hyperscan 4.0.1

### PR DESCRIPTION
**Pull request by flier**

### CODE REVIEW

**Comment by apjanke** [comment]
Merged. Thank you for your contribution to Homebrew!

**Comment by DomT4** [comment]
Just for future reference @flier for Python dependencies we _almost never_ want `depends_on "python"`. It should be either:
```ruby
depends_on :python
```
Or more frequently if it needs Python 2.7 to compile but it doesn't matter where that 2.7 comes from:
```ruby
depends_on :python if MacOS.version <= :snow_leopard
```
If it doesn't need Python 2.7 and can use Python 2.6 or below the dependency doesn't need writing at all :smiley:.

Thanks!

**Comment by apjanke** [comment]
Sorry for missing that when I reviewed; I should have caught that.

**Comment by DomT4** [comment]
No worries at all. These things are easily missed, especially when there are legitimate cases of `depends_on "python"` in places.

**Comment by flier** [comment]
got it, thanks guys

**Pull request closed without merging**
