### PR TITLE
Pull/tinc

### PR DESCRIPTION
**Pull request by afh**

### CODE REVIEW

**Comment by mikemcquaid** [comment]
The test is failing for `devel`: http://bot.brew.sh/job/Homebrew%20Pull%20Requests/20242/version=yosemite/testReport/junit/brew-test-bot/yosemite/test___devel_tinc/

**Comment by afh** [comment]
Hmm the `-K` options was removed. The only "good" test I can think of for both stable and devel is checking version output `tincd --version`, since this is a network daemon that doesn't provide a conf-file parsing options. Would that be enough for a test or would you prefer different tests depending on what is installed (stable or devel).?

**Comment by mikemcquaid** [comment]
Yeh, just go for `--version` I guess.

**Comment by afh** [comment]
Done.

**Pull request closed without merging**
