### PR TITLE
Add bazel

### PR DESCRIPTION
**Pull request by pgr0ss**

### CODE REVIEW

**Comment by pgr0ss** [comment]
I just realized this isn't properly creating a `.bazelrc`. Let me see if I can figure that out.

**Comment by pgr0ss** [comment]
I'm a little stuck. I think I need to add something like:

```diff
diff --git a/Library/Formula/bazel.rb b/Library/Formula/bazel.rb
index c6a6819..1ef1da8 100644
--- a/Library/Formula/bazel.rb
+++ b/Library/Formula/bazel.rb
@@ -6,12 +6,27 @@ class Bazel < Formula
 
   head "https://github.com/bazelbuild/bazel.git"
 
+  option "without-bazelrc", "Do not create a .bazelrc in ~"
+
   depends_on :macos => :mavericks
   depends_on :java => "1.8+"
 
   def install
     system "./compile.sh"
+
     bin.install "./output/bazel"
+
+    prefix.install "base_workspace"
+
+    if build.with? "bazelrc"
+      File.open(File.expand_path("~/.bazelrc"), "w") do |file|
+        file.puts(<<-END)
+build --package_path %workspace%:/usr/local/Cellar/bazel/0.1.0/base_workspace
+fetch --package_path %workspace%:/usr/local/Cellar/bazel/0.1.0/base_workspace
+query --package_path %workspace%:/usr/local/Cellar/bazel/0.1.0/base_workspace
+        END
+      end
+    end
   end
 
   test do
```

But `base_workspace` isn't getting copied.

Bazel releases an installer which properly creates the base_workspace (and bazelrc), but a binary installer seems to violate the homebrew principals: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Acceptable-Formulae.md#we-dont-like-binary-formulae

If anyone has an idea of how to get this working, please let me know. If not, I'll try to find more time later to keep investigating.

**Comment by mikemcquaid** [comment]
@pgr0ss We don't allow writing into `~`. You could instead use `Pathname.write` and `EOS.undent` to write something into e.g. `pkgshare/"examples"` and suggest copying it in caveats. You'll need to use `opt_prefix/"base_workspace"` as the path (rather than hardcoding the Cellar and version). Is there any way to coax Bazel into using a configuration file in e.g. `/usr/local/etc`?

**Comment by pgr0ss** [comment]
I couldn't find a way to coax bazel into using `/usr/local/etc`. Do you know why `prefix.install "base_workspace"` isn't working for me?

**Comment by mikemcquaid** [comment]
`.install` moves rather than copies.

**Comment by pgr0ss** [comment]
I haven't had a chance to figure out how to get this working. I'm going to close for now.

**Pull request closed without merging**
