### PR TITLE
jetty 9.3.3.v20150827

### PR DESCRIPTION
**Pull request by makigumo**

### CODE REVIEW

**Comment by makigumo** [comment]
I have no clue, what might be the problem here. Maybe a sandboxing issue?

**Comment by dunn** [comment]
Do you get the same error locally with `brew test -v --sandbox jetty`?

**Comment by makigumo** [comment]
That's it. With ```--sandbox``` it fails.

```
$ brew test jetty -v
Testing jetty
Starting Jetty: 2015-09-12 08:38:40.120:INFO::main: Logging initialized @589ms
2015-09-12 08:38:40.173:WARN:oejs.HomeBaseWarning:main: This instance of Jetty is not running from a separate {jetty.base} directory, this is not recommended.  See documentation at http://www.eclipse.org/jetty/documentation/current/startup.html
2015-09-12 08:38:40.324:INFO::main: Redirecting stderr/stdout to /usr/local/Cellar/jetty/9.3.3.v20150827/libexec/logs/2015_09_12.stderrout.log
OK 2015年 9月12日 土曜日 08時38分43秒 CEST
==> /usr/local/Cellar/jetty/9.3.3.v20150827/bin/jetty check
==> /usr/local/Cellar/jetty/9.3.3.v20150827/bin/jetty stop
```

```
$ brew test -v --sandbox jetty
Testing jetty
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20150912-2714-1ykq29n.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Library/Homebrew -- /usr/local/Library/Homebrew/test.rb /usr/local/Library/Formula/jetty.rb -v --sandbox
Starting Jetty: java.nio.file.FileSystemException: /usr/local/Cellar/jetty/9.3.3.v20150827/libexec/start_8080264116088275042.properties: Operation not permitted
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:362)
	at java.nio.file.Files.createFile(Files.java:633)
	at java.nio.file.TempFileHelper.create(TempFileHelper.java:138)
	at java.nio.file.TempFileHelper.createTempFile(TempFileHelper.java:161)
	at java.nio.file.Files.createTempFile(Files.java:853)
	at org.eclipse.jetty.start.StartArgs.getMainArgs(StartArgs.java:596)
	at org.eclipse.jetty.start.Main.invokeMain(Main.java:204)
	at org.eclipse.jetty.start.Main.start(Main.java:457)
	at org.eclipse.jetty.start.Main.main(Main.java:75)

Usage: java -jar start.jar [options] [properties] [configs]
       java -jar start.jar --help  # for more information
FAILED 2015年 9月12日 土曜日 08時39分24秒 CEST
==> /usr/local/Cellar/jetty/9.3.3.v20150827/bin/jetty check
==> Sandbox log
Sep 12 08:39:20 sandboxd[150]: java(2754) deny file-write-create /usr/local/Cellar/jetty/9.3.3.v20150827/libexec/start_8080264116088275042.properties
Error: jetty: failed
<0> expected but was
<1>.
```

Jetty is creating a runtime file ```/usr/local/Cellar/jetty/9.3.3.v20150827/libexec/start_8080264116088275042.properties```, which is prevented by the sandboxing mechanism. I had a quick look, but there seems to be no switch to disable the file generation. The directory it writes to is always JETTY_BASE which is ```/usr/local/Cellar/jetty/9.3.3.v20150827/libexec```.

So I'm afraid there might be no easy solution :(

**Comment by dunn** [comment]
Maybe add `ENV["JETTY_BASE"] = testpath` at the beginning of the test block?

**Comment by DomT4** [comment]
That leads to:

```
==> /usr/local/Cellar/jetty/9.3.2.v20150730/bin/jetty check
Cannot find a start.ini file or a start.d directory in your JETTY_BASE directory: /private/tmp/jetty20150912-17011-rke6hh
```

Sadly. Moving the `start.ini` file over doesn't help much either, although we get further:

```
Starting Jetty: MKDIR: ${jetty.base}/lib
MKDIR: ${jetty.base}/lib/ext
MKDIR: ${jetty.base}/resources
MKDIR: ${jetty.base}/webapps
INFO: Base directory was modified
FAILED Sat Sep 12 22:24:58 BST 2015
==> /usr/local/Cellar/jetty/9.3.2.v20150730/bin/jetty check
Error: jetty: failed
<0> expected but was
<1>.
```

**Comment by makigumo** [comment]
Thanks for the pointer, I now just create a temporary copy of JETTY_BASE for the test. I hope this is ok.

**Comment by DomT4** [comment]
This is where I ended up, which works, but is kind of clunky to move the entire directory to the testpath:

```diff
diff --git a/Library/Formula/jetty.rb b/Library/Formula/jetty.rb
index ed85cf2..a47b58a 100644
--- a/Library/Formula/jetty.rb
+++ b/Library/Formula/jetty.rb
@@ -31,6 +31,9 @@ class Jetty < Formula
   end

   test do
+    ENV["JETTY_BASE"] = testpath
+    cp_r Dir[libexec/"*"], testpath
+
     pid = fork { exec bin/"jetty", "start" }
     sleep 5 # grace time for server start
     begin
```

**Comment by makigumo** [comment]
Oh thanks, I will use that. A lot cleaner and smaller than what I came up with :)

**Comment by dunn** [comment]
Merged in 3f257caa723f7f73077bd96e1b1b76889d5ab512, thanks!

**Pull request closed without merging**
