### PR TITLE
Update WeeChat formula to 1.1

### PR DESCRIPTION
**Pull request by Mikaela**
I am not sure where I should point devel, so I didn't change it. If it should be changed to something or even be removed, please do tell me.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Just remove it for now, thanks!

**Comment by Mikaela** [comment]
Done

**Comment by mikemcquaid** [comment]
Looks like the `inreplace` is failing so it can probably be removed as it wasn't needed for `devel`: http://bot.brew.sh/job/Homebrew%20Pull%20Requests/19648/version=yosemite/testReport/junit/brew-test-bot/yosemite/install_weechat/

**Comment by Mikaela** [comment]
Removed. I also removed the comments as I think they were for the removed section.

**Comment by mikemcquaid** [comment]
Yup, they were, thanks!

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew and great work here!

**Comment by Mikaela** [comment]
You're welcome :)

**Pull request closed without merging**
