### PR TITLE
update terraform to v0.6.7

### PR DESCRIPTION
**Pull request by nicolai86**

### CODE REVIEW

**Comment by steve-jansen** [comment]
+1

**Comment by antonbabenko** [comment]
I just tried it myself and here is the response:
```
Last 15 lines from /Users/Bob/Library/Logs/Homebrew/terraform/03.go:
		Body: {"errors":["Resource not found!"]}
2015/11/25 16:37:14 [DEBUG] Handling Atlas conflict response: Conflict
2015/11/25 16:37:14 [DEBUG] Atlas reported conflict, checking for equivalent states.
2015/11/25 16:37:14 [DEBUG] States are equivalent, incrementing serial and retrying.
2015/11/25 16:37:14 [DEBUG] Handling Atlas conflict response: Conflict
2015/11/25 16:37:14 [DEBUG] Atlas reported conflict, checking for equivalent states.
2015/11/25 16:37:14 [DEBUG] States are not equivalent, returning conflict.
2015/11/25 16:37:14 [DEBUG] Handling Atlas conflict response: Conflict
2015/11/25 16:37:14 [DEBUG] Atlas reported conflict, checking for equivalent states.
2015/11/25 16:37:14 [DEBUG] States are equivalent, incrementing serial and retrying.
2015/11/25 16:37:14 [DEBUG] Handling Atlas conflict response: Conflict
2015/11/25 16:37:14 [DEBUG] Already attempted conflict resolution; returning conflict.
FAIL
FAIL	github.com/hashicorp/terraform/state/remote	1.914s
ok  	github.com/hashicorp/terraform/terraform	0.833s

READ THIS: https://git.io/brew-troubleshooting
```

**Comment by steve-jansen** [comment]
@antonbabenko Worked for me on OS 10.10.5:

```
$ brew upgrade https://raw.githubusercontent.com/nicolai86/homebrew/patch-4/Library/Formula/terraform.rb
######################################################################## 100.0%
==> Upgrading 1 outdated package, with result:
terraform 0.6.7
==> Upgrading terraform
==> Downloading https://homebrew.bintray.com/bottles/terraform-0.6.7.yosemite.bottle.tar.gz

curl: (22) The requested URL returned error: 401 Unauthorized
Error: Failed to download resource "terraform"
Download failed: https://homebrew.bintray.com/bottles/terraform-0.6.7.yosemite.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://github.com/hashicorp/terraform/archive/v0.6.7.tar.gz

... lots of cloning ...

==> Checking out revision 975617b05ea8a58727e6c1a06b6161ff4185a9f2
==> go build
==> go build
==> go test ./...
==> gox -arch amd64 -os darwin -output bin/terraform-{{.Dir}} ./...
==> gox -arch amd64 -os darwin -output bin/terraform-{{.Dir}} ./...
🍺  /usr/local/Cellar/terraform/0.6.7: 28 files, 447M, built in 13.1 minutes
```

**Comment by elblivion** [comment]
+1

**Comment by antonbabenko** [comment]
Does not work still for me on 10.11.1. I tried both sources: `brew upgrade https://raw.githubusercontent.com/nicolai86/homebrew/patch-4/Library/Formula/terraform.rb` and `brew install https://raw.githubusercontent.com/nicolai86/homebrew/cac63b5a5ab133c450e4a61a5f3490039af0c5ab/Library/Formula/terraform.rb`.

Can someone confirm that it works on El Capitan ?

**Comment by antonbabenko** [comment]
I even run `brew uninstall --force terraform` and `brew doctor`, but still no luck on El Capitan.

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

For future reference the preferred commit message format for simple version updates is `terraform 0.6.7`.

**Comment by antonbabenko** [comment]
Sorry for disturbance a few hours ago. It works on my home mac (same version), but didn't work at work. Probably I will have to cleanup something to get it to work there as well. Great job @nicolai86 !

**Comment by nicolai86** [comment]
@antonbabenko I'm glad it works for you. Cheers!

**Pull request closed without merging**
