### PR TITLE
xcode: expect xcode 7.1

### PR DESCRIPTION
**Pull request by UniqMartin**

### CODE REVIEW

**Comment by DomT4** [comment]
Need to update Clang version and documentation here as well :)

**Comment by UniqMartin** [comment]
Dang, you are right …

**Comment by UniqMartin** [comment]
Updated. Hopefully I've been more thorough this time.

**Comment by DomT4** [comment]
LGTM, Thanks. Will let it pass the CI first, just in case.

**Comment by UniqMartin** [comment]
Thanks for bearing with me and my noob errors/naivety!

> Will let it pass the CI first, just in case.

Yeah, if it had the potential of breaking all future builds, I'd also let the CI check first.

**Comment by DomT4** [comment]
Easy mistake to make :smile:. In future we'll have to wait for Travis to update as well, but we're skipping `brew doctor` checks on Travis at the moment.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/dec0442d0b289ccf4fd53fea817114ea487cc9c4. Thanks again @UniqMartin! :star2:

**Pull request closed without merging**
