### PR TITLE
update-bash: add shebang to appease shellcheck

### PR DESCRIPTION
**Pull request by tamird**

### CODE REVIEW

**Comment by UniqMartin** [comment]
I think this sends the wrong signal in that things that have a shebang are supposed to be executable and stand-alone. This file is neither. I'd suggest to just use `shellcheck -s bash <file>` instead.

**Comment by apjanke** [comment]
Agreed. I think this file should not have a shebang.

**Comment by mikemcquaid** [comment]
Passing on this but thanks!

**Comment by tamird** [comment]
Makes sense, thanks!

**Pull request closed without merging**
