### PR TITLE
Add devel block for sdl2.

### PR DESCRIPTION
**Pull request by mikepurvis**
Advertised by the project here:

https://www.libsdl.org/hg.php

### CODE REVIEW

**Comment by bfontaine** [comment]
You probably need to change this line:
```rb
system "./autogen.sh" if build.head?
```

into this one:
```rb
system "./autogen.sh" if build.head? || build.devel?
```

**Comment by mikepurvis** [comment]
Hmm, curiously it seemed to work for me (at least on a `reinstall`) without that, but I've changed it now.

**Comment by mikepurvis** [comment]
An alternative binary that could be used for this is the one linked from this page:

https://www.libsdl.org/tmp/download-2.0.php

The URL isn't much more permanent-looking, but the one I proposed is a slightly newer snapshot.

**Comment by apjanke** [comment]
Merged. Thank you for your contribution to Homebrew!

**Pull request closed without merging**
