### PR TITLE
fdk-aac 0.1.4

### PR DESCRIPTION
**Pull request by Noctem**
Update to latest stable release, install example AAC encoder, add test with new WAV fixture, modernize.

The WAV is monaural, 250ms long, 16 bit, 8000Hz sample rate, and plays a tone that logarithmically scales from 50Hz to 2kHz.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Is that the smallest possible WAV? Would be good to get it even smaller if possible.

**Comment by Noctem** [comment]
@mikemcquaid Since WAVs are uncompressed by design, that leaves us with three options: reducing the length, bit depth, and/or sampling rate. Keeping it at 250ms but reducing the sampling rate to 6000Hz and bit depth to 8 bits would bring the file size down to 1546 bytes from 4046. I considered doing this initially but I wasn't sure if there would be any incompatibilities with such a low sample rate and bit depth.

**Comment by mikemcquaid** [comment]
@Noctem I'd take the length down to as short as possible and maybe make it of silence as well (if that changes the size; it might after Git does its compression)

**Comment by Noctem** [comment]
@mikemcquaid Alright, I came up with a bit of a compromise that got the size down to 846 bytes. I kept the 8000Hz sample rate but cut the bit depth in half and reduced the length to 100ms. Changing the content doesn't alter the size of the actual WAV, but to increase compressibility I made it a solid tone which is almost as compressible as silence.

**Comment by mikemcquaid** [comment]
> Edit: Apparently my concerns about 8bit WAV compatibility were well-founded. So the bit depth will have to remain at 16, but I reduced the length again to 64ms. Now it's 1070 bytes, is that acceptable?

Sounds great :+1:

**Comment by mikemcquaid** [comment]
(Let me know when that's the case and I'll merge)

**Comment by Noctem** [comment]
@mikemcquaid I fixup'd and reworded the compatible 1070 byte WAV into d247216. It's good to go.

**Comment by mikemcquaid** [comment]
Thanks @Noctem!

**Pull request closed without merging**
