### PR TITLE
thc-pptp-bruter: use https, modernized

### PR DESCRIPTION
**Pull request by vszakats**
Test not added, I'm not familiar with the package's purpose.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
@vszakats Does it install any binaries?

**Comment by vszakats** [comment]
Yes, it does, a single executable into bin:
```
$ ./thc-pptp-bruter 
Target IP missing.
thc-pptp-bruter [options] <remote host IP>
  -v        Verbose output / Debug output
  -W        Disable windows hack [default: enabled]
  -u <user> User [default: administrator]
  -w <file> Wordlist file [default: stdin]
  -p <n>    PPTP port [default: 1723]
  -n <n>    Number of parallel tries [default: 5]
  -l <n>    Limit to n passwords / sec [default: 100]

Windows-Hack reuses the LCP connection with the same caller-id. This
gets around MS's anti-brute forcing protection. It's enabled by default.
```

**Comment by mikemcquaid** [comment]
Then calling that on e.g. 127.0.0.1 should allow you to run a simple test.

**Comment by vszakats** [comment]
It requires `sudo`, but even then, it fails with exit code 255 when calling it with 127.0.0.1:
```
$ sudo thc-pptp-bruter 127.0.0.1 || echo $?
Failed to open pptp connection: Connection refused
255
```

**Comment by mikemcquaid** [comment]
Ok, fair enough. Can we use `--help` or `--version` or similar without `sudo`?

**Comment by vszakats** [comment]
Calling it without arguments will do the job. Next issue: openssl linkage.

**Comment by vszakats** [comment]
In trying to `brew install` this formula to test openssl linkage after these pending changes, I've stumbled into an issue.

How to run `brew install` as an admin user to be able to access `/usr/local/`, while being logged in as a normal (none-admin, non-sudoer) user?

Tried `su <admin> brew install ...` and `sudo -u <admin> brew install ...` to no avail.

The band-aid solution would be to copy the formula `.rb` under the admin account and `brew install` as usual. I'd like to avoid that copying, if possible.

**Comment by mikemcquaid** [comment]
I'm not sure, I just do everything as an admin user.

**Comment by vszakats** [comment]
Copying seems unavoidable.

**Comment by vszakats** [comment]
All issues cleared:
```
$ brew audit --strict thc-pptp-bruter.rb 
==> brew style thc-pptp-bruter

1 file inspected, no offenses detected
```

**Comment by mikemcquaid** [comment]
Great work here and particular thanks for the test!

**Pull request closed without merging**
