### PR TITLE
dub 0.9.24-rc4 (devel)

### PR DESCRIPTION
**Pull request by John-Colvin**

### CODE REVIEW

**Comment by dunn** [comment]
Odd that this is coming up now (it's the stable build that's failing):
```
==> ./build.sh
Generating version file...
fatal: Not a git repository (or any of the parent directories): .git
Running dmd...
source/dub/generators/generator.d(423): Error: template std.path.globMatch cannot deduce function from argument types !()(DirEntry, string), candidates are:
/usr/local/Cellar/dmd/2.068.1/include/d2/std/path.d(2993):        std.path.globMatch(CaseSensitive cs = CaseSensitive.osDefault, C, Range)(Range path, const(C)[] pattern) if (isForwardRange!Range && isSomeChar!(ElementEncodingType!Range) && isSomeChar!C && is(Unqual!C == Unqual!(ElementEncodingType!Range)))
```

**Comment by dunn** [comment]
Oh, maybe a sandbox issue.  Try `brew install -v --sandbox dmd` locally and see if it reproduces.

**Comment by John-Colvin** [comment]
sadly no, it's (arguably) a bug in `dub` that is being caught by dmd 2.068.x

**Comment by John-Colvin** [comment]
sadly no, it's (arguably) a bug in `dub 0.9.23` that is being caught by dmd 2.068.x

0.9.24 will be fully released soon, which will solve this. In the mean time, it would be great to have the latest rc available here to help get more battle-testing before release.

**Comment by John-Colvin** [comment]
https://github.com/Homebrew/homebrew/pull/44065

**Pull request closed without merging**
