### PR TITLE
remove Formula#file_modified?

### LINKED ISSUE #43607: Third-party diff tools will lead to deadlock
I use `brew edit go` to modify formula and rebuild golang, but I found that `brew upgrade` will be blocked. Then I checked and found that brew will detect if there's local changes in formulas and maybe it runs `git diff`, I use `vimdiff` as default diff tool for `git diff`, so brew will wait for vimdiff to exit and vimdiff will never exit because it runs background... So I was wondering if maybe we can do something to enhance the behavior for checking local changes...

### PR DESCRIPTION
**Pull request by dunn**
It's been more trouble than it's worth.

Fixes #43607.
Closes #43049.

### CODE REVIEW

**Comment by dunn** [comment]
cc @Homebrew/owners

**Comment by mistydemeo** [comment]
:+1:

**Comment by mikemcquaid** [comment]
:+1: :sob:

**Comment by DomT4** [comment]
It'd be nice to try and work something like this at some point, as it is a useful feature in certain circumstances, but the edge cases are troublesome to handle. :+1: from me.

**Comment by xu-cheng** [comment]
:+1:

**Pull request closed without merging**
