### PR TITLE
remove unnecessary prefix.install_metafiles

### PR DESCRIPTION
**Pull request by xu-cheng**
`prefix.install_metafiles` will be called automatically for every formulae.

### CODE REVIEW

**Comment by xu-cheng** [comment]
Also thanks to @bfontaine. `brew style --fix` works like charm. :smiley:

**Comment by jacknagel** [comment]
So, these are intentional, because we want these files to be installed in the prefix like every other formula, rather than into libexec.

**Comment by xu-cheng** [comment]
Oh, I see. However, this also means there are many other formulae who are mistaking to install metafiles into `libexec`. IMHO, we should treat it as a general issue rather than a formula-specific one.

**Comment by jacknagel** [comment]
I guess I don't see a reason to undo work that someone else has already done.

**Comment by xu-cheng** [comment]
> I guess I don't see a reason to undo work that someone else has already done.

I mean we should tweak the core code so that calling `prefix.install_metafiles` in formulae would be unnecessary.

**Comment by adamv** [comment]
There's no point in the core code where we can guarantee that the prefix files are waiting in the prefix, I think.

**Comment by xu-cheng** [comment]
How about we do something like this in the core?
```ruby
formula.prefix.install_metafiles formula.buildpath
formula.prefix.install_metafiles formula.libexec if formula.libexec.exist?
```

**Comment by xu-cheng** [comment]
Close this PR as I will split it into multiple commits with more modernize and adding test.

**Pull request closed without merging**
