### PR TITLE
Update fzf.rb

### PR DESCRIPTION
**Pull request by olbrew**
FZF is has now an 0.11.1 version. Updated it's link and shasum.

### CODE REVIEW

**Comment by apjanke** [comment]
Merged. Thank you for your contribution to Homebrew!

For future reference, our preferred format for version-bump PR titles is "fzf 0.11.1", so the specific version is in the PR title.

**Comment by olbrew** [comment]
I'll remember it. Thank you. Just one question though, according to the contributing guidelines I shouldn't change the bottle but when I tested locally it gave an error trying the bottle URL. Is this normal?

**Comment by apjanke** [comment]
If I understand what you're saying – trying to install from bottle using your updated formula was giving you a download failure (like a 401 or 404) – yes, that's normal. The new bottle files are not "published" until maintainers merge the PR, and attempts to download them are expected to fail.

**Comment by olbrew** [comment]
Yes, that's probably what happened. Thank you and a happy 2016!

**Comment by mikemcquaid** [comment]
@apjanke @dunn I'm open to ideas on how to improve this workflow so it's less confusing.

**Pull request closed without merging**
