### PR TITLE
open-mpi 1.8.4: Add test

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by dpo** [comment]
Excellent. Thanks for that.

**Comment by sjackman** [comment]
@mikemcquaid `Aborted by user Mike McQuaid` Porque?

**Comment by mikemcquaid** [comment]
@sjackman Need to push out an OpenSSL fix quickly.

**Comment by mikemcquaid** [comment]
(I've already queued a retry)

**Comment by sjackman** [comment]
Okay. Ta.

**Comment by sjackman** [comment]
Thanks, Jack.

**Pull request closed without merging**
