### PR TITLE
postgresql: force linking against homebrewed readline

### LINKED ISSUE #45405: postgresql 9.4.5 El Capitan bottle breaks ~/.psql_history
The postgresql 9.4.4 OS X 10.11 El Capitain bottle works fine, but [9.4.5](http://www.postgresql.org/docs/9.4/static/release-9-4-5.html) is [broken](http://www.postgresql.org/message-id/28958.1445875729@sss.pgh.pa.us) and corrupts my `~/.psql_history` file(s) by truncating lines to 1021 characters and encoding spaces as `\040`

[brew gist-logs postgresql](https://gist.github.com/f04e722afa8c702a6c92)

postgresql 9.4.4 bottle works just fine which I can recreate by chaning:
$(brew --prefix)/[Library/Formula/postgresql.rb](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/postgresql.rb)
```
  stable do
    # https://github.com/Homebrew/homebrew/commit/5b3d216
    url "https://ftp.postgresql.org/pub/source/v9.4.4/postgresql-9.4.4.tar.bz2"
    sha256 "538ed99688d6fdbec6fd166d1779cf4588bf2f16c52304e5ef29f904c43b0013"
    #master
    #url "https://ftp.postgresql.org/pub/source/v9.4.5/postgresql-9.4.5.tar.bz2"
    #sha256 "b87c50c66b6ea42a9712b5f6284794fabad0616e6ae420cf0f10523be6d94a39"
```
```
   bottle do
    #https://github.com/Homebrew/homebrew/commit/715e055
    sha256 "c300df1c732b749654f507498ae77531842dbb3bebc1083fe05cb191e5ee6bb3" => :el_capitan
    #master
    #sha256 "57294da21442db822bf719143880000c9a90656188dcf580fafcb6b4e4350f9e" => :el_capitan
```
now I can install 9.4.4 again with `brew install postgresql`
And verify if it works correctly:
```
psql postgres
SELECT version() ;
\q
tail -2 ~/.psql_history-postgres
```
which creates following _correct_ output:
```
SELECT version() ;
\q
```
I can also recreate this 9.4.5 El Capitan bottle error with 9.4.4 if I rebuild it from source instead of using the bottle with: `brew install postgresql --build-from-source --overwrite --verbose` which creates following _wrong_ output with `\040` for spaces:
```
SELECT\040version()\040;
\\q
```

### PR DESCRIPTION
**Pull request by apjanke**
Fixes #45405
Also includes audit style fix.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
LGTM :+1:

**Comment by DomT4** [comment]
Presuming it works, :shipit:

**Comment by apjanke** [comment]
I think it works, but I'd like to test the bottle before committing it. I see from https://github.com/Homebrew/homebrew/commit/e240ba1db61a578025b281ba87b2bd35759a04db that a bottle for it got built. Is there a way I can download and install that without merging the commit and publishing it to BinTray? I tried just going through the motions of pulling that commit in, but it's still trying to download from BinTray and getting a 401.

**Comment by DomT4** [comment]
You can download them off the CI server, on the build pages for each OS X version, such as http://bot.brew.sh/job/Homebrew%20Pull%20Requests/36198/version=el_capitan/

screen shot 2015-11-09 at 20 03 37

**Comment by DomT4** [comment]
(Then you could either install with `brew install ./that_botte.tar.gz` or:

```
cp ~/Downloads/that_botte.tar.gz `homebrew --cache`
brew pull 45823
brew install postgresql
```

**Comment by apjanke** [comment]
Looks good; it's linked against `readline`. I'm pulling this in.

```
$ brew install ./postgresql-9.4.5_2.el_capitan.bottle.tar.gz
==> Pouring postgresql-9.4.5_2.el_capitan.bottle.tar.gz
[...snip...]
🍺  /usr/local/Cellar/postgresql/9.4.5_2: 3021 files, 40M
$ otool -L `which psql`
/usr/local/bin/psql:
	/usr/local/lib/libpq.5.dylib (compatibility version 5.0.0, current version 5.7.0)
	/usr/local/opt/openssl/lib/libssl.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/opt/readline/lib/libreadline.6.dylib (compatibility version 6.0.0, current version 6.3.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1225.1.1)
```

**Pull request closed without merging**
