### PR TITLE
gl2ps: add test

### PR DESCRIPTION
**Pull request by xu-cheng**

### CODE REVIEW

**Comment by xu-cheng** [comment]
@mikemcquaid Several PRs report the same error on Mountain Lion with following message:
```
==> brew pull --clean https://github.com/Homebrew/homebrew/pull/36888	 FAILED
fatal: ref HEAD is not a symbolic ref
==> Applying patch
Applying: gl2ps: add test
Auto packing the repository for optimum performance. You may also
run "git gc" manually. See "git help gc" for more information.
fatal: Unable to create '/usr/local/.git/refs/remotes/origin/pr/9959/head.lock': File exists.

If no other git process is currently running, this probably means a
git process crashed in this repository earlier. Make sure no other git
process is running and remove the file manually to continue.
error: failed to run reflog
Resolve operation not in progress, we are not resuming.
Error: Patch failed to apply: aborted.
```

**Comment by xu-cheng** [comment]
@mikemcquaid Need a little help. How to pull this PR with bottles?

**Comment by mikemcquaid** [comment]
@xu-cheng The downstream build view (http://bot.brew.sh/job/Homebrew%20Pull%20Requests/21531/downstreambuildview/) shows that the Homebrew Bottles upload job failed. You can hit Rebuild on the Homebrew Bottles job (although I just did so) and then when it's done (http://bot.brew.sh/job/Homebrew%20Bottles/15843/console) then we can pull it (and I'll get it).

**Comment by xu-cheng** [comment]
Thanks a lot. You are awesome. :rocket:

**Comment by mikemcquaid** [comment]
:heart_eyes:

**Pull request closed without merging**
