### PR TITLE
dub 0.9.23

### PR DESCRIPTION
**Pull request by John-Colvin**
What is correct practice for when there is no current development release?

### CODE REVIEW

**Comment by DomT4** [comment]
> What is correct practice for when there is no current development release?

Just murder the ` devel ` elements completely :). Once there's a development release available again, we can just put a new block in without any pain.

**Comment by John-Colvin** [comment]
Ah, yes, I see the auto-tester didn't like that :+1:

**Comment by DomT4** [comment]
Yeah there's a built-in check to make sure ` devel ` is always newer than ` stable ` :smiley_cat:

**Comment by xu-cheng** [comment]
Thanks for the pull request! 🎉 Homebrew depends on contributions from community members like you and we're grateful for your support.

**Pull request closed without merging**
