### PR TITLE
fig 1.4.2

### PR DESCRIPTION
**Pull request by Aigeruth**

### CODE REVIEW

**Comment by xu-cheng** [comment]
Close in favor of #44273 

Thanks for the pull request! 🎉 Homebrew depends on contributions from community members like you and we're grateful for your support.

**Comment by Aigeruth** [comment]
@xu-cheng I created my PR based on #37206. Has the renaming policy changed?

**Comment by xu-cheng** [comment]
@Aigeruth We only add support for formula renaming recently. If you are interested, [this](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Rename-A-Formula.md) is how we handle it now.

**Comment by Aigeruth** [comment]
@xu-cheng Thank you!

**Pull request closed without merging**
