### PR TITLE
Updated batik.rb

### PR DESCRIPTION
**Pull request by genki**
Added a java option for suppressing dock icon

### CODE REVIEW

**Comment by DomT4** [comment]
Is this actually an option, or is it suppressing the dock icon for everyone, out of curiosity?

**Comment by mikemcquaid** [comment]
This looks like something that should probably be handled by `batik` themselves rather than Homebrew.

**Comment by genki** [comment]
DomT4, yes.

mikemcquaid, Yeah, I think so. But the dock icon is really annoying.
This small modification can get rid of it and will not conflict with the fix in the future.

**Comment by jacknagel** [comment]
Can we at least get it reported upstream?

**Comment by luzpaz** [comment]
Is this the upstream bug?
https://issues.apache.org/jira/browse/CASSANDRA-5611

**Comment by mikemcquaid** [comment]
Closing this as I think it's something for upstream to fix.

**Pull request closed without merging**
