### PR TITLE
gdk-pixbuf 2.31.2

### PR DESCRIPTION
**Pull request by bfontaine**

### CODE REVIEW

**Comment by blogabe** [comment]
Per @jacknagel here https://github.com/Homebrew/homebrew/pull/31675, which version of gdk-pixbuf should Homebrew maintain, the stable minor even release or the developmental minor odd release?

**Comment by jacknagel** [comment]
Reverted per the above.

**Comment by mikemcquaid** [comment]
@jacknagel Sorry, my bad. Could you add a comment so I don't stupidly do this again? Thanks!

**Comment by jacknagel** [comment]
Working on an audit check for this.

**Pull request closed without merging**
