### PR TITLE
Chapel 1.12

### PR DESCRIPTION
**Pull request by ben-albrecht**

### CODE REVIEW

**Comment by ben-albrecht** [comment]
@DomT4 - I am not seeing the tests for this pull request in the [Jenkins queue](http://bot.brew.sh/job/Homebrew%20Pull%20Requests/). Will it be added later at some point?

**Comment by DomT4** [comment]
@BrewTestBot test this please

**Comment by DomT4** [comment]
Not sure what happened there. Will be in the queue shortly now.

**Comment by ben-albrecht** [comment]
@DomT4 Maybe it has something to do with the duplicate name between this PR and my previous PR: #44506

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/0a47cb27035470f99697807f942af7db0ffee4ff. Thank you for your contribution to Homebrew @ben-albrecht; we appreciate it! :smiley_cat:

**Pull request closed without merging**
