### PR TITLE
thefuck 1.26

### PR DESCRIPTION
**Pull request by scott-abernethy**
New formula for thefuck, a "magnificent app which corrects your previous console command."

### CODE REVIEW

**Comment by DomT4** [comment]
Another project for maintainers to make a call on - Very new (~2 weeks old), but extremely popular on Github, and not a self-submission.

**Comment by scott-abernethy** [comment]
Test failed on mountain lion due to 'correct' correction of echp to ecpg (I was expecting a correction to echo). Fixing.

**Comment by xu-cheng** [comment]
Consider its popularity. I think it's good to merge this.

@scott-abernethy Thanks for the pull request! 🎉 Homebrew depends on contributions from community members like you and we're grateful for your support.

**Comment by scott-abernethy** [comment]
All good, thanks.

**Pull request closed without merging**
