### PR TITLE
colortail 0.3.4

### PR DESCRIPTION
**Pull request by bfontaine**
I asked upstream for tagged releases (https://github.com/joakim666/colortail/issues/11)

### CODE REVIEW

**Comment by bfontaine** [comment]
Failing on ML without much info:

```
==> ./autogen.sh --disable-dependency-tracking --prefix=/usr/local/Cellar/colortail/0.3.4
Failed to execute: ./autogen.sh
```

**Comment by mikemcquaid** [comment]
Might be missing the interpreter or something?

**Comment by bfontaine** [comment]
Thanks Mike, I’m trying that. I’ll submit a PR upstream if it works.

**Comment by bfontaine** [comment]
That was it, I made a PR to upstream and linked to it in the formula.

**Pull request closed without merging**
