### PR TITLE
mediaconch 15.12

### PR DESCRIPTION
**Pull request by dericed**

### CODE REVIEW

**Comment by dunn** [comment]
Failing on Mavericks:
```
../../../Source/Common/Core.cpp:1235:38: error: use of undeclared identifier 'getuid'
        struct passwd *pw = getpwuid(getuid());
                                     ^
../../../Source/Common/Core.cpp:1281:38: error: use of undeclared identifier 'getuid'
        struct passwd *pw = getpwuid(getuid());
                                     ^
../../../Source/Common/Core.cpp:1362:9: error: use of undeclared identifier 'usleep'
        usleep(50000);
        ^
```
http://bot.brew.sh/job/Homebrew%20Pull%20Requests/39214/version=mavericks/testReport/junit/brew-test-bot/mavericks/install_mediaconch/

**Comment by mistydemeo** [comment]
Both of those functions are defined in unistd.h, which isn't included on OS X:

```c
#if defined(UNIX)
#include <unistd.h>
#include <sys/types.h>
#include <pwd.h>
#elif defined(MACOS) || defined(MACOSX)
#include <sys/types.h>
#include <pwd.h>
#include <uuid/uuid.h>
```

**Comment by dericed** [comment]
The developers did a silent update of https://mediaarea.net/download/binary/mediaconch/15.12/MediaConch_CLI_15.12_GNU_FromSource.tar.bz2. Can the test be rerun?

**Comment by mikemcquaid** [comment]
@dericed Done but I'd really suggest they don't do that in future as randomly changing tarballs can be a sign of being hacked.

**Comment by dericed** [comment]
ok, we'll fix, and post a revision tarball soon. thanks!

**Comment by dericed** [comment]
The tarball is updated. Should I squash these two commits?

**Comment by mistydemeo** [comment]
Please! Thanks.

**Comment by dericed** [comment]
@mistydemeo squashed

**Pull request closed without merging**
