### PR TITLE
Formatting corrections to Homebrew's core

### PR DESCRIPTION
**Pull request by woodruffw**
Hello!

These commits correct some minor formatting issues in Homebrew's core, namely missing spacing between methods and missing parentheses in method declarations with arguments.

Each directory's formatting corrections are isolated in its own commit.

Other potential issues I didn't correct, but can if wanted:
- [ ] Remaining heredocs that haven't been converted to use `EOS.undent`
- [ ] Excessively brief method arguments (`f`, `fn`, `val`, etc)
- [ ] Indentation corrections and preference of `""` over `''` (or vice versa)
- [ ] Replacement of Perl-style special variables with Ruby-style ones

### CODE REVIEW

**Comment by bfontaine** [comment]
Unfortunately we don’t merge style-only pull-requests.

**Comment by mikemcquaid** [comment]
Yup, sorry!

**Comment by woodruffw** [comment]
I was originally going to include these in #41021, but was advised to keep that limited to the bottling installation system only.
Should I drop this entirely or try to include it in some other fashion? I think it would be a big benefit in terms of conformity/readability of the codebase.

**Comment by mikemcquaid** [comment]
I don't think the conformity is important necessarily. The big downside is that you'll now show up for the `git blame` for these lines.

**Comment by woodruffw** [comment]
Alright. I'll drop this.

**Comment by mikemcquaid** [comment]
Thanks :heart:

**Pull request closed without merging**
