### PR TITLE
Updated jless to use sha256

### PR DESCRIPTION
**Pull request by stevenatwork**

### CODE REVIEW

**Comment by dunn** [comment]
Looks like one of the checksums is wrong:
```
==> Verifying jless--patch-ecbbbf7a06d221021dae9f74862e2c41c91ded118c215687c13f5cb95d22f975.gz checksum
Error: SHA256 mismatch
Expected: ecbbbf7a06d221021dae9f74862e2c41c91ded118c215687c13f5cb95d22f975
Actual: 0681485f47237aeee42a34bbf0ab55215933c7713d1be80ac202a31c7a6fdc31
Archive: /Library/Caches/Homebrew/jless--patch-ecbbbf7a06d221021dae9f74862e2c41c91ded118c215687c13f5cb95d22f975.gz
To retry an incomplete download, remove the file above.

**Comment by stevenatwork** [comment]
hm.. really weird,

```
==> Downloading http://ftp.netbsd.org/pub/pkgsrc/distfiles/less-382-iso258.patch.gz
Warning: Patch reports different SHA256: ecbbbf7a06d221021dae9f74862e2c41c91ded118c215687c13f5cb95d22f975
Downloaded to: /Library/Caches/Homebrew/jless--patch-ecbbbf7a06d221021dae9f74862e2c41c91ded118c215687c13f5cb95d22f975.gz
SHA1: 961275c26c6f6ec2e04821d9d9d1b10505214b1f
SHA256: 0681485f47237aeee42a34bbf0ab55215933c7713d1be80ac202a31c7a6fdc31
```

Wow,

So via my network I get 

However when using https://www.hybrid-analysis.com/sample/0681485f47237aeee42a34bbf0ab55215933c7713d1be80ac202a31c7a6fdc31?environmentId=1

I get 0681485f47237aeee42a34bbf0ab55215933c7713d1be80ac202a31c7a6fdc31

Really spooky as I get ecbbbf7a06d221021dae9f74862e2c41c91ded118c215687c13f5cb95d22f975 on my network

I'll investigate more and see what's up.

**Comment by stevenatwork** [comment]
Turns out Chrome was decompressing the files but leaving the .gz extension.
Fixed the PR

**Comment by bfontaine** [comment]
Thank you for your contribution to @stevenatwork; we appreciate it! :tada:

**Pull request closed without merging**
