### PR TITLE
miller 3.1.2

### PR DESCRIPTION
**Pull request by standage**
bugfix release

### CODE REVIEW

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/1157fb6b867aa0cc77e6d16f66871733b2827971. Thank you for your contribution to Homebrew @standage; we appreciate it! :smiley_cat:

**Comment by johnkerl** [comment]
Thanks; beat me to it! (I was waiting for the end of the workday.) :D

**Comment by standage** [comment]
It's amazing what people will do for you when they need your stuff to get their own work done! ;-) #oss #ftw.

**Comment by standage** [comment]
Ever since this pull request was merged, git has been opening up my text editor with a "merge branch" commit message. The first couple of times it wasn't a big deal, but it has become a nuisance by now. I scraped the docs and couldn't find anything, and `brew doctor` doesn't report any issues. Any pointers on how to fix this?

**Comment by DomT4** [comment]
@standage You contributed from your `master` rather than a branch, which can cause git weirdness.

Maybe try something like:
```
cd $(brew --prefix) && git fetch && git reset --hard origin/master
```
Might sort it out. Be aware that'll also overwrite any local changes you have to Homebrew, i.e. if you've edited `a2ps` to make it print the word `hello` every operation that'll be removed.

**Comment by standage** [comment]
That sorted it out, thanks!

I'll be more careful about using feature branches for future pull requests.

**Pull request closed without merging**
