### PR TITLE
carina 1.2.0

### PR DESCRIPTION
**Pull request by rgbkrk**
Bump `carina` to 1.2.0

### All Submissions:

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew/pulls) for the same update/change?

### CODE REVIEW

**Comment by nijikon** [comment]
Thank you for your contribution to Homebrew, we appreciate it!

**Comment by rgbkrk** [comment]
Did something weird happen with the bottling process?

```
$ brew upgrade carina
==> Upgrading 1 outdated package, with result:
carina 1.2.0
==> Upgrading carina
==> Downloading https://homebrew.bintray.com/bottles/carina-1.2.0.yosemite.bottle.tar.gz
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 8061ece663fd56944df7d1af4fc785d7cd5ba814b51abc13c6e8096ee00f153e
Actual: ff35c1a1fe7a77bc5cbb4485d452b3926b3e9191a2c965be42cfa55d1e0242c5
Archive: /Library/Caches/Homebrew/carina-1.2.0.yosemite.bottle.tar.gz
To retry an incomplete download, remove the file above.
Warning: Bottle installation failed: building from source.
==> Cloning https://github.com/getcarina/carina.git
Updating /Library/Caches/Homebrew/carina--git
==> Checking out tag v1.2.0
==> make get-deps
==> make carina VERSION=1.2.0
🍺  /usr/local/Cellar/carina/1.2.0: 2 files, 8.2M, built in 29 seconds
```

**Comment by nijikon** [comment]
This is weird, let me check.

**Comment by DomT4** [comment]
Was probably an upload glitch on that bottle. Had the CI build new ones in https://github.com/Homebrew/homebrew/commit/a44e04876533dabf5e774a3012b1cd8ab7259690.

**Pull request closed without merging**
