### PR TITLE
Update xctool to 0.2.4

### PR DESCRIPTION
**Pull request by LegNeato**
https://github.com/facebook/xctool/releases/tag/v0.2.4

### CODE REVIEW

**Comment by tdsmith** [comment]
Build's [failing on Mountain Lion](http://bot.brew.sh/job/Homebrew%20Pull%20Requests/27159/version=mountain_lion/testReport/junit/brew-test-bot/mountain_lion/install_xctool/):

> The following build commands failed:
	CompileC /tmp/xctool20150602-95880-zgcsah/xctool-0.2.4/build/5B1008/Intermediates/otest-query.build/Release/otest-query-osx.build/Objects-normal/i386/TestingFramework.o /tmp/xctool20150602-95880-zgcsah/xctool-0.2.4/Common/TestingFramework.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Should this work?

We also prefer sha256 checksums to sha1 now.

**Comment by LegNeato** [comment]
Hmmm, I'll investigate the failure and report back.

**Comment by LegNeato** [comment]
Ok, so the older compiler is choking on newer objc usage/syntax. The newer compiler targeting 10.7 (even older) works. I assume I just keep updating this to kick off new tests? I don't have this old an OS and Xcode to try on...

**Comment by tdsmith** [comment]
> I assume I just keep updating this to kick off new tests?

Yep! It'll build again on each new push to your branch.

**Comment by mikemcquaid** [comment]
> Ok, so the older compiler is choking on newer objc usage/syntax.

Seems the `depends_on :xcode => "5.0"` probably needs bumped?

**Comment by LegNeato** [comment]
AFAIK xctool is still supposed to work with Xcode 5+ still. I'll check to see if we dropped support explicitly.

**Comment by mikemcquaid** [comment]
Maybe it's worth just bumping the Xcode dependency for now or querying on their issue tracker?

**Comment by DomT4** [comment]
Ping?

**Comment by LegNeato** [comment]
Yeah, we've been chatting about it an pretty sure we're going to drop support for Xcode 5 (as Apple has already done and seeing how Xcode 7 beta is out today)

**Comment by DomT4** [comment]
Should we drop Xcode 5 support in this PR then?

**Comment by mikemcquaid** [comment]
> Should we drop Xcode 5 support in this PR then?

Yes.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/4b0ec9250eef7a190b298f891564346e95da7844. Thanks for your contribution to Homebrew, we appreciate it! :smiley_cat:.

Please note for future reference the preferred commit message for simple version bumps is styled `xctool 0.2.4`, Thanks!

**Pull request closed without merging**
