### PR TITLE
jboss-forge 3.0.0.Beta1

### PR DESCRIPTION
**Pull request by gastaldi**
This is the official version. We are no longer maintaining the 2.x version

### CODE REVIEW

**Comment by bfontaine** [comment]
Don’t you have a stable version?

**Comment by gastaldi** [comment]
Hi,
Although it is called Beta, it is stable and the version we want people to use.

**Comment by mikemcquaid** [comment]
> Although it is called Beta, it is stable and the version we want people to use.

Then please don't call it beta.

**Comment by gastaldi** [comment]
We'll release the Final version on march. Closing this PR now.
Em 25/12/2015 16:08, "Mike McQuaid" <notifications@github.com> escreveu:

**Pull request closed without merging**
