### PR TITLE
python 2.7.10

### PR DESCRIPTION
**Pull request by jab**
Python 2.7.10 was just released. Not familiar with the python homebrew formula nor with bottled formulas, so this PR still needs some work, but figured I'd get the ball rolling in case it's helpful.

### CODE REVIEW

**Comment by DomT4** [comment]
CC @tdsmith for review :heart:. I seem to recall the `sip` failure is unrelated.

**Comment by youtux** [comment]
I think it would be nice to upgrade `setuptools` to 16.0 too.

**Comment by DomT4** [comment]
Yup, if `setuptools` 16.0 is stable we should bump to that here as well.

**Comment by jab** [comment]
Thanks for reviewing everyone. Just pushed a new revision which updates setuptools to 16.0. Does that just leave updating the bottle SHAs? I looked at https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Bottles.md#bottle-creation but couldn't immediately tell if the Brew Test Bot already built bottles for this PR and it was just a matter of finding them, or if I should build the bottles myself.

**Comment by DomT4** [comment]
The test bot builds bottles for each PR and those bottles are applied automatically when we pull the update. Nothing needs doing on the contributor side for bottles :).

**Comment by jab** [comment]
Oh sweet! Nice tools you've got there :)

**Comment by jab** [comment]
Looks like the latest revision is causing test failures, e.g.
http://bot.brew.sh/job/Homebrew%20Pull%20Requests/26672/version=yosemite/testReport/junit/brew-test-bot/yosemite/test_sip/

Any idea why we'd get `'Python.h' file not found`?

**Comment by DomT4** [comment]
`sip`'s failure is unrelated per #39123. I'll let Tim :+1: / :-1: this before it gets merged but this looks good.

**Comment by geoff-codes** [comment]
SIP is at 4.16.7 upstream vs. 4.16.5 in the formula. I haven't a clue what sip is, nor really anything about python, so I'm not gonna touch it, but this failure may well be fixed upstream.

Also, could someone retitle this PR? I just prepped an identical PR because grepping 2.7.10 didn't turn up anything.

**Comment by jab** [comment]
@geoff-codes Just pushed 20a50b2 updating sip to 4.16.7, we'll see if that fixes the failure. Thanks for the idea.

Thanks @DomT4 for updating the PR title.

**Comment by jab** [comment]
According to test bot my update to sip 4.16.7 caused "brew install pyqwt" and "... qscintilla2" to fail with e.g.
```
Error: Failed to download resource "sip"
Download failed: https://homebrew.bintray.com/bottles/sip-4.16.7.yosemite.bottle.1.tar.gz
```
Any ideas?

**Comment by DomT4** [comment]
It's an internal problem we're aware of. Pull the `sip` bump out of this PR (We'll ignore other the `sip` failure on the bot in this PR) and create a new PR for it. That'll allow us to merge the Python bump here sooner at least.

**Comment by jab** [comment]
Just reset back to 1a647e521b44486c8839e95ab95096980b02cabe.

**Comment by tdsmith** [comment]
Can you reset pip to the latest 6.x? I want pip 7 to age for a little bit longer before we include it in the bottles because it has some big changes that probably break things. Using the newest setuptools is OK. Thanks!

**Comment by jab** [comment]
> Can you reset pip to the latest 6.x? I want pip 7 to age for a little bit longer before we include it in the bottles because it has some big changes that probably break things. Using the newest setuptools is OK. Thanks!

Done in cdda90b577196b383de8a7fe9ec658b0c3d3e139. My pleasure!

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/d943d45d5e4794adf461dbaceaed1587a728a519 with Tim's :+1:. Thanks for your contribution to Homebrew, we appreciate it! :smiley:.

Please note for future reference the ideal commit message for simple version bumps is `python 2.7.10` - You got it spot on in the PR title :).

**Comment by jab** [comment]
Thanks for merging! Pleasure to contribute. Duly noted on the commit
messages in the future. (And you're the one that deserves the credit for
re-titling this PR:)

**Pull request closed without merging**
