### PR TITLE
ola: with-ftdi option

### PR DESCRIPTION
**Pull request by Hazardius**
Option in OLA recipe for adding dependencies to build it with FTDI USB plugin.

### CODE REVIEW

**Comment by bfontaine** [comment]
How common is this need?

**Comment by Hazardius** [comment]
I'm not fully aware about needs of community, but I think FTDI devices are quite popular these days (partially because they're really cheap) and this change makes it much easier to use f.e. OpenDMX USB 2.0 with OLA.

I needed OLA with FTDI plugin myself and after figuring out how to do that with brew recipe I asked about feedback on [open-lighting google mailing group](https://groups.google.com/forum/#!msg/open-lighting/7ZZc6sN0yHE/Ug6MI7msCgAJ) what do they think about this option. They proposed to send it and that's how I've got here. :)

I hope it'll be included in homebrew in this or better manner since I'm using it a lot recently.

**Comment by bfontaine** [comment]
Thanks. Don’t we need to add an `--enable-something` option? Or is it automatically picked by the build?

**Comment by Hazardius** [comment]
Yes - if there's no libftdi amongst dependencies - it disables installing FTDI plugin.

**Comment by bfontaine** [comment]
Thank you @Hazardius! :tada:

**Pull request closed without merging**
