### PR TITLE
noweb (fix formula)

### PR DESCRIPTION
**Pull request by FranklinChen**
No files from the `icon` directory were being installed. This
prevented correct functionality. Now they are installed.

### CODE REVIEW

**Comment by dunn** [comment]
This will fail if they have a tex installation but don't run with `sudo`, right? Since it'll try to install into `/usr/local/texlive`?
```ruby
      if which 'kpsewhich'
        ohai 'TeX installation found. Installing TeX support files there might fail if your user does not have permission'
        texmf = Pathname.new(`kpsewhich -var-value=TEXMFLOCAL`.chomp)
```
I think we should just set `texmf = prefix` no matter what.

**Comment by dunn** [comment]
Two audit failures from the test bot:
```
        Error: 2 problems in 1 formula
noweb:
 * Stable: SHA1 checksums are deprecated, please use SHA256
 * Non-libraries were installed to "/usr/local/Cellar/noweb/2.11b/lib"
Installing non-libraries to "lib" is discouraged.
The offending files are:
  /usr/local/Cellar/noweb/2.11b/lib/autodefs.asdl
  /usr/local/Cellar/noweb/2.11b/lib/autodefs.c
  /usr/local/Cellar/noweb/2.11b/lib/autodefs.icon
  /usr/local/Cellar/noweb/2.11b/lib/autodefs.lrtl
  /usr/local/Cellar/noweb/2.11b/lib/autodefs.mmix
  /usr/local/Cellar/noweb/2.11b/lib/autodefs.pascal
  /usr/local/Cellar/noweb/2.11b/lib/autodefs.promela
  /usr/local/Cellar/noweb/2.11b/lib/autodefs.sml
  /usr/local/Cellar/noweb/2.11b/lib/autodefs.tex
  /usr/local/Cellar/noweb/2.11b/lib/autodefs.yacc
  /usr/local/Cellar/noweb/2.11b/lib/btdefn
  /usr/local/Cellar/noweb/2.11b/lib/disambiguate
  /usr/local/Cellar/noweb/2.11b/lib/docs2comments
  /usr/local/Cellar/noweb/2.11b/lib/elide
  /usr/local/Cellar/noweb/2.11b/lib/emptydefn
  /usr/local/Cellar/noweb/2.11b/lib/finduses
  /usr/local/Cellar/noweb/2.11b/lib/h2a
  /usr/local/Cellar/noweb/2.11b/lib/l2h
  /usr/local/Cellar/noweb/2.11b/lib/markup
  /usr/local/Cellar/noweb/2.11b/lib/mnt
  /usr/local/Cellar/noweb/2.11b/lib/noidx
  /usr/local/Cellar/noweb/2.11b/lib/nt
  /usr/local/Cellar/noweb/2.11b/lib/nwmtime
  /usr/local/Cellar/noweb/2.11b/lib/pipedocs
  /usr/local/Cellar/noweb/2.11b/lib/tmac.w
  /usr/local/Cellar/noweb/2.11b/lib/toascii
  /usr/local/Cellar/noweb/2.11b/lib/tohtml
  /usr/local/Cellar/noweb/2.11b/lib/toroff
  /usr/local/Cellar/noweb/2.11b/lib/totex
  /usr/local/Cellar/noweb/2.11b/lib/unmarkup
  /usr/local/Cellar/noweb/2.11b/lib/xchunks
```

**Comment by mistydemeo** [comment]
The non-libraries aren't new - can leave those to another PR to fix, I think.

**Comment by FranklinChen** [comment]
I did some cleanup, but will later look into change the installation to avoid putting stuff into `lib`.

**Comment by dunn** [comment]
Merged in cf69a153d918665d48852af0c3ccfa67ec9c556d, thank you! If you want to open another PR to deal with the `lib` stuff (and maybe add a test!), that would be awesome.

**Pull request closed without merging**
