### PR TITLE
use secure URLs for maven components

### PR DESCRIPTION
**Pull request by vszakats**

### CODE REVIEW

**Comment by DomT4** [comment]
Be wary with Maven stuff you will hit sandbox issues in places, and we may ask you to fix 'em :wink:

**Comment by vszakats** [comment]
Thanks for the pre-warning :) I may stand not much chance to fix any of those, but I'm staying prepared for the red flags (and hoping for getting enough clues to make the edits as/if needed).

**Comment by vszakats** [comment]
Looks like a lucky case, it's all green :)

**Comment by DomT4** [comment]
Colour me slightly amazed :smile:. Maven stuff keeps trying to break free from the sandbox when it downloads additional modules.

Merged. Thanks for catching these @vszakats!

**Pull request closed without merging**
