### PR TITLE
ice 3.6b (devel)

### PR DESCRIPTION
**Pull request by DomT4**
* Devel version 3.6b added
* Formula Cleanup
* Option wording updates
* Externalised the patch
* Revision for OpenSSL

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Maybe need an `openssl` dep?

**Comment by DomT4** [comment]
Doh. Forgot that. Fixing imminently :+1:

**Comment by DomT4** [comment]
This doesn't seem to want to build on Mountain Lion for hell or high water. Previous two attempts broke after it reached the 24 declared errors stage, heh. I didn't know if we wanted to try ` needs :cxx11 ` or if that could actually just be applied to the single ` devel ` block and install. I just banned ML compile for devel for now :cry:.

**Comment by mikemcquaid** [comment]
Could try the `needs :cxx11` or add a `fails_with`?

**Comment by DomT4** [comment]
Should we try the ` needs :cxx11 ` applying just to ` devel ` or the whole formula?

**Comment by mikemcquaid** [comment]
The latter if that's the only bit failing compilation.

**Comment by DomT4** [comment]
Yeah, the only bit not compiling on ML is the ` devel ` element. Stable is still a-okay.

**Comment by DomT4** [comment]
Still blew up. I'll try a ` fails_with ` instead.

**Comment by DomT4** [comment]
Looks like there's a kink in the ` fails_with ` mechanism for non-stable elements?

```
==> brew install --devel --verbose ice					 FAILED
Error: ice cannot be built with any available compilers.
To install this formula, you may need to:
  brew install gcc
```

Shouldn't it be doing that automatically for ` fails_with `?

**Comment by DomT4** [comment]
Enforcing ` fails_with ` broke the ` devel ` build on all three platforms. Looks like a linking error:

```
rm -f ../../lib/libFreeze.3.6b.dylib
g++-4.9  -dynamiclib  -Wall -D_REENTRANT -L../../lib -o ../../lib/libFreeze.3.6b.dylib -install_name @rpath/libFreeze.36b.dylib BackgroundSaveEvictorI.o Catalog.o CatalogIndexList.o ConnectionI.o EvictorI.o EvictorIteratorI.o Index.o IndexI.o MapDb.o MapI.o ObjectStore.o SharedDbEnv.o TransactionalEvictorContext.o TransactionalEvictorI.o TransactionHolder.o TransactionI.o Util.o BackgroundSaveEvictor.o CatalogData.o Connection.o ConnectionF.o DB.o Evictor.o EvictorF.o EvictorStorage.o Exception.o Transaction.o TransactionalEvictor.o PingObject.o  -lIce -lIceUtil  -ldb_cxx
Undefined symbols for architecture x86_64:
  "Db::set_error_stream(std::basic_ostream<char, std::char_traits<char> >*)", referenced from:
      vtable for Freeze::MapDb in MapDb.o
  "Db::set_message_stream(std::basic_ostream<char, std::char_traits<char> >*)", referenced from:
      vtable for Freeze::MapDb in MapDb.o
  "Db::verify(char const*, char const*, std::basic_ostream<char, std::char_traits<char> >*, unsigned int)", referenced from:
      vtable for Freeze::MapDb in MapDb.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[2]: *** [../../lib/libFreeze.3.6b.dylib] Error 1
make[1]: *** [Freeze] Error 2
make: *** [all] Error 1
```

**Comment by DomT4** [comment]
Closing in favour of the recent Ice changes we merged with the BDB update.

**Pull request closed without merging**
