### PR TITLE
mongrel2 1.9.3

### PR DESCRIPTION
**Pull request by jkarneges**

### CODE REVIEW

**Comment by jkarneges** [comment]
The build succeeds but running tests fails. It looks like the response_tests program writes to /dev/zero, and I wonder if this is inaccessible in the jenkins environment (it works fine for me locally).

**Comment by dunn** [comment]
Yeah, we have a sandbox restricting where the test can write to.  Maybe `dev/zero` should be on the whitelist, though.

**Comment by jkarneges** [comment]
Must be a new thing then? This test code was the same in the previous version.

I think it belongs on the whitelist. Along with /dev/null, if it isn't already there.

**Comment by dunn** [comment]
Yep, we just turned it on a couple weeks ago.

**Comment by dunn** [comment]
OK, whitelisted `/dev/zero`, let's kick off a new build.

**Comment by jkarneges** [comment]
Thanks! Build failed again, but it seems to come from a pushpin test rather than anything from mongrel2. Does the build do some kind of reverse dependency testing? (pushpin depends on mongrel2)

**Comment by dunn** [comment]
Yeah, we test the dependents to make sure there aren't breaking changes. But this looks like a sandbox issue. We'd be _super_ grateful if you could fix that up in this PR too.

**Comment by jkarneges** [comment]
See #43349.

**Comment by jkarneges** [comment]
Alright it looks like the pushpin issue was fixed and now the reverse deps tests succeed.

I hope this can be merged now.

**Comment by xu-cheng** [comment]
Thanks for the pull request! 🎉 Homebrew depends on contributions from community members like you and we're grateful for your support.

**Pull request closed without merging**
