### PR TITLE
Be extra-sensitive towards taps

### PR DESCRIPTION
**Pull request by DomT4**
References: #37788 #36236

### CODE REVIEW

**Comment by DomT4** [comment]
Apologies to ping you again, but you're the only maintainer I discussed either of these with. @mikemcquaid

**Comment by mikemcquaid** [comment]
Happy to include this in `pull` but I'd rather not in `update` I think.

**Comment by DomT4** [comment]
Do we want to do anything with the ` update ` situation or are we okay with it? I guess the vast majority of users won't have as many of the Homebrew taps tapped as I do.

**Comment by mikemcquaid** [comment]
I think `update` is probably fine for now.

**Comment by DomT4** [comment]
Cool. Do you want me to close this in favour of #38623, or close #38623 in favour of this, since we're only making the one change?

**Comment by DomT4** [comment]
Apologies. Wrong issue link. This issue is the one intended to be referenced => #37788

**Comment by mikemcquaid** [comment]
Yeh, let's pass on this.

**Comment by DomT4** [comment]
Cool :+1:

**Pull request closed without merging**
