### PR TITLE
afl-fuzz 2.01b

### PR DESCRIPTION
**Pull request by fbrosson**
I guess this release might solve the problem found in https://github.com/Homebrew/homebrew/pull/49022

### CODE REVIEW

**Comment by DomT4** [comment]
Apparently not, I'm afraid :confused: 
```
==> /usr/local/Cellar/afl-fuzz/2.00b/bin/afl-clang++ -g /private/tmp/afl-fuzz20160212-80698-5m2sbc/main.cpp -o /private/tmp/afl-fuzz20160212-80698-5m2sbc/test
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-49b865.s:2:Unknown pseudo-op: .macosx_version_min
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-49b865.s:2:Rest of line ignored. 1st junk character valued 49 (1).
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-49b865.s:66:Unknown pseudo-op: .cfi_startproc
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-49b865.s:70:Unknown pseudo-op: .cfi_def_cfa_offset
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-49b865.s:70:Rest of line ignored. 1st junk character valued 49 (1).
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-49b865.s:72:Unknown pseudo-op: .cfi_offset
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-49b865.s:72:Rest of line ignored. 1st junk character valued 37 (%).
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-49b865.s:75:Unknown pseudo-op: .cfi_def_cfa_register
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-49b865.s:75:Rest of line ignored. 1st junk character valued 37 (%).
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-49b865.s:93:Unknown pseudo-op: .cfi_endproc
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-49b865.s:102:Unknown pseudo-op: .cfi_startproc
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-49b865.s:103:Unknown pseudo-op: .cfi_personality
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-49b865.s:103:Rest of line ignored. 1st junk character valued 49 (1).
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-49b865.s:104:Unknown pseudo-op: .cfi_lsda
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-49b865.s:104:Rest of line ignored. 1st junk character valued 49 (1).
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-49b865.s:108:Unknown pseudo-op: .cfi_def_cfa_offset
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-49b865.s:108:Rest of line ignored. 1st junk character valued 49 (1).
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-49b865.s:110:Unknown pseudo-op: .cfi_offset
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-49b865.s:110:Rest of line ignored. 1st junk character valued 37 (%).
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-49b865.s:113:Unknown pseudo-op: .cfi_def_cfa_register
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-49b865.s:113:Rest of line ignored. 1st junk character valued 37 (%).
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-49b865.s:121:Unknown pseudo-op: .cfi_offset
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-49b865.s:121:Rest of line ignored. 1st junk character valued 37 (%).
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-49b865.s:123:Unknown pseudo-op: .cfi_offset
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-49b865.s:123:Rest of line ignored. 1st junk character valued 37 (%).
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-49b865.s:125:Unknown pseudo-op: .cfi_offset
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-49b865.s:125:Rest of line ignored. 1st junk character valued 37 (%).
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-49b865.s:127:Unknown pseudo-op: .cfi_offset
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-49b865.s:127:Rest of line ignored. 1st junk character valued 37 (%).
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-49b865.s:129:Unknown pseudo-op: .cfi_offset
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-49b865.s:129:Rest of line ignored. 1st junk character valued 37 (%).
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-49b865.s:408:Unknown pseudo-op: .cfi_endproc
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-49b865.s:515:Unknown pseudo-op: .cfi_startproc
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-49b865.s:516:Unknown pseudo-op: .cfi_personality
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-49b865.s:516:Rest of line ignored. 1st junk character valued 49 (1).
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-49b865.s:517:Unknown pseudo-op: .cfi_lsda
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-49b865.s:517:Rest of line ignored. 1st junk character valued 49 (1).
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-49b865.s:521:Unknown pseudo-op: .cfi_def_cfa_offset
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-49b865.s:521:Rest of line ignored. 1st junk character valued 49 (1).
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-49b865.s:523:Unknown pseudo-op: .cfi_offset
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-49b865.s:523:Rest of line ignored. 1st junk character valued 37 (%).
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-49b865.s:526:Unknown pseudo-op: .cfi_def_cfa_register
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-49b865.s:526:Rest of line ignored. 1st junk character valued 37 (%).
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-49b865.s:534:Unknown pseudo-op: .cfi_offset
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-49b865.s:534:Rest of line ignored. 1st junk character valued 37 (%).
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-49b865.s:536:Unknown pseudo-op: .cfi_offset
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-49b865.s:536:Rest of line ignored. 1st junk character valued 37 (%).
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-49b865.s:538:Unknown pseudo-op: .cfi_offset
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-49b865.s:538:Rest of line ignored. 1st junk character valued 37 (%).
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-49b865.s:540:Unknown pseudo-op: .cfi_offset
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-49b865.s:540:Rest of line ignored. 1st junk character valued 37 (%).
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-49b865.s:542:Unknown pseudo-op: .cfi_offset
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-49b865.s:542:Rest of line ignored. 1st junk character valued 37 (%).
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-49b865.s:818:Unknown pseudo-op: .cfi_endproc
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-49b865.s:874:Unknown pseudo-op: .cfi_startproc
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-49b865.s:878:Unknown pseudo-op: .cfi_def_cfa_offset
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-49b865.s:878:Rest of line ignored. 1st junk character valued 49 (1).
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-49b865.s:880:Unknown pseudo-op: .cfi_offset
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-49b865.s:880:Rest of line ignored. 1st junk character valued 37 (%).
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-49b865.s:883:Unknown pseudo-op: .cfi_def_cfa_register
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-49b865.s:883:Rest of line ignored. 1st junk character valued 37 (%).
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-49b865.s:887:Unknown pseudo-op: .cfi_endproc
clang: error: assembler command failed with exit code 1 (use -v to see invocation)
Error: afl-fuzz: failed
Failed executing: /usr/local/Cellar/afl-fuzz/2.00b/bin/afl-clang++ -g /private/tmp/afl-fuzz20160212-80698-5m2sbc/main.cpp -o /private/tmp/afl-fuzz20160212-80698-5m2sbc/test
```

**Comment by alex** [comment]
FWIW, I asked about this on the afl mailing list, and Michał said that there were no changes to this part of the code in these releases, which I confirmed with `diff`. I'm very confused.

**Comment by DomT4** [comment]
One thing that did change: Xcode was updated from 7.2 to 7.2.1. Maybe causing a subtle compile bug or something? This is fine and happy on Mavericks, so has to be something different between Mavericks and Yosemite/El Cap.

**Comment by alex** [comment]
Recompiling afl-fuzz 1.96 on my 10.11 machine and the tests still pass, so
I'm confused.

On Fri, Feb 12, 2016 at 9:19 PM, Dominyk Tiller <notifications@github.com>
wrote:

> One thing that did change: Xcode was updated from 7.2 to 7.2.1. Maybe
> causing a subtle compile bug or something? This is fine and happy on
> Mavericks, so has to be something different between Mavericks and
> Yosemite/El Cap.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Homebrew/homebrew/pull/49113#issuecomment-183561200>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by DomT4** [comment]
Yeah, I can repro that. 1.96 is fine on El Cap. The releases since then are problematic on `test do`, apparently.

**Comment by fbrosson** [comment]
Do all build environments have the same locale settings? In particular, are they all configured to use unicode? Would it be possible to reschedule a build with `LANG=en_US.UTF-8` ? Should I change the formula for that?

**Comment by DomT4** [comment]
You can pass `ENV["LC_ALL"] = "en_US.UTF-8"` inside `test do`.

**Comment by fbrosson** [comment]
Thanks for the info. I'll try it very soon.
We have seen that on Mavercks (10.9) everything looks OK, even without any special locale settings. Let's see if with `LC_ALL=en_US.UTF-8` we can make the tests succeed on Yosemite (10.10) and El Capitan (10.11).

**Comment by fbrosson** [comment]
Well, it seems it has nothing to do with the locale settings.
I tried adding `LC_ALL=en_US.UTF-8` to both the install and test blocs, with the same failures.
Then I thied `LC_ALL=C`, but it did not help either.
I also tried afl-clang with C code (instead of C++,) but I got puzzling errors.
Maybe we've hit an upstream issue.
If anyone has a workaround for the formula...

**Comment by ilovezfs** [comment]
@DomT4 @fbrosson OK, the problem is that it doesn't like being invoked with a full path. You can reproduce that without even using the test framework. This fixes the test case, but not the upstream bug, which is an annoyance but not necessarily a show-stopper:
```
diff --git a/Library/Formula/afl-fuzz.rb b/Library/Formula/afl-fuzz.rb
index b2ec75e..355c678 100644
--- a/Library/Formula/afl-fuzz.rb
+++ b/Library/Formula/afl-fuzz.rb
@@ -28,7 +28,8 @@ class AflFuzz < Formula
       }
     EOS
 
-    system "#{bin}/afl-clang++", "-g", cpp_file, "-o", exe_file
+    cd "#{bin}"
+    system "afl-clang++", "-g", cpp_file, "-o", exe_file
     output = `#{exe_file}`
     assert_equal 0, $?.exitstatus
     assert_equal output, "Hello, world!"
```

**Comment by DomT4** [comment]
That is an unusual bug. It's possibly worth telling upstream that seems to be the root cause.

The proposed `test do` fix is fine for now, although it'd be great to add a notation there on not being able to call the full path with a link to an upstream bug submission. You can just do:
```ruby
ENV.prepend_path "PATH", bin
```
As well, rather than wrapping in `#{}`.

**Comment by fbrosson** [comment]
I just made the suggested change but I would be puzzled it it worked. Because whenever a runtime is called invoked without any path, then shell "completes" it, i.e. it passes the "resolved" absolute path as argv[0].

**Comment by DomT4** [comment]
It worked :smile:.

**Comment by ilovezfs** [comment]
I suspect it's a parsing error or just a failure to look up the name properly on OS X when it's magically deciding its behavior based on the name it's invoked with even though it's the same binary.

**Comment by fbrosson** [comment]
That's really strange. It cleared all errors on Travis CI but not on the default build server.
Well, at least we know which direction to dig. Good catch, @ilovezfs  Thanks!
Wait, maybe afl-* does not like being called with very long paths. I'm going to try calling "./afl-clang++" instead of just afl-clang++.

**Comment by ilovezfs** [comment]
./ dies too, of course :)

**Comment by ilovezfs** [comment]
>but not on the default build server
That's some config issue on the server, not an issue with your formula, if you had a look at the report.

**Comment by DomT4** [comment]
>  It cleared all errors on Travis CI but not on the default build server.

The remaining error is unrelated. It's something that crops up with Jenkins from time to time. It flags as a failure but if you check the actual build log it's fine.

**Comment by ilovezfs** [comment]
@DomT4 jinx.

**Comment by fbrosson** [comment]
ok. Oops, I'll revert my second change.

**Comment by fbrosson** [comment]
Jobs [109190989](https://travis-ci.org/Homebrew/homebrew/builds/109190989) and [109198772](https://travis-ci.org/Homebrew/homebrew/builds/109198772) were given the exact same formula, but only the first one passed. The only difference was that the first job was alone on the server, whereas the second had to share the resources with another job. Maybe afl-clang++ is failing to catch a failed memory allocation.

**Comment by fbrosson** [comment]
My previous revert was not complete... I had forgotten to remove the `./` in front of `afl-clang++`. It(s fixed now, and job [#10804](https://travis-ci.org/Homebrew/homebrew/builds/109202347) should pass like [#10799](https://travis-ci.org/Homebrew/homebrew/builds/109190989) did.

**Comment by ilovezfs** [comment]
@DomT4 @fbrosson OK this actually patches the upstream bug:
 ```
diff --git a/Library/Formula/afl-fuzz.rb b/Library/Formula/afl-fuzz.rb
index b2ec75e..9ae9886 100644
--- a/Library/Formula/afl-fuzz.rb
+++ b/Library/Formula/afl-fuzz.rb
@@ -11,6 +11,8 @@ class AflFuzz < Formula
     sha256 "e49e6508d15e54d370c427e7f8e353a6d3eb292d20600b5f2c912c4e8e149c04" => :mavericks
   end
 
+  patch :DATA
+
   def install
     system "make", "PREFIX=#{prefix}"
     system "make", "install", "PREFIX=#{prefix}"
@@ -34,3 +36,17 @@ class AflFuzz < Formula
     assert_equal output, "Hello, world!"
   end
 end
+
+__END__
+diff --git a/Makefile b/Makefile
+index 6df3e53..91c5a5a 100644
+--- a/Makefile
++++ b/Makefile
+@@ -116,6 +116,7 @@ install: all
+ 	mkdir -p -m 755 $${DESTDIR}$(BIN_PATH) $${DESTDIR}$(HELPER_PATH) $${DESTDIR}$(DOC_PATH) $${DESTDIR}$(MISC_PATH)
+ 	rm -f $${DESTDIR}$(BIN_PATH)/afl-plot.sh
+ 	install -m 755 $(PROGS) $(SH_PROGS) $${DESTDIR}$(BIN_PATH)
++	ln -sf afl-as ${DESTDIR}$(BIN_PATH)/as
+ 	if [ -f afl-qemu-trace ]; then install -m 755 afl-qemu-trace $${DESTDIR}$(BIN_PATH); fi
+ 	if [ -f afl-clang-fast -a -f afl-llvm-pass.so -a -f afl-llvm-rt.o ]; then set -e; install -m 755 afl-clang-fast $${DESTDIR}$(BIN_PATH); ln -sf afl-clang-fast $${DESTDIR}$(BIN_PATH)/afl-clang-fast++; install -m 755 afl-llvm-pass.so afl-llvm-rt.o $${DESTDIR}$(HELPER_PATH); fi
+ 	set -e; for i in afl-g++ afl-clang afl-clang++; do ln -sf afl-gcc $${DESTDIR}$(BIN_PATH)/$$i; done
```

The problem is clear if you dump the parameters:
```
GOOD:
param clang++
param -g
param /private/tmp/afl-fuzz20160214-26329-r8t9k/main.cpp
param -o
param /private/tmp/afl-fuzz20160214-26329-r8t9k/test
param -B
param /usr/local/Cellar/afl-fuzz/2.00b/lib/afl
param -no-integrated-as
param -g
param -O3
param -funroll-loops


BAD:
param clang++
param -g
param /private/tmp/afl-fuzz20160214-26329-r8t9k/main.cpp
param -o
param /private/tmp/afl-fuzz20160214-26329-r8t9k/test
param -B
param /usr/local/Cellar/afl-fuzz/2.00b/bin
param -no-integrated-as
param -g
param -O3
param -funroll-loops
```

When argv[0] has a slash, it actually looks for the directory `/usr/local/Cellar/afl-fuzz/2.00b/bin` and finds it. But they forgot to install the symlink `as -> afl-as`. When the path doesn't have a slash, it doesn't even try, and just uses the hard-coded path `/usr/local/Cellar/afl-fuzz/2.00b/lib/afl`, where the symlink `as -> afl-as` is indeed installed.

Relevant code is here:
https://github.com/mcarpenter/afl/blob/master/afl-gcc.c#L77-L96

You can see they actually intended to install it:
https://github.com/mcarpenter/afl/blob/master/Makefile#L111

The reason for the oversight is that they did symlink it up here:
https://github.com/mcarpenter/afl/blob/master/Makefile#L68

But since `as` is not actually one of the progs, it doesn't get installed unless you do it manually. If we add it to the list of installs here https://github.com/mcarpenter/afl/blob/master/Makefile#L118 that also works, but that installs a full copy of the file, which is unnecessary, rather than just copying the symlink.

You can inline the fix in the formula if you want, by adding
```
cd bin
ln_s "afl-as", "as"
```
but it's probably better to use the actual Makefile patch and give it to upstream as well.

**Comment by ilovezfs** [comment]
@DomT4 @fbrosson An alternate fix, of course, which you may prefer is
```
diff --git a/Library/Formula/afl-fuzz.rb b/Library/Formula/afl-fuzz.rb
index b2ec75e..bb39393 100644
--- a/Library/Formula/afl-fuzz.rb
+++ b/Library/Formula/afl-fuzz.rb
@@ -11,6 +11,8 @@ class AflFuzz < Formula
     sha256 "e49e6508d15e54d370c427e7f8e353a6d3eb292d20600b5f2c912c4e8e149c04" => :mavericks
   end
 
+  patch :DATA
+
   def install
     system "make", "PREFIX=#{prefix}"
     system "make", "install", "PREFIX=#{prefix}"
@@ -34,3 +36,25 @@ class AflFuzz < Formula
     assert_equal output, "Hello, world!"
   end
 end
+
+__END__
+diff --git a/afl-gcc.c b/afl-gcc.c
+index 89c2bbc..3c69eb6 100644
+--- a/afl-gcc.c
++++ b/afl-gcc.c
+@@ -72,6 +72,7 @@ static void find_as(u8* argv0) {
+ 
+   }
+ 
++#if 0
+   slash = strrchr(argv0, '/');
+ 
+   if (slash) {
+@@ -94,6 +95,7 @@ static void find_as(u8* argv0) {
+     ck_free(dir);
+ 
+   }
++#endif
+ 
+   if (!access(AFL_PATH "/as", X_OK)) {
+     as_path = AFL_PATH;

```

That will just force it to always use either the environment variable or `/usr/local/Cellar/afl-fuzz/2.00b/lib/afl`, which we know works.

**Comment by DomT4** [comment]
@ilovezfs Nice hunting! Mind submitting that patch upstream and explaining the problems we've been having? It'd be great to get them to accept or at least consider it before we accept it unilaterally.

**Comment by fbrosson** [comment]
@ilovezfs Great hunting indeed! Thanks! I've just changed the formula using your second patch proposal.
@DomT4 As the formula is currently written (in this PR), the patch applies to both stable and head. Should I move the `patch :DATA` line inside a `stable do` block and add a second `patch :DATA` in a `head do` block with a condition based on a `grep` (if possible) in order to only apply the patch for head if necessary (and unconditionally for stable) ? Or is it just fine like this? (We can always drop the patch for head once someone finds out that head got fixed.)
@ilovezfs @DomT4 I included a short comment in the formula just before the `patch :DATA` line. Are you both OK with what I wrote? Please do not hesitate to suggest changes.
Good news: All jobs on Travis CI are OK. And on default the errors due to Jenkins.

**Comment by DomT4** [comment]
Has this patch been submitted upstream yet?

>  Or is it just fine like this? (We can always drop the patch for head once someone finds out that head got fixed.)

Aye. It's fine as-is until we know upstream has accepted it. This formula has quite a unique `head`; normally they are git/svn/bzr/etc, a moving tarball is an unusual one.

**Comment by fbrosson** [comment]
> Has this patch been submitted upstream yet?

I did not contact nor send anything to upstream. I guess @ilovezfs already has.. If not, I'd rather let him do it, since he's the contributor who worked on the bug and created the patch.

**Comment by ilovezfs** [comment]
@DomT4 @fbrosson All right, I sent the following to Michael:
>afl-fuzz find_as() bug

>February 15, 2016 at 10:02 PM To lcamtuf@coredump.cx

>Hi Michael,

>This is about "Compilation error in 1.97b?"
https://groups.google.com/forum/#!topic/afl-users/-aIUjqcnwOM Homebrew reference: https://github.com/Homebrew/homebrew/pull/49113

>I have found the bug as well as a couple different fixes, but Homebrew would prefer not to unilaterally accept the patches. The problem occurs whenever afl-clang++ is invoked with a path containing a slash and it is installed in a DESTDIR where DESTDIR/bin/as doesn't exist. Creating the symlink "as -> afl-as" in DESTDIR/bin fixes the issue. If afl-clang++ is invoked just as "afl-clang++" without any slashes, the bug is avoided because afl-gcc.c will default to using the hard-coded AFL_PATH (i.e., $(PREFIX)/lib/afl/), where the Makefile has indeed installed both afl-as and the symlink "as -> afl-as."

>One solution is to install the symlink "as -> afl-as" in DESTDIR/bin. I don't know if the DESTDIR's you usually install to already contain "as" in their bin subdirectory, though, so that may be a problem because you probably don't want to overwrite any preexisting file named "as" in DESTDIR/bin. Alternatively, the symlink could be installed if and only if a file named "as" isn't already there. However, I'm thinking you probably actually want it using afl-as via a symlink named "as," and don't want it using a preexisting as file, so it may also be a bug that you're currently ending up (unintentionally?) using the preexisting as instead.

>A second solution, and probably the better one, is to remove https://github.com/mcarpenter /afl/blob/master/afl-gcc.c#L75-L96 as I do in this patch: https://github.com/Homebrew/homebrew/pull/49113#issuecomment-183995837
I'm not sure what that code is supposed to be buying you, since the hard-coded path AFL_PATH should always be fine if the Makefile did its job, and if it's not fine, the user can override it using the AFL_PATH environment variable. But perhaps I've misunderstood something, and the problematic code that is used whenever there's a slash is meant to achieve something that isn't possible by just using the hard-coded AFL_PATH or the environment variable.

>Do you like either of my two proposed fixes, or do you have another idea you prefer, like maybe something that allows compilation to succeed even when there's only "afl-as" and no "as"?

>Thanks

**Comment by ilovezfs** [comment]
>This formula has quite a unique head; normally they are git/svn/bzr/etc, a moving tarball is an unusual one.

@DomT4 Maybe better, then, to rely on <url>https://github.com/mcarpenter/afl/</url>?

**Comment by ilovezfs** [comment]
@DomT4 @fbrosson OK, upstream patched it, and I've verified the fix works, so the version just needs to be bumped to 2.01b.

Also, the way the HEAD version is implemented here is broken since it will just use the old tarball with the same name in your Homebrew cache. It would probably be better to make it
```
 head "https://github.com/mcarpenter/afl.git"
```
which is unofficial, but was updated almost immediately, and also has the tags.

Alternatively, Homebrew needs some way to say that cached HEAD tar files for a particular formula should always be invalidated and redownloaded, or needs some way to check the modification time displayed on the http page for the "latest" tarball and download it again if the date doesn't match the timestamp (perhaps in its name) recorded for the cached copy.

**Comment by fbrosson** [comment]
Thanks @ilovezfs & @mcarpenter !
I've updated the formula to use the new 2.01b released today.
@DomT4 & @mcarpenter : I changed `head` to make it point to the Git repo from https://github.com/mcarpenter/afl. Is this OK or should I revert to the afl-latest.tgz link the formula has been using until now? Thanks!

**Comment by ilovezfs** [comment]
@DomT4 @fbrosson Here's upstream's stance:

me:
>Excellent, thank you. Do you mind pushing it to GitHub, too, please?

mz:
>I don't own the github mirror :-) You have to ping the owner.

me:
>Appears to have just happened automagically, which is nice:
https://github.com/mcarpenter/afl/commits/master

>Or the owner noticed very quickly :)

>Would you be willing to start your own? The Homebrew HEAD builds are broken since the tarball name for "latest" doesn't change, and so users' old cached copy will be used. For obvious reasons, Homebrew will prefer and possibly require the repository be owned by you in order to use the URL, though they may be willing to make an exception or implement some kind of workaround if posting to your own GitHub repo isn't in the cards.

mz:
>Is this something I can fix on my end? It doesn't seem like a very
well-behaved approach (sending an If-Modified-Since request would be
better). Or perhaps you could append a random token at the end of the
URL, or scan the directory for the latest numbered version?

>I'm not honestly planning a github repo for AFL; this may change, but
a workaround of some sort probably makes sense.

me:
>What about hosting a repo on your own site? I believe git, svn, cvs, hg, and bzr are all supported.

mz
>It's a security exposure with no compelling benefit on my end. I don't
quite understand what the tgz issue is, though - how does Homebrew
handle other projects that release using versioned tarballs?

me
>The "stable" version+url get manually bumped in the formula by a maintainer, or via a user pull request, followed by a maintainer accepting the pull request. Before either of those happens, all CI/tests are re-run with the new version. Once committed, new binary "bottles" are automatically regenerated. The "head" url is basically never a tarball with a fixed name, but is a repository of some kind.
```
$ ag "head "|grep "\.tar\."
spidermonkey.rb:9:  head "https://hg.mozilla.org/tracemonkey/archive/tip.tar.gz"
$ ag "head "|grep "tgz"
afl-fuzz.rb:6:  head "http://lcamtuf.coredump.cx/afl/releases/afl-latest.tgz"
$ ag "head "|grep "latest"
afl-fuzz.rb:6:  head "http://lcamtuf.coredump.cx/afl/releases/afl-latest.tgz"
```
>This is why they're going to resist any built-in workarounds. Basically no one is doing it that way.

>For your reference:
```
$ ag "head "|grep "git"|wc -l
     811
$ ag "head "|grep "svn"|wc -l
      36
$ ag "head "|grep "hg"|wc -l
      28
$ ag "head "|grep "cvs"|wc -l
       7
$ ag "head "|grep "bzr"|wc -l
       2
```

mz:
/* radio silence */

**Comment by DomT4** [comment]
The reason I don't love head tarballs is because (possibly only with `HOMEBREW_DEVELOPER` set) people can see this message:
```
==> Verifying afl-fuzz-HEAD.tgz checksum
Warning: Cannot verify integrity of afl-fuzz-HEAD.tgz
A checksum was not provided for this resource
For your reference the SHA256 is: 2a92285ee23b2d60ca408724c719a2e66f21600cf061b3b291b2b6933455ca40
tar xvf /usr/local/var/homebrew/cache/afl-fuzz-HEAD.tgz
```
Which understandably spooks 'em :smile:.

**Comment by DomT4** [comment]
(And aye, probably our logic should be more specific than "It is not a git/svn/bzr/etc clone/etc? Checksum it!")

**Comment by ilovezfs** [comment]
@DomT4 This formula has no checksum for the head tarball. The problem is that the cached copy gets used. I wonder if head should have a :disable_cache key of some kind that could be overridden with something like --force-enable-cache.

**Comment by fbrosson** [comment]
As @ilovezfs wrote [above](#issuecomment-184563496), the GitHub unofficial mirror https://github.com/mcarpenter/afl is synchronised with upstream as we can see with https://github.com/mcarpenter/afl/commit/2aa346e445558fb168630835da2086a3febe7d2f. It is either being pulled from upstream to GitHub by @mcarpenter or pushed by upstream to GitHub (with mcarpenter's agreement/credentials).
Therefore the political question is: Should Homebrew use an unofficial repo for `head` ? I see 3 options: assume yes, revert to the afl-latest.tgz link, or comment out `head` in the formula until the cache issue is solved. Just let me know what your preference is and I'll update my commit if needed :-)
BTW, the build finished 14 minutes ago. (Oops, I renamed this PR __after__ pushing my updated commit, that's why Jenkins writes "PR #49113: afl-fuzz 2.00b" but in fact Jenkins was correctly given 2.01b.)

**Comment by DomT4** [comment]
> This formula has no checksum for the head tarball. 

Indeed. Doing so would be incredibly unpractical, given it would need updating often. The logic is [here](https://github.com/Homebrew/homebrew/blob/0b7599f577bfcd701abc5f47cdcdcdfd62e0946d/Library/Homebrew/resource.rb#L119-L122), and I believe because tarballs are files whereas most `head`s generate folders (`git-sh--git`) for example that logic gets activated when it shouldn't.

> Should Homebrew use an unofficial repo for head ? 

We don't, generally, because if anything goes wrong it's on us for accepting it.

> comment out head in the formula until the cache issue is solved.

My preference would be to remove it, personally.

**Comment by fbrosson** [comment]
Fine. I just remved `head`.

**Comment by DomT4** [comment]
Thanks! We had a small internal discussion and are likely to clamp down a bit more on tarballs as `head`s generally. It's not really something we intended to support and it's obviously problematic on keeping cached `head`s up-to-date.

**Comment by ilovezfs** [comment]
@DomT4 Is there any plan to implement some kind of automated, new-version detection, like built-in sparkle checking, grepping for the highest version number from a directory, etc.?

**Comment by DomT4** [comment]
Not at the moment. Various maintainers and external contributors have tried various clever ways to check upstream for automatic updates but so far nothing perfect has popped up. Even if automatic update _checking_ became available, we heavily prefer PRs filed by humans and overseen by humans.

**Comment by ilovezfs** [comment]
@DomT4 Assuming arguendo that the newer version number could be accurately determined, I was thinking it would be something like:
```
brew install --unverified-upstream-version foo
```

**Comment by mcarpenter** [comment]
Hi,

I'm the owner of the unofficial afl repo/mirror that you have found here on github (there is, I think, at least one other). To summarise:

 * Yes, definitely not official (though with Michal's blessing when I set it up).
 * Script automatically polls coredump.cx for new tarballs ~hourly and updates the github repo.
 * This is running from my home... it has been pretty reliable but it's clearly not "five-nines" (or anything close to that).
 *  This repo has my email in the commits (I considered putting Michal's email in there, but that seemed even weirder...). Any future official repo will not match this (hashes).
 * Since it's not official it's missing some early releases. If you are going to depend on it then that precludes me from doing a history re-write should those early releases ever turn up (which I have done at least once before). But I'm okay with that.

Paging @lcamtuf ?

**Comment by lcamtuf** [comment]
Well, I don't have a problem with a distro using a mirror =) It
increases your attack surface a bit (you now depend on two people not
getting owned, versus one), but it's a relatively minor incremental
risk in the grand scheme of things.

/mz

**Comment by ilovezfs** [comment]
@DomT4 perhaps the github repo can be considered sanctified with holy water now?

**Comment by fbrosson** [comment]
Hi @lcamtuf ! I've jist noticed a minor typo in https://github.com/lcamtuf : you forgot the "d" in lcamtuf.core**d**ump.cx.

**Comment by ilovezfs** [comment]
@UniqMartin @DomT4 So can we include mcarpenter's github repo as the head url since lcamtuf he has no problem with it?

**Comment by UniqMartin** [comment]
Not sure why I'm being invoked here, but judging from the discussion I'm leaning more towards removing the `head` URL for now. Is there something major to be gained from retaining it (in modified form)? My gut feeling is that very few people want to build the non-stable version and those don't need Homebrew to help them with that (but I might be wrong).

**Comment by ilovezfs** [comment]
@UniqMartin Thanks for weighing in. Then I believe this PR is good to go as-is.

**Comment by DomT4** [comment]
Sorry, I wasn't online much last night. Even _I_ have to take a break from this project sometimes :wink:.

If upstream officially endorse the GitHub head we're happy to consider it, sure, but I'm with @UniqMartin that unless people demand its return there's not much point for now. Homebrew provides a fairly rough `head` experience as-is, to be fair.

**Comment by DomT4** [comment]
Alright, 51 comments and 7 participants later, merged in https://github.com/Homebrew/homebrew/commit/646d848d68546d926cc225696b43e929241f0330.

Thank for @fbrosson for another contribution to Homebrew, and thank you to everyone else for the help/thoughts/etc! :tada:

**Pull request closed without merging**
