### PR TITLE
boost 1.59.0 redux

### PR DESCRIPTION
**Pull request by tdsmith**
Incorporates #42960 and #43974.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
I think we need to merge this sooner rather than later due to https://github.com/Homebrew/homebrew/issues/40837#issuecomment-141583751. If it breaks stuff we may need to just temporarily vendor or boneyard.

**Comment by tdsmith** [comment]
I've resolved those; everything builds against 1.59. From the tests on Mavericks, it doesn't look ABI compatible, so I think we need to bump dependents as well. I don't know why builds are timing out.

**Comment by tdsmith** [comment]
And 1.59 doesn't solve the issue: https://svn.boost.org/trac/boost/ticket/11664 -- we're better off patching 1.58.

**Comment by tdsmith** [comment]
(unless you can get this to build on test-bot)

**Comment by mikemcquaid** [comment]
@tdsmith I was seeing issues with El Capitan on 10.11 with Xcode 7 timing out if `--verbose` was passed to the bot. I suspect that's the same issue here now that Xcode 7 is on Yosemite too. CC @xu-cheng as we talked about this.

**Comment by xu-cheng** [comment]
Any news? (Probably need rebase first)

**Comment by autosquid** [comment]
Any idea to move this on?

**Comment by mikemcquaid** [comment]
We need to ship this soon. It's blocking the latest MySQL version. @tdsmith what's your ETA on getting this in? If you don't have time to work on it: can you close it so another person can? Thanks!

**Comment by tdsmith** [comment]
I don't know how to troubleshoot the build issues that are stalling this.

This additionally needs patching for the same issue that affected 1.58.

**Comment by tdsmith** [comment]
I do suggest using this branch as a basis for further efforts.

**Comment by autosquid** [comment]
A known bug in `log_setup` in boost 1.59 is fixed here: https://github.com/boostorg/log/pull/10  but will not be available till 1.60. 
Can we patch it  here?

**Comment by mikemcquaid** [comment]
@autosquid Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by autosquid** [comment]
@mikemcquaid  ok, I'll try to do that this weekend.

**Comment by autosquid** [comment]
@mikemcquaid  please check if it is ok. https://github.com/Homebrew/homebrew/pull/45740

**Pull request closed without merging**
