### PR TITLE
cleanup: handle bottle version

### PR DESCRIPTION
**Pull request by xu-cheng**

### CODE REVIEW

**Comment by mikemcquaid** [comment]
:heart_eyes:

**Comment by jacknagel** [comment]
I don't really see a reason that `Version.parse` needs to be responsible for this. Can't we match against `BOTTLE_EXTNAME_RX` before calling it and move this logic out?

My hope was we could entirely remove the pathname crap from Version.parse eventually.

**Comment by jacknagel** [comment]
For example, if we're trying to fix the cache, can't the cache code check if the filename is a bottle and then call the appropriate logic?

**Comment by xu-cheng** [comment]
En, I will try to come to a new approach.

> My hope was we could entirely remove the pathname crap from Version.parse eventually.

I have the similar thought. Also I think we can merge `Version#parse` and `Version#_parse`. There seems to be no reason to have two methods since `bottle_version` is removed.

**Comment by xu-cheng** [comment]
Comment on new version PR?

**Comment by xu-cheng** [comment]
Any comments?

**Comment by xu-cheng** [comment]
@jacknagel @mikemcquaid Good to merge?

**Comment by mikemcquaid** [comment]
:+1:

**Pull request closed without merging**
