### PR TITLE
Tippecanoe 1.3.1

### PR DESCRIPTION
**Pull request by ericfischer**
* Tile generation is multithreaded to take advantage of multiple CPUs
* More compact data representation reduces memory usage and improves speed
* Polygon clipping uses [Clipper](http://www.angusj.com/delphi/clipper/documentation/Docs/_Body.htm)
  and makes sure interior and exterior rings are distinguished by winding order
* Individual GeoJSON features can specify their own minzoom and maxzoom
* New `tile-join` utility can add new properties from a CSV file to an existing tileset
* Feature coalescing, line-reversing, and reordering by attribute are now options, not defaults
* Output of `decode` utility is now in GeoJSON format
* Tile generation with a minzoom spends less time on unused lower zoom levels
* Bare geometries without a Feature wrapper are accepted
* Default tile resolution is 4096 units at all zooms since renderers assume it

### CODE REVIEW

**Comment by DomT4** [comment]
Looks like it's trying to ignore the `prefix` argument, perhaps? We link things ourselves; It's not necessary for projects to try to install to a top level prefix instead.

```
==> make install PREFIX=/usr/local/Cellar/tippecanoe/1.3.1
mkdir -p /usr/local/Cellar/tippecanoe/1.3.1/bin
cp tippecanoe /usr/local/Cellar/tippecanoe/1.3.1/bin/tippecanoe
cp man/tippecanoe.1 /usr/local/share/man/man1/
cp: /usr/local/share/man/man1/tippecanoe.1: Operation not permitted
make: *** [install] Error 1
```

**Comment by ericfischer** [comment]
Oops, that was sloppy of me. Thanks. I'll fix it.

**Comment by ericfischer** [comment]
Thanks. I think it should be fixed now.

**Comment by bfontaine** [comment]
Thank you for your contribution to Homebrew @ericfischer! :tada:

**Pull request closed without merging**
