### PR TITLE
opus 1.1.1

### PR DESCRIPTION
**Pull request by rillian**
New upstream release.

### CODE REVIEW

**Comment by rillian** [comment]
I don't understand the travis failure. This patch has nothing to do with postgres.

```
$ git clean -qxdff
warning: failed to remove Cellar/postgresql/9.4.5/lib
warning: failed to remove Cellar/postgresql/9.4.5/share/doc/postgresql/html
The command "git clean -qxdff" failed and exited with 1 during .
```
https://travis-ci.org/Homebrew/homebrew/jobs/93401888

**Comment by DomT4** [comment]
Ignore the Travis failure, It's unrelated. You want the `default` CI to pass here.

**Comment by rillian** [comment]
Ok, thanks!

**Comment by DomT4** [comment]
We're still ironing out bits of our Travis setup. Our main CI is still the Jenkins one, for now :)

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/463aadc25d02951e69096d555824687bba93911b. Thank you for your contribution to Homebrew @rillian; we appreciate it! :smiley_cat:

**Pull request closed without merging**
