### PR TITLE
pandoc 1.15.1.1

### PR DESCRIPTION
**Pull request by adunning**
Added note on bash completion support (new in this version).

### CODE REVIEW

**Comment by adunning** [comment]
Sorry, @dunn, #45073 hadn't been created yet when I looked earlier! Should I close this one, or do we want to keep the note on bash completion support?

**Comment by dunn** [comment]
Oh cool, thanks for noticing that addition! Let's go with this PR.

Since `pandoc --bash-completion` generates a completion script, how about we install it for the user?  Something like this should work, after `cabal_clean_lib`:
```ruby
(bash_completion/"pandoc").write shell_output("#{bin}/pandoc --bash-completion")
```

**Comment by adunning** [comment]
That's an excellent idea. I won't be able to get to this until Monday, so if you want to throw that into your version, that would be brilliant; but if you don't have the time, I can take care of it later.

**Comment by adunning** [comment]
I've updated this for 1.15.1.1. I had to modify the line to install the bash completion script slightly, since `shell_output` doesn't work in that context, but it works otherwise; thanks for the pointer!

**Comment by dunn** [comment]
The test failure was the fault of the bot:
```
[ 4 of 18] Compiling Text.TeXMath.Readers.MathML.EntityMap ( src/Text/TeXMath/Readers/MathML/EntityMap.hs, dist/dist-sandbox-8039fe57/build/Text/TeXMath/Readers/MathML/EntityMap.o )
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/ghc89119_0/ghc_21.s: hPutBuf: resource exhausted (No space left on device)
cabal: Error: some packages failed to install:
texmath-0.8.4 failed during the building phase. The exception was:
ExitFailure 1

**Comment by xu-cheng** [comment]
Thanks for the pull request! 🎉 Homebrew depends on contributions from community members like you and we're grateful for your support.

**Pull request closed without merging**
