### PR TITLE
htop: add "ncurses" dependency

### PR DESCRIPTION
**Pull request by youtux**
`htop` supports mouse scrolling, but needs to be built with `ncurses` >= 6

See https://github.com/hishamhm/htop/issues/322

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Is it possible to use the OS X ncurses version? Also, this should probably be `:optional` for now.

**Comment by youtux** [comment]
I believe that El Capitan ships with ncurses 5.7. So it is possible to compile `htop` without the `homebrew/dupes/ncurses` dependency, but it will not support mouse scrolling.

Should I set it to `:optional` then?

**Comment by dunn** [comment]
Yeah, I think so.  Also please use the full name of ncurses, so:
```ruby
depends_on "homebrew/dupes/ncurses" => :optional
```
Thanks!

**Comment by youtux** [comment]
What about
```ruby
  option "with-ncurses", "Build using homebrew ncurses (enables mouse scroll)"
  depends_on "homebrew/dupes/ncurses" => :optional
```
for a more detailed explaination?

**Comment by DomT4** [comment]
That should be fine.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/ae109fb3fea22bc9a1e8217ed4deef505a6310b5. Thank you for another contribution to Homebrew @youtux! :smiley_cat:

**Pull request closed without merging**
