### PR TITLE
kubernetes-cli 0.12.1

### PR DESCRIPTION
**Pull request by mnuessler**

### CODE REVIEW

**Comment by DomT4** [comment]
Checksum seems to be off:

```
==> Downloading https://github.com/GoogleCloudPlatform/kubernetes/archive/v0.12.1.tar.gz
Warning: Formula reports different SHA256: b935b33b843a54e7ee805041e6be889addcd7fee24f1b64376f390e51612230c
Downloaded to: /Library/Caches/Homebrew/kubernetes-cli-0.12.1.tar.gz
SHA1: c53f2ef221d9fae87b68bf34790eef468c0b2e8b
SHA256: a119cfafe512fa6847dcd3ef728e5c7cd1a09cd83f2af8720d81d9e76c05d8c2
```

Reproducible locally:

```
a119cfafe512fa6847dcd3ef728e5c7cd1a09cd83f2af8720d81d9e76c05d8c2  v0.12.1.tar.gz
```

**Comment by mnuessler** [comment]
Checksum was indeed wrong, fixed it.

**Comment by DomT4** [comment]
Thanks! Looks good now :).

**Comment by asparagui** [comment]
Thanks!

**Pull request closed without merging**
