### PR TITLE
Fixed Xcode download location

### PR DESCRIPTION
**Pull request by zebMcCorkle**

### CODE REVIEW

**Comment by DomT4** [comment]
We use the existing version in another couple places as well. Presumably, if we wanted to change one, we'd be better changing them all. Will let the other maintainers review this and we'll make a decision.

Given the current link presents as a big login screen tagged "Developer" when you can actually log in and download Xcode with any standard Apple ID, and we've seen people get confused by this, I don't mind the change to the friendlier initial Xcode page.

**Comment by dunn** [comment]
Should we change them all at once?

**Comment by mikemcquaid** [comment]
Yeh, let's update this globally, it's a much nicer page.

**Comment by DomT4** [comment]
Other locations for this particular string in this context are `blacklist.rb`, `requirements.rb` and `doctor.rb`.

**Pull request closed without merging**
