### PR TITLE
Upgrade juju 1.25.2

### PR DESCRIPTION
**Pull request by AdamIsrael**

### CODE REVIEW

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/bf5bae18bd9373aa256b1e83bed349421ed989bf. Thank you for your contribution to Homebrew @AdamIsrael; we appreciate it! :smiley_cat:

**Comment by AdamIsrael** [comment]
What's the process to roll back this merge? Unfortunately, I misread the release date on juju 1.25.2 and the previous formula, 1.25.0, is still current.

**Comment by DomT4** [comment]
Is it worth waiting till the end of the day to see what happens?

> juju-core 1.25.2

> A new proposed stable release of Juju, juju-core 1.25.2, is now available.
This release may replace version 1.25.0 on Thursday January 21.

**Comment by AdamIsrael** [comment]
Unfortunately not. That page hasn't been updated to reflect a blocking bug, and the next release to be proposed is 1.25.3, and I don't have an ETA on that yet.

**Comment by AdamIsrael** [comment]
Of course, just after writing that I see this: 

    A new proposed stable release of Juju, juju-core 1.25.3, is now available.
    This release may replace version 1.25.0 on Thursday January 21.

So, I'm open to suggestions for the next step. I can update this pull request (or create a new one) for 1.23.3, pending its potential release today.

**Comment by DomT4** [comment]
Heh. I've reverted the accidental version update from this PR for now. If upstream cut a confirmed release today confirmed stable feel free to cut a new PR to handle that and we'll merge that in.

Thanks for double checking various bits and pieces on this, appreciate the effort!

**Pull request closed without merging**
