### PR TITLE
ImageMagick update to version 6.9.1-9

### PR DESCRIPTION
**Pull request by timster**
ImageMagick has updated to version 6.9.1-9 yesterday.

### CODE REVIEW

**Comment by tdsmith** [comment]
Thanks for your pull request! :tada: Homebrew thrives because of contributions like this one. Merged in 9f7cf2b17.

**Comment by leoj3n** [comment]
This release is no longer on the server... http://www.imagemagick.org/download/releases

**Comment by dunn** [comment]
@leoj3n not the first time this has happened :/ 

Would you be willing to open a pull request, updating imagemagick to the latest version? Thanks!

**Comment by leoj3n** [comment]
@dunn The formula is complex and I'm not sure what needs to be edited... Maybe someone with more domain specific knowledge?

**Comment by dunn** [comment]
Unless it's an unusual update with major changes, you can just update the `url` and `sha256` like this PR does.

**Comment by leoj3n** [comment]
#42131

**Pull request closed without merging**
