### PR TITLE
elixir 1.0.5

### PR DESCRIPTION
**Pull request by thecodeboss**
Elixir updated to 1.0.5

### CODE REVIEW

**Comment by brunoadacosta** [comment]
\o nice

**Comment by edude03** [comment]
Does Elixir need to be updated to OTP-18 as well or can you built it on 17 still?

**Comment by thecodeboss** [comment]
I can verify it still builds fine on OTP-17. My understanding is that 1.0.5 only adds support for OTP-18, and it does not deprecate OTP-17.

**Comment by DevL** [comment]
Elixir 1.0.5 supports OTP 17+.
Elixir 1.1 will most likely require OTP 18.

**Comment by orendon** [comment]
:+1: for this

Prolly worth to change the message `Erlang 17 is required to install` to `Erlang 17+` to avoid any confusion, see [Formula/elixir.rb#L14](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/elixir.rb#L14)

**Comment by thecodeboss** [comment]
Thanks for the suggestion @orendon, I've modified the formula with that change.

**Comment by reset** [comment]
:+1: looking forward to this being merged

**Comment by scohen** [comment]
:+1:  Really looking forward to having 1.0.5, it fixes behavior in Record that we need.

**Comment by drewolson** [comment]
I'd also love to get this merged soon(ish).

**Comment by DomT4** [comment]
Just to double check: If we pull this now it doesn't break `elixir` for current users, and if we pull this now it won't break when we fire the gun on merging the updated `erlang`?

**Comment by drewolson** [comment]
@DomT4 correct on both counts.

**Comment by scohen** [comment]
Correct, this is compatible with r17 and r18.

**Comment by thecodeboss** [comment]
@DomT4 Those two are correct, this will not break elixir for current users, and it will not break with the updated erlang.

**Comment by DomT4** [comment]
Thanks all for the reply, and to @thecodeboss for the contribution to Homebrew. Merged in https://github.com/Homebrew/homebrew/commit/f670569c419ef96a32f2a5e84376184dccf655c2.

**Pull request closed without merging**
