### PR TITLE
mldonkey: fix build with recent ocaml

### LINKED ISSUE #41256: mldonkey failed to build on 10.10 [fixed]
brew install mldonkey
==> Downloading https://downloads.sourceforge.net/project/mldonkey/mldonkey/3.1.5/mldonkey-3.1.5.tar.bz2
Already downloaded: /Library/Caches/Homebrew/mldonkey-3.1.5.tar.bz2
==> ./configure --prefix=/usr/local/Cellar/mldonkey/3.1.5
********  Objective-Caml 3.12.0 is required  *********
*******  Check http://caml.inria.fr/  ********
Do you want this script to try to download and install ocaml
LOCALLY in mldonkey directory ?
./configure: line 4943: read: read error: 0: Bad file descriptor

### PR DESCRIPTION
**Pull request by mistydemeo**
Fixes #41256.

### CODE REVIEW

**Comment by designer9418** [comment]
➜  ~  brew install mldonkey
    ==> Downloading https://downloads.sourceforge.net/project/mldonkey/mldonkey/3.1.
    Already downloaded: /Library/Caches/Homebrew/mldonkey-3.1.5.tar.bz2
    ==> Downloading https://github.com/ygrek/mldonkey/commit/c91a78896526640a301f5a9
    Already downloaded: /Library/Caches/Homebrew/mldonkey--patch-1fb503d37eed92390eb891878a9e6d69b778bd2f1d40b9845d18aa3002f3d739.patch
    ==> Patching
    patching file src/utils/net/terminal.ml
    ==> ./configure --prefix=/usr/local/Cellar/mldonkey/3.1.5
    ==> make install
    File "src/utils/extlib/IO.ml", line 747, characters 4-21:
    Warning 3: deprecated: String.unsafe_set
    File "src/utils/extlib/IO.ml", line 1:
    Error: Could not find the .cmi file for interface src/utils/extlib/IO.mli.
    make: *** [src/utils/extlib/IO.cmx] Error 2

**Comment by mistydemeo** [comment]
Interesting, I wonder if it's picking up anything from my local opam registry. It builds locally for me.

**Comment by mistydemeo** [comment]
@BrewTestBot test this please

**Comment by mistydemeo** [comment]
Curious. It failed *only* on 10.9, with a totally different error?

```
Error: Files src/utils/cdk/printf2.cmx and src/utils/lib/autoconf.cmx
       make inconsistent assumptions over interface Autoconf
make: *** [build/cdk.cmxa] Error 2
make: *** Waiting for unfinished jobs....
```

**Comment by mistydemeo** [comment]
@BrewTestBot test this please

**Comment by korsmakolnikov** [comment]
Finally it works.

**Pull request closed without merging**
