### PR TITLE
lv2file 0.84 (new formula)

### PR DESCRIPTION
**Pull request by david0**

### CODE REVIEW

**Comment by bfontaine** [comment]
The audit is failing:
```
==> audit problems
lv2file:
 * GitHub repository not notable enough (<10 forks, <10 watchers and <20 stars)
```

**Comment by david0** [comment]
Hm. If thats necessary to be added to homebrew, then this PR can be closed.

I think nevertheless this tool might have so small notability using this metric because its very specific application and has limited scope. Also, its named explicitly on http://lv2plug.in/pages/developing.html.

**Comment by mikemcquaid** [comment]
Passing on this for now, I recommend creating your own tap for this. Sorry!

**Comment by david0** [comment]
Thats ok for me. Thank you for your effort anyway. Merry christmas!

**Comment by mikemcquaid** [comment]
@david0 And to you!

**Pull request closed without merging**
