### PR TITLE
download_strategy: private method allowing extra curl options.

### PR DESCRIPTION
**Pull request by indrajitr**
This allows some curl options to be always passed to curl, with raw
head calls (`curl -I`) (in `CurlDownloadStrategy#actual_urls`) or with
actual `curl` (in `CurlDownloadStrategy#curl`).

This also avoid the need for overriding whole `_fetch` in a few cases
and just override `_curl_opts` to append additional options instead.

NB: As suggest by @mikemcquaid, this is initial stab at fixing [this]( https://github.com/Homebrew/homebrew/commit/7822f70c06ead5189dd0d308f3550f9924656537#commitcomment-12052731)

### CODE REVIEW

**Comment by xu-cheng** [comment]
cc @Homebrew/owners. LGTM :+1:

**Comment by mikemcquaid** [comment]
Makes sense to me.

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Comment by indrajitr** [comment]
Wow, this was _quick_. Thank you all for running this project so efficiently!

**Comment by DomT4** [comment]
Is the line on 403 breaking the SSL3 download? It seems to have removed the `'-C', downloaded_size, '-o', temporary_path` part?

Only glanced over this for 5 seconds, feel free to say if I'm being an idiot.

**Comment by mikemcquaid** [comment]
@DomT4 SSL3 download? Can you give a test case?

**Comment by indrajitr** [comment]
`CurlSSL3DownloadStrategy` doesn't override `#_fetch` anymore, instead it just overrides `#_curl_opts` and appends the necessary options. `#_fetch` in `CurlDownloadStrategy` does the rest.

@DomT4, any concern with the approach?

**Comment by DomT4** [comment]
@mikemcquaid To be honest I'm not aware of anything that isn't at least capable of TLSv1 these days. In an ideal world I'd tag it as `@deprecated` and remove it in 6 months or something.

> any concern with the approach?

Nope, as long as it works. My concern was just a presumption that we'd deliberately kept them apart in the past for some reason, but I hadn't looked into it deeply yet.

**Comment by indrajitr** [comment]
Agreed on deprecating, I too assumed there might have been an use case somewhere.

>> any concern with the approach?

> Nope, as long as it works. My concern was just a presumption that we'd deliberately kept them apart in > the past for some reason, but I hadn't looked into it deeply yet.

Ok, I just took that as a demonstrable use case where `#_curl_opts` would be useful in DRY-ing up without overriding `#_fetch`.

**Comment by DomT4** [comment]
I think we're fine to just remove it now, to be honest. SSLv3 has breakage all over the shop, and we should find alternatives for servers & formulae that rely on SSLv3 to fetch exclusively (There are none in the core). Opened #41536.

**Comment by indrajitr** [comment]
:+1:

**Pull request closed without merging**
