### PR TITLE
mktorrent: add openssl dependency

### LINKED ISSUE #43927: mktorrent failed to build on 10.11
https://gist.github.com/3ef67948b9591e18f749

Can't find OpenSSL.

```
#include <openssl/sha.h> /* SHA1() */
         ^
1 error generated.
make: *** [hash_pthreads.o] Error 1
```

### PR DESCRIPTION
**Pull request by apjanke**
Fixes #43927

### CODE REVIEW

**Comment by DomT4** [comment]
Please bump the revisions when you add new `openssl` dependencies, if it was previously hooking the system. Thanks!

**Comment by apjanke** [comment]
Bumped revision.

**Comment by apjanke** [comment]
Say, there's several more formulae like this that are failing on 10.11 due to the missing OpenSSL dependency. Should I combine them in a single PR, for the ones that only need the `depends_on "openssl"` + revision bump? Or keep them as one formula per PR?

**Comment by DomT4** [comment]
In this case I'd probably keep them in single PRs, just in case anything goes wrong with one of the builds. The CI is backed up at the moment & larger PRs carry greater risk of something breaking.

I presume you are but check these locally as well, as the El Cap bot isn't yet available for public PR checking.

**Comment by apjanke** [comment]
Yeah, I'm doing a `brew install` && `brew test` on my 10.11 Public Beta 6 / Xcode 7 GM / with CLT box for each of these before submitting the PR. I'll add a `brew audit` now that you mentioned it in one of the other comments.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/1b602f88a590f19826935f945cc16b82decf4226. Thanks again!

**Pull request closed without merging**
