### PR TITLE
travis: remove ruby path tweak

### PR DESCRIPTION
**Pull request by xu-cheng**

### CODE REVIEW

**Comment by xu-cheng** [comment]
@UniqMartin any idea on ci failure?

**Comment by UniqMartin** [comment]
This might be due to the `#!/usr/bin/env ruby` shebang in `Library/Homebrew/test/vendor/bundle/ruby/1.8/bin/rake`, that I'm also seeing locally. I'm not sure yet what causes this line to be written, though. And I don't understand yet why that doesn't cause any issues when testing locally.

**Comment by UniqMartin** [comment]
> And I don't understand yet why that doesn't cause any issues when testing locally.

After wiping `Library/Homebrew/test/vendor/bundle` and `~/.gem` I see the same issue locally. It has something to do with what shebangs are generated by RubyGems and/or Bundler. Currently, we get `#!/usr/bin/env ruby` and this breaks if the matching Ruby binary is not in `PATH`.

I won't have much time this weekend, so feel free to ponder this issue yourself, if you like. Otherwise I'll investigate how to change this behavior next week …

**Comment by xu-cheng** [comment]
@UniqMartin recently I may not have time around to further debug this. And it doesn't work nicely with my rbenv settings. So I will close PR. Feel free to work on a new PR yourself.

**Comment by UniqMartin** [comment]
Alright, I'll revisit this issue in a PR of my own as soon as I find the time. Thanks for giving it a try!

**Comment by xu-cheng** [comment]
Thanks

**Comment by UniqMartin** [comment]
Should be addressed by #47694.

**Pull request closed without merging**
