### PR TITLE
phantomjs 2.1.0

### PR DESCRIPTION
**Pull request by dunn**
The test will fail (https://github.com/ariya/phantomjs/issues/13876), but I'm opening this so people see we're aware of the new version and we don't get a flurry of PRs.

### CODE REVIEW

**Comment by DomT4** [comment]
> The test will fail

Apparently it did not :smile_cat:.

**Comment by dunn** [comment]
Huh!  I wonder if it's possible that a sandbox test only fails after a non-sandboxed install.

**Comment by DomT4** [comment]
Should _theoretically_ be possible if it is somehow remembering where `HOME` is during the build.

**Comment by dunn** [comment]
Nope, rebuilt locally in a sandbox and still failed.

Should I go ahead and merge this anyway?

**Comment by DomT4** [comment]
Huh, odd. Maybe run it back through CI to see if the first pass was just lucky or something? :confused:

**Comment by mikemcquaid** [comment]
Given our tests exist just for our CI: given it's passing and created a bottle, I decided to :ship: this. Nice work @dunn!

**Pull request closed without merging**
