### PR TITLE
gnu-apl: use secure mirror

### PR DESCRIPTION
**Pull request by DomT4**
Kicked over from #41770 for reasons discussed there.

### CODE REVIEW

**Comment by DomT4** [comment]
@mikemcquaid Any idea why the test-bot is incapable of installing the bottle generated here? It's a tiny build and tiny bottle, and I don't have any issues locally or on another VM, but every time I run it through the bot it freezes up until timeout :confounded:.

**Comment by mikemcquaid** [comment]
@DomT4 Looks like the test is freezing rather than the install?

**Comment by DomT4** [comment]
Well, now I feel like an idiot. I'll check it out.

**Comment by DomT4** [comment]
:eyes: 

```
==> /usr/local/Cellar/gnu-apl/1.4/bin/apl -s -f hello.apl
Executable ./Cellar/.4/bipl/1.4/bin/APs/APserver not found.
This could means that 'apl' was not installed ('make install') or that it
was started in a non-standard way. The expected location of APserver is
either the same directory as the binary 'apl' or the subdirectory 'APs' of
that directory (the directory should also be in $PATH).
::connect() to existing APserver failed: Invalid argument
Svar_DB not connected in Svar_DB::is_registered_id()
```

That `Executable` path is er, unusual.

**Comment by DomT4** [comment]
If you open a new shell after installation the `executable` path error goes away and is replaced by:

```
==> /usr/local/Cellar/gnu-apl/1.4/bin/apl -s -f hello.apl
::connect() to existing APserver failed: Invalid argument
Svar_DB not connected in Svar_DB::is_registered_id()
```

Will keep looking into it.

**Pull request closed without merging**
