### PR TITLE
src (formula): add dependency on rcs

### PR DESCRIPTION
**Pull request by L2G**
Eric Raymond's "src" utility is a wrapper for RCS, thus depends on it.

### CODE REVIEW

**Comment by L2G** [comment]
I was inclined to add a revision number to this formula so that "brew upgrade" would automatically take care of the new dependency, but I wasn't sure whether that would be welcome.

**Comment by tdsmith** [comment]
Sorry if this is a dumb question, but do you know why the test succeeds without the rcs dependency if src needs rcs? (I assume it's not on the build bots!) Can you add a test that fails if rcs is missing?

**Comment by mikemcquaid** [comment]
Perhaps it's only needed on Mountain Lion and below? Can you remove the `depends_on` for Mavericks to see? Thanks!

**Comment by bfontaine** [comment]
@tdsmith the test is already using `rcs` ([with `src commit`](https://github.com/Homebrew/homebrew/pull/34165#issuecomment-62960123)). Maybe that’s why it fails on Mountain Lion.

**Comment by tdsmith** [comment]
Yeah, the test fails for me locally (without RCS installed) on Yosemite the same way it failed on Mountain Lion in that PR.

Heh, maybe some of the build bots have RCS installed.

**Comment by mikemcquaid** [comment]
Yeh, must be on the machines somehow. Weird.

**Pull request closed without merging**
