### PR TITLE
Update mupdf tools url

### PR DESCRIPTION
**Pull request by adlermedrado**
The URL was incorrect on Formula, so I need to update it pointing to the right place.

### CODE REVIEW

**Comment by DomT4** [comment]
It looks like the URL was moved because there's a new version. You could do the version bump instead,  if you'd like to.

**Comment by mikemcquaid** [comment]
> It looks like the URL was moved because there's a new version. You could do the version bump instead, if you'd like to.

That'd be good :+1:

**Comment by adlermedrado** [comment]
Sure, will do.

**Comment by DomT4** [comment]
Thanks!

**Comment by tomafro** [comment]
I've bumped the version here: https://github.com/Homebrew/homebrew/pull/46669

**Comment by chdiza** [comment]
We can in future avoid the disappearing older versions problem by switching the base of the URL to `http://mupdf.com/downloads/archive/`, where the newest versions AND the older ones are all stored.  This way, when we're caught between the time of new release and the time where someone *realizes* there's a new release, the formula will still work.

**Pull request closed without merging**
