### PR TITLE
Build libfreenect with OpenNI2 support by default, new formula for libfreenect2

### PR DESCRIPTION
**Pull request by xionglingfeng**
1. Build libfreenect with OpenNI2 support by default
2. New formula for libfreenect2 (some dirty hack applied to workaround `libusb-1.0` #41647)

### CODE REVIEW

**Comment by dunn** [comment]
Since libfreenect2 doesn't have a stable release yet it's going to need to start in the [head-only](https://github.com/Homebrew/homebrew-head-only) repository unfortunately.

**Comment by dunn** [comment]
But adding `"-DLibUSB_INCLUDE_DIRS=#{Formula["libusb"].include}/libusb-1.0"` to the cmake argument list should let you avoid all those `inreplace`s.

**Comment by xionglingfeng** [comment]
I created another [PR](#41846) for `libfreenect` and I will move `libfreenect2` to head-only repository.

**Comment by dunn** [comment]
Great! I'll close this one; let me know if you have any questions!

**Pull request closed without merging**
