### PR TITLE
Kubernetes CLI v1.1.3 stable / v1.2.0-alpha.4 devel

### PR DESCRIPTION
**Pull request by antoineco**

### CODE REVIEW

**Comment by bfontaine** [comment]
It would be awesome if you could make one commit for each version.

**Comment by antoineco** [comment]
Sure thing

**Comment by DomT4** [comment]
Appreciate how minor this is but we don't use `v` for `version` in the commit message, just:
```
something 1.2.3
```
Just a tiny style thing.

Merged in https://github.com/Homebrew/homebrew/commit/c1de0c703bd71d4ed7d6bbb78162590a23f21fa2 & https://github.com/Homebrew/homebrew/commit/5235dc74d0bbb7a5143eddd80fe6fe086b5d9fc3. Thank you for your contributions to Homebrew @antoineco; we appreciate them! :smiley_cat:

**Comment by apjanke** [comment]
@bfontaine et al: to clarify, were you just asking for separate commits in a single PR on this, or separate PRs? It's okay to have both stable and dev in a single PR, right? Splitting them in to separate PRs can cause audit failures if the stable version gets ahead of dev.

**Comment by antoineco** [comment]
He probably meant 2 commits in 1 PR indeed. I think I'm the one who got it wrong :)

**Comment by bfontaine** [comment]
Yeah I meant multiple commits in one PR; sorry if that was unclear.

**Pull request closed without merging**
