### PR TITLE
polarssl => mbed-tls

### PR DESCRIPTION
**Pull request by DomT4**
PolarSSL is/has rebranded to ‘mbed TLS’ as part of their acquisition by ARM. This includes a name change, a change of lib names, a change of license (soonish) and a change to Git names and website addresses in the near future.

Due to the fairly awful way Git handles formulae renames, thought the best way to handle this was to first boneyard PolarSSL, and then introduce the replacement here. Have adapted the affected formulae, which are thankfully few.

It looks like one has just replaced the other, but there is two separate commits, one which removes PolarSSL, and another which introduces the replacement and fixes up the formulae. If this still breaks git let me know and I'll split them into entirely different PRs.

**References:**

* https://polarssl.org/tech-updates/releases/mbedtls-1.3.10-released
* https://community.arm.com/groups/internet-of-things/blog/2015/02/09/polarssl-is-dead-long-live-mbed-tls
* https://github.com/Homebrew/homebrew-boneyard/pull/38

### CODE REVIEW

**Comment by mikemcquaid** [comment]
We should probably just add an alias here for the new name instead so people can upgrade.

**Comment by DomT4** [comment]
As in keep PolarSSL but alias the new name, or keep the new formula but alias the PolarSSL name?

**Comment by mikemcquaid** [comment]
> As in keep PolarSSL but alias the new name

This. Upstream might not be happy but that's life, unfortunately.

**Comment by DomT4** [comment]
Cool. I'll close this out and close the boneyard PR and tee up a new PR here - That helps preserve the historical discussion if someone from upstream comes looking at some point.

**Pull request closed without merging**
