### PR TITLE
Update passenger to version 5.0.21

### PR DESCRIPTION
**Pull request by FooBarWidget**

### CODE REVIEW

**Comment by mikemcquaid** [comment]
@BrewTestBot test this please

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/c95dfabb109b176b1ff619d336b84730f156c92f. Thank you for another contribution to Homebrew @FooBarWidget! :smiley_cat:

**Comment by FooBarWidget** [comment]
No need to thank me, my release script sent the pull request for me. ;)

**Comment by DomT4** [comment]
Thank you for writing a clever release script then! :wink:

**Pull request closed without merging**
