### PR TITLE
node 5.1.0

### PR DESCRIPTION
**Pull request by chrmoritz**
This PR updates [Node to v5.1.0](https://nodejs.org/en/blog/release/v5.1.0/) and [npm to v3.4.0](https://github.com/npm/npm/releases/tag/v3.4.0).

### CODE REVIEW

**Comment by bcomnes** [comment]
5.1.0 is shipping npm 3.3.12.  Are we tracking that?  Other than that LGTM.

**Comment by xeoneux** [comment]
#46118 fixes npm version to 3.3.12

**Comment by DomT4** [comment]
Apologies @chrmoritz; I'm tracking backwards through open PRs and missed this being open as well as the more recent Node PR, which I merged.

We are attempting to track major/minor versions of `npm`, but not patch. In this case, `3.3.12` is preferable. If `3.3.13` became available before a new Node release and it contained something important we'd accept that, but we wouldn't necessary want to jump to `3.4.x` just yet, essentially.

**Comment by bcomnes** [comment]
> We are attempting to track major/minor versions of npm

@DomT4 should there be a comment about this in the formula? e.g. `please track the major.minor.* version of npm shipping with node.js`

**Comment by DomT4** [comment]
Fair point. https://github.com/Homebrew/homebrew/commit/3d1e01ba7dbb8e3e1b592f88a287e0f486a42d92

**Pull request closed without merging**
