### PR TITLE
Update smartmontools.rb

### PR DESCRIPTION
**Pull request by AustinChou**
fixed a issue that cause $PATH not containing smartmontools binaries

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Where were they being installed before?

**Comment by AustinChou** [comment]
They were installed to /usr/local/Cellar/smartmontools/x.y/bin but not linked to /usr/local/bin. I browsed the [official document](http://www.smartmontools.org/browser/trunk/smartmontools/INSTALL) and I found out that we should add `--sbindir` arguments.

**Comment by mikemcquaid** [comment]
If they were in `x.y/bin` they'd be linked in `local/bin`. Are you sure they weren't in `sbin`?

**Comment by jacknagel** [comment]
Since we've very, very slowly been installing fewer things into sbin, I think this is OK.

**Pull request closed without merging**
