### PR TITLE
Agda: Tweak layout; bump revision

### LINKED ISSUE #47189: Agda: Post-install dependency on GHC
One of the tests for the Agda formula is currently failing. (https://github.com/Homebrew/homebrew/pull/47181#issuecomment-166008072, https://github.com/Homebrew/homebrew/issues/45318#issuecomment-166021855)

cc @dunn

The symptoms indicate that GHC is unable to find the `agda-lib-ffi-0.11` package.
```
Calling: ghc -O -o /private/tmp/agda20151219-14447-53rowc/stdlib-test -Werror -package-db=/usr/local/Cellar/agda/2.4.2.4_1/agda-stdlib/ffi/package.conf.d -i/private/tmp/agda20151219-14447-53rowc -main-is MAlonzo.Code.QstdlibZ45Ztest /private/tmp/agda20151219-14447-53rowc/MAlonzo/Code/QstdlibZ45Ztest.hs --make -fwarn-incomplete-patterns -fno-warn-overlapping-patterns
Compilation error:

MAlonzo/Code/Foreign/Haskell.hs:4:18:
    Could not find module ‘Data.FFI’
    Use -v to see a list of the files searched for.

MAlonzo/Code/Foreign/Haskell.hs:5:18:
    Could not find module ‘IO.FFI’
    Use -v to see a list of the files searched for.
```

This is confirmed by running a check on Agda’s dedicated GHC package database.
```
$ ghc-pkg -f /usr/local/Cellar/agda/2.4.2.4_1/agda-stdlib/ffi/package.conf.d check
WARNING: cache is out of date: /usr/local/Cellar/agda/2.4.2.4_1/agda-stdlib/ffi/package.conf.d/package.cache
ghc will see an old view of this package db. Use 'ghc-pkg recache' to fix.
WARNING: cache is out of date: /usr/local/Cellar/ghc/7.10.3a/lib/ghc-7.10.3/package.conf.d/package.cache
ghc will see an old view of this package db. Use 'ghc-pkg recache' to fix.
There are problems in package agda-lib-ffi-0.11:
  Warning: haddock-interfaces: /usr/local/Cellar/agda/2.4.2.4_1/agda-stdlib/ffi/share/doc/x86_64-osx-ghc-7.10.2/agda-lib-ffi-0.11/html/agda-lib-ffi.haddock doesn't exist or isn't a file
  Warning: haddock-html: /usr/local/Cellar/agda/2.4.2.4_1/agda-stdlib/ffi/share/doc/x86_64-osx-ghc-7.10.2/agda-lib-ffi-0.11/html doesn't exist or isn't a directory
  dependency "base-4.8.1.0-075aa0db10075facc5aaa59a7991ca2f" doesn't exist

The following packages are broken, either because they have a problem
listed above, or because they depend on a broken package.
agda-lib-ffi-0.11
```

GHC has recently been updated to 7.10.3, and the current version of the `base` package is now 4.8.2.0.  The `agda-lib-ffi-0.11` package included in the Agda bottle has been built with GHC 7.10.2, and still references the previous version of the `base` package, which no longer exists on the system.

I believe incrementing the revision number for the Agda formula should fix the issue — for now.

### PR DESCRIPTION
**Pull request by mietek**
Fixes #47189.

cc @dunn @mikemcquaid

### CODE REVIEW

**Comment by dunn** [comment]
If I'm understanding your comment in https://github.com/Homebrew/homebrew/issues/47189#issuecomment-166024023, it sounds like GHC should be a run-time dependency.

**Comment by mietek** [comment]
@dunn: GHC already _is_ a run-time dependency, conditional on the default option `--with-malonzo`.

All three jobs timed out; frobbing.

**Comment by dunn** [comment]
Oh, right.  Then it seems like these breakages should be caught when the test-bot checks Agda during GHC updates.

**Comment by mietek** [comment]
Well, that would be nice, but I haven’t seen anything to this effect.

**Comment by mietek** [comment]
Could the failures have been masked by jobs timing out?

**Comment by dunn** [comment]
The Jenkins builds aren't timing out.

**Comment by mietek** [comment]
OK. Well, the Travis build are timing out repeatedly; in any case, I tested the change locally and can confirm it fixes the problem.

**Comment by DomT4** [comment]
Ignore Travis timeouts, they're a non-issue really. If Travis times out and Jenkins is green, you're still golden.

I think the need for this bump was my screw up, so my apologies for that. This formula has kind of a reputation for the test breaking without any runtime problems; I may well have overlooked a test failure and presumed `agda` was back to its old tricks. Lesson learnt.

**Comment by mietek** [comment]
No worries. Feel free to ping me about any future issues with this or other Haskell-related formulae.

**Comment by dunn** [comment]
Merged in 2aff8f49bf2a43d01e05b3e1c9499c1ecde26615, thanks again!

**Pull request closed without merging**
