### PR TITLE
style-check: test added

### PR DESCRIPTION
**Pull request by bfontaine**

### CODE REVIEW

**Comment by vszakats** [comment]
https can be enabled for both `homepage` and `url`, thanks.

**Comment by bfontaine** [comment]
Fixed. Do you test these by hand, or do you have a script?

**Comment by vszakats** [comment]
By hand, no script yet. `url` updates could be automatized easily for the most part - maybe I'll do it, but it won't be in Ruby for the first round.

**Comment by vszakats** [comment]
A quick attempt in shell script:
```bash
#!/bin/sh

url_is_https_available() {

   # TODO: handle mirror selection URLs (which are in fact pages)
   # TODO: try well-known alternate URLs (S3, Apache)

   local tmpf1 tmpf2 size1 size2
   local https canupgrade

   type=$1
   url=$2

   case "${url}" in
      http://*)

         tmpf1="$(mktemp)" || exit 1
         tmpf2="$(mktemp)" || exit 1

         https="$(printf '%s' "${url}" | sed -re 's|^http://|https://|g')"
         canupgrade=0

         if curl -f -L --connect-timeout 2 "${url}" -o "${tmpf1}" > /dev/null 2>&1 ; then
            if curl -f -L --connect-timeout 2 "${https}" -o "${tmpf2}" > /dev/null 2>&1 ; then
               if [ "${type}" = 'homepage' ] ; then
                  size1=$(wc -c < "${tmpf1}")
                  size2=$(wc -c < "${tmpf2}")
                  percent=$(printf '%i %i' "${size1}" "${size2}" | awk '{ print 100*$1/$2 }')
                  if [ "${percent}" -ge 90 -a "${percent}" -le 110 ] ; then
                     canupgrade=1
                  fi
               else
                  if diff -s --binary --speed-large-files "${tmpf1}" "${tmpf2}" > /dev/null 2>&1 ; then
                     canupgrade=1
                  fi
               fi
            fi
         fi

         rm -f "${tmpf1}"
         rm -f "${tmpf2}"

         if [ "${canupgrade}" = 1 ] ; then
            if [ "${type}" = 'homepage' ] ; then
               echo "You can probably upgrade this ${type} URL to https (double-check manually):"
            else
               echo "You can upgrade this ${type} URL to https:"
            fi
            echo "${https}"
         else
            echo "Couldn't find a better alternative for this ${type} URL:"
            echo "${url}"
         fi
         echo
         ;;

      ftp://*)

         echo "Try using an https or http URL. FTP protocol doesn\'t play well"
         echo 'with firewalls/proxies/certain browsers and it lacks security.'
         echo
         ;;
   esac
}

# success
url_is_https_available 'download' 'http://archive.apache.org/dist/maven/maven-3/3.2.5/binaries/apache-maven-3.2.5-bin.tar.gz'
# failure
url_is_https_available 'download' 'http://downloads.webmproject.org/releases/webp/libwebp-0.4.3.tar.gz'
# success
url_is_https_available 'homepage' 'http://www.apache.org/'
```

**Comment by bfontaine** [comment]
Why do you write `[ "${percent}" -ge 90 -a "${percent}" -le 110 ]`? Isn’t the homepage supposed to be the same on `http` and `https`?

**Comment by vszakats** [comment]
The idea was to cover dynamically generated pages.
I'll extend the script to check for complete match and display the hint accordingly.

**Comment by vszakats** [comment]
Update done, also fixed some OS X compatibility issues:
https://gist.github.com/vszakats/663dc8ccf1d49b903f8e

**Pull request closed without merging**
