### PR TITLE
jenkins 1.623

### PR DESCRIPTION
**Pull request by kassi**

### CODE REVIEW

**Comment by dunn** [comment]
Is it possible to add a test in order to check basic functionality?

**Comment by DomT4** [comment]
The only thing that'd really be feasible is:

```ruby
test do
  assert_match /#{version}/, shell_output("#{bin}/jenkins --version")
end
```

But if the machine hadn't yet had Java invoked that day, it can take a little while to get the output. Anything else would need a running server AFAIK.

**Comment by mikemcquaid** [comment]
> But if the machine hadn't yet had Java invoked that day, it can take a little while to get the output. Anything else would need a running server AFAIK.

That seems fine for now :+1:

**Comment by DomT4** [comment]
Added the test in a new commit after verifying locally.

Merged in https://github.com/Homebrew/homebrew/commit/604e70e7fb21bb52e230b61667b74fc8b46e1352. Thank you for your contribution to Homebrew, we appreciate it! :smiley_cat:.

**Pull request closed without merging**
