### PR TITLE
ffmpeg: HEAD use https mirror

### PR DESCRIPTION
**Pull request by rdp**
This makes it possible to clone when behind proxies

### CODE REVIEW

**Comment by vszakats** [comment]
Just picking nits, could you update this http link to https (it's in a comment):
http://trac.macports.org/ticket/20938#comment:22

**Comment by vszakats** [comment]
This PR will need to be rebased, and after rebase there'll be another potential update opportunity; the patch URL can be changed to this:
```ruby
url "http://git.videolan.org/?p=ffmpeg.git;a=commitdiff_plain;h=83808ee7e9e89b0c83d5ecd94b35952c44716b68"
```
->
```ruby
url "https://github.com/FFmpeg/FFmpeg/commit/83808ee7e9e89b0c83d5ecd94b35952c44716b68.patch"
```

**Comment by tdsmith** [comment]
Please use `.diff` for patches from Github; the `.patch` includes the git version, which can change.

**Comment by vszakats** [comment]
Noted and updated to `.diff`

**Comment by jacknagel** [comment]
looks like this PR is now outdated.

**Comment by rdp** [comment]
works well now, thanks!

**Pull request closed without merging**
