### PR TITLE
tap_utils added

### PR DESCRIPTION
**Pull request by bfontaine**
The goal here is to move common tap functions out of `cmd/`.

cc @xu-cheng @mikemcquaid

### CODE REVIEW

**Comment by bfontaine** [comment]
I wonder if we should move `tap_args` on `ARGV`.

**Comment by xu-cheng** [comment]
I think we can(and maybe should) keep `install_tap` as it is. It is only used to keep backwards compatibility for external command. 

As for other two methods, we can make them class method of `Tap`.

**Comment by bfontaine** [comment]
@xu-cheng You’re right; I’ll keep it there.

**Comment by xu-cheng** [comment]
How about adding the remaining methods into `Tap` class or at least in `tap.rb`.  Maybe I'm too picky, but `require "tap"` seems to be better than `require "tap_utils"`

**Comment by bfontaine** [comment]
@xu-cheng Yes I’d be happy if we could fit these methods elsewhere instead of creating a new file.

**Comment by bfontaine** [comment]
I’m closing this for now and will reopen another PR with clean changes that take into account the recent tap changes.

**Pull request closed without merging**
