### PR TITLE
fribidi 0.19.7

### PR DESCRIPTION
**Pull request by Nyx0uf**

### CODE REVIEW

**Comment by dunn** [comment]
Any chance of adding a test, while you're at it?  Just something that checks basic functionality would be great!

**Comment by Nyx0uf** [comment]
I don't know what to test ?

I made this PR because fribidi 0.19.7 will probably be necessary for the next version of libass

**Comment by DomT4** [comment]
Per upstream's test files,

```ruby
test do
  (testpath/"test.input").write <<-EOS.undent
    a _lsimple _RteST_o th_oat
  EOS

  assert_match /a simple TSet that/, shell_output("#{bin}/fribidi --charset=CapRTL --test test.input")
end
```

Should work.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/40568815a009469bfebb17e98678009fac62cda4. Thank you for your contribution to Homebrew, we appreciate it! :smiley_cat:

**Pull request closed without merging**
