### PR TITLE
stunnel 5.23

### LINKED ISSUE #43628: stunnel 5.22 not found
stunnel 5.22 not found,now is 5.23.

### PR DESCRIPTION
**Pull request by DomT4**
Closes #43628.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
:+1:

**Comment by DomT4** [comment]
Looks like they've broken the hack we've been using to generate `.pem` files. Doesn't work, even outside brew. Breaks at this point:

```
You are about to be asked to enter information that will be incorporated
into your certificate request.
What you are about to enter is what is called a Distinguished Name or a DN.
There are quite a few fields but you can leave some blank
For some fields there will be a default value,
If you enter '.', the field will be left blank.
-----
PL []:
```

I'll work around it.

**Comment by DomT4** [comment]
Made the cert generation programmatic.

**Comment by mikemcquaid** [comment]
:+1:

**Pull request closed without merging**
