### PR TITLE
dromeaudio 0.3.0 (import from head-only)

### PR DESCRIPTION
**Pull request by bfontaine**
See https://github.com/Homebrew/homebrew-head-only/pull/193

### CODE REVIEW

**Comment by bfontaine** [comment]
```
-- Installing: /usr/local/Cellar/cmake/3.4.0/share/cmake/Modules/FindDromeAudio.cmake
CMake Error at share/cmake_install.cmake:39 (file):
  file INSTALL cannot copy file
  "/tmp/dromeaudio20151119-84455-vo7cqk/DromeAudio-0.3.0/share/FindDromeAudio.cmake"
  to
  "/usr/local/Cellar/cmake/3.4.0/share/cmake/Modules/FindDromeAudio.cmake".
Call Stack (most recent call first):
  cmake_install.cmake:35 (include)
```

**Comment by mikemcquaid** [comment]
@bfontaine Yeh, it'll need fixed up to not try and install that into CMake's Cellar but instead under `HOMEBREW_PREFIX/share/cmake/Modules`

**Comment by bfontaine** [comment]
@mikemcquaid Installing in this location breaks the sandbox. Should I install under `prefix` then either `cp` or symlink the CMake file in `postinstall`?

With `--sandbox`:
```
CMake Error at share/cmake_install.cmake:39 (file):
  file INSTALL cannot copy file
  "/tmp/dromeaudio20151124-80542-1979tka/DromeAudio-0.3.0/share/FindDromeAudio.cmake"
  to "/usr/local/share/cmake/Modules/FindDromeAudio.cmake".
Call Stack (most recent call first):
  cmake_install.cmake:35 (include)
```

**Comment by mikemcquaid** [comment]
> @mikemcquaid Installing in this location breaks the sandbox. Should I install under prefix then either cp or symlink the CMake file in postinstall?

Sorry, yeh, maybe this should be installed inside the prefix/share/cmake/Modules and `brew link`d automatically?

**Comment by bfontaine** [comment]
I need to fix the test but otherwise it works :+1:

**Pull request closed without merging**
