### PR TITLE
Update flickcurl to 1.26

### PR DESCRIPTION
**Pull request by robertoaloi**

### CODE REVIEW

**Comment by mikemcquaid** [comment]
`brew test flickrcurl` is failing, can you take a look? http://bot.brew.sh/job/Homebrew%20Pull%20Requests/19622/version=yosemite/testReport/junit/brew-test-bot/yosemite/test_flickcurl/

**Comment by robertoaloi** [comment]
Not sure what the error is about. The command seems to be launched correctly and the program help is  displayed. Looks like a timeout. Could it be caused by the big chunk of text displayed by the program on launch?

**Comment by tdsmith** [comment]
If `echo $?` isn't `0` after running `flickcurl -h` locally, the test needs to be revised to account for the new behavior.

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! For future reference the preferred commit message format for simple version updates is `flickcurl 1.26`. I've fixed the test in f747122.

**Comment by robertoaloi** [comment]
Gotcha. I had a config file from the previous version, so didn't notice the failure locally.
Thanks for your help.

**Pull request closed without merging**
