### PR TITLE
latex2html: make tex optional

### PR DESCRIPTION
**Pull request by DomT4**
Re https://github.com/Homebrew/homebrew/pull/38855#issuecomment-94504628

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Thanks @DomT4!

**Comment by larseggert** [comment]
With this change, `latex2html` doesn't pick up `tex` and `latex` under `/Library/TeX/texbin/` anymore during the `configure` phase, which breaks it for me.

**Comment by DomT4** [comment]
Are you building `brew install latex2html --with-tex`?

**Comment by larseggert** [comment]
No

**Comment by DomT4** [comment]
Try that. You have to tell it to use Tex now. It builds fine and seems to run fine without it, which is why the dep was made optional.

**Comment by larseggert** [comment]
It doesn't run fine without it for me. But I will try the option.

**Comment by DomT4** [comment]
What are you trying to execute with it that's causing it to fail?

**Comment by larseggert** [comment]
I have texlive installed. I then installed latex2html, but without the `--with-tex` option, so it wasn't picked up during the build. I then try to run latex2html on a `.tex` document, and it fails.

**Comment by DomT4** [comment]
If someone wants to move it to `homebrew/tex` with the full dependency reinstated, I have no particular objection.

**Pull request closed without merging**
