### PR TITLE
pypy 2.6.0

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by tdsmith** [comment]
Thanks Alex!

**Comment by tdsmith** [comment]
Bummer: build timeout; raised the limit to 2 hours and kicked off a new build.

**Comment by alex** [comment]
thanks!

**Comment by tdsmith** [comment]
This package is broken in the way described under the "Packaging" section of http://pypy.org/download.html. We should start using package.py, I guess.

**Pull request closed without merging**
