### PR TITLE
boot2docker 1.5.0

### PR DESCRIPTION
**Pull request by oncletom**
refs #36718

I wonder if it is better to provide a git URL + tag or rather a solid tar.gz file URL + sha1sum?

### CODE REVIEW

**Comment by DaveBlooman** [comment]
:+1:

**Comment by acroca** [comment]
:+1:

**Comment by xu-cheng** [comment]
> I wonder if it is better to provide a git URL + tag or rather a solid tar.gz file URL + sha1sum?

Generally, `tar.gz` url + sha1sum is better. It's more security and easier to handle (in terms of download and cleanup). But there're some repos code which use git submodule. In such case, we should use git url . Github doesn't pack submodule into tarball.

**Comment by oncletom** [comment]
Thanks @xu-cheng, it is good to know :-)

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
