### PR TITLE
README: use long key ID instead of short key ID

### PR DESCRIPTION
**Pull request by viktorahlstrom**
Just decided to open a PR about this because it seems a bit better to use long instead of short key-id.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
CC @xu-cheng @DomT4 for thoughts

**Comment by DomT4** [comment]
I'd probably make it `0xE33A3D3CCE59E297`.

On the command-line you can use short key, long key, very long key, it doesn't care as long as you don't search for the email address.

The fun with website keyservers where most people will probably head for validation is that you usually can't search for keys with the short key string, `CE59E297` returns nothing, as does `E33A3D3CCE59E297`. Using the email address directly works fine.

If you want to search for the key using the key itself rather than the email address you have to go the whole `0xE33A3D3CCE59E297`, but just to be confusing, after you locate it and click through it only presents the very short key:

screen shot 2015-07-08 at 23 27 36

**Comment by mikemcquaid** [comment]
> I'd probably make it 0xE33A3D3CCE59E297.

:+1:

**Comment by viktorahlstrom** [comment]
@DomT4 Changed to `0xE33A3D3CCE59E297`.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/c1b48b5878f369426ae988d0d7aff6242190f896. Thank you for your contribution to Homebrew, we appreciate it! :smiley_cat:

**Pull request closed without merging**
