### PR TITLE
pdfgrep 1.4.1

### PR DESCRIPTION
**Pull request by nijikon**

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Install is failing: http://bot.brew.sh/job/Homebrew%20Pull%20Requests/32291/version=yosemite/testReport/junit/brew-test-bot/yosemite/install_pdfgrep/

**Comment by bfontaine** [comment]
Ping?

**Comment by bfontaine** [comment]
This PR needs to be rebased on top of `master`.

**Comment by DomT4** [comment]
Pretty much identical PR was merged at some point, so closing here. Thanks for the submission nonetheless! :smiley:

**Pull request closed without merging**
