### PR TITLE
keybase 1.0.14-1

### PR DESCRIPTION
**Pull request by yous**
### All Submissions:

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew/pulls) for the same update/change?

### CODE REVIEW

**Comment by DomT4** [comment]
Is this stable upstream @gabriel @patrickxb?

**Comment by gabriel** [comment]
1.0.14-0 and 1.0.14-1 are equivalent.... I think was incremented for linux

In the future, we'll be removing the prerelease (-) part of the version string

**Comment by gabriel** [comment]
@patrickxb are we in a good enough spot to bump and tag to 1.0.15 or should we wait?

**Comment by DomT4** [comment]
Another maintainer merged in https://github.com/Homebrew/homebrew/pull/50058. Please do shout if we shouldn't be using this tag yet and I'll revert it, but closing here.

**Comment by tdsmith** [comment]
Mea culpa; sorry for not noticing the older PR & discussion.

**Pull request closed without merging**
