### PR TITLE
imagemagick: fix perl/remove PerlMagick formula

### PR DESCRIPTION
**Pull request by DomT4**
Refs: #47838

Has been available as part of ImageMagick for a while, which is an option we support. The ImageMagick option was broken, but fixed in this PR.

Also PerlMagick is no longer released by itself, so this formula would never be updated again unless we switch to using the ImageMagick releases for only the Perl element, which is a bit pointless when there's already the option in the ImageMagick formula.

### CODE REVIEW

**Comment by dunn** [comment]
Add a line to `tap_migrations`?

**Comment by DomT4** [comment]
Wasn't really planning to migrate it, just purge it from the planet. We don't tend to migrate stuff we've "merged" into another formula. Happy to boneyard if it people want though.

**Comment by dunn** [comment]
Oh, right. Never mind me, then.

**Comment by DomT4** [comment]
Feel free to shout if you disagree. Hasn't really been considered an "official" policy, just the way things have happened so far :smile_cat:.

**Comment by mikemcquaid** [comment]
:+1:

**Pull request closed without merging**
