### PR TITLE
rename app-engine formulae

### PR DESCRIPTION
**Pull request by vladshablinsky**
Needs to be merged when the bug is fixed. https://github.com/Homebrew/homebrew/issues/42965

### CODE REVIEW

**Comment by xu-cheng** [comment]
:+1:

**Comment by mikemcquaid** [comment]
Can this be rebased on `master`? Thanks!

**Comment by vladshablinsky** [comment]
Done. `test do` block should be added for each formula in `brew audit --strict`

**Comment by mikemcquaid** [comment]
Thanks @vladshablinsky!

**Comment by xu-cheng** [comment]
@vladshablinsky This PR may break these formulae. I just found `name` variable is used in `install`. By changing the names, formulae's installation are changed in the process.

**Comment by vladshablinsky** [comment]
@xu-cheng I can change `name` to `oldname` in `install`. What should we do in  cases like this?

**Pull request closed without merging**
