### PR TITLE
gettext 0.19.5.1

### PR DESCRIPTION
**Pull request by nijikon**

### CODE REVIEW

**Comment by mikemcquaid** [comment]
This is an issue with the new bottling code. I'm working on a fix.

**Comment by nijikon** [comment]
Ok, thanks for the information.

**Comment by mikemcquaid** [comment]
Fixed in b8a48d3, restarting the build.

**Comment by mikemcquaid** [comment]
Fixing the test failure in #41932, merging as-is. Thanks @nijikon!

**Pull request closed without merging**
