### PR TITLE
libpng: add head

### PR DESCRIPTION
**Pull request by vszakats**

### CODE REVIEW

**Comment by mistydemeo** [comment]
I'd prefer to keep using the release tarballs so we don't need autotools to build the stable releases.

**Comment by vszakats** [comment]
Noted. The primary `ftp://` URL is scary looking; I thought it'd be safer to tap the original vanilla source, it'd also work from behind firewalls.

**Comment by mistydemeo** [comment]
The ftp URL should be temporary; this is only until they're able to start uploading to Sourceforge again.

**Comment by vszakats** [comment]
Sourceforge is no less scary :)

**Comment by mistydemeo** [comment]
They haven't started tampering with source tarballs, and we use Sourceforge in plenty of places. ;)

**Comment by vszakats** [comment]
I've modified the patch to add head with build dependencies moved there.

**Comment by mistydemeo** [comment]
Thanks!

**Comment by dunn** [comment]
Merged as a194f141e315f268abe427f10c81f451c731d26c, thanks!

**Pull request closed without merging**
