### PR TITLE
doctor: move code away from cmd/

### PR DESCRIPTION
**Pull request by bfontaine**
This is similar to the previous PR but for the `doctor` and `missing` commands. It moves everything from `cmd/doctor.rb` to `diagnostic.rb`, under `Homebrew::Diagnostic`; makes `inject_dump_stats` a `Checks` instance method; moves `cmd/missing.rb`’s `missing_deps` in the same `diagnostic.rb` file.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Makes sense to me but would like to see at least an integration test for these.

**Comment by DomT4** [comment]
Not intending this negatively, more a curiosity thing, but what do we gaining from moving significant code chunks from x to y?

**Comment by bfontaine** [comment]
@DomT4 the goal is to rewrite our commands handling with a formula-like DSL: one command = one class. Removing unrelated code in these files is a necessary step to avoid breaking stuff when we’ll move to the new model.

**Comment by UniqMartin** [comment]
It also helps with testability, if we move towards an architecture where there is a frontend for a command that deals with global state and parses the user's arguments, and then passes those in a structured form to a (private) API that performs the actual work.

**Comment by DomT4** [comment]
Thanks for the explanations :bow:

**Comment by bfontaine** [comment]
@mikemcquaid Yeah; I wrote an integration test for `brew missing` and will write `doctor` ones tonight.

**Comment by DomT4** [comment]
I've probably just caused you a merge conflict here, apologies! Should be a simple rebase, I didn't do anything too breaking.

**Comment by bfontaine** [comment]
@mikemcquaid If you’re :+1: I’ll merge this.

**Comment by mikemcquaid** [comment]
:+1:

**Pull request closed without merging**
