### PR TITLE
qt5: fix broken pkg-config files (again)

### PR DESCRIPTION
**Pull request by UniqMartin**
Reinstate the fix reverted in f00b3489d01e73b23379608b6ac6260912f54bc0 now that it has been submitted and merged upstream.

### CODE REVIEW

**Comment by DomT4** [comment]
:tada:. Thanks for chasing up on this Martin. Will be nice to have Qt5 mostly working again, bar the issues in #42217 & #42191 I believe (?).

**Comment by UniqMartin** [comment]
Glad to be able to contribute back a bit. My OS X command line experience would be a lot less enjoyable without Homebrew. Plus it's such a pleasure to work with all of you! :heart:

If I find the time, I'll have a look at #42217 and #42191. With some luck I'll be able to find a solution.

**Comment by DomT4** [comment]
I'll merge this in about 20 minutes. Just finishing off something else first.

**Comment by DomT4** [comment]
:boat:'ed in https://github.com/Homebrew/homebrew/commit/fdbb338f2274e093b96209e7ca3ff9bf5460714e. Thank you once more @UniqMartin. Apologies for the ~32 minutes; Had to also hunt down all the other issues this PR fixes.

**Comment by UniqMartin** [comment]
No need to apologize! The issue was there for weeks, so half an hour more or less shouldn't make a big difference. Thanks for always being helpful and responsive!

**Pull request closed without merging**
