### PR TITLE
offlineimap: rename from offline-imap

### PR DESCRIPTION
**Pull request by vladshablinsky**
Needs to be merged when the bug is fixed. https://github.com/Homebrew/homebrew/issues/42965

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Needs rebased on `master`

**Comment by xu-cheng** [comment]
I would like to avoid formula rename with only minor name style changing. So I'm kinda :-1: this PR.

**Comment by mikemcquaid** [comment]
FWIW the Debian name: https://packages.debian.org/stable/mail/offlineimap

**Comment by nijikon** [comment]
@mikemcquaid is this still the case? I can do it in the referenced PR.

**Comment by mikemcquaid** [comment]
@nijikon Yeh, let's rename, thanks :+1:

**Comment by UniqMartin** [comment]
Closing because the formula has been renamed in #47638.

**Pull request closed without merging**
