### PR TITLE
t1utils 1.39

### PR DESCRIPTION
**Pull request by DomT4**
Version bump, added head.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Test failing: http://bot.brew.sh/job/Homebrew%20Pull%20Requests/25006/version=yosemite/testReport/junit/brew-test-bot/yosemite/test_mftrace/

**Comment by DomT4** [comment]
Passes fine locally off a fresh build. Will try a revision bump.

**Comment by DomT4** [comment]
That made it happy. Green now.

**Comment by mikemcquaid** [comment]
Thanks @DomT4!

**Pull request closed without merging**
