### PR TITLE
README: add PGP key

### PR DESCRIPTION
**Pull request by xu-cheng**
cc @Homebrew/owners

### CODE REVIEW

**Comment by DomT4** [comment]
We should probably sign the key with our GPG keys as well for verification, and upload it to a public traditional keyserver. But it's good to :ship:

**Comment by xu-cheng** [comment]
:ship:ed. Also I have upload it to MIT PGP Server. As for signing the key , can you do this @DomT4? I'm not quite familiar on that.

**Comment by DomT4** [comment]
Essentially:

* `gpg2 --sign-key 0xE33A3D3CCE59E297`
* `gpg2 --send-key 0xE33A3D3CCE59E297`

Then give it about 5 minutes and do:

* `gpg2 --recv-keys 0xe33a3d3cce59e297`

And then `gpg2 --list-sigs 0xe33a3d3cce59e297` will confirm your signature underneath it. And then 20 minutes or so later once the Keyservers have bounced each other around a bit you can go to https://pgp.mit.edu/pks/lookup?op=vindex&search=0xE33A3D3CCE59E297 and your signature will appear there as well.

**Comment by xu-cheng** [comment]
Thanks @DomT4

**Pull request closed without merging**
