### PR TITLE
xaric: test added

### PR DESCRIPTION
**Pull request by bfontaine**

### CODE REVIEW

**Comment by xu-cheng** [comment]
[This](http://stackoverflow.com/questions/1401002/trick-an-application-into-thinking-its-stdin-is-interactive-not-a-pipe) should help to solve the test failure.

**Comment by bfontaine** [comment]
Thanks @xu-cheng, I’m trying the [`script -q`](http://stackoverflow.com/a/13587964/735926) trick.

**Comment by bfontaine** [comment]
It works :+1:

**Comment by DomT4** [comment]
If this was previously using the system OpenSSL, a revision would be good.

**Comment by mikemcquaid** [comment]
> If this was previously using the system OpenSSL, a revision would be good.

:+1: on this.

**Comment by bfontaine** [comment]
Just edited this PR. I’m in an internship since Monday so I don’t have as much time as I used to have during the day.

**Comment by mikemcquaid** [comment]
Thanks @bfontaine!

**Pull request closed without merging**
