### PR TITLE
Use https URLs

### PR DESCRIPTION
**Pull request by pdalpra**
This PR fixes some URLs to use HTTPS (more specifically, Formulae from W to Z :) )

### CODE REVIEW

**Comment by DomT4** [comment]
` xml-security-c ` needs an OpenSSL dependency and a revision bump. `whereami` is failing to build on Yosemite.

**Comment by jacknagel** [comment]
ping

**Comment by pdalpra** [comment]
Well, TBH, it's hardly related to the changes  of my PR...
But I can remove the changes on those two formulae if you'd like.

**Comment by DomT4** [comment]
Opened an issue upstream on `whereami` - https://github.com/victor/whereami/issues/15. Also opened #39245 to fix the SSL linkage on xml.

On this, it'd be nice if we can fix everything highlighted by ` brew audit --strict ` rather than just change one element, but that's Jack's call to make.

**Comment by pdalpra** [comment]
I removed `xml-security-c` and `whereami` from my PR, so that I doen't break anything if merged (tests are passing now).

@DomT4 : indeed. I was focused on HTTPS links issues as this quite easy to change and as it makes up most of the errors reported by `brew audit`, but a thorough clean up per formula is probably better.

**Pull request closed without merging**
