### PR TITLE
update ruby-build and rbenv URLs

### PR DESCRIPTION
**Pull request by kurotaky**
I updated homepage and download url for rbenv and ruby-build. 
rbenv and ruby-build are provided following URLs now.

* rbenv
 * https://github.com/rbenv/rbenv/
* ruby-build
 * https://github.com/rbenv/ruby-build

### CODE REVIEW

**Comment by DomT4** [comment]
Could you possibly make this one commit per formula changed? Thanks!

**Comment by kurotaky** [comment]
@DomT4 
I just rebased commits in order to divided each formula.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/6b379b5922e13cb235ebd4b3a9644a7db5d5acf2 & https://github.com/Homebrew/homebrew/commit/fb7fc1587d733748c7058946d1d38a2bf7edd495.

Thank you for your contributions to Homebrew @kurotaky; we appreciate them! :smiley_cat:

**Comment by kurotaky** [comment]
Thanks! :smile_cat:

**Pull request closed without merging**
