### PR TITLE
docker: fix --with-experimental (libtool dependency and optional hardware signing)

### PR DESCRIPTION
**Pull request by cyli**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew/pulls) for the same update/change?

Docker experimental supports hardware signing yubikey PKCS11 libraries.  Currently the formula is breaking if libtool is not installed:

```
$ brew install docker --with-experimental
==> Cloning https://github.com/docker/docker.git
Updating /Library/Caches/Homebrew/docker--git
==> Checking out tag v1.10.3
==> hack/make.sh dynbinary
Last 15 lines from /Users/yingli/Library/Logs/Homebrew/docker/01.make.sh:
# Try this instead: make all
#

date: illegal option -- -
usage: date [-jnu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
# WARNING! DOCKER_EXPERIMENTAL is set: building experimental features

---> Making bundle: dynbinary (in bundles/1.10.3/dynbinary)
Building: bundles/1.10.3/dynbinary/docker-1.10.3
# github.com/miekg/pkcs11
vendor/src/github.com/miekg/pkcs11/pkcs11.go:26:10: fatal error: 'ltdl.h' file not found
#include <ltdl.h>
         ^
1 error generated.

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
Fix docker-machine-driver-xhyve HEAD https://github.com/Homebrew/homebrew/pull/49467
```

This adds the libtool dependency if experimental is enabled or yubikey is enabled (since, if it ever moves out of experimental, it will be needed if yubikey support is desired).

This also adds a recommended dependency on the yubico-piv-tool formula, which installs the necessary yubikey libraries.

```
$ brew install docker --with-experimental
==> Installing dependencies for docker: libtool, yubico-piv-tool
==> Installing docker dependency: libtool
==> Downloading https://homebrew.bintray.com/bottles/libtool-2.4.6.el_capitan.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/libtool-2.4.6.el_capitan.bottle.tar.gz
==> Pouring libtool-2.4.6.el_capitan.bottle.tar.gz
==> Caveats
In order to prevent conflicts with Apple's own libtool we have prepended a "g"
so, you have instead: glibtool and glibtoolize.
==> Summary
🍺  /usr/local/Cellar/libtool/2.4.6: 69 files, 3.6M
==> Installing docker dependency: yubico-piv-tool
==> Downloading https://homebrew.bintray.com/bottles/yubico-piv-tool-1.2.2.el_capitan.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/yubico-piv-tool-1.2.2.el_capitan.bottle.tar.gz
==> Pouring yubico-piv-tool-1.2.2.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/yubico-piv-tool/1.2.2: 16 files, 368.7K
==> Installing docker
==> Cloning https://github.com/docker/docker.git
Updating /Library/Caches/Homebrew/docker--git
==> Checking out tag v1.10.3
==> hack/make.sh dynbinary
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completion has been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/docker/1.10.3: 10 files, 11.7M, built in 15 seconds
```

```
brew install docker --with-experimental --without-yubico-piv-tool
==> Installing dependencies for docker: libtool
==> Installing docker dependency: libtool
==> Downloading https://homebrew.bintray.com/bottles/libtool-2.4.6.el_capitan.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/libtool-2.4.6.el_capitan.bottle.tar.gz
==> Pouring libtool-2.4.6.el_capitan.bottle.tar.gz
==> Caveats
In order to prevent conflicts with Apple's own libtool we have prepended a "g"
so, you have instead: glibtool and glibtoolize.
==> Summary
🍺  /usr/local/Cellar/libtool/2.4.6: 69 files, 3.6M
==> Installing docker
==> Cloning https://github.com/docker/docker.git
Updating /Library/Caches/Homebrew/docker--git
==> Checking out tag v1.10.3
==> hack/make.sh dynbinary
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completion has been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/docker/1.10.3: 10 files, 11.7M, built in 15 seconds
```

### CODE REVIEW

**Comment by dunn** [comment]
What will happen if a user does `brew install --with-experimental --without-yubico-piv-tool`?

**Comment by cyli** [comment]
@dunn It installs libtool and docker only

**Comment by dunn** [comment]
I was wondering more why it's `:recommended` when built as experimental, and not simply required.

NB: options that only exist when other options are enabled, like `-without-yubico-piv-tool`, don't show up in `brew info`.

**Comment by cyli** [comment]
@dunn:  It's needed to do hardware signing with docker, but it's not required to run Docker.  wrt `-without-yubico-piv-tool`, would you suggest I add the manual option with a description?

**Comment by dunn** [comment]
Sorry for the delay.
> would you suggest I add the manual option with a description?

Adding options manually with the `option "with-foo"` DSL makes them unconditional which won't work here.  It's OK as-is, just be aware that most people won't realize it's possible to build without yubico-piv-tool.

**Comment by cyli** [comment]
@dunn That's probably fine, thanks!

**Comment by dunn** [comment]
OK, merged as a8713e1955823abed7d68e1f8e0e330e98a90afa. Thanks!

**Comment by cyli** [comment]
@dunn Thanks lots!

**Pull request closed without merging**
