### PR TITLE
rhino 1.7r5

### PR DESCRIPTION
**Pull request by mathiasbynens**

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Any chance of a wee `test do` block for this (if you're feeling really lovely)? Thanks!

**Comment by vszakats** [comment]
May I suggest updating `homepage` to https: `https://www.mozilla.org/rhino/`?

**Comment by mikemcquaid** [comment]
> May I suggest updating homepage to https: https://www.mozilla.org/rhino/ ?

:+1:

**Comment by mathiasbynens** [comment]
Thanks for the feedback! PR amended.

**Comment by vszakats** [comment]
Thanks.

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
