### PR TITLE
Update perl-build to 1.12

### PR DESCRIPTION
**Pull request by moltar**

### CODE REVIEW

**Comment by ploxiln** [comment]
Not sure if anyone noticed: this PR's automated build is holding up all the others, for 3 hours now, even though none of the configurations are still actually running.

http://bot.brew.sh/job/Homebrew%20Pull%20Requests/33214/

**Comment by moltar** [comment]
Did I break anything?

**Comment by ploxiln** [comment]
seems unlikely it's your fault

**Comment by dunn** [comment]
Our bots have been backed up and a little finicky recently; we'll re-queue this in a bit.

**Comment by DomT4** [comment]
You need to update the checksum here as well.

One of our CI machines has gone on strike, which is currently blocking builds. We're hoping to restore function over the next 4/5 hours and at that point things will move again.

**Comment by DomT4** [comment]
@BrewTestBot test this please

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/5d41d3326bcfc52582f6c92e4dd3f49beb85939a. Thank you for your patience & your contribution to Homebrew @moltar.

**Pull request closed without merging**
