### PR TITLE
bacula 7.2.0

### PR DESCRIPTION
**Pull request by nijikon**
To what we want to change ```/opt/bacula```?

### CODE REVIEW

**Comment by mikemcquaid** [comment]
> To what we want to change /opt/bacula?

Can you provide more context here?

**Comment by nijikon** [comment]
./autoconf/mkinstalldirs /opt/bacula/log
mkdir /opt/bacula
mkdir: /opt/bacula: Operation not permitted
mkdir /opt/bacula/log
mkdir: /opt/bacula: No such file or directory
make: *** [installdirs] Error 1

**Comment by DomT4** [comment]
`var/"bacula"` maybe. The inclusion of `log` makes me think it's that sort of thing.

**Comment by DomT4** [comment]
Closing as dead. Please feel free to resubmit as fresh with the comments above addressed, if you'd like to. Thanks for the submission to Homebrew!

**Pull request closed without merging**
