### PR TITLE
pip 8.0.0: for various packages

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by DomT4** [comment]
Punted this off the build queue because combined this PR is going to take at least a couple of hours, possibly longer. CC @tdsmith for thoughts on whether we want to do this, etc.

**Comment by alex** [comment]
:+1:

**Comment by tdsmith** [comment]
Thanks, Alex! Per Donald I'll wait for 8.0.1.

I'm surprised all these things use pip! That's probably wrong.

I'm also gonna pull pip and setuptools out of the damn pypy bottles so we can bump pip without retranslating; that was my bad idea.

**Comment by DomT4** [comment]
Closing per Tim's comment then. Nonetheless, thank you for the submission @alex :heart:

**Comment by rakkesh** [comment]
FWIW, `pip` `8.0.2` is now available - https://pypi.python.org/pypi/pip

**Pull request closed without merging**
