### PR TITLE
antiword: audit fixes

### PR DESCRIPTION
**Pull request by nijikon**

### CODE REVIEW

**Comment by nijikon** [comment]
@DomT4 is this better?

**Comment by DomT4** [comment]
This is somewhat complicated. The usage of `HOMEBREW_PREFIX` makes me suspect those mapping files are intended to persist across installations, but there's no logic to facilitate that and that symlink is indeed pointing to what would be `pkgshare`.

**Comment by apjanke** [comment]
Antiword's own Makefile doesn't handle this gracefully either: `make global_uninstall` will delete `*.txt` in that resources dir, which would include any user-installed mappings, and attempt to unconditionally remove the directory.

```
global_uninstall:
...
	cd $(DESTDIR)$(GLOBAL_RESOURCES_DIR); rm -f *.txt fontnames
	-rmdir $(DESTDIR)$(GLOBAL_RESOURCES_DIR)
```

Then again, maybe this doesn't matter, because nobody uses `make uninstall`, and they rely on their package managers instead.

**Comment by DomT4** [comment]
Hmm. Maybe it should just be `opt_pkgshare` then if upstream's logic would, in an outside-brew situation, wipe the directory clean regardless.

**Comment by apjanke** [comment]
Yeah, I'd think so too. But unless we alter the formula to provide persistence for it, I'm thinking we should just remove its mention from the caveats because users shouldn't install their custom files there anyway, due to the wiping behavior.

Providing persistence would probably be pretty easy - special-case the `/usr/local/share/antiword` directory to be a `:mkpath` instead of a symlink, so the individual files inside it get symlinked instead. But I don't know if Homebrew wants to do that for every customizable formula.

**Comment by DomT4** [comment]
> I'm thinking we should just remove its mention from the caveats because users shouldn't install their custom files there anyway, due to the wiping behavior.

Since it also recommends ` ~/.antiword` this seems ideal to me. I personally don't really want to get into the cycle where we have a giant list of things that need custom `:mkpath` logic, especially where there's a ready-made alternative directory.

**Comment by apjanke** [comment]
Sounds good to me.

**Pull request closed without merging**
