### PR TITLE
crystax-ndk 10.2.1

### PR DESCRIPTION
**Pull request by crystax**
Version bump

### CODE REVIEW

**Comment by crystax** [comment]
As I see, automatic tests are passed, except of "mavericks", where tests failed due to "no space left on device" error, which obviously has nothing to correctness of my pull request. Is it possible to re-trigger it again to get tests passed?

**Comment by DomT4** [comment]
Only the bottle untar failed on this (On one machine), and since we don't add a bottle for this formula, as far as I'm concerned it can just be merged. I'll let it sit till this afternoon to see if anyone objects, but otherwise I'll merge it at that point.

**Comment by crystax** [comment]
Thank you!

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/90943ca422dcfec0e6898776f2a7feda4176144a. Thank you for your contribution to Homebrew, we appreciate it! :smiley_cat:

**Pull request closed without merging**
