### PR TITLE
nginx devel 1.9.4

### PR DESCRIPTION
**Pull request by guoxiao**

### CODE REVIEW

**Comment by DomT4** [comment]
```
==> /usr/local/Cellar/nginx/1.8.0/bin/nginx -t
nginx: [alert] could not open error log file: open() "/usr/local/var/log/nginx/error.log" failed (1: Operation not permitted)
nginx: the configuration file /usr/local/etc/nginx/nginx.conf syntax is ok
2015/08/31 10:30:02 [emerg] 2751#0: open() "/usr/local/var/run/nginx.pid" failed (1: Operation not permitted)
nginx: configuration file /usr/local/etc/nginx/nginx.conf test failed
Error: nginx: failed
```

It's trying to write to `/usr/local/var/` during the test, which we no longer permit. Can we feed `nginx` custom paths temporarily for the PID location?

**Comment by DomT4** [comment]
@BrewTestBot test this please

**Comment by dunn** [comment]
Similar failure:
```
==> /usr/local/Cellar/nginx/1.8.0/bin/nginx -t -c /private/tmp/nginx20150903-70190-ogfuwt/nginx.conf
nginx: [alert] could not open error log file: open() "/usr/local/var/log/nginx/error.log" failed (1: Operation not permitted)
nginx: the configuration file /private/tmp/nginx20150903-70190-ogfuwt/nginx.conf syntax is ok
2015/09/03 04:08:04 [emerg] 70203#0: mkdir() "/usr/local/var/run/nginx/client_body_temp" failed (1: Operation not permitted)

**Comment by guoxiao** [comment]
It seems nginx `error_log` path is specified at compile time. 
Adding another `error_log` in config file only adds another log path, and nginx still tries to write to the original path.

**Comment by xu-cheng** [comment]
Can you rebase this? I have fixed sandbox problem.

**Comment by DomT4** [comment]
You've merged some unrelated changes in here which are breaking the build currently.

**Comment by guoxiao** [comment]
@DomT4 Sorry. I've removed them.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/35b2e54a52465fad4f4d02ff31a796e186da5507. Thank you for sticking with this whilst we sorted out the sandbox side of things @guoxiao, Appreciated.

**Pull request closed without merging**
