### PR TITLE
kettle 6.0.1.0-386

### PR DESCRIPTION
**Pull request by joshua-rutherford**

### CODE REVIEW

**Comment by joshua-rutherford** [comment]
Closing and reopening to restart build process.  Downloads from sourceforge mirrors were extremely slow yesterday so one of the builds timed out.

**Comment by DomT4** [comment]
Can we possibly change the `<string>#{bin}/pdicarte</string>` line in the `plist` to read `opt_bin` instead of `bin`? Means people don't actually have to copy over the new `plist` every update for it to keep working.

**Comment by joshua-rutherford** [comment]
@DomT4, I've made that change but kept it as a separate commit since it's not simply a version bump.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/673541b6ee8d1094270fa80f9ab4b76a68a636e0 & https://github.com/Homebrew/homebrew/commit/bcbdb7d3c4b1783a78d6cdc75efdaa0d62a1f051.

Thank you for your contributions to Homebrew @joshua-rutherford! :santa:

**Pull request closed without merging**
