### PR TITLE
iojs 2.0.1

### PR DESCRIPTION
**Pull request by DomT4**

### CODE REVIEW

**Comment by denji** [comment]
@DomT4 `npm` not ready iojs?

**Comment by bcomnes** [comment]
@denji huh?

**Comment by denji** [comment]
@bcomnes https://github.com/DomT4/homebrew/blob/4ca5f1613507be85d0bee4ccd1dafb8214025e28/Library/Formula/iojs.rb#L30-L35

**Comment by bcomnes** [comment]
This PR looks good to me for now.  I can update https://github.com/Homebrew/homebrew/pull/36369 to see if it passes the test without patching.

**Comment by DomT4** [comment]
I presume they would have made a fairly huge announcement if `npm` finally worked right out of the box in all aspects, but I didn't see anything like that? #36369 is the place to track `npm` in `iojs` progress.

**Comment by bcomnes** [comment]
Thats what I was assuming too.  No matter, updating https://github.com/Homebrew/homebrew/pull/36369 now as well.

**Comment by DomT4** [comment]
Thanks for sticking with this Bret.

**Comment by denji** [comment]
Don't see the benefit from using iojs without npm, and at the moment am using the official node.rb.

**Comment by DomT4** [comment]
It's under heavy discussion, and will happen eventually. For now, I'm using `nvm` personally, but not everyone needs the whole experience.

**Comment by bcomnes** [comment]
I unlink/link between using the node and (`--force` linked) iojs formula in homebrew, and configured `npm` to use pangyp in `~/.npmrc` currently.  A little clumsy, but a clean minimal, version manager free solution right now.

**Comment by shinnn** [comment]
[io.js v2.0.1 has been released](https://github.com/iojs/io.js/blob/8bf878d6e5ac0faa3871cddd5dcc423ae4d3d45a/CHANGELOG.md#2015-05-07-version-201-rvagg).

**Comment by DomT4** [comment]
@shinnn Thanks, have bumped this PR.

**Comment by xu-cheng** [comment]
Thanks @DomT4

**Pull request closed without merging**
