### PR TITLE
gitfs: migrate to homebrew/devel-only

### PR DESCRIPTION
**Pull request by DomT4**
Upstream have labelled this pre-release, and it’s blocking #36081 or #35954 from going in. Propose we move it to devel-only and vendor the older libgit2 in.

### CODE REVIEW

**Comment by DomT4** [comment]
Ugh:

```
    ENV.prepend "CFLAGS", "-I#{libexec}/include"
    ENV.prepend "LDFLAGS", "-L#{libexec}/lib"
```

```
d.so, 2): Library not loaded: libgit2.21.dylib
  Referenced from: /private/tmp/gitfs--pygit2-cV3ktB/pygit2-0.21.4/cffi-0.8.6-py2.7-macosx-10.10-intel.egg/_cffi_backend.so
  Reason: image not found
/usr/local/Library/Homebrew/debrew.rb:11:in `raise'
BuildError: Failed executing: python -c import\ setuptools,\ tokenize
__file__\ =\ 'setup.py'
exec(compile(getattr(tokenize,\ 'open',\ open)(__file__).read()
\ \ .replace('\r\n',\ '\n'),\ __file__,\ 'exec'))
 --no-user-cfg install --prefix=/usr/local/Cellar/gitfs/0.2.5/libexec/vendor --single-version-externally-managed --record=installed.txt
```

It's there, but it can't find it. So I guess we're back to this blocking #36081 or #35954 from going in. Kinda deeply annoying when one package stops two being updated.

**Comment by DomT4** [comment]
Reported upstream: https://github.com/PressLabs/gitfs/issues/175

**Comment by dragostis** [comment]
How about using libgit2 v0.21 in the gitfs Homebrew script? The issue is that older versions of pygit2 won't be compatible with newer versions of libgit2.

Another solution would be to upgrade the pygit2 version as well, but I don't see this as a long term solution unless it gets automated.

**Comment by mikemcquaid** [comment]
> How about using libgit2 v0.21 in the gitfs Homebrew script?

That would work.

**Comment by DomT4** [comment]
Sadly it didn't. The [comment here](https://github.com/Homebrew/homebrew/pull/36082#issuecomment-70735729) was what happened when I tried to vendor the older libgit2 into gitfs/libexec.

**Comment by DomT4** [comment]
> Another solution would be to upgrade the pygit2 version as well, but I don't see this as a long term solution unless it gets automated.

I'm going for this solution. It works. I'll add a note to the formula on the absolute necessity to update it, and I'll try to improve the test so the brew-bot can detect when libgit2 breaks it.

@mikemcquaid Any feelings on keeping this here or moving to to devel-only? I'm indifferent, given it's already in the core and no longer blocking.

**Comment by DomT4** [comment]
Ugh. Ignore previous post. It builds fine, but then...

```
Traceback (most recent call last):
  File "/usr/local/Cellar/gitfs/0.2.5/libexec/bin/gitfs", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2797, in <module>
    parse_requirements(__requires__), Environment()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 576, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: pygit2==0.21.4
```

:angry: Annoying.

**Comment by DomT4** [comment]
Based on upstream's response to the last ` pygit2 ` update request, I'm just going to try patching the requirement number.

**Comment by DomT4** [comment]
Alright. Fixed. Closing this in favour of a new clean PR.

**Comment by DomT4** [comment]
Merged the changes into #36081.

**Pull request closed without merging**
