### PR TITLE
XQuartz 2.7.8

### PR DESCRIPTION
**Pull request by UniqMartin**
Available since October 17, first to officially support El Capitan.

### CODE REVIEW

**Comment by DomT4** [comment]
```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Your XQuartz (2.7.7) is outdated
Please install XQuartz 2.7.8:
  https://xquartz.macosforge.org
```

:smile_cat:. We'll have to go fix that.

**Comment by UniqMartin** [comment]
Oh, I see. I didn't realize it requires some action on the test bot …

**Comment by mikemcquaid** [comment]
FWIW now may be a good time to point out: I'm not really sure we need to tell users they always have to have the latest XQuartz installed?

**Comment by mikemcquaid** [comment]
(we should update this anyway, though)

**Comment by DomT4** [comment]
> Oh, I see. I didn't realize it requires some action on the test bot …

It runs as a standard `doctor` check, so since the CI hasn't been updated, it'd fail all the builds. Same with the Xcode changes.

>  I'm not really sure we need to tell users they always have to have the latest XQuartz installed?

On compatibility probably not. I'd argue (Well I won't argue, too tired) there's security validity to reminding users they've an outdated X11 lying around, though, given they may well have installed such a package to validate our dependency requirements at some point.

**Comment by UniqMartin** [comment]
> On compatibility probably not. I'd argue (Well I won't argue, too tired) there's security validity to reminding users they've an outdated X11 lying around, though, given they may well have installed such a package to validate our dependency requirements at some point.

I second that.

Hopefully, most users nowadays don't have it installed at all. Judging from my personal use and the improved situation with Gtk+ it's rarely needed. Sadly, major software like Inkscape (at least the official OS&nbsp;X download) still depend on it.

**Comment by CamJN** [comment]
Probably want to wait until xquartz.macosforge.org is back up before merging.

**Comment by DomT4** [comment]
There's another hold up here as well, so it won't be merged till both are resolved, fret not.

**Comment by DomT4** [comment]
@BrewTestBot test this please

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/25b5001b44923eb74bc8b6800f680fde984383a1. Thank you @UniqMartin! :smiley:

**Pull request closed without merging**
