### PR TITLE
Master

### PR DESCRIPTION
**Pull request by mvabl-steve**
The location of the source file changed. I have updated in in the class
for Libspatiale

### CODE REVIEW

**Comment by dunn** [comment]
Looks like you pulled in some other changes by accident.  If you run `git rebase origin/master`, that should clean things up, then you can `git push -f` to update this PR.

**Comment by mvabl-steve** [comment]
OK, done. Bouncing back-and-forth btw Terminal & GitHubDesktop; not sure if that's going to screw things up. Like I said, not a developer! :)

**Comment by xu-cheng** [comment]
Please rebase the commits. We recommend you to use another branch to submit PR. [Here](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) is the document if you need help. Thanks.

**Comment by mvabl-steve** [comment]
OK, I am out of my depth here. Here's what I know: the formula libspatialite, line 4, has
```
url "https://www.gaia-gis.it/gaia-sins/libspatialite-4.3.0.tar.gz"
```

That just needs to be changed to

```
url "https://www.gaia-gis.it/gaia-sins/libspatialite-sources/libspatialite-4.3.0.tar.gz"

```
Unless someone else has already done it.

Sorry, I just don't know what I'm doing.

**Comment by DomT4** [comment]
Fixed in 4b9da3441db9faaec99865bed0c3214c3a768bac. Thanks for the submission here, we appreciate the willingness to contribute :heart:

**Comment by mvabl-steve** [comment]
Wow, you guys are WAY more friendly than the guys over at StackOverflow!! :)

**Pull request closed without merging**
