### PR TITLE
kubernetes-cli: install bash completion

### PR DESCRIPTION
**Pull request by oyvindio**
The Kubernetes distribution provides bash completion for kubectl
already; we just need to install it.

### CODE REVIEW

**Comment by DomT4** [comment]
```
        Error: 1 problem in 1 formula
kubernetes-cli:
 * 33: Trailing whitespace was found

```

**Comment by oyvindio** [comment]
That was me doing a whitespace change to trigger a new ci build to see if
it would go green, as the build error for the previous commit looked
unrelated to my change. I'll delete the last commit and see if I can get it
to build ok afterwards.

**Comment by oyvindio** [comment]
I think the build of cc94340 fails because of a corner case bug in `brew bottle`:

`brew bottle` does the equivalent of a `stat(2)` on every file in the source tarball to get the most recent mtime of the source. One of the dependencies Kubernetes pulls in contains a deliberately broken symlink as test data. When we stat that file, we get an error because stat tries to follow the symlink and fails, causing an exception which makes `brew bottle` fail.

I patched brew bottle to only consider files where stat succeeds when determining the most recent mtime, and that seems to work.

**Comment by mikemcquaid** [comment]
Wow, great work @oyvindio, that was on my list of things to do today so much :heart: for fixing it and for this pull request in general. Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
