### PR TITLE
mimms: use https urls

### PR DESCRIPTION
**Pull request by vszakats**

### CODE REVIEW

**Comment by vszakats** [comment]
Fails on El Capitan. Unrelated to this update.

**Comment by DomT4** [comment]
Any idea what's going on here @tdsmith?

```
==> /usr/local/Cellar/mimms/3.2.1/bin/mimms --version
Traceback (most recent call last):
  File "/usr/local/Cellar/mimms/3.2.1/libexec/bin/mimms", line 21, in <module>
    from libmimms.core import run
  File "/usr/local/lib/python2.7/site-packages/libmimms/core.py", line 31, in <module>
    from . import libmms
  File "/usr/local/lib/python2.7/site-packages/libmimms/libmms.py", line 26, in <module>
    libmms = cdll.LoadLibrary("libmms.0.dylib")
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(libmms.0.dylib, 6): image not found
==> Sandbox log
Oct  7 03:08:18 sandboxd[65590]: Python(24243) deny file-write-create /usr/local/lib/python2.7/site-packages/libmimms/__init__.pyc
Oct  7 03:08:18 sandboxd[65590]: Python(24243) deny file-write-create /usr/local/lib/python2.7/site-packages/libmimms/core.pyc
Oct  7 03:08:18 sandboxd[65590]: Python(24243) deny file-write-create /usr/local/lib/python2.7/site-packages/libmimms/libmms.pyc
```

Not sure why that wouldn't be happening on <El Cap if it's just a sandbox issue :confused:

**Comment by tdsmith** [comment]
Not a sandbox error; not sure what's up.

**Comment by vszakats** [comment]
FWIW, it installs without any problem on a live El Capitan system:
```
$ brew install mimms
==> Downloading https://launchpad.net/mimms/trunk/3.2.1/+download/mimms-3.2.1.tar.bz2
==> Downloading from https://launchpadlibrarian.net/14464298/mimms-3.2.1.tar.bz2
######################################################################## 100.0%
==> Patching
patching file libmimms/libmms.py
==> python setup.py install --prefix=/usr/local/Cellar/mimms/3.2.1
🍺  /usr/local/Cellar/mimms/3.2.1: 15 files, 100K, built in 4 seconds
```

**Comment by vszakats** [comment]
Is there any chance to get this merged? The bot error is unrelated to this PR and install works well on real-life El Capitan, so it may be best to handle the bot failure as a separate Issue.

**Comment by DomT4** [comment]
Install wasn't the issue; the `brew test --verbose` stage is what flagged the failure, and I can replicate that locally.

**Comment by vszakats** [comment]
Ah okay, I can also confirm it by just trying to run `mimms`. Though my question still applies. I'd rather close this than holding off for an unrelated fix. I can open an Issue about it, if that helps merging this one.

Not being a Python expert, what I can see that `libmms.0.dylib` is not found by `dlopen()` even though it's present in `/usr/local/lib` (as a valid symlink).

**Comment by vszakats** [comment]
Closing this one after having been implemented in a separate commit: https://github.com/Homebrew/homebrew/commit/aff56d38dd85f5426062a8f40de6a1badddad1be

**Comment by bfontaine** [comment]
Sorry @vszakats I’m running a script to find HTTPS-able URLs and didn’t see this PR before committing.

**Comment by vszakats** [comment]
No worries at all @bfontaine! This one was in limbo since a while, with not much hope to be merged. I'm happy to see it committed either way :)

**Pull request closed without merging**
