### PR TITLE
Build `ttfautohintGUI` also.

### PR DESCRIPTION
**Pull request by lemzwerg**
Second try.

### CODE REVIEW

**Comment by lemzwerg** [comment]
Stupid me.  What a luck that a but is handling this.

**Comment by mikemcquaid** [comment]
Please don't keep recreating PRs. You can push more commits to your branch and the PR will be updated.

**Comment by lemzwerg** [comment]
OK.  I tried, but somehow the `git rebase --interactive origin/master` stage failed for me (certainly due to my lack of experience with the github flow), so I've chosen a route that works for me. Sorry.

Just curious: Why do you have this rule?  As long as there is no real feedback, it shouldn't make a difference...

**Comment by mikemcquaid** [comment]
Because it's noisy; all the maintainers get emailed every time you create a new pull request where you could instead just watch the result and push new commits until it passes.

**Comment by lemzwerg** [comment]
Thanks for the information.

**Pull request closed without merging**
