### PR TITLE
mahout 0.10.0

### PR DESCRIPTION
**Pull request by guoxiao**
TODO: add test block

### CODE REVIEW

**Comment by mikemcquaid** [comment]
would be nice to use a wrapper script to set `JAVA_HOME`

**Comment by asparagui** [comment]
See also #38948.

**Comment by guoxiao** [comment]
I noticed something in https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Acceptable-Formulae.md#acceptable-formulae

>We don’t like binary formulae
>Our policy is that formulae in the core repository (Homebrew/homebrew) must be built from source. Binary-only formulae should go to Homebrew/homebrew-binary.

So in the pull-request I changed the formulae to build from source. But in #38948 it is still a binary formulae. Should my PR be better according to the guideline?

**Comment by mikemcquaid** [comment]
@guoxiao We should maybe notify that that's OK for Java formulae because they work cross-platform from binaries.

**Comment by guoxiao** [comment]
@mikemcquaid agree

**Comment by mikemcquaid** [comment]
@guoxiao Done, thanks!

**Pull request closed without merging**
