### PR TITLE
llvm: Add option to build OCaml bindings

### PR DESCRIPTION
**Pull request by aw1621107**
Also has a minor organizational change, which I can change if it's a problem.

This adds a check for the required OCaml packages and works around a CMake setup bug.

### CODE REVIEW

**Comment by apjanke** [comment]
The CI failures are timeouts, even though Jenkins ran to success in less time than that. Possibly a busy day on the build system? If you squash your commits, which should probably be done anyway, it'll trigger another attempt at the build.

**Comment by aw1621107** [comment]
Maybe? I think the CI builds timed out the past times I submitted LLVM changes, so it could be the formula too...

I'll hold off on squashing until I get a response to the patch I submitted upstream. If it's applied I'll need another commit to get rid of a `make` step

**Comment by aw1621107** [comment]
Oh, quick question -- looks like superenv isn't replacing my PATH the normal way? I didn't have to add opam to my PATH to get CMake to detect it or the other OCaml stuff...

**Comment by aw1621107** [comment]
Yeah, actually, I'm going to hold off on this. Something about what I did seems to have polluted PATH in some way...

**Pull request closed without merging**
