### PR TITLE
winetricks 20150826

### PR DESCRIPTION
**Pull request by uyjulian**

### CODE REVIEW

**Comment by DomT4** [comment]
Seems to be dying on Mavericks and El Cap :confused: 

```
==> /usr/local/Cellar/winetricks/20150826/bin/winetricks dlls list
------------------------------------------------------
wine cmd.exe /c echo '%ProgramFiles%' returned unexpanded string '%ProgramFiles%' ... this can be caused by a corrupt wineprefix, by an old wine, or by not owning /private/tmp/winetricks20151030-24084-1iaonq3/.wine
------------------------------------------------------
Error: winetricks: failed
Failed executing: /usr/local/Cellar/winetricks/20150826/bin/winetricks dlls list
```

**Comment by uyjulian** [comment]
Maybe wine is broken on the buildbot... because it is working fine on my side

>julians-MacBook-Pro:~ julian$ /usr/local/Cellar/winetricks/20150826/bin/winetricks dlls list
>adobeair                 Adobe AIR 15.0 (Adobe, 2014) [downloadable]
> ...

**Comment by DomT4** [comment]
Checked it three times. Still breaking :confused:

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
