### PR TITLE
ttfautohint-1.4

### PR DESCRIPTION
**Pull request by lemzwerg**
Regarding #44608, thanks for help!  However, I managed to completely screw up the repository, so I started from scratch to clean up everything, this time doing it in a clean way hopefully :-)

### CODE REVIEW

**Comment by jiegec** [comment]
Well you can actually rebase and push --force and don't need to open a new pull request ;)

**Comment by lemzwerg** [comment]
Thanks for the hint!

**Comment by lemzwerg** [comment]
Hmm, is it normal that the second check takes such a long time?

**Comment by jiegec** [comment]
@lemzwerg 46 pending build on jenkins. The mavericks machine is down and stuck all builds:http://bot.brew.sh/job/Homebrew/version=mavericks/15177/console @Homebrew/homebrew

**Comment by lemzwerg** [comment]
OK, thanks

**Comment by jiegec** [comment]
@lemzweg Now the jenkins is running again

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/8b5df4d80ce3647ccfa5e3e08cae54d11fb5c192. Thank you for another contribution to Homebrew @lemzwerg! :smiley_cat:

**Pull request closed without merging**
