### PR TITLE
ldc 0.16.0-alpha4 (devel)

### PR DESCRIPTION
**Pull request by John-Colvin**

### CODE REVIEW

**Comment by John-Colvin** [comment]
For some reason there's no info on why it failed.

**Comment by John-Colvin** [comment]
@BrewTestBot test this please

**Comment by John-Colvin** [comment]
is that the right way to get it to restart testing? I guess I could change the commit to trigger it.

**Comment by John-Colvin** [comment]
updated for new alpha release

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/c57574826d92b0dc0a452ae72c3608ad48524c01. Thank you @John-Colvin!

**Pull request closed without merging**
