### PR TITLE
Alter patch to make http-parser bottle relocatable

### PR DESCRIPTION
**Pull request by staticfloat**
I'm not sure if you guys would prefer this patch rolled into the current one (as I have it right now) or as a separate one on top of the current patch.  The only reason I rolled it into the current one is that it touches some of the same lines.

This patch changes the `ln` command to create a relative symlink rather than an absolute one.

### CODE REVIEW

**Comment by staticfloat** [comment]
I have a PR open to upstream about this here: https://github.com/joyent/http-parser/pull/264

**Comment by xu-cheng** [comment]
I'm thinking instead patching individual formulae we should handle this inside relocate logic.

**Comment by staticfloat** [comment]
That is also a good idea; I'm working with upstream to get this patched, but relocation logic to remap symlinks would be nice as well!

**Comment by staticfloat** [comment]
Great; so now that #43816 has been merged, can `http-parser` be changed to simply be `Cellar :any`, or does it need to be rebottled?

**Comment by xu-cheng** [comment]
It requires rebottle. I have queue a job here http://bot.brew.sh/job/Homebrew%20Testing/880/

**Comment by xu-cheng** [comment]
Fixed by https://github.com/Homebrew/homebrew/commit/01a0d4b5555298c2bf61abd48f061f0cf1dda38d

**Comment by staticfloat** [comment]
Thanks @xu-cheng!  I appreciate it!

**Pull request closed without merging**
