### PR TITLE
quantlib 1.6

### PR DESCRIPTION
**Pull request by dunn**
No Debian mirror yet.

### CODE REVIEW

**Comment by bfontaine** [comment]
Shouldn’t we wait for Debian to add a mirror?

**Comment by dunn** [comment]
Fine with me, but there's sometimes a delay, isn't there?

**Comment by bfontaine** [comment]
I guess so, but I don’t know how reactive they are.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/2dc63a770b3b5ebf0928dc68bec85cef1364f844. Thanks again @dunn!

There's little point waiting for Debian to update if they haven't done so relatively quickly. Either they're backporting the version rather than adding a new `orig` base tarball, or they're not going to update. The mirrors tend to be quickly updated otherwise. I added a MacPorts one.

**Pull request closed without merging**
