### PR TITLE
upgrade to giflib 5.1

### PR DESCRIPTION
**Pull request by scottjg**
also patch a bunch of stuff that broke with the api changes.

### CODE REVIEW

**Comment by scottjg** [comment]
tricky. i think gdal is being installed from a bottle, linked against the old version of giflib (libgif.4.dylib). the tests uninstall the old version of giflib and install the new version (libgif.7.dylib). installing the gdal bottle then points against a library that doesn't exist.

not sure how these types of situations are handled normally. do i need to just bump the `revision` of the gdal formula to force it to rebuild? there's no version dependencies in these brew formulas so i don't know how you could force a user to upgrade these other packages when giflib is upgraded.

```
==> brew fetch --retry --build-bottle --force giflib			 PASSED
==> brew install --verbose --build-bottle giflib			 PASSED
==> brew audit giflib							 PASSED
==> brew bottle --rb giflib						 PASSED
==> Determining giflib bottle revision...
==> Bottling giflib-5.1.1.mavericks.bottle.tar.gz...
./giflib-5.1.1.mavericks.bottle.tar.gz
  bottle do
    cellar :any
    sha1 "ca89fd8d4d487f350d947ffd087cfb74a5b0015e" => :mavericks
  end
==> brew uninstall --force giflib					 PASSED
==> brew install ./giflib-5.1.1.mavericks.bottle.tar.gz			 PASSED
==> brew fetch --retry fontforge					 PASSED
==> brew install fontforge						 PASSED
==> brew test --verbose fontforge					 PASSED
==> brew fetch --retry gdal						 PASSED
==> brew install gdal							 PASSED
==> brew test --verbose gdal						 FAILED
Testing gdal
==> /usr/local/Cellar/gdal/1.11.1_3/bin/gdalinfo --formats
dyld: Library not loaded: /usr/local/lib/libgif.4.dylib
  Referenced from: /usr/local/Cellar/gdal/1.11.1_3/bin/gdalinfo
  Reason: image not found
Error: gdal: failed
Failed executing: /usr/local/Cellar/gdal/1.11.1_3/bin/gdalinfo --formats
/usr/local/Library/Homebrew/formula.rb:719:in `block in system'
/usr/local/Library/Homebrew/formula.rb:676:in `open'
/usr/local/Library/Homebrew/formula.rb:676:in `system'
/usr/local/Library/Formula/gdal.rb:320:in `block in <class:Gdal>'
/usr/local/Library/Homebrew/formula.rb:629:in `block in run_test'
/usr/local/Library/Homebrew/extend/fileutils.rb:21:in `mktemp'
/usr/local/Library/Homebrew/formula.rb:626:in `run_test'
/usr/local/Library/Homebrew/cmd/test.rb:38:in `block (2 levels) in test'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/usr/local/Library/Homebrew/cmd/test.rb:37:in `block in test'
/usr/local/Library/Homebrew/cmd/test.rb:15:in `each'
/usr/local/Library/Homebrew/cmd/test.rb:15:in `test'
/usr/local/Library/brew.rb:135:in `<main>'
```

**Comment by mikemcquaid** [comment]
Hi @scottjg :wave: 

> do i need to just bump the revision of the gdal formula to force it to rebuild?

Yup :+1: 

Also, could you please submit these patches to the upstream developers of these projects and add link to the upstream patch submissions and explanation of why the patches are needed as a comment in each formula file. Thanks (and sorry for the pain)!

**Comment by jacknagel** [comment]
If we need to patch this many packages to deal with this change, we should probably not upgrade at this time. We can add giflib 5.x to homebrew-versions.

**Comment by scottjg** [comment]
> If we need to patch this many packages to deal with this change, we should probably not upgrade at this time.

ok

**Pull request closed without merging**
