### PR TITLE
Gstreamer family 1.6.1

### PR DESCRIPTION
**Pull request by tschoonj**
also `orc`, which is also part of the family

### CODE REVIEW

**Comment by DomT4** [comment]
Looks like a sandbox violation on the `gst-python` formula:

```
/usr/bin/install -c -m 644 Gst.py GstPbutils.py '/usr/local/lib/python2.7/site-packages/gi/overrides'
install: /usr/local/lib/python2.7/site-packages/gi/overrides/Gst.py: Operation not permitted
make[3]: *** [install-pygioverridesPYTHON] Error 71
make[3]: *** Waiting for unfinished jobs....
libtool: install: /usr/bin/install -c .libs/_gi_gst.so /usr/local/lib/python2.7/site-packages/gi/overrides/_gi_gst.so
install: /usr/local/lib/python2.7/site-packages/gi/overrides/_gi_gst.so: Operation not permitted
make[3]: *** [install-pygioverridesexecLTLIBRARIES] Error 71
make[2]: *** [install-am] Error 2
make[1]: *** [install-recursive] Error 1
make: *** [install-recursive] Error 1
```

**Comment by tschoonj** [comment]
Interesting: the sandbox violation occurs only on Mavericks... I have a feeling it's connected to the other problem. I will throw gst-python out for now

**Comment by tschoonj** [comment]
I hate the mavericks bot :sad:

**Comment by tschoonj** [comment]
Ok... will close this down and open individual PRs...

Would you mind looking into this Mavericks issue at some point? Thanks!

**Comment by DomT4** [comment]
I've looked into the Mavericks issue before with no productive end result. It is peculiar that the issue only impacts Mavericks. Perhaps @mikemcquaid has some idea that I missed.

**Comment by mikemcquaid** [comment]
Not sure; could be a leftover cache on just that machine or seomthing?

**Comment by DomT4** [comment]
I've tried purging the cache and build logs of everything on the VM's `brew` prior to the mass `gstreamer` PRs before and running the build again; ran into the same error. Did it manually rather than via `cleanup` so definitely nothing left before trying again.

**Pull request closed without merging**
