### PR TITLE
Add giflib as compulsory dependency for formula "vice"

### LINKED ISSUE #42145: Bottled version of Vice has missing dependencies
Vice has giflib as an optional dependency:

```
agatti@tardigrade ~ $ brew info vice
vice: stable 2.4 (bottled)
Versatile Commodore Emulator
http://vice-emu.sourceforge.net/
/usr/local/Cellar/vice/2.4_1 (1208 files, 58M) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/vice.rb
==> Dependencies
Build: pkg-config ✔
Required: jpeg ✔, libpng ✔
Optional: giflib ✘, lame ✔
==> Options
--with-giflib
	Build with giflib support
--with-lame
	Build with lame support
==> Caveats
Cocoa apps for these emulators have been installed to /usr/local/Cellar/vice/2.4_1.

.app bundles were installed.
Run `brew linkapps vice` to symlink these to /Applications.
```

however, the bottled version relies upon giflib being installed:

```
agatti@tardigrade ~ $ brew install vice
==> Downloading https://homebrew.bintray.com/bottles/vice-2.4_1.yosemite.bottle.tar.gz
######################################################################## 100.0%
==> Pouring vice-2.4_1.yosemite.bottle.tar.gz
==> Caveats
Cocoa apps for these emulators have been installed to /usr/local/Cellar/vice/2.4_1.

.app bundles were installed.
Run `brew linkapps vice` to symlink these to /Applications.
==> Summary
🍺  /usr/local/Cellar/vice/2.4_1: 1208 files, 58M
agatti@tardigrade ~ $ brew linkapps vice
Linking /usr/local/opt/vice/x128.app to /Applications.
Linking /usr/local/opt/vice/x64.app to /Applications.
Linking /usr/local/opt/vice/x64dtv.app to /Applications.
Linking /usr/local/opt/vice/x64sc.app to /Applications.
Linking /usr/local/opt/vice/xcbm2.app to /Applications.
Linking /usr/local/opt/vice/xcbm5x0.app to /Applications.
Linking /usr/local/opt/vice/xpet.app to /Applications.
Linking /usr/local/opt/vice/xplus4.app to /Applications.
Linking /usr/local/opt/vice/xvic.app to /Applications.

agatti@tardigrade ~ $ cd /Applications
agatti@tardigrade /Applications $ open x64.app
LSOpenURLsWithRole() failed with error -10810 for the file /Applications/x64.app.
agatti@tardigrade /Applications $ cd x64.app/Contents/MacOS
agatti@tardigrade /Applications/x64.app/Contents/MacOS $ ./x64
dyld: Library not loaded: /usr/local/lib/libgif.4.dylib
  Referenced from: /usr/local/Cellar/vice/2.4_1/x64.app/Contents/MacOS/./x64
  Reason: image not found
[1]    2163 trace trap  ./x64
```

### PR DESCRIPTION
**Pull request by xuebinglee**
giflib has been made a compulsory (instead of optional) dependency to resolve #42145

### CODE REVIEW

**Comment by DomT4** [comment]
Since there's breakage here let's bump the `revision` to `2`.

**Comment by xuebinglee** [comment]
@DomT4 Good point. Done.

**Comment by xuebinglee** [comment]
@DomT4 I just realized that the commit message should've been "vice: bump revision to 2". Sorry about the incorrect format and typo.

**Comment by xuebinglee** [comment]
I've kept my fork up to date. Let me know if there's anything else I should do.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/15047366ba2a2cdf4cdcdd4048bf02ee67638dd3. Thank you for your contribution to Homebrew, we appreciate it! :smiley_cat:

**Pull request closed without merging**
