### PR TITLE
GStreamer 1.6.3

### PR DESCRIPTION
**Pull request by lovebug356**

### CODE REVIEW

**Comment by DomT4** [comment]
Where the `https://download.gnome` links for the gst-* formulae are available I'd like to keep using them, Thanks.

**Comment by lovebug356** [comment]
For which formula do you see that they are available on download.gnome? I can't find them on the gnome servers for any of them.

Is there a benefit in using links to mirrors (which are not always in sync) instead of the official locations?

**Comment by DomT4** [comment]
You seem to be correct. I thought I spotted a couple but apparently I cannot read numbers this morning.

> Is there a benefit in using links to mirrors (which are not always in sync) instead of the official locations?

Usually they are in sync; I'm not sure why there's a delay there this time but before they've always been up very quickly after release. The advantage is that _some_ of the GNOME mirrors remain secured with TLS throughout the connection and not downloading via plaintext is a significant upside for privacy.

**Comment by lovebug356** [comment]
ok, thx for feedback. It might be an idea to support multiple source url's, so it can always gracefully fall back to a working solution.

**Comment by DomT4** [comment]
Since this hasn't appeared on the mirrors still I'll take it as-is. The upstream website does declare it a stable release so seems fine.

Merged in a bunch o' commits. Thank you for your contributions to Homebrew @lovebug356; we appreciate them! :smiley_cat:

**Pull request closed without merging**
