### PR TITLE
xcode 7.2

### PR DESCRIPTION
**Pull request by DomT4**

### CODE REVIEW

**Comment by mikemcquaid** [comment]
@DomT4 did you update the build machines already? Thanks for this :heart:

**Comment by DomT4** [comment]
Aye, the VMs have been updated with the latest security & OS X releases and the Xcode/CLT bumps. Left a notation in the team chat but nothing major.

Want to do a bit of testing before we recommend people update to Xcode 7.2. The internal Xcode number changed from `7.0.0` to `7.0.2` in
```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/7.0.2
```
which apparently some upstreams directly link to: https://github.com/Homebrew/homebrew/issues/46832

**Comment by mikemcquaid** [comment]
Great, thanks.

**Comment by DomT4** [comment]
I can't produce any failures on some of the major formulae we ship, and an `otool -L` of my entire `lib` directory doesn't show any internal linking to Xcode Clang library paths so presuming the one reported issue is going to be pretty niche. Gonna :shipit:.

**Pull request closed without merging**
