### PR TITLE
update transmission-2.91 to remove malware

### PR DESCRIPTION
**Pull request by booi**
This is an *urgent* PR to update transmission to 2.91 following detection of malware in 2.90. The announcement can be seen here:

https://www.transmissionbt.com/

### CODE REVIEW

**Comment by booi** [comment]
More information

https://forum.transmissionbt.com/viewtopic.php?t=17834
https://www.reddit.com/r/mac/comments/498bir/transmission_290_infected_with_keranger/

**Comment by booi** [comment]
I think this is likely a binary replacement so it's unlikely homebrew was affected. Should update just in case.

**Comment by bfontaine** [comment]
Closing in favor of #49831. Thank you anyway!

**Comment by booi** [comment]
No problem! I'm very happy the community is so active even on a Sunday :).

**Pull request closed without merging**
