### PR TITLE
Gstreamer family 1.6.0

### PR DESCRIPTION
**Pull request by tschoonj**
Working my way through the gstreamer 1.6.0 family release:

- [x] gstreamer
- [x] gst-plugins-base
- [x] gst-plugins-good
- [x] gst-plugins-bad
- [x] gst-plugins-ugly
- [x] gst-libav 
- [x] gst-python
- [x] gst-validate

### CODE REVIEW

**Comment by tschoonj** [comment]
A test fails on El Capitan:

````
        Testing gst-libav
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20150927-6017-1yev2vg.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Library/Homebrew -- /usr/local/Library/Homebrew/test.rb /usr/local/Library/Formula/gst-libav.rb --verbose
==> /usr/local/opt/gstreamer/bin/gst-inspect-1.0 libav

(gst-plugin-scanner:6029): GStreamer-WARNING **: Failed to load plugin '/usr/local/lib/gstreamer-1.0/libgstlibav.so': dlopen(/usr/local/lib/gstreamer-1.0/libgstlibav.so, 2): Library not loaded: /usr/local/lib/liblzma.5.dylib
  Referenced from: /usr/local/lib/gstreamer-1.0/libgstlibav.so
  Reason: Incompatible library version: libgstlibav.so requires version 8.0.0 or later, but liblzma.5.dylib provides version 6.0.0
No such element or plugin 'libav'
Error: gst-libav: failed
Failed executing: /usr/local/opt/gstreamer/bin/gst-inspect-1.0 libav
/usr/local/Library/Homebrew/formula.rb:1342:in `block in system'
/usr/local/Library/Homebrew/formula.rb:1279:in `open'
/usr/local/Library/Homebrew/formula.rb:1279:in `system'
/usr/local/Library/Formula/gst-libav.rb:44:in `block in <class:GstLibav>'
/usr/local/Library/Homebrew/formula.rb:1188:in `block in run_test'
/usr/local/Library/Homebrew/extend/fileutils.rb:17:in `mktemp'
/usr/local/Library/Homebrew/formula.rb:1184:in `run_test'
/usr/local/Library/Homebrew/test.rb:28:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/usr/local/Library/Homebrew/test.rb:27:in `<main>'
````

This is strange as the Homebrew version of liblzma on my Yosemite has the right version, while on the El Capitan build bot it seems to be older.

Is it soft-linked to the system liblzma somehow? That one appears to be older and would indeed produce this problem.

**Comment by tschoonj** [comment]
@DomT4 @mikemcquaid 

Would you guys mind looking into this? It looks really fishy to me...

**Comment by DomT4** [comment]
We're maintainer light this week, so I'm afraid out of Mike & me you're stuck with the latter :wink:. I'll see if I can repro locally on my El Cap machine.

**Comment by DomT4** [comment]
Ah, there's a nice easy explanation here for once.

`xz` is a build dep of `gst-libav` because it is needed to untar the `.tar.xz` tarball. We leave `:build` dependencies installed throughout the build, then remove them and that ensures during `brew test` there aren't dependencies missing or mislabelled.

In this case, apparently `gst-libav` now links to `liblzma` at runtime and fails to find it during the test because we've removed it as a build dep. This appears to be new; the current version available in core has no such linkage.

If you chuck in a `depends_on "xz" # For LZMA` line into `gst-libav` you'll be good on that.

**Comment by tschoonj** [comment]
Done!

**Comment by dunn** [comment]
:scream_cat: :book: 
```
checking for XML catalog... /usr/local/etc/xml/catalog
checking for xmlcatalog... /usr/local/opt/libxml2/bin/xmlcatalog
checking for DocBook XML DTD V4.3 in XML catalog... not found
configure: error: could not find DocBook XML DTD V4.3 in XML catalog
```

**Comment by DomT4** [comment]
Those errors are going to stick around until #44268 is merged. Just want to double check that PR locally before doing so.

**Comment by DomT4** [comment]
@BrewTestBot test this please

**Comment by DomT4** [comment]
I won't list all 10 commits this was merged in, but merged :wink:. Thanks again Tom!

**Pull request closed without merging**
