### PR TITLE
icu4c 55.1

### PR DESCRIPTION
**Pull request by vszakats**

### CODE REVIEW

**Comment by vszakats** [comment]
This happened on Mavericks (only):
```
==> ./configure --prefix=/usr/local/Cellar/yaz/5.11.0_1 --with-xml2
==> make install
clang: error: linker command failed due to signal (use -v to see invocation)
make[1]: *** [zoomtst4] Error 254
make[1]: *** Waiting for unfinished jobs....
libtool: link: clang -g -O2 -D_THREAD_SAFE -o .libs/zoom-bug-641 zoom-bug-641.o  ../src/.libs/libyaz.dylib -lreadline -lncurses -lexslt -lxslt -lz -licucore -lm -lxml2 -liconv -lpthread
make: *** [install-recursive] Error 1
```

Any ideas what this might mean, and why is it Mavericks specific?

**Comment by vszakats** [comment]
@BrewTestBot make a rebuild.

**Comment by vszakats** [comment]
@BrewTestBot test this please

**Comment by vszakats** [comment]
No magic power over the bot!

**Comment by mikemcquaid** [comment]
@vszakats I've queued another build, it'll just take a while.

**Comment by vszakats** [comment]
Thanks @mikemcquaid. It was an intermittent failure, completed fine now.

**Comment by mikemcquaid** [comment]
Thanks @vszakats!

**Comment by jacknagel** [comment]
If these things are linked to icu, shouldn't they declare a dependency?

**Comment by jacknagel** [comment]
(referring to "secondary dependents")

**Comment by vszakats** [comment]
These two are using ICU headers via `yaz` headers and directly link to ICU libs, so I think they should.

**Comment by tdsmith** [comment]
mpd wasn't revisioned here and has an icu4c dependency and broke; are there other packages we might have missed?

**Comment by vszakats** [comment]
These might be candidates:
```
beecrypt.rb:  depends_on "icu4c"
boost.rb:    depends_on "icu4c" => [:optional, "c++11"]
boost.rb:    depends_on "icu4c" => :optional
couchdb.rb:  depends_on "icu4c"
gptfdisk.rb:  depends_on "icu4c"
harfbuzz.rb:  depends_on "icu4c" => :recommended
iojs.rb:  depends_on "icu4c" => :optional
mapnik.rb:  depends_on "icu4c"
node.rb:  depends_on "icu4c" => :optional
parrot.rb:  depends_on "icu4c" => :optional
rakudo-star.rb:  depends_on "icu4c" => :optional
sqlite.rb:  depends_on "icu4c" => :optional
sword.rb:  depends_on "icu4c" => :optional
znc.rb:  depends_on "icu4c" => :optional
```

Potentially `yazpp` that depends on `yaz`, and maybe `metaproxy` that depends on it `yazpp`.

**Comment by vszakats** [comment]
Made a PR for those I _suspect_ might fall into the same category: https://github.com/Homebrew/homebrew/pull/39354

**Comment by srl295** [comment]
FYI ICU 56 just landed yesterday. http://site.icu-project.org/download/56

**Comment by vszakats** [comment]
Thanks @srl295!

**Pull request closed without merging**
