### PR TITLE
gflags 2.1.2

### PR DESCRIPTION
**Pull request by Noctem**
Update to latest stable release, change URLs to GitHub, use cmake, modernize formula.

### CODE REVIEW

**Comment by DomT4** [comment]
Does 2.1.2 fix the problems we had with 2.1.1 that caused the revert in https://github.com/Homebrew/homebrew/commit/a7f3495fa98b48a66c01ea8b243d2b7894b79639?

**Comment by Noctem** [comment]
@DomT4 So that would manifest itself while building `osquery`? If so, then yes.

I just built `osquery` against `gflags` 2.1.2 and `glog` 0.3.4 (via #38246) and didn't run into any issues.

**Comment by DomT4** [comment]
Yeah, both ` osquery ` and ` glog ` broke pretty spectacularly last time. If it compiles and runs fine against the new ` gflags ` we should be golden.

**Comment by asparagui** [comment]
Thanks, will keep an eye on.

**Pull request closed without merging**
