### PR TITLE
grails: update to 2.5.0

### PR DESCRIPTION
**Pull request by cyphercrack**

### CODE REVIEW

**Comment by tdsmith** [comment]
Can you rebase this on current master and force-push to your Github remote? Happy to help if that's gibberish.

**Comment by cyphercrack** [comment]
I've rebase to current master.

**Comment by mikemcquaid** [comment]
@BrewTestBot test this please

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
