### PR TITLE
nginx 1.9.1

### PR DESCRIPTION
**Pull request by PikachuEXE**

### CODE REVIEW

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/998e2d9a7c0b4ad4b3bbd68c4560964ee7e67182. Thanks for your contribution to Homebrew, we appreciate it! :smiley_cat:.

Tiny nit for future: `devel` version bumps should have the commit message marked with `(devel)`, Thanks!

**Comment by PikachuEXE** [comment]
This is the first time I do devel version bump, so not so sure about the rules.
Would love to see that hint about `(devel)` being put in [PR Guide](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-%28and-get-it-merged%29.md#how-to-open-a-homebrew-pull-request-and-get-it-merged)

**Comment by DomT4** [comment]
> Would love to see that hint about (devel) being put in PR Guide

Fair point. Open a PR if you like?

**Comment by PikachuEXE** [comment]
#40578 opened

**Pull request closed without merging**
