### PR TITLE
gmp 6.1.0

### PR DESCRIPTION
**Pull request by dunn**
Not available on the mirrors yet ¯\\(´o｀)/¯

### CODE REVIEW

**Comment by dunn** [comment]
john-jumbo _really_ wants to write to `~`; this is the only way I could figure out how to stop it, smh.  Other proposals very welcome.

**Comment by DomT4** [comment]
Yeah, it uses an alternative language-specific method to determine `$HOME` that doesn't involve actually checking the `$HOME` env, much like Java is prone to doing. I'd probably just ditch the test for now, rather than forcing an unnecessary rebuild on users.

**Comment by dunn** [comment]
Why is the 10.9 test installing things from Versions? https://travis-ci.org/Homebrew/homebrew/jobs/92458524

**Comment by DomT4** [comment]
We tap `versions` to get the special Ruby installation, so I guess the CI just builds against anything it can find that uses the formula as a dep, maybe?

**Comment by dunn** [comment]
Oh, makes sense.

**Comment by DomT4** [comment]
Tried putting it back through Travis but looks like it's still using the travis file at the time of commit. The Travis build of the `.travis` configuration change passed fine though, so presume this would be alright.

Up to you whether you want to rebase and let Travis poke it again or just merge off the Jenkins build being green.

**Comment by dunn** [comment]
May as well, thanks for figuring out the fix!

**Pull request closed without merging**
