### PR TITLE
node 0.12.4

### PR DESCRIPTION
**Pull request by mourner**
Bump: 
http://blog.nodejs.org/2015/05/13/node-v0-12-3-0.12.3/
http://blog.nodejs.org/2015/05/22/node-v0-12-4-stable/

### CODE REVIEW

**Comment by DomT4** [comment]
#39780

**Comment by mourner** [comment]
@DomT4 ha, sorry, I wondered why Node wasn't updated shortly but didn't check issues on the matter for some reason. Thanks!

**Comment by DomT4** [comment]
No worries! Feel free to keep this open. Once there's a new release or patch we can apply you can just tweak the PR if you like.

**Comment by dunn** [comment]
0.12.4 is out and looks like the v8 problem is fixed: https://github.com/joyent/node/releases/tag/v0.12.4

**Comment by DomT4** [comment]
Yup, they merged the V8 fix last night. If you rebase this against the master and rebump the `npm` version if they've released a new stable version in the mean time this should be good to go providing the bot is happy.

**Comment by mourner** [comment]
@DomT4 thanks!
Update the PR to node 0.12.4, should be good to go!

**Comment by DomT4** [comment]
Can you update your master branch and then rebase this PR against that master branch? Thanks! We merged an `npm` update the other night as part of some other fixes, and Git not knowing that commit exists in this branch is likely causing the merge conflict.

**Comment by mourner** [comment]
@DomT4 ah apologies, done!

**Comment by DomT4** [comment]
Looks great, Thanks! :star2:

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/9033a265c7f0f0ef19736f13f8a2e415a1bc2b95. Thanks for your contribution to Homebrew, we appreciate it! :smiley_cat:

**Pull request closed without merging**
