### PR TITLE
libvirt 1.2.13

### PR DESCRIPTION
**Pull request by justinclift**

### CODE REVIEW

**Comment by vszakats** [comment]
Hello, would you mind using `https` for both the `homepage` and the `url`?

**Comment by justinclift** [comment]
@vszakats Good idea.  I'll update the formula now. :smile:

**Comment by vszakats** [comment]
Thanks!

**Comment by tdsmith** [comment]
Thanks for the pull request! 🎉 Homebrew depends on contributions from community members like you and we're grateful for your support.

**Comment by justinclift** [comment]
Welcome. :smile:

**Pull request closed without merging**
