### PR TITLE
thefuck 3.0

### PR DESCRIPTION
**Pull request by scorphus**
Here we go again! TheFuck 3.0 FTW

 * Add new dependency: decorator-4.0.2
 * Update dependency: psutil-3.2.1

### CODE REVIEW

**Comment by scorphus** [comment]
I'm looking into what went wrong with the build.

**Comment by scorphus** [comment]
I got it, reproduced locally and am on it. I'll soon force-push a fix.

**Comment by scorphus** [comment]
Thefuck now always shows those up/down non-ascii arrow keys. I'll try setting `THEFUCK_REQUIRE_CONFIRMATION` to `false`.

**Comment by scorphus** [comment]
YAY! \o/

**Comment by dunn** [comment]
Awesome! Merged in f763c4ede530adb50deffb180f154481f7d2c71f :bee:

**Pull request closed without merging**
