### PR TITLE
mdk 1.2.8 (new formula)

### PR DESCRIPTION
**Pull request by tml**
Add the GNU MDK suite (an implementation of Don Knuth's MIX computer
from "The Art of Computer Programming."

### CODE REVIEW

**Comment by tml** [comment]
Note that this formula will not pass "brew audit" perfectly cleanly, because there is intentional trailing whitespace on line 41 of the forumla; without this whitespace, the expected output will not match the actual output.

**Comment by jacknagel** [comment]
We prefer to use heredocs (grep for `<<-EOS.undent`) for multi-line strings.

Can we do something similar to

```rb
expected = "partial string" + " " * 100 + "partial string"
```

to satisfy the audit failure?

**Comment by tml** [comment]
@jacknagel Sure - I can push both of those. Any idea what I need to do to fix this one?

* "ftpmirror.gnu.org" is preferred for GNU software (url is https://ftpmirror.gnu.org/gnu/mdk/v1.2.8/mdk-1.2.8.tar.gz).

With "https://" there, it fails "brew audit"; without the "https://", it fails to fetch on jenkins with this compile log:


        ==> Downloading ftpmirror.gnu.org/gnu/mdk/v1.2.8/mdk-1.2.8.tar.gz
==> Retrying download
==> Downloading ftpmirror.gnu.org/gnu/mdk/v1.2.8/mdk-1.2.8.tar.gz
Error: Failed to download resource "mdk"
Download failed: ftpmirror.gnu.org/gnu/mdk/v1.2.8/mdk-1.2.8.tar.gz

**Comment by jacknagel** [comment]
`ftpmirror` doesn't a "gnu" subdirectory, so you need to remove the `/gnu/` from the URL.

In other words, the URLs should be:

```rb
url "http://ftpmirror.gnu.org/mdk/v1.2.8/mdk-1.2.8.tar.gz"
mirror "https://ftp.gnu.org/gnu/mdk/v1.2.8/mdk-1.2.8.tar.gz"
```

**Comment by tml** [comment]
Done. Thanks for the help!

**Pull request closed without merging**
