### PR TITLE
mpich 3.2rc2 (devel)

### PR DESCRIPTION
**Pull request by smseo**
Updated the mpich formula to use the latest develop branch of MPICH, mpich-3.2rc2.

### CODE REVIEW

**Comment by s2mcom** [comment]
The Travis CI build failed because no fortran compiler was found. It was a configure failure.

**Comment by mikemcquaid** [comment]
Hmm, not sure why the `depends_on :fortran` isn't working.

**Comment by s2mcom** [comment]
Any suggestions to resolve this issue?

**Comment by mikemcquaid** [comment]
I'm not sure. @xu-cheng @DomT4 @tdsmith @mistydemeo may know more about Fortran stuff.

**Comment by xu-cheng** [comment]
Maybe `ENV.fortran if build.with? "fortran"` will help.

**Comment by DomT4** [comment]
No idea I'm afraid. I try to avoid Fortran stuff.

**Comment by apjanke** [comment]
I think the issue is that the `depends_on :fortran => :recommended` won't cause a fortran compiler to be installed; it just detects what is available on the system. In this normal case, it needs to have `gcc` installed since `gfortran` is supplied by it.

If I change it to an unconditional `depends_on :fortran`, then `brew install mpich` will automatically install `gcc`.

Sounds like the `default_formula` requirement resolution may need to be reviewed for `:recommended` dependencies.

Here's what I think is happening, based on adding some logging statements to `formula_installer.rb`. That `:recommended` `:fortran` requirement gets converted to a dependency on `gcc`. But then later on [in `formula_installer#expand_dependencies`](https://github.com/Homebrew/homebrew/blob/3126196ca45beb822d64ae4dd4962850bd0bb576/Library/Homebrew/formula_installer.rb#L325-L342), it checks that `gcc` dependency against `build.without?` and it returns false, so the installer skips it.

```
      if (dep.optional? || dep.recommended?) && build.without?(dep)
        puts "Pruning unused optional dependency #{dep}"
        Dependency.prune
```

**Comment by mikemcquaid** [comment]
@apjanke Nice work finding the bug :+1:

**Comment by smseo** [comment]
Thanks @apjanke.
@mikemcquaid I can modify `depends_on :fortran => :recommended` to `depends_on :fortran`, but I'm not sure it's a right fix. Is it better to wait until the bug above is resolved?

**Comment by mikemcquaid** [comment]
> Is it better to wait until the bug above is resolved?

Yup, thanks!

**Comment by smseo** [comment]
OK. Thanks!

**Comment by zbeekman** [comment]
So, what's the status here? I'm a bit lost.

**Comment by mikemcquaid** [comment]
> Here's what I think is happening, based on adding some logging statements to formula_installer.rb. That :recommended :fortran requirement gets converted to a dependency on gcc. But then later on in formula_installer#expand_dependencies, it checks that gcc dependency against build.without? and it returns false, so the installer skips it.

This is the issue here. `build.without?` needs fixed to handle this case and/or we should check it twice to check based on the actual requirement name that was expanded to the dependency.

**Comment by mikemcquaid** [comment]
The dependency issue is fixed in https://github.com/Homebrew/homebrew/issues/46916. If you rebase this pull request it should be sorted.

**Comment by smseo** [comment]
Thanks @mikemcquaid. I've rebased, but I think this commit is not meaningful because #47001 has a patch for MPICH 3.2 (stable release) and MPICH 3.2rc2 is not a devel version anymore. What do you think about closing this pull request?

**Comment by UniqMartin** [comment]
@smseo If you could work with the author of #47001 and help out there, that would be awesome! I agree that working on this devel version doesn't make much sense anymore. Nonetheless, thanks for your work here and sorry for the issue that stalled this PR!

(Please let me know, if I misread your comment and thus closed this PR too early.)

**Comment by UniqMartin** [comment]
@smseo Sorry, but when I wrote my last comment I didn't realize that other PR was basically done.

**Comment by smseo** [comment]
@UniqMartin No problem. And, thanks for closing this request. I also saw other PR was done.

**Pull request closed without merging**
