### PR TITLE
bottle: better match for formulea with `stable do` block

### PR DESCRIPTION
**Pull request by xu-cheng**
It will only work if the indents are correct.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
:+1:

**Comment by xu-cheng** [comment]
Updated to handle arbitrary number of spaces in the indent. But it still requires `stable do` and `end` in the same indent level.

**Comment by mikemcquaid** [comment]
> But it still requires stable do and end in the same indent level.

I think that's a safe assumption.

**Comment by xu-cheng** [comment]
I did a little scan, `unittest-cpp` is so far the only formula has the wrong `bottle` position.

**Comment by xu-cheng** [comment]
Is this PR good for merging? Or maybe more reviews?

**Comment by mikemcquaid** [comment]
Merge away.

**Comment by xu-cheng** [comment]
:shipit:

**Comment by mikemcquaid** [comment]
@xu-cheng Can you use `brew pull` or add the `Closes #37024` message to your commit manually so we can see what commit closed the PR from the notification email? Thanks!

**Comment by xu-cheng** [comment]
I did use `brew pull`. However after I push it to homebrew, I deleted the branch immediately. It seems if the branch is deleted ahead of Github find the PR is closed, it will omit the close message. Next time, I will wait for a couple of time before deleting the branch. Cheers.

**Comment by mikemcquaid** [comment]
Ah, my mistake, sorry and yeh, that'd be great, thanks!

**Pull request closed without merging**
