### PR TITLE
kettle 6.0.0

### PR DESCRIPTION
**Pull request by jamesongithub**

### CODE REVIEW

**Comment by mikemcquaid** [comment]
The test is failing: is there any way to coax this into the Cellar? http://bot.brew.sh/job/Homebrew%20Pull%20Requests/36035/version=el_capitan/testReport/junit/brew-test-bot/el_capitan/test_kettle/

**Comment by jamesongithub** [comment]
Hm i didn't hit any problems installing it locally and it's in the cellar.

How do I run the tests locally? 

$ brew test kettle
`Error: Testing requires the latest version of kettle`

**Comment by DomT4** [comment]
You'd need to install the new version before you can test it.

**Comment by jamesongithub** [comment]
i did?

```
$ brew info kettle
kettle: stable 5.0.1
Pentaho Data Integration software
http://community.pentaho.com/projects/data-integration/
/usr/local/Cellar/kettle/6.0.0.0-353 (3121 files, 1.0G) *
  Built from source
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/kettle.rb
==> Caveats
To have launchd start kettle at login:
  ln -sfv /usr/local/opt/kettle/*.plist ~/Library/LaunchAgents
Then to load kettle now:
  launchctl load ~/Library/LaunchAgents/homebrew.mxcl.kettle.plist
.app bundles were installed.
Run `brew linkapps kettle` to symlink these to /Applications.
```

No sure where the 5.0.1 is coming from.

**Comment by DomT4** [comment]
Homebrew thinks `kettle: stable 5.0.1` is the latest, regardless of what you have installed, because that's what is written in the formula. How did you create the PR? Do you use your core Homebrew repo for submitting PRs or a local copy elsewhere?

**Comment by jamesongithub** [comment]
The PR is from my fork. To install I just pointed to the formula locally, which is the same as the fork.

**Comment by DomT4** [comment]
The origin will be set to Homebrew rather than your fork, so `brew info` may well be reading the correct version off our origin. Mike's the git expert, I'll leave it to him to comment on this, heh.

**Comment by mikemcquaid** [comment]
Rather than pointing to the fork check out the branch and do `brew uninstall --force kettle; brew install kettle`

**Comment by jamesongithub** [comment]
i didn't point at the fork. i checked it out locally and installed it by pointing at the formula locally.

**Comment by mikemcquaid** [comment]
Rather than pointing to the formula just try to follow my previous instructions, thanks. Also, the sandbox errors are the issue here: https://travis-ci.org/Homebrew/homebrew/jobs/89550319#L2880

**Comment by bfontaine** [comment]
This should be rebased on top of `master`.

**Comment by jamesongithub** [comment]
looks like this is done now.

**Pull request closed without merging**
