### PR TITLE
add .editorconfig

### PR DESCRIPTION
**Pull request by xu-cheng**
See http://editorconfig.org

### CODE REVIEW

**Comment by mikemcquaid** [comment]
I'd probably rather we didn't add this.

**Comment by xu-cheng** [comment]
The idea is to let formula author's editors auto pick up this config file. So we don't need to manually point out style problem(mainly indent size etc). 

But I'm OK to both include or not include such change.

**Comment by mikemcquaid** [comment]
Yeh, I guess my problem is that it requires a plugin for most editors, no?

**Comment by xu-cheng** [comment]
While hand of editors support this without plugin. Additional I saw many OSS projects(e.g. Ruby) includes this.

But I guess I will pass this.

**Pull request closed without merging**
