### PR TITLE
glib-networking: fix sandbox

### PR DESCRIPTION
**Pull request by DomT4**
Retains the exact presently existing behaviour, just in a way we can sandbox during installation and start bottling this formula. Everything still ends up in `HOMEBREW_PREFIX/lib/gio/modules`.

Ref: #41501

### CODE REVIEW

**Comment by DomT4** [comment]
Oh, heh. This is getting killed by the:

```
==> brew install ./glib-networking-2.44.0.yosemite.bottle.tar.gz	 FAILED
Error: undefined method `skip_relocation?' for nil:NilClass
```

issue @dunn saw in #43157 as well.

**Comment by xu-cheng** [comment]
I don't use these formulae. But I have some questions:

* Do we have to copy all these files? Why can't we install them into `lib`, then symlink them? If you have to copy these files, can you confirm which files are used in action?(since you are altering install path, I wonder do you change another hard code searching path in the process?)
* The cache file doesn't appear to be used in this formula. I think the right course is to delete it in install and regenerate in postinstall.

**Comment by DomT4** [comment]
> Why can't we install them into lib, then symlink them?

I did it this way because if we switch to symlinks and then someone does `brew rm glib-networking` the entire `HOMEBREW_PREFIX/lib/gio` directory is removed, which doesn't seem to be desirable as `glib` and `glib-networking` both attempt to create it during installation and we create it `post_install`.

It seems desired to keep that directory intact, even after `glib-networking` is removed and that's the behaviour we've supported to date.

> (since you are altering install path, I wonder do you change another hard code searching path in the process?)

There's almost nothing about the `glib-networking` formula, heh. It's these set of libs, and some locales. There doesn't seem to be any paths to bork, as long as we put the stuff in the same place for other formulae/software to find it.

> The cache file doesn't appear to be used only in this formula. I think the right course is to delete it in install and regenerate in postinstall.

Sure, we can do that, but we still need to handle the rest of the objects it dumps in that prefix that would otherwise cause linking errors. The cache is only a wee part of the linking failure.

**Comment by xu-cheng** [comment]
> I did it this way because if we switch to symlinks and then someone does brew rm glib-networking the entire HOMEBREW_PREFIX/lib/gio directory is removed, which doesn't seem to be desirable as glib and glib-networking both attempt to create it during installation and we create it post_install.

> It seems desired to keep that directory intact, even after glib-networking is removed and that's the behaviour we've supported to date.

This can be fixed by https://github.com/xu-cheng/homebrew/commit/5dcfbe44ed168890c7824ef36c25ddc7956d2d28

**Pull request closed without merging**
