### PR TITLE
percona-server 5.6.22-72.0

### PR DESCRIPTION
**Pull request by nijikon**

### CODE REVIEW

**Comment by DomT4** [comment]
@jacknagel May want to kill this build again, It's been going for 4 hours and Mavericks and Yosemite have failed to fetch the tarballs involved :confused:.

**Comment by hacfi** [comment]
It it possible to retrigger the build? The tarballs seem to work fine at the moment.

**Comment by mikemcquaid** [comment]
Let's give it a few days.

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Comment by hacfi** [comment]
Thanks for merging @mikemcquaid

**Pull request closed without merging**
