### PR TITLE
Typing software trr and its requirements apel.

### PR DESCRIPTION
**Pull request by wkentaro**

### CODE REVIEW

**Comment by tdsmith** [comment]
Looking through old PRs and found this: are you still interested in this? We shouldn't maintain a Japanese to English translation in the formula; can you remove the translation?

**Comment by wkentaro** [comment]
Alright, I fixed it.

**Comment by tdsmith** [comment]
Thanks for the PR and for coming back to update it; sorry this took us so long!

**Comment by wkentaro** [comment]
I'm happy to hear that. Thank you for your time!

2015年3月31日火曜日、tim smith<notifications@github.com>さんは書きました:

> Thanks for the PR and for coming back to update it; sorry this took us so
> long!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Homebrew/homebrew/pull/31900#issuecomment-87963931>.
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Pull request closed without merging**
