### PR TITLE
librevenge: use secure homepage, fix test failure

### PR DESCRIPTION
**Pull request by vszakats**

### CODE REVIEW

**Comment by dunn** [comment]
What are the revision bumps for?

**Comment by DomT4** [comment]
Weird Boost CI issues, if I remember correctly from the other PR.

**Comment by vszakats** [comment]
Ref: https://github.com/Homebrew/homebrew/pull/45914#issuecomment-156412624

**Comment by DomT4** [comment]
Looks like it's still failing. Weird. Have kind of a busy day today but I'll try and take a look locally this PM.

**Comment by vszakats** [comment]
It didn't resolve the problem, just opened this one to continue where the issue was abandoned in another [PR](https://github.com/Homebrew/homebrew/pull/45914).

**Comment by vszakats** [comment]
👍🏻

**Comment by DomT4** [comment]
Oh. Kind of an obvious failure that I should have spotted really. All the failing tests seem to be looking for `Boost` because it is present at compile-time, but because it is marked as a `:build` dep we remove it postinstall to check `:build` deps aren't mislabelled, and that causes the test to fail on looking for Boost.

It looks like Boost became runtime-expected here, at some point, probably because we're passing ` ENV["LDFLAGS"] = "-lboost_system-mt"`, I suspect.

**Comment by vszakats** [comment]
@DomT4 You were spot on &mdash; after applying your fix, it passes without any problem.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/8191b84a0f233d26e9aeb3f88685bfd4e1229939. Thanks @vszakats!

**Pull request closed without merging**
