### PR TITLE
disco: audit fixes

### PR DESCRIPTION
**Pull request by apjanke**
Just audit fixes.

### CODE REVIEW

**Comment by bfontaine** [comment]
Is there any reason for making a PR instead of pushing directly?

**Comment by apjanke** [comment]
I wanted to run it through the test bots and get an el capitan bottle for it. Getting bottles requires a PR, right?

**Comment by apjanke** [comment]
Build failure:

```
Compiling src/ddfs/ddfs_gc.erl failed:
src/ddfs/ddfs_gc.erl:52: erlang:now/0: Deprecated BIF. See the "Time and Time Correction in Erlang" chapter of the ERTS User's Guide for more information.
src/ddfs/ddfs_gc.erl:56: erlang:now/0: Deprecated BIF. See the "Time and Time Correction in Erlang" chapter of the ERTS User's Guide for more information.
[...snip...]
src/ddfs/ddfs_gc.erl:119: erlang:now/0: Deprecated BIF. See the "Time and Time Correction in Erlang" chapter of the ERTS User's Guide for more information.
ERROR: compile failed while processing /private/tmp/disco20151127-13670-9rg34/disco-0.5.4/master: rebar_abort
make: *** [master] Error 1
```

Sounds like Erlang 18 introduced a big API change, and our last `disco` build was from before that.

From the [referenced ERTS manual](http://www.erlang.org/doc/apps/erts/time_correction.htm):

> As of OTP 18 (ERTS version 7.0) the time functionality of Erlang has been extended. This both includes a new API for time, as well as time warp modes which alters the behavior of the system when system time changes.

**Comment by apjanke** [comment]
Upstream PR for this issue: discoproject/disco#632

**Comment by bfontaine** [comment]
> Getting bottles requires a PR, right?

Yep.

**Comment by apjanke** [comment]
I'm pulling this in to get the audit fix out of the way. Leaving the existing bottles as is. Moved the bug report to #46780, which has better description.

**Pull request closed without merging**
