### PR TITLE
dnsmasq 2.73

### PR DESCRIPTION
**Pull request by nijikon**
I don't know if i'm suppose to change tha sha256 for bottle segment.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
> I don't know if i'm suppose to change tha sha256 for bottle segment.

Just leave them as-is and they'll be updated when we pull, thanks!

**Comment by nijikon** [comment]
@mikemcquaid so I should only change sha1 to sha256 for the package, and the bottle will automatically be updated from sha1 to sha256?

**Comment by mikemcquaid** [comment]
@nijikon Yup :+1:

**Comment by nijikon** [comment]
@mikemcquaid clear, thanks!

**Comment by nijikon** [comment]
@mikemcquaid is this ok or there is something else that needs to be done?

**Comment by mikemcquaid** [comment]
Thanks @nijikon!

**Pull request closed without merging**
