### PR TITLE
Updated terraform to v0.6.11

### PR DESCRIPTION
**Pull request by joaocc**

### CODE REVIEW

**Comment by joshuajabbour** [comment]
Is this all that is required? Previous upgrades included changes to the `terraform_deps` (https://github.com/Homebrew/homebrew/pull/48610, https://github.com/Homebrew/homebrew/pull/47901, etc).

cc @nicolai86

**Comment by nicolai86** [comment]
@joshuajabbour AFAICT terraform switched to vendoring their dependencies /w v0.6.11, see [6fe27036](https://github.com/hashicorp/terraform/commit/6fe27036650adc8bc9237d033dd9d18c517892a1)

We should probably restructure the formula to account for this change - removing most if not all of the `git clone` steps.

**Comment by joshuajabbour** [comment]
Excellent, sounds good. Def :+1: on removing the unnecessary code then.

I was going to suggest putting some comments in the formula explaining the upgrade process, but it sounds like it should be pretty straightforward form now on.

**Comment by mikemcquaid** [comment]
Install is failing: http://bot.brew.sh/job/Homebrew%20Pull%20Requests/41154/version=el_capitan/testReport/junit/brew-test-bot/el_capitan/install_terraform/

**Comment by nicolai86** [comment]
@mikemcquaid see https://github.com/Homebrew/homebrew/pull/48773 for a working PR

**Comment by joaocc** [comment]
Quick question... 
Why don't we use the binary distribution that is already available at terraform (https://www.terraform.io/downloads.html and https://releases.hashicorp.com/terraform/0.6.11/terraform_0.6.11_darwin_amd64.zip)?
It seems to be easier to get the zip and extract the executable files.
Thx

**Comment by DomT4** [comment]
> Why don't we use the binary distribution 

We don't use binaries in the core, beside `.jar` files and a few other special cases.

They provide bad UX because we can't control how they behave, we can't ensure they work on every platform without unclear logic and if someone comes to us with "x software has x horrible security vulnerability" all we can do is kind of shrug and tell them to wait on a new upstream release.

**Comment by miketheman** [comment]
Recommending closure via https://github.com/Homebrew/homebrew/commit/eea72993bbb225897d2986b445a2a2de5bfe1149

**Comment by DomT4** [comment]
Oops, missed that this was still open. Good shout, closing.

**Comment by joaocc** [comment]
@DomT4, can you please explain what you meant by "We don't use binaries in the core"?
I see many other homebrew installs with binaries only.
Many times I update formulas for a new version of some sw, instead of installing them from their site. All I do is get the installer URL (usually dmg or zip), calc the sha256, and PR it.
Most of these are binaries only.
Thanks

**Comment by DomT4** [comment]
In the core: Those are very likely our binaries, generated by our CI infrastructure.
In `homebrew-binary`: Likely upstream's binaries.
In `Caskroom/cask`: All are from upstream.

Looking at your contributor record you've contributed frequently to the Caskroom, so indeed, upstream binary/sha/submit PR would be the correct mechanism for them. In Homebrew/homebrew though, almost everything is built from source and packaged by us.

**Comment by joaocc** [comment]
Thanks for the clarification!

**Pull request closed without merging**
