### PR TITLE
aws-elasticbeanstalk-3.4.5

### PR DESCRIPTION
**Pull request by zabawaba99**

### CODE REVIEW

**Comment by DomT4** [comment]
Do any of the resources need updating?

**Comment by zabawaba99** [comment]
From what I saw, no. I was able to successfully install/test that aws-elasticbeanstalk after making the change.

Are there any other checks I should do as well?

**Comment by DomT4** [comment]
It'd be cool to check if the resources on pypi have updates available, and if we can use those. Not sure what @tdsmith's preference on checking for updates on formula update is.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/a74669d1a8d9c29395b89cde4d2b4cc8abde013b. Thanks for your contribution to Homebrew, we appreciate it! :smiley_cat:

**Comment by zabawaba99** [comment]
Anytime!

**Pull request closed without merging**
