### PR TITLE
audit fixes: C 06: ctags - cups-pdf

### PR DESCRIPTION
**Pull request by apjanke**

### CODE REVIEW

**Comment by bfontaine** [comment]
Seems like Travis doesn’t like long builds without output:
```
==> Determining crystax-ndk bottle revision...
==> Bottling crystax-ndk-10.2.1.el_capitan.bottle.tar.gz...
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
The build has been terminated
```

**Comment by apjanke** [comment]
Guh. I'll break this out in to separate, more tractable PRs and re-submit.

**Comment by apjanke** [comment]
Oh wait; that's not going to help if it's timing out on just a single formula with slow output. Well, I'll yank that one out and see if something can be done.

**Comment by bfontaine** [comment]
I think that’s an issue inherent to `crystax-ndk` and other large formulae.

**Comment by mikemcquaid** [comment]
CC @xu-cheng for thoughts no how to resolve the Travis failure. @apjanke just ignore this, we'll merge when Jenkins is green, thanks!

**Comment by apjanke** [comment]
Hmm. The `brew test cryptol` failed, but only on Yosemite.

```
failed: brew test --verbose cryptol

Stacktrace

        Testing cryptol
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20151103-37201-dlr7f2.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Library/Homebrew -- /usr/local/Library/Homebrew/test.rb /usr/local/Library/Formula/cryptol.rb --verbose
==> /usr/local/Cellar/cryptol/2.2.4/bin/cryptol -b /private/tmp/cryptol20151103-37202-1gk81vd/hello.icry
Error: cryptol: failed
Expected /Loading\ module\ Cryptol\nQ\.E\.D\.\nQ\.E\.D\.\n/ to match "Loading module Cryptol\n*** An error occurred.\n***  Failed to start the external solver: fd:6: hGetLine: end of file\n***  Make sure you can start \"/usr/local/bin/cvc4\"\n***  from the command line without issues.\n*** An error occurred.\n***  Failed to start the external solver: fd:6: hGetLine: end of file\n***  Make sure you can start \"/usr/local/bin/cvc4\"\n***  from the command line without issues.\n".  
```

I don't have a Yosemite box to work through this on, so will probably just remove the `cvc4` change.

And the `csup` build failed, but only in Travis CI, and only on El Capitan. That one I'll try to figure out.

```

clang -DNDEBUG -DHAVE_FFLAGS -O -pipe -I/usr/local/include -Wall -W -Wstrict-prototypes -Wmissing-prototypes -Wpointer-arith -Wreturn-type -Wcast-qual -Wwrite-strings -Wswitch -Wshadow -Wcast-align -Wunused-parameter -Wchar-subscripts -Winline -Wnested-externs -Wredundant-decls -Wno-format-y2k -c -o rcsparse.o rcsparse.c

rcsparse.c:35:10: fatal error: 'rcstokenizer.h' file not found
#include "rcstokenizer.h"
         ^
1 error generated.
make: *** [rcsparse.o] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by mikemcquaid** [comment]
@apjanke If just Travis and not Jenkins fail: you can ignore it.

**Pull request closed without merging**
