### PR TITLE
Add formula for Apache Spark 1.5.2

### PR DESCRIPTION
**Pull request by jimhe**
This is modeled off the apache-spark141 formula.

### CODE REVIEW

**Comment by dunn** [comment]
Shouldn't this be in our Versions tap?

**Comment by jimhe** [comment]
Oh, I must have wandered down this path through `brew create` which put the new file in homebrew. I'm happy to PR against the other repo instead.

**Comment by dunn** [comment]
Please do!  But could you make it a general 1.5.x formula?

**Comment by jimhe** [comment]
Could you elaborate on 1.5.x? Would that just be separate files for each x?

**Comment by dunn** [comment]
I mean not pinning the version at 1.5.3.  If/when 1.5.4 is released, update it to that.  The formula name would be `apache-spark15` instead of `apache-spark153`.

**Comment by jimhe** [comment]
Gotcha. Thanks!

**Comment by jimhe** [comment]
Actually there's already a PR for 1.5.2 [here](https://github.com/Homebrew/homebrew-versions/pull/1115). I can submit a more generalized 1.5 if you prefer.

**Comment by dunn** [comment]
That'd be great!

**Comment by DomT4** [comment]
Closing here then.

**Pull request closed without merging**
