### PR TITLE
Git related improvement

### PR DESCRIPTION
**Pull request by xu-cheng**

### CODE REVIEW

**Comment by mikemcquaid** [comment]
:+1:. The only thing you might want to verify is if e.g. `git` is installed by Homebrew it can still get picked up after that.

**Comment by xu-cheng** [comment]
>  The only thing you might want to verify is if e.g. git is installed by Homebrew it can still get picked up after that.

Right, I almost forget this part.

**Comment by xu-cheng** [comment]
> The only thing you might want to verify is if e.g. git is installed by Homebrew it can still get picked up after that.

Fixed in https://github.com/Homebrew/homebrew/commit/540d61edfe8de16667de4eb72a777b449bbe9ea2

**Comment by mikemcquaid** [comment]
Bit hacky but I don't see a better approach :+1:

**Comment by xu-cheng** [comment]
I seems accidentally nuke my PR during rebase.

**Comment by xu-cheng** [comment]
resubmit one in #43693

**Pull request closed without merging**
