### PR TITLE
SwiftLint 0.1.2

### PR DESCRIPTION
**Pull request by jpsim**
Thanks!

### CODE REVIEW

**Comment by dunn** [comment]
Build failed for trying to write outside of the sandbox we run `brew` in: http://bot.brew.sh/job/Homebrew%20Pull%20Requests/32089/version=yosemite/testReport/junit/brew-test-bot/yosemite/install_swiftlint/

Not sure why it only happened on Yosemite, though.

**Comment by jpsim** [comment]
```
Couldn't update module cache session file '/Users/brew/Library/Developer/Xcode/DerivedData/ModuleCache/Session.modulevalidation': You don’t have permission to save the file “Session.modulevalidation” in the folder “ModuleCache”.
```

Why does Homebrew's CI prevent Xcode from writing to DerivedData? Seems overly prohibitive.

**Comment by DomT4** [comment]
> Not sure why it only happened on Yosemite, though.

There's a requirement in the formula for an Xcode that only Yosemite+ supports.

> Why does Homebrew's CI prevent Xcode from writing to DerivedData? Seems overly prohibitive.

Part of our sandbox. We've added the path to the whitelist for now. DerivedData is semi-problematic not only in terms of sandboxing but disk usage, but we can deal with it over time hopefully.

**Comment by dunn** [comment]
> There's a requirement in the formula for an Xcode that only Yosemite+ supports.

My brain's fried on account of the heat wave and I forgot Yosemite is the latest version.

**Comment by jpsim** [comment]
Thanks for the clarification and "fix" @DomT4! Since this is green, I assume it can be merged?

Could you please also re-run #43228 on CI since it failed for the same reason?

Thanks!

**Comment by DomT4** [comment]
> Since this is green, I assume it can be merged?

Yup! In https://github.com/Homebrew/homebrew/commit/0bca65c76693f2331ab6ebb0a72e9e1d0ab22ec8 :wink:.

Have re-queued the other PR as well. Thank you for your contribution to Homebrew, we appreciate it!

**Comment by jpsim** [comment]
:bow:

**Pull request closed without merging**
