### PR TITLE
git-annex 6.20160126

### PR DESCRIPTION
**Pull request by psibre**

### CODE REVIEW

**Comment by psibre** [comment]
Building on an i7 with `--jobs=4` took me over half an hour... no surprise that the CI builds run into the Travis time limit with `--jobs=2`.

**Comment by ilovezfs** [comment]
@psibre this PR is a duplicate. https://github.com/Homebrew/homebrew/pull/48514

**Comment by tdsmith** [comment]
Thanks for the PR! Deferring to the earlier one.

**Comment by psibre** [comment]
@tdsmith darn, I realize now that I forgot to clear the `is:issue` filter when I searched before doing this. my bad!

**Comment by tdsmith** [comment]
No worries!

**Pull request closed without merging**
