### PR TITLE
'brew man': abort if a formula is given

### PR DESCRIPTION
**Pull request by bfontaine**
I’m at work, this is a quick fix for #40735.

### CODE REVIEW

**Comment by xu-cheng** [comment]
I think we can just check whether `HOMEBREW_DEVELOPER` is set.

At the same time, this command requires more cares. Can you help to fix these problems as well?

* `ARGV.include?("--link") || ARGV.include?("-l")` can be replaced by `ARGV.flag? "--link"`
* Linking manpage should abort if `HOMEBREW_REPOSITORY` is the same as `HOMEBREW_PREFIX`.
* `brew man --server` is broken. Maybe just remove such feature.
* It would be nicer to replace `if  ... return end` structure to `if ... else ... end`.

**Comment by bfontaine** [comment]
Thanks @xu-cheng, I will look at all these when I’ll be home tonight.

**Comment by mikemcquaid** [comment]
> I think we can just check whether HOMEBREW_DEVELOPER is set.

I don't think we want to do this as this is something contributors use periodically.

**Comment by DomT4** [comment]
Yeah, I'd rather keep this available outside of `HOMEBREW_DEVELOPER`, even if we have to introduce logic to ensure people aren't passing arguments to the `brew man` command.

**Comment by bfontaine** [comment]
@Homebrew/owners any objection to the `--server` feature removal?

**Comment by mikemcquaid** [comment]
Makes sense to me; I almost removed it a few months ago.

**Comment by DomT4** [comment]
No objections. Kill it with :fire:.

**Comment by jacknagel** [comment]
Kill it

**Comment by jacknagel** [comment]
What does `--link` do, btw?

**Comment by bfontaine** [comment]
`--link` seems to be useful only if the Homebrew prefix is not the same directory as the git repository. Can this happen? I went back in the history and found the commit introducing `brew man` 5 years ago, dadcaee, and it already had this option.

**Comment by jacknagel** [comment]
Oh, that makes sense. That's a supported configuration.

**Comment by bfontaine** [comment]
Is everyone happy with this PR?

**Comment by DomT4** [comment]
LGTM :rocket:

**Comment by xu-cheng** [comment]
:+1:

**Comment by mikemcquaid** [comment]
:+1:

**Pull request closed without merging**
