### PR TITLE
Add includes/libraries for libebml and libmatroska to mkvtoolnix.rb

### PR DESCRIPTION
**Pull request by drewpc**
This fixes compile errors mentioned in issues #42480 and #41485

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Think the build issues may be fixed with https://github.com/Homebrew/homebrew/pull/44217

**Comment by sorentorp** [comment]
brew install --with-wxmac mkvtoolnix
==> Installing dependencies for mkvtoolnix: libebml, libmatroska
==> Installing mkvtoolnix dependency: libebml
==> Downloading https://homebrew.bintray.com/bottles/libebml-1.3.1.el_capitan.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/libebml-1.3.1.el_capitan.bottle.tar.gz
==> Pouring libebml-1.3.1.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/libebml/1.3.1: 33 files, 640K
==> Installing mkvtoolnix dependency: libmatroska
==> Downloading https://homebrew.bintray.com/bottles/libmatroska-1.4.2.el_capitan.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/libmatroska-1.4.2.el_capitan.bottle.tar.gz
==> Pouring libmatroska-1.4.2.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/libmatroska/1.4.2: 34 files, 1.6M
==> Installing mkvtoolnix
==> Downloading https://www.bunkus.org/videotools/mkvtoolnix/sources/mkvtoolnix-8.3.0.tar.xz
Already downloaded: /Library/Caches/Homebrew/mkvtoolnix-8.3.0.tar.xz
==> ./configure --prefix=/usr/local/Cellar/mkvtoolnix/8.3.0 --without-curl --with-boost=/usr/local/opt/boost --with-extra-includes=/usr/local/opt/libogg/includ
==> ./drake -j4
Last 15 lines from /Users/sorentorp/Library/Logs/Homebrew/mkvtoolnix/02.drake:
In file included from src/common/common.h:46:
In file included from /usr/local/opt/boost/include/boost/format.hpp:38:
In file included from /usr/local/opt/boost/include/boost/format/internals.hpp:20:
In file included from /usr/local/opt/boost/include/boost/optional.hpp:15:
/usr/local/opt/boost/include/boost/optional/optional.hpp:1254:53: warning: unused parameter 'out' [-Wunused-parameter]
operator<<(std::basic_ostream<CharType, CharTrait>& out, optional_detail::optional_tag const& v)
                                                    ^
/usr/local/opt/boost/include/boost/optional/optional.hpp:1254:95: warning: unused parameter 'v' [-Wunused-parameter]
operator<<(std::basic_ostream<CharType, CharTrait>& out, optional_detail::optional_tag const& v)
                                                                                              ^
In file included from src/common/common_pch.h:4:
src/common/common.h:68:10: fatal error: 'ebml/c/libebml_t.h' file not found
#include <ebml/c/libebml_t.h>
         ^
2 warnings and 1 error generated.

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
Add includes/libraries for libebml and libmatroska to mkvtoolnix.rb https://github.com/Homebrew/homebrew/pull/44152
Warning:

**Comment by mikemcquaid** [comment]
@BrewTestBot test this please

**Comment by drewpc** [comment]
I updated my branch with the latest changes from Homebrew and Travis is no longer complaining about build errors.  Hopefully this helps!

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
