### PR TITLE
docker 1.6.2

### PR DESCRIPTION
**Pull request by PikachuEXE**
Haven't updated boot2docker though

### CODE REVIEW

**Comment by mikemcquaid** [comment]
> Haven't updated boot2docker though

Please do that or we can't merge this. Thanks!

**Comment by PikachuEXE** [comment]
`brew install fig` failed

**Comment by DomT4** [comment]
It tried to download a bottle which hadn't yet been generated, which caused the failure:

```
==> Installing fig dependency: boot2docker
==> Downloading https://homebrew.bintray.com/bottles/boot2docker-1.6.2.mavericks.bottle.tar.gz
Error: Failed to download resource "boot2docker"
Download failed: https://homebrew.bintray.com/bottles/boot2docker-1.6.2.mavericks.bottle.tar.gz
```

**Comment by PikachuEXE** [comment]
Force push to restart build?

**Comment by DomT4** [comment]
It'll happen again. Let Mike look at it in the morning before trying anything else.

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

For future reference please only change one formula per commit.

**Comment by PikachuEXE** [comment]
Well
`Haven't updated boot2docker though`
`Please do that or we can't merge this. Thanks!`
I am so confused now :P

**Comment by mikemcquaid** [comment]
Sorry, it's good to change them both but ideally we'll have one commit per formula so two commits in a single pull-request.

**Comment by PikachuEXE** [comment]
OK I see in [pull request guide](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-%28and-get-it-merged%29.md#how-to-open-a-homebrew-pull-request-and-get-it-merged):
`Squash new commits into one change per formula with git rebase --interactive origin/master`
Maybe use `one commit per formula` to replace `one change per formula`?

**Comment by mikemcquaid** [comment]
:+1:

**Comment by mikemcquaid** [comment]
Done in https://github.com/Homebrew/homebrew/commit/4d90dd961aedcaf05aab704a05117efa7929e58e.

**Pull request closed without merging**
