### PR TITLE
rust 1.2.0

### PR DESCRIPTION
**Pull request by dhda**

### CODE REVIEW

**Comment by DomT4** [comment]
Thanks for the submission!

I've kicked this off the build queue for now. Our CI is currently very backed up and the timeout is at the regular ~60 minute mark, which Rust will hit. Once the queue has calmed a little one of us will bump the timeout to several hours and reschedule it. Shouldn't be any later than the morning :).

**Comment by DomT4** [comment]
@BrewTestBot test this please

**Comment by DomT4** [comment]
Slightly odd failure on Mavericks here:

```
circular_raw_ostream.o" "r-LLVMSupport-raw_os_ostream.o" "r-LLVMSupport-raw_ostream.o" "r-LLVMSupport-regcomp.o" "r-LLVMSupport-regerror.o" "r-LLVMSupport-regexec.o" "r-LLVMSupport-regfree.o" "r-LLVMSupport-regstrlcpy.o" failed with: exit code: 1
note: stdout ---

note: stderr ---
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: /private/tmp/rust20150808-77251-6wtcn9/rustc-1.2.0/x86_64-apple-darwin/stage0/lib/rustlib/x86_64-apple-darwin/lib/librustc_llvm-62abc69f.rlib is not an archive
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar: internal ranlib command failed

error: aborting due to previous error
```

**Comment by dtrebbien** [comment]
This patch worked for me running Mac OS 10.10.4.  It took 32.8 minutes on a 2.3 GHz Core i7 with 16 GiB of RAM.

Completely speculating:  I wonder if the "librustc_llvm-62abc69f.rlib is not an archive" error is due to a memory use cap.  Perhaps the archiver hit the memory limit, which caused the output to be truncated/corrupted.

**Comment by dhda** [comment]
@dtrebbien That seems possible. From the [Rust docs](https://github.com/rust-lang/rust/blob/master/README.md):

> Rust currently needs about 1.5 GiB of RAM to build without swapping; if it hits swap, it will take a very long time to build.

@DomT4 How much memory are the Jenkins nodes configured with? I'm skeptical that this would cause a failure only on Mavericks, but I could see it happening if the memory usage was right on the edge.

**Comment by DomT4** [comment]
CC @mikemcquaid 

Is anyone here still running Mavericks? If you could try a local build if you are, and let us know how that goes, we'd appreciate that.

**Comment by johnjelinek** [comment]
```
==> Downloading https://static.rust-lang.org/dist/rustc-1.2.0-src.tar.gz
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/rust/1.2.0 --enable-clang --release-channel=stable
==> make



error: aborting due to previous error
make: *** [x86_64-apple-darwin/stage2/lib/rustlib/x86_64-apple-darwin/lib/stamp.rustc_driver] Error 101

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
rust 1.2.0 https://github.com/Homebrew/homebrew/pull/42642
```

**Comment by dtrebbien** [comment]
@johnjelinek What do the logs in `~/Library/Logs/Homebrew/rust` say the error was?

**Comment by johnjelinek** [comment]
oh ... lol:
```
Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.



error: aborting due to previous error
make: *** [x86_64-apple-darwin/stage2/lib/rustlib/x86_64-apple-darwin/lib/stamp.rustc_driver] Error 101
```

**Comment by mikemcquaid** [comment]
I'm afraid I've no idea here. The Mavericks VM has 10GB of RAM. The only thought is that perhaps it's using too many make jobs and `ENV.j1` might fix it? I'm triggering another rebuild now just in case.

**Comment by DomT4** [comment]
Died in the same way. May need to consult upstream on this.

**Comment by dhda** [comment]
The error is different this time:

```
error: failed to write /var/folders/_z/11_kwl954xvch_n92gnzdjzw0000gp/T/rustc.6OPc2O6nOsbL/rust.metadata.bin: No space left on device (os error 28)
make: *** [x86_64-apple-darwin/stage1/lib/rustlib/x86_64-apple-darwin/lib/stamp.rustc] Error 101
```

The Mountain Lion build is also failing, with what looks like a Homebrew error:

```
==> git checkout 5a98bb2						 PASSED
==> brew pull --clean https://github.com/Homebrew/homebrew/pull/42642	 PASSED
==> brew doctor								 PASSED
==> brew --env								 PASSED
==> brew config								 PASSED
==> brew tests								 PASSED
==> brew tests --no-compat						 PASSED
==> brew readall							 PASSED
==> brew uses rust							 PASSED
==> brew fetch --retry cmake git makedepend openssl pkg-config		 PASSED
==> brew fetch --retry --build-bottle --force rust			 PASSED
==> brew install --only-dependencies --verbose --build-bottle rust	 PASSED
==> brew install --verbose --build-bottle rust				 PASSED
==> brew audit rust							 PASSED
==> brew bottle --verbose --rb rust					 FAILED
Error: Formula not installed or up-to-date: rust
==> brew test --verbose rust						 FAILED
Error: Testing requires the latest version of rust
```

**Comment by felixbuenemann** [comment]
I monitored resource usage during install on El Cap 10.11 Beta (15A244d) and top memory usage reported by `/usr/bin/time -l` was 1GB RSS and disk usage inside `/private/tmp/rust20150812-85404-1gd2bn7`topped out at 2GB during make install of rust. Compilation of rust took 40min on a dual core i7-5557U 3.1GHz w/16GB RAM (13" rMBP 2015).

However for me make of cargo failed with the following error:
```
==> Downloading https://static-rust-lang-org.s3.amazonaws.com/cargo-dist/2015-08-07/cargo-nightly-x86_64-apple-darwin.ta
==> ./install.sh --prefix=/private/tmp/rust--cargo20150812-85404-ev1v22/target/snapshot/cargo
==> ./configure --prefix=/usr/local/Cellar/rust/1.2.0 --local-rust-root=/private/tmp/rust--cargo20150812-85404-ev1v22/ru
==> make
"/private/tmp/rust--cargo20150812-85404-ev1v22/rustc/bin/rustc" -V
dyld: Library not loaded: x86_64-apple-darwin/stage1/lib/rustlib/x86_64-apple-darwin/lib/librustc_driver-35017696.dylib
  Referenced from: /private/tmp/rust--cargo20150812-85404-ev1v22/rustc/bin/rustc
  Reason: image not found
make: *** [cargo-x86_64-apple-darwin] Trace/BPT trap: 5
```

**Comment by felixbuenemann** [comment]
The above mentioned error seem to be cause by a mismatch in the library path of rustc:
```
% "/usr/local/Cellar/rust/1.2.0/bin/rustc" -V
dyld: Library not loaded: x86_64-apple-darwin/stage1/lib/rustlib/x86_64-apple-darwin/lib/librustc_driver-62abc69f.dylib
  Referenced from: /usr/local/Cellar/rust/1.2.0/bin/rustc
  Reason: image not found
zsh: trace trap  "/usr/local/Cellar/rust/1.2.0/bin/rustc" -V
couchbook% otool -L /usr/local/Cellar/rust/1.2.0/bin/rustc
/usr/local/Cellar/rust/1.2.0/bin/rustc:
	x86_64-apple-darwin/stage1/lib/rustlib/x86_64-apple-darwin/lib/librustc_driver-62abc69f.dylib (compatibility version 0.0.0, current version 0.0.0)
…
% find /usr/local/Cellar/rust/1.2.0 -type f -name librustc_driver-62abc69f.dylib
/usr/local/Cellar/rust/1.2.0/lib/librustc_driver-62abc69f.dylib
/usr/local/Cellar/rust/1.2.0/lib/rustlib/x86_64-apple-darwin/lib/librustc_driver-62abc69f.dylib
```

I'll try rebuilding with `--disable-rpath` to see if that helps.

**Comment by mistydemeo** [comment]
What's the `otool -L` output for `rustc`?

**Comment by felixbuenemann** [comment]
@mistydemeo It's shown above, I only truncated it after the first line.

**Comment by felixbuenemann** [comment]
Btw. I found this formula for installing rust nightlies and it's using install_name_tool to fix the lib paths in rustc and rustdoc. So I am probably running into the same issue fixed there.

**Comment by felixbuenemann** [comment]
Enabling `--disable-rpath` did not make a difference.

@mistydemeo Here's the full output from `otool -L`:
```
% otool -L /usr/local/Cellar/rust/1.2.0/bin/rustc
/usr/local/Cellar/rust/1.2.0/bin/rustc:
	x86_64-apple-darwin/stage1/lib/rustlib/x86_64-apple-darwin/lib/librustc_driver-62abc69f.dylib (compatibility version 0.0.0, current version 0.0.0)
	x86_64-apple-darwin/stage1/lib/rustlib/x86_64-apple-darwin/lib/librustc_trans-62abc69f.dylib (compatibility version 0.0.0, current version 0.0.0)
	x86_64-apple-darwin/stage1/lib/rustlib/x86_64-apple-darwin/lib/librustc_privacy-62abc69f.dylib (compatibility version 0.0.0, current version 0.0.0)
	x86_64-apple-darwin/stage1/lib/rustlib/x86_64-apple-darwin/lib/librustc_borrowck-62abc69f.dylib (compatibility version 0.0.0, current version 0.0.0)
	x86_64-apple-darwin/stage1/lib/rustlib/x86_64-apple-darwin/lib/librustc_resolve-62abc69f.dylib (compatibility version 0.0.0, current version 0.0.0)
	x86_64-apple-darwin/stage1/lib/rustlib/x86_64-apple-darwin/lib/librustc_lint-62abc69f.dylib (compatibility version 0.0.0, current version 0.0.0)
	x86_64-apple-darwin/stage1/lib/rustlib/x86_64-apple-darwin/lib/librustc_typeck-62abc69f.dylib (compatibility version 0.0.0, current version 0.0.0)
	x86_64-apple-darwin/stage1/lib/rustlib/x86_64-apple-darwin/lib/librustc-62abc69f.dylib (compatibility version 0.0.0, current version 0.0.0)
	x86_64-apple-darwin/stage1/lib/rustlib/x86_64-apple-darwin/lib/libflate-62abc69f.dylib (compatibility version 0.0.0, current version 0.0.0)
	x86_64-apple-darwin/stage1/lib/rustlib/x86_64-apple-darwin/lib/librustc_data_structures-62abc69f.dylib (compatibility version 0.0.0, current version 0.0.0)
	x86_64-apple-darwin/stage1/lib/rustlib/x86_64-apple-darwin/lib/libarena-62abc69f.dylib (compatibility version 0.0.0, current version 0.0.0)
	x86_64-apple-darwin/stage1/lib/rustlib/x86_64-apple-darwin/lib/libgraphviz-62abc69f.dylib (compatibility version 0.0.0, current version 0.0.0)
	x86_64-apple-darwin/stage1/lib/rustlib/x86_64-apple-darwin/lib/libgetopts-62abc69f.dylib (compatibility version 0.0.0, current version 0.0.0)
	x86_64-apple-darwin/stage1/lib/rustlib/x86_64-apple-darwin/lib/librbml-62abc69f.dylib (compatibility version 0.0.0, current version 0.0.0)
	x86_64-apple-darwin/stage1/lib/rustlib/x86_64-apple-darwin/lib/librustc_back-62abc69f.dylib (compatibility version 0.0.0, current version 0.0.0)
	x86_64-apple-darwin/stage1/lib/rustlib/x86_64-apple-darwin/lib/libsyntax-62abc69f.dylib (compatibility version 0.0.0, current version 0.0.0)
	x86_64-apple-darwin/stage1/lib/rustlib/x86_64-apple-darwin/lib/libserialize-62abc69f.dylib (compatibility version 0.0.0, current version 0.0.0)
	x86_64-apple-darwin/stage1/lib/rustlib/x86_64-apple-darwin/lib/libterm-62abc69f.dylib (compatibility version 0.0.0, current version 0.0.0)
	x86_64-apple-darwin/stage1/lib/rustlib/x86_64-apple-darwin/lib/liblog-62abc69f.dylib (compatibility version 0.0.0, current version 0.0.0)
	x86_64-apple-darwin/stage1/lib/rustlib/x86_64-apple-darwin/lib/libfmt_macros-62abc69f.dylib (compatibility version 0.0.0, current version 0.0.0)
	x86_64-apple-darwin/stage1/lib/rustlib/x86_64-apple-darwin/lib/librustc_llvm-62abc69f.dylib (compatibility version 0.0.0, current version 0.0.0)
	x86_64-apple-darwin/stage1/lib/rustlib/x86_64-apple-darwin/lib/libstd-62abc69f.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1225.0.0)
	/usr/lib/libedit.3.dylib (compatibility version 2.0.0, current version 3.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.1.0)
```

**Comment by felixbuenemann** [comment]
Btw. I've checked how [multirust](https://github.com/brson/multirust) handles this and it simply sets the DYLD_LIBRARY_PATH to the path containing the rust libs (eg. "/Users/felix/.multirust/toolchains/stable/lib").

**Comment by felixbuenemann** [comment]
@mistydemeo I can successfully run rust if I comment out the complete cargo resource. I noticed that homebrew fixes the install name automatically at the end of the install. The problem seems to be that the cargo resource tries to run rustc before it has been fixed.

I think much of the formulas complexity could be removed if cargo was a standalone package instead of a resource.

**Comment by felixbuenemann** [comment]
I seem to be running into an El Capitan specific security "feature" where the [DYLD_LIBRARY_PATH gets unset by Mac OS X](https://forums.developer.apple.com/message/31148). The only way I found to work around this so far ist to set the DYLD_LIBRARY_PATH in a shellscript wrapper for rustc.

From my tests it is no longer possible to export DYLD_LIBRARY_PATH into child processes, at least if rootless mode is enabled, which is the default.

Example:
```bash
cat foo
#!/bin/bash
export DYLD_LIBRARY_PATH=foo
echo foo DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH
echo "calling bar"
./bar

cat bar
#!/bin/bash
echo bar DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH

./foo
foo DYLD_LIBRARY_PATH=foo
calling bar
bar DYLD_LIBRARY_PATH=
```

**Comment by felixbuenemann** [comment]
This PR can be closed, because #42872 has been merged.

@dhda Thanks for the initial work!

**Pull request closed without merging**
