### PR TITLE
Add 2.1.5 devel(beta) version & Fix sha1 to sha256 

### PR DESCRIPTION
**Pull request by zchee**
Signed-off-by: Koichi Shiraishi <zcheeee@gmail.com>

### CODE REVIEW

**Comment by mikemcquaid** [comment]
There's an audit failure: http://bot.brew.sh/job/Homebrew%20Pull%20Requests/30016/version=yosemite/testReport/junit/brew-test-bot/yosemite/audit___devel_libevent/

**Comment by DomT4** [comment]
@BrewTestBot test this please

**Comment by DomT4** [comment]
```
Error: 2 problems in 1 formula
libevent:
 * Devel: Use https://downloads.sourceforge.net to get geolocation (url is https://sourceforge.net/projects/levent/files/libevent/libevent-2.1/libevent-2.1.5-beta.tar.gz).
 * 13: Trailing whitespace was found
```

**Comment by DomT4** [comment]
Closing as dead. Feel free to address the comments resubmit this fresh if still interested. Thanks for the submission!

**Comment by zchee** [comment]
@mikemcquaid @DomT4 
Hi!
Sorry, super late reply...
I do not check this PR :scream:

After all, what was wrong?

**Comment by DomT4** [comment]
You need to use a:
```
url "https://downloads.sourceforge.net/project/levent/libevent/
```
style URL rather than `https://sourceforge.net/projects/levent/files` style URL. Feel free to resubmit a fresh PR on that, if you'd like to.

**Pull request closed without merging**
