### PR TITLE
bashmarks new formula

### PR DESCRIPTION
**Pull request by alexandregz**
I put 1.0 to version because software doesn't have

### CODE REVIEW

**Comment by mistydemeo** [comment]
We don't accept software without stable versions in this repository, sorry. You can resubmit to [homebrew-headonly](https://github.com/Homebrew/homebrew-headonly/) or request that the developers add a stable version. Thanks!

**Comment by alexandregz** [comment]
I'm think that I have not explained well, software are unversioned but is stable, it's a bash script and have two/three years, I don't know exactly. Only I put number version just to audit formula.

**Comment by mistydemeo** [comment]
I understand that, but we don't accept unversioned software in this repository. If it's stable, you could request a tag from the author.

**Comment by alexandregz** [comment]
Ups, sorry, you're right :smile:

**Comment by huyng** [comment]
Hey I'm the author of that repo. I'll add a tag for 1.0, can we get this reopened?

**Comment by alexandregz** [comment]
hey @huyng , you can add tag and I (or just you) can put another PR here :smile:

**Comment by mistydemeo** [comment]
I can reopen if @alexandregz is interested in updating this PR to use the new tarball, otherwise someone can submit a new one. Thank you!

**Comment by alexandregz** [comment]
I'ts fine for me

**Comment by andrioli** [comment]
@huyng where is the tag? I'm missing `brew install bashmarks` :smile:

**Comment by alexandregz** [comment]
@andrioli to instal you can tap https://github.com/alexandregz/homebrew-MXhomebrew.

But yep, I'm just waiting to tag from @huyng :smile:

**Pull request closed without merging**
