### PR TITLE
ec2-ami-tools: delete JAVA_HOME, formula is ruby based

### PR DESCRIPTION
**Pull request by vszakats**

### CODE REVIEW

**Comment by vszakats** [comment]
In the light of https://github.com/Homebrew/homebrew/pull/37187, this patch should most probably be cancelled to keep these formulae in sync with each other.

**Comment by vszakats** [comment]
Doing some tests... pls hold off the merge.

**Comment by vszakats** [comment]
`JAVA_HOME` not needed in `test` indeed.

**Comment by xu-cheng** [comment]
Close this as I will do some major change on AmazonWebServicesFormula in #37192.

Thanks for contribution @vszakats.

**Pull request closed without merging**
