### PR TITLE
mongodb 2.6.7

### PR DESCRIPTION
**Pull request by ehershey**

### CODE REVIEW

**Comment by junjielee** [comment]
how to install? is it "brew install mongoldb==2.6.7"?

**Comment by bfontaine** [comment]
@junjielee just use `brew update && brew install mongodb`, or if you already have it, `brew update && brew upgrade mongodb`.

**Comment by junjielee** [comment]
@bfontaine but I used `brew install mongodb`, it would install mongodb with version 3.x. how do I use `brew install` to install version 2.6.7 or other version? thanks

**Comment by DomT4** [comment]
^ `brew tap homebrew/versions && brew install mongodb26`.

**Pull request closed without merging**
