### PR TITLE
New formula: afew 0.0.0

### PR DESCRIPTION
**Pull request by benjaminfrank**
afew is an initial tagging script for notmuch mail. Afew does not
provide tags/releases, therefore I took commit
162d9fa00ba09892bd8d63ec9fa182e0319000a2 and called the version
artificially 0.0.0
I ask upstream to do proper tags/releases.

### CODE REVIEW

**Comment by bfontaine** [comment]
It’s probably better to have this in head-only until upstream provides stable releases.

**Comment by benjaminfrank** [comment]
Does homebrew offer something to signal that a new "head" version exists, like an internal version number that I could bump whenever new commits come in?

**Comment by bfontaine** [comment]
> Does homebrew offer something to signal that a new "head" version exists

It supports `HEAD` URLs, which it’ll use to pull the changes as they come.

**Comment by benjaminfrank** [comment]
But subsequent brew updates would not check if the head changed, right? So an explicit remove/install would be required to "update" a head-only formula. 
What I was thinking of is more like an internal version for a head formula such that I could bump the formula and a upgrad/update would fetch the "new" head.

**Comment by DomT4** [comment]
> But subsequent brew updates would not check if the head changed, right?

Correct.

> So an explicit remove/install would be required to "update" a head-only formula. 

Correct.

> What I was thinking of is more like an internal version for a head formula such that I could bump the formula and a upgrad/update would fetch the "new" head.

We don't have anything like this, because obviously depending on when you clone the `HEAD` formula you won't have installed the same "version". It can be done with `revision` (commit) usage, but then it isn't really `head-only` or stable.

**Comment by benjaminfrank** [comment]
if this is now head-only, do i need to open a new PR in homebrew-head-only?

**Comment by mikemcquaid** [comment]
Yeh, sorry.

**Comment by benjaminfrank** [comment]
Moving over to hombrew-head-only.

**Pull request closed without merging**
