### PR TITLE
Upgrade setuptools to 11.0 and pip to 6.0.6

### PR DESCRIPTION
**Pull request by dstufft**

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Will let @tdsmith (our resident Python expert) make the call here.

**Comment by dstufft** [comment]
Yea no worries! I figured I'd send it now since it's early morning and I know @tdsmith has said doing pypy/pypy3 updates off hours is best since they take a long time to build and take up build farm time.

**Comment by mikemcquaid** [comment]
Stopped this build as it was blocking the bot.

**Comment by dstufft** [comment]
Ha, I Thought doing it at 5am would help make it not be intrusive ;(

**Comment by mikemcquaid** [comment]
Timezones :grinning:

**Comment by tdsmith** [comment]
(In the absence of true badness I'd be happy updating pypy/3 less often than python/3, since the pypy packages are less popular and pypy users probably have greater python clue.)

**Comment by dstufft** [comment]
pip 6.0.4 fixes a number of exceptions that happen if you use ``-v`` but more importantly it includes a change to PEP 440 that fixes an issue that people were having with what we defined ``>`` as.

The things that I think are probably important:

* Fix an issue where using -v would cause an exception saying ``TypeError: not all arguments converted during string formatting``.

**Comment by dstufft** [comment]
Bleh @ Github for submitting my thing instead of inserting a newline, added more things to the above post.

**Comment by tdsmith** [comment]
Sounds good; I'll fire this off again next I find a quiet moment on the build bot.

My standard for badness is probably whether pypy users can upgrade pip themselves, though. :)

**Comment by dstufft** [comment]
Hah, well they can do that since none of the actual broken-ness prevents it entirely, you just can't use ``-v`` sometimes. The PEP 440 thing is the one I care the most about since that changes the meaning of ``>`` and ``<``.

**Comment by tdsmith** [comment]
Superseded by #35618.

**Pull request closed without merging**
