### PR TITLE
eot-utils: test added

### PR DESCRIPTION
**Pull request by bfontaine**

### CODE REVIEW

**Comment by vszakats** [comment]
Hi @bfontaine, I'd suggest https for `homepage` and `url`. Strangely both are currently redirected to plaintext version, the `url` with code `307 temporary redirect`. Anyhow I think it's a step up.

**Comment by bfontaine** [comment]
Done.

**Comment by vszakats** [comment]
Thanks!

**Comment by tdsmith** [comment]
Thanks Baptiste!

**Pull request closed without merging**
