### PR TITLE
dupx: evict to boneyard

### PR DESCRIPTION
**Pull request by L2G**

### CODE REVIEW

**Comment by L2G** [comment]
Can someone shine some light on what Jenkins is running into here?

**Comment by tdsmith** [comment]
There's no gdb in core.

**Comment by L2G** [comment]
Is there a gdb somewhere? Because I have a /usr/local/bin/gdb on my system linked to /usr/local/Cellar/gdb/7.9/bin/gdb. For the life of me I can't remember where that would have come from if not from core or at least a tap…

**Comment by xu-cheng** [comment]
There is gdb in `homebrew/dupes`. However, we don't allow mandatory cross tap dependency in the core formula.

**Comment by L2G** [comment]
I understand. It was just driving me crazy that I couldn't remember where it came from.

**Comment by L2G** [comment]
But that raises another question… why is it in homebrew/dupes if it's not present in OS X? (Or is it present in versions other than Mavericks?)

**Comment by xu-cheng** [comment]
In OS X, we should use lldb.

**Comment by xu-cheng** [comment]
> It was just driving me crazy that I couldn't remember where it came from.

You could run `brew info gdb` to check the origin.

**Comment by L2G** [comment]
> You could run `brew info gdb` to check the origin.

…which was giving me nothing, which was why it was driving me crazy.

**Comment by L2G** [comment]
The configure script says:

> configure: error: gdb is not in the path, this utility requires GDB

…so maybe dupx should just be thrown to the boneyard.

**Comment by L2G** [comment]
https://github.com/Homebrew/homebrew-boneyard/pull/47

**Comment by L2G** [comment]
Ping.

**Comment by L2G** [comment]
@mikemcquaid Thanks. I see this was added to the boneyard, but I don't think the removal from core has happened yet…?

**Comment by mikemcquaid** [comment]
Whoops, done in 9f95d11.

**Pull request closed without merging**
