### PR TITLE
Update bbe.rb

### PR DESCRIPTION
**Pull request by zedtux**
The homepage (http://bbe-.sourceforge.net) isn't reachable (getaddrinfo: Name or service not known)

### CODE REVIEW

**Comment by bfontaine** [comment]
Thanks again @zedtux! :smile:

**Comment by zedtux** [comment]
@bfontaine and thanks to you for your message of yesterday and your merges of today. As I'm the http://brewformulas.org author, I'm the right guy to tell what URL are broken or not so don't get me as a broken URL maniac guy ;-)

**Comment by bfontaine** [comment]
Thank you for making brewformulas.org :smiley: 
You might be interested by this if you want to list the executables installed by any formula: https://github.com/Homebrew/homebrew-command-not-found/blob/master/executables.txt

**Comment by zedtux** [comment]
Awesome ! I will make something with that information. Thanks

**Pull request closed without merging**
