### PR TITLE
x265 1.8

### PR DESCRIPTION
**Pull request by nijikon**

### CODE REVIEW

**Comment by dunn** [comment]
Thanks again! Merged in 759ff42e005b5fac29923d68d510ad1cecb07318.

**Comment by gaming-hacker** [comment]
anyone gotten this to build with --HEAD adn 16-bit?

**Comment by dunn** [comment]
If `--with-16-bit` works with the stable build, then it's probably an upstream issue that the developers should hear about!

**Comment by gaming-hacker** [comment]
well i'm not quite sure yet
in the homebrew formula i specificied --with-16-bit 
cmake source -DHIGH_BIT_DEPTH=ON
4.0M Dec 30 12:49 libx265.79.dylib*
4.6M Dec 30 12:49 libx265.a
102K Dec 30 12:49 x265*

where on the x265 page, it says to drill down and run this batch file

 ffmpeg and the x265 CLI which use our bit-depth introspection API (x265_api_get) instead of the globally exported C interface can select between 8 and 10bit libx265 libraries at runtime.
For linux/Mac, you can use or adapt the build/linux/multilib.sh
this produces
8bit 10bit 12bit libs with x265
14M Dec 30 12:46 libx265.a
4.4M Dec 30 12:46 libx265_main.a
102K Dec 30 12:46 x265*
12bit/ 4.6M Dec 30 12:45 libx265.a
10bit/4.7M Dec 30 12:46 libx265.a

**Comment by dunn** [comment]
Oh, maybe there are some more files we should be installing.  Interested in opening a pull request to fix that? Take a look at https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md and let us know if you have questions!

**Pull request closed without merging**
