### PR TITLE
use HOMEBREW_SOURCEFORGE_MIRROR only when HOMEBREW_SOURCEFORGE_TESTING is set

### PR DESCRIPTION
**Pull request by xu-cheng**

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Honestly I don't think it's worth changing this for now as I'm going to tear out all the SourceForge stuff very shortly (possibly this weekend).

**Comment by xu-cheng** [comment]
I understand this. However, the existing users who set HOMEBREW_SOURCEFORGE_MIRROR already may experience unpredict behavior.

**Comment by mikemcquaid** [comment]
Made a more comprehensive cleanup in https://github.com/Homebrew/homebrew/pull/37213.

**Comment by xu-cheng** [comment]
Sweat.

**Pull request closed without merging**
