### PR TITLE
spidermonkey 31.5.0

### PR DESCRIPTION
**Pull request by dholm**

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Failing on 10.8: http://bot.brew.sh/job/Homebrew%20Pull%20Requests/24094/version=mountain_lion/testReport/junit/brew-test-bot/mountain_lion/install_spidermonkey/

**Comment by jedireza** [comment]
:sparkles: ping :sparkles:

**Comment by mikemcquaid** [comment]
@jedireza consider making your own PR with the issues mentioned here fixed.

**Comment by DomT4** [comment]
Ping. Welcome either progress on this PR or a new PR entirely.

**Comment by jedireza** [comment]
Apologies for the delayed response. I'd be happy to help, but I don't know much out creating/updating homebrew formulas. I originally hoped this would be a simple url change. If I have more time I'll look into this in more detail.

@dholm are you willing to help finish this off?

**Comment by mikemcquaid** [comment]
@jedireza This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by DomT4** [comment]
Closing as dead here. Welcome a new PR.

**Pull request closed without merging**
