### PR TITLE
neo4j 2.3.2

### PR DESCRIPTION
**Pull request by mindrones**

### CODE REVIEW

**Comment by DomT4** [comment]
It doesn't like the checksum here:
```
==> Downloading http://dist.neo4j.org/neo4j-community-2.3.1-unix.tar.gz
Warning: Formula reports different SHA256: 37e24d95c914c54d5cbbe99473d4beef89da78adb2db04eb87258a489225932a
Downloaded to: /Library/Caches/Homebrew/neo4j-2.3.2.tar.gz
SHA1: 3e714073dad1f4ad04dc3e879a96798140623d31
SHA256: 7b2f30d73af107eacd9a3a619475ef448a08eecb2cdb42ab1f8a38d091c70ecb
```

**Comment by DomT4** [comment]
Oh, I see why. You forgot to update the URL :wink:

**Comment by mindrones** [comment]
@DomT4 Ooops, you're right, fixed! Sorry for the noise :)

**Comment by DomT4** [comment]
Heh, no worries! I'm always happier with simple mistakes than having to chase upstreams around to find out why the SHA256 is wrong.

Merged in https://github.com/Homebrew/homebrew/commit/4965a6c45339ea84f152bf2a28bf02d6f1e03b2d. Thank you for another contribution to Homebrew @mindrones! :smiley_cat:

**Pull request closed without merging**
