### PR TITLE
ssdb 1.9.2

### PR DESCRIPTION
**Pull request by felixbuenemann**
* Update to 1.9.2
* Patch and install ssdb-cli
* Separate data directory for ssdb slave
* Fix ssdb-ins.sh script

### CODE REVIEW

**Comment by felixbuenemann** [comment]
Swapped back some lines, to make the diff more readable.

**Comment by felixbuenemann** [comment]
Hmm, the ssdb-ins.sh is still broken, I think it doesn't make sense to include it, because it's basically a SysV init script. I only kept it because it was in the previous release.

**Comment by dunn** [comment]
Have these patches been reported upstream?

**Comment by felixbuenemann** [comment]
I don't really think it makes sense, because the patches adjust for the changes in directory structure done  by the formula itself. The ssdb-ins.sh could probably be changed upstream to be able to work with both relative and absolute pidfile paths, but that still leaves the difference in the bin path.

**Comment by dunn** [comment]
Since there's a `make` step, shouldn't that be configurable?

**Comment by felixbuenemann** [comment]
The ssdb-ins.sh file is not generated by make.

**Comment by felixbuenemann** [comment]
@dunn I agree that the amount of patching required to get this package to work fine with homebrews directory structure is a bit unhealthy and I'd be preferable to have the upstream build system improved to accommodate for that, but I really don't have the time to do that right now. So maybe we could live with the patches for the time being?

**Comment by mikemcquaid** [comment]
@dunn Doesn't look too bad to me but feel free to disagree.

**Comment by dunn** [comment]
@BrewTestBot test this please

**Comment by dunn** [comment]
Right-o. Merged in 779726ab031c9dcaae782329f68e3e8a69459176, thank you @felixbuenemann!

**Comment by felixbuenemann** [comment]
Thanks, Alex!

**Pull request closed without merging**
