### PR TITLE
Silently ignore FormulaUnavailableError in check_conflicts

### PR DESCRIPTION
**Pull request by xu-cheng**

### CODE REVIEW

**Comment by mikemcquaid** [comment]
What's the use-case for this e.g. a formula with this problem?

**Comment by xu-cheng** [comment]
I'm working on a x11 free versioned of [`xpdf`](https://github.com/Homebrew/homebrew-x11/blob/master/xpdf.rb). If I don't tap `homebrew/x11`, it will error out during the installation(as it conflicted with other formulae with `homebrew/x11`).

```
$ brew install xpdf-tools
Error: No available formula for pdf2image
Searching formulae...
Searching taps...
homebrew/x11/pdf2image
```

In fact, it will happen for all formulae who have cross-tap conflict list.

**Comment by mikemcquaid** [comment]
What happens if you use a fully-qualified name with the `conflicts_with`?

**Comment by xu-cheng** [comment]
Same error.

**Comment by mikemcquaid** [comment]
Ok. I think it shouldn't fail for a fully-qualified name but should for an unqualified one.

**Comment by xu-cheng** [comment]
Ok to merge this?

**Comment by mikemcquaid** [comment]
If this fails for an unqualified name but fixes the tap case: :+1:.

**Comment by xu-cheng** [comment]
> If this fails for an unqualified name but fixes the tap case: :+1:.

While, this PR makes both cases fixed. I will tweak a bit to fix only full-qualified name.

**Comment by mikemcquaid** [comment]
Thanks!

**Comment by xu-cheng** [comment]
Updated.

**Comment by mikemcquaid** [comment]
:+1:

**Comment by chdiza** [comment]
This same issue happens when doing `brew audit`.  E.g., I have a local copy of the `pdf2image` formula, which a while back was moved off to the X11 tap.  If I do `brew audit pdf2image.rb`, I get:
```
pdf2image:
 * Can't find conflicting formula "homebrew/homebrew-x11/xpdf".

Error: 1 problems in 1 formulae
```
I don't see why I should have to have the conflicting thing actually tapped in order to avoid an error message.

**Comment by xu-cheng** [comment]
@chdiza Can you submit a PR similar to this one? Thanks.

**Pull request closed without merging**
