### PR TITLE
syncthing 0.11.0

### PR DESCRIPTION
**Pull request by DomT4**
Bump.

We may want to hold off on merging this for a few days.

**NOT COMPATIBLE WITH THE 0.10.x RELEASE BRANCH. See:**
https://forum.syncthing.net/t/syncthing-v0-11-0-release-notes/2426

### CODE REVIEW

**Comment by jalada** [comment]
:+1:

**Comment by canton7** [comment]
Can we upgrade to 0.11 now, but offer a syncthing-0.10 package for those wishing to stay on 0.10?

A lot of other package managers are upgrading to 0.11 about now, and you need to be able to upgrade your whole network at once.

**Comment by xu-cheng** [comment]
@DomT4 we should put syncthing 0.10 to homebrew/version.

**Comment by DomT4** [comment]
Agreed. Happy to supply 0.10.x in Versions. If someone wants to tee up a PR in Homebrew/versions to add Syncthing v0.10.x, that'd be great. Otherwise I'll get around to it this evening.

**Comment by mikemcquaid** [comment]
Thanks again @DomT4!

**Comment by DomT4** [comment]
010 pending in Versions here: https://github.com/Homebrew/homebrew-versions/pull/785

I understand there's possibly to be at least one more maintenance release; if someone could watch out for that and bump the formula when it happens, I'd be appreciative.

**Pull request closed without merging**
