### PR TITLE
checkstyle: 6.2

### PR DESCRIPTION
**Pull request by robsonpeixoto**

### CODE REVIEW

**Comment by DomT4** [comment]
The SHA is off apparently:

```
==> Downloading https://downloads.sourceforge.net/project/checkstyle/checkstyle/6.2/checkstyle-6.2-bin.tar.gz
Already downloaded: /Library/Caches/Homebrew/checkstyle-6.2.tar.gz
==> Verifying checkstyle-6.2.tar.gz checksum
Error: SHA1 mismatch
Expected: f681a1f2126db151a2c60f7a21375cac97754351
Actual: 5b92798c55cbc8cf87f1435a2fc64e04d50a6648
```

**Comment by DomT4** [comment]
Looks like one of the files referenced by the formula has been moved/deleted/renamed/etc?

```
==> brew install --verbose --build-bottle checkstyle			 FAILED
==> Downloading https://downloads.sourceforge.net/project/checkstyle/checkstyle/6.2/checkstyle-6.2-bin.tar.gz
Already downloaded: /Library/Caches/Homebrew/checkstyle-6.2.tar.gz
==> Verifying checkstyle-6.2.tar.gz checksum
tar xf /Library/Caches/Homebrew/checkstyle-6.2.tar.gz
Error: No such file or directory - sun_checks.xml
```

**Comment by robsonpeixoto** [comment]
I made a wrong push with an incorrect message. I did a amend and a push -f.
My bad, sorry

**Comment by robsonpeixoto** [comment]
@DomT4 now the test passed!

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Comment by robsonpeixoto** [comment]
For me it's a pleasure.

**Pull request closed without merging**
