### PR TITLE
neo4j 2.2.6 + neo4j 2.3.0-RC1 (devel)

### PR DESCRIPTION
**Pull request by mindrones**
After this one I'll make a new PR with the new stable (2.3.0), I've done this one to keep the complete versions history.

### CODE REVIEW

**Comment by bfontaine** [comment]
Can’t we directly get the 2.3.0? It’ll save time (both for maintainers and the CI) to have one PR instead of two.

**Comment by mindrones** [comment]
But what if someone wants to use 2.2.6?

**Comment by bfontaine** [comment]
@mindrones Homebrew doesn’t allows you to choose the version you want to install; it’s always the latest available. You might want to submit the 2.2.6 version to [Homebrew/versions](https://github.com/Homebrew/homebrew-versions) instead.

**Comment by mindrones** [comment]
@bfontaine OK thanks, here it is #45208 (closing this one instead)

**Pull request closed without merging**
