### PR TITLE
pound 2.7

### PR DESCRIPTION
**Pull request by bfontaine**

### CODE REVIEW

**Comment by bfontaine** [comment]
The build timed out because it’s computing two safe primes (1024- and 2048-bit long).

**Comment by bfontaine** [comment]
The build timed out probably because it’s computing two safe primes (1024- and 2048-bit long). Poke @mikemcquaid.

**Comment by mikemcquaid** [comment]
Is it not starting a daemon or something? But yeh, would be good to just make the test quicker if possible.

**Comment by bfontaine** [comment]
@mikemcquaid No, the test just check the syntax of the configuration file. It’s the *build* that times out, not the test :wink:

**Comment by mikemcquaid** [comment]
Ah gotcha.

**Comment by bfontaine** [comment]
Mmmh in fact on my machine `brew install pound` hangs at the end of `./configure` but running the build instructions directly in `brew install -i pound` works, `time make` gives me only `5m20`.

**Comment by jacknagel** [comment]
@BrewTestBot test this please

**Comment by jacknagel** [comment]
The configure script seems to fork off a `conftest` process that is not cleaned up, and this causes the call to `rd.gets` in `Formula#system` to hang (so this only happens in verbose mode).

Not sure why this only happens on 10.10.

**Comment by jacknagel** [comment]
Found the bug: https://groups.google.com/forum/#!topic/google-perftools/vyHgx0mFciQ

Simple reproduction:

```
$ cat t.c
#include <unistd.h>

int main(void) {
    fork();
    return 0;
}
$ clang -Wall t.c -o badfork -ltcmalloc
$ ./badfork
$ ps aux | grep "[b]adfork"
jacknagel       54473   0.3  0.0  2446416    280 s000  S    12:08PM   0:00.12 ./badfork
```

remove the `-ltcmalloc` and the child will not hang:

```
$ kill 54473
$ clang -Wall t.c -o badfork
$ ./badfork
$ ps aux | grep "[b]adfork"
````

Simplest solution is to pass `--disable-tcmalloc` to configure.

**Comment by bfontaine** [comment]
Thanks for your work, @jacknagel :smile:

**Pull request closed without merging**
