### PR TITLE
audit: enforce https on *.bintray.com urls

### PR DESCRIPTION
**Pull request by vszakats**

### CODE REVIEW

**Comment by DomT4** [comment]
Might just be easier to fix the 7 formulae which currently violate the proposed rule.

**Comment by vszakats** [comment]
That wouldn't cover any future project storing their releases there. Bintray as a service is meant to do that and it is free for FOSS projects, so it may happen.

**Comment by DomT4** [comment]
No, but most formulae authors base their new formulae off of existing formulae using similar URLs/etc. I think more formulae authors check other formulae than the ` audit `. The amount of PRs we hit where everything works except the audit stage. That's just my concern.

Agree the mass-SSL/TLS-ification of audit checks is a good thing - Otherwise I wouldn't have touched it in the first place, but I'd love to try and create a mechanism to check for available SSL/TLS links automatically rather than having to keep piling things up in the ` audit ` long-term.

I'm aware what Bintray is :wink:.

**Comment by vszakats** [comment]
Sorry, if my words suggested you don't know Bintray - it was not my intent.

As for solutions, one approach may be to create an easily extendable list of url regexps, and just extend that list (effectively an SSL/TLS whitelist) without adding new code. This would cost less to maintain and update &mdash; over the initial development, of course.

And here's a quick attempt for SSL/TLS detection (in shell script, not Ruby, unfortunately):
https://gist.github.com/vszakats/663dc8ccf1d49b903f8e

**Comment by vszakats** [comment]
And, here's some thoughts on a possible way to automatically secure Apache urls:
https://github.com/Homebrew/homebrew/issues/37945

**Comment by mikemcquaid** [comment]
Thanks again @vszakats!

**Comment by DomT4** [comment]
Apologies. My tone was much more grumpy than I intended it to be; My comment about Bintray was supposed to be kinda tongue-in-cheek fun.

> UPDATE: @bfontaine has a nice Ruby implementation based on above.

This looks nice actually. Pretty much what I was thinking along the lines of. If @mikemcquaid and co had no objections to that chunk, we could effectively replace a lot of the SSL/TLS checks in the ` audit ` with a similar block to that at some point.

**Pull request closed without merging**
