### PR TITLE
influxdb 0.9.4.1

### PR DESCRIPTION
**Pull request by toddboom**

### CODE REVIEW

**Comment by toddboom** [comment]
it seems like the build never got kicked off here - any ideas?

**Comment by toddboom** [comment]
@mikemcquaid can you kick this?

**Comment by DomT4** [comment]
Our CI has been having some significant issues over the last week. It's slowly plowing through the backlog now. Please bear with it, Thanks!

**Comment by toddboom** [comment]
@DomT4 thanks for the update - looks all good now!

**Comment by toddboom** [comment]
@DomT4 anything i can do to help get this merged?

**Comment by DomT4** [comment]
It's good. Merged in https://github.com/Homebrew/homebrew/commit/ffefe174b80fda6ca1e4f80704928c82b607b922. Thank you for your contribution to Homebrew @toddboom, and apologies for the CI holdup.

**Pull request closed without merging**
