### PR TITLE
webp 0.5.0

### PR DESCRIPTION
**Pull request by mintyphoenix**
Updating to current version.

### CODE REVIEW

**Comment by DomT4** [comment]
Looks like everything that `brew uses webp` and isn't `:optional` needs a `revision` bump.

**Comment by mintyphoenix** [comment]
Thanks for the feedback @DomT4 . This is all _very_ new to me in terms of contributing/pull requests.

Looking at the failing tests, it would seem that `webkitgtk` failing is the root of `devhelp` & `gitg` failing. Are you suggesting that bumping `webkitgtk` to the current version, ideally resulting in all three then passing, should resolve the issue? Or have I misunderstood?

Assuming that is the case, I made a quick pass at updating `webkitgtk` and it's unfortunately beyond me :disappointed: 

Separately, I took a look at the [brew-test-bot.mavericks.test openimageio](http://bot.brew.sh/job/Homebrew%20Pull%20Requests/41354/version=mavericks/testReport/brew-test-bot/mavericks/test_openimageio/) trace but could not see how the trace related to this formula so any insight with that would also be appreciated (especially since I only have an El Capitan environment myself and the failing test is Mavericks).

**Comment by DomT4** [comment]
> This is all very new to me in terms of contributing/pull requests.

No worries! Happy to try and help :smiley:.

> Separately, I took a look at the brew-test-bot.mavericks.test openimageio trace 

Blurgh. You can ignore that; sadly when the CI is _very_ busy it's not always successful at flushing the environment completely before the next build is triggered.

> Are you suggesting that bumping webkitgtk to the current version, ideally resulting in all three then passing, should resolve the issue? Or have I misunderstood?

If `webkitgtk` has a version update available, sure. Otherwise just bump the `revision` there.

The problem seems to be that `webp` which `webkitgtk` uses changed the versioning of the library from `libwebp.5.dylib` to `libwebp.6.dylib` and consequently the formulae that use `webp` when pouring bottles can no longer find it because the installation was built against the older `webp`.

I'd recommend bumping the revisions on:
* webkitgtk
* mapnik
* sdl_image
* sdl2_image

Essentially if a formula doesn't have a `revision` line already you'd do something like this:
```diff
  desc ""
  homepage ""
  url ""
  sha256 ""
+ revision 1
```
And if the formula already has a revision you'd increase the number one increment, so 1 => 2, and so on. Ideally each changed formula should be a new commit, with the commit message like:
```
webkitgtk: bump revision for webp update
```
And so on.

**Comment by DomT4** [comment]
You've pulled in a lot of extra commits here accidentally. Mind doing a rebase so the CI doesn't fall over trying to pull it for testing? Thanks!

**Comment by mintyphoenix** [comment]
I pooched the rebase/pushing the rebase so I quickly re-did the changes based on current commits.

**Comment by DomT4** [comment]
Thanks! I've killed the build on CI for now because it's going to need a good 4 hours to finish building I suspect. I'll re-queue it tonight when things are quieter.

**Comment by DomT4** [comment]
@BrewTestBot test this please

**Comment by DomT4** [comment]
Alright, this seems fine now. I'm sure something somewhere will still break because these significant version bumps across almost any large project always do, but should be minimal with the revision bumps here.

Merged! Thank you for your contributions to Homebrew @mintyphoenix; we appreciate them! :smiley_cat:

**Pull request closed without merging**
