### PR TITLE
unbound: 1.5.4

### PR DESCRIPTION
**Pull request by MindTooth**
Only tested on El Capitan.

### CODE REVIEW

**Comment by dunn** [comment]
Would it be possible to add a test, just to check basic functionality?

**Comment by MindTooth** [comment]
I'll be away for a few days.  But I'll look into when I can.

**Comment by DomT4** [comment]
Will merge for now, since the new bottle is `cellar :any` and that's a nice thing for users. If you could swing by with a PR when you get a moment to add a test though, that'd be awesome.

Thanks @MindTooth! Merged in https://github.com/Homebrew/homebrew/commit/1b3ce6b330723ab9a94aba2865c814f82cc6ac63.

**Comment by MindTooth** [comment]
Really not sure other than a version check.

Similar issue here (respons): https://github.com/Homebrew/homebrew/pull/40144#issuecomment-107664647

**Pull request closed without merging**
