### PR TITLE
Build `ttfautohintGUI` also.

### PR DESCRIPTION
**Pull request by lemzwerg**

### CODE REVIEW

**Comment by mikemcquaid** [comment]
If you're resubmitting this: it should be `:optional`

**Comment by lemzwerg** [comment]
Sorry, I don't understand – I'm not a homebrew user, I just want to synchronize the formula with what I have on http://www.freetype.org/ttfautohint/osx.html (contributed by Dave Crossland).  Where shall I add this `:optional` keyword?

**Comment by mikemcquaid** [comment]
If you're not a Homebrew user I'd suggest you don't need to create a pull request here to change things; wait for one of our users to request it.

**Comment by lemzwerg** [comment]
@davelab6, can you help, please?

**Comment by lemzwerg** [comment]
Meanwhile, I've found out how `:optional` works :-)  I've submitted a new pull request.

**Pull request closed without merging**
