### PR TITLE
fits 0.8.4

### PR DESCRIPTION
**Pull request by anjackson**
Upgrading FITS to the latest release, 0.8.4.

### CODE REVIEW

**Comment by DomT4** [comment]
Blew up on Mountain Lion only:

```
==> ant
Buildfile: /private/tmp/fits20150322-57250-1e2toaz/fits-0.8.4/build.xml

compile:
    [javac] /private/tmp/fits20150322-57250-1e2toaz/fits-0.8.4/build.xml:79: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds

BUILD FAILED
/private/tmp/fits20150322-57250-1e2toaz/fits-0.8.4/build.xml:79: Class not found: javac1.8

```

**Comment by mikemcquaid** [comment]
Looks like it needs a `depends_on :java => "1.8"`

**Comment by jacknagel** [comment]
@BrewTestBot test this please

**Comment by jacknagel** [comment]
@BrewTestBot test this please

**Comment by mikemcquaid** [comment]
@BrewTestBot test this please

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
