### PR TITLE
FORD 4.2.3

### PR DESCRIPTION
**Pull request by zbeekman**
FORD 4.2.3

Major enhancement:
 - Call graphs
 - Module dependency graphs
 - Type/class graph/diagram

Also, I have reordered the python package dependencies/resources now that [Homebrew PyPi Poet](https://github.com/tdsmith/homebrew-pypi-poet) sorts them in alphabetical order. This will ease maintenance in the future. When the formula for FORD was first authored, `poet -f ford` produced resource stanzas that were neither sorted, nor in a deterministic order. This made inspecting the stanzas for changed versions more time consuming.

### CODE REVIEW

**Comment by dunn** [comment]
The test is failling on all three builds:
```
==> /usr/local/Cellar/ford/4.2.3/bin/ford /private/tmp/ford20150901-70562-8dt6h6/test-project.md
Traceback (most recent call last):
  File "/usr/local/Cellar/ford/4.2.3/libexec/bin/ford", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2793, in <module>
    working_set.require(__requires__)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 673, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 576, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: graphviz
Error: ford: failed

**Comment by zbeekman** [comment]
ah, I forgot to add the new python graphviz binding dependency to the `resource(r).stage do` and also add graphviz itself as a dependency

**Comment by zbeekman** [comment]
@dunn I can't seem to determine if my latest commits have been queued up by the testbot or not... It's been a while since I pushed the fixes...

**Comment by dunn** [comment]
If you pushed again, it's been queued, but we've still got a bit of a backlog so the delay isn't surprising.

**Comment by zbeekman** [comment]
ah OK, I tried to search the queue but couldn't find any evidence of it... It seems that all is well now, and the tests passed

**Comment by dunn** [comment]
Looks good! Merged in 2a5243d28e2a3719f385d4c11f6073e6d0be2878, thanks!

**Pull request closed without merging**
