### PR TITLE
repl: test added

### PR DESCRIPTION
**Pull request by bfontaine**

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Test is failing on the bots: http://bot.brew.sh/job/Homebrew%20Pull%20Requests/25068/version=yosemite/testReport/junit/brew-test-bot/yosemite/test_repl/

**Comment by jacknagel** [comment]
@BrewTestBot test this please

**Comment by jacknagel** [comment]
```
Testing repl
==> /usr/local/Cellar/repl/1.0.0/bin/repl brew
Error: Unknown command: version
Error: repl: failed
<"brew>> 0.9.5\nbrew>> "> expected but was
<"brew>> brew>> ">.
```

**Comment by bfontaine** [comment]
Thanks @jacknagel, fixed.

**Comment by mikemcquaid** [comment]
Thanks @bfontaine!

**Pull request closed without merging**
