### PR TITLE
yeti: test added

### PR DESCRIPTION
**Pull request by bfontaine**

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Install is failing on the bots: http://bot.brew.sh/job/Homebrew%20Pull%20Requests/19350/version=yosemite/testReport/junit/brew-test-bot/yosemite/install_yeti/

**Comment by bfontaine** [comment]
@mikemcquaid It might fail because of the JDK version (upstream is [aware of problems with JDK 1.8](https://groups.google.com/forum/#!topic/yeti-lang/_ldFJg2eaek)), I just submitted #35596 to get the bot’s JDK version which may help with debugging here.

**Comment by bfontaine** [comment]
Checking this PR now that #35596 has been merged, are build pages removed after some time?

build not found

**Comment by mikemcquaid** [comment]
> are build pages removed after some time?

Yup, a week. Rerunning.

**Comment by mikemcquaid** [comment]
@BrewTestBot test this please

**Comment by bfontaine** [comment]
@mikemcquaid the stacktrace shows the bot runs `/usr/libexec/java_home --failfast --version 1.7+`. Why is there a plus at the end? This causes it to use the latest JDK version, i.e. `1.8` instead of `1.7`.

On my mac (I don’t have the JDK version 1.8 so I tested with 1.6/1.7):
```
$ /usr/libexec/java_home --failfast --version 1.6
/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
$ /usr/libexec/java_home --failfast --version 1.6+
/Library/Java/JavaVirtualMachines/jdk1.7.0_40.jdk/Contents/Home
```

The `+` is added [here](https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/requirements.rb#L135).

This is likely the cause of the failure, because Yeti isn’t compatible with Java 8.

**Comment by mikemcquaid** [comment]
The `depends_on` currently means "that version or later". We probably need to modify the syntax to fix that.

**Comment by bfontaine** [comment]
Which kind of syntax would you like?

You could use something like Rubygem, modified to be backward compatible:

```
depends_on :java => "1.7" # alias for >=1.7 to be backward compatible
depends_on :java => "=1.7" # force 1.7
depends_on :java => "<1.8" # force a version below 1.8

# I don’t have any use-case for these
depends_on :java => "~>1.7" # 1.x
depends_on :java => ">=1.7" # same as the actual syntax
depends_on :java => ">1.7" # same as ">=1.8" and "1.8"
depends_on :java => "<=1.7" # same as "<1.8"
```

**Comment by jacknagel** [comment]
I would recommend using a custom requirement for now (rather than wait for someone to implement a constraint resolver).

**Comment by bfontaine** [comment]
@jacknagel Thanks, I was thinking of me for this someone :smiley:. I tried the following for a custom requirement:

```rb
class JavaHardDependency < JavaDependency
  satisfy { java_version }

  def java_version
    args = %w[/usr/libexec/java_home --failfast]
    args << "--version #{@version}" if @version
    quiet_system(*args)
  end
end

# then in the formula
depends_on JavaHardDependency => "1.7"
```

But it doesn’t work. Is my requirement ok, or is there a mistake in it?

**Comment by mikemcquaid** [comment]
> depends_on :java => "1.7" # alias for >=1.7 to be backward compatible

I think we can just migrate the existing usages to use `1.7+` and pass it straight through.

**Comment by bfontaine** [comment]
@mikemcquaid Do you mean you want a PR that adds a `+` on all the formulae and removes the `+` in the `JavaDependency` class?

```
$ git grep "depends_on :java"
Library/Formula/artifactory.rb:  depends_on :java => "1.7"
Library/Formula/blucat.rb:  depends_on :java => "1.6"
Library/Formula/ceylon.rb:  depends_on :java => "1.7"
Library/Formula/closure-compiler.rb:  depends_on :java => "1.7"
Library/Formula/duck.rb:  depends_on :java => [:build, "1.7"]
Library/Formula/elasticsearch.rb:  depends_on :java => "1.7"
Library/Formula/findbugs.rb:  depends_on :java => '1.7'
Library/Formula/galen.rb:  depends_on :java => "1.6"
Library/Formula/golo.rb:  depends_on :java => "1.7"
Library/Formula/jenkins.rb:  depends_on :java => "1.6"
Library/Formula/jooby-bootstrap.rb:  depends_on :java => "1.8"
Library/Formula/kafka.rb:  depends_on :java => "1.7"
Library/Formula/mesos.rb:  depends_on :java => "1.7"
Library/Formula/mvnvm.rb:  depends_on :java => "1.7"
Library/Formula/predictionio.rb:  depends_on :java => "1.7"
Library/Formula/pylucene.rb:  depends_on :java => "1.7"
Library/Formula/redpen.rb:  depends_on :java => "1.8"
Library/Formula/tomcat-native.rb:  depends_on :java => "1.7"
```

**Comment by mikemcquaid** [comment]
> @mikemcquaid Do you mean you want a PR that adds a + on all the formulae and removes the + in the JavaDependency class?

It'd be an acceptable solution, I think. Might want to check the main taps too but: yeh.

**Comment by bfontaine** [comment]
@mikemcquaid What do you think of this roadmap?

1. Allow formulae to add a trailing `+` but ignore it in the requirement (i.e. `"1.7+"` would be the same as `"1.7"`)
2. Wait a couple days (weeks?) for most taps to update their formulae to the new system (i.e. add a `+` where it’s relevant)
3. Stop ignoring the `+` in the requirement and switch to the new system

**Comment by mikemcquaid** [comment]
> @mikemcquaid What do you think of this roadmap?
> 
> Allow formulae to add a trailing + but ignore it in the requirement (i.e. "1.7+" would be the same as "1.7")
> Wait a couple days (weeks?) for most taps to update their formulae to the new system (i.e. add a + where it’s relevant)
> Stop ignoring the + in the requirement and switch to the new system

Sounds great :+1:

**Comment by bfontaine** [comment]
See #36376.

**Comment by bfontaine** [comment]
Green!

**Comment by mikemcquaid** [comment]
Thanks @bfontaine!

**Pull request closed without merging**
