### PR TITLE
Openmpi 1.8.4 (add java dependency)

### PR DESCRIPTION
**Pull request by davydden**
see https://github.com/Homebrew/linuxbrew/issues/365#issuecomment-104373158

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Is this just needed at build-time?

**Comment by davydden** [comment]
I guess it depends on point of view. As you you might have seen in the issue above, the error appeared at
```
libexec.install bin/'vtsetup.jar'
```
which is absent without Java. I know nothing about java, but I suppose this file may be used later on by some (java) applications.

**Comment by mikemcquaid** [comment]
Let's make it a `:build` dependency for now, thanks.

**Comment by davydden** [comment]
done.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/41e38cd9a13fb27e4e667e175acf84661db9f5e1. Thanks for your contribution to Homebrew, we appreciate it! :smiley_cat:. Please note for non version bumps the commit format should be a simple `formula: change i made`, Thanks!

**Pull request closed without merging**
