### PR TITLE
yacas 1.3.6

### PR DESCRIPTION
**Pull request by hkjinlee**
Updated not-working 1.3.4 formula to 1.3.6.

- Corrected download URL
- Modified configure and Makefile.in, Makefile.am for build

### CODE REVIEW

**Comment by asparagui** [comment]
a) Could you report your fixes upstream?
b) Looks like mountain lion needs some c++0x tweaks.

**Comment by hkjinlee** [comment]
@asparagui Got it. I'll try to make it upstream first

**Comment by bfontaine** [comment]
Any update on this?

**Comment by DomT4** [comment]
Presuming dead. Feel free to resubmit as a fresh PR with the various issues addressed if desired. Thanks for the submission!

**Pull request closed without merging**
