### PR TITLE
Upgrade vowpal-wabbit to 8.0

### PR DESCRIPTION
**Pull request by zachmayer**
Lots of new features.  Some of the cool ones are:
    - [Online gradient boosting trees for binary classification](http://jmlr.org/proceedings/papers/v37/beygelzimer15.pdf)
    - [Online follow-the-regularized-leader optimization](http://www.eecs.tufts.edu/~dsculley/papers/ad-click-prediction.pdf)
    - Field-aware low-rank quadratic features (similar to [libFFM](http://www.csie.ntu.edu.tw/~cjlin/libffm/))
    - Lots of bug fixes, including processing older model files

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

For future reference the preferred commit message format for simple version updates is `vowpal-wabbit 8.0`.

**Comment by zachmayer** [comment]
Thanks!  Without homebrew I couldn't make PRs like this =D

`vowpal-wabbit 8.0.` vs the changelog from 7.10 vs 8.0?

**Comment by mikemcquaid** [comment]
Just the `vowpal-wabbit 8.0` (but the body can always include a changelog if you'd like)

**Comment by zachmayer** [comment]
Gotcha, will do that in the future.  Thanks!

**Pull request closed without merging**
