### PR TITLE
go 1.5.2

### PR DESCRIPTION
**Pull request by fsouza**

### CODE REVIEW

**Comment by parkr** [comment]
:heart:

**Comment by zellyn** [comment]
:+1:

**Comment by beauhoyt** [comment]
:+1:

**Comment by osamingo** [comment]
:+1:

**Comment by DomT4** [comment]
I'm merging it as I type this, no need for extra emojis :wink:.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/ecfef088212ed1a63f64caabf307368ea3974906. Thank you for another Homebrew contribution @fsouza! :smiley_cat:

**Pull request closed without merging**
