### PR TITLE
cgrep 6.5.3

### PR DESCRIPTION
**Pull request by dunn**

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Test failing: http://bot.brew.sh/job/Homebrew%20Pull%20Requests/31239/version=yosemite/testReport/junit/brew-test-bot/yosemite/test_cgrep/

**Comment by dunn** [comment]
Yeah, I haven't been able to figure out why yet.

**Comment by dunn** [comment]
Pretty much mystified by these test failures; never occur locally.

**Comment by dunn** [comment]
Closing in favor of #45423

**Pull request closed without merging**
