### PR TITLE
sysbench: add missing protocol to mirror url

### PR DESCRIPTION
**Pull request by vszakats**

### CODE REVIEW

**Comment by DomT4** [comment]
How did I manage to do that :sweat_smile:

**Comment by nijikon** [comment]
Nice :dancer:

**Comment by DomT4** [comment]
I guess I'll take one screwed up mirror given how many I've changed over my time here :smile:.

Merged in https://github.com/Homebrew/homebrew/commit/9f77211997484bdda928e0d0bbf867686f90116d. Thanks for spotting this @vszakats!

**Comment by vszakats** [comment]
:)

**Pull request closed without merging**
