### PR TITLE
Upgrade isync to version 1.1.2

### PR DESCRIPTION
**Pull request by gma**

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Please add a `depends_on "openssl"`: http://bot.brew.sh/job/Homebrew%20Pull%20Requests/22583/version=yosemite/testReport/junit/brew-test-bot/yosemite/audit_isync/

**Comment by DomT4** [comment]
Ah. You put the ` depends_on "openssl" ` in the wrong bit :). Needs to be under the ` berkeley-db ` dep rather than tucked inside the ` head ` block.

**Comment by gma** [comment]
I didn't think it was a particularly sensible thing to bounce back at me… quicker to just add it and merge it. Or just merge it; adding the dep doesn't seem related to bumping the version.

**Comment by DomT4** [comment]
We can't add it after merging it; Our bot produces binaries, which we call bottles, and those binaries are linked to the tools used at compile-time. So if we merged it, and then added the dep, those bottles would still be hooked into using the system OpenSSL, and would immediately need regenerating to fix that problem. It's less redundant work for the bot to be able to do it inside the PR.

Adding the dep is important in this case becuase OS X's OpenSSL is deprecated and well, kinda useless.

**Comment by gma** [comment]
It's okay, I'm not bothered and don't have time to spare finding out how to fix it. I just thought bumping the version (which I'd done locally anyway to build it) might be helpful.

**Comment by mikemcquaid** [comment]
> It's okay, I'm not bothered and don't have time to spare finding out how to fix it.

In future please don't create pull requests if you're not bothered and don't have time. I know it seems like just a little thing for us to fix it for you but we have hundreds of pull requests to do that with and only a few maintainers. It doesn't really scale.

**Pull request closed without merging**
