### PR TITLE
mkvtoolnix: updated to v8.7.0

### PR DESCRIPTION
**Pull request by mohakshah**
Updated mkvtoolnix to version 8.7.0 along with the sha256

### CODE REVIEW

**Comment by mohakshah** [comment]
The formula specifies a requirement of ruby 1.9.
`depends_on :ruby => ["1.9", :build]`

 Yet, the build fails on mavericks with the following message.
> rake aborted!
> Ruby 1.9.x or newer is required for building

Looking at the build environment, even though the system ruby is at 2.0, ruby 1.8.7 is prepended to the path.

>System Ruby: 2.0.0-p481

>Ruby: /usr/local/opt/ruby187/bin/ruby => /usr/local/Cellar/ruby187/1.8.7-p374_1/bin/ruby

>PATH: /usr/local/opt/ruby187/bin:/usr/local/Library/ENV/4.3:/usr/local/opt/xz/bin:/usr/local/opt/pkg-config/bin:/usr/local/opt/flac/bin:/usr/bin:/bin:/usr/sbin:/sbin

Does someone know what I'm missing here?

**Comment by DomT4** [comment]
It's a CI bug on our side that https://github.com/Homebrew/homebrew/pull/47605 should solve.

**Comment by mohakshah** [comment]
O.K., thanks! I'll wait for #47605 to be merged and resend the pull request.

**Comment by mikemcquaid** [comment]
@mohakshah You can leave this open and we'll refresh it when that's merged.

**Comment by mohakshah** [comment]
👍

**Comment by DomT4** [comment]
@BrewTestBot test this please

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

For future reference the preferred commit message format for simple version updates is `mkvtoolnix 8.7.0`.

**Pull request closed without merging**
