### PR TITLE
frag_find: head added

### PR DESCRIPTION
**Pull request by bfontaine**
I also added a better test.

### CODE REVIEW

**Comment by DomT4** [comment]
Apparently needs an `openssl` dependency and consequent revision.

**Comment by bfontaine** [comment]
@DomT4 Done. Is there any way to detect this locally, before making the PR?

**Comment by mikemcquaid** [comment]
@bfontaine `brew audit frag_find` _after_ installing.

**Comment by DomT4** [comment]
It should be getting thrown by [this block](https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/formula_cellar_checks.rb#L142-L157) as well after you install it locally. I don't know if you have to have the developer env set or build `--debug` or such to see those messages though.

**Pull request closed without merging**
