### PR TITLE
gdb: migrate from homebrew/dupes

### PR DESCRIPTION
**Pull request by mistydemeo**

### CODE REVIEW

**Comment by mistydemeo** [comment]
PR so the bottle gets rebuilt, will merge when the bot's done.

**Comment by DomT4** [comment]
Are we importing the entire `gdb` commit tree?

**Comment by mistydemeo** [comment]
Yeah, I ran `git filter-branch` to retain history for it.

**Comment by DomT4** [comment]
Ah okay :)

**Pull request closed without merging**
