### PR TITLE
audit: imporve revision check logic

### PR DESCRIPTION
**Pull request by xu-cheng**
* Check revision decrease against both stable and devel spec.
* Check revision reset only for stable spec if stable spec is available.

cc @DomT4

### CODE REVIEW

**Comment by mikemcquaid** [comment]
:+1:

**Comment by DomT4** [comment]
No objections from me.

I think @bfontaine posted something about this check on the chat yesterday, don't know if we can address his concerns at all/already are here.

**Comment by bfontaine** [comment]
My concern was that this check can take a long time in the core repo; with it `brew audit --strict` on a given formula can take >20s while without it it only takes ~2s. This PR doesn’t address it; I’m not sure we could really improve it.

@xu-cheng Do you think it would make sense to only check the past `N` log entries on a formula? Something like `N=10` would probably suffice.

**Comment by xu-cheng** [comment]
> with it brew audit --strict on a given formula can take >20s while without it it only takes ~2s.

This shouldn't be that slow. I wonder you may have shallow clone on your computer.

> Do you think it would make sense to only check the past N log entries on a formula? Something like N=10 would probably suffice.

A good idea, I can explore it. But how large should the N be?

**Comment by xu-cheng** [comment]
Updated to check only 10 recent commits.

**Comment by bfontaine** [comment]
Thank you!

> I wonder you may have shallow clone on your computer.

No I have the full history. Is it fast on yours?

**Comment by DomT4** [comment]
FWIW, even on my MacBook Pro which is Mid-2015/8-core/16GB RAM/etc `audit --strict` does take a lot longer to finish than it did before we added the revision check:

> brew audit --strict openssl  13.98s user 2.01s system 110% cpu 14.410 total

After this PR with the changes made it's back to a relatively normal amount of time:

> brew audit --strict openssl  3.66s user 0.43s system 107% cpu 3.809 total

**Comment by xu-cheng** [comment]
OK, I may get false impression because I test it with other formula. `brew audit openssl` does take quite long time.

**Comment by bfontaine** [comment]
It’s now back to a few seconds for `brew audit --strict git`; thank you @xu-cheng!

**Pull request closed without merging**
