### PR TITLE
libgdata 0.16.1 (new formula)

### PR DESCRIPTION
**Pull request by tschoonj**

### CODE REVIEW

**Comment by tschoonj** [comment]
@DomT4 This one too? :smile:

**Comment by DomT4** [comment]
@BrewTestBot test this please

**Comment by tschoonj** [comment]
@DomT4 and this one? :smile:

**Comment by DomT4** [comment]
And last but not least, merged in https://github.com/Homebrew/homebrew/commit/7b62a88f3c573cef2a807f7b8aa7dfc30ca980d8. Careful, you're becoming our go-to point of contact for all the GTK stuff :wink:

**Comment by tschoonj** [comment]
Thanks for all the work!

And I don't mind being the go-to guy for GTK/GNOME stuff :smile:

**Pull request closed without merging**
