### PR TITLE
tokyo-dystopia: test added

### PR DESCRIPTION
**Pull request by bfontaine**

### CODE REVIEW

**Comment by bfontaine** [comment]
The build fails because it doesn’t support spaces in paths:

```
clang: error: clang: no such file or directory: 'Pull'error: 
no such file or directory: 'Pull'
```

I’ll try with a patch.

**Comment by mikemcquaid** [comment]
Hmm, I wonder which particular path it's having problems with? `PATH`?

**Comment by bfontaine** [comment]
The bot uses an include path with a space:

```
==> make
clang -c -I. -I/usr/local/Cellar/tokyo-cabinet/1.4.48/include -I/Users/brew/Jenkins/workspace/Homebrew Pull Requests/version/yosemite/home/include (…)
```

Is it something I can fix this issue in the formula, or is it the bot that need to escape this space? In the later case, it might be the same issue than #37547.

**Comment by mikemcquaid** [comment]
Have tried changing the workspace and retrying the job. Let's see what happens.

**Comment by mikemcquaid** [comment]
Tada. I'll change that globally. Thanks!

**Pull request closed without merging**
