### PR TITLE
nspr 4.10.10

### PR DESCRIPTION
**Pull request by l-hedgehog**

### CODE REVIEW

**Comment by DomT4** [comment]
Why the change of link from `ftp` to `archive`, out of curiosity?

**Comment by l-hedgehog** [comment]
@DomT4, "existing links to ftp.mozilla.org will continue to work, although
archive.mozilla.org is now considered the canonical domain" from [mozilla.dev.platform](https://lists.mozilla.org/pipermail/dev-platform/2015-October/012032.html)

**Comment by DomT4** [comment]
Nice, Thanks for the link!

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
