### PR TITLE
update libsass to 3.1 release

### PR DESCRIPTION
**Pull request by drewwells**
Minor version 3.1.0 of release has landed.  This updates the version and sha to the new release "Bulleit Bottle" https://github.com/sass/libsass/issues/697

### CODE REVIEW

**Comment by DomT4** [comment]
The ` devel do ` block can be killed, since ` stable ` now outdated ` devel ` :). Does ` sassc ` need a revision to cope with the API changes, or is it good?

**Comment by drewwells** [comment]
I figure we could leave devel around since it will be useful very soon for tracking 3.2.  I don't know what the normal practice for homebrew is, but I'd appreciate keeping the code there for easily updating it to 3.2.

I should update sassc, it will be broken.

**Comment by DomT4** [comment]
It'll need to be chopped, I'm afraid. The bot red-flags a situation where stable outdates devel, because you get the situation where people install ` devel ` thinking it's more recent than ` stable ` and then the complaints come flooding in :wink:. It's a tiny block of code very easily added back in as soon as there's a new devel though :).

The syntax is always
```
devel do
   url ""
   sha1 ""
end
```

Cool. Just tack a ` revision 1 ` underneath the SHA and we should be golden.

**Comment by drewwells** [comment]
Ahh okay, I'll remove it.  It looks like sassc does not have a 3.1 release.  I'll report back what I find about that backwards compat situation.

> Well, luckily, SassC is the official binary wrapper for libsass and is always kept in sync.

**Comment by DomT4** [comment]
>  It looks like sassc does not have a 3.1 release.

Weird. They're supposed to be released in-sync, as you highlight. Cheers for taking that upstream to ask what the situation is.

I don't know if the arbitrary change will be enough, you may need to make an actual ` revision ` to force the bot. Not sure. Guess we'll see :wink:.

**Comment by drewwells** [comment]
Fortunately @xzyfer shipped a release of sassc for brew! https://github.com/sass/sassc/releases/tag/3.1.0

**Comment by drewwells** [comment]
I'm getting a lot of strange errors, I'm going to split this commit into two PR

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! For future reference the preferred commit message format for simple version updates is `libsass 3.1.0`.

**Pull request closed without merging**
