### PR TITLE
git-annex: fix #36309

### LINKED ISSUE #36309: git-annex addurl fails if quvi is not installed
`git-annex addurl` has an implicit runtime dependency on `quvi`.
On a clean system with a fresh installation of homebrew:
```
$ brew install git-annex
==> Installing dependencies for git-annex: gsasl, libidn, libtasn1, gmp, 
==> Installing git-annex dependency: gsasl
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/gsasl-1.8.0
######################################################################## 100.0%
==> Pouring gsasl-1.8.0.mavericks.bottle.1.tar.gz
🍺  /usr/local/Cellar/gsasl/1.8.0: 130 files, 1.8M
==> Installing git-annex dependency: libidn
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/libidn-1.29
######################################################################## 100.0%
==> Pouring libidn-1.29.mavericks.bottle.1.tar.gz
🍺  /usr/local/Cellar/libidn/1.29: 70 files, 1.4M
==> Installing git-annex dependency: libtasn1
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/libtasn1-4.
######################################################################## 100.0%
==> Pouring libtasn1-4.2.mavericks.bottle.tar.gz
🍺  /usr/local/Cellar/libtasn1/4.2: 55 files, 568K
==> Installing git-annex dependency: gmp
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/gmp-6.0.0a.
######################################################################## 100.0%
==> Pouring gmp-6.0.0a.mavericks.bottle.tar.gz
🍺  /usr/local/Cellar/gmp/6.0.0a: 15 files, 3.2M
==> Installing git-annex dependency: nettle
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/nettle-2.7.
######################################################################## 100.0%
==> Pouring nettle-2.7.1.mavericks.bottle.1.tar.gz
🍺  /usr/local/Cellar/nettle/2.7.1: 66 files, 1.7M
==> Installing git-annex dependency: gnutls
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/gnutls-3.3.
######################################################################## 100.0%
==> Pouring gnutls-3.3.11.mavericks.bottle.tar.gz
🍺  /usr/local/Cellar/gnutls/3.3.11: 1021 files, 9.0M
==> Installing git-annex
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/git-annex-5
######################################################################## 100.0%
==> Pouring git-annex-5.20150113.mavericks.bottle.tar.gz
🍺  /usr/local/Cellar/git-annex/5.20150113: 10 files, 76M
$ git init
Initialized empty Git repository in /Users/psibre/.git/
$ git annex init
init  ok
(recording state in git...)
$ git annex add README.md
add README.md ok
(recording state in git...)
$ git annex addurl --file=README.md https://raw.githubusercontent.com/Homebrew/homebrew/master/README.md

git-annex: quvi: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
failed
git-annex: addurl: 1 failed
$
```
If `quvi` is installed, everything works:
```
$ brew install quvi
==> Installing dependencies for quvi: pkg-config, lua, libquvi
==> Installing quvi dependency: pkg-config
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/pkg-config-
######################################################################## 100.0%
==> Pouring pkg-config-0.28.mavericks.bottle.2.tar.gz
🍺  /usr/local/Cellar/pkg-config/0.28: 10 files, 604K
==> Installing quvi dependency: lua
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/lua-5.2.3_1
######################################################################## 100.0%
==> Pouring lua-5.2.3_1.mavericks.bottle.tar.gz
🍺  /usr/local/Cellar/lua/5.2.3_1: 13 files, 308K
==> Installing quvi dependency: libquvi
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/libquvi-0.4
######################################################################## 100.0%
==> Pouring libquvi-0.4.1_1.mavericks.bottle.1.tar.gz
🍺  /usr/local/Cellar/libquvi/0.4.1_1: 83 files, 544K
==> Installing quvi
==> Downloading https://downloads.sourceforge.net/project/quvi/0.4/quvi/quvi-0.4
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/quvi/0.4.2
==> make install
🍺  /usr/local/Cellar/quvi/0.4.2: 8 files, 116K, built in 9 seconds
$ git annex addurl --file=README.md https://raw.githubusercontent.com/Homebrew/homebrew/master/README.md
addurl README.md ok
(recording state in git...)
$
```

### PR DESCRIPTION
**Pull request by psibre**

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Seems to be failing to build: http://bot.brew.sh/job/Homebrew%20Pull%20Requests/20552/version=yosemite/testReport/junit/brew-test-bot/yosemite/install_git_annex/

**Comment by psibre** [comment]
From trying to build git-annex from source in the past, I know that it's utterly volatile -- dependency hell with cabal etc. Which is why I cherish the fact that homebrew has it bottled! =)

Trying to [build like the bot](http://bot.brew.sh/job/Homebrew%20Pull%20Requests/20552/version=mavericks/testReport/junit/brew-test-bot/mavericks/install_git_annex/) on a clean system fails for me *even without this patch*, i.e., at the latest upstream revision (4bb9eb891653197fe7f4fb6a30e00cbbb2435278). So I'm pretty sure it's not due to adding the `depends_on "quvi"` stanza:
```
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: git-annex-5.20150113 (user goal)
trying: http-conduit-2.1.5 (dependency of git-annex-5.20150113)
trying: conduit-1.2.3.1 (dependency of http-conduit-2.1.5)
trying: utf8-string-1 (dependency of git-annex-5.20150113)
trying: git-annex-5.20150113:-android
trying: git-annex-5.20150113:-androidsplice
trying: git-annex-5.20150113:+assistant
trying: git-annex-5.20150113:+cryptohash
trying: git-annex-5.20150113:+dbus
trying: git-annex-5.20150113:+desktopnotify
trying: git-annex-5.20150113:+dns
trying: git-annex-5.20150113:-ekg
trying: git-annex-5.20150113:+feed
trying: git-annex-5.20150113:+inotify
trying: git-annex-5.20150113:+network-uri
trying: git-annex-5.20150113:+pairing
trying: git-annex-5.20150113:+production
trying: git-annex-5.20150113:+quvi
trying: git-annex-5.20150113:+s3
next goal: aws (dependency of git-annex-5.20150113:+s3)
rejecting: aws-0.11.2, 0.11.1, 0.11, 0.10.5 (conflict: utf8-string==1, aws =>
utf8-string==0.3.*)
rejecting: aws-0.10.4, 0.10.3, 0.10.2, 0.10.1, 0.10 (conflict:
conduit==1.2.3.1, aws => conduit>=1.1 && <1.2)
rejecting: aws-0.9.4 (conflict: utf8-string==1, aws => utf8-string==0.3.*)
rejecting: aws-0.9.3, 0.9.2 (conflict: conduit==1.2.3.1, aws => conduit>=1.1
&& <1.2)
rejecting: aws-0.9.1, 0.9, 0.8.6, 0.8.5, 0.8.4, 0.8.3, 0.8.2, 0.8.1, 0.8.0,
0.7.6.4, 0.7.6.3, 0.7.6.2, 0.7.6.1, 0.7.6, 0.7.5, 0.7.4, 0.7.3, 0.7.2, 0.7.1,
0.7.0, 0.6.2, 0.6.1, 0.6.0, 0.5.0, 0.4.1, 0.4.0.1, 0.4.0, 0.3.2, 0.3.1, 0.3,
0.2, 0.1, 0.0.6, 0.0.5, 0.0.4, 0.0.3, 0.0.2, 0.0.1 (conflict:
git-annex-5.20150113:s3 => aws(>=0.9.2))
Backjump limit reached (change with --max-backjumps).
```

Having said all that, `git-annex` *does* have a compile time dependency on `quvi` (see `+quvi` flag above); what I was trying accomplish with my pull request was simply to make homebrew also install `quvi` when installing the `git-annex` bottle.

**Comment by mikemcquaid** [comment]
Yeh. I don't mind just adding the dependency but if we can get this green first that'd be great too.

**Comment by psibre** [comment]
Some of the Haskell library skew with `aws` have resolved themselves overnight. However, now the build fails down the line...
```
Building feed-0.3.9.2...
Preprocessing library feed-0.3.9.2...

Text/Feed/Import.hs:35:8:
    Could not find module ‘System.IO.UTF8’
    Use -v to see a list of the files searched for.
```
It seems like the only way to build `git-annex` is to keep trying daily until the dependency hell with cabal sorts itself out...
Is there a way to periodically restart the CI build until it passes and builds the bottles?

**Comment by mikemcquaid** [comment]
> Is there a way to periodically restart the CI build until it passes and builds the bottles?

Nope but if you ask me I can kick it off periodically.

**Comment by mikemcquaid** [comment]
Still borked :(

**Comment by psibre** [comment]
Yeah, confirmed. Haskell may be a fantastic language (or so I've read), but their dependency resolution engine is fundamentally broken.
It seems that we have to wait for [`feed`](http://hackage.haskell.org/package/feed) to be updated since its [`utf8-string`](http://hackage.haskell.org/package/utf8-string) was updated last week and breaks compatibility...

**Comment by carlmod** [comment]
As git-annex was updated again, it would probably make sense to update the pullrequest to the new version. 

    url "https://hackage.haskell.org/package/git-annex-5.20150205/git-annex-5.20150205.tar.gz"
    sha1 "5df6114cb029531e429e2b423f5ae7f755ffa390"

It does still not build, but it seems `feed` has a pullrequest that should fix it https://github.com/sof/feed/pull/10.

**Pull request closed without merging**
