### PR TITLE
Updated to node.js v4.1.2

### PR DESCRIPTION
**Pull request by stoshiya**
Please review and merge. This release contains security fix.

### CODE REVIEW

**Comment by DomT4** [comment]
Can you update `npm` to `https://registry.npmjs.org/npm/-/npm-2.14.6.tgz` as well, Thanks.

**Comment by DomT4** [comment]
Changed my mind. I'll do it afterwards. It's non-urgent compared to the security fix.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/222b673a994a8725b13abefb1b052d8f67312092. Thank you for your contribution to Homebrew @stoshiya; we appreciate it! :smiley_cat:

**Comment by killswitch** [comment]
Dagggg beat me. Thanks @stoshiya!

**Pull request closed without merging**
