### PR TITLE
bottle: allow to keep old bottle specification

### PR DESCRIPTION
**Pull request by xu-cheng**
cc @mikemcquaid

### CODE REVIEW

**Comment by xu-cheng** [comment]
I just found I forget to make revision etc to sync. Will have a try to find a solution.

**Comment by xu-cheng** [comment]
Added field checking when keeping old bottle. And set revision as the same in that situation.

**Comment by mikemcquaid** [comment]
LGTM :+1:

**Comment by xu-cheng** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
