### PR TITLE
mp3splt: test added

### PR DESCRIPTION
**Pull request by bfontaine**

### CODE REVIEW

**Comment by bfontaine** [comment]
[Build failed](http://bot.brew.sh/job/Homebrew%20Pull%20Requests/21431/version=mountain_lion/testReport/junit/brew-test-bot/mountain_lion/test_mp3splt/):

```
==> /usr/local/Cellar/mp3splt/2.6.2/bin/mp3splt -t 0.1 /usr/local/Library/Homebrew/test/fixtures/test.mp3
dyld: Library not loaded: /usr/local/lib/libltdl.7.dylib
  Referenced from: /usr/local/lib/libmp3splt.0.dylib
  Reason: image not found
Error: mp3splt: failed
```

**Comment by mikemcquaid** [comment]
> Update 2: added a libtool build dependency, like #17732.

Looks like a runtime dependency from the above if there's a library link?

**Comment by bfontaine** [comment]
@mikemcquaid Right, fixed.

**Comment by mikemcquaid** [comment]
Now it's failing `audit`. @jacknagel @Homebrew/owners remind me what the correct solution is here, I always forget.

**Comment by xu-cheng** [comment]
`depends_on "libtool" => :run`

**Comment by jacknagel** [comment]
This package doesn't depend seem to depend on libtool. The bad linkage was in `libmp3splt`:

```
dyld: Library not loaded: /usr/local/lib/libltdl.7.dylib
  Referenced from: /usr/local/lib/libmp3splt.0.dylib
  Reason: image not found
Error: mp3splt: failed
```

which already has a `depends_on "libtool" => :run`

**Comment by bfontaine** [comment]
Thanks. I usually wait for the build to finish before commenting, and you were faster than me :)

**Pull request closed without merging**
