### PR TITLE
Pull the homebrew curl user agent from env

### PR DESCRIPTION
**Pull request by nlesiecki**
Certain proxies do user agent filtering, and it's helpful to be able to set the user agent. Homebrew overrides .curlrc with the -A flag, so un-override it.

### CODE REVIEW

**Comment by apjanke** [comment]
If we're going to do this, should we name the variable `HOMEBREW_USER_AGENT` or `HOMEBREW_HTTP_USER_AGENT`? Our other env vars that allow users to configure `brew`'s behavior seem to start with the `HOMEBREW_` prefix, and I don't think `USER_AGENT` is a standard env var.

**Comment by mikemcquaid** [comment]
This isn't the type of thing I'd like to be user-customisable as it doesn't allow upstreams to handle Homebrew correctly.

**Comment by nlesiecki** [comment]
Mike what do you propose for a user like me who has to sit behind a proxy? Just not use Homebrew? that seems like a pretty poor outcome. What about appending to the User-Agent instead of overriding it?

**Comment by nlesiecki** [comment]
I'm more than happy to work on a better idea.

**Comment by mikemcquaid** [comment]
Tell your proxy provider that you need access to Homebrew. Alternatively, use a VPN or SSH tunnel.

**Comment by ab** [comment]
@mikemcquaid This is not an option for a lot of people behind restrictive proxies. What exactly do you mean by "allow upstreams to handle Homebrew correctly"?

**Comment by mikemcquaid** [comment]
@ab If upstream wants to block Homebrew clients: we need them to be able to do so. If your proxy provider wants to block Homebrew clients: we need them to be able to do so. Your issue is not with Homebrew but with your proxy provider.

**Comment by ab** [comment]
I'm having a hard time understanding your position: why do you think it's a good idea to remove users' freedom to run homebrew?

**Comment by mikemcquaid** [comment]
I think restrictive proxies are a terrible idea. Please ask the people who run your restrictive proxy why they think it's a good idea to stop users from using Homebrew (particularly if you need it to do your job). Homebrew is not the first and will not be the last piece of software that does not allow you to customise your user-agent so almost all software will have problems with your proxy.

**Comment by mikemcquaid** [comment]
And for why our user-agent should be consistent: If I’m paying for my bandwidth and some tarball on my server gets added to Homebrew: I start paying huge amounts of money for bandwidth and have no way to stop that if Homebrew’s user agent is not consistent.

**Pull request closed without merging**
