### PR TITLE
ipfs: Bumps to version 0.3.9

### PR DESCRIPTION
**Pull request by eelcocramer**

### CODE REVIEW

**Comment by DomT4** [comment]
Would you mind squashing your commits here? The CI is having some trouble pulling it cleanly. Thanks!

**Comment by eelcocramer** [comment]
Sure. Sorry for the mess in the first place :-/

**Comment by eelcocramer** [comment]
Looks like CI build keeps failing. Shall I close this PR and create a new one?

**Comment by DomT4** [comment]
I re-queued it. Latest crash was a known Jenkins bug.

**Comment by DomT4** [comment]
There we go. Green on the CIs. Merged in https://github.com/Homebrew/homebrew/commit/d44d19aeba15154fc01f08d898c70199a78280cf. Thank you for your contribution to Homebrew @eelcocramer; we appreciate it! :smiley_cat:

**Comment by eelcocramer** [comment]
Thank you for maintaining Homebrew! I'm happy to contribute in any way.

**Pull request closed without merging**
