### PR TITLE
scala: modernize

### PR DESCRIPTION
**Pull request by vszakats**

### CODE REVIEW

**Comment by mikemcquaid** [comment]
We want to avoid cleanup-only PRs like this unless they improve security or add a missing test, I'm afraid.

**Comment by vszakats** [comment]
It does improve security by swapping an sha1 hash to sha256.

**Comment by vszakats** [comment]
Oh closed already. Thanks :(

**Comment by vszakats** [comment]
```diff
   resource 'completion' do
-    url 'https://raw.githubusercontent.com/scala/scala-dist/v2.11.4/bash-completion/src/main/resources/completion.d/2.9.1/scala'
-    sha1 'e2fd99fe31a9fb687a2deaf049265c605692c997'
+    url "https://raw.githubusercontent.com/scala/scala-dist/v2.11.4/bash-completion/src/main/resources/completion.d/2.9.1/scala"
+    sha256 "95aeba51165ce2c0e36e9bf006f2904a90031470ab8d10b456e7611413d7d3fd"
   end
```

**Comment by mikemcquaid** [comment]
Oh, sorry, please undelete the patch and I'll reopen and merge.

**Comment by vszakats** [comment]
Restored the patch and thanks!

**Comment by mikemcquaid** [comment]
No, thank you @vszakats!

**Pull request closed without merging**
