### PR TITLE
Use HTTPS for formulae Google Code homepages

### PR DESCRIPTION
**Pull request by pdalpra**
This PR modifies the homepages of all formulae whose homepages are hosted on Google Code to use HTTPS.

`brew audit` before :

```
285 problems in 224 formulae
```

`brew audit` after :

```
216 problems in 155 formulae
```

That's not much, but it cleans up audit results a bit ;)

### CODE REVIEW

**Comment by DomT4** [comment]
I plucked ` slowhttptest `, ` xar ` and ` szl ` out of this PR to deal with some OpenSSL issues. They were the reasons the bot failed you on testing in this PR.

**Comment by jacknagel** [comment]
Thanks for the PR. It is generally easier for us to deal with these changes incrementally (i.e. a few formulae at a time). Big PRs like this tend to unfairly consume CI resources.

**Comment by pdalpra** [comment]
Sorry :( 
If you like, I can split this PR into smaller ones (or at least, make smaller PR next time !)

**Comment by jacknagel** [comment]
A new, smaller PR (5-10 formulae) every day or so would be great, and prevent the build bots from getting bogged down unnecessarily.

**Comment by jacknagel** [comment]
Happy to accept this in smaller increments.

**Comment by pdalpra** [comment]
Sure, will do. Sorry for not giving updates before.

**Pull request closed without merging**
