### PR TITLE
apr 1.5.2

### PR DESCRIPTION
**Pull request by vszakats**
Fixes https://github.com/Homebrew/homebrew/issues/39362

### CODE REVIEW

**Comment by vszakats** [comment]
```
W0505 03:17:36.864459 1888727824 logging.cpp:81] RAW: Received signal SIGTERM from process 64468 of user 502; exiting
Error: mesos: failed
Will not overwrite /private/tmp/mesos20150505-64468-hd8g4f/Library/Python/2.7/lib/python/site-packages/homebrew.pth
```

**Comment by DomT4** [comment]
@tdsmith Any idea on the failure here? I thought it may just be a random bot hiccup, but seems to have reproduced. Doesn't *look* like one of those issues where a revision is needed either.

**Comment by tdsmith** [comment]
Oh, the python chunk of the mesos test is obsolete, now; I pushed a change a while back that does that automatically for all tests. Fix in #39402 and then we can give this another spin.

**Comment by DomT4** [comment]
Thanks Tim, appreciate the ninja-quick fix! :bow:

**Comment by vszakats** [comment]
https://github.com/Homebrew/homebrew/pull/39402 fixed this PR indeed. Thanks.

**Comment by xu-cheng** [comment]
Thanks @vszakats

**Pull request closed without merging**
