### PR TITLE
Update formulae to use special rbenv dependency

### PR DESCRIPTION
**Pull request by DomT4**
I like (and use) `rbenv` and I hate PRs that are left open. In combination, this PR was born.

CC @mikemcquaid @mislav.

Closes #47336.

### CODE REVIEW

**Comment by DomT4** [comment]
Not really sure why this failed the CI. It passes locally with `brew uses`, `brew install`, `brew readall`, and so on.

**Comment by DomT4** [comment]
Unless it's trying to build from most to least recent commit, i.e. before the `rbenv` requirement has been created, but as far as I know that wouldn't be expected/standard?

**Comment by mikemcquaid** [comment]
@DomT4 The issue is in the `test-bot` itself. Would be great to try a fix or alternatively split core/formula changes into separate PRs.

**Comment by mislav** [comment]
@DomT4 Thanks for tackling this! :bow:

**Comment by DomT4** [comment]
@mikemcquaid Did we introduce a regression there at some point? I seem to remember being able to do this sort of thing with prior special dependencies, but perhaps I'm misremembering. Debugging locally isn't possible at the moment because `brew test-bot` hangs on the `uses --recursive` element due to the prior discussed issue, which I'll try and poke around with more today. I may split this as a workaround and then create a "fake" PR with a fake special dependency to play with it some more.

@mislav No worries! Use `rbenv` as my daily Ruby driver, so happy to give some ease-of-life back  :wink:

**Comment by DomT4** [comment]
Span the core change off into it's own PR in https://github.com/Homebrew/homebrew/pull/47897. Will merge that (after it has passed CI), rebase this and then merge.

**Comment by DomT4** [comment]
I'll fix the two test CI failures afterwards; only minor `assert_include` grumbles.

**Comment by DomT4** [comment]
Alright, this is done :tada:

**Comment by UniqMartin** [comment]
I suspect this change is responsible for the following output?

```
$ brew update
Updated Homebrew from 565ce432 to 81f8dd1e.
Error: Unsupported special dependency :rbenv
Error: Unsupported special dependency :rbenv
Error: Unsupported special dependency :rbenv
Error: Unsupported special dependency :rbenv
Error: Unsupported special dependency :rbenv
Error: Unsupported special dependency :rbenv
Error: Unsupported special dependency :rbenv
Error: Unsupported special dependency :rbenv
Error: Unsupported special dependency :rbenv
Error: Unsupported special dependency :rbenv
Error: Unsupported special dependency :rbenv
Error: Unsupported special dependency :rbenv
Error: Unsupported special dependency :rbenv
==> New Formulae
spaceman-diff
==> Updated Formulae
doxygen                       nexus                         rbenv-bundler-ruby-version    rbenv-use
enca                          postgis                       rbenv-communal-gems           rbenv-vars
gnutls                        rbenv-aliases                 rbenv-ctags                   rbenv-whatis
itstool                       rbenv-binstubs                rbenv-default-gems            stunnel
libodfgen                     rbenv-bundle-exec             rbenv-gemset                  youtube-dl
libxmp-lite                   rbenv-bundler                 rbenv-readline
==> Deleted Formulae
ffts                                                         perlmagick
```

**Comment by DomT4** [comment]
Sigh. Why does Homebrew hate me sometimes. It worked (and works) locally but I wasn't updating, just merging in the code and then running `brew update`.

Does `brew update` read the new files backwards or something? :confounded:. If you do `brew install rbenv-gemset` there's no actual runtime problem. Frustrating. This feels like a core bug.

**Comment by mikemcquaid** [comment]
> Does brew update read the new files backwards or something? . If you do brew install rbenv-gemset there's no actual runtime problem. Frustrating. This feels like a core bug.

@DomT4 It is a core bug as it's not reloading `require`d files. Still maybe worth finding a workaround. @xu-cheng any ideas?

**Comment by mikemcquaid** [comment]
Will be fixed by https://github.com/Homebrew/homebrew/pull/47380 (when I eventually get it done)

**Comment by UniqMartin** [comment]
I believe this might be the same reason why it originally failed. In case of `brew update` it's the same reason for many other update-related issues, namely that `dependency_collector.rb` is loaded before the update pulls in the updated version of this file and the formulae that use it.

**Comment by UniqMartin** [comment]
I guess the errors are only visible because I have `HOMEBREW_DEVELOPER` set? In which case normal users would be fine, I guess.

> Will be fixed by #47380 (when I eventually get it done)

Yes, exactly.

**Comment by DomT4** [comment]
> I guess the errors are only visible because I have HOMEBREW_DEVELOPER set? In which case normal users would be fine, I guess.

Lord I hope so. I'd rather not deal with another bug 300 users report to us across 2 months of updates :smile:

Welcome thoughts if Xu has them. I think between him & Mike they've been the ones most frequently working on the problems with `update` using Ruby code. Agree life will be a happier place when we're no longer leaning on Ruby for the initial update process.

**Comment by DomT4** [comment]
Checked my ML VM which isn't set up in developer mode. Error isn't printed there, so regular users shouldn't see anything. Small silver lining.

**Comment by UniqMartin** [comment]
> Lord I hope so. I'd rather not deal with another bug 300 users report to us across 2 months of updates :smile:

I just checked and that's the case (i.e. no error for normal users). The only slightly annoying thing for them will be, that all those `rbenv-` formulae will appear as if they were updated in the report generated by `brew update`, because it failed to load them to extract the version number.

**Comment by DomT4** [comment]
If I had to trigger a core bug, one that most users will only see as something having an update available isn't the worst in the world, I guess. It used to be our default to load the `update` message for any formula change rather than only version/revision, so perhaps people won't notice :sweat:.

**Comment by UniqMartin** [comment]
Anyway, sorry for raising (somewhat) false alarm! Nothing really bad has happened after all. :smile:

**Comment by DomT4** [comment]
Aha, It's fine. I'm thankful you mentioned it. Will remind myself to scale back these sorts of changes as much as possible until we address the underlying core issue around the update mechanism.

**Pull request closed without merging**
