### PR TITLE
Add auditing as necessary step before submitting new formulae to "Formula-Cookbook.md"

### PR DESCRIPTION
**Pull request by maijs**
Travis CI runs `brew audit [formula]` check with `--strict` option which results in more scrupulous test. Formula creators should be aware of this fact and make sure `brew audit --strict [formula]` returns no errors before they create pull request.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
That's only necessary for new formulae in which case `--online` should also be used.

**Comment by maijs** [comment]
I concur. `--online` option added.

**Comment by mikemcquaid** [comment]
Sorry, to clarify: `--strict --online` are only required for new formulae submissions, not all formulae updates.

**Comment by maijs** [comment]
@mikemcquaid, thanks for clarification. Moved the instructions to `Formula-Cookbook.md` which addresses new formulae specifically.

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
