### PR TITLE
d-bus 1.8.20, 1.9.20 (devel)

### PR DESCRIPTION
**Pull request by dunn**

### CODE REVIEW

**Comment by mikemcquaid** [comment]
:+1:

**Comment by dunn** [comment]
Haven't forgotten about this, just a bit mystified by the failure.

**Comment by DomT4** [comment]
99% sure your failure is related to [this](https://github.com/Homebrew/homebrew/issues/41501#issuecomment-129262725).

**Comment by dunn** [comment]
Aha, looks like it.

**Comment by DomT4** [comment]
If we merge it, will be fixed in #43165.

**Comment by dunn** [comment]
I'm fine waiting for that PR.

**Pull request closed without merging**
