### PR TITLE
pulseaudio 8.0

### PR DESCRIPTION
**Pull request by rakkesh**

### CODE REVIEW

**Comment by rakkesh** [comment]
Leaving the two current patches as they are,
* `pulseaudio` builds fine without the Xcode-only patch on an CLT-only machine but the [bug](https://bugs.freedesktop.org/show_bug.cgi?id=55152) is not closed yet.
* not sure about the `i386` patch as I don't have a machine with that architecture at the moment.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/8c7901af4c501259df8cef5fecc825dd2f3c0947, https://github.com/Homebrew/homebrew/commit/618c707af01057fff535110367e3ddff84b1e3e2 & https://github.com/Homebrew/homebrew/commit/d01d52d8168cea48ff3c823a6b43fa5a46019fb9.

Thank you for your contributions to Homebrew @rakkesh! :smiley_cat:. If you're feeling particularly kind you could check if `i3status` in the X11 tap needs a revision bump as well :)

**Comment by rakkesh** [comment]
@DomT4 `i3status` doesn't seem to link with any of the `pulseaudio` libraries ( `libpulse.0.dylib` or `libpulse-simple.0.dylib`).

```
$ otool -L /usr/local/Cellar/i3status/2.9/bin/i3status
/usr/local/Cellar/i3status/2.9/bin/i3status:
	/usr/local/opt/confuse/lib/libconfuse.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/opt/yajl/lib/libyajl.2.dylib (compatibility version 2.0.0, current version 2.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
```

**Comment by DomT4** [comment]
Oh, weird. It has a mandatory/recommended dependency if I remember correctly. Perhaps that's only runtime rather than build.

**Comment by rakkesh** [comment]
Then all is fine, `i3status`, poured from bottle doesn't fail when executed in the presence of an updated version of `pulseaudio`.

```
$ i3status
Unable to find the configuration file (looked at ~/.i3status.conf, $XDG_CONFIG_HOME/i3status/config, /etc/i3status.conf and $XDG_CONFIG_DIRS/i3status/config)
```

**Comment by rakkesh** [comment]
I am not quite sure if that is a valid functional test. If you have a config which you can share, I can test it out.

**Comment by DomT4** [comment]
:+1:, Thanks for checking. I've no idea to be honest, I don't use that particular piece of software.

**Pull request closed without merging**
