### PR TITLE
Fixes wrong scons' sha256.

### PR DESCRIPTION
**Pull request by linjunpop**

### CODE REVIEW

**Comment by DomT4** [comment]
Can we ask upstream why the SHA has changed here? Thanks.

**Comment by tdsmith** [comment]
Looks legit; http://article.gmane.org/gmane.comp.programming.tools.scons.user/26929

**Comment by DomT4** [comment]
Thanks Tim :bow:. Would be nice if they'd bump the version very slightly in these situations rather than silently changing the SHA :/.

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

For future reference the preferred commit message format is `scons: fix sha256.`.

**Pull request closed without merging**
