### PR TITLE
updating to latest rethinkdb version

### PR DESCRIPTION
**Pull request by Gutek**
update to 2.1.4 version

### CODE REVIEW

**Comment by ablyler** [comment]
@mikemcquaid it looks like the build for this is taking 2+ hours on OS X 10.11 due to boost not having a bottle. can we create a bottle manually for boost to speed this up?

**Comment by mikemcquaid** [comment]
@ablyler We're working on it.

**Comment by ablyler** [comment]
@mikemcquaid great, let me know if there is anything I can do to help.

**Comment by mikemcquaid** [comment]
I've requeued the CI now we have a `boost` bottle.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/90e198e881533dd0dccaeedece1a6f3902e72d5e. Thank you for your contribution to Homebrew @Gutek!

**Comment by robconery** [comment]
Nice @Gutek thank you for this!

**Pull request closed without merging**
