### PR TITLE
Google App Engine (Python) `1.9.23` => `1.9.26`

### PR DESCRIPTION
**Pull request by brianmhunt**

### CODE REVIEW

**Comment by dunn** [comment]
Any chance of a test while you're at it? Just something that checks basic functionality would be great.

**Comment by brianmhunt** [comment]
@dunn I would certainly enjoy writing a test but I've never written in Ruby before, and am not sure how homebrew does its testing.

That said, a basic test might be along the lines of:

```sh
$ env PYTHONPATH=/usr/local/share/google-app-engine python -m
  google.appengine.base.capabilities_pb
```

(where `base.capabilities_pb` is just an arbitrary python module in AppEngine).  This'll exit with a non-zero status code when app-engine is (basically) not working (in the sense that the builtin Python cannot include it).

**Comment by dunn** [comment]
This is how you'd write that:
```
  test do
    ENV["PYTHONPATH"] = pkgshare
    system "python", "-m", "google.appengine.base.capabilities_pb"
  end
```
But when I run it I get `/usr/local/opt/python/bin/python2.7: No module named appengine.base`.

**Comment by brianmhunt** [comment]
Thanks @dunn —

I'm not sure what the `pkgshare` value is, but when I explicitly set the environment to `PYTHONPATH=/usr/local/Cellar/app-engine-python/1.9.23/share/google-app-engine` then the exit code is 0 when I try it.

What is the `pkgshare` value?

**Comment by dunn** [comment]
The value of `pkgshare` is `/usr/local/Cellar/app-engine-python/1.9.23/share/app-engine-python`.  When I installed this formula I didn't have a directory in `share` called `google-app-engine`, just `app-engine-python`.

**Comment by brianmhunt** [comment]
Perhaps the discrepancy is because I upgraded from the prior [`google-app-engine`](https://github.com/hanxue/homebrew/blob/dd7536b2572d19233e758bf6fe77afb32d2f3e4e/Library/Formula/google-app-engine.rb) formula (per the [renames](https://github.com/Homebrew/homebrew/blob/d69099b1c2c0047440de63176af165deff5fac2c/Library/Homebrew/formula_renames.rb))?

In any case, there should definitely be some sort of symlink e.g. `/usr/local/share/google-app-engine` ➡ `/usr/local/Cellar/app-engine-python/{{ VERSION e.g. 1.9.26 }}/share/google-app-engine`

When that symlinking exists, exporting that as the `PYTHONPATH` and running the `python -m` test should work as expected.  Sorry I cannot offer a PR but I can only guess how Ruby/formula would properly do the symlink.

**Comment by bfontaine** [comment]
This PR needs to be rebased on top of `master`.

**Comment by bfontaine** [comment]
Ping?

**Comment by bfontaine** [comment]
Closing due to no response. Feel free to open another PR addressing the comments above. Thanks!

**Pull request closed without merging**
