### PR TITLE
Disable MMX. Clang in 10.11 doesn't support the inline assembly. 

### PR DESCRIPTION
**Pull request by shaneburrell**
Upstream has been notified.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
@shaneburrell Let's disable this just for 10.11 for now, thanks.

**Comment by shaneburrell** [comment]
That should get it.

**Comment by DomT4** [comment]
Let's not dupe the whole arguments just for 10.11. You can do something like this:

```ruby
args = %W[
  --disable-dependency-tracking
  --prefix=#{prefix}
  --another-arg
  --and-another
  --so-on
]

args <<  "--disable-mmx" if MacOS.version >= :el_capitan
```

**Comment by shaneburrell** [comment]
Changed to args and optionally disable mmx if >= el_capitan.

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

For future reference the preferred commit message format is `pixman: disable MMX on 10.11.`.

**Pull request closed without merging**
