### PR TITLE
afl-fuzz 1.97b

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by alex** [comment]
Tests failing, and I don't quite understand why.

**Comment by DomT4** [comment]
The actual test failure is the `test do` block, which fails locally too:
```
==> /usr/local/Cellar/afl-fuzz/1.97b/bin/afl-clang++ -g /private/tmp/afl-fuzz20160210-462-1n8sxbt/main.cpp -o /private/tmp/afl-fuzz20160210-462-1n8sxbt/test
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-007cae.s:2:Unknown pseudo-op: .macosx_version_min
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-007cae.s:2:Rest of line ignored. 1st junk character valued 49 (1).
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-007cae.s:66:Unknown pseudo-op: .cfi_startproc
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-007cae.s:70:Unknown pseudo-op: .cfi_def_cfa_offset
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-007cae.s:70:Rest of line ignored. 1st junk character valued 49 (1).
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-007cae.s:72:Unknown pseudo-op: .cfi_offset
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-007cae.s:72:Rest of line ignored. 1st junk character valued 37 (%).
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-007cae.s:75:Unknown pseudo-op: .cfi_def_cfa_register
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-007cae.s:75:Rest of line ignored. 1st junk character valued 37 (%).
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-007cae.s:93:Unknown pseudo-op: .cfi_endproc
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-007cae.s:102:Unknown pseudo-op: .cfi_startproc
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-007cae.s:103:Unknown pseudo-op: .cfi_personality
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-007cae.s:103:Rest of line ignored. 1st junk character valued 49 (1).
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-007cae.s:104:Unknown pseudo-op: .cfi_lsda
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-007cae.s:104:Rest of line ignored. 1st junk character valued 49 (1).
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-007cae.s:108:Unknown pseudo-op: .cfi_def_cfa_offset
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-007cae.s:108:Rest of line ignored. 1st junk character valued 49 (1).
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-007cae.s:110:Unknown pseudo-op: .cfi_offset
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-007cae.s:110:Rest of line ignored. 1st junk character valued 37 (%).
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-007cae.s:113:Unknown pseudo-op: .cfi_def_cfa_register
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-007cae.s:113:Rest of line ignored. 1st junk character valued 37 (%).
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-007cae.s:121:Unknown pseudo-op: .cfi_offset
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-007cae.s:121:Rest of line ignored. 1st junk character valued 37 (%).
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-007cae.s:123:Unknown pseudo-op: .cfi_offset
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-007cae.s:123:Rest of line ignored. 1st junk character valued 37 (%).
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-007cae.s:125:Unknown pseudo-op: .cfi_offset
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-007cae.s:125:Rest of line ignored. 1st junk character valued 37 (%).
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-007cae.s:127:Unknown pseudo-op: .cfi_offset
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-007cae.s:127:Rest of line ignored. 1st junk character valued 37 (%).
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-007cae.s:129:Unknown pseudo-op: .cfi_offset
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-007cae.s:129:Rest of line ignored. 1st junk character valued 37 (%).
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-007cae.s:408:Unknown pseudo-op: .cfi_endproc
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-007cae.s:515:Unknown pseudo-op: .cfi_startproc
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-007cae.s:516:Unknown pseudo-op: .cfi_personality
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-007cae.s:516:Rest of line ignored. 1st junk character valued 49 (1).
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-007cae.s:517:Unknown pseudo-op: .cfi_lsda
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-007cae.s:517:Rest of line ignored. 1st junk character valued 49 (1).
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-007cae.s:521:Unknown pseudo-op: .cfi_def_cfa_offset
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-007cae.s:521:Rest of line ignored. 1st junk character valued 49 (1).
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-007cae.s:523:Unknown pseudo-op: .cfi_offset
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-007cae.s:523:Rest of line ignored. 1st junk character valued 37 (%).
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-007cae.s:526:Unknown pseudo-op: .cfi_def_cfa_register
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-007cae.s:526:Rest of line ignored. 1st junk character valued 37 (%).
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-007cae.s:534:Unknown pseudo-op: .cfi_offset
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-007cae.s:534:Rest of line ignored. 1st junk character valued 37 (%).
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-007cae.s:536:Unknown pseudo-op: .cfi_offset
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-007cae.s:536:Rest of line ignored. 1st junk character valued 37 (%).
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-007cae.s:538:Unknown pseudo-op: .cfi_offset
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-007cae.s:538:Rest of line ignored. 1st junk character valued 37 (%).
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-007cae.s:540:Unknown pseudo-op: .cfi_offset
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-007cae.s:540:Rest of line ignored. 1st junk character valued 37 (%).
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-007cae.s:542:Unknown pseudo-op: .cfi_offset
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-007cae.s:542:Rest of line ignored. 1st junk character valued 37 (%).
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-007cae.s:818:Unknown pseudo-op: .cfi_endproc
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-007cae.s:874:Unknown pseudo-op: .cfi_startproc
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-007cae.s:878:Unknown pseudo-op: .cfi_def_cfa_offset
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-007cae.s:878:Rest of line ignored. 1st junk character valued 49 (1).
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-007cae.s:880:Unknown pseudo-op: .cfi_offset
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-007cae.s:880:Rest of line ignored. 1st junk character valued 37 (%).
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-007cae.s:883:Unknown pseudo-op: .cfi_def_cfa_register
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-007cae.s:883:Rest of line ignored. 1st junk character valued 37 (%).
/var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/main-007cae.s:887:Unknown pseudo-op: .cfi_endproc
clang: error: assembler command failed with exit code 1 (use -v to see invocation)
Error: afl-fuzz: failed
Failed executing: /usr/local/Cellar/afl-fuzz/1.97b/bin/afl-clang++ -g /private/tmp/afl-fuzz20160210-462-1n8sxbt/main.cpp -o /private/tmp/afl-fuzz20160210-462-1n8sxbt/test
```

**Comment by alex** [comment]
@DomT4 locally meaning on `master`, or locally with this PR?

**Comment by DomT4** [comment]
Locally with this PR. I pulled it and tested it to make sure it wasn't just CI behaving unusually.

**Comment by alex** [comment]
Ok, I'll pass this along to upstream to see if they're aware.

On Wed, Feb 10, 2016 at 11:31 AM, Dominyk Tiller <notifications@github.com>
wrote:

> Locally with this PR. I pulled it and tested it to make sure it wasn't
> just CI behaving unusually.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Homebrew/homebrew/pull/49022#issuecomment-182463926>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by DomT4** [comment]
Closing in favour of #49113, but that still has a broken test apparently. Feel free to dump any info from upstream there and hopefully we'll somehow get to the bottom of it.

**Pull request closed without merging**
