### PR TITLE
Isolate formula class namespaces

### PR DESCRIPTION
**Pull request by jacknagel**
Addresses #40151

### CODE REVIEW

**Comment by xu-cheng** [comment]
:+1:

**Comment by mikemcquaid** [comment]
I guess it's an implementation detail so we don't need to care but: what's used to create the `Module`; the full path to the formula/tap?

**Comment by mikemcquaid** [comment]
Otherwise: LGTM

**Comment by jacknagel** [comment]
In this updated implementation, the formula file is `module_eval`'d inside the module and then the formula class is cached directly. The full path is used as the key, so we only need to do one hash lookup at runtime (as opposed to a normal hash lookup plus a `const_get`, which is also a hash lookup, in the earlier implementation).

**Pull request closed without merging**
