### PR TITLE
rubber 1.2

### PR DESCRIPTION
**Pull request by dunn**
I think a real test will require TeX.

### CODE REVIEW

**Comment by dunn** [comment]
Should've seen this coming:
```
$ brew outdated
rubber (1.2 < 20100306)
```

**Comment by DomT4** [comment]
Meh. Put in a fake version using the release date.

**Comment by bfontaine** [comment]
You could use `20150625-1.2`.

**Comment by DomT4** [comment]
:boat:'ed in https://github.com/Homebrew/homebrew/commit/e402aeacfb9b763c1532b1a81696d33e3099c673. Thanks!

**Pull request closed without merging**
