### PR TITLE
pulledpork: add head

### PR DESCRIPTION
**Pull request by Drewshg312**
Adding a `head` option to `pulledpork` formula
new version of pulledpork - 0.7.1 is available

### CODE REVIEW

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/891f6e3707842a7898f1eab3c196ad843ff77cf0. Thank you @Drewshg312, we appreciate your contribution to Homebrew! :smiley_cat:

**Comment by Drewshg312** [comment]
Lol) thanx for help guys!

**Comment by Drewshg312** [comment]
seems like my pull request didn't work lol))) pulledpork still not updated for some reason....

**Comment by DomT4** [comment]
It works okay for me locally. Make sure you `brew update` and then try `brew install pulledpork --HEAD`.

**Comment by Drewshg312** [comment]
oh yeah! True - it works.. just confused  because `brew info pulledpork` still says `pulledpork: stable 0.7.0, HEAD` instead of `0.7.1`

**Comment by DomT4** [comment]
Yeah, until they actually formally release 0.7.1 the latest "version" is still 0.7.0, but the `HEAD` is 0.7.1, or whatever upstream have in their svn repo at the moment.

**Comment by Drewshg312** [comment]
I see! Thank you!

**Pull request closed without merging**
