### PR TITLE
jump 0.7.1

### PR DESCRIPTION
**Pull request by gsamokovarov**
With Go 1.6 out, comes jump 0.7.1 as well. Minor improvements around
file locking and performance.

### CODE REVIEW

**Comment by dunn** [comment]
The test is failing unfortunately:
```
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20160219-11720-2vqrol.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Library/Homebrew -- /usr/local/Library/Homebrew/test.rb /usr/local/Library/Formula/jump.rb --verbose
==> /usr/local/Cellar/jump/0.7/bin/jump chdir /private/tmp/jump20160219-11721-1yay7al/test_dir
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0xa183e]

goroutine 1 [running]:
panic(0x17f4a0, 0xc8200140d0)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:464 +0x3e6
github.com/gsamokovarov/jump/scoring.(*Entries).Find(0x0, 0x7fff5fbff072, 0x30, 0x0, 0x0)
	/private/tmp/jump20160219-11528-19d20ya/jump-0.7.0/src/github.com/gsamokovarov/jump/scoring/entries.go:28 +0x17e
github.com/gsamokovarov/jump/cmd.updateCmd(0xc82000a410, 0x1, 0x1, 0xc82000a600)
	/private/tmp/jump20160219-11528-19d20ya/jump-0.7.0/src/github.com/gsamokovarov/jump/cmd/chdir.go:27 +0x2a6
main.main()
	/private/tmp/jump20160219-11528-19d20ya/jump-0.7.0/main.go:24 +0x558
Error: jump: failed
Failed executing: /usr/local/Cellar/jump/0.7/bin/jump chdir /private/tmp/jump20160219-11721-1yay7al/test_dir
/usr/local/Library/Homebrew/formula.rb:1483:in `block in system'
/usr/local/Library/Homebrew/formula.rb:1420:in `open'
/usr/local/Library/Homebrew/formula.rb:1420:in `system'
/usr/local/Library/Formula/jump.rb:30:in `block in <class:Jump>'
/usr/local/Library/Homebrew/formula.rb:1329:in `block in run_test'
/usr/local/Library/Homebrew/extend/fileutils.rb:35:in `mktemp'
/usr/local/Library/Homebrew/formula.rb:1325:in `run_test'
/usr/local/Library/Homebrew/test.rb:28:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/usr/local/Library/Homebrew/test.rb:27:in `<main>'

**Comment by gsamokovarov** [comment]
Holy moly. Fixed that for `0.7.1`.

**Comment by dunn** [comment]
The version was getting parsed wrong; I fixed it, but we need to rebuild the bottles, so that's queued up again.

**Comment by gsamokovarov** [comment]
Hey, I think I hit that with `0.6.1` too. Sorry for the sloppy release and thanks for helping me getting it through!

**Comment by dunn** [comment]
Oh, dang, this PR needs to be rebased against the current master in order to get the new parsing logic.  Could you do that? Sorry!

**Comment by gsamokovarov** [comment]
Sure! Rebased it.

**Comment by dunn** [comment]
Thanks for your patience! Merged in d4fc7f9b8820b05274aa282f7169c7e6f356acef.

**Pull request closed without merging**
