### PR TITLE
build#install: install metafiles from buildpath

### PR DESCRIPTION
**Pull request by dunn**
This came up in https://github.com/Homebrew/homebrew-emacs/pull/158#issuecomment-172031003;  `install_metafiles` is passed the current directory, which can be changed during installation by `Dir.chdir`.

There may be cases where the metafiles are in a subdirectory, but my
guess is those are rare and this is brittle and undocumented behavior
anyway.

### CODE REVIEW

**Comment by dunn** [comment]
Writing tests for this would require updating the testballs; is that worth it?

**Comment by mikemcquaid** [comment]
@dunn Probably but feel free to pass.

**Comment by dunn** [comment]
Oh, good idea.

Also (and this suggests I need to be writing more tests) `brew tests` is failing for me locally with these errors: https://gist.github.com/dunn/1b4fc5297a693be3742d  Do I need to tweak my environment, or is this unexpected?

**Comment by bfontaine** [comment]
@dunn This looks like an issue on your side because the tests pass on Travis.

**Comment by mikemcquaid** [comment]
Makes sense :+1:

**Comment by tdsmith** [comment]
lgtm

**Pull request closed without merging**
