### PR TITLE
add Formula.racks

### PR DESCRIPTION
**Pull request by xu-cheng**
Also exclude symlink when enumerating installed racks.

cc @mikemcquaid  @viktorahlstrom

### CODE REVIEW

**Comment by mikemcquaid** [comment]
:+1: except for naming; I don't know if it's obvious what `racks` does or means.

**Comment by xu-cheng** [comment]
The name is a little tricking. I think we should address it in https://github.com/Homebrew/homebrew/issues/41884 

But if we have a glossary in the document, `racks` seem to be the best name out there.

**Comment by mikemcquaid** [comment]
I don't agree here. I don't really understand what a "rack" is and I've been working on Homebrew for 6+ years now. We don't really expose that name to users.

**Comment by xu-cheng** [comment]
What name do you suggestion here? In all, I would like to avoid a too general name, so we won't end up use a whole sentence instead of a word when referring to this in the future discussion.

**Comment by mikemcquaid** [comment]
`cellar_subdirs`

**Comment by xu-cheng** [comment]
I think that would be even worse and more confusing name, especially we already have methods like `Formulary#from_rack` and `Formulary#to_rack`

**Comment by mikemcquaid** [comment]
Ok, up to you. I'd still like to move away from `rack` as terminology as I don't think it's obvious what it means (and I think having a glossary to have to explain to Homebrew maintainers that "rack" means "Cellar subdirectories" is weird)

**Pull request closed without merging**
