### PR TITLE
Update FAQ.md

### PR DESCRIPTION
**Pull request by ianrrees**
The uninstall gist has several problems, such as not removing brew taps...

### CODE REVIEW

**Comment by mikemcquaid** [comment]
I'd probably rather we removed it instead and/or moved the script to the Homebrew/install repo as `uninstall` and then improved it there so it worked.

**Comment by ianrrees** [comment]
Makes sense - I'm new to homebrew so didn't want to suggest anything too drastic right off the bat.

**Comment by mikemcquaid** [comment]
@Homebrew/owners What do you think about moving the uninstall script into the `install` repo?

**Comment by tdsmith** [comment]
It probably needs some love and having it someplace more formal than a gist sounds helpful. Would we like to see a `brew selfdestruct` command someday?

**Comment by DomT4** [comment]
@tdsmith If it's useful, I've done some more work on #31860 locally. I can always reopen that PR.

**Comment by DomT4** [comment]
Opened #37713 for discussion, as desired.

**Comment by denji** [comment]
[GPGPTools](https://gpgtools.org/) installs itself in /usr/local/ need to re-reinstall to work correctly the command line tools.

**Comment by xu-cheng** [comment]
Closes this to in favor of #38457

**Pull request closed without merging**
