### PR TITLE
sshguard: add warning to caveats, modernize

### PR DESCRIPTION
**Pull request by asparagui**
add warning about security issue. thanks kkauder!

Closes #38080.

### CODE REVIEW

**Comment by DomT4** [comment]
I have no say on this, and Mike has already voiced his opinion against the idea, but personally I'd rather include the patch and revision or ban installing it on Yosemite completely. The gaping security hole ain't so pretty.

**Comment by asparagui** [comment]
If dev has indeed stopped, then should we boneyard sshguard?

**Comment by DomT4** [comment]
It doesn't seem to be dead per se, the dev work has just shifted off of SF. They seem to be working on it in [Bitbucket now](https://bitbucket.org/sshguard/sshguard/). It seems to be official - Same devs as the SF code, and there's a link to the Bitbucket website on the [Sourceforge page](http://sourceforge.net/projects/sshguard/). We might be able to open the issue on that Bitbucket rather than leaving it to sit on the mailing list and get them to merge the patch or a version of it.

**Comment by tdsmith** [comment]
some notes in #38006

**Comment by DomT4** [comment]
@tdsmith - Nice! Guess we could just add it as a patch then, ` https://bitbucket.org/sshguard/sshguard/commits/fc01ad308c10ceb4164e23967b4713b9e7e533d7/raw/ `. Meets the usual guideline of "patch must be accepted before use", and means we can cover the hole until the new release is cut.

**Comment by asparagui** [comment]
Closing per above discussion.

**Pull request closed without merging**
