### PR TITLE
Monit 5.13

### PR DESCRIPTION
**Pull request by tcwalther**
Updated Monit to 5.13. I am not sure how to update the bottled sections - this is my first homebrew commit, and the Wiki says I should leave the `bottled do` part up to you - so right now it compiles from source.

### CODE REVIEW

**Comment by xu-cheng** [comment]
Thanks for the pull request! 🎉 Homebrew depends on contributions from community members like you and we're grateful for your support.

**Comment by tcwalther** [comment]
@xu-cheng sure, you're welcome. Can you explain why you closed the ticket, but didn't merge the branch? Is there something I can do to get my pull request accepted?

**Comment by xu-cheng** [comment]
I already merged your commit in https://github.com/Homebrew/homebrew/commit/129d47c48fe0fd4da69d2f7707adb7b74ed8bc78. We don't use Github merge button to keep git log clean.

**Comment by tcwalther** [comment]
Thanks so much for the info, and of course also for the merge =).

**Pull request closed without merging**
