### PR TITLE
prefixsuffix 0.6.6 (new formula)

### PR DESCRIPTION
**Pull request by tschoonj**

### CODE REVIEW

**Comment by tschoonj** [comment]
Not sure how this warning applies here: it's a project hosted by GNOME. It's also packaged by Ubuntu.

**Comment by dunn** [comment]
I'd be fine ignoring the audit in this case.

**Comment by tschoonj** [comment]
@DomT4 Can you merge this in please? 

Thanks!

**Comment by DomT4** [comment]
Feel free to ping other maintainers as well, I don't want to hog all the helpfulness :trollface:.

Merged in https://github.com/Homebrew/homebrew/commit/b1eb59a18f637546e43d5612554c796b43ad161f. Thanks again Tom!

**Pull request closed without merging**
