### PR TITLE
bump libyubikey, ykpers, yubico-piv-tool, and add ykneomgr

### PR DESCRIPTION
**Pull request by jesboat**

### CODE REVIEW

**Comment by jacknagel** [comment]
ping again

**Comment by jacknagel** [comment]
Updates applied in a3aaf1f, 467b67d, and f53e3f4. Feel free to resubmit ykneomgr in a new PR.

**Comment by forkbomber** [comment]
@mikemcquaid, @jacknagel would you consider inclusion of ykneomgr.rb in its current form?
It is more than 6 months since original commit and it is unlikely that author would continue working on tests for ykneomgr.rb.
I feel like community would be better off having a formula with simplest tests (--version) than no formula at all.

**Comment by mikemcquaid** [comment]
@forkbomber I'd like a test but a simple test is better than nothing, yup.

**Comment by LukeHoersten** [comment]
Any progress on this?

**Comment by mikemcquaid** [comment]
@LukeHoersten No. You could submit a PR yourself. Thanks!

**Comment by forkbomber** [comment]
@mikemcquaid - see #45572 with "--version" test as agreed.

**Pull request closed without merging**
