### PR TITLE
Upgrading RocksDB to 3.13

### PR DESCRIPTION
**Pull request by marpaia**

### CODE REVIEW

**Comment by dunn** [comment]
The test is failing on Mavericks and Yosemite, but not Mountain Lion: http://bot.brew.sh/job/Homebrew%20Pull%20Requests/32438/

**Comment by marpaia** [comment]
Yeah, I saw that. I'm also the maintainer of the osquery package, which seems to install fine, but the tests don't pass. That's odd, the tests are a little janky for osquery right now, so I'm going to rework those a bit and see if there's a difference.

**Comment by marpaia** [comment]
Is there something going on with the build system lately? I noticed that it asked for new permission to just _view_ the tests and they're taking hours to run, which hasn't historically been that much of a problem with homebrew, as far as I can recall.

**Comment by dunn** [comment]
We've just got a backlog right now, so tests are sitting in the queue waiting to start.

We don't have control over the permissions changes, unfortunately, but you've always needed to grant some permissions to view test results.

**Comment by DomT4** [comment]
It's been a very busy few days for the CI. There's been a lot of stuff being processed that aren't short builds (Yesterday alone we had three builds time out at the 2 hour mark).

The new permissions Jenkins asks for are actually a downgrade on the permission level it had previously, so if you've ever authorised the test-bot it's more or less asking your permission to downgrade its privilege level.

**Comment by marpaia** [comment]
Always appreciate a double reply :) Sorry to hear about the build being backed up.

**Comment by DomT4** [comment]
The `osquery` test failed:

```
clang -cc1 version 6.1.0 based upon LLVM 3.6.0svn default target x86_64-apple-darwin14.5.0
ignoring nonexistent directory "/usr/include/c++/v1"
ignoring duplicate directory "/usr/local/include"
  as it is a non-system directory that duplicates a system directory
#include "..." search starts here:
#include <...> search starts here:
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1
 /usr/local/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/6.1.0/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
 /usr/include
 /System/Library/Frameworks (framework directory)
 /Library/Frameworks (framework directory)
End of search list.
In file included from test.cpp:1:
In file included from /usr/local/include/osquery/sdk.h:25:
/usr/local/include/osquery/logger.h:16:10: fatal error: 'glog/logging.h' file not found
#include <glog/logging.h>
         ^
1 error generated.
Error: osquery: failed
Failed executing: /usr/bin/clang++ test.cpp -o test -v -std=c++11 -losquery -lthrift -lboost_system -lboost_thread-mt -lboost_filesystem -lglog -lrocksdb
```

**Comment by marpaia** [comment]
any idea why that's failing? the osquery brew package depends on glog, so it should be there during the test, no?

**Comment by DomT4** [comment]
`osquery` seems to depend on `gflags` but not `glog`? I have neither glog nor gflags installed and running `brew install -v --only-dependencies osquery` gets me:

```
==> Installing dependencies for osquery: snappy, rocksdb, thrift, yara, gflags
```

**Comment by marpaia** [comment]
good call, added that, we'll see what happens

**Comment by marpaia** [comment]
Oh cool, look at that, we passed :) That old test for osquery was janky, I'm still not sure why it was failing, but this new one is a better test and it's passing, so I'm cool with it.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/870e565ed8c72743011c9558699060a7e96ddf27 & https://github.com/Homebrew/homebrew/commit/5c32cb6c4bd92a90e4da4f9fabca982259a6b725. Thank you @marpaia!

**Pull request closed without merging**
