### PR TITLE
botan 1.10.10, 1.11.19 (devel)

### PR DESCRIPTION
**Pull request by dunn**

### CODE REVIEW

**Comment by dunn** [comment]
https://github.com/randombit/botan/issues/241

**Comment by mikemcquaid** [comment]
Audit failure due to incorrect dylib names: http://bot.brew.sh/job/Homebrew%20Pull%20Requests/31048/version=yosemite/testReport/junit/brew-test-bot/yosemite/audit___devel_botan/

Otherwise :+1:

**Comment by dunn** [comment]
They say they'll rename them in the next release; should I merge now or wait for that?

**Comment by mikemcquaid** [comment]
@dunn Merge now :+1:

**Pull request closed without merging**
