### PR TITLE
why3 0.85 (new formula)

### PR DESCRIPTION
**Pull request by bfontaine**
[Why3](http://why3.lri.fr/) “is a platform for deductive program verification.” It’s maintained (last commit was four days ago) and popular.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Installation failing: http://bot.brew.sh/job/Homebrew%20Pull%20Requests/20544/version=yosemite/testReport/junit/brew-test-bot/yosemite/install_why3/

**Comment by bfontaine** [comment]
@mikemcquaid Fixed. I tried a lot of different things yesterday but the solution was to use a build in two steps (`make` then `make install`).

**Comment by mikemcquaid** [comment]
Nice work!

**Comment by mikemcquaid** [comment]
Thanks @bfontaine!

**Pull request closed without merging**
