### PR TITLE
PhantomJS 2.0.0

### LINKED ISSUE #36240: phantomjs 2.0.0
Not sure about the current status of `phantomjs`, but there is a new 2.0.0 release: https://github.com/ariya/phantomjs/releases/tag/2.0.0

There is no working pre-built package available yet.

More information: https://github.com/ariya/phantomjs/issues/12897

### PR DESCRIPTION
**Pull request by mikemcquaid**
Closes #36240.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
@DomT4 Apologies that you're going to hate me but I've pushed this as-is even although it seems to link against the system OpenSSL. I'm open to working out a better solution in a follow-up PR but wanted to get this in for now as we've got people clamouring for it.

**Comment by DomT4** [comment]
@mikemcquaid No worries. It's still a work in progress in terms of enforcing our OpenSSL, but there's exceptions to every rule. I promise not to hold it against you for this needing to be one of those exceptions for a while :wink:

**Comment by mikemcquaid** [comment]
@DomT4 Well, it's a bit worse in that I didn't try particularly hard to resolve it because rebuilding from source is pain. If you want to give it a go at all: feel free :wink:

**Comment by DomT4** [comment]
@mikemcquaid I seem to recall Phantom taking at least an hour to rebuild in the past, so I feel some hefty sympathy on that. Still, one of the perks of you being a maintainer is getting to ignore my OpenSSL ranting as desired :wink:

**Comment by DomT4** [comment]
Doing a test rebuild of QT5, which PhantomJS contains, reveals some fun things. Don't know whether I spotted this at the time we dealt with Qt5 ages ago and we filed a report upstream on the inability to select OpenSSL. Looks like it's having the same Python on 10.6 problem and hooking directly into the SYSROOT and plucking headers and libs from that OpenSSL instead of anything else in the path:

```
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/openssl/stack.h:95:5: note: 'sk_push' has been explicitly marked deprecated here

int sk_push(STACK *st,char *data) DEPRECATED_IN_MAC_OS_X_VERSION_10_7_AND_LATER;

^

ssl/qsslsocket_openssl_symbols.cpp:198:18: warning: 'sk_free' is deprecated: first deprecated in OS X 10.7 [-Wdeprecated-declarations]

DEFINEFUNC(void, sk_free, STACK *a, a, return, DUMMYARG)

^

ssl/qsslsocket_openssl_symbols_p.h:177:33: note: expanded from macro 'DEFINEFUNC'

ret q_##func(arg) { funcret func(a); }

^
```

**Comment by mikemcquaid** [comment]
Doh. Reckon we should just remove the (now redundant) `openssl` dependency for now then?

**Pull request closed without merging**
