### PR TITLE
llvm: install python bindings only if specified

### PR DESCRIPTION
**Pull request by tamird**
The `--with-python` doesn't do anything right now =/

### CODE REVIEW

**Comment by xu-cheng** [comment]
> The --with-python doesn't do anything right now =/

That's incorrect. This is intentional that `--with-python` is used to make llvm binding to homebrew python rather than system python.

**Comment by tamird** [comment]
Where does that happen?

**Comment by xu-cheng** [comment]
> Where does that happen?

Inside https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/requirements/python_dependency.rb. It will set `PATH` variable for python.

Maybe I should rephrase a bit. Without `--with-python`, llvm will bind to system python. With it, it will bind to the python which appears first in users' PATH variable.

**Comment by tamird** [comment]
@xu-cheng where does that code inspect the passed flags?

**Comment by xu-cheng** [comment]
You mean the code translates from `:python` to `PythonDependency`? It's [here](https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/dependency_collector.rb#L116).

**Comment by tamird** [comment]
No, I mean the code that parses the `--with-python` flag and takes an action

**Comment by xu-cheng** [comment]
Oh, that's because `:python` is `:optional` in `llvm.rb`. `--with-flag` will trig `PythonDependency` to take the action.

**Comment by tamird** [comment]
Oh, I see. Yikes, that's some crazy magic.

**Comment by tdsmith** [comment]
>  This is intentional that --with-python is used to make llvm binding to homebrew python rather than system python.

Does it actually have a linkage to a Python framework? If it doesn't, we should nix the --with-python option and just let it build against system Python.

**Comment by xu-cheng** [comment]
> Does it actually have a linkage to a Python framework? If it doesn't, we should nix the --with-python option and just let it build against system Python.

The lldb has:
```
$ otool -L /usr/local/opt/llvm/lib/liblldb.dylib
/usr/local/opt/llvm/lib/liblldb.dylib:
	/usr/local/opt/llvm/lib/liblldb.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/Cellar/llvm/3.5.1/lib/libLLVM-3.5.dylib (compatibility version 0.0.0, current version 0.0.0)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1151.16.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1151.16.0)
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 62.0.0)
	/System/Library/Frameworks/Carbon.framework/Versions/A/Carbon (compatibility version 2.0.0, current version 157.0.0)
	/System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 1.0.0, current version 57031.1.35)
	/System/Library/PrivateFrameworks/DebugSymbols.framework/Versions/A/DebugSymbols (compatibility version 1.0.0, current version 115.0.0)
	/usr/local/Frameworks/Python.framework/Versions/2.7/Python (compatibility version 2.7.0, current version 2.7.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
	/usr/lib/libxml2.2.dylib (compatibility version 10.0.0, current version 10.9.0)
	/usr/lib/libedit.3.dylib (compatibility version 2.0.0, current version 3.0.0)
	/usr/lib/libpanel.5.4.dylib (compatibility version 5.4.0, current version 5.4.0)
	/usr/lib/libncurses.5.4.dylib (compatibility version 5.4.0, current version 5.4.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
	/System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices (compatibility version 1.0.0, current version 48.0.0)
```

**Comment by tdsmith** [comment]
Okay :+1:

**Pull request closed without merging**
