### PR TITLE
wireshark 1.99.8 (devel)

### PR DESCRIPTION
**Pull request by ojab**

### CODE REVIEW

**Comment by DomT4** [comment]
I've been sitting on this locally until we handle #42105, as everyone's Qt5 builds are about to break horribly otherwise. #42105 will get merged later tonight unless we hear something from upstream, at which point I'll merge this shortly afterwards.

**Comment by ojab** [comment]
Ah, no problem.

**Comment by DomT4** [comment]
Feel free to leave it open! I'm happy to merge your PR just after we merge the Qt5 fix :)

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/5ecf77b65a03066381175651edd8ad539eafb995. Thank you for your contribution to Homebrew, we appreciate it! :smiley_cat:

**Pull request closed without merging**
