### PR TITLE
pstree: also install man page

### PR DESCRIPTION
**Pull request by UniqMartin**

### CODE REVIEW

**Comment by DomT4** [comment]
Is the manpage urgent enough to force a general reinstall?

**Comment by UniqMartin** [comment]
> Is the manpage urgent enough to force a general reinstall?

Personally, I find that a man page massively improves the UX, so I'd want every user to get it. I think forcing all users to re-download a bottle that is around 8 KB or making them recompile something that finishes in less than a second is okay to achieve that …

**Comment by mikemcquaid** [comment]
Yeh, I don't think this should have a `revision` bump.

**Comment by mikemcquaid** [comment]
:+1: when :green_apple:

**Comment by UniqMartin** [comment]
> Yeh, I don't think this should have a `revision` bump.

Why? My impression so far was that user-visible changes affecting the default installation do warrant a revision bump. Any guidelines as to which changes warrant a revision bump and which don't?

**Comment by mikemcquaid** [comment]
> Why? My impression so far was that user-visible changes affecting the default installation do warrant a revision bump. Any guidelines as to which changes warrant a revision bump and which don't?

Revision bumps should be saved for "we want to make sure every user of this formulae is forceably upgraded" e.g. security issues or widely reported bugs.

**Comment by UniqMartin** [comment]
:bow:

**Pull request closed without merging**
