### PR TITLE
gnuradio 3.7.8.1

### PR DESCRIPTION
**Pull request by jiegec**

### CODE REVIEW

**Comment by apjanke** [comment]
CI and Jenkins failed.

Maybe a sandboxing violation?

```
byte-compiling /usr/local/Cellar/wxpython/3.0.2.0/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx/tools/XRCed/XMLTreeMenu.py to XMLTreeMenu.pyc
byte-compiling /usr/local/Cellar/wxpython/3.0.2.0/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx/tools/XRCed/xrced.py to xrced.pyc
byte-compiling /usr/local/Cellar/wxpython/3.0.2.0/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx/webkit.py to webkit.pyc
byte-compiling /usr/local/Cellar/wxpython/3.0.2.0/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx/wizard.py to wizard.pyc
byte-compiling /usr/local/Cellar/wxpython/3.0.2.0/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx/xrc.py to xrc.pyc
running install_headers
creating /usr/local/Cellar/wxmac/3.0.2/include/wx-3.0/wx/wxPython
error: could not create '/usr/local/Cellar/wxmac/3.0.2/include/wx-3.0/wx/wxPython': Operation not permitted
==> Formula
Path: /usr/local/Library/Formula/wxpython.rb
```

From http://bot.brew.sh/job/Homebrew%20Pull%20Requests/35792/version=el_capitan/testReport/brew-test-bot/el_capitan/install___only_dependencies_gnuradio/.

**Comment by DomT4** [comment]
It is yeah. There's some discussion in https://github.com/Homebrew/homebrew/issues/45024. Was hoping to get feedback from Tim there before I did anything drastic.

**Comment by apjanke** [comment]
Thanks. Will read up there.

**Comment by DomT4** [comment]
This should be resolved now. Please `brew update` and let us know if you run into any issues, Thanks!

**Pull request closed without merging**
