### PR TITLE
Frescobaldi updated to version 2.18

### PR DESCRIPTION
**Pull request by Asuranceturix**

### CODE REVIEW

**Comment by L2G** [comment]
It looks like CI failed for want of a LaTeX distribution. @Asuranceturix, I don't think this is your fault, but the maintainers probably ought to chime in here…

    ==> brew install --only-dependencies --verbose --build-bottle frescobaldi FAILED
    lilypond: A LaTeX distribution is required for Homebrew to install this formula.
    
    Make sure that "/usr/texbin", or the location you installed it to, is in
    your PATH before proceeding.
    
    You can install with Homebrew Cask:
      brew install Caskroom/cask/mactex
    
    You can download from:
      https://www.tug.org/mactex/
    Error: An unsatisfied requirement failed this build.

**Comment by Asuranceturix** [comment]
Well, whatever is needed from LaTeX, it should be the same that was needed
for previous versions of this formula. All I did was point to the newer
sources and add a new python module into which the Frescobaldi author
apparently offloaded part of the functionality. The problem with LaTeX must
stem from the Lilypond dependency, which does require LaTeX.

**Comment by xu-cheng** [comment]
Let's either make lilypond optional or move this formula to homebrew/tex.

**Comment by L2G** [comment]
Probably would have to be the latter, since it's an editor for LilyPond files…

**Comment by Asuranceturix** [comment]
Lilypond is, indeed optional: the formula features a --without-lilypond
switch, and the previously-accepted version of the formula already did.

**Comment by L2G** [comment]
I think what @xu-cheng is saying is to make `depends_on "lilypond" => :recommended` into `depends_on "lilypond" => :optional` in order to allow the CI to work.

That seems like a hack around a problem that is more Jenkins's fault than the formula's, IMHO.

**Comment by Asuranceturix** [comment]
Yep, I agree it looks more like a shortcoming of Jenkins. However, I wouldn't oppose making Lilypond optional if it will help. Anyway, potential Frescobaldi users already know they will probably want to install Lilypond too.

**Comment by mikemcquaid** [comment]
> However, I wouldn't oppose making Lilypond optional if it will help.

That'd be good, thanks.

**Comment by Asuranceturix** [comment]
On 27 April 2015 at 23:02, Mike McQuaid <notifications@github.com> wrote:

> However, I wouldn't oppose making Lilypond optional if it will help.
>
> That'd be good, thanks.
>
Shall I change this and make a new pull request?

**Comment by L2G** [comment]
I think it's okay to push to the same branch to keep the same pull request. You can even rebase and force-push it for neatness.

**Comment by mikemcquaid** [comment]
> I think it's okay to push to the same branch to keep the same pull request. You can even rebase and force-push it for neatness.

Yes. Squash commits by running `brew update; git checkout $YOUR_BRANCH; git rebase --interactive origin/master` and then mark each commit other than the first as `squash` or `fixup` then `git push -f`. Thanks!

**Comment by Asuranceturix** [comment]
Ok, I hope I did it right. :)
I changed portmidi to optional too because it's Lilypond who generates MIDI
output. Portmidi without Lilypond does not make any sense, so we might as
well save Jenkins' time checking Portmidi.

**Comment by L2G** [comment]
Whitespace gnat… :scream_cat:

"Happens to the best of us," as my dad used to say. Just remember to run `brew audit` before you push.

You can fix it up in-place by committing your change with `git commit --amend`. Then audit with `brew audit frescobaldi`, and if that comes up clear, push once more with `git push -f`.

    ==> brew audit frescobaldi						 FAILED
    Error: 1 problems in 1 formulae
    frescobaldi:
     * 63: Trailing whitespace was found

**Comment by Asuranceturix** [comment]
Oops, sorry, forgot to check that. Fixed! :D

**Comment by mikemcquaid** [comment]
Failing to install on 10.8: http://bot.brew.sh/job/Homebrew%20Pull%20Requests/25067/version=mountain_lion/testReport/junit/brew-test-bot/mountain_lion/install_frescobaldi/

**Comment by Asuranceturix** [comment]
According to the log (or what I understand of it), it fails when building
the bundle, which has not changed since the previous formula. Did the
previous formula pass this test? I don't currently have a 10.8, so I will
need some time to track down this issue. Should I close this and make a new
pull request when (if) I solve this issue?

**Comment by mikemcquaid** [comment]
You can push fixes to this PR. You could perhaps just remove the code that makes the app bundle.

**Comment by Asuranceturix** [comment]
Is there any way to make that dependent on the OS version? It seems unfair
to deprive users of 10.9 and 10.10 of the convenience of the bundle just
because it doesn't work on 10.8, doesn't it?

**Comment by mikemcquaid** [comment]
Considering it's not part of the Frescobaldi buildsystem anyway I'd rather we just move closer to that than have different features across OS versions.

**Comment by DomT4** [comment]
`lilypond` has moved to Homebrew/tex so the dependency needs to be fully declared now, i.e. `depends_on "homebrew/tex/lilypond" => :optional`. Other comments above need addressing as well, Thanks!

**Pull request closed without merging**
