### PR TITLE
Docker 1.8.0

### PR DESCRIPTION
**Pull request by ndeloof**

### CODE REVIEW

**Comment by mistydemeo** [comment]
Can you update boot2docker too and add it to this PR? They need to be updated together.

**Comment by tavisto** [comment]
In looking into helping out and adding the [boot2docker](https://github.com/boot2docker/boot2docker-cli) update, I saw the following in the repo:
> This project is officially deprecated in favor of Docker Machine.

I am not sure if that boot2docker-cli will be updated.

**Comment by ndeloof** [comment]
@mistydemeo boot2docker last release is 1.7.1 https://github.com/boot2docker/boot2docker-cli/releases
and will indeed be replaced by docker machine

**Comment by ndeloof** [comment]
also see https://github.com/Homebrew/homebrew/pull/42844

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
