### PR TITLE
youtube-dl 2015.07.18

### PR DESCRIPTION
**Pull request by dstftw**

### CODE REVIEW

**Comment by bfontaine** [comment]
The build failed on ML:

```
==> make PREFIX=/usr/local/Cellar/youtube-dl/2015.07.18
python devscripts/make_contributing.py README.md CONTRIBUTING.md
python devscripts/make_supportedsites.py docs/supportedsites.md
Traceback (most recent call last):
  File "devscripts/make_supportedsites.py", line 13, in <module>
    import youtube_dl
  File "devscripts/../youtube_dl/__init__.py", line 16, in <module>
    from .options import (
  File "devscripts/../youtube_dl/options.py", line 8, in <module>
    from .downloader.external import list_external_downloaders
  File "devscripts/../youtube_dl/downloader/__init__.py", line 3, in <module>
    from .common import FileDownloader
  File "devscripts/../youtube_dl/downloader/common.py", line 8, in <module>
    from ..compat import compat_str
  File "devscripts/../youtube_dl/compat.py", line 82, in <module>
    _asciire = re.compile('([\x00-\x7f]+)') if sys.version_info < (2, 7) else compat_urllib_parse._asciire
AttributeError: 'module' object has no attribute '_asciire'
make: *** [supportedsites] Error 1
```

http://bot.brew.sh/job/Homebrew%20Pull%20Requests/29783/version=mountain_lion/testReport/junit/brew-test-bot/mountain_lion/install_youtube_dl/

**Comment by dunn** [comment]
This is an upstream bug, will be fixed in the next version: https://github.com/rg3/youtube-dl/issues/6271

Backporting the commit as a patch was a little fiddly, but I think I figured it out in #41856.

**Comment by dstftw** [comment]
I see little sense messing with patches since new version should come out shortly (I've notified our maintainer to make a rebuild right after noticed and fixed this issue).

**Comment by dunn** [comment]
Oh, did https://github.com/rg3/youtube-dl/releases/tag/2015.07.18 change to incorporate the fix? I notice `youtube-dl.1` isn't included at all anymore, which would mean a pandoc dependency even for the stable version.

**Comment by dstftw** [comment]
`2015.07.18` does not incorporate the fix. The correct URL to full tarball is https://yt-dl.org/downloads/2015.07.18/youtube-dl-2015.07.18.tar.gz and it includes `youtube-dl.1`.

**Comment by dunn** [comment]
Oh, got it, thanks!

If you're OK waiting for the next version, that's fine with me.

**Pull request closed without merging**
