### PR TITLE
afl-fuzz 2.06b

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by justinclift** [comment]
@alex Ping... :wink:

**Comment by alex** [comment]
The test failures look like jenkins internal stuff, they don't appear related to this PR near as I can tell.

**Comment by justinclift** [comment]
@mikemcquaid Seems like this should be resubmitted to the test box.  You ok to kick that off? :smile:

**Comment by mikemcquaid** [comment]
It doesn't need resubmitted, we can pull as-is.

**Pull request closed without merging**
