### PR TITLE
fleetctl 0.11.4

### PR DESCRIPTION
**Pull request by madeddie**
I could add a simple --version test. 
Since this application is a utility to talk to a service, I'd have to write a mock service to test more of it, which might be overkill.

If you want the --version test, reply to this comment and I'll update the PR. If you want more extensive testing, could you point me to examples doing client -> server testing with a mock server?

### CODE REVIEW

**Comment by DomT4** [comment]
>  If you want more extensive testing, could you point me to examples doing client -> server testing with a mock server?

This would be great! There's an example of server testing [here](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/mpd.rb#L127-L139), if that's useful.

**Comment by madeddie** [comment]
Ah, sorry, I meant it the other way around, fleetctl is more like mpc. So it'd need a server to test against. There's some Go code in the package that's able to emulate a server, but compiling that just to test the client seems like overkill.

**Comment by mikemcquaid** [comment]
@madeddie A `--version` test would be great.

**Comment by DomT4** [comment]
Apologies for the misunderstanding! My misread on that. Checking the version is fine then, per Mike's comment.

**Comment by madeddie** [comment]
Added simplest --version test.

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
