### PR TITLE
idris 0.9.20

### PR DESCRIPTION
**Pull request by justjoheinz**

### CODE REVIEW

**Comment by DomT4** [comment]
Looks like there's a crash here:

```
==> /private/tmp/idris20151108-54501-1n5stbg/hello
==> /usr/local/Cellar/idris/0.9.20/bin/idris --exec 'putStrLn {ffi=FFI_C} "Hello, interpreter!"'
Error: idris: failed
Expected /Hello, interpreter!/ to match "Uncaught error: (input):1:10:Elaborating {__infer0} arg {ival0}: ffi is not an implicit argument of Prelude.Interactive.putStrLn\n".
```

**Comment by justjoheinz** [comment]
The tests did not work with the new version. I wrote an updated test for the foreign function interface.

**Comment by justjoheinz** [comment]
Now I am at a loss, I do not know what keeps the build from passing as the output seems to indicate just timeout errors.

**Comment by mikemcquaid** [comment]
You can ignore the Travis timeouts; that Jenkins is passing is enough, thanks!

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
