### PR TITLE
doctor: use multithread to accelerate speed

### PR DESCRIPTION
**Pull request by xu-cheng**
Create two type of threads:
 * worker: do the actual check and send check result to report thread.
 * reporter: print the warning message to stderr.

Benchmark for `129 kegs, 71,153 files, 4.5G` Cellar.
 * Old: `brew doctor  3.61s user 0.87s system 22% cpu 20.001 total`
 * New: `brew doctor  4.35s user 0.96s system 38% cpu 13.880 total`

Note: the performance will vary based on the diagnostic result.
Under worst case, there will be no difference between multithread
model and original sequential model.

cc @UniqMartin @mikemcquaid

### CODE REVIEW

**Comment by xu-cheng** [comment]
As mentioned in other PR, there isn't a significant improvement.  I think the reason is GIL. I will see if possible to make it multiprocess instead of multithread.

**Comment by mikemcquaid** [comment]
> I think the reason is GIL.

Either that or it's just IO-bound.

**Comment by UniqMartin** [comment]
@xu-cheng Thanks for giving it a try and disproving my claim! :bow:

> Either that or it's just IO-bound.

I tried playing with the number of workers, but without significant improvement. IO-bound sounds quite plausible, given that `check_for_linked_keg_only_brews` is by far the slowest check. Thus parallelism might actually degrade performance.

Benchmark for a `163 kegs, 80,632 files, 2.4G` cellar on a Retina MacBook Pro (13-inch, Late 2012):

```
# serial code, slow checks last
brew doctor:  10.880s user,   0.930s system,  15.142s total ( 78.0% cpu)
brew doctor:  10.890s user,   0.990s system,  16.100s total ( 73.8% cpu)

# parallelized, slow checks last
brew doctor:  11.650s user,   1.010s system,  12.126s total (104.4% cpu)
brew doctor:  13.400s user,   1.130s system,  14.041s total (103.5% cpu)

# parallelized, slow checks first
brew doctor:  11.610s user,   1.340s system,  12.224s total (105.9% cpu)
brew doctor:  13.020s user,   1.110s system,  13.682s total (103.3% cpu)
```

Thoughts:

- Multi-threading should probably be disabled for `-D` and invocation with named test(s).
- Non-deterministic output order might be quite bad from a UX perspective, especially for people with rather messy setups.
- Results so far don't seem good enough to warrant the added complexity and worse UX.

**Comment by mikemcquaid** [comment]
> Results so far don't seem good enough to warrant the added complexity and worse UX.

Agreed. I'd like to see at least a 50% speedup to make the code complexity worthwhile. There's possibly ways we can speed things up by doing less disk access or e.g. using something like `find` to get some of the results.

**Comment by xu-cheng** [comment]
Yeah, this PR is most for experiment purpose. Close for now.

**Comment by UniqMartin** [comment]
> There's possibly ways we can speed things up by doing less disk access

If I find the time, I'll have a look at the biggest offenders and see if they can be improved.

> or e.g. using something like `find` to get some of the results.

I'm personally against doing this, because the price of the speedup (if there's any) is that we would have to rely on external tools that can break in more ways than native Ruby code (due to user configuration, overrides in `PATH`,  etc.) and that we would have to parse the textual output of those tools (which comes with its own set of corner cases). The benefit has to be pretty significant to offset these pains.

**Comment by mikemcquaid** [comment]
> I'm personally against doing this, because the price of the speedup (if there's any) is that we would have to rely on external tools that can break in more ways than native Ruby code (due to user configuration, overrides in PATH, etc.) and that we would have to parse the textual output of those tools (which comes with its own set of corner cases). The benefit has to be pretty significant to offset these pains.

Obviously I'm only in favour if there's a fairly dramatic speedup. As this is a standard Unix tool the output parsing is extremely straightforward. I've certainly seen "iterate over files in Ruby" massively sped up in the past by letting `find` do the same thing.

**Comment by UniqMartin** [comment]
> As this is a standard Unix tool the output parsing is extremely straightforward.

The parsing is never straightforward thanks to encoding issues, special characters like newlines in file names (which are perfectly legal on OS X), and other issues I probably have forgotten. Working with the functionality that a programming language offers at least shields you from this (or gives you someone to blame if that fails, other than yourself).

**Pull request closed without merging**
