### PR TITLE
Ntopng

### PR DESCRIPTION
**Pull request by Drewshg312**
Please could you add head version. The issue is here: https://github.com/ntop/ntopng/issues/84

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Please rebase your branch on `origin/master` and squash your commits, thanks!

**Comment by Drewshg312** [comment]
Could you please help me with that... I'm new to git. Basically, I want to cancel all the changes on Master and commit and pull only the ntopng branch. Thank you

**Comment by mikemcquaid** [comment]
Squash commits by running `brew update; git checkout $YOUR_BRANCH; git rebase --interactive origin/master` and then mark each commit other than the first as `squash` or `fixup` then `git push -f`. Thanks!

**Comment by Drewshg312** [comment]
Could you explain how to mark each commit other than the first as `squash` or `fixup`?

**Comment by dunn** [comment]
Replace `pick` with `squash` on each line you want to squash; likewise for fixups.

**Comment by Drewshg312** [comment]
lol where? I've never done it before…

**Comment by dunn** [comment]
When you run `git rebase --interactive`, it should open a window in your editor with a list of the commits that aren't in `origin/master`.  Each line will look something like `pick 6a5dd4b Merge branch 'master' ...`.

**Comment by Drewshg312** [comment]
Gotcha! thanx… But what if all previous commits were mistake and the only changes I want is the last one: `pick 16bfa31 ntopng: add head`? What should I do in this case?

**Comment by Drewshg312** [comment]
should I just remove all lines except the last one?

**Comment by dunn** [comment]
Yeah, that should work.

**Comment by Drewshg312** [comment]
This msg was opened in sublime and when I try to save it says: 

    Unable to save /usr/local/.git/rebase-merge/git-rebase-todo
    Error: No such file or directory"

**Comment by Drewshg312** [comment]
so I closed without saving and done:

    $ git push -f
    git rebase --interactive origin/master
    Successfully rebased and updated refs/heads/ntopng.
    
    Andryuwka @ drew-sh.server:/usr/local (27 entries, 0 hidden)
    #539 Sat Aug 01 11:35:27 $ git push -f
    warning: push.default is unset; its implicit value has changed in
    Git 2.0 from 'matching' to 'simple'. To squelch this message
    and maintain the traditional behavior, use:
    
      git config --global push.default matching
    
    To squelch this message and adopt the new behavior now, use:
    
      git config --global push.default simple
    
    When push.default is set to 'matching', git will push local branches
    to the remote branches that already exist with the same name.
    
    Since Git 2.0, Git defaults to the more conservative 'simple'
    behavior, which only pushes the current branch to the corresponding
    remote branch that 'git pull' uses to update the current branch.
    
    See 'git help config' and search for 'push.default' for further information.
    (the 'simple' mode was introduced in Git 1.7.11. Use the similar mode
    'current' instead of 'simple' if you sometimes use older versions of Git)
    
    fatal: The current branch ntopng has no upstream branch.
    To push the current branch and set the remote as upstream, use
    
        git push --set-upstream origin ntopng

**Comment by Drewshg312** [comment]
Trying to do everything from scratch and getting:

    $ git push me ntopng
    Username for 'https://github.com': Drewshg312
    Password for 'https://Drewshg312@github.com':
    To https://github.com/Drewshg312/homebrew.git
     ! [rejected]        ntopng -> ntopng (non-fast-forward)
    error: failed to push some refs to 'https://github.com/Drewshg312/homebrew.git'
    hint: Updates were rejected because the tip of your current branch is behind
    hint: its remote counterpart. Integrate the remote changes (e.g.
    hint: 'git pull ...') before pushing again.
    hint: See the 'Note about fast-forwards' in 'git push --help' for details.

What the hell all that mean?? I just wanted to add head to ntopng formula! wtf???

**Comment by dunn** [comment]
You'll need to use the `-f` (force) option, since you're updating this PR in a way that removes some commits.

**Comment by Drewshg312** [comment]
like this: `git push me ntopng -f`?

**Comment by dunn** [comment]
Should work.

**Comment by Drewshg312** [comment]
I've already deleted local and remote branches so will try to do it now from scratch… again… lol

**Comment by Drewshg312** [comment]
So I've redone all this and now I have no clue how to check if it works or not… Any ideas?

**Comment by dunn** [comment]
How to check if the formula works? Or if the branch looks how it should?

**Comment by Drewshg312** [comment]
how to check if the branch looks how it should and if my PR is updated

**Comment by dunn** [comment]
Since you deleted the branch, you'll have to open a new PR.

To make sure your branch looks good, check it out in git (`git checkout branch-name`), then rebase `git rebase --interactive origin/master` and remove anything that you don't want as part of the new PR.  Then push!

**Comment by Drewshg312** [comment]
Done it twice.

first I've got this: 

    $ git push me ntopng
    Username for 'https://github.com': Drewshg312
    Password for 'https://Drewshg312@github.com':
    Counting objects: 5367, done.
    Delta compression using up to 12 threads.
    Compressing objects: 100% (1938/1938), done.
    Writing objects: 100% (5367/5367), 1.30 MiB | 749.00 KiB/s, done.
    Total 5367 (delta 4224), reused 4436 (delta 3420)
    To https://github.com/Drewshg312/homebrew.git
     * [new branch]      ntopng -> ntopng

then rechecked:

    $ git push me ntopng -f
    Username for 'https://github.com': Drewshg312
    Password for 'https://Drewshg312@github.com':
    Everything up-to-date

I mean here on gitHub shouldn't some page appear which tells the info about the PR?

**Comment by dunn** [comment]
Yeah, you pushed to https://github.com/Drewshg312/homebrew.git so go there and you should see a "Compare & pull request" button.  If there isn't one, select the `ntopng` branch from the drop-down menu, then click the "pull request" button.

This should help if you're still confused: https://help.github.com/articles/using-pull-requests/

**Comment by Drewshg312** [comment]
I get it! So which repository should I usually use for asking some changes by PR?
mine
`https://github.com/Drewshg312/homebrew.git`
or
`https://github.com/Homebrew/homebrew.git`
??

**Comment by dunn** [comment]
You open PRs at Homebrew/homebrew, but you should be able to use the "pull request" buttons at either location.

**Pull request closed without merging**
