### PR TITLE
fontforge 20141230

### PR DESCRIPTION
**Pull request by DomT4**
A complete darn formula rewrite from the bottom up.

Version bump.

### CODE REVIEW

**Comment by DomT4** [comment]
I'm happy with this if you are at this point Mike.

https://github.com/fontforge/fontforge/issues/2020 isn't so urgent now that we've switched tarball to save considerable size, and the https://github.com/fontforge/fontforge/issues/2022 problem has a working fix here, and I'll backport any official upstream fix if there becomes one.

**Comment by DomT4** [comment]
The remaining ` SemVer ` issue is going to take a while to test and resolve, both for me and upstream. Upstream in particular are trying to work out how to force the bumps on the various Linux distros which commonly use a versioning system to work out updates. I don't think the resolution of that is going to come before the next release, at the earliest.

But, let me check if reverting the previous explicit version helps with the future ` SemVer ` problem, if it happens, then I'll be content here. Apologies for being a pain in the arse :wink:.

**Comment by DomT4** [comment]
Alright, no dice on the revert. This is good to go as is if you're happy. SemVer in future could prove troublesome at this point, garg.

**Comment by mikemcquaid** [comment]
One solution if we know semver is definitely coming is to go for e.g. `1.20141230` as the version number if it's going to `2.x.y` later.

**Comment by DomT4** [comment]
Would that still work here given the previous explicit version was set at ` 201411xx ` or something? Or would we need to revert that before merging in a new explicit version that is underneath that number? Or does the ` 1.x ` automatically trump the ` 201411xx `?

**Comment by mikemcquaid** [comment]
You'll need to play with `brew upgrade` but it could be possible for us to play with the versions such that each is seen as an upgrade.

**Comment by DomT4** [comment]
Alright. I'll take another run at Fontforge this evening and see if I can get the versions to play a little nicer than they were the other night.

**Comment by DomT4** [comment]
I don't think we're going to get a definite *"semver will happen"* from upstream for a while, at least until they work out how to handle the Linux distros which face the same problem, so I'm content for us to keep the current pattern around versioning until at least the next release, and reconsider the situation with each release.

**Pull request closed without merging**
