### PR TITLE
ID3 tags stripped from MP3 test fixture

### PR DESCRIPTION
**Pull request by bfontaine**
This lower the file size, down to 360B.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Just to check: is this the last change we forsee making to this file? I just ask because of how badly Git handles changing binary files.

**Comment by bfontaine** [comment]
I think so, I can’t think of another way to further reduce the file size (didn’t thought about this one when I added the file).

**Comment by mikemcquaid** [comment]
It's worth noting that although this will reduce the file size it'll actually increase the amount of data in the repository stored for this file.

**Comment by bfontaine** [comment]
Right.

**Comment by mikemcquaid** [comment]
So do you still think it's worth doing? Does it have benefits beyond reducing the file size? Not saying it doesn't, just wanting to discuss it. Thanks!

**Comment by bfontaine** [comment]
I found these ID3 tags when working on a test for mp3cat, which somehow strips them when it processes a file. I thus needed an ID3-less version of the test fixture to compare it to `mp3cat`’s output. This is the main reason I did this PR. If you know of another way of adding a 360B file in a formula to test it, I’ll use it and this PR should be closed. Writing it unpacked in the Ruby file would take too much space I think.

**Comment by mikemcquaid** [comment]
Hmm, I think in that case we can just check that it runs rather than checking the output is valid. I can see us wanting to write tests in future that expect ID3 tags to be present.

**Comment by bfontaine** [comment]
Thanks, I simplified #35428 then.

**Comment by mikemcquaid** [comment]
Thanks for understanding :heart:

**Pull request closed without merging**
