### PR TITLE
use BSD stat

### PR DESCRIPTION
**Pull request by tdsmith**
Fixes https://groups.google.com/forum/#!msg/homebrew-discuss/XxMZRKUbRn8/A2bnpmilFwAJ.

### CODE REVIEW

**Comment by DomT4** [comment]
Seems fine to me but feel free to wait for review by a maintainer who doesn't glare at the core with suspicion that it's trying to invite them to their doom :wink:.

**Comment by mikemcquaid** [comment]
:+1:

**Comment by xu-cheng** [comment]
How about use `ls` like https://github.com/Linuxbrew/linuxbrew/commit/2e907aa58b1bd7ba035e576d9ab80e0ac9757cbb? Therefore, it will work fine for all POSIX system.

**Comment by tdsmith** [comment]
Sorry; I pushed just before I saw your post. I don't have a preference.

**Comment by xu-cheng** [comment]
I don't have a preference, either. Just brought up more options. :wink:

**Pull request closed without merging**
