### PR TITLE
install: fix handling of "not migrated" message.

### PR DESCRIPTION
**Pull request by mikemcquaid**
CC @xu-cheng, thoughts? Still not totally sure I understand before so feel free to tear this to bits :grinning:

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Note that this was written on a plane and was thus hasn't been really tested yet.

**Comment by xu-cheng** [comment]
Some thoughts:
* Maybe it's better to put logic outside formulae already installed check. They are independent/unrelated to each other. 
* I think at the best we can warning people they need to migrate rather than error out. The reason is they are high chance old name rack is another formula. And we shouldn't stop users to install formulae which happen to have that old name.

**Comment by mikemcquaid** [comment]
@xu-cheng Decided to just revert the initial commit.

**Comment by xu-cheng** [comment]
I think https://github.com/Homebrew/homebrew/pull/43269 is an acceptable solution.

**Comment by mikemcquaid** [comment]
Cool, didn't see that yet. Closing!

**Pull request closed without merging**
