### PR TITLE
bitrise 1.0.0

### PR DESCRIPTION
**Pull request by viktorbenei**
You can find the release notes at: https://github.com/bitrise-io/bitrise/releases/tag/1.0.0

### CODE REVIEW

**Comment by viktorbenei** [comment]
I checked the error and it seems to be an issue in the tester, not in our changes, I'll trigger a new test with a new push.

**Comment by viktorbenei** [comment]
For reference it only failed on Mountain Lion with:

```
FATAL: Could not checkout 24c54c7611b85231ddc7ab9ed04ff3ad6b0d4c91
hudson.plugins.git.GitException: Could not checkout 24c54c7611b85231ddc7ab9ed04ff3ad6b0d4c91
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$8.execute(CliGitAPIImpl.java:1907)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:152)
...
```

Link: http://bot.brew.sh/job/Homebrew%20Pull%20Requests/33106/version=mountain_lion/console

**Comment by viktorbenei** [comment]
Second run, with a "noop" change (https://github.com/Homebrew/homebrew/pull/43868/files#diff-6305e22dbd56dfb67c68e79ccd0086c1R65) was successful.

**Comment by dunn** [comment]
Merged in e7714f48f720d6ffea262ba6955dfd8bb5195535, thanks! For future reference we can re-queue a build when necessary without requiring an additional push; just let us know if it's needed.

**Pull request closed without merging**
