### PR TITLE
audit fixes: A: 01: ack - apache-forrest

### PR DESCRIPTION
**Pull request by apjanke**
audit fixes in: ack, acpica, aeskeyfind, aircrack-ng, alure, amap, apache-forrest

### CODE REVIEW

**Comment by apjanke** [comment]
Test failure for `apache-forrest` is due to a missing JAVA_HOME on the Travis CI test environment, it looks like. Is this something that should be configured as part of the `test do` in the formula, or provided by the server, or...?

```
ec -f /tmp/homebrew20151005-12172-1rvsmg5.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Library/Homebrew -- /usr/local/Library/Homebrew/test.rb /usr/local/Library/Formula/apache-forrest.rb --verbose

==> /usr/local/Cellar/apache-forrest/0.9/bin/forrest -projecthelp

.

Last 150 lines from /Users/travis/Library/Logs/Homebrew/apache-forrest/01.forrest:

2015-10-05 04:11:45 +0000

/usr/local/Cellar/apache-forrest/0.9/bin/forrest
-projecthelp

Apache Forrest.  Run 'forrest -projecthelp' to list options

Error: JAVA_HOME is not defined correctly.
  We cannot execute /System/Library/Frameworks/JavaVM.framework/Home/bin/java

Error: apache-forrest: failed
Failed executing: /usr/local/Cellar/apache-forrest/0.9/bin/forrest -projecthelp
/usr/local/Library/Homebrew/formula.rb:1342:in `block in system'
/usr/local/Library/Homebrew/formula.rb:1279:in `open'
/usr/local/Library/Homebrew/formula.rb:1279:in `system'
/usr/local/Library/Formula/apache-forrest.rb:36:in `block in <class:ApacheForrest>'
/usr/local/Library/Homebrew/formula.rb:1188:in `block in run_test'
/usr/local/Library/Homebrew/extend/fileutils.rb:17:in `mktemp'
/usr/local/Library/Homebrew/formula.rb:1184:in `run_test'
/usr/local/Library/Homebrew/test.rb:28:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/usr/local/Library/Homebrew/test.rb:27:in `<main>'
==> FAILED
```

**Comment by DomT4** [comment]
I'd presume we need to env script the `apache-forrest` binaries to point at the correct `JAVA_HOME` in `def install`. CC @xu-cheng

**Comment by DomT4** [comment]
Could be very wrong there though, so would probably wait for Xu's advice :smile_cat:

**Comment by apjanke** [comment]
Shouldn't `JAVA_HOME` be detected and defined at run time, not at build or installation time? The JRE install can change over time, and on OS X the conventional way is with `export JAVA_HOME=$(/usr/libexec/java_home)` in your shell startup scripts, or the wrapper script to launch a Java program.

E.g. mine is currently this, but it changes each time a Java update comes out, or if I want to run stuff under different versions.

```
$ echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home
```

**Comment by xu-cheng** [comment]
> I'd presume we need to env script the apache-forrest binaries to point at the correct JAVA_HOME in def install.

That's correct. You can search `Language::Java.java_home_env` among formulae for example.

**Comment by apjanke** [comment]
Cool. I'll pull apache-forrest out of this PR and change it to use that `java_home_env` under a separate PR.

**Comment by apjanke** [comment]
That `Language::Java.java_home_env` looks just right, and was easy enough to use in the formula. Thanks.

**Comment by DomT4** [comment]
Same caveat re audit fixes as in the prior PR, but merged in https://github.com/Homebrew/homebrew/commit/f4864f385c10403c51a0c38691c18f94f917a612. Thank you for another set of contributions to Homebrew!

**Pull request closed without merging**
