### PR TITLE
Fix newt install formula - trac.macports.com down

### PR DESCRIPTION
**Pull request by ktaragorn**
More information in #43528

### CODE REVIEW

**Comment by ktaragorn** [comment]
Got this url from http://www.filewatcher.com/m/patch-Makefile.in.diff.1393-0.html.

Tested on my local, `sha1` matches and `newt` is able to install.

**Comment by bfontaine** [comment]
Thank you! Could you please upgrade the `sha1` to a `sha256`?

**Comment by ktaragorn** [comment]
Done @bfontaine

**Comment by DomT4** [comment]
Fixed in https://github.com/Homebrew/homebrew/commit/79b0774dbf22853ffeedd36fabb2f6e974aa8400.

You missed the other SHA1 at the top of the formula which needed updating as well and I was reluctant to push it through another bot run given how backed up we've been the last few days. Apologies & Thanks for the submission and willingness to fix :heart:

**Comment by ktaragorn** [comment]
thanks for fixing @DomT4 glad i could be of help

**Pull request closed without merging**
