### PR TITLE
Tell brew doctor to ignore Topaz Labs libtliinfocus10.dylib

### PR DESCRIPTION
**Pull request by rotx**

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Why should it ignore these specifically? We only add stuff here we know doesn't cause issues.

**Comment by rotx** [comment]
Sorry, I should have left a proper comment. Those two are part of their Photoshop (and other plugins). They don't cause any issues other than brew doctor complaining and getting people to inadvertently delete them. No dependencies to Homebrew at all:

otool -L libtliinfocus10.dylib 
libtliinfocus10.dylib:
	/Library/Application Support/Topaz Labs/Common/lib/libtliinfocus10.dylib (compatibility version 1.0.0, current version 1.0.0)
	/Library/Application Support/Topaz Labs/Common/lib/libcv.dylib (compatibility version 2.1.0, current version 2.1.0)
	/Library/Application Support/Topaz Labs/Common/lib/libcvaux.dylib (compatibility version 2.1.0, current version 2.1.0)
	/Library/Application Support/Topaz Labs/Common/lib/libcxcore.dylib (compatibility version 2.1.0, current version 2.1.0)
	/Library/Application Support/Topaz Labs/Common/lib/libml.dylib (compatibility version 2.1.0, current version 2.1.0)
	/usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libmx.A.dylib (compatibility version 1.0.0, current version 292.4.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 111.1.4)

otool -L libtlImageIO.dylib 
libtlImageIO.dylib:
	/usr/local/lib/libtlImageIO.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/Topaz_3rdParty/lib/liblcms.1.dylib (compatibility version 2.0.0, current version 2.19.0)
	/usr/local/Topaz_3rdParty/lib/libMagick++.3.dylib (compatibility version 4.0.0, current version 4.0.0)
	/usr/local/Topaz_3rdParty/lib/libMagickCore.3.dylib (compatibility version 4.0.0, current version 4.0.0)
	/usr/local/Topaz_3rdParty/lib/libMagickWand.3.dylib (compatibility version 4.0.0, current version 4.0.0)
	/usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 7.4.0)
	/usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 111.1.4)

**Comment by mikemcquaid** [comment]
> /usr/local/Topaz_3rdParty/lib/liblcms.1.dylib (compatibility version 2.0.0, current version 2.19.0)
> /usr/local/Topaz_3rdParty/lib/libMagick++.3.dylib (compatibility version 4.0.0, current version 4.0.0)
> /usr/local/Topaz_3rdParty/lib/libMagickCore.3.dylib (compatibility version 4.0.0, current version 4.0.0)
> /usr/local/Topaz_3rdParty/lib/libMagickWand.3.dylib (compatibility version 4.0.0, current version 4.0.0)

These may all cause Homebrew issues so I'd rather leave the warning as-is, I think.

**Comment by tdsmith** [comment]
I would also like to leave this check in place but I wonder if you have suggestions for ways we can reduce the impact of this notification on users.

**Comment by DomT4** [comment]
Passing on this, but please do let us know if there are mutually useful ways we can soften the impact here.

**Pull request closed without merging**
