### PR TITLE
Upgrade SSL to 1.0_2d

### PR DESCRIPTION
**Pull request by LaurentFough**
Upgrade OpenSSL requirement to 1.0_2d

### CODE REVIEW

**Comment by DomT4** [comment]
Will this work & not cause runtime/build problems @nabla-c0d3?

**Comment by nabla-c0d3** [comment]
It will cause build problems as setup.py expects 1.0.2a. I am about to release Nassl and SSLyze 0.12 which will support OpenSSL 1.0.2.d so let's wait until that happens.

**Comment by DomT4** [comment]
Cool. Thanks for the reply @nabla-c0d3 :+1:. Closing here, but happy to take an update PR when the new version is cut if you're still interested then @LaurentFough.

**Comment by LaurentFough** [comment]
ditto @nabla-c0d3: Thanks.
Will wait on the PR.

**Pull request closed without merging**
