### PR TITLE
formula_installer: don't install build dep if dependent is installed

### PR DESCRIPTION
**Pull request by xu-cheng**
**Important Note** The fix may be incorrect. See https://github.com/Homebrew/homebrew/pull/47816#issuecomment-169686926

### CODE REVIEW

**Comment by bfontaine** [comment]
I don’t understand what this code does. What is the issue?

**Comment by xu-cheng** [comment]
I found a bug as follow:
* I installed `pyside` from source, then removed its build dependencies. 
* If I then `brew install matplotlib --with-pyside` it will try to install `sphinx-doc`, which is a  build dependency of `pyside`.

Maybe you need wait a moment before I come out a minimal example to reproduce. Now after a little think, I suspect my fix is incorrect. Because, we should never expand pyside's dependencies at the first place.

**Comment by UniqMartin** [comment]
How difficult would it be to distill the bug down to a minimal (failing) test case first?

I believe our dependency resolution code is rather fragile (and not very well understood) and we probably should withhold changes until we can properly test them, unless the bug being fixed is truly severe (the recent MPI problems come to mind). I don't think the issue here meets this condition. Having more installed than is necessary is mildly annoying, but is unlikely to break things, right?

**Comment by xu-cheng** [comment]
Now, after some thought, this PR is definitely an incorrect fix. The real problem is `Dependency.skip` should skip build dependencies as well. 

Per @UniqMartin, in long term, we need to improve the dependency resolution as such:
* Handle tap priority (I'm working on this)
* Better test case.
* Avoid duplicated code between `formula_installer.rb` and `build.rb`. Jack was working on this but abandoned.
* Many edge bugs such as this one. 

Close this for now.

**Pull request closed without merging**
