### PR TITLE
gambit-scheme 4.7.5

### PR DESCRIPTION
**Pull request by dunn**

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Took too long to build. Can we try and remove the `ENV.j1` and see if they've fixed that?

**Comment by dunn** [comment]
Should it try to build with GCC by default too?

**Comment by mikemcquaid** [comment]
Nah, clang works.

**Comment by dunn** [comment]
It built in less than 10 minutes on Yosemite for me (and looks like the Yosemite bot completed pretty quickly too); why the huge difference?

**Comment by mikemcquaid** [comment]
@dunn No idea really. The Clang versions aren't different enough between 10.9/10.10.

**Pull request closed without merging**
