### PR TITLE
Update cabal-install to 1.20.0.6

### PR DESCRIPTION
**Pull request by pthariensflame**
See #35476 for context.

### CODE REVIEW

**Comment by pthariensflame** [comment]
This keeps erroring out on Mountain Lion.  The line that catches my eye is:

```
xcrun: Error: failed to exec real xcrun. (Argument list too long)
```

What could be causing that?

**Comment by mikemcquaid** [comment]
> xcrun: Error: failed to exec real xcrun. (Argument list too long)

A compiler or similar build tool invocation, I suspect.

**Comment by jacknagel** [comment]
The build is apparently prepending `/usr/bin` to the path, which causes our compiler shim to invoke /usr/bin/xcrun instead of our xcrun shim; the real xcrun then finds the gcc-4.9 shim, which again invokes the real xcrun, over and over until the argument list overflows. This doesn't happen when using clang because the /usr/bin/xcrun finds /usr/bin/clang on the path before our clang shim.

It's unfortunate that the build overrides our path management in this way. I worked around it in 7c92f38b1dad961cb719007f13b2a9b15773dcdf, which seems like a good change independent of this issue.

**Comment by jacknagel** [comment]
Closing in favor of #35642.

**Pull request closed without merging**
