### PR TITLE
fswatch 1.5.0

### PR DESCRIPTION
**Pull request by emcrisostomo**

### CODE REVIEW

**Comment by dunn** [comment]
Could you add a test while you're at it? Just something that checks basic functionality would be great.

**Comment by DomT4** [comment]
Will pull for now since it has been a couple days. If you can add tests to formulae that don't have them in future though, that would be significantly appreciated.

Merged in https://github.com/Homebrew/homebrew/commit/9028c1f6668df5fb53912389d3f0892f559cff70. Thank you for your contribution to Homebrew!

**Comment by emcrisostomo** [comment]
@dunn, @DomT4, I'm willing to add tests to the formula, sorry for the belated answer. I'll update the formula as soon as I can: is it ok to do without without bumping `fswatch` version or would it be better to wait for the next update?

**Comment by DomT4** [comment]
@emcrisostomo Feel free to submit whenever! No need to wait for a new version, we always appreciate people adding functional tests to formulae at any point.

**Comment by emcrisostomo** [comment]
Thank you @DomT4, that's what I'll do then.

**Pull request closed without merging**
