### PR TITLE
postgresql 9.5.0

### PR DESCRIPTION
**Pull request by MSch**

### CODE REVIEW

**Comment by Tafkas** [comment]
I think you got the sha-256 sum wrong in https://github.com/Homebrew/homebrew/pull/47813/files#diff-bb263ae049efa84da5fd327721899362R8
It should be "f1c0d3a1a8aa8c92738cab0153fbfffcc4d4158b3fee84f7aa6bfea8283978bc"

**Comment by MSch** [comment]
@Tafkas Isn't that exactly the shasum I have there?

**Comment by UniqMartin** [comment]
> I think you got the sha-256 sum wrong

@Tafkas Thanks for chiming in here! I think the SHA256 hash is alright. It's the same in this and your PR.

The builds are failing because tests for some of the formulae that depend on `postgresql` are failing (see [this log line](https://travis-ci.org/Homebrew/homebrew/jobs/100827142#L1321) for an example). This can probably be solved by a `revision` bump of the affected formulae.

**Comment by MSch** [comment]
@UniqMartin should I do that in my PR?

**Comment by MSch** [comment]
@UniqMartin updated my PR with the bumped revisions

**Comment by UniqMartin** [comment]
> should I do that in my PR?

Yes, that would be good! The CI will make sure to rebuild them all in the right order. Please make it one commit per formula with `<formula>: revision for postgresql` as the subject line.

**Comment by MSch** [comment]
@UniqMartin and done

**Comment by UniqMartin** [comment]
Sorry for not noticing before: The `revision` line of the `postgresql` formula can be removed because of the version bump. Also, since there is no `devel do` block anymore the `stable do` block can also be removed and the URL and SHA256 moved to the top, like for other formulae that are stable-only.

Please run `brew audit --strict postgresql` locally and make sure it reports no issues before pushing.

**Comment by MSch** [comment]
@UniqMartin done. `brew audit --strict` finds no offenses.

**Comment by UniqMartin** [comment]
Thanks! The changes are looking good. We'll see what the bots have to say about this. :smiley_cat:

**Comment by UniqMartin** [comment]
Looks like `postgis` (a dependency of `pgrouting`) is also affected and needs a `revision` bump.

**Comment by UniqMartin** [comment]
Merged in 8ba158d573aabb4351b4c139976a8fdf170fd9dd. Thanks for this contribution to Homebrew, @MSch! :tada:

**Comment by MSch** [comment]
Thanks for guiding me through it @UniqMartin!

**Pull request closed without merging**
