### PR TITLE
mono 4.0.1

### PR DESCRIPTION
**Pull request by directhex**

### CODE REVIEW

**Comment by xu-cheng** [comment]
Thanks for the pull request! 🎉 Homebrew depends on contributions from community members like you and we're grateful for your support.

**Comment by xu-cheng** [comment]
This has been reverted in https://github.com/Homebrew/homebrew/commit/a3e42d0fae5ebd7c098fd19fe6e98b8314b79253. The latest stable mono release is still in 3.12.1. You can resubmit this as a devel release. Thanks.

**Comment by directhex** [comment]
4.0.1 is a STABLE release version which officially ships TODAY. The website hasn't been updated yet because I haven't finished building binaries for all platforms yet. 



Sent from my Sony Xperia™ smartphone

---- Xu Cheng wrote ----

**Comment by xu-cheng** [comment]
In such case, let's wait for website been updated. Also, we may need to add mono 3.x to homebrew/versions(if mono 4.x has back incompatibility issue).

Some user has already complained for pre-shipping. (#39127).

**Comment by mikemcquaid** [comment]
Let's go back to 4.0.1. As mentioned in #39127 PRs like this should have more context if there's a reason that e.g. it's not on the website yet or you want it merged quickly.

**Pull request closed without merging**
