### PR TITLE
tin 2.2.1

### PR DESCRIPTION
**Pull request by bfontaine**

### CODE REVIEW

**Comment by bfontaine** [comment]
Seems the bot has the same problem I got: I can’t download it from my network (the connection hangs after a few seconds), but when I tried from a server on my university network it worked.

**Comment by mikemcquaid** [comment]
Is there a mirror somewhere?

**Comment by bfontaine** [comment]
Yep, forgot to check that. Fixed.

**Comment by mikemcquaid** [comment]
This is taking a really long time to build. Any ideas?

**Comment by bfontaine** [comment]
I just tried different mirrors and used the best one as the formula’s URL.

**Comment by mikemcquaid** [comment]
The issue is the install time rather than the mirror. How long does it take on your machine, out of interest?

**Comment by bfontaine** [comment]
Less than two minutes:

```
$ brew install tin
==> Downloading ftp://ftp.cuhk.edu.hk/pub/packages/news/tin/v2.2/tin-2.2.1.tar.gz
######################################################################## 100,0%
==> ./configure --prefix=/usr/local/Cellar/tin/2.2.1 --mandir=/usr/local/Cellar/tin/2.2.1/share/man
==> make build
==> make install
🍺  /usr/local/Cellar/tin/2.2.1: 25 files, 2,1M, built in 78 seconds
```

**Comment by mikemcquaid** [comment]
Weird.

**Comment by bfontaine** [comment]
It seems to me it’s the fetch part that [fails](http://bot.brew.sh/job/Homebrew%20Pull%20Requests/22094/version=yosemite/testReport/junit/brew-test-bot/yosemite/fetch___devel_tin/):

```
==> Downloading ftp://ftp.cuhk.edu.hk/pub/packages/news/tin/v2.3/tin-2.3.1.tar.gz
Trying a mirror...
==> Downloading ftp://ftp.tin.org/pub/news/clients/tin/v2.3/tin-2.3.1.tar.gz
==> Retrying download
==> Downloading ftp://ftp.cuhk.edu.hk/pub/packages/news/tin/v2.3/tin-2.3.1.tar.gz
Trying a mirror...
==> Downloading ftp://ftp.tin.org/pub/news/clients/tin/v2.3/tin-2.3.1.tar.gz
Error: Failed to download resource "tin"
Download failed: ftp://ftp.tin.org/pub/news/clients/tin/v2.3/tin-2.3.1.tar.gz
```

**Comment by mikemcquaid** [comment]
I guess it's maybe worth looking for an HTTP mirror?

**Comment by bfontaine** [comment]
They don’t list one. Is it ok if I host a tarball on my website?

```
http://bfontaine.net/homebrew/tin-2.2.1.tar.gz
http://bfontaine.net/homebrew/tin-2.3.1.tar.gz
```

**Comment by mikemcquaid** [comment]
I'd rather not. We could consider hosting one on Bintray.

**Comment by bfontaine** [comment]
…Or a gist? :smile: 

```
https://gist.github.com/bfontaine/1d414687ae3dba44468e/raw/1a8489bfd26d43c030868ae9eb4d83c4f3fb8a51/tin-2.2.1.tar.gz
```

Yes Bintray would be a better solution.

**Comment by bfontaine** [comment]
Seems like the FTP server supports HTTP, trying with that.

**Comment by mikemcquaid** [comment]
Got it, nice work @bfontaine!

**Pull request closed without merging**
