### PR TITLE
pulse: boneyarding

### PR DESCRIPTION
**Pull request by DomT4**
Incredibly frustratingly, given it seemed like a promising project taking some steps that its forked predecessor has struggled to thus far, particularly around encryption, and it’s already mature codebase, upstream have nonetheless [decided](https://ind.ie/blog/focus/) to stop supporting Pulse as an individual project, thus, boneyard it goes. 

A little unhappy about this choice being forced on us, but ho hum. No point supporting something upstream has said will no longer be supported individually.

### CODE REVIEW

**Comment by DomT4** [comment]
Boneyard PR: https://github.com/Homebrew/homebrew-boneyard/pull/33

**Comment by mikemcquaid** [comment]
> No point supporting something upstream has said will no longer be supported individually.

Is it still useful as-is?

**Comment by DomT4** [comment]
To a degree, but given upstream have said go back to using Syncthing I didn't want us to get in a position where we end up being a support team for them because they've discontinued consumer support for the tool.

**Comment by mikemcquaid** [comment]
Ah, ok.

**Comment by DomT4** [comment]
Kinda frustrating. 'Hey we have this great alternative' only to turn the entire plan around two months down the line, but that's life I guess, heh.

**Pull request closed without merging**
