### PR TITLE
ffmpeg 2.8.2

### PR DESCRIPTION
**Pull request by zmwangx**
https://github.com/FFmpeg/FFmpeg/releases/tag/n2.8.2.

### CODE REVIEW

**Comment by DomT4** [comment]
@BrewTestBot test this please

**Comment by zmwangx** [comment]
I wonder why the bot fails to init on Yosemite and El Capitan each time...

**Comment by DomT4** [comment]
We seem to have a troublesome plugin this week. As long as the only errors are `xml` plugin failures can be ignored.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/528438dccdca4aa64fd6653fea66dcdcca5a9a57. Thank you for another Homebrew contribution @zmwangx! :smiley_cat:

**Pull request closed without merging**
