### PR TITLE
muparser 2.2.4

### PR DESCRIPTION
**Pull request by dunn**

### CODE REVIEW

**Comment by vszakats** [comment]
Would mind changing `head` to https?:
https://muparser.googlecode.com/svn/trunk/

**Comment by dunn** [comment]
No problem. Should `*.googlecode.com` urls be flagged by the audit?

**Comment by vszakats** [comment]
Thanks! Audit should ideally catch this, I'll look into it.

**Comment by DomT4** [comment]
You'll need to revert this change. The system ` svn ` can't handle SSL/TLS well, especially from Googlecode domains and will just fail. We can't presume that the user has Homebrew's ` svn ` installed.

```
Dominyks-MacBook-Pro ~> /usr/bin/svn checkout https://muparser.googlecode.com/svn/trunk/                  [~/Downloads]
Error validating server certificate for 'https://muparser.googlecode.com:443':
 - The certificate is not issued by a trusted authority. Use the
   fingerprint to validate the certificate manually!
Certificate information:
 - Hostname: *.googlecode.com
 - Valid: from Wed, 22 Apr 2015 13:49:06 GMT until Tue, 21 Jul 2015 00:00:00 GMT
 - Issuer: Google Inc, US
 - Fingerprint: fc:a8:a4:41:0c:e4:82:9a:98:3b:78:62:91:b8:13:d9:a4:f6:8a:df
(R)eject, accept (t)emporarily or accept (p)ermanently?
```

**Comment by vszakats** [comment]
Sorry for the noise folks.

**Comment by dunn** [comment]
Will the checkout fail, or will the user just have manually accept the certificate?

**Comment by DomT4** [comment]
Homebrew doesn't permit interactivity during install, so it doesn't particularly matter either way, but my suspicion is that it would just hang. You should be able to find out fairly easily though: ` brew unlink svn && brew install https://raw.githubusercontent.com/dunn/homebrew/muparser/Library/Formula/muparser.rb --HEAD `.

**Comment by dunn** [comment]
Works for me; entered 'p' and it continued.  As long as it's a HEAD build the bots won't have to deal with it.

**Comment by DomT4** [comment]
Personally: I don't really want to even give users the option. Google's own statistic tracking of insecure content warnings has showed that given an easy option, people consistently click through warnings within seconds of them being presented: i.e. without bothering to consider implications/validity/etc.

For Homebrew: From previous maintainer comments I believe the interactivity during compile rule is pretty strict. One of the maintainers will be able to advise though.

**Comment by dunn** [comment]
Ohh, by 'permit interactivity' I thought you meant it wasn't possible for there to be interactivity during install.  #38375 went through with the same situation, so I figured it worked and wasn't a problem.  But maybe that was an oversight.

**Comment by DomT4** [comment]
Hoops. We might need to revert that one. CC @Homebrew/owners for opinions/update/clarification on the interactivity during compile situation.

**Comment by asparagui** [comment]
Generally -1 on requiring user input.  The form I don't really don't like is "here, accept our custom license before we can do anything".  Having said that, an untrusted cert isn't that bad.  Would stripping HEAD in #38375 get rid of the issue?

**Comment by dunn** [comment]
Yeah, we can just pull the Inkscape HEAD.

**Comment by DomT4** [comment]
Removing the ` s ` from ` https ` should work okay as well, I'd presume.

**Comment by mikemcquaid** [comment]
Yeh, I agree, let's just make this `http`.

**Comment by dunn** [comment]
OK, back to normal.

**Comment by tdsmith** [comment]
Thanks!

**Pull request closed without merging**
