### PR TITLE
kitchen-sync 0.44

### PR DESCRIPTION
**Pull request by denji**

### CODE REVIEW

**Comment by dunn** [comment]
Any chance of a more comprehensive test? 😁

**Comment by denji** [comment]
@dunn I think it is not very feasible because of homebrew. For in-depth tests to run mysql and postgresql once to initialize the database, install ruby gems and ruby held tests.

**Comment by bfontaine** [comment]
Yeah, it doesn’t support any `-h`/`--help` option nor anything we could use without creating a database.

**Comment by bfontaine** [comment]
Thank you @denji! :tada:

**Pull request closed without merging**
