### PR TITLE
scalariform 0.1.6 (new formula)

### PR DESCRIPTION
**Pull request by jawshooah**
This formula is for @daniel-trinh's [fork](https://github.com/daniel-trinh/scalariform) of the [original](https://github.com/mdr/scalariform) by @mdr. The original has not been updated since 2013, and the fork is now considered to be the officially maintained version.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
> The original has not been updated since 2013, and the fork is now considered to be the officially maintained version.

Can you provide a citation for this? Ideally the original would update the README to clarify this. Formula looks good otherwise though, thanks!

**Comment by jawshooah** [comment]
Sure. @daniel-trinh now has [publish permissions](https://github.com/daniel-trinh/scalariform/issues/28) for the `org.scalariform` group ID, so the latest `scalariform` build on the official [maven repository](https://search.maven.org/#search%7Cga%7C1%7Ca%3A%22scalariform_2.11%22) is his. Anyone who updates their maven or [sbt](http://www.scala-sbt.org/) dependencies will be getting his version.

Really the only step remaining is a transfer of ownership of the original GitHub repo.

**Comment by jawshooah** [comment]
@mikemcquaid daniel-trinh/scalariform#55 discusses this very issue.

**Comment by daniel-trinh** [comment]
See this comment in Sonatype for when @mdr granted publishing rights to me:

https://issues.sonatype.org/browse/OSSRH-14656?focusedCommentId=304131&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-304131

**Comment by mikemcquaid** [comment]
I'd like to see some communication from @mdr.

**Comment by daniel-trinh** [comment]
Not exactly a comment from @mdr, but the readme on mdr's original repo now has a redirect message to my fork: https://github.com/mdr/scalariform/blob/master/README.rst

**Comment by mikemcquaid** [comment]
@daniel-trinh Sounds good :+1:

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
