### PR TITLE
Update gitlab-ci-multi-runner

### PR DESCRIPTION
**Pull request by johnjelinek**
### All Submissions:

- [X] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew/blob/master/.github/CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew/pulls) for the same update/change?

_You can erase any parts of this template not applicable to your Pull Request._

### New Formulae Submissions:

- [ ] Does your submission pass
`brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ ] Have you built your formula locally prior to submission with `brew install <formula>`?

### Changes to Homebrew's Core:

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031) if you'd like one.
- [ ] Have you successfully ran `brew tests` with your changes locally?

v0.7.2 => v1.0.4

### CODE REVIEW

**Comment by johnjelinek** [comment]
did not build? http://bot.brew.sh/job/Homebrew%20Pull%20Requests/42397/version=el_capitan/testReport/junit/brew-test-bot/el_capitan/install_gitlab_ci_multi_runner/

why not?

**Comment by bfontaine** [comment]
This is the error:
```
==> go build -o gitlab-ci-multi-runner -ldflags -X main.NAME=gitlab-ci-multi-runner -X main.VERSION=1.0.4 -X main.REVISION=014aa8c
# gitlab.com/gitlab-org/gitlab-ci-multi-runner/executors/docker
src/gitlab.com/gitlab-org/gitlab-ci-multi-runner/executors/docker/executor_docker.go:134: undefined: Asset
```

**Comment by johnjelinek** [comment]
hmm ... strange. I guess we can close this for someone else to take a shot at it.

**Comment by johnjelinek** [comment]
Looks like the build passed here for this revision: https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/builds/681394

**Comment by johnjelinek** [comment]
@mikemcquaid: maybe we should re-open, I just found this in the README: https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/blob/v1.0.4/docs/development/README.md#executor_dockergo-missing-asset-symbol

**Comment by johnjelinek** [comment]
I'm guessing we could run something like `make deps docker` before it does a build.

**Comment by cybertk** [comment]
See #49562

**Comment by johnjelinek** [comment]
Thanks for taking this @cybertk

**Pull request closed without merging**
