### PR TITLE
Miller 3.2.2

### PR DESCRIPTION
**Pull request by johnkerl**
https://github.com/johnkerl/miller/releases/tag/v3.2.2

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Squash commits by running `brew update; git checkout $YOUR_BRANCH; git rebase --interactive origin/master` and then mark each commit other than the first as `squash` or `fixup` then `git push -f`. Thanks!

**Comment by mikemcquaid** [comment]
(into a single commit)

**Comment by johnkerl** [comment]
My apologies for the delay -- was on travel -- thank you!

**Comment by DomT4** [comment]
No worries! Happy to help :)

**Pull request closed without merging**
