### PR TITLE
Update Ruby formula to v2.3.0

### PR DESCRIPTION
**Pull request by syndbg**
# Changes: 

Updated Ruby formula version to 2.3.0.

## To reviewers:

Should I update the bottle manually or wait for the bot to do it?

### CODE REVIEW

**Comment by rakkesh** [comment]
@syndbg Homebrew bot will take care of the `bottle do` block when this PR is merged.

**Comment by syndbg** [comment]
@rakkesh Okay, thank you :+1:

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

For future reference the preferred commit message format for simple version updates is `ruby 2.3.0`.

**Comment by syndbg** [comment]
@mikemcquaid Ah, thank you. You're far too kind :beers: 

Merry Christmas :santa:

**Pull request closed without merging**
