### PR TITLE
carthage 0.6.5

### PR DESCRIPTION
**Pull request by jspahrsummers**
https://github.com/Carthage/Carthage/releases/tag/0.6.5

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Install seems to be failing consistently on Yosmemite :sob:: http://bot.brew.sh/job/Homebrew%20Pull%20Requests/24206/version=yosemite/testReport/junit/brew-test-bot/yosemite/install_carthage/

**Comment by jspahrsummers** [comment]
It looks like Jenkins is building it with Xcode 6.3, despite the dependency upon Xcode 6.1.1. Is there any way to express that we still require the latter? (Breaking Swift changes prevent us from using the former currently.)

**Comment by mikemcquaid** [comment]
Ah, I see. We can't unfortunately as we only have one Yosemite build machine and for various $REASONS it is always running the newest Xcode. We could make a custom requirement that'd stop people installing it with old versions but we wouldn't be able to make a new binary package in that case so I wonder if it's maybe just worth us waiting for a new version here. Sorry dude!

**Comment by jspahrsummers** [comment]
Sure, we can do that. :ok_hand:

**Pull request closed without merging**
