### PR TITLE
SourceKitten 0.5.0

### PR DESCRIPTION
**Pull request by jpsim**
Hopefully Homebrew supports formulas requiring Xcode 7 Beta 6. Thanks!

### CODE REVIEW

**Comment by mikemcquaid** [comment]
> Hopefully Homebrew supports formulas requiring Xcode 7 Beta 6.

Not until it's a stable version, unfortunately.

**Comment by jpsim** [comment]
That's understandable. Should I keep this PR open until then, or close it?

**Comment by mikemcquaid** [comment]
Up to you, we're happy for you to leave it open

**Comment by jpsim** [comment]
Does the Xcode 7 GM release count as a "stable version"?

**Comment by mikemcquaid** [comment]
@jpsim Unfortunately not. It will when it starts getting delivered through the App Store.

**Comment by apjanke** [comment]
That `depends_on :xcode => ["6.4", :build]` doesn't seem to actually catch the version mismatch. I ran the current 0.4.5 formula on OS X 10.11 with Xcode 7 GM, and `brew` didn't complain about the Xcode version; it just ran the build, which failed with an obscure-sounding compiler error. Is this expected? Can `brew` actually check the Xcode version, or is that just documentation?

**Comment by beltex** [comment]
Hello @apjanke!

> I ran the current 0.4.5 formula on OS X 10.11 with Xcode 7 GM, and brew didn't complain about the Xcode version; it just ran the build, which failed with an obscure-sounding compiler error.

I believe `depends_on :xcode` checks that there is a version that is greater than or equal to the one listed, hence the check passes. The compiler error occurs because Xcode 6.4 comes with the Swift 1.2 compiler (which version 0.4.5 of SourceKitten required), while Xcode 7 comes with the Swift 2.0 compiler which has breaking changes.

The other thing is `depends_on :xcode` doesn't check if the Xcode version in question is active, if it is set via `xcode-select -s` that is, thus you would still hit the compiler error even if you had Xcode 6.4 installed as well, but Xcode 7 was active.

The long term solution would be to instead depend on Swift compiler version. Once Swift goes open-source later this year, this can be done. See https://github.com/Homebrew/homebrew/issues/42864#issuecomment-133078788 for more.

**Comment by jpsim** [comment]
@mikemcquaid now that Xcode 7 is officially released in the App Store, this PR should be good to go once your CI infrastructure is in place!

**Comment by mikemcquaid** [comment]
@BrewTestBot test this please

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/23df9fc70fc56e4882751540ad60f2d8855651c1. Thank you for your contribution to Homebrew @jpsim!

**Pull request closed without merging**
