### PR TITLE
mr: Git repo on official homepage is off

### PR DESCRIPTION
**Pull request by gabrielfurini**
Git repository on official homepage is off (git://myrepos.branchable.com/)

### CODE REVIEW

**Comment by L2G** [comment]
[The author's installation page](https://myrepos.branchable.com/install/) still implies that git://myrepos.branchable.com/ is the primary source, and it looks to me like it's still working. Was there a particular problem that prompted your change?

**Comment by gabrielfurini** [comment]
L2G, I'm sorry, you are right.
Some config on my actual network is blocking the url. Tested using another network and it's really working.

**Comment by L2G** [comment]
Ahh, I hate when that happens!

So this PR can be closed without taking any action? (That would need to be done either by you or one of the maintainers.)

**Comment by tdsmith** [comment]
Closing, then; thanks both of you!

**Pull request closed without merging**
