### PR TITLE
hercules 3.12

### PR DESCRIPTION
**Pull request by rbowler**
Update hercules to version 3.12

### CODE REVIEW

**Comment by dunn** [comment]
Would it be possible to add a test, while you're at it?

**Comment by rbowler** [comment]
I will see if I can put something together.

**Comment by rbowler** [comment]
Alex, I added a test to the formula, I also added a line to install the sample configuration file.

**Comment by dunn** [comment]
Thanks so much, merged in 9a51ab5507275232fb73373bcc34c296febaa470.

**Pull request closed without merging**
