### PR TITLE
Added Formula for Qore Language

### PR DESCRIPTION
**Pull request by temnoregg**
Fixed and improved formula as defined here - https://github.com/Homebrew/homebrew/pull/42133

### CODE REVIEW

**Comment by dunn** [comment]
A few things caught by the audit; some you can fix, but the notability issue is one we'll have to think about:
```
==> audit problems
qore:
 * Stable: version 0.8.11.1 is redundant with version scanned from URL
 * The homepage should start with http or https (URL is ).
 * The homepage is not reachable (curl exit code 3)
 * GitHub repository not notable enough (<10 forks, <10 watchers and <20 stars)

**Comment by temnoregg** [comment]
Updated as suggested by audit

**Comment by bfontaine** [comment]
> but the notability issue is one we'll have to think about

FWIW the Wikipedia page about the language was deleted two years ago because it didn’t meet their notability guidelines (which aren’t the same as ours). It’s in the [OpenSUSE official repo](http://qore.org/47-news/208-qore-in-opensuse-official-repository) but not in Debian nor Fedora.

**Comment by mikemcquaid** [comment]
Passing on this for the previously mentioned notability reasons, sorry. I suggest you create your own tap.

**Pull request closed without merging**
