### PR TITLE
graphicsmagick: set default quantum-depth to 16 (issue #46101)

### PR DESCRIPTION
**Pull request by carandraug**
See original discussion on the original issue #46101

### CODE REVIEW

**Comment by schoeps** [comment]
Now the user could specify depth-8, depth-16 and depth-32 at the same time without an error message. That's not ideal. At least a check for conflict should be made. Some other formulae solve this problem such that you have to disable the default setting manually "--without-quantum-depth-16 --with-quantum-depth-32"  (e.g. I did this for gmsh: https://github.com/Homebrew/homebrew-science/blob/master/gmsh.rb, line 33f)

**Comment by tdsmith** [comment]
As a microscopist I'm quite sympathetic; I agree with @schoeps. The dependents are mostly in homebrew/science, so queueing a PR there (to be rebuilt after this is pulled here) would be reasonable:

```
$ brew uses graphicsmagick
homebrew/science/bioformats-cpp
homebrew/science/dgtal
homebrew/science/gnudatalanguage
homebrew/science/octave
homebrew/science/vips
homebrew/science/vips7
homebrew/x11/xastir
```

**Comment by DomT4** [comment]
Closing as dead. Please feel free to resubmit a fresh PR as desired with Tim's comment in mind. Thanks for your submission to Homebrew!

**Comment by carandraug** [comment]
@DomT4 Tim's comment was to note other recipes that they will have to update once this gets accepted. But this has not been accepted yet. Will it be if I inform `homebrew/science` and `homebrew/x11` of this?

Note that this pull request came after issues on `homebrew/science` and is why @schoeps is commenting here.

**Pull request closed without merging**
