### PR TITLE
yacas: fix 404.

### PR DESCRIPTION
**Pull request by geoff-codes**
Split out from #37014 per "one commit per formula, one formula per commit" guideline.

### CODE REVIEW

**Comment by tdsmith** [comment]
What's up with the new checksum?

**Comment by tdsmith** [comment]
New version available in #35482.

**Comment by geoff-codes** [comment]
Yeah, I put a [note here](https://github.com/Homebrew/homebrew/pull/37014#discussion_r25120720) regarding that (and, apologies for not transferring notes/ better commit logs as I split these out). Re: the SHA1, I couldn't tell you why it differs from the old one, but the contents of the tarball matches [the release tag](http://sourceforge.net/p/yacas/code/HEAD/tree/tags/v1_3_4). But IMO I think pulling #35482 is probably the way to go.

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

For future reference the preferred commit message format for simple version updates is `yacas: fix 404.`.

**Pull request closed without merging**
