### PR TITLE
libgit2-glib 0.23.6

### PR DESCRIPTION
**Pull request by tschoonj**

### CODE REVIEW

**Comment by DomT4** [comment]
I presume `libgit` still compiles against this? It usually throws a bit of tantrum if they aren't in-sync: #42134

**Comment by tschoonj** [comment]
This is just a bug fix update, I doubt it broke binary compatibility

**Comment by DomT4** [comment]
Hey, as long as you're right :stuck_out_tongue_winking_eye:

**Comment by tschoonj** [comment]
@DomT4 this one also needs a rebuild. Two buildbots were acting up...

**Comment by DomT4** [comment]
@BrewTestBot test this please

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/7678c30d7441259c32e74b7807a82c75d17c463f. Thanks again Tom.

**Pull request closed without merging**
