### PR TITLE
openssl 1.0.2g

### PR DESCRIPTION
**Pull request by vszakats**
Pending official announcement and mirror updates.

### CODE REVIEW

**Comment by vszakats** [comment]
Changes: https://github.com/openssl/openssl/commit/09375d12fb684c6991c06b473664a0630b8b2edf

**Comment by alex** [comment]
Tests failing because one of the mirrors isn't updated yet.

**Comment by vszakats** [comment]
Announced: https://groups.google.com/forum/#!topic/mailing.openssl.dev/O8NBKdB5MYs

**Comment by vszakats** [comment]
Do we need both mirrors?

**Comment by alex** [comment]
I don't think so, it's only a fallback if the primary isn't available, and
it's not even used for wheel based installs.

On Tue, Mar 1, 2016 at 9:26 AM, Viktor Szakats <notifications@github.com>
wrote:

> Do we need both mirrors?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Homebrew/homebrew/pull/49685#issuecomment-190740862>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by vszakats** [comment]
In case of `mirrorservice.org` we have no control over its update frequency, so it may cause a delay (and/or manual nudges) if it must be up in order to pass tests. I'm open to opinions on which one to remove, if any.

**Comment by alex** [comment]
If it'll help get the PR landed sooner, I'd be in favor of dropping both mirrors :-)

**Comment by DomT4** [comment]
Leave the mirrors as-is.

**Comment by DomT4** [comment]
I'll update the Homebrew one ASAP and `mirrorservice` is synced regularly enough for it to be a non-issue to date.

You will however, I suspect, have to remove the patches here now.

**Comment by vszakats** [comment]
Checking the CI output the problem is again overload of OpenSSL servers. (even though I haven't had such errors on another CI). So it's not a mirroring problem in the first place.

**Comment by vszakats** [comment]
Yep, forgot about the patches.

**Comment by vszakats** [comment]
Patches removed.

**Comment by DomT4** [comment]
Mirror updated.

**Comment by alex** [comment]
Huge thanks to everyone for being so prompt and on the ball with this.

**Comment by DomT4** [comment]
This could be mildly interesting, potentially.

> In addition, weak ciphers in SSLv3 and up are now disabled in default builds of OpenSSL. Builds that are not configured with "enable-weak-ssl-ciphers" will not provide any "EXPORT" or "LOW" strength ciphers. 

This _should not_ be a problem but I'm curious as to whether anything does break or we get bug reports on; given the way people configure things or are configured by default half the time I wouldn't even be surprised.

**Comment by alex** [comment]
Indeed, theoretically some people could break (https://xkcd.com/1172/ :P). I don't think there's anything that can be done though, homebrew doesn't want to be in the business of making software weaker than upstream :-)

**Comment by DomT4** [comment]
Whether people love me for it or not, when OpenSSL 1.1.0 lands SSLv3 is going away in Homebrew, so better we find some breakage sooner :smile:.

**Comment by alex** [comment]
Failing on travis with the 10.9 builder.

**Comment by vszakats** [comment]
In 10.9 the actual build and bottling goes fine, but later:
```
==> brew uninstall --force pkg-config
Error: dlopen(/usr/local/Cellar/ruby187/1.8.7-p374_1/lib/ruby/1.8/i686-darwin13.4.0/digest/md5.bundle, 9): Library not loaded: /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
  Referenced from: /usr/local/Cellar/ruby187/1.8.7-p374_1/lib/ruby/1.8/i686-darwin13.4.0/digest/md5.bundle
  Reason: image not found - /usr/local/Cellar/ruby187/1.8.7-p374_1/lib/ruby/1.8/i686-darwin13.4.0/digest/md5.bundle
Please report this bug:
    https://git.io/brew-troubleshooting
```

**Comment by alex** [comment]
The other two travis jobs were on track to pass, but timed out.

**Comment by DomT4** [comment]
Ignore Travis, really. This is never going to pass on Travis regardless because of the timeout. If this reproduces on Jenkins I'll whip something up; I thought we solved it for Jenkins at least last time.

**Comment by alex** [comment]
:+1:

**Comment by vszakats** [comment]
Let's brace ourselves for a build-error:
https://groups.google.com/forum/#!topic/mailing.openssl.dev/gYxZkC4F08o

**Comment by alex** [comment]
Jenkins tests failed, but it doesn't appear to be because of that build failure; there's a bunch of unrelated deps stuff which caused it as far as I can tell.

**Comment by DomT4** [comment]
> UPDATE: Happens hopefully on old OS versions only.

Yeah, spotted that ping into my inbox and groaned :smile:. All the CI build failures look to be CI related rather than OpenSSL related.

**Comment by vszakats** [comment]
Sorry, for false alarm @DomT4 :o Overall it looks like a lucky day, though the CI failure didn't look good at first sight.

**Comment by tdsmith** [comment]
Pulled in 3ac6215; thanks all!

**Comment by vszakats** [comment]
Thank you!

**Comment by tdsmith** [comment]
FWIW, @ reaperhulk says the unpatched release tarball builds fine on 10.7, so that's nice.

**Pull request closed without merging**
