### PR TITLE
ocaml: rename from objective-caml

### PR DESCRIPTION
**Pull request by vladshablinsky**
`objective-caml -> ocaml` from https://github.com/Homebrew/homebrew/issues/14374

### CODE REVIEW

**Comment by DomT4** [comment]
Do the dependencies elsewhere need changing from `objective-caml` to `ocaml` as well?

**Comment by dunn** [comment]
A few in versions and science as well:
```
./Taps/homebrew/homebrew-science/megam.rb:  depends_on "objective-caml"
./Taps/homebrew/homebrew-science/megam.rb:    ENV['WITHCLIBS'] = "-I #{Formula["objective-caml"].opt_lib}/ocaml/caml"
./Taps/homebrew/homebrew-science/proverif.rb:  depends_on "objective-caml"
./Taps/homebrew/homebrew-versions/camlp5-606.rb:  depends_on "objective-caml312"
./Taps/homebrew/homebrew-versions/coq83.rb:  depends_on "objective-caml312"
./Taps/homebrew/homebrew-versions/objective-caml312.rb:  conflicts_with "objective-caml", :because => "both install an ocaml binary"
./Taps/homebrew/homebrew-versions/unison232.rb:  depends_on "objective-caml"
./Taps/homebrew/homebrew-versions/unison240.rb:  depends_on "objective-caml" => :build
```

**Comment by vladshablinsky** [comment]
> Do the dependencies elsewhere need changing from objective-caml to ocaml as well?
No, they don't.

**Comment by mikemcquaid** [comment]
Let's see what happens.

**Comment by guoxiao** [comment]
This rename breaks `brew upgrade`
```
% brew upgrade                                                                                                                                             
Error: No such file or directory - /usr/local/Cellar/ocaml
```

**Comment by bfontaine** [comment]
@guoxiao Please open a new issue and explain how to reproduce the issue, thanks!

**Comment by guoxiao** [comment]
see #42938

**Comment by aw1621107** [comment]
Would a PR changing objective-caml to ocaml in the rest of the formulae be ok?

**Pull request closed without merging**
