### PR TITLE
charm-tools 1.9.1

### PR DESCRIPTION
**Pull request by marcoceppi**
This is a feature and bug fix release, deprecating 1.8.0

### CODE REVIEW

**Comment by marcoceppi** [comment]
Welp, not sure how to get at the pip that this installed, but `pip install -r requirements.txt` needs to run as well in this release.

**Comment by dunn** [comment]
We usually add python dependencies as `resources`, as in [`sphinx-doc.rb`](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/sphinx-doc.rb).  That way we can check the SHA and cache them.  Is that not possible here?

**Comment by DomT4** [comment]
Should be fine to do it our usual way, looking at the upstream code.

**Comment by marcoceppi** [comment]
It's easier to just patch `setup.py` and do a new upstream release than sort this out. See #46273

**Pull request closed without merging**
