### PR TITLE
pinentry 0.9.1

### PR DESCRIPTION
**Pull request by chdiza**

### CODE REVIEW

**Comment by DomT4** [comment]
Any chance we can add a mirror? http://mirrors.dotsrc.org/gcrypt/pinentry/ looks like it's regularly updated.

**Comment by chdiza** [comment]
I added a mirror that's also among the mirrors of most of the other `gnupg2`-related stuff.

**Comment by DomT4** [comment]
Thanks. I'll take any mirror that isn't an ` ftp:// ` mirror :smile_cat:

**Comment by xu-cheng** [comment]
Thanks for the pull request! 🎉 Homebrew depends on contributions from community members like you and we're grateful for your support.

**Pull request closed without merging**
