### PR TITLE
avce00: lib installed, test added

### PR DESCRIPTION
**Pull request by bfontaine**
I tried to write a test using the library but can’t find any arc/info sample file on the Web.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Could you try and fix: `Error: Add a new regex to bottle_version.rb to parse 2.0.0 from avce00-2.0.0.yosemite.bottle.tar.gz`? Thanks!

**Comment by bfontaine** [comment]
Do you know why [this regex](https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/bottle_version.rb#L28) fails to capture the version here?

**Comment by mikemcquaid** [comment]
@bfontaine it may be captured by a regex above that.

**Comment by bfontaine** [comment]
@mikemcquaid You’re right, I fixed the regex above.

**Comment by bfontaine** [comment]
All green :)

**Comment by mikemcquaid** [comment]
Thanks @bfontaine!

**Pull request closed without merging**
