### PR TITLE
glide updated to 0.3.0

### PR DESCRIPTION
**Pull request by mattfarina**

### CODE REVIEW

**Comment by mattfarina** [comment]
@mikemcquaid any idea when you're going to restart #40817 and this one?

**Comment by mikemcquaid** [comment]
@mattfarina At some point in the next 24h.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/fcdd1bbf048b37f1eee5d9ef684f4b7e4f133855. Thank you for your contribution to Homebrew, we appreciate it! :smiley_cat:.

Please note for future reference the preferred commit message style for version bumps is `glide 0.3.0` and checksums should be upgraded to `sha256`, Thanks!

**Comment by mattfarina** [comment]
Will do. Thanks.

**Pull request closed without merging**
