### PR TITLE
doctor: export command should use double quotes

### LINKED ISSUE #37496: Brew just screwed it all
Kosmos:icu kosmos$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so
    echo export PATH='/usr/local/sbin:$PATH' >> ~/.bash_profile
Kosmos:icu kosmos$ echo export PATH='/usr/local/sbin:$PATH' >> ~/.bash_profile
After running the recommendations from brew I get this:

Kosmos:~ kosmos$ ls
-bash: ls: command not found
Kosmos:~ kosmos$ brew
/usr/local/bin/brew: line 10: readlink: command not found
/usr/local/bin/brew: line 25: uname: command not found
/usr/local/bin/brew: line 25: tr: command not found
/usr/local/bin/brew: line 30: exec: ruby: not found
Kosmos:~ kosmos$ ps aux
-bash: ps: command not found
Kosmos:~ kosmos$ 

None of my CMD lines are working anymore. Any workaround this?

### PR DESCRIPTION
**Pull request by xu-cheng**
Closes #37496

### CODE REVIEW

**Comment by mikemcquaid** [comment]
This change is incorrect because if you use `echo` then the single-quotes are required for `$PATH` to be inserted as-is into the file rather than interpolated. Please revert. Thanks!

**Comment by xu-cheng** [comment]
> This change is incorrect

:cry: Let me do some test to clear my head.

> the single-quotes are required for $PATH to be inserted as-is into the file rather than interpolated.

Then I would say the correct command should be 
```
echo 'export PATH="#{HOMEBREW_PREFIX}/bin:$PATH"' >> ~/.bash_profile
```

We need the double quotes in case there are spaces in the `$PATH`.

**Comment by mikemcquaid** [comment]
The previous version is correct as-is as the single-quotes are only needed for the `$PATH` and `HOMEBREW_PREFIX`. Will comment more on #37500.

**Comment by bfontaine** [comment]
Here is a quick explanation, just FYI:

Bash variables expansion occurs when you write `$your_variable_name`.

```
$ a=2
$ echo $a
2
```

It also works in double-quoted strings:

```
$ a=3
$ echo "a is $a"
a is 3
```

Using double-quoted strings, even for a single variable, is a good practice because Bash always sees the string as one argument. If a variable is expanded to multiple words (i.e. it contains spaces), Bash will treat them as multiple arguments.

```
$ myfiles="foo bar"
$ touch $myfiles
$ ls -l
total 0
-rw-r--r--  1 baptiste  wheel  0  8 mar 10:14 bar
-rw-r--r--  1 baptiste  wheel  0  8 mar 10:14 foo
$ touch "$myfiles"
$ ls -l
total 0
-rw-r--r--  1 baptiste  wheel  0  8 mar 10:14 bar
-rw-r--r--  1 baptiste  wheel  0  8 mar 10:14 foo
-rw-r--r--  1 baptiste  wheel  0  8 mar 10:14 foo bar
```

Note I had to use `myfiles="foo bar"` instead of `myfiles=foo bar` because otherwise Bash thinks I want to execute `bar` with the env variable `myfiles` set to `foo`.

Now, what if we wanted to include a dollar sign in a shell script without having it expanded? `$$` doesn’t work, because it’s a special variable for the current shell PID. We can escape it with a backslash:

```
$ echo "\$PATH"
$PATH
```

But backslashes are ugly, so Bash allows us to use *single-quoted* strings, which are the same as double-quoted except that variable expansion doesn’t occur:

```
$ echo '$PATH'
$PATH
```

This becomes handy when you write code that write code, like above. When you write the following code, the part between single quotes *is* some Bash code, which you don’t want to be executed now, `$PATH` must be expanded when the user sources its `~/.bash_profile` (i.e. when they start a Bash session).

```sh
echo 'export PATH="#{HOMEBREW_PREFIX}/bin:$PATH"' >> ~/.bash_profile
```

```
$ a=foo
$ echo export a="bar:$a"
export a=bar:foo
$ echo 'export a="bar:$a"'
export a="bar:$a"
```

**Comment by xu-cheng** [comment]
@bfontaine Thanks for sharing. I used to thought `echo export a='$a'` would print out `export a='$a'`. Now I know I am wrong. Fixed this in #37500.

**Pull request closed without merging**
