### PR TITLE
python3 3.5.0a1 (devel)

### PR DESCRIPTION
**Pull request by tdsmith**
* bump pip to 6.0.8
* add 3.5.0a1 devel
* bump head to 3.5
* replace VER with xy method

### CODE REVIEW

**Comment by tdsmith** [comment]
Failure is a problem testing sip on Mountain Lion:

==> /usr/bin/clang++ -c /private/tmp/sip-ZxTyeo/siptestcmodule.cpp -o siptestcmodule.o -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -fno-strict-aliasing -fno-common -dynamic -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -mno-fused-madd -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -I/usr/local/Cellar/sip/4.16.5/include
clang: error: unknown argument: '-mno-fused-madd' [-Wunused-command-line-argument-hard-error-in-future]
clang: note: this will be a hard error (cannot be downgraded to a warning) in the future
Error: sip: failed

Questions of the day:
* why is sip's test using system python-config on Mountain Lion with a :python dependency?
* why is system python-config emitting flags that the system compiler can't use?

**Comment by mikemcquaid** [comment]
> why is sip's test using system python-config on Mountain Lion with a :python dependency?

The test environment is not the same as the build environment. This is a long-standing issue that we should probably fix at some point.

**Comment by tdsmith** [comment]
Oops, I knew that, thanks!

Is this workaround too hacky?

**Comment by tdsmith** [comment]
Hmm, I guess python isn't getting postinstalled during the test cycle?

**Comment by tdsmith** [comment]
Yeah, setting PYTHONPATH to `lib/python#{version}/site-packages` in `test` allows the tests to pass.

System python needs PYTHONPATH set because it doesn't look in /usr/local, and Homebrew Python needs PYTHONPATH set because it doesn't get post-installed on the bot, so it doesn't look in /usr/local either.

**Pull request closed without merging**
