### PR TITLE
fix nimrod formula

### PR DESCRIPTION
**Pull request by jeizsm**

### CODE REVIEW

**Comment by dunn** [comment]
```
==> /bin/sh bootstrap.sh
/bin/sh: bootstrap.sh: No such file or directory
```
I don't see a `bootstrap.sh` in the 0.11.2 tarball.

**Comment by dunn** [comment]
Could you also update `sha1`s to `sha256`, please? Thanks!

**Comment by jeizsm** [comment]
@dunn done

**Comment by dunn** [comment]
Thanks! Merged in 08181f77c3885673d0a99e22b64feb040e7b7c28.

**Pull request closed without merging**
