### PR TITLE
[WIP] gpac: make x11 dependency optional.

### PR DESCRIPTION
**Pull request by mikemcquaid**
This is surprisingly stubborn about picking up X11 even when told not to.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
@BrewTestBot test this please

**Comment by mikemcquaid** [comment]
CC @DomT4 in case you want to try and play with this at all.

**Comment by DomT4** [comment]
Regardless of what `--X11-path` is set to, `configure` will always check `/usr/X11R6`, and since we leave `/usr` in the `$PATH` it seems to be able to follow the symlink from `/usr/X11R6` to `/opt/x11` and scoop up the X11 availability, which it then uses, even when told not to.

This works:

```ruby
    else
      # Configure works around our superenv by ignoring a set
      # X11-path variable and detecting /usr/X11R6 regardless
      # which is hardcoded into configure.
      inreplace "configure", "has_x11=\"yes\"", "has_x11=\"no\""
      args << "--disable-x11-shm" << "--disable-x11-xv"
    end
```

**Comment by DomT4** [comment]
Reported upstream and opened #40566.

**Pull request closed without merging**
