### PR TITLE
pod2man: fix location of pod2man archive has changed

### PR DESCRIPTION
**Pull request by lapthorn**
Location of the pod2man archive has changed - now points to the new location.

See https://archives.eyrie.org/software/ARCHIVE/podlators/ for the whole archive

### CODE REVIEW

**Comment by lapthorn** [comment]
Current URL 301s --> 404, updated location 200s.

**Comment by DomT4** [comment]
It seems to have moved because there's a version update available. Perhaps we could do that instead?

**Comment by lapthorn** [comment]
Cool - closing this PR - doing a separate upgrade commit/PR

**Comment by lapthorn** [comment]
@DomT4 https://github.com/Homebrew/homebrew/pull/48702

**Pull request closed without merging**
