### PR TITLE
fix homebrew.mxcl.mongodb.plist open file limits

### PR DESCRIPTION
**Pull request by bmike**
65k is too large an open file limit.

Set the soft limit to 1000
Set the hard limit to 1023

### CODE REVIEW

**Comment by mikemcquaid** [comment]
> 65k is too large an open file limit.

Why?

**Comment by bmike** [comment]
Sorry - the why got lost on a test merge.

Setting the files in excess of kernel limits is bad. The OS ignores the settings silently when you call for 65k files for the mongodb process. It inherits the bash(or default shell) ulimit of 256 and ignores the code request for 

I've selected a large enough limit to suppress the mongodb warning but small enough to not cause stability issues / run into kernel limits.

    Mac:mongodb bmike$ sysctl kern.maxfiles kern.maxfilesperproc
    kern.maxfiles: 12288
    kern.maxfilesperproc: 10240

Is this the why you seek?

**Comment by bmike** [comment]
Here's the source of the problem as I see it. You could accept this PR or reverse that one:

https://github.com/Homebrew/homebrew/commit/058e57ffb11acfa5432c73ac55807ec30ba35b50

**Comment by mikemcquaid** [comment]
@fmela do you have thoughts on this?

**Comment by fmela** [comment]
Reverting the change would again break MongoDB when using the WiredTiger storage engine for most users.

I used an aggressive value of 65536, which also requires ones to bump up the sysctl limits that @bmike mentioned. This can be accomplished with launchctl, e.g.:

```
sudo launchctl limit maxfiles 100000 100000
```

I think a less aggressive limit of 10240 makes sense, since it should work for everyone without requiring a corresponding sysctl change.

**Comment by bmike** [comment]
@fmela Thanks for weighing in.Some thoughts as to why I chose 1000/1023 files per mongod process:

* Setting the limit at 10240 is over 80% of the entire kernel's file count for all processes. Starting two mongodb would then easily exhaust all file handles for the system. That's still quite aggressive IMO.
* WiredTiger is not the default storage engine for 3.0 - nor is it specified in the existing plist (so if you edit it to change to the non-default engine, you can change your limits at with that edit).
* The vendor only asks for 1000 files, so I'd rather follow their guidance out of the box.
*  I've been using WiredTiger with 1000 files with no issues on 3.0, 3.0.1 and 3.0.2

I'm not sure what "most users" is, but 10k per mongod seems large for the initial settings IMO.

**Comment by fmela** [comment]
@bmike I'm happy to discuss and find a solution that works for everyone.

The WiredTiger engine organizes each collection and index in its own file, which means one can very easily run into the file descriptor limit unless it has been raised. You can reproduce this by running db.stats() on a database with a enough collections and indexes to exceed the limit and watch the server process crash (at least, it was the case with version 3.0.1, but I haven't attempted with 3.0.2). I don't think that a database with more than 1000 collections and indexes is out of the ordinary at all.

If we set the limit to 10,240, it does not mean MongoDB will use all of the available descriptors. It will use as many descriptors as it needs, and it will crash if its requirements cannot be satisfied. I intended to set the limit high enough that so that file descriptor limits will become a non-issue.

**Comment by fmela** [comment]
I should add that we ought to fix the issue @bmike ran into (which effectively reduces the limit to just 256 descriptors!) ASAP. Perhaps we can reopen the discussion about what the new limit should be on a different pull request.

**Comment by bmike** [comment]
Sounds great to me. Thanks for the use case. I'll see if I can punish things a bit with WireTiger and see the error messages. Having it set for out of the box reasonableness would be win/win for both storage engines.

**Comment by mikemcquaid** [comment]
What are the default limits without bumping them manually? Can we try and reach some sort of agreement on actual numbers? Thanks!

**Comment by bmike** [comment]
Mongodb ussues a warning if it can't get 1000 files. 

OS X defaults to 256 since the home brew asks for more files than the defaults I posted above. `sysctl`

**Comment by fmela** [comment]
I don't believe the ulimit comes into play if the process is being launched by launchctl. I think the relevant limits are the sysctl parameters (default to 12288 per system and 10240 per process) and the launchctl maxfiles parameters. How about we use 4096 as the limit (rather than the original 1024)? Even if MongoDB uses all the descriptors allocated to it, that still leaves plenty for the rest of the system.

**Comment by mikemcquaid** [comment]
4096 works for me if it does for everyone else.

**Comment by bmike** [comment]
I did a quick survey of 20 macs that I had handy. The only one that had less than 5000 open files on / was a Mac Mini server for someone at home, running caching server and time machine server and no user even logged in. (and it clocked in with 4619 open files)

    server:~ bmike$ sudo lsof / | wc -l
        4619
    server:~b mike$ lsof / | cut -f 1 -d " "  | sort | uniq -c | sort -n | tail
       7 pkd
       8 lsof
       8 secinitd
       8 tccd
      13 IMDPersis
      13 secd
      18 sshd
      22 com.apple
      24 bash
      62 cfprefsd


10.10 grants 12288 open files on non Server.app Macs so I'm more comfortable with the 1000 I proposed in the PR, but 4k is fine if it gets the 65k number reduced sooner rather than later.

**Comment by mikemcquaid** [comment]
Let's go for 4096.

**Comment by bmike** [comment]
@mikemcquaid I assume you were waiting for me to fix the file? What next?

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
