### PR TITLE
Fixing audit warnings

### PR DESCRIPTION
**Pull request by mrjbq7**
Fixed a number of ``brew audit`` warnings.

* Switch to ``https`` urls
* Switch to ruby versions of ``mv``, ``rm``, ``touch``, ``chmod``
* Fix wiki.freedesktop.org urls

Before:

``Error: 304 problems in 238 formulae``

After:

``Error: 38 problems in 36 formulae``

### CODE REVIEW

**Comment by DomT4** [comment]
Welp, this is going to set fire to the bots :smile_cat:. Homebrew doesn't usually accept such wide PRs, because when users do ` brew update ` they'll see a list of 300 formulae updated and most people panic in that situation. Maintainers here may welcome this PR in smaller chunks.

**Comment by jacknagel** [comment]
Yes, please do break this up and submit in in smaller increments (spread out over a longer period of time). Thanks!

**Comment by jacknagel** [comment]
Also, please avoid changing any `gnome` URLs, as I know others are working on these already.

**Comment by mrjbq7** [comment]
@jacknagel couple questions:

1) How small, and over how many weeks would you like these changes to be spread? I would personally would rather rip the bandaid off quickly...

2) The gnome URLs are changed to ``https`` because ``brew audit`` produced warnings and were fixed. Why is this bad?

https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/cmd/audit.rb#L311

**Comment by jacknagel** [comment]
We have limited CI resources, and pull requests of this size block everything else from moving forward. I would say no more than 10 changed formula per PR, per day.

>The gnome URLs are changed to https because brew audit produced warnings and were fixed. Why is this bad?

Because, as I said, others are already working on this and it will conflict with their work. Thanks!

**Comment by mrjbq7** [comment]
Oh, I misunderstood re: gnome.

Okay, I'll do smaller patches!

**Pull request closed without merging**
