### PR TITLE
git-extras 4.1.0, with audit fixes

### PR DESCRIPTION
**Pull request by apjanke**

### CODE REVIEW

**Comment by apjanke** [comment]
The Travis CI build failed. Looks like it's because I accidentally pushed this to a branch on the main Homebrew repo and then deleted it before pushing it to my fork and submitting the PR. It's trying to grab the nonexistent branch from the main repo.

```
Worker information
hostname: worker-jupiter-brain:73a293e1-4a90-44fe-a30e-e3d755a37664
version: v2.0.0 https://github.com/travis-ci/worker/tree/ca6cb0c5d3920912b1c3acc87c44a5da2120a971
instance: e98b878f-90dc-4872-b732-788a3f53ac06:
startup: 1m7.185132661s
Build system information
Build language: objective-c
Build group: stable
Build dist: precise

$ git clone --depth=50 --branch=git-extras-4.1.0 https://github.com/Homebrew/homebrew.git Homebrew/homebrew
Cloning into 'Homebrew/homebrew'...
warning: Could not find remote branch git-extras-4.1.0 to clone.
fatal: Remote branch git-extras-4.1.0 not found in upstream origin

The command "eval git clone --depth=50 --branch=git-extras-4.1.0 https://github.com/Homebrew/homebrew.git Homebrew/homebrew" failed. Retrying, 2 of 3.

Cloning into 'Homebrew/homebrew'...
warning: Could not find remote branch git-extras-4.1.0 to clone.
fatal: Remote branch git-extras-4.1.0 not found in upstream origin

The command "eval git clone --depth=50 --branch=git-extras-4.1.0 https://github.com/Homebrew/homebrew.git Homebrew/homebrew" failed. Retrying, 3 of 3.

Cloning into 'Homebrew/homebrew'...
warning: Could not find remote branch git-extras-4.1.0 to clone.
fatal: Remote branch git-extras-4.1.0 not found in upstream origin

The command "eval git clone --depth=50 --branch=git-extras-4.1.0 https://github.com/Homebrew/homebrew.git Homebrew/homebrew" failed 3 times.



The command "git clone --depth=50 --branch=git-extras-4.1.0 https://github.com/Homebrew/homebrew.git Homebrew/homebrew" failed and exited with 128 during .

Your build has been stopped.

```

Looks like the Jenkins build is going, though. Will just merge if that passes.

**Comment by apjanke** [comment]
Actually, there are two Travis CI runs that are showing up attached to this PR. One is labeled "continuous-integration/travis-ci/pr" and is running the code in this PR, and another is "continuous-integration/travis-ci/push", and is trying to run the code found in the branch pushed to the main repo. Don't know why it is showing up on this PR; maybe because of the matching branch names.

**Comment by apjanke** [comment]
Merged.

CC @qw3rtman: if you do a `brew update && brew upgrade` (or `brew install git-extras` if you don't have it installed already), you and other users should get the new 4.1.0 release now.

**Comment by qw3rtman** [comment]
Yep, working. Thanks, @apjanke! :+1:

**Pull request closed without merging**
