### PR TITLE
cogl, clutter and clutter-gtk: version bumps

### PR DESCRIPTION
**Pull request by tschoonj**

### CODE REVIEW

**Comment by tschoonj** [comment]
@DomT4 can you restart this build please? Thanks!

**Comment by DomT4** [comment]
Afraid you'll have to bear with us for a little bit. We're starting to work through the backlog caused by the significant CI problems this week, so we'll get to this as soon as possible.

**Comment by DomT4** [comment]
@BrewTestBot test this please

**Comment by tschoonj** [comment]
more docbook trouble :disappointed:

**Comment by DomT4** [comment]
Ugh, yup. Will try and find some time tonight to test your other PR and try and work out why El Cap is falling apart on this :cry:.

```
checking for XML catalog... /usr/local/etc/xml/catalog
checking for xmlcatalog... /usr/local/opt/libxml2/bin/xmlcatalog
checking for DocBook XML DTD V4.3 in XML catalog... not found
configure: error: could not find DocBook XML DTD V4.3 in XML catalog
==> Formula
Path: /usr/local/Library/Formula/gtk-doc.rb
```

**Comment by tschoonj** [comment]
I am also still looking into this, have already launched a few build jobs to see more clearly...

**Comment by tschoonj** [comment]
@DomT4 This one also needs a rebuild now that your merged in docbook

**Comment by DomT4** [comment]
@BrewTestBot test this please

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/893f9fa6948897dba44c15b7a833669566db94e7, https://github.com/Homebrew/homebrew/commit/1aa0c82825b2474fe5f8fd5d9abbfd0fac9c7aa3 & https://github.com/Homebrew/homebrew/commit/fdb9a03d738e3849beb771c1cf10a034299c7437. Thank you once more :smiley_cat:

**Pull request closed without merging**
