### PR TITLE
Update xctool to v0.2.3

### PR DESCRIPTION
**Pull request by LegNeato**

### CODE REVIEW

**Comment by LegNeato** [comment]
Not sure why it says it failed, perhaps a CI issue?

**Comment by albertschulz** [comment]
+1

**Comment by HeEAaD** [comment]
+1

**Comment by leviathan** [comment]
+1

**Comment by mikemcquaid** [comment]
Don't :+1: PRs, please.

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

For future reference the preferred commit message format for simple version updates is `xctool 0.2.3`.

**Pull request closed without merging**
