### PR TITLE
fetchmail: explicitly specify openssl prefix

### PR DESCRIPTION
**Pull request by lembacon**

### CODE REVIEW

**Comment by DomT4** [comment]
Is it not currently picking up on Homebrew's OpenSSL correctly in some way?

**Comment by lembacon** [comment]
@DomT4 On OS X El Capitan (as of beta 2), it will attempt to pick up the nonexistent system OpenSSL.

**Comment by mikemcquaid** [comment]
Can you gist the error, out of interest? Thanks!

**Comment by lembacon** [comment]
@mikemcquaid https://gist.github.com/1c4301ebc11897a7c182

**Comment by jacknagel** [comment]
Looking at the configure script, it just loops over a list of some common places that openssl can be found (/usr/local, /usr, etc.) but since the headers are missing from 10.11 it fails.

**Pull request closed without merging**
