### PR TITLE
mapnik: enable use of "cellar :any"

### PR DESCRIPTION
**Pull request by springmeyer**
- Fixes hardcoded paths by defining `-DBOOST_EXCEPTION_DISABLE`
 - Enables `cellar :any` in order for bottles to work from any path
 - Replaces #41526

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Nice :clap:

**Comment by DomT4** [comment]
Curious if this actually works for you, the bot didn't throw the `cellar :any` out when I pulled the updated bottle, but if I regenerate a bottle locally it doesn't tag it `cellar :any` any more for me:

```
==> Detecting if mapnik-3.0.0.yosemite.bottle.2.tar.gz is relocatable...
./mapnik-3.0.0.yosemite.bottle.2.tar.gz
  bottle do
    revision 2
    sha256 "d735290c985a96100d2516bb903e0750b53328a656d9ea0b06de1c1b32ec7d84" => :yosemite
  end
```

Let us know. Thanks for the PR!

**Comment by mikemcquaid** [comment]
@DomT4 Looks relocatable here.

**Comment by DomT4** [comment]
Oh well, maybe my bottle decided to sulk for some reason. If it works, all is cool :octopus:

**Comment by springmeyer** [comment]
Also confirmed that installing from a bottle works now for me (using alternative homebrew prefix) after stashing my local changes and pulling latest homebrew. Thanks for the help in figuring this out!

**Pull request closed without merging**
