### PR TITLE
chipmunk: use https urls

### PR DESCRIPTION
**Pull request by vszakats**

### CODE REVIEW

**Comment by vszakats** [comment]
Download fails on Yosemite alone:
```
==> Downloading https://chipmunk-physics.net/release/Chipmunk-7.x/Chipmunk-7.0.1.tgz
/usr/bin/curl -fLA Homebrew 0.9.5 (Ruby 2.0.0-481; OS X 10.10.4) https://chipmunk-physics.net/release/Chipmunk-7.x/Chipmunk-7.0.1.tgz -C 0 -o /Library/Caches/Homebrew/chipmunk-7.0.1.tgz.incomplete --silent
Error: Failed to download resource "chipmunk"
```

It worked on my Yosemite fine (with stock `curl`), which may indicate a transient error.

**Comment by mikemcquaid** [comment]
Rebuilding!

**Comment by vszakats** [comment]
Thanks @mikemcquaid! Greened out now.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/ab17e0391f59c7c1baa5fef1880137e43c4dda11. Thank you @vszakats!

**Pull request closed without merging**
