### PR TITLE
wine flicker patch

### PR DESCRIPTION
**Pull request by dholm**
Re-add the patch for screen flickering since the issue is unresolved.

### CODE REVIEW

**Comment by dholm** [comment]
The bug is still unresolved so I don't know why you removed the patch?

https://bugs.winehq.org/show_bug.cgi?id=34166

**Comment by LinusU** [comment]
Hi, I saw this a bit late and actually submitted my own pr #44555 to address this. It does bump the `revision` thought which is needed since `brew` won't pick it up as a new version otherwise, and anyone who already upgraded to 1.7.52 will be stuck without the patches.

If you add that we could merge this one, otherwise we could just merge mine instead.

Cool to see that I'm not the only one confused by why they just dumped the patch without requiring any reason as to why.

:rocket:

**Comment by dholm** [comment]
@LinusU Done!

**Comment by LinusU** [comment]
Cool, I'll close mine and link to this

**Comment by dholm** [comment]
@LinusU I just realized you authored the original patch.  Thanks! :D

**Comment by dunn** [comment]
Apologies for that. I'll merge this as soon as it's green.

**Comment by LinusU** [comment]
@dunn Thanks! It wont become green thought, since the build exceeds the time limit. It wasn't green on the previous pr you merged.

**Comment by dunn** [comment]
It was green on Jenkins, which is the CI we're relying on.

**Comment by LinusU** [comment]
Aha, sorry, I was looking at the Travis one.

On a related note, can I only see that build status if I grant the brew bot read access to all my, and any organization I belong to, private repos. I can't access it right now just because I don't want to give away my employers code, seems very strange...

**Comment by uyjulian** [comment]
Hmm... I'll add that bug page to my bookmarks just in case the patch fails to apply again, and somebody posted a new one

**Comment by dunn** [comment]
Unfortunately we don't have control over what permissions Jenkins asks for.

**Comment by dunn** [comment]
The El Capitan bot choked; I've re-queued the builds.

**Comment by DomT4** [comment]
> On a related note, can I only see that build status if I grant the brew bot read access to all my, and any organization I belong to, private repos. I can't access it right now just because I don't want to give away my employers code, seems very strange

It doesn't *read* the code; It checks which organisations you are part of to see what level of permissions it should give you in accessing the CI.

**Comment by LinusU** [comment]
@DomT4 Ahh, well that explains it. I read it as read access to my and my organizations data. Thx.

**Comment by LinusU** [comment]
@dunn Seems like it worked \o/ time to merge?

**Comment by dunn** [comment]
:wine_glass: 02eefc7c2443a1bd45a71619eb21e882b44ed68d :wine_glass:

**Comment by LinusU** [comment]
Thank you! :wine_glass: :100:

**Pull request closed without merging**
