### PR TITLE
FFmpeg: add dcadec option

### PR DESCRIPTION
**Pull request by AirPort**
This library was added only recently to homebrew, add the option to build FFmpeg with it.

### CODE REVIEW

**Comment by bfontaine** [comment]
@BrewTestBot test this please.

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Comment by rolyreyes** [comment]
In order for this to actually work, "—disable-decoder=dca" must also be passed. Otherwise ffmpeg will prefer the older dts decoder.

**Comment by mikemcquaid** [comment]
> In order for this to actually work, "—disable-decoder=dca" must also be passed. Otherwise ffmpeg will prefer the older dts decoder.

@rolyreyes Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Pull request closed without merging**
