### PR TITLE
Remove outdated graylog2-server

### PR DESCRIPTION
**Pull request by joschi**
The formula is for an ancient version of Graylog2 and doesn't work because
the tar ball doesn't exist any more.

### CODE REVIEW

**Comment by xu-cheng** [comment]
Should it move to homebrew/boneyard ?

**Comment by joschi** [comment]
The version is really ancient and the download URL is broken. I'm not sure that anyone would find it useful anymore.

**Comment by xu-cheng** [comment]
Wasn't that what boneyard stands for?

**Comment by mikemcquaid** [comment]
It is, yep. Can you add it to `tap_migrations.rb` and create a PR on the boneyard to add it there.

**Comment by joschi** [comment]
@mikemcquaid I've updated the PR.

**Pull request closed without merging**
