### PR TITLE
riemann 0.2.10

### PR DESCRIPTION
**Pull request by mnuessler**

### CODE REVIEW

**Comment by mnuessler** [comment]
It seems that the riemann download server has a limit on the number of downloads you can do within a period of time.

**Comment by mikemcquaid** [comment]
> It seems that the riemann download server has a limit on the number of downloads you can do within a period of time.

Could you see if you can find a `mirror`?

**Comment by mnuessler** [comment]
I could not find any mirror so far.

Interestingly I can download it locally many times in a row using `wget http://aphyr.com/riemann/riemann-0.2.10.tar.bz2`. But it fails on second attempt using `brew fetch --retry --build-bottle --force riemann`:
```
==> Downloading https://aphyr.com/riemann/riemann-0.2.10.tar.bz2

curl: (22) The requested URL returned error: 429
==> Retrying download
==> Downloading https://aphyr.com/riemann/riemann-0.2.10.tar.bz2

curl: (22) The requested URL returned error: 429
Error: Failed to download resource "riemann"
Download failed: https://aphyr.com/riemann/riemann-0.2.10.tar.bz2
```

**Comment by dunn** [comment]
Sometimes servers treat wget and curl differently.  Can you repeatedly download it yourself using curl?

**Comment by mnuessler** [comment]
With curl I can download it repeatedly too. Only with `brew fetch` it fails, but I have no idea what is done differently there.

**Comment by dunn** [comment]
Went ahead and merged this in 02d219b58d254c0e8bd77a73d901b0e03af13818, but if you want to go the extra mile and find a mirror or ask the developers about their server settings, that'd be awesome!

**Pull request closed without merging**
