### PR TITLE
ldc 0.17.0-beta2 (devel)

### PR DESCRIPTION
**Pull request by John-Colvin**

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Failing to build, sadly: http://bot.brew.sh/job/Homebrew%20Pull%20Requests/40094/version=el_capitan/testReport/junit/brew-test-bot/el_capitan/install___devel_ldc/

**Comment by apjanke** [comment]
On CI:

```
cd /tmp/ldc20160114-4648-5vhneb/ldc-0.16.1-src && /tmp/ldc20160114-4648-5vhneb/ldc-0.16.1-src/build/bin/ldc2 --output-o -c -I/tmp/ldc20160114-4648-5vhneb/ldc-0.16.1-src/runtime/druntime/src -I/tmp/ldc20160114-4648-5vhneb/ldc-0.16.1-src/runtime/druntime/src/gc /tmp/ldc20160114-4648-5vhneb/ldc-0.16.1-src/runtime/druntime/src/core/atomic.d -of/tmp/ldc20160114-4648-5vhneb/ldc-0.16.1-src/build/runtime/src/core/atomic.o -w -d -O3 -release -disable-invariants
ldc2(5445,0x7fff72e43000) malloc: *** mach_vm_map(size=140237583474688) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
Error: out of memory
make[2]: *** [runtime/src/core/atomic.o] Error 1
make[1]: *** [runtime/CMakeFiles/druntime-ldc.dir/all] Error 2
make: *** [all] Error 2
```

I don't think this is a regression caused by this PR: this PR only affects the `devel` version, and the bots are testing the `stable` version. I get a similar "out of memory" error when doing a `brew install -s ldc` using the current formula locally on my 4 GB OS X 10.9 VM.

I say we just merge this, and open a separate issue for the build failure. It's not OP's problem.

**Comment by John-Colvin** [comment]
I think this is ready to go now.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/f867a42f93f05a9bf2e3c7de48f7b1a2256a4eca. Thanks @John-Colvin!

**Pull request closed without merging**
