### PR TITLE
legit: install completion files

### PR DESCRIPTION
**Pull request by wkentaro**

### CODE REVIEW

**Comment by bfontaine** [comment]
We should probably add a `revision 1` here.

**Comment by wkentaro** [comment]
Updated.

**Comment by xu-cheng** [comment]
I suggest you use single PR to update the same formula. Otherwise, it's easy to confuse our ci bot.

**Comment by xu-cheng** [comment]
Thanks for the pull request! 🎉 Homebrew depends on contributions from community members like you and we're grateful for your support.

**Pull request closed without merging**
