### PR TITLE
formula_installer: rename "dependent"

### PR DESCRIPTION
**Pull request by mikemcquaid**
Dependent, to me at least, means something related to a dependency.
It’s always been exceptionally confusing to me that this actually means
“a dependency or actually just a formula”. Rename it so it’s clear it’s
just a formula.

### CODE REVIEW

**Comment by xu-cheng** [comment]
Personally, I have no problem to use `dependent`.

> this actually means “a dependency or actually just a formula”.

This means the formula which a dependency comes from.

By renaming to `formula`, it will be confused with the `formula` of `FormulaInstaller`. i.e. the formula currently is being installed.

And besides, `e.formula = formula.full_name` is incorrect without changing [the method in Exception](https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/exceptions.rb#L39-Lundefined)

**Comment by mikemcquaid** [comment]
> By renaming to formula, it will be confused with the formula of FormulaInstaller. i.e. the formula currently is being installed.

I'm happy to use `f` consistently.

> And besides, e.formula = formula.full_name is incorrect without changing the method in Exception

I can fix this.

Would you object to it being merged once that's fixed?

**Comment by xu-cheng** [comment]
I'm in the neutral ground for this change. And I'm happy to see what are other maintainers' opinion. That to be said, if we merge this, it would be better to change all of `dependent` in the codebase.

**Comment by UniqMartin** [comment]
I think that in the context of dependency handling it has its place in that it says: this is not an arbitrary formula (and not necessarily the formula to be installed), but the thing that invoked the dependency or requirement that is currently being handled.

In some of the code you are touching there are pairs of the form dependent–dependency or dependent–requirement. I think “dependent” has a narrower meaning than “formula” and thus makes the relationship between the two clearer.

**Comment by mikemcquaid** [comment]
> this is not an arbitrary formula (and not necessarily the formula to be installed), but the thing that invoked the dependency or requirement that is currently being handled.

It is the formula that is installed, though, which is not the `dependent` of anything. That's my issue.

**Pull request closed without merging**
