### PR TITLE
mysql 5.7.9

### PR DESCRIPTION
**Pull request by DomT4**
Broke the very incompatible with the prior version formula changes into each commit so it's more obvious what changed and why. There's *a lot* still borked here.

### CODE REVIEW

**Comment by DomT4** [comment]
**innotop**:
```
Warning: duplicate function definition 'do' detected in mysql.xs, line 242
Warning: duplicate function definition 'rows' detected in mysql.xs, line 754
cc -c  -I/System/Library/Perl/Extras/5.18/darwin-thread-multi-2level/auto/DBI -I/usr/local/opt/mysql/include/mysql -fno-omit-frame-pointer -DDBD_MYSQL_WITH_SSL -DDBD_MYSQL_INSERT_ID_IS_GOOD -g  -arch x86_64 -arch i386 -g -pipe -fno-common -DPERL_DARWIN -fno-strict-aliasing -fstack-protector -Os   -DVERSION=\"4.027\" -DXS_VERSION=\"4.027\"  "-I/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE"   mysql.c
mysql.xs:906:22: error: use of undeclared identifier 'net_buffer_length'
            retsv = newSViv(net_buffer_length);
                            ^
/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE/embed.h:377:40: note: expanded from macro 'newSViv'
#define newSViv(a)              Perl_newSViv(aTHX_ a)
                                                   ^
1 error generated.
make: *** [mysql.o] Error 1
make: *** Waiting for unfinished jobs....
```

**mysql-connector-odbc: does not build, `my_pthread.h` no longer exists, if you fix that**:

```
/tmp/mysql-connector-odbc20151104-28772-8thl6f/mysql-connector-odbc-5.3.4-src/util/stringutil.c:72:53: error: too few arguments to function call, expected 3, have 2
    SQLCHAR *u8= (SQLCHAR *)my_malloc(u8_max, MYF(0));
                            ~~~~~~~~~               ^
/usr/local/Cellar/mysql/5.7.9/include/mysql/mysql/service_mysql_alloc.h:66:1: note: 'my_malloc' declared here
extern void * my_malloc(PSI_memory_key key, size_t size, myf_t flags);
^
/tmp/mysql-connector-odbc20151104-28772-8thl6f/mysql-connector-odbc-5.3.4-src/util/stringutil.c:91:47: error: too few arguments to function call, expected 3, have 2
  out= (SQLWCHAR *)my_malloc(out_bytes, MYF(0));
                   ~~~~~~~~~                  ^
```

**mysql-proxy:**
```
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I.. -I/usr/local/opt/mysql/include/mysql -I/usr/local/Cellar/glib/2.46.1_1/include/glib-2.0 -I/usr/local/Cellar/glib/2.46.1_1/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/include/lua-5.1 -D_REENTRANT -I/usr/local/Cellar/glib/2.46.1_1/include/glib-2.0 -I/usr/local/Cellar/glib/2.46.1_1/lib/glib-2.0/include -I/usr/local/opt/gettext/include -g -O2 -c network_mysqld_proto_binary.c  -fno-common -DPIC -o .libs/libmysql_proxy_la-network_mysqld_proto_binary.o
network-mysqld-packet.c:1134:3: error: use of undeclared identifier 'CLIENT_SECURE_CONNECTION'
                CLIENT_SECURE_CONNECTION |
                ^
network-mysqld-packet.c:1262:36: error: use of undeclared identifier 'CLIENT_SECURE_CONNECTION'
                } else if (shake->capabilities & CLIENT_SECURE_CONNECTION) {
                                                 ^
network-mysqld-packet.c:1308:36: error: use of undeclared identifier 'CLIENT_SECURE_CONNECTION'
                } else if (shake->capabilities & CLIENT_SECURE_CONNECTION) {
                                                 ^
network-mysqld-packet.c:1321:36: error: use of undeclared identifier 'CLIENT_SECURE_CONNECTION'
                } else if (shake->capabilities & CLIENT_SECURE_CONNECTION) {
                                                 ^
network-mysqld-packet.c:1389:35: error: use of undeclared identifier 'CLIENT_SECURE_CONNECTION'
        } else if (shake->capabilities & CLIENT_SECURE_CONNECTION) {
                                         ^
network-mysqld-packet.c:1415:30: error: use of undeclared identifier 'CLIENT_SECURE_CONNECTION'
        auth->client_capabilities = CLIENT_SECURE_CONNECTION | CLIENT_PROTOCOL_41;
                                    ^
network-mysqld-packet.c:1472:36: error: use of undeclared identifier 'CLIENT_SECURE_CONNECTION'
                if ((auth->server_capabilities & CLIENT_SECURE_CONNECTION) &&
                                                 ^
network-mysqld-packet.c:1473:36: error: use of undeclared identifier 'CLIENT_SECURE_CONNECTION'
                    (auth->server_capabilities & CLIENT_SECURE_CONNECTION)) {
                                                 ^
```

**mytop**:
```
Warning: duplicate function definition 'do' detected in mysql.xs, line 242
Warning: duplicate function definition 'rows' detected in mysql.xs, line 754
cc -c  -I/System/Library/Perl/Extras/5.18/darwin-thread-multi-2level/auto/DBI -I/usr/local/opt/mysql/include/mysql -fno-omit-frame-pointer -DDBD_MYSQL_WITH_SSL -DDBD_MYSQL_INSERT_ID_IS_GOOD -g  -arch x86_64 -arch i386 -g -pipe -fno-common -DPERL_DARWIN -fno-strict-aliasing -fstack-protector -Os   -DVERSION=\"4.027\" -DXS_VERSION=\"4.027\"  "-I/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE"   mysql.c
mysql.xs:906:22: error: use of undeclared identifier 'net_buffer_length'
            retsv = newSViv(net_buffer_length);
                            ^
/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE/embed.h:377:40: note: expanded from macro 'newSViv'
#define newSViv(a)              Perl_newSViv(aTHX_ a)
                                                   ^
1 error generated.
make: *** [mysql.o] Error 1
make: *** Waiting for unfinished jobs....
```


**sysbench**:
```
clang -D_THREAD_SAFE  -g -O2      -o sysbench sysbench.o sb_timer.o sb_options.o sb_logger.o db_driver.o tests/fileio/libsbfileio.a tests/threads/libsbthreads.a tests/memory/libsbmemory.a tests/cpu/libsbcpu.a tests/oltp/libsboltp.a tests/mutex/libsbmutex.a drivers/mysql/libsbmysql.a -L/usr/local/opt/mysql/lib -lmysqlclient_r -lssl -lcrypto   -lm
ld: library not found for -lmysqlclient_r
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [sysbench] Error 1
make[1]: *** [install-recursive] Error 1
make: *** [install-recursive] Error 1
```

**Comment by DomT4** [comment]
Looks like `sysbench` has been fixed upstream, so might be able to backport https://github.com/akopytov/sysbench/commit/057e143b2774c9f28d5ae987c94c4326c1560264 potentially.

**Comment by DomT4** [comment]
The CI is being odd:

```
- Could not find (the correct version of) boost.
-- MySQL currently requires boost_1_59_0

CMake Error at cmake/boost.cmake:76 (MESSAGE):
  You can download it with -DDOWNLOAD_BOOST=1 -DWITH_BOOST=<directory>
```

The PR's initial commit *was* 6 days ago but has been rebased against the master from about 20 minutes ago, so it should know the new version of Boost :unamused:. CC @mikemcquaid

**Comment by mikemcquaid** [comment]
You can check the CI's `brew config` etc.

**Comment by DomT4** [comment]
Just wondered if I was missing some obvious git problem or something. Will poke the CI later.

**Comment by DomT4** [comment]
Looks like a CI thing rather than a git thing. https://github.com/Homebrew/homebrew/pull/45705 blew up on the same error, despite being a freshly cut branch straight off the master.

Will have to poke around the CI I guess.

**Comment by dmyers** [comment]
:+1:

**Comment by bfontaine** [comment]
@dmyers Please don’t write “:+1:” comments unless you have something to add to the discussion; thanks!

**Comment by DomT4** [comment]
Good news is that everything in this PR is passing. It's just the stuff that we know is broken that er, remains broken. Given two of the big remaining errors are Perl perhaps we need to limit it to OS X versions that support the Perl it wants or something.

**Comment by DomT4** [comment]
Small note, by "it" I mean the two troublesome formulae that haven't really been updated in yonks, not `mysql` :smile_cat:.

**Comment by mikemcquaid** [comment]
> Small note, by "it" I mean the two troublesome formulae that haven't really been updated in yonks, not mysql .

I think in these cases it's worth either boneyarding or just merging as-is.

**Comment by DomT4** [comment]
That should be everything fixed apart from `mysql-proxy` and `mysql-connector-odbc` which remain very broken. Fixed `sysbench` by backporting an upstream fix, fixed `innotop` and `mytop` by updating the MySQL Perl resource vendored to the latest released recently.

**Comment by mikemcquaid** [comment]
> That should be everything fixed apart from mysql-proxy and mysql-connector-odbc which remain very broken.

:skull: :wink:

**Comment by DomT4** [comment]
What should be the final build here is underway.

**Comment by DomT4** [comment]
It is done :tada:

**Comment by dmyers** [comment]
Great job @DomT4! Thanks for working on it.

**Comment by maguowei** [comment]
👏

**Pull request closed without merging**
