### PR TITLE
taylor 0.1.2

### PR DESCRIPTION
**Pull request by thelvis4**
Update `taylor` to version 0.1.2

### CODE REVIEW

**Comment by DomT4** [comment]
I'm not sure we've updated our CI infrastructure with 7.2.1 yet to be honest! This may have to wait for me to do that tonight.

**Comment by thelvis4** [comment]
@DomT4 any changes of the situation?

**Comment by DomT4** [comment]
It looks like it disagrees with your checksum:
```
==> Downloading from https://codeload.github.com/yopeso/Taylor/tar.gz/0.1.2
Warning: Formula reports different SHA256: 7c76f41037f261d2ee9a3c3d222c4eba61b26f708366e1f83caa02da7c878dfb
Downloaded to: /Library/Caches/Homebrew/taylor-0.1.2.tar.gz
SHA1: 00b528318337da3aa85e0272641b45352a77affb
SHA256: a9a5a68554577000ac67819f77946c3441994dd9b3774c356e3f42c792eb3af1
```

**Comment by DomT4** [comment]
(The CI has been updated, so once that's fixed this should pass fine)

**Comment by thelvis4** [comment]
@DomT4 That's weird, if you look [here](https://github.com/yopeso/Taylor/commit/b3a1ed6158ee9199306e8c2b3be639121f7654f2), the SHA of the tag 0.1.2 is `b3a1ed6` which gives me a SHA256  of `7c76f41037f261d2ee9a3c3d222c4eba61b26f708366e1f83caa02da7c878dfb`.
Might it be that previously a tag with the same name was created and it was cached somewhere?

**Comment by dunn** [comment]
The tarball will have a different checksum than the tree it's archiving, though.

**Comment by DomT4** [comment]
It's failing to build now because it's trying to breach the sandbox:
```
ln -sf "/usr/local/Cellar/taylor/0.1.2/bin/taylor" "/usr/local/bin/taylor"
ln: /usr/local/bin/taylor: Operation not permitted
make: *** [install] Error 1
```

**Comment by dunn** [comment]
Looks like it's happening here: https://github.com/yopeso/Taylor/blob/master/Resources/scripts/install#L20

That step seems unnecessary to me.

**Comment by thelvis4** [comment]
@dunn Actually it's [here](https://github.com/yopeso/Taylor/blob/master/Makefile#L19). I'll find a solution and I will recreate the tag.

**Comment by dunn** [comment]
Thanks!

**Comment by thelvis4** [comment]
Tag was updated. Now it seems fine. A job failed due to incompatible Xcode version.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/d251ef0d43828221f08fb6e9f901cae69ab49095. Thank you for another contribution to Homebrew @thelvis4! :smiley_cat:

**Comment by thelvis4** [comment]
@DomT4, @dunn  Thanks for your support! :beers:

**Pull request closed without merging**
