### PR TITLE
itstool: removed :python dependency

### PR DESCRIPTION
**Pull request by tschoonj**

### CODE REVIEW

**Comment by DomT4** [comment]
Probably still needs it on `snow_leopard` and below.

**Comment by DomT4** [comment]
Also possibly worth bumping the revision so we don't end up with some users still having it linked to Homebrew's Python and some to the system, etc. Sorry for not thinking of that earlier :sweat:.

**Comment by tschoonj** [comment]
@DomT4 done!

**Comment by DomT4** [comment]
Part of me is slightly worried this is somehow going to find a new and interesting way to blow up in our faces, but fingers crossed all goes smoothly. It passed the CI at least.

Merged in https://github.com/Homebrew/homebrew/commit/ad561e85536c588295b6bac52d4853d1501e9d4d. Thanks once more Tom!

**Comment by tschoonj** [comment]
Thanks for merging it in.

To see if it works properly, could you restart my remaining PRs? #45785 #45845 #45932 #45895 

Thanks!

**Pull request closed without merging**
