### PR TITLE
gv moved to homebrew/x11

### PR DESCRIPTION
**Pull request by bfontaine**
See Homebrew/homebrew-x11#60.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Thanks @bfontaine!

**Comment by bfontaine** [comment]
@mikemcquaid you should add the preferred commit format in [the documentation](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Migrating-A-Formula-To-A-Tap.md).

**Comment by mikemcquaid** [comment]
@bfontaine Good idea.

**Comment by mikemcquaid** [comment]
@bfontaine https://github.com/Homebrew/homebrew/commit/80cafaeb6492e5e7720586ae628c1e85408197d5

**Comment by bfontaine** [comment]
Thanks :+1:

**Pull request closed without merging**
