### PR TITLE
opam 1.2.2

### PR DESCRIPTION
**Pull request by DomT4**
Closes #39645

### CODE REVIEW

**Comment by bfontaine** [comment]
@BrewTestBot test this please.

**Comment by mikemcquaid** [comment]
:+1:

**Comment by DomT4** [comment]
Bottles seem to be failing to upload because the `opam` PR of three weeks ago uploaded some and it can't overwrite them. Will just manually kill the unused 1.2.2 bottles on Bintray and kick the bottle build off again.

**Comment by DomT4** [comment]
Yup, that worked.

**Comment by bfontaine** [comment]
Thanks @DomT4, merged :wink: 
Tell me if you’d prefer to merge your own PRs by yourself.

**Comment by DomT4** [comment]
> Tell me if you’d prefer to merge your own PRs by yourself.

It's cool :+1:. Leave my major stuff to be self-merged, but otherwise all the simple version bumps, etc I'm not fussed on who merges them.

**Pull request closed without merging**
