### PR TITLE
pypy 2.5.0

### PR DESCRIPTION
**Pull request by tdsmith**
* use upstream binary to bootstrap translation (discussion in #35618,
  #35248, #35176, #32765)
* bump pip and setuptools
* add test

### CODE REVIEW

**Comment by tdsmith** [comment]
Holler if we want a `--without-bootstrap` option or some conditional that selects system python instead.

**Comment by mikemcquaid** [comment]
> Holler if we want a --without-bootstrap option or some conditional that selects system python instead.

Yeh, we do I think. Even better would be if it's autoselected somehow based on being on an unsupported platform.

**Comment by tdsmith** [comment]
Okay! Added some logic to do that.

**Comment by mikemcquaid** [comment]
Looks good :+1: I still think at some point I'd like to try and get something (perhaps just in the bot) to handle the "bootstrap from an earlier bottle" because it'd be handy for loads of things.

**Comment by DomT4** [comment]
^ We're also going to have this problem with Go from 1.5. Go 1.5.x will require a 1.4 version of Go available to bootstrap, so our bottles seem like a decent bet there, unless like here we also use the last upstream binary.

**Comment by tdsmith** [comment]
Wishlist item noted!

**Comment by apjanke** [comment]
The `pypy3` formula still lacks the bootstrap mechanism. Would you like me to port it over based on the one here?

**Pull request closed without merging**
