### PR TITLE
gd: fix broken homepage and abandoned head url

### PR DESCRIPTION
**Pull request by vszakats**

### CODE REVIEW

**Comment by vszakats** [comment]
Already broken in a dependency, unrelated to this update. Closing.

**Comment by tdsmith** [comment]
May I reopen this?

**Comment by vszakats** [comment]
It's okay, please do.

**Comment by vszakats** [comment]
Would you like to reopen? I'd delete the branch if not needed anymore.

**Comment by vszakats** [comment]
Archived the `.diff` here for future reference:

```diff
diff --git a/Library/Formula/gd.rb b/Library/Formula/gd.rb
index 31b1a59..b13247a 100644
--- a/Library/Formula/gd.rb
+++ b/Library/Formula/gd.rb
@@ -1,10 +1,10 @@
 class Gd < Formula
-  homepage "https://libgd.bitbucket.org/"
+  homepage "https://libgd.github.io/"
   url "https://bitbucket.org/libgd/gd-libgd/downloads/libgd-2.1.1.tar.xz"
   sha256 "9ada1ed45594abc998ebc942cef12b032fbad672e73efc22bc9ff54f5df2b285"
 
   head do
-    url "https://bitbucket.org/libgd/gd-libgd.git"
+    url "https://github.com/libgd/libgd.git"
 
     depends_on "autoconf" => :build
     depends_on "automake" => :build
```

**Pull request closed without merging**
