### PR TITLE
haskell formulae: remove gmp dependencies

### PR DESCRIPTION
**Pull request by geoff-codes**
With a couple of other minor changes (change sha256, remove `fails_with :clang`s, as this shouldn't be necessary any more).

### CODE REVIEW

**Comment by mikemcquaid** [comment]
A few things failing to install.

**Comment by geoff-codes** [comment]
Yep. cless, cgrep, and iris, to be exact. It's our good friend the cabal dependency resolver: http://bot.brew.sh/job/Homebrew%20Pull%20Requests/26063/

They all have dependency checks for base (or lens) < 4.8, and ghc 7.10.1 ships with 4.8 (exactly). So these never would have built with 7.10.1 regardless; I'm sure if you look back at commit history, these all pre-date the change from 7.8.X to 7.10.X. so I'm not really sure how to attack this one.

**Comment by geoff-codes** [comment]
pandoc-citeproc built fine, but it's test block failed to produce any output. Not sure what that means? I didn't change the test, but assumedly it passed before...

**Comment by mikemcquaid** [comment]
In those cases I guess I'd just omit their `revision` bump and we won't rebottle them.

**Comment by geoff-codes** [comment]
@mikemcquaid  So, I propose that we loosen cabal's dependency checks, [semi-permanently](https://github.com/pullreq/homebrew/commit/5c3d8daba2686fc791544bbc9ea92f6ed3b0086c), as this fixes two of the three failures, and it seems to be the ticket [over here](https://github.com/pthariensflame/homebrew/commit/fe0f5eea803b0fe9d31348290d41010b45ee95d7#diff-54dba270edb9e5854d59fa08a34fdb38R36) as well.

I've also fixed the pandoc-citeproc test, but backed out the changes to idris entirely as it seems very screwy and there's a [binary available](http://www.idris-lang.org/download/), so maybe it would be better handled by the cask folks.

**Comment by mikemcquaid** [comment]
Works for me, thanks.

**Comment by mikemcquaid** [comment]
`darcs` still failing everywhere.

**Comment by geoff-codes** [comment]
Yep. Looks like it has to be done case by case. I've `rebase -p`'d that change out, added it individually for cgrep and cless. Third time's a charm...

**Comment by mikemcquaid** [comment]
Thanks @geoff-codes!

**Pull request closed without merging**
