### PR TITLE
awscli 1.7.29

### PR DESCRIPTION
**Pull request by nijikon**

### CODE REVIEW

**Comment by DomT4** [comment]
Test is dying on all three platforms:

```
==> brew test --verbose awscli						 FAILED
Testing awscli
==> /usr/local/Cellar/awscli/1.7.29/bin/aws --version
Traceback (most recent call last):
  File "/usr/local/Cellar/awscli/1.7.29/libexec/bin/aws", line 27, in <module>
    sys.exit(main())
  File "/usr/local/Cellar/awscli/1.7.29/libexec/bin/aws", line 23, in main
    return awscli.clidriver.main()
  File "/usr/local/Cellar/awscli/1.7.29/libexec/lib/python2.7/site-packages/awscli/clidriver.py", line 47, in main
    driver = create_clidriver()
  File "/usr/local/Cellar/awscli/1.7.29/libexec/lib/python2.7/site-packages/awscli/clidriver.py", line 56, in create_clidriver
    event_hooks=emitter)
  File "/usr/local/Cellar/awscli/1.7.29/libexec/lib/python2.7/site-packages/awscli/plugin.py", line 44, in load_plugins
    modules = _import_plugins(plugin_mapping)
  File "/usr/local/Cellar/awscli/1.7.29/libexec/lib/python2.7/site-packages/awscli/plugin.py", line 61, in _import_plugins
    module = __import__(path, fromlist=[module])
  File "/usr/local/Cellar/awscli/1.7.29/libexec/lib/python2.7/site-packages/awscli/handlers.py", line 48, in <module>
    from awscli.customizations.s3endpoint import register_s3_endpoint
  File "/usr/local/Cellar/awscli/1.7.29/libexec/lib/python2.7/site-packages/awscli/customizations/s3endpoint.py", line 29, in <module>
    from botocore.utils import fix_s3_host
ImportError: cannot import name fix_s3_host
Error: awscli: failed
```

**Comment by bfontaine** [comment]
It seems like the `botocore` resource needs to be updated as well. See [aws/aws-cli#1339](https://github.com/aws/aws-cli/issues/1339).

**Comment by nijikon** [comment]
@bfontaine thanks for pointing that out. Fixed. Waiting for the build.

**Comment by bfontaine** [comment]
@BrewTestBot test this please

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
