### PR TITLE
Bug fix for `to_rack`

### PR DESCRIPTION
**Pull request by xu-cheng**
cc @mikemcquaid  @vladshablinsky

### CODE REVIEW

**Comment by vladshablinsky** [comment]
I tested this and decided that it's okay. We just need to use fully-qualified formula for taps and everything else works fine. Am I wrong?

**Comment by xu-cheng** [comment]
I think the logic here is a little messy and overcomplicated. So I re-implement it, please check again.

**Comment by vladshablinsky** [comment]
Works fine. :+1:

**Comment by mikemcquaid** [comment]
:+1:

**Pull request closed without merging**
