### PR TITLE
libgroove 4.3.0

### PR DESCRIPTION
**Pull request by johnmuhl**

### CODE REVIEW

**Comment by bfontaine** [comment]
Thank you @johnmuhl, merged in b8a5ea1 :+1: 

For the record, the preferred checksum is now `sha256`.

**Comment by mikemcquaid** [comment]
@bfontaine If possible pull using `brew pull` and let it autoclose the PR (it might take ~5m). Thanks!

**Comment by bfontaine** [comment]
@mikemcquaid Ok, I use `brew pull` but I thought the autoclose was broken.

**Comment by xu-cheng** [comment]
Maybe add these informations in https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Maintainer-Guidelines.md

**Comment by mikemcquaid** [comment]
@xu-cheng @bfontaine Added in https://github.com/Homebrew/homebrew/pull/40127.

**Pull request closed without merging**
