### PR TITLE
Gnutls 3.3.16

### PR DESCRIPTION
**Pull request by nijikon**

### CODE REVIEW

**Comment by nijikon** [comment]
Fixes #38298

**Comment by nijikon** [comment]
Fixes #40802

**Comment by nijikon** [comment]
@mikemcquaid is there a 1 hour limit per running job? Seems like the job was killed.

**Comment by DomT4** [comment]
Yup. There's an absolute cap at 60 minutes to prevent anything stalling and staying stalled in the queue for hours at the expense of other PRs.

We manually bump it for special PRs. Is none of the stuff here building against the new `gnutls` without revisions/version bumps?

**Comment by nijikon** [comment]
Clear on the cap. I don't get the question about the revisions/version bumps. When I bump a package to a newer version should I bump the revisions from ```brew uses```?

**Comment by DomT4** [comment]
> When I bump a package to a newer version should I bump the revisions from brew uses?

Not necessarily. They only need bumped if either `brew install -fs` or `brew test --verbose xyz` fails on them. If it builds, and it tests, there's a solid chance it doesn't need a revision.

**Comment by nijikon** [comment]
I'm sorry, I'm a bit confused. Can you clarify what should be the path of updating this. How should I handle it, I want to know for future reference.

**Comment by DomT4** [comment]
Which bit are you confused with? :)

**Comment by nijikon** [comment]
I want to upgrade the gnutls. I updated the version and now for what other packages do I need to bump revision? All from brew uses or else?

**Comment by DomT4** [comment]
It's just a minor, so you should be able to drop everything aside the `gnutls` bump itself. We only need to bump the revisions when the dependants break in some way, whether it's an API compatibility issue, or something more obvious like changing the `dylib` version number.

If you want to leave the two other version bumps in here (Rather than the revision changes) I'm fine with that though.

**Comment by nijikon** [comment]
Ok, I think I understand now.

- removed revision change for bdw-gc and libatomic_ops
- guile revision change stays cause it depends on libunistring which version had changed

If this can be merged, please bring the cap up and run the test, thanks!

**Comment by DomT4** [comment]
Let's move `guile` to another PR - It has a special function about 3/4 of the way into the install, and sometimes that function takes 2 minutes, sometimes ~4 hours - It's a lottery.

**Comment by DomT4** [comment]
Oh, welp. Guess that could be tricky with the version bump for `libunistring` here as well. Alright, let's see how it goes.

**Comment by nijikon** [comment]
Ok, if it will go south, then we can try to separate it.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/35ab2495d07002b8ee4562bab70ea3803ab474f6, and a bunch of other commits :wink:. Thanks again @nijikon! Guile decided to play nice this time :smile_cat:.

**Comment by mietek** [comment]
One of the changes in this PR (https://github.com/Homebrew/homebrew/commit/f208b9b7436cec6dec7b2a1232479a9842591ef3#commitcomment-12302034) mistakenly reverts https://github.com/sblessing/homebrew/commit/96b28e8f95130876fbe3fcbb09065633033bab2d. See also https://github.com/Homebrew/homebrew/pull/39209.

**Comment by DomT4** [comment]
https://github.com/Homebrew/homebrew/commit/288a57e46567b1f70029065be11cf18e82a1bb73

**Comment by mietek** [comment]
Thanks!

**Comment by DomT4** [comment]
Hmm. Is it possible the belief `ghc` isn't runtime here is wrong? It usually isn't, but the [test](http://bot.brew.sh/job/Homebrew/14100/version=yosemite/testReport/junit/brew-test-bot/yosemite/test_agda/) blew up on the change. Trying a full rebuild to see if it reproduces.

```
==> /usr/local/Cellar/agda/2.4.2.3_1/bin/agda -c --no-main --safe /private/tmp/agda20150722-60325-spon8a/simple-test.agda
Checking simple-test (/private/tmp/agda20150722-60325-spon8a/simple-test.agda).
Finished simple-test.
Compiling Agda.Primitive in /usr/local/Cellar/agda/2.4.2.3_1/share/x86_64-osx-ghc-7.10.1/Agda-2.4.2.3/lib/prim/Agda/Primitive.agdai to /private/tmp/agda20150722-60325-spon8a/MAlonzo/Code/Agda/Primitive.hs
Compiling simple-test in /private/tmp/agda20150722-60325-spon8a/simple-test.agdai to /private/tmp/agda20150722-60325-spon8a/MAlonzo/Code/QsimpleZ45Ztest.hs
Calling: ghc -O -Werror -i/private/tmp/agda20150722-60325-spon8a /private/tmp/agda20150722-60325-spon8a/MAlonzo/Code/QsimpleZ45Ztest.hs --make -fwarn-incomplete-patterns -fno-warn-overlapping-patterns
ghc: createProcess: runInteractiveProcess: exec: does not exist (No
such file or directory)
Error: agda: failed
Failed executing: /usr/local/Cellar/agda/2.4.2.3_1/bin/agda -c --no-main --safe /private/tmp/agda20150722-60325-spon8a/simple-test.agda
```

**Comment by mietek** [comment]
Works for me without GHC. It looks like your test is using the MAlonzo backend?

**Comment by DomT4** [comment]
Honestly, no idea. I've been trying to avoid getting intimate with GHC stuff. I'm running it through our CI again to see if it reproduces with a clean build.

**Comment by nijikon** [comment]
I was able to build agda with current master without no issues. https://gist.github.com/nijikon/2d3ebe26d51ab44a780c

**Comment by nijikon** [comment]
```cabal-install``` has ```depends_on "ghc"``` so we can change it to ```depends_on "ghc"``` in ```agda``` as well.

**Comment by mietek** [comment]
@nijkon: Your gist shows [building Agda from source](https://gist.github.com/nijikon/2d3ebe26d51ab44a780c#file-agda-build-L222-223):
> ```
> Warning: Formula file is modified!
> Building from source because Library/Formula/agda.rb has local changes
> ```

Agda already has a perfectly good bottle, and does not require GHC to be present at runtime:
```
$ which ghc
$ brew install agda
==> Downloading https://homebrew.bintray.com/bottles/agda-2.4.2.3_2.yosemite.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/agda-2.4.2.3_2.yosemite.bottle.tar.gz
==> Pouring agda-2.4.2.3_2.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/agda/2.4.2.3_2: 942 files, 305M
$ agda -I
                 _ 
   ____         | |
  / __ \        | |
 | |__| |___  __| | ___
 |  __  / _ \/ _  |/ __\     Agda Interactive
 | |  |/ /_\ \/_| / /_| \
 |_|  |\___  /____\_____/    Type :? for help.
        __/ /
        \__/

The interactive mode is no longer supported. Don't complain if it doesn't work.
Main>
```

> `cabal-install` has `depends_on "ghc"` so we can change it to `depends_on "ghc"` in `agda` as well.
In contrast with Agda, most uses of `cabal-install` do require GHC to be present at runtime.

**Comment by nijikon** [comment]
@mietek Yes, I build everything from source cause of the development flags, always everything compiles in order to verify if nothing is broken. I think that only using it for build makes sense if it is not needed afterwards. Agda does not compile without ```depends_on "ghc" => :build```.

**Comment by DomT4** [comment]
The outcome of this conversation is that both the `:build` dependencies are fine to remain as such?

I'm fairly sure the test failure we saw the other night that threw confusion around was some problem with the way we test outside of formula installations, as it didn't reoccur during a fresh rebuild. Unless any users see the problem when they run `brew test --verbose agda` I'm just going to ignore it for now.

**Comment by mietek** [comment]
:+1:

**Pull request closed without merging**
