### PR TITLE
swiftgen 0.7.3

### PR DESCRIPTION
**Pull request by AliSoftware**

### CODE REVIEW

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/01980616a442369b16ec4b2b30f89f701732822b. Thank you once again @AliSoftware! :smiley_cat:

**Comment by AliSoftware** [comment]
That was fast! :tada:

**Comment by DomT4** [comment]
If it takes an hour or longer you're entitled to a refund :stuck_out_tongue_winking_eye:.

**Comment by AliSoftware** [comment]
I take :beers: and :chocolate_bar: :wink:

**Pull request closed without merging**
