### PR TITLE
hhvm 3.9.0 (new formula)

### PR DESCRIPTION
**Pull request by jwatzman**
Add a formula for HHVM, Facebook's JIT compiler/runtime for the PHP and
Hack languages.

### CODE REVIEW

**Comment by jwatzman** [comment]
In the interest of full disclosure,
- I'm one of the upstream maintainers of HHVM. The formula cookbook suggests not submitting software for which you are a maintainer, unless it's quite popular, and I think HHVM more than qualifies for this.
- We don't build with any compiler Apple ships. It was pointed out this was likely a problem for getting the formula into core in discussion on #42957. Figured I'd give it a shot anyways, can always move this into our own tap if I have to, but I'd much prefer it be in core if you'll take it.

Thanks!

**Comment by mikemcquaid** [comment]
What's the expected build time here?

**Comment by jwatzman** [comment]
Long. It takes like 10-20m-ish on my 12-core Mac Pro, and the build parallelizes pretty well... so like 2-3 hours or so on a single core?

<3 C++ :\

**Comment by jwatzman** [comment]
Is there some possibility this would be merged, or should I get a tap set up under the official HHVM project? I'd love to have it merged into core to make it easier for our users to set up, but if that's not going to happen, I'd also love to announce an official tap :)

**Comment by denji** [comment]
@jwatzman Not a good idea to stir here hhvm (main repository), there still is and extensions as php.
You need to put in a separate repository-tap. Am I right? PHP exactly [`Homebrew/homebrew-php`](https://github.com/Homebrew/homebrew-php)

**Comment by jwatzman** [comment]
@denji This isn't a PHP extension, and so doesn't belong in `Homebrew/homebrew-php`. It belongs either here, or in a tap I'm going to set up under the HHVM project.

**Comment by mikemcquaid** [comment]
I think we'll need to pass on this as it's struggling to build on our machines. Sorry!

**Comment by jwatzman** [comment]
Thanks for letting me know, I'll set up an HHVM-official tap then :)

**Pull request closed without merging**
