### PR TITLE
apache-spark 1.4.0

### PR DESCRIPTION
**Pull request by ogrisel**
Amended #40596 to use an https URL.

### CODE REVIEW

**Comment by ogrisel** [comment]
Hum, I just tested it locally and the closer.cgi URL of apache.org are not interpreted by the homebrew. Is there a good way to deal with the apache mirrors in homebrew formulae?

**Comment by ogrisel** [comment]
Here is the error message I get:

```
$ brew fetch apache-spark
==> Downloading https://www.apache.org/dyn/closer.cgi/spark/spark-1.4.0/spark-1.4.0-bin-hadoop2.6.tgz
Error: Failed to download resource "apache-spark"
Download failed: Couldn't determine mirror, try again later.
```

**Comment by ogrisel** [comment]
I have forced-pushed a new version of the Formula that uses `https://archive.apache.org/dist/` instead of `https://www.apache.org/dyn/closer.cgi/` and it seems to work.

There might be an issue with the handling of the apache mirror. But this problem does not happen for other apache projects such as apache-drill for instance.

**Comment by karlhigley** [comment]
@ogrisel: The [Hadoop recipe](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/hadoop.rb) uses a slightly different URL format, which seems to make the mirrors work.  Updated in #40596.

**Comment by DomT4** [comment]
Let's not add a third open PR on top of the other two for this formula, as much as we appreciate the enthusiasm :wink:.

**Comment by ogrisel** [comment]
But mine works ;)

**Comment by ogrisel** [comment]
I don't understand the report by jenkins. All tests pass. The failure on mavericks seems to be caused by a git checkout issue:

http://bot.brew.sh/job/Homebrew%20Pull%20Requests/27717/version=mavericks/console

**Comment by DomT4** [comment]
^ Jenkins crashed, essentially.

**Pull request closed without merging**
