### PR TITLE
docker-machine 0.6.0

### PR DESCRIPTION
**Pull request by deekthesqueak**
Updates the docker-machine package to 0.6.0. Also updates the test to check against the version

### CODE REVIEW

**Comment by deekthesqueak** [comment]
Duplicates https://github.com/Homebrew/homebrew/pull/48847 but has better test. docker-machine --version should give a better output to test against than docker-machine ls.

**Comment by voxxit** [comment]
Agreed on the `--version` flag change. :+1:

**Comment by hacfi** [comment]
:+1:

**Comment by outcoldman** [comment]
@deekthesqueak @voxxit how is the `--version` better than `ls`? Current "test" only verifies this line https://github.com/docker/machine/blob/master/commands/version.go#L18, but ls also parses config and verifies that after upgrade your config still valid. Considering how many times docker-machine broke the config - seems like a good test for me.

If you really want to have `version` test, why not add it as one more test?

**Comment by ianwalter** [comment]
I don't see any harm in having both tests. I'm really looking forward to this being merged!

**Comment by DomT4** [comment]
I'm indifferent on the test change. If people want to follow-up with a more thorough test, be my guest. Merging here though because it went through CI more recently than the other build which means I don't have to wait another few hours for the other PR to get back in the queue.

Merged in https://github.com/Homebrew/homebrew/commit/a7bd847534083ce5eef2a8f35eef1a5822b8c204. Thank you for your contribution to Homebrew @deekthesqueak; we appreciate it! :smiley_cat:

**Pull request closed without merging**
