### PR TITLE
boost: apply backported fix for ambiguous call to swap

### PR DESCRIPTION
**Pull request by programmarchy**
This fixes a compile error in boost variant
See 10882 https://svn.boost.org/trac/boost/ticket/10882

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Would like to see upstream accept and merge this patch before we apply it.

**Comment by tdsmith** [comment]
My reading was that it's been accepted: https://svn.boost.org/trac/boost/ticket/10882#comment:3

**Comment by vszakats** [comment]
I suggest to switch to https for the patch `url`.

**Comment by vszakats** [comment]
And for the `homepage` as well, even though it is currently redirected to http.

**Comment by jacknagel** [comment]
I think at this point we will move directly to boost 1.58, so closing.

**Pull request closed without merging**
