### PR TITLE
update resourced setuptools to 18.7.1

### PR DESCRIPTION
**Pull request by felixonmars**

### CODE REVIEW

**Comment by DomT4** [comment]
Want @tdsmith to sign off on this if possible, and we'll likely want this PR to be broken into individual PRs because the `pypy` builds alone take 90 minutes *each*.

**Comment by tdsmith** [comment]
No objections but is there a reason it's important to update to this release?

**Comment by felixonmars** [comment]
It's not important, I'm just bumping because it's outdated (too much).

**Comment by DomT4** [comment]
Will let Tim decide on necessity here.

**Comment by DomT4** [comment]
Passing on this for now. We'll handle non-urgent updates gradually rather than in bulk. Thank you for the submission though @felixonmars :heart:.

**Comment by felixonmars** [comment]
Would you be interested if I split the commit? :P

**Comment by DomT4** [comment]
Not unless Tim is particularly interested, or there are some kind of vulnerabilities in the older versions. Several of these formulae are huge compiles and would chew through CI time with glee. It's Tim's call.

**Comment by xu-cheng** [comment]
@DomT4 I don't think we should pass this because it's not urgent. Some of them are outdated to much.

@felixonmars It would be nice to split the commit. e.g. one PR for one formula.

**Comment by DomT4** [comment]
@xu-cheng I'm not sure on the upsides of setting aside ~5 hours of CI time for a bump that doesn't gain anything end users actually *need*, especially since we won't be adding formulae revisions and most users won't see that bump until the next update anyway.

**Comment by xu-cheng** [comment]
@DomT4 but it will benefit users who install these formulae later :wink: Things like these rarely got updated. It's nice to have someone in community to improve them, no matter the gain.

>  ~5 hours of CI time 

We are not in backlog now. So I won't worry about that. Especially, if the commits are split by several PRs.

**Pull request closed without merging**
