### PR TITLE
synfigstudio: boneyard

### PR DESCRIPTION
**Pull request by zmwangx**
Main reasons for boneyard:

* As this formula now stands, it fails to build (with a mysterious error) against FFmpeg 3.0 (#49178), blocking the FFmpeg upgrade;

* This is a GUI-only tool (look at its awkward test), so it doesn't quite belong to core to begin with; and due to the build issue above, work is needed if it is to be revived in homebrew/gui;

* There's not enough interest, seeing that we are two releases or half a year behind, and no user even proposed a version bump;

* Upstream's preferred method of installation is the app bundle (which seems to be a much more complete solution, given the app bundle's size), distributed in binary disk images.

More discussions in #49178.

Actually, to repeat what I said in https://github.com/Homebrew/homebrew/pull/49178#issuecomment-186669070:

> The deeper I look into this project, the more I find its distribution a total mess. There are at least three distribution channels:

> 1. Main download (synfig-studio installers only) is on http://www.fosshub.com/Synfig.html, a site that doesn't even provide static download links (from the site's [FAQ](http://www.fosshub.com/faq.html): We have been a target for several websites that decided to steal bandwidth from us by posting a link directly to our setup files. blah blah blah. Posting a direct link is a waste of bandwidth for us and it's also useless because of this: blah blah blah.) I ended up downloading just to see what's in it, and got a HUGE GUI app, 2 GB in size. Not sure how the 4.8M source tarball and 4.6M bottle worked :open_mouth: 

> 2. Then download is "mirrored" on SourceForge: https://sourceforge.net/projects/synfig/files/releases/1.0.2/source/. Which isn't exactly a mirror because there are more download options (e.g., source tarballs for each module) there than the main download location. This channel may be used for HBC, because SF is at least nice enough to provide static links.

> 3. GitHub: https://github.com/synfig/synfig. Development (of all three formulae `etl`, `synfig`, `synfigstudio`) happens there, tagging happens there, no download option parity though.

> This abundance of vastly different download options (and non-options) coupled with the GUI nature of `synfigstudio` leaves me bewildered as a Homebrew user/contributor and non-synfigstudio user. It would be cool if a synfig user could come along and take up the task of maintaining it, but judging from the fact that we're two releases and half a year behind, there doesn't seem to be enough interest. One could attempt to upgrade `synfig` and `synfigstudio` to 1.0.2 and wish they just work out fine (at this point even the build failure is mysterious), but what's most likely is more friction and back-and-forth, all for a GUI-only tool that doesn't quite belong to Homebrew core in the first place. And I don't think FFmpeg 3.0, which must be anticipated by quite some users (given FFmpeg's known install base), should be further delayed without a real issue.

> Therefore my conclusion is, although it doesn't seem to completely justify boneyard treatment, I'm tempted to do it with `synfigstudio`. Interested parties may attempt to revive in homebrew-gui or homebrew-cask, and I'm fine with either, as long as it's not my problem any more. I'll submit a boneyard PR.

### CODE REVIEW

**Comment by zmwangx** [comment]
CC @DomT4.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/e3b88367251e9d055560cae6db7aeef2b435b818. Thanks again @zmwangx! The `ffmpeg` PR should pretty much come as close to passing as it's going to now if you rebase and eject `synfigstudio` from the changes there.

**Comment by zmwangx** [comment]
> The ffmpeg PR should pretty much come as close to passing as it's going to now if you rebase and eject synfigstudio from the changes there.

Yep, rebased. Feeling kinda bad about the harsh treatment of synfigstudio though. Hopefully a synfigstudio fan will get upset enough to revive it somehow.

**Comment by DomT4** [comment]
> Feeling kinda bad about the harsh treatment of synfigstudio though.

It's not that harsh, to be fair. We've temporarily removed formulae to the boneyard for less. Wouldn't worry about it. If there are still people out there using it and needing it hopefully they'll contribute and help get it back into Homebrew (GUI).

**Pull request closed without merging**
