### PR TITLE
global: fix ctags option

### PR DESCRIPTION
**Pull request by dunn**
see: https://github.com/Homebrew/homebrew/pull/46916#issuecomment-164946280

All credit to @UniqMartin

### CODE REVIEW

**Comment by UniqMartin** [comment]
Have you checked if other formulae depend on this one (and on that particular spelling of the option)?

**Comment by dunn** [comment]
:see_no_evil:

**Comment by dunn** [comment]
No, not in core or any of the Homebrew taps.

**Comment by UniqMartin** [comment]
> No, not in core or any of the Homebrew taps.

Thanks for checking, I hadn't verified this myself. As far as I can tell, this is good to go. :+1:

**Pull request closed without merging**
