### PR TITLE
audit: uniformize the desc problems

### PR DESCRIPTION
**Pull request by bfontaine**
I’m making a PR just in case someone disagrees with the wording.

### CODE REVIEW

**Comment by DomT4** [comment]
FWM.

**Comment by bfontaine** [comment]
@DomT4 I guess you meant “WFM” :wink:

**Comment by DomT4** [comment]
"Fine with me" :wink:

**Comment by bfontaine** [comment]
Oh. The Urban Dictionary was giving me a different definition so I assumed it was a typo. :smile:

**Comment by DomT4** [comment]
Oh god, I dread to think what it means to the Urban Dictionary. *Goes to check*

**Comment by DomT4** [comment]
> fwm
Abbreviation for "Fine with me".
It's fwm if you want to drive home.
by bharatman February 08, 2008

This was the definition I meant. The rest were wildly inaccurate in this context :laughing:.

**Pull request closed without merging**
