### PR TITLE
zssh: modernize + basic test added

### PR DESCRIPTION
**Pull request by bfontaine**

### CODE REVIEW

**Comment by bfontaine** [comment]
The test is failing with the bot but works for me:
```
$ brew test --verbose zssh
Testing zssh
==> /usr/local/Cellar/zssh/1.5c/bin/zssh --version
zssh version 1.5c , built Jeu 1 jan 2015 01:22:06 CET
Copyright (C) 2001 Matthieu Lucotte <gounter@users.sourceforge.net>
zssh comes with ABSOLUTELY NO WARRANTY. Use at your own risk.
This is free software, and you are welcome to redistribute it
under certain conditions.
See the GNU General Public License for more details.
$ brew doctor
Your system is ready to brew.
```

**Comment by mikemcquaid** [comment]
If it's failing on the bot we'll need to tweak or remove the test :(

**Comment by bfontaine** [comment]
I removed the test.

**Comment by mikemcquaid** [comment]
Probably want to pass on modernising without a test.

**Comment by bfontaine** [comment]
@mikemcquaid I’m working on a test but the bot [fails](http://bot.brew.sh/job/Homebrew%20Pull%20Requests/19091/version=yosemite/console) even before trying to run it:

```
[…]
 > git checkout -f a094359abbbdba0cde8be3392b6d33f39b8fe9d8
FATAL: Could not checkout null with start point a094359abbbdba0cde8be3392b6d33f39b8fe9d8
hudson.plugins.git.GitException: Could not checkout null with start point a094359abbbdba0cde8be3392b6d33f39b8fe9d8
[…]
```

**Comment by mikemcquaid** [comment]
@bfontaine That's a random Jenkins failure. Restarted the job.

**Comment by bfontaine** [comment]
Thanks @mikemcquaid. Still failing thought. From what I tried I don’t think I’ll be able to write a working test for this one.

**Pull request closed without merging**
