### PR TITLE
leiningen 2.6.0

### PR DESCRIPTION
**Pull request by brunchboy**
Update Leiningen to release 2.6.0

### CODE REVIEW

**Comment by DomT4** [comment]
Already filed in #48861. Just waiting for that to go through CI. Thanks for the submission though! :heart:

**Comment by brunchboy** [comment]
Whoops! Is there a way I can check for that next time, to search for pending changes to formulae?

**Comment by DomT4** [comment]
Probably easiest to chuck the formula name in https://github.com/Homebrew/homebrew/pulls with the filter `is:pr is:open` (which should be the default filter on that page).

**Comment by brunchboy** [comment]
Perfect! `is:pr is:open leiningen` and it shows up. :+1:  Thanks, I will try to avoid making extra work for you in the future. Should I submit a PR `CONTRIBUTING.md` to add this step in the future? That would help me (and others) remember.

**Comment by dunn** [comment]
Sure!

**Pull request closed without merging**
