### PR TITLE
redis: upstream replaced source distfile

### PR DESCRIPTION
**Pull request by nijikon**

### CODE REVIEW

**Comment by DomT4** [comment]
Can you poke someone upstream to get clarification this was a legit change? Thanks!

**Comment by nijikon** [comment]
Pinged Salvatore on twitter :)

**Comment by nijikon** [comment]
https://twitter.com/antirez/status/692983535045599232 @antirez confirmed, we can merge.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/305bcf891f184d5635d143debb8d3e52f6efaa86. Thanks for double checking this, Appreciate that!

**Pull request closed without merging**
