### PR TITLE
test_formula_installer: fix log file leak

### PR DESCRIPTION
**Pull request by xu-cheng**

### CODE REVIEW

**Comment by xu-cheng** [comment]
Currently, file leak test only run [when `LOG_FS_LEAKS ` is set](https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/test/testing_env.rb#L81). Should we make it run unconditionally?

**Comment by mikemcquaid** [comment]
@xu-cheng Seems like a good idea.

**Comment by xu-cheng** [comment]
Updated to always check file leak.

**Comment by mikemcquaid** [comment]
:+1:

**Pull request closed without merging**
