### PR TITLE
use secure cpan urls and minor related updates

### PR DESCRIPTION
**Pull request by vszakats**
* use secure cpan URLs as primary `url`s
* move insecure cpan URLs as `mirror`s
* cleanup cpan `http://www.cpan.org/` URLs to `http://search.cpan.org/CPAN/` uniformly

### CODE REVIEW

**Comment by DomT4** [comment]
FWIW I'm entirely happy to use `metacpan` as the primary resource URL given it is secure and the other isn't.

**Comment by DomT4** [comment]
But leave `innotop` & `mytop` out of the PR please; will fix those in the MySQL PR I have open which I really don't want to do significant rebasing of :laughing:.

**Comment by vszakats** [comment]
Got it! I actually wanted to inquire you whether to keep those insecure cpan URLs. I'm also happy to drop them. I may replace `innotop` and `mytop` with some http removal, if that's okay.

**Comment by DomT4** [comment]
> I actually wanted to inquire you whether to keep those insecure cpan URLs.

I don't mind them as fallback mirrors, but I'm happy with people using the secure alternative instead as the primary URL.

**Comment by vszakats** [comment]
I've put back the insecure one as mirrors, but I'd argue this isn't very good from a security POV. The secure URL can be easily forced to fall back to the insecure mirror and defeat the point of https altogether.

**Comment by vszakats** [comment]
Also replaced `http://www.cpan.org/` with `http://search.cpan.org/CPAN/`.

**Comment by DomT4** [comment]
> but I'd argue this isn't very good from a security POV

I'm aware. At some point the no insecure redirect environmental variable will block the downgrade.

**Comment by DomT4** [comment]
Pulled so many bottles here :laughing:. Was going to kick it off the CI and just merge it, but most of the formulae here needed new bottles either for SHA256 or El Cap, so I let it run.

Merged in a whole bunch of commits. Thank you @vszakats :smiley:

**Comment by vszakats** [comment]
Thank you @DomT4!

**Pull request closed without merging**
