### PR TITLE
mat 0.5.3

### PR DESCRIPTION
**Pull request by DomT4**
Version bump.

### CODE REVIEW

**Comment by DomT4** [comment]
@tdsmith One of the tests is failing, and I'm not quite sure why, or what to report upstream. Any chance you could look it over? Happy to report upstream afterwards if necessary, but I'm trying to avoid going upstream with "err it broke and I don't know why apart from this output" :smile_cat: 

```
~> mat -l
Traceback (most recent call last):
  File "/usr/local/Cellar/mat/0.5.3/libexec/bin/mat", line 142, in <module>
    main()
  File "/usr/local/Cellar/mat/0.5.3/libexec/bin/mat", line 116, in main
    list_supported()
  File "/usr/local/Cellar/mat/0.5.3/libexec/bin/mat", line 96, in list_supported
    for item in mat.list_supported_formats():
  File "/usr/local/Cellar/mat/0.5.3/libexec/lib/python2.7/site-packages/libmat/mat.py", line 67, in list_supported_formats
    with open(path, 'r') as xmlfile:
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

**Comment by tdsmith** [comment]
`path` is none and should not be ¯\\\_(ツ)\_/¯ Seems like it's maybe failing to find a file.

**Comment by DomT4** [comment]
Funky. Thanks for taking a peek. I'll try compiling it outside of Homebrew in the morning and see if it happens again. If it does, I guess it's time to wander upstream.

**Comment by jacknagel** [comment]
@BrewTestBot test this please

**Comment by DomT4** [comment]
Sorry, this slipped my mind. There's actually a new issue when ran locally now. Could be a 10.10.4 problem though:

```
Fatal Python error: PyThreadState_Get: no current thread
[1]    41882 abort      mat -l
```

**Comment by DomT4** [comment]
Aye. Using Homebrew's Python we get:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/mat/0.5.3/libexec/bin/mat", line 142, in <module>
    main()
  File "/usr/local/Cellar/mat/0.5.3/libexec/bin/mat", line 116, in main
    list_supported()
  File "/usr/local/Cellar/mat/0.5.3/libexec/bin/mat", line 96, in list_supported
    for item in mat.list_supported_formats():
  File "/usr/local/Cellar/mat/0.5.3/libexec/lib/python2.7/site-packages/libmat/mat.py", line 67, in list_supported_formats
    with open(path, 'r') as xmlfile:
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

back. Reporting upstream now.

**Comment by DomT4** [comment]
https://github.com/Homebrew/homebrew/commit/45c6a6c7aba6fb0951b16d6a76dc8306763ea0f1

**Pull request closed without merging**
