### PR TITLE
pdsh: boneyard

### PR DESCRIPTION
**Pull request by DomT4**
Not sure how much longer it's worth supporting this for on newer OS X versions. It hard-exits on run for me on three of the executables with:

```
==> /usr/local/Cellar/pdsh/2.31/bin/pdsh -V
pdsh@Dominyk: module path "/usr/local/Cellar/pdsh/2.31/lib/pdsh" insecure.
pdsh@Dominyk: "/": World writable and sticky bit is not set
pdsh@Dominyk: Couldn't load any pdsh modules
```

AFAIK on OS X the entirety of `/` is not intended to be set with a sticky bit, only certain aspects of it.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
If there's no sign of a future release I'd be tempted to boneyard it.

**Comment by DomT4** [comment]
Hasn't been a commit upstream since the last release towards the end of 2013.

**Comment by mikemcquaid** [comment]
:+1: to boneyard from me.

**Comment by DomT4** [comment]
:+1: - Will flip the PR to remove it later tonight.

**Comment by DomT4** [comment]
https://github.com/Homebrew/homebrew-boneyard/pull/56

**Comment by ebpitts** [comment]
Aww, sorry to see this boneyarded. The Eventbrite ops team is a heavy user. It works fine for us.

```
$ /usr/local/Cellar/pdsh/2.31/bin/pdsh -V
pdsh-2.31 (+readline)
rcmd modules: ssh,exec (default: ssh)
misc modules: dshgroup
```

@DomT4 sounds like the problem is that you've made your root filesystem world-writable; normally permissions for `/` are `drwxr-xr-x`. Pdsh [is paranoid](https://code.google.com/p/pdsh/issues/detail?id=16) abotu the permissions of the directory (and it's parents) that it loads modules from.

**Comment by DomT4** [comment]
The lack of update is more of a contributing factor to the boneyarding than the behaviour of the tool itself. The latter was just interesting.

My permissions for `/` are `drwxr-xr-x` and `root:wheel` or `root:admin`- Not everything in `/` is tagged with a sticky bit but that's not overly uncommon for OS X.

**Comment by DomT4** [comment]
Sorry, I just realised I misread your comment. Yeah, permissions on my `/` had wandered off at some point and Disk Utility didn't warn me about it. Warning is gone.

If you can get some kind of upstream communication to say the project is alive I'm not opposed to flipping the removal here.

**Comment by mistydemeo** [comment]
If pdsh is working, I'd be glad to have it regardless of whether it's actively developed.

**Comment by DomT4** [comment]
Alright. Once the bots are back online and actually dealing with the queue I'll retrieve it from the yard and tidy it up, unless anyone objects before then.

**Comment by hSATAC** [comment]
Too sad to see this... I am too a heavy user of pdsh and it's working fine on my macbook.

**Comment by DomT4** [comment]
It'll be restored at some point today. We're having a lot of CI issues at the moment and I've been trying to hold off on dumping something else on the queue until the load is less. Haven't forgotten this.

**Comment by DomT4** [comment]
#41345

**Pull request closed without merging**
