### PR TITLE
bigdata 1.5.1

### PR DESCRIPTION
**Pull request by dunn**

### CODE REVIEW

**Comment by jacknagel** [comment]
Alias symlinks don't need the ".rb" extension.

**Comment by tdsmith** [comment]
Audit says:

> bigdata:
 * Non-executables were installed to "/usr/local/Cellar/bigdata/1.5.1/bin"
The offending files are:
  /usr/local/Cellar/bigdata/1.5.1/bin/config  
  /usr/local/Cellar/bigdata/1.5.1/bin/config.sh

Anything to do about these?

**Comment by dunn** [comment]
I just switched over to the recommended `.jar` bundle, is that alright?

**Comment by mikemcquaid** [comment]
Thanks again @dunn!

**Pull request closed without merging**
