### PR TITLE
rust 1.3.0

### PR DESCRIPTION
**Pull request by dtrebbien**

### CODE REVIEW

**Comment by dtrebbien** [comment]
Both Travis CI builds failed with "The job exceeded the maximum time limit for jobs, and has been terminated."

**Comment by stouset** [comment]
Rust takes a long time to compile. How would one circumvent that?

**Comment by DomT4** [comment]
There will be a Jenkins CI build done soonish which doesn't have such a limited timeout.

**Comment by mikemcquaid** [comment]
Also if there's any way to speed up the build that would be handy too.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/aea0f1dd93220b6a28db8e79ccedf05d451c1ba8. Thank you for your contribution to Homebrew @dtrebbien; we appreciate it! :smiley_cat:

**Comment by dtrebbien** [comment]
Just to follow up on reducing build time, I asked on \#rust-internals IRC and was told that build time is a known issue, but there is currently no master plan for fixing it.

One suggestion was to use an external LLVM rather than having rust build its own LLVM.  Testing this approach out this morning, I see that the build time is actually slightly longer on my MacBook Pro when using Homebrew's LLVM (i.e. external LLVM):
32.0 minutes with in-tree LLVM (https://github.com/rust-lang/llvm) versus 32.3, 33.7 minutes using Homebrew's LLVM 3.6.2.

As noted at rust-lang/llvm#21, Rust's LLVM has some additional optimizations.

**Comment by dtrebbien** [comment]
PR #44138 adds a `--with-llvm` option

**Pull request closed without merging**
