### PR TITLE
Update example-formula.rb

### PR DESCRIPTION
**Pull request by mikicaivosevic**
Refactor if else

### CODE REVIEW

**Comment by bfontaine** [comment]
I personally find the original code more understandable.

**Comment by dunn** [comment]
I agree; the ternary operator isn't as readable, and in the example formula we should emphasize readability for new contributors.

**Comment by DomT4** [comment]
Agree with Baptiste & Alex here.

Although `args << build.with? "example2" ? "--with-example2" : "--with-example1"` is cleaner it isn't particularly nice for Ruby/Homebrew newcomers.

**Comment by dunn** [comment]
I think we're going to pass on this, but thank you for the pull request!

**Pull request closed without merging**
