### PR TITLE
Qt 5.6.0

### PR DESCRIPTION
**Pull request by luzpaz**

### CODE REVIEW

**Comment by UniqMartin** [comment]
Sadly, this version bump will be a bit more involved than the current changes in this PR:

- Patches for the 5.5 series that were merged upstream need to be removed.
- The `head` line needs to be updated to point to the 5.6 branch.
- Configure arguments should ideally be updated to reflect changes made to defaults in 5.6.
- The option for disabling the build of the `QtWebKit` module (gone in 5.6) needs to be removed.
  - Formulae that link against `QtWebKit` need to be rebuilt (e.g. `pyqt5`, maybe others).
- Due to an [upstream change](https://codereview.qt-project.org/#/c/140954/), formulae that require `pkg-config` files for finding Qt will fail to build.
  - Formulae known to be affected by this: `mkvtoolnix`, `poppler`, `suil`, `wireshark`. (All of them have optional Qt 5 support via `--with-qt5`.)

(This list might be incomplete and is based on preliminary testing with 5.6.0-rc1.) I was hoping to be able to address all of the above at some point, but feel free to do that yourself, as I'm severely short on time at the moment. Thanks!

**Comment by DomT4** [comment]
> Due to an upstream change, formulae that require pkg-config files for finding Qt will fail to build.
Formulae known to be affected by this: mkvtoolnix, poppler, suil, wireshark. (All of them have optional Qt 5 support via --with-qt5.)

Following up on the discussion we had on Slack I'm :+1: on reverting the commit that caused the removal of the `pkg-config` files for now if you are.

We need the `revision` line purged as well, as per norm on stable version updates.

**Comment by UniqMartin** [comment]
> Following up on the discussion we had on Slack I'm :+1: on reverting the commit that caused the removal of the `pkg-config` files for now if you are.

I guess that's a sensible temporary workaround that requires the least effort. Ideally though, we'd be able to switch over affected formulae to CMake-based builds (if available) or check with upstream if they are aware of the issue and what they prefer as a solution/workaround.

An undesirable effect of reverting the commit as a workaround could be that it creates the false impression that everything's fine on OS X, while there has actually been a breaking change in Qt 5.6.

**Comment by DomT4** [comment]
I think realistically if we want to get 5.6 in sooner than a couple+ months time we need to retain the `pkg-config` files in some form.

Reporting the breakage to respective upstreams, linking to that bug report in each impacted formula and temporarily keeping the `pkg-config` files with an explanation in the Qt5 formula makes sense to me, and should lessen the risk of upstreams presuming nothing significant changed.

**Comment by luzpaz** [comment]
hey fellas, please take over. These changes are out of my depth.

**Comment by jakepetroules** [comment]
Thanks for starting on this so quickly. Please let of know of any problems at [bugreports.qt.io](https://bugreports.qt.io)!

**Comment by luzpaz** [comment]
@UniqMartin 
[x] ``head`` was updated to 5.6 branch

Note: the patches don't reference bugreports in Qt but instead their codereview page. How does one know which patches were merged in to trunk ?

**Comment by UniqMartin** [comment]
> hey fellas, please take over. These changes are out of my depth.

Didn't mean to discourage you, but can totally understand if the change feels too complex for you. Just wanted to point out what I'm aware of before you start wondering why the build fails. Thanks for giving it a try nonetheless! :smiley_cat: I'll try to prepare something with the least-effort strategy discussed above. Please give me a day or two to do that.

> Note: the patches don't reference bugreports in Qt but instead their codereview page. How does one know which patches were merged in to trunk ?

Some of the comments above the patches mention the release they should end up in. Some don't, because the patch was not merged yet upstream when it was added to the formula. But the code review links are actually more useful than bug report links (that don't always exist): They have a section titled “Included in” that lists all the branches and tags that include the change. (A less accurate but efficient strategy to get rid of obsolete patches is to retry `brew unpack --patch qt5` with the new URL and remove failing patches until this operation succeeds.)

**Comment by UniqMartin** [comment]
Closing in favor of #50234. (I hope everyone's fine with that.)

**Comment by luzpaz** [comment]
All good. Thanks for spearheading!

**Pull request closed without merging**
