### PR TITLE
Update xctool to 0.2.5.

### PR DESCRIPTION
**Pull request by ExtremeMan**
https://github.com/facebook/xctool/releases/tag/v0.2.5

### CODE REVIEW

**Comment by DomT4** [comment]
It's trying to write a cache file that we no longer grant it access to via sandboxing. Can we set some kind of variable here to prevent this?

```
Build Preparation
Couldn't update module cache session file '/Users/brew/Library/Developer/Xcode/DerivedData/ModuleCache/Session.modulevalidation': You don’t have permission to save the file “Session.modulevalidation” in the folder “ModuleCache”.

2015-08-21 14:28:05.511 xcodebuild[75478:26580037] Error saving log: Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory" UserInfo=0x7fc72b567180 {NSFilePath=/Users/brew/Library/Developer/Xcode/DerivedData/xctool-dplznjrqyyderlegyyrfcaubwcff/Logs/Build/DBDF7549-73BE-430A-9C6D-FD3337B658FD.xcactivitylog, NSLocalizedDescription=No such file or directory} | User info: {
    NSFilePath = "/Users/brew/Library/Developer/Xcode/DerivedData/xctool-dplznjrqyyderlegyyrfcaubwcff/Logs/Build/DBDF7549-73BE-430A-9C6D-FD3337B658FD.xcactivitylog";
    NSLocalizedDescription = "No such file or directory";
} 
```

We do actually override the `HOME` environmental variable, so it's possible `xctool` is ignoring that override on this.

**Comment by ExtremeMan** [comment]
Specified the path to the derived data folder using `IDECustomDerivedDataLocation` environment. Works locally, let's see how it goes on your sandbox.

**Comment by ExtremeMan** [comment]
@DomT4, looks like it is fixed.

**Comment by DomT4** [comment]
Nice! Merged in https://github.com/Homebrew/homebrew/commit/4237b1f22514b9b2a673d4502d16505728d4903a. Thank you for your contribution to Homebrew, we appreciate it! :smiley_cat:

**Comment by ExtremeMan** [comment]
Awesome. Thanks!

**Pull request closed without merging**
