### PR TITLE
dmd 2.067.0

### PR DESCRIPTION
**Pull request by John-Colvin**
new release day :)

### CODE REVIEW

**Comment by John-Colvin** [comment]
ooo-errr, hold on a minute, need to run some checks.

**Comment by John-Colvin** [comment]
This breaks https://github.com/Homebrew/homebrew/blob/master/Library/Formula/dub.rb unless --devel is used (illegal behaviour that is now more strictly caught). Is there an agreed protocol for these situations? I could add dmd 2.066.1 to homebrew-versions and make dub depend on it for now perhaps?

**Comment by NfNitLoop** [comment]
Aw, ya beat me to it. 

How does it break dub? `brew test dub` worked for me.

**Comment by John-Colvin** [comment]
For me ```brew install dub``` (after installing 2.067.0 of course) fails with a bunch of compiler errors (escaping references to locals and so on).

The wait won't be long apparently.

**Comment by DomT4** [comment]
> I could add dmd 2.066.1 to homebrew-versions and make dub depend on it for now perhaps?

Mandatory tap deps aren't allowed in the core, I'm afraid.

> The wait won't be long apparently.

Generally, if the wait isn't too odious, we just wait for the new release to unstick things. Either that, or backporting the fixes to the compile as patch blocks works, providing upstream have already accepted them.

**Comment by John-Colvin** [comment]
I presume making a package default to a development version is not OK? There is a release candidate for dub that works with dmd 2.067.0 right now, but it'll be another week at best before it's released as stable.

**Comment by mikemcquaid** [comment]
> Generally, if the wait isn't too odious, we just wait for the new release to unstick things. Either that, or backporting the fixes to the compile as patch blocks works, providing upstream have already accepted them.

Yup, let's wait. We don't want to default to a development version unfortunately.

**Comment by John-Colvin** [comment]
Depends on: https://github.com/Homebrew/homebrew/pull/38407

Should be good to go once that is merged.

**Comment by John-Colvin** [comment]
Ok, just tested it with dub, everything seems fine. :+1:

**Comment by DomT4** [comment]
The bot has erased the build log and bottle since it only retains them for a few days to save space. I'll ask it to rebuild the bottle.

**Comment by DomT4** [comment]
@BrewTestBot test this please

**Comment by DomT4** [comment]
Cool. Build and bottle success :+1:

**Comment by xu-cheng** [comment]
Thanks for the pull request! 🎉 Homebrew depends on contributions from community members like you and we're grateful for your support.

**Pull request closed without merging**
