### PR TITLE
nim: fix checksum and update head url

### PR DESCRIPTION
**Pull request by ilovezfs**
Fixes the checksum error:
  Error: SHA256 mismatch
  Expected: 688da1487eb507e0aa96b757a2a4a311123ad38ab68a10277a0415724f982b33
  Actual: cd61f5e5768d4063596d6df578ae9bb5f9d52430773542987e91050b848cb1a9

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Thanks again @ilovezfs!

**Comment by DomT4** [comment]
Any idea why it changed?

**Comment by ilovezfs** [comment]
Nope.

**Comment by DomT4** [comment]
Can we go and check in case we've just pwned users?

**Comment by mikemcquaid** [comment]
Good point, sloppy of me not to check @DomT4, sorry.

**Comment by ilovezfs** [comment]
@DomT4 @mikemcquaid Comparing against http://rpm-ostree.cloud.fedoraproject.org/repo/pkgs/xena/nim/nim/nim-0.13.0.tar.xz/509126e206164f9bd3b4a0a9612fb349/nim-0.13.0.tar.xz
which has the same checksum as the original, here's what changed:
https://gist.github.com/ilovezfs/68a5546967626d4e85d0

**Comment by mikemcquaid** [comment]
@ilovezfs generally we create an upstream bug report to ask them not to repackage and check they weren't hacked.

**Comment by ilovezfs** [comment]
@mikemcquaid That makes sense. In this case, I would say there's no reason to because those changes all look benign. The original PR here was on the 18th, and those changes look like they were made the next day, which explains the discrepancy.

**Comment by mikemcquaid** [comment]
@ilovezfs I think it's still good practice to let upstreams know that we notice and that it takes effort on our part to check the difference between a malicious and intentional repackaging.

**Comment by ilovezfs** [comment]
@mikemcquaid @DomT4 https://github.com/nim-lang/Nim/issues/3968

**Comment by mikemcquaid** [comment]
@ilovezfs :bow:

**Comment by ilovezfs** [comment]
@mikemcquaid @DomT4 All is well: https://github.com/nim-lang/Nim/issues/3968#issuecomment-197046603

**Pull request closed without merging**
