### PR TITLE
anjuta 3.18.2

### PR DESCRIPTION
**Pull request by tschoonj**

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Failing on 10.10/10.9: http://bot.brew.sh/job/Homebrew%20Pull%20Requests/36119/

**Comment by tschoonj** [comment]
For some reason the Homebrew python is required on these two platforms when running itstool, which already has a dependency on `:python`. Strange...

**Comment by DomT4** [comment]
`itstool` has an unconditional `:python` dep which is probably the cause of that. CC @tdsmith in case he knows the background of that dep.

**Comment by tschoonj** [comment]
Same issue as in #45845. @tdsmith could you shine some light on this?

Thanks

**Comment by mikemcquaid** [comment]
@BrewTestBot test this please

**Comment by tschoonj** [comment]
Excellent! Both look ready now

**Comment by mikemcquaid** [comment]
Thanks @tschoonj!

**Pull request closed without merging**
