### PR TITLE
node 5.4.0

### PR DESCRIPTION
**Pull request by DomT4**

### CODE REVIEW

**Comment by UniqMartin** [comment]
Merged in a2c774b5455d638d7a23802b6b518db08f7be5e1. Thanks for your contribution, Dominyk! :smile_cat:

**Comment by DomT4** [comment]
'Tis alright, you could say I'm a regular around these parts :wink:

**Comment by UniqMartin** [comment]
Is it weird if I merge another maintainer's PR? GitHub certainly gets a bit confused and claims you closed it (and notifies me about it) even though I'm the one who eventually committed and pushed.

**Comment by DomT4** [comment]
If it's a simple version bump that's passed the CI, generally feel free. We only shy away from merging if there's work ongoing or someone has self-assigned it or it's a core change or such. Simple formula bumps are good to roll.

Github does handle the situation a little oddly.

**Comment by UniqMartin** [comment]
Cool! I wouldn't have done it if it was more than a simple version bump or something else (long discussion, etc.) indicated that the update requires a bit more care.

**Pull request closed without merging**
