### PR TITLE
x264 r2533, ffmbc 0.7.2, libav 11.3

### PR DESCRIPTION
**Pull request by Noctem**
Update to latest stable and master commits, migrate `10-bit` option to `with-10-bit`.

### CODE REVIEW

**Comment by Noctem** [comment]
Testing the functionality of this would require either `ffmpeg` or a YUV4MPEG fixture.

If it's a common enough occurrence that non-dependencies are necessary or useful for testing a formula, perhaps there should be a test dependency option like:
```ruby
depends_on "foo" => :test
```
where `foo` is only checked or installed (perhaps temporarily) when `brew test` is used. Thoughts?

**Comment by tdsmith** [comment]
Looks like $(brew uses x264) needs a revision bump: http://bot.brew.sh/job/Homebrew%20Pull%20Requests/22614/

**Comment by mikemcquaid** [comment]
> depends_on "foo" => :test

Yeh, I've been debating similar syntax at some point.

**Comment by tdsmith** [comment]
Pulling in the interim; very thorough, here! Thanks a lot. :tada:

**Pull request closed without merging**
