### PR TITLE
squid 3.5.9

### PR DESCRIPTION
**Pull request by wickedsp1d3r**

### CODE REVIEW

**Comment by DomT4** [comment]
Test is failing because we run sandboxed installations & tests on the CI now. Can we manipulate the values it needs to run for the `test do` stage?

```
WARNING: Cannot write log file: /usr/local/var/logs/cache.log
/usr/local/var/logs/cache.log: Operation not permitted
         messages will be sent to 'stderr'.
==> /usr/local/Cellar/squid/3.5.9/sbin/squid -k check
WARNING: Cannot write log file: /usr/local/var/logs/cache.log
/usr/local/var/logs/cache.log: Operation not permitted
         messages will be sent to 'stderr'.
2015/09/26 09:52:12| Set Current Directory to /usr/local/var/cache/squid
squid: ERROR: No running copy
WARNING: Cannot write log file: /usr/local/var/logs/cache.log
/usr/local/var/logs/cache.log: Operation not permitted
         messages will be sent to 'stderr'.
2015/09/26 09:52:13| Set Current Directory to /usr/local/var/cache/squid
squid: ERROR: No running copy
Error: squid: failed
```

**Comment by bfontaine** [comment]
Note that this duplicates #43631.

**Comment by DomT4** [comment]
I'm happy enough to merge whichever PR passes the CI first on this. The other PR hasn't moved on fixing the sandbox issues yet.

**Comment by bfontaine** [comment]
> I'm happy enough to merge whichever PR passes the CI first on this. The other PR hasn't moved on fixing the sandbox issues yet.

I agree on that.

**Comment by xu-cheng** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
