### PR TITLE
libepoxy 1.2 (new formula)

### PR DESCRIPTION
**Pull request by linkmauve**
This is a library used to abstract OpenGL functions differences between different OS.

### CODE REVIEW

**Comment by linkmauve** [comment]
Sorry, but I lost access to my uni’s OSX machines last month, and since then I’ve been unable to work on that PR.
Additionally, the buildbot is 404ing the test result.
I’d be grateful to someone who has actual access to an OSX machine to fix this last issue. :)

**Comment by mikemcquaid** [comment]
Rerunning the test so we can get a result again.

**Comment by mikemcquaid** [comment]
@BrewTestBot test this please

**Comment by linkmauve** [comment]
I just fixed the --strict failures, but I still fail to understand the other error, or how to fix it. :/
I should also note that the included patch got merged to libepoxy master, so it won’t be needed anymore for the next release.

**Comment by mikemcquaid** [comment]
@linkmauve Does `brew test --verbose libepoxy` work for you locally?

**Comment by linkmauve** [comment]
That’s the issue, I don’t have access to an OSX machine anymore, so I can’t test manually, and I have no idea how to fix the issue the bot reports.
It works fine on my Linux machine, with clang 3.5.0 and the same libepoxy version.

**Comment by mikemcquaid** [comment]
Think we're going go have to pass on this then, I'm afraid.

**Comment by tdsmith** [comment]
the error was that it wanted to be `testpath/"test.c"`, `testpath/"test"` (`testpath` outside the quotes) in what used to be lines 45 and 46

**Comment by linkmauve** [comment]
Yes, I was trying to find the actual issue, the previous (and main) error was this one: http://bot.brew.sh/job/Homebrew%20Pull%20Requests/19621/version=mountain_lion/testReport/junit/brew-test-bot/mountain_lion/test_libepoxy/

**Comment by linkmauve** [comment]
The file is executable, it appears to be in the correct format… Really, I don’t know what could go wrong here.

**Comment by tdsmith** [comment]
Running locally, it's segfaulting in glGetString.

```
bash-3.2$ lldb test
(lldb) target create "test"
Current executable set to 'test' (x86_64).
(lldb) run
Process 86482 launched: '/private/tmp/libepoxy-WlLALr/test' (x86_64)
Process 86482 stopped
* thread #1: tid = 0x2253ea, 0x00007fff87827c30 libGL.dylib`glGetString + 15, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x3b0)
    frame #0: 0x00007fff87827c30 libGL.dylib`glGetString + 15
libGL.dylib`glGetString + 15:
-> 0x7fff87827c30:  movq   0x3b0(%rcx), %rdx
   0x7fff87827c37:  movq   (%rcx), %rdi
   0x7fff87827c3a:  movl   %eax, %esi
   0x7fff87827c3c:  popq   %rbp
```

**Comment by scoopr** [comment]
I've written a working testcase. The problem with the previous one is that you can't just call GL calls before setting up a GL context.
scoopr/homebrew@ae259fa3eb91884c8b88c5b6f8b0866419a4dc5c

**Comment by linkmauve** [comment]
I just added this commit to my branch, this PR could probably be merged now. Thanks scoopr!

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
