### PR TITLE
mogenerator 1.30

### PR DESCRIPTION
**Pull request by rentzsch**
### All Submissions:

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew/pulls) for the same update/change?

_You can erase any parts of this template not applicable to your Pull Request._

### New Formulae Submissions:

- [x] Does your submission pass
`brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Have you built your formula locally prior to submission with `brew install <formula>`?

### Changes to Homebrew's Core:

- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your core changes, as applicable? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031) if you'd like one.
- [x] Have you successfully ran `brew tests` with your changes locally?

### CODE REVIEW

**Comment by rentzsch** [comment]
Ref: <http://bot.brew.sh/job/Homebrew%20Pull%20Requests/43569/>, <http://bot.brew.sh/job/Homebrew%20Pull%20Requests/43569/version=mavericks/console>

mogenerator 1.30 purposely can't be built on 10.9 any more. I can't find a way to tell brew bot that that's OK?

**Comment by DomT4** [comment]
Yup! `depends_on :macos => :yosemite` will do that for you.

**Comment by rentzsch** [comment]
Thanks @DomT4. I promise I read the docs but didn't figure that out.

**Comment by DomT4** [comment]
No worries! The documentation is extensive and it's easy to lose detail in there.

Merged in https://github.com/Homebrew/homebrew/commit/24c36b382c607121985682b4b6c6c7383437e22a. Thank you for another contribution to Homebrew @rentzsch! :smiley_cat:

**Pull request closed without merging**
