### PR TITLE
smc 0.01_2 (new formula)

### PR DESCRIPTION
**Pull request by yoshida-mediba**
## Apple System Management Control (SMC) Tool

Command line interface to Apple System Management Control

### CODE REVIEW

**Comment by yoshida-mediba** [comment]
Is there a way to solve?

```
==> brew style smc
1 file inspected, no offenses detected
Error: 2 problems in 1 formula

==> audit problems
smc:
 * GitHub repository not notable enough (<10 forks, <10 watchers and <20 stars)
 * GitHub repository too new (<30 days old)

==> FAILED
```

**Comment by mikemcquaid** [comment]
@yoshida-mediba I'm afraid we'll need to pass on this repository for now, sorry!

**Comment by mikemcquaid** [comment]
I'd suggest creating our own tap instead.

**Comment by bfontaine** [comment]
Here is how to create a tap: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-to-Create-and-Maintain-a-Tap.md

**Pull request closed without merging**
