### PR TITLE
pipes-sh 1.1.0: new formula

### PR DESCRIPTION
**Pull request by wkentaro**
### pipes.sh
* Animated pipes terminal screensaver
* https://github.com/pipeseroni/pipes.sh
* 1.1.0

### CODE REVIEW

**Comment by mikemcquaid** [comment]
@xu-cheng @DomT4  Any idea what the failure is here with the sandbox?

**Comment by DomT4** [comment]
Will pull this locally (sans bottle) in a minute and grab the more verbose log.

**Comment by DomT4** [comment]
Oh, heh. There's a missing comma in the test and it's passing the argument as one solid block, which causes failure:

```
==> /usr/local/Cellar/pipes-sh/1.1.0/bin/pipes.sh-v
Failed to execute: /usr/local/Cellar/pipes-sh/1.1.0/bin/pipes.sh-v
```

Should be:
```ruby
system "#{bin}/pipes.sh", "-v"
```

**Comment by wkentaro** [comment]
sorry, fixed.

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

For future reference the preferred commit message format for new formulae is `pipes-sh 1.1.0 (new formula)`.

**Comment by wkentaro** [comment]
Thanks!

**Pull request closed without merging**
