### PR TITLE
updated atlassian cli to 4.5.0

### PR DESCRIPTION
**Pull request by jayshao**

### CODE REVIEW

**Comment by bfontaine** [comment]
Any chance you could fix the audit issue on the test block by replacing this line:
```rb
assert shell_output(bin/"#{cmd} --help 2>&1 | head").include?("Usage:") unless cmd == "atlassian"
```

by that one?
```rb
assert_match "Usage:", shell_output(bin/"#{cmd} --help 2>&1") unless cmd == "atlassian"
```

**Comment by jayshao** [comment]
@bfontaine this is my first Brew PR - any advice on things I can look at to get this to pass? I am using this on my local install, will admit, am a bit confused as to where I can start

**Comment by bfontaine** [comment]
@jayshao The test is failing:
```
        Testing stash-cli
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20151014-7419-14oz9l1.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Library/Homebrew -- /usr/local/Library/Homebrew/test.rb /usr/local/Library/Formula/stash-cli.rb --verbose
==> /usr/local/Cellar/stash-cli/4.5.0/bin/all --help 2>&1
Error: stash-cli: failed
<0> expected but was
<254>.
```

You can see it here: http://bot.brew.sh/job/Homebrew%20Pull%20Requests/34807/version=yosemite/testReport/junit/brew-test-bot/yosemite/test_stash_cli/

You can also test locally with `brew test stash-cli`. It seems that the binaries installed by this formula now return an error code when called with `--help` (even if it’s a valid flag), like a lot of programs. `shell_output` accepts a second argument for the expected exit code. Try changing `shell_output(...)` into `shell_output(..., 254)` in the test. If `brew test stash-cli` doesn’t complain it should be ok.

**Comment by bfontaine** [comment]
Feel free to ask more questions if you need help and/or don’t understand something :wink:

**Comment by DomT4** [comment]
Any update here?

**Comment by DomT4** [comment]
Closing as dead. Please feel free to resubmit a fresh PR as desired. Thanks for your submission to Homebrew!

**Pull request closed without merging**
