### PR TITLE
Eliminate runtime ghc dependencies.

### PR DESCRIPTION
**Pull request by geoff-codes**
[The Homebrew community needs to get it's shit together on dependency resolution.](https://github.com/Homebrew/homebrew/pull/38329#issuecomment-90603079)
[Stuff](http://bot.brew.sh/job/Homebrew%20Pull%20Requests/25034/version=mavericks/console) like [this](http://bot.brew.sh/job/Homebrew%20Pull%20Requests/25034/version=mountain_lion/testReport/brew-test-bot/mountain_lion/) is [pretty mad](https://github.com/Homebrew/homebrew/pull/37828#issuecomment-82958087).

:yum:

### CODE REVIEW

**Comment by geoff-codes** [comment]
This will need to be merged regardless of build failures for #39134 to pass the testbot's scrutiny, I believe.

**Comment by DomT4** [comment]
> pretty mad.

? This just leads to a dead link, which is expected. The test-bot discards build logs after a few days to avoid ramming the disk space. Maybe I'm missing something here.

**Comment by geoff-codes** [comment]
Its not the details that matter; its that purescript is failing to build, and its currently a downstream **runtime** dependency of ghc, so it gets tested along with ghc. It fails, so the ghc build "fails".

**Comment by geoff-codes** [comment]
@DomT4 Let me try to explain this a little better. This needs to be merged **because** they fail. Both these formulae say that it `depends_on “ghc”`. But they don’t build, regardless.

When I push a change to #39134, the test bot test bot checks these after building ghc so to ensure these formula break when their “dependency” gets upgraded. So the build as a whole “fails”, even though GHC is fine.

**Comment by geoff-codes** [comment]
@mikemcquaid Oh and I can’t put them all in the same PR because it wants to re-build GHC for each, and exceeds the 2 hour timeout.

http://bot.brew.sh/job/Homebrew%20Pull%20Requests/25148/

And, for the record, Hackage's dependency resolution is _way_ worse (endemic), this was just really annoying suss out. :smile_cat:

**Comment by mikemcquaid** [comment]
> The Homebrew community needs to get it's shit together on dependency resolution.
> Stuff like this is pretty mad.

The criticism (and tone of it) is not really welcome. People do the best they can and we couldn't run this project without the Homebrew community's contributions. The problem here is the dependency resolution situation for Haskell packages. If you can offer a solution to that where we can pin versions in formulae that'd be extremely welcome.

**Comment by mikemcquaid** [comment]
That said, this PR may well be the right approach, I just need to double-check that.

**Comment by mikemcquaid** [comment]
Yeh, this PR makes sense. I'd like us to try and resolve these errors if we can, though. Version bump or something, maybe?

**Comment by geoff-codes** [comment]
Apologies, it was meant lightheartedly, since those were the exact words you used in #38329. I've been tearing my hair out about this for the last three days, and it turned out to be a _homebrew_ dependency resolution issue, so I went for it. Again, sorry, I meant no offense.

**Comment by mikemcquaid** [comment]
> Apologies, it was meant lightheartedly, since those were the exact words you used in #38329. I've been tearing my hair out about this for the last three days, and it turned out to be a homebrew dependency resolution issue, so I went for it. Again, sorry, I meant no offense.

Heh, in that case, fair play, no offence taken and appreciate the apology. I still blame the Haskell community for these errors though :wink:

**Comment by geoff-codes** [comment]
They can. I haven't looked at agda yet but with the changes here at https://github.com/pullreq/homebrew/commit/243c21a5 purescript builds fine with the ghc built with #39134.

**Comment by mikemcquaid** [comment]
Great!

**Comment by geoff-codes** [comment]
@mikemcquaid So, as soon as this PR is merged I have the rollback of https://github.com/pullreq/homebrew/commit/243c21a5629d7fef464e0d83ab11e55bd3c09e29 in #39134 staged for commit, and I do believe it should be a :white_check_mark: this time around. I've also got [a follow up PR in the wings](https://github.com/Homebrew/homebrew/commit/5dd75db6e6b68bb9df47c210e345a2473e511a25) to eliminate the gmp deps (should these be rev bumped as well? due to the dynamic linkage?).

**Comment by DomT4** [comment]
> Really, the only thing that should have a runtime dependency on ghc is cabal, I think.

Thanks for the explanation. Pointing to links which contained expected deadlinks kinda threw me off :smile_cat:.

**Comment by mikemcquaid** [comment]
Can we get one commit per-formula here? I'd also like to get these both actually building before we merge this even if that means a version bump or similar.

**Comment by geoff-codes** [comment]
I've pushed a separate PR purescript, and it should build. Agda, well, cabal can't figure out how to resolve the dependencies :hankey:. So this PR is now just resoling the `depends_on 'ghc' => build` issue in Agda that's tripping up the ghc build.

**Comment by geoff-codes** [comment]
I've push those final changes to #39134, as I'm not sure if I'll be able to do so for a couple of days otherwise (travel). So, when/if this and #39238 get merged you may want to re-trigger the testbot manually on #39134.

**Comment by mkscrg** [comment]
@mikemcquaid Anything an outsider can do to help make this (or #39134) merge-worthy? A working GHC 7.10 formula would be :sparkles:

**Comment by mkscrg** [comment]
This build fails because Adga doesn't build with GHC 7.10 yet. Note the `base < 4.8` dependency on Hackage: <http://hackage.haskell.org/package/Agda-2.4.2.2>

Here's the open ticket for 7.10 support: <https://code.google.com/p/agda/issues/detail?id=1482>

**Pull request closed without merging**
