### PR TITLE
unbound 1.5.7

### PR DESCRIPTION
**Pull request by Habbie**

### CODE REVIEW

**Comment by DomT4** [comment]
@BrewTestBot test this please

**Comment by Habbie** [comment]
Please hold off on merging - I think it may have a problem with upgrading.

**Comment by DomT4** [comment]
Sure. Let us know.

**Comment by Habbie** [comment]
`brew reinstall` on the old one has the same issue, being that the postinstall is not idempotent:
```
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall unbound`
```

so I'd say go ahead with the merge. I'll make a ticket (or a patch) for the post-install issue afterwards. It's not an actual problem.

**Comment by DomT4** [comment]
Any chance we could roll that into this? Providing users are going to run into the problem on update/upgrade in certain cases?

**Comment by apjanke** [comment]
I put together a fix for it. #46892. It tweaks the config file before the install instead of after.

**Comment by Habbie** [comment]
That looks great. Closing this, thanks @apjanke

**Comment by apjanke** [comment]
Your commit got pulled in with #46892, which I've merged. Thank you for your contribution to Homebrew!

**Comment by Habbie** [comment]
:+1: welcome as always!

**Pull request closed without merging**
