### PR TITLE
aws-elasticbeanstalk 3.3.2

### PR DESCRIPTION
**Pull request by Tonkpils**

### CODE REVIEW

**Comment by tdsmith** [comment]
Can you bump these resources?

```
  resource "jmespath" do
    url "https://pypi.python.org/packages/source/j/jmespath/jmespath-0.7.1.tar.gz"
    sha256 "cd5a12ee3dfa470283a020a35e69e83b0700d44fe413014fd35ad5584c5f5fd1"
  end

  resource "python-dateutil" do
    url "https://pypi.python.org/packages/source/p/python-dateutil/python-dateutil-2.4.2.tar.gz"
    sha256 "3e95445c1db500a344079a47b171c45ef18f57d188dffdb0e4165c71bea8eb3d"
  end
```

and use a sha256 hash for the download (i.e. `sha256 "2854c0cc10138d14ccc8166a26e441bba2a1913d5a1c54a33b5a0a448b785942"`) please?

**Comment by Tonkpils** [comment]
@tdsmith `sha256` for every resource or just those two?

**Comment by xu-cheng** [comment]
@Tonkpils `sha256` for every resource would be better. :+1:

**Comment by Tonkpils** [comment]
Done :)

**Comment by tdsmith** [comment]
:+1: :sparkles: Thanks; Homebrew depends on contributions from community members like you and we're grateful for your support!

**Pull request closed without merging**
