### PR TITLE
cvc4: use https url

### PR DESCRIPTION
**Pull request by vszakats**
Ref: https://github.com/Homebrew/homebrew/commit/73da0eeb86a3e05d37b12dd988d3d34fd0220daa#commitcomment-15105091

### CODE REVIEW

**Comment by vszakats** [comment]
Yosemite specific failure:
```
==> /usr/local/Cellar/cryptol/2.2.4/bin/cryptol -b /private/tmp/cryptol20151224-16224-11d8rm3/hello.icry
Error: cryptol: failed
Expected /Loading\ module\ Cryptol\nQ\.E\.D\.\nQ\.E\.D\.\n/ to match "Loading module Cryptol\n*** An error occurred.\n***  Failed to start the external solver: fd:6: hGetLine: end of file\n***  Make sure you can start \"/usr/local/bin/cvc4\"\n***  from the command line without issues.\n*** An error occurred.\n***  Failed to start the external solver: fd:6: hGetLine: end of file\n***  Make sure you can start \"/usr/local/bin/cvc4\"\n***  from the command line without issues.\n".
```

**Comment by mikemcquaid** [comment]
@BrewTestBot test this please

**Comment by DomT4** [comment]
Why are we bumping the `revision` here?

**Comment by vszakats** [comment]
It was a blind try to avoid the Yosemite failure. I'm undoing it.

**Comment by DomT4** [comment]
Cool, Thanks. Just wanted to check I wasn't missing a discussion somewhere there.

Merged in https://github.com/Homebrew/homebrew/commit/de1956df80d84a7d207e6daa5cdf7ddbbac732cb. Thanks @vszakats!

**Pull request closed without merging**
