### PR TITLE
Update vault to v0.5.0

### PR DESCRIPTION
**Pull request by kunalshah**

### CODE REVIEW

**Comment by kunalshah** [comment]
This build failed because Travis CI couldn't reach external host. https://travis-ci.org/Homebrew/homebrew/jobs/107968257

Part of log:

==> brew tests
==> Installing or updating 'bundler' gem
Successfully installed bundler-1.11.2
1 gem installed
Could not reach host bundler.rubygems.org. Check your network connection and try
again.
/Users/travis/.gem/ruby/1.8/gems/bundler-1.11.2/lib/bundler/spec_set.rb:94:in `block in materialize': Could not find rake-10.5.0 in any of the sources (Bundler::GemNotFound)
	from /Users/travis/.gem/ruby/1.8/gems/bundler-1.11.2/lib/bundler/spec_set.rb:87:in `map!'
	from /Users/travis/.gem/ruby/1.8/gems/bundler-1.11.2/lib/bundler/spec_set.rb:87:in `materialize'
	from /Users/travis/.gem/ruby/1.8/gems/bundler-1.11.2/lib/bundler/definition.rb:137:in `specs'
	from /Users/travis/.gem/ruby/1.8/gems/bundler-1.11.2/lib/bundler/definition.rb:182:in `specs_for'
	from /Users/travis/.gem/ruby/1.8/gems/bundler-1.11.2/lib/bundler/definition.rb:171:in `requested_specs'
	from /Users/travis/.gem/ruby/1.8/gems/bundler-1.11.2/lib/bundler/environment.rb:18:in `requested_specs'
	from /Users/travis/.gem/ruby/1.8/gems/bundler-1.11.2/lib/bundler/runtime.rb:13:in `setup'
	from /Users/travis/.gem/ruby/1.8/gems/bundler-1.11.2/lib/bundler.rb:92:in `setup'
	from /Users/travis/.gem/ruby/1.8/gems/bundler-1.11.2/lib/bundler/setup.rb:18:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
==> FAILED



What is the process to re-submit the build job?

**Comment by dunn** [comment]
> What is the process to re-submit the build job?

Just let us know and we can re-queue it, thanks!

**Comment by kunalshah** [comment]
Thanks @dunn , I closed and re-opened the pull request hoping it'd pass this time. However, there seems to be problem with github notification as the travis builds are not started for mine and other's pull requests. I have written to support@github.com before few minutes seeking assistance.

**Comment by dunn** [comment]
Sometimes we have a backlog and they take a while to start, too.

**Comment by kunalshah** [comment]
Got it. Will wait for few hours next time. Thanks for the prompt response.

**Comment by DomT4** [comment]
Don't worry _too much_ about transient Travis errors for now. As long as you pass Jenkins we're more or less happy.

Merged in https://github.com/Homebrew/homebrew/commit/44da220638ab1955f02a61eea80978a608eda17f. Thank you for your contribution to Homebrew @kunalshah; we appreciate it! :smiley_cat:

**Comment by mkuzmin** [comment]
Here is a quote from HashiCorp [blog post](https://www.hashicorp.com/blog/vault-0.5.html):
> The HashiCorp-provided binary release of Vault 0.5.0 is built against a slightly modified Go 1.5.3 that contains two commits cherry-picked from the Go 1.6 tree. These patches contain bug fixes specific to TLS certificate handling that were affecting Vault users.

A cask with official binaries works better.

**Pull request closed without merging**
