### PR TITLE
list: exclude logs and Ruby from unbrewed

### PR DESCRIPTION
**Pull request by UniqMartin**

### CODE REVIEW

**Comment by xu-cheng** [comment]
:+1:

**Comment by mikemcquaid** [comment]
:+1: but can you provide a bit more context as to the motivation for this?

**Comment by UniqMartin** [comment]
> can you provide a bit more context as to the motivation for this?

I have multiple independent Homebrew installations on a single system and hence decided to put both the cache and the logs directory into a subdirectory of the respective prefix to keep things more organized (I think Dominyk mentioned he's doing something similar). I wanted to keep the output of `brew list --unbrewed` accurate and not ignoring the logs directory seemed like an oversight.

I'm pretty sure the Ruby directories, that are used for stuff that should survive Ruby reinstalls, should be treated in a similar manner to the corresponding Python directories, also to keep the output of `brew list --unbrewed` clean. (Could be I misunderstood something here, as I'm not much of a Python user.)

**Comment by mikemcquaid** [comment]
Ok, cool, :+1: then and thanks for clarifying. Adding some of that in commit messages would be :heart_eyes:.

**Comment by UniqMartin** [comment]
> Adding some of that in commit messages would be :heart_eyes:.

I believe my original commit messages get that across while being more succinct than the explanation I wrote in my comment above. Or am I overlooking something?

**Comment by mikemcquaid** [comment]
@UniqMartin I read them before asking but I didn't understand the high-level motivation. Up to you, though.

**Comment by UniqMartin** [comment]
Would adding

> This avoids spurious output in `brew list --unbrewed` when the Homebrew logs directory is a subdirectory of the Homebrew prefix.

to the logs-related commit message and adding

> This avoids spurious output in `brew list --unbrewed` when a brewed `ruby` is used to, e.g., install Gems.

to the Ruby-related one be an improvement?

**Comment by mikemcquaid** [comment]
> to the Ruby-related one be an improvement?

Yup :+1:

**Comment by UniqMartin** [comment]
Updated. :smiley_cat:

**Comment by mikemcquaid** [comment]
:+1: :ship:

**Comment by DomT4** [comment]
> I have multiple independent Homebrew installations on a single system and hence decided to put both the cache and the logs directory into a subdirectory of the respective prefix to keep things more organized (I think Dominyk mentioned he's doing something similar). 

Yeah, I'm planning on flat-out moving the `HOMEBREW_CACHE` and `LOGS` to a relative prefix fairly soon. It was on my pre-Christmas list, but well, life/uni/etc. I keep mine in `HOMEBREW_PREFIX/var/homebrew` personally.

:+1: on this PR from me.

**Comment by UniqMartin** [comment]
> I keep mine in `HOMEBREW_PREFIX/var/homebrew` personally.

Thanks! I didn't remember where you put them exactly. As `var` is excluded by default, you were already covered. I went for a more immediately accessible location in `HOMEBREW_PREFIX/.brew-cache` and `HOMEBREW_PREFIX/.brew-logs` and hence noticed the omission. :smile_cat:

**Pull request closed without merging**
