### PR TITLE
go-app-engine 1.9.23

### PR DESCRIPTION
**Pull request by raindev**
Upgrade both 32 and 64 bit versions

### CODE REVIEW

**Comment by DomT4** [comment]
Could you possibly update both to use `sha256` instead of `sha1`? Thanks!

**Comment by raindev** [comment]
Yes, sure

**Comment by xu-cheng** [comment]
Thanks for the pull request! 🎉 Homebrew depends on contributions from community members like you and we're grateful for your support.

**Comment by raindev** [comment]
I'm glad to help! Thank you for maintaining Homebrew, it makes our lifes much easier :)

**Pull request closed without merging**
