### PR TITLE
ldc: 0.15.2-beta2

### PR DESCRIPTION
**Pull request by John-Colvin**

### CODE REVIEW

**Comment by John-Colvin** [comment]
What's with the missing test results?

**Comment by DomT4** [comment]
They aren't missing: http://bot.brew.sh/job/Homebrew%20Pull%20Requests/29095/version=mavericks/testReport/junit/brew-test-bot/mavericks/install_ldc/

**Comment by John-Colvin** [comment]
I had to authorise access otherwise it wouldn't load them. Also, I see  ```Some checks have failed — Build finished. No test results found.``` in the test/checks dialogue on this page

**Comment by DomT4** [comment]
I believe you have to authorise access to the test-bot to view the logs. I think that is out of our hands. @mikemcquaid will know.

**Comment by John-Colvin** [comment]
Ok, I understand and can see the build logs now.

The problem is that the currently released version of ldc (v0.5.1) doesn't build with llvm 3.6.1
Is there any way to proceed?

**Comment by mikemcquaid** [comment]
> The problem is that the currently released version of ldc (v0.5.1) doesn't build with llvm 3.6.1
> Is there any way to proceed? Currently we're totally reliant on the bottle for 0.5.1

What do you think we should do; make the beta version the stable one temporarily?

**Comment by John-Colvin** [comment]
We do have patches for llvm 3.6.1 support for 0.5.1, but they touch 40+ files and are likely to be less well tested than 0.5.2-beta2

temporary beta as stable then? https://github.com/Homebrew/homebrew/pull/41511

**Comment by John-Colvin** [comment]
Ok, now #41511 is merged, I guess this can be closed.

**Pull request closed without merging**
