### PR TITLE
gtk-gnutella: fix 404.

### PR DESCRIPTION
**Pull request by geoff-codes**
Split out from #37014 per "one commit per formula, one formula per commit" guideline.

### CODE REVIEW

**Comment by tdsmith** [comment]
Is this expected to build on Mountain Lion?

**Comment by geoff-codes** [comment]
> Is this expected to build on Mountain Lion?

I have no idea. :confused:

**Comment by tdsmith** [comment]
Hmm, this sequence:

>/bin/rm -f libshared.a
/usr/bin/ranlib: file: libshared.a(compat_un.o) has no symbols
/usr/bin/ranlib: file: libshared.a(dbus_util.o) has no symbols
/usr/bin/ranlib: file: libshared.a(fragcheck.o) has no symbols
/usr/bin/ranlib: file: libshared.a(mingw32.o) has no symbols
/usr/bin/ranlib: file: libshared.a(regex.o) has no symbols
error: /usr/bin/ranlib: file: libshared.a is not writable (No such file or directory)

makes me think things might run out of order; want to try adding a call to `ENV.deparallelize` at the top of install?

**Comment by geoff-codes** [comment]
Yeah that looks like a makefile race, lets give it a shot.

**Comment by geoff-codes** [comment]
:+1:

**Pull request closed without merging**
