### PR TITLE
ghi 0.9.4

### PR DESCRIPTION
**Pull request by AlexChesters**

### CODE REVIEW

**Comment by DomT4** [comment]
Was going to merge this in a minute, just noticed it'd been closed. Something broken/etc?

**Comment by AlexChesters** [comment]
Sorry @DomT4, just managed to squeeze in a bug fix or two so making a new version, creating a new PR now!

**Comment by AlexChesters** [comment]
I've created a new PR #45055

**Comment by DomT4** [comment]
No worries! Will merge that one once Travis has passed it.

The upside of a formula that doesn't need bottles is that it doesn't have to wait for Jenkins, which means you don't have to wait for the giant Jenkins backlog to clear before we can merge, heh.

**Comment by AlexChesters** [comment]
Ha, that's true :smile: 

Nice one, cheers @DomT4!

**Pull request closed without merging**
