### PR TITLE
atlassian-cli 4.3.0 (replaced stash-cli)

### PR DESCRIPTION
**Pull request by guoxiao**

### CODE REVIEW

**Comment by DomT4** [comment]
Is this actually a new project, or did the upstream project rename?

If the latter, we don't handle upstream renames this way sadly, since the way our formula code works the user won't automatically get updated from `stash-cli` to `atlassian-cli` even though they're the same thing. It's a core issue that we're aware of and have a desire to fix going forwards, but for now, can't do formula renames.

See #37306 for a recent example of how to handle it instead. (We alias the new name onto the old name).

If it's a new project entirely and the old one isn't going to get updates any more, it should be moved to the `boneyard` instead of just deleted.

**Comment by guoxiao** [comment]
The upstream integrated `stash-cli` and several commands into a `atlassian-cli` package. The `stash` command provided by `stash-cli` now can be provided by `atlassian-cli`. 
So I think I should add a alias to redirect `stash-cli` to `atlassian-cli`?

**Comment by DomT4** [comment]
Sorry - I meant the other way around. The current formula remains, but you update everything aside the name, and then you symlink the new name `atlassian-cli` onto the existing `stash-cli` formula.

**Comment by guoxiao** [comment]
But now `atlassian-cli` is the correct name, and `stash-cli` is only a part of it. So I think aliasing `atlassian-cli` onto `stash-cli` is not appropriate.

**Comment by DomT4** [comment]
Sadly it is the way we do things, otherwise users who already have `stash-cli` installed will never get the update. See #14374 for the list of things we would like to change but can't yet.

**Comment by guoxiao** [comment]
Alright. I've updated the formulas.
We may need a rename when it's possible.

**Comment by DomT4** [comment]
Thanks. Feel free to comment on that issue I highlighted that it needs a rename.

**Comment by mikemcquaid** [comment]
@BrewTestBot test this please

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/7fee2f6ef745d08339234af25b83f3494fac4f07. Thank you for your contribution to Homebrew, we appreciate it! :smiley_cat:

**Pull request closed without merging**
