### PR TITLE
postgresql: use SSL/TLS URLs

### PR DESCRIPTION
**Pull request by vszakats**
(homepage will redirect to plaintext, but anyways)

### CODE REVIEW

**Comment by xu-cheng** [comment]
Looks like it require a revision since last openssl update:
```
==> brew test --verbose pgloader					 FAILED
Testing pgloader
==> initdb
dyld: Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /usr/local/Cellar/postgresql/9.4.1/bin/postgres
  Reason: image not found
no data was returned by command ""/usr/local/Cellar/postgresql/9.4.1/bin/postgres" -V"
The program "postgres" is needed by initdb but was not found in the
same directory as "/usr/local/Cellar/postgresql/9.4.1/bin/initdb".
Check your installation.
Error: pgloader: failed
Failed executing: initdb 
```
http://bot.brew.sh/job/Homebrew/12774/version=yosemite/console

cc @DomT4 Am I right?

**Comment by DomT4** [comment]
> cc @DomT4 Am I right?

**Comment by DomT4** [comment]
> cc @DomT4 Am I right?

I'm not sure here actually. The error doesn't look consistent with a linking failure in the traditional sense, and I can't replicate it using my local install. The error seems to either be saying OpenSSL doesn't exist on the machine at all, or Postgres isn't getting installed into `bin` alongside `initdb` :confused:. I'll poke it a bit shortly and see if I can find anything weird going on.

**Comment by vszakats** [comment]
`revision 1` didn't fix it.

**Comment by vszakats** [comment]
It passed after bumping revision.

**Comment by DomT4** [comment]
Weird. Didn't look like the typical error, and I couldn't reproduce locally even using everything from-bottle. Ho hum. At least it's cleared the bot now.

**Comment by xu-cheng** [comment]
Thanks @vszakats

**Pull request closed without merging**
