### PR TITLE
glib-networking 2.46.0

### PR DESCRIPTION
**Pull request by tschoonj**

### CODE REVIEW

**Comment by tschoonj** [comment]
@DomT4 can you restart this please? It should work now with #44221 pulled in.

Thanks

**Comment by DomT4** [comment]
Done.

**Comment by tschoonj** [comment]
@DomT4 can you check this again? It doesn't look like it has restarted to me...

Thanks

**Comment by DomT4** [comment]
It's in the queue at around ~3​36​03. The queue just isn't short today.

**Comment by tschoonj** [comment]
Ok, thanks

**Comment by DomT4** [comment]
Got there in the end. Merged in https://github.com/Homebrew/homebrew/commit/519cdce1df8ae654b4a00dbccc41405cd5eb6578. Thank you!

**Pull request closed without merging**
