### PR TITLE
Postgis 2.2.0

### PR DESCRIPTION
**Pull request by jsheedy**
Updated postgis to 2.2.0 and dependency sfcgal to 1.2.0.

### CODE REVIEW

**Comment by cosmo0920** [comment]
Tests are failing.
Perhaps you need to read this comment: https://github.com/Homebrew/homebrew/pull/41962#issuecomment-123250123.

**Comment by jsheedy** [comment]
Ok, thanks. I'll take a look.

**Comment by cosmo0920** [comment]
Thanks!
iIt seems that you can include `postgis` and `sfcgal` into `postgresql` formula like this PR: https://github.com/Homebrew/homebrew/pull/43719

**Comment by DomT4** [comment]
Unless `sfcgal` actually installs directly into the `postgresql` prefix like the other formulae, it's fine to stay as an independent formula.

**Comment by nlebedev** [comment]
I've tested postgis 2.2.0 formula with brewed Postgresql devel 9.5beta1 version.
Although posts gets built ok, I can't create extension in my DB.
When running `CREATE EXTENSION postgis;`
I get  
`ERROR: could not open extension control file "/usr/local/Cellar/postgresql/9.5beta1/share/postgresql/extension/postgis.control": No such file or directory`

When trying to copy everything from `/usr/local/Cellar/postgis/2.2.0/share/postgresql/extension/` to 
`/usr/local/Cellar/postgresql/9.5beta1/share/postgresql/extension/`
I get
`ERROR: could not access file "$libdir/postgis-2.2": No such file or directory`

How do I create extension for postgis brewed with this formula?

**Comment by jsheedy** [comment]
I never got around to fixing this up, so I'm going to close the pull request. Thanks for your help and suggestions!

**Pull request closed without merging**
