### PR TITLE
boost-python: install documentation

### PR DESCRIPTION
**Pull request by afh**

### CODE REVIEW

**Comment by DomT4** [comment]
```
boost-python:
 * Dir["libs/python/doc"] is unnecessary; just use "libs/python/doc"
```

Unless you meant:
```
doc.install Dir["libs/python/doc/*"]
```
Of course.

**Comment by afh** [comment]
Thanks for the hint, I've updated this PR accordingly.

**Comment by mikemcquaid** [comment]
Thanks again @afh!

**Comment by afh** [comment]
@mikemcquaid Awesome avatar :laughing: 

What were the main reasons for splitting Boost.Python into its own boost-python formula?

I find it odd, that it is not a standalone formula suitable for development; it's missing the necessary includes (e.g. boost/python.hpp). Meaning that if I have a project using Boost.Python I also have to install the boost formula in order to get the required headers.

Would it be possible to detect whether the boost formula is installed and symlink the `include` directory to the boost-python installation (as to have all required place available from one place) and install the include files when boost is not installed.

**Comment by mikemcquaid** [comment]
I'm not sure of the reason CC @tdsmith @mistydemeo

**Comment by tdsmith** [comment]
The goal of boost-python was to provide a Boost.Python library that could be linked against the correct python without having to rebuild All Of Boost; we couldn't bottle Boost.Python with boost because it had an explicit link to a Python framework. Anything that needed Boost.Python had to rebuild boost --with-python, which was really painful.

Since then, we discovered that Boost.Python did not need to be linked against a Python framework at all, and I sent patches upstream to Boost to fix their linking, and so now boost-python is bottled.

The boost-python package is still useful to minimize the amount of recompilation needed for people who need python3 support.

I assumed while separating the packages that boost would always be installed because I don't understand the boost build system very well; this was the least work I could do to get the libraries to build the way I wanted them to build. There's probably room for improvement.

The PRs should be pretty easy to find if you want more background.

**Comment by tdsmith** [comment]
> I assumed while separating the packages that boost would always be installed

Also: anecdotally, this seems fine in practice, since packages that use Boost.Python tend to rely on other Boost libraries as well.

**Pull request closed without merging**
