### PR TITLE
fq 0.9.2, HEAD

### PR DESCRIPTION
**Pull request by dunn**

### CODE REVIEW

**Comment by mikemcquaid** [comment]
:+1: once green

**Comment by DomT4** [comment]
Sandbox failure, I believe:

```
Opening configdb /usr/local/Cellar/fq/0.9.2/var/lib/fq/fqd.sqlite
... failed to open /usr/local/Cellar/fq/0.9.2/var/lib/fq/fqd.sqlite: unable to open database file
```

**Comment by dunn** [comment]
It works locally with `--sandbox.`  I'll poke a little more.

**Comment by dunn** [comment]
Oh, @DomT4 was right.  The sandbox is preventing fqd.sqlite from being created; I had already created it on a previous non-sandbox test, so that's why I wasn't seeing the error.

**Pull request closed without merging**
