### PR TITLE
arabica 20160214

### PR DESCRIPTION
**Pull request by bfontaine**

### CODE REVIEW

**Comment by apjanke** [comment]
Missing "mangle" command?

```
        Testing arabica
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20160216-1737-i8hbk3.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Library/Homebrew -- /usr/local/Library/Homebrew/test.rb /usr/local/Library/Formula/arabica.rb --verbose
==> /usr/local/Cellar/arabica/20160214/bin/mangle test.xml test.xsl
Error: arabica: failed
No such file or directory - /usr/local/Cellar/arabica/20160214/bin/mangle
```

**Comment by bfontaine** [comment]
I need to look into that; it’s installed locally but the test fails.

**Comment by DomT4** [comment]
Apologies @bfontaine, I completely missed this PR being open :cry:. The `mangle` executable is only generated if you build it against Boost, which you probably have locally but the CI won't. That's likely the only reason the test failed.

**Comment by bfontaine** [comment]
Thank you and no worries @DomT4 :smile:

**Pull request closed without merging**
