### PR TITLE
bump cryptography to 1.2.3

### LINKED ISSUE #49709: sickrage has a broken build
OpenSSL changed a function signature in a security release. :tada:

https://github.com/pyca/cryptography/issues/2750

```
tim@rocketman:Library (master)$ grep -Re 'url.*cryptography.*' Formula Taps
Formula/ansible.rb:    url "https://pypi.python.org/packages/source/c/cryptography/cryptography-1.1.2.tar.gz"
Formula/duplicity.rb:    url "https://pypi.python.org/packages/source/c/cryptography/cryptography-1.2.1.tar.gz"
Formula/letsencrypt.rb:    url "https://pypi.python.org/packages/source/c/cryptography/cryptography-1.2.3.tar.gz"
Formula/mitmproxy.rb:    url "https://pypi.python.org/packages/source/c/cryptography/cryptography-1.1.2.tar.gz"
Formula/ooniprobe.rb:    url "https://pypi.python.org/packages/source/c/cryptography/cryptography-1.0.1.tar.gz"
Formula/sickrage.rb:    url "https://pypi.python.org/packages/source/c/cryptography/cryptography-1.1.tar.gz"
Formula/svtplay-dl.rb:    url "https://pypi.python.org/packages/source/c/cryptography/cryptography-1.1.2.tar.gz"
Taps/homebrew/homebrew-versions/ansible19.rb:    url "https://pypi.python.org/packages/source/c/cryptography/cryptography-1.1.2.tar.gz"
```

### PR DESCRIPTION
**Pull request by tdsmith**
Fixes #49709.

### CODE REVIEW

**Comment by tdsmith** [comment]
blocking #49499

**Comment by tdsmith** [comment]
duplicity needs pyrax bumped; mitmproxy needs a version bump; sickrage has a sha mismatch

**Comment by dmage** [comment]
+1

**Comment by tdsmith** [comment]
need to bundle setuptools for mitmproxy and sickrage

**Comment by Thinkscape** [comment]
+1

**Comment by tdsmith** [comment]
pulled without sickrage

**Pull request closed without merging**
