### PR TITLE
Let lilypond use superenv and clang.

### PR DESCRIPTION
**Pull request by geoff-codes**
The package failed to build for me _without_ removing these.

### CODE REVIEW

**Comment by geoff-codes** [comment]
And again, same mysterious failure on ML only...

**Comment by jacknagel** [comment]
There's no need to bump the revision for a change like this, or to put it another way, there's no reason people who already have it installed should have to reinstall it.

**Comment by geoff-codes** [comment]
> There's no need to bump the revision for a change like this, or to put it another way, there's no reason people who already have it installed should have to reinstall it.

Lilypond (and Guile) are largely written in C++. Is the stdlib ABI change not a sufficient enough reason to bump the rev?

**Comment by jacknagel** [comment]
Isn't lilypond an application? Why should users who already have a working installation need to reinstall it?

**Comment by adius** [comment]
Any advancements with this issue?

**Comment by geoff-codes** [comment]
@adius @jacknagel I removed the offending version bump a while back... is there anything else holding this up?

**Comment by mikemcquaid** [comment]
@BrewTestBot test this please

**Comment by geoff-codes** [comment]
@BrewTestBot please inform @mikemcquaid the result of his request please

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

For future reference the preferred commit message format is `lilypond: use superenv and clang.`.

**Pull request closed without merging**
