### PR TITLE
v8: fix up libv8.dylib install_name

### LINKED ISSUE #36571: v8 formula links libraries to /usr/local/lib when Homebrew is installed in home directory
I have homebrew installed in my home directory:  ~/homebrew

The d8 binary from the v8 formula has a dylib link to /usr/local/lib.

```
wfurr@wfurr-macbookair:~$ otool -L homebrew/bin/d8 
homebrew/bin/d8:
	/usr/local/lib/libv8.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libedit.3.dylib (compatibility version 2.0.0, current version 3.0.0)
	/usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 60.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)
	/usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 2577.0.0)
wfurr@wfurr-macbookair:~$ LD_LIBRARY_PATH=/Users/wfurr/homebrew/lib d8
dyld: Library not loaded: /usr/local/lib/libv8.dylib
  Referenced from: /Users/wfurr/homebrew/bin/d8
  Reason: image not found
Trace/BPT trap: 5
```

Changing the path with install_name_tool fixes the issue.

```
wfurr@wfurr-macbookair:~$ sudo install_name_tool -change /usr/local/lib/libv8.dylib /Users/wfurr/homebrew/lib/libv8.dylib homebrew/bin/d8 
Password:
wfurr@wfurr-macbookair:~$ d8
V8 version 3.25.30 [console: readline]
```

The library should be linked against the correct directory when installed

### PR DESCRIPTION
**Pull request by tdsmith**
Fixes #36571.

Is there a reason v8 isn't bottled?

### CODE REVIEW

**Comment by mistydemeo** [comment]
> Is there a reason v8 isn't bottled?

Looking at history, the formula hasn't been touched in close to a year - we weren't bottling as much at the time.

**Comment by tdsmith** [comment]
Hmm; this has been fixed before, in bb7fcab9d6. Was there bit-rot?

**Comment by tdsmith** [comment]
@BrewTestBot test this please

**Comment by mikemcquaid** [comment]
> Looking at that commit, gyp may not have written an absolute install_name in 2012, but it does now; keg_fix_install_names doesn't touch absolute install_names, so I don't expect that commit to have solved the current issue.

Maybe use an `inreplace` here for now as it seems like something that may well move around?

**Pull request closed without merging**
