### PR TITLE
create: accept HEAD urls

### LINKED ISSUE #45310: brew create missing "name" option
Brew create uses a first part of string splitted by a 'minus' sign, so this:

```bash
brew create https://github.com/fboender/ansible-cmdb.git
```

Returns an error:

```
Error: /usr/local/Library/Formula/ansible.rb already exists
```

Indeed it exists! But ansible-cmbd doesn't....

### PR DESCRIPTION
**Pull request by bfontaine**
Fixes #45310.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
:+1: although I do wonder if people necessarily mean `head` in that case or if they are just intending to provide the homepage?

**Comment by bfontaine** [comment]
@mikemcquaid If it ends with `.git` it’s probably that they mean `head`; it takes more effort to copy `github.com/a/b.git` than `github.com/a/b`.

**Comment by bfontaine** [comment]
We could pre-fill the `homepage` field though.

**Comment by mikemcquaid** [comment]
> @mikemcquaid If it ends with .git it’s probably that they mean head; it takes more effort to copy github.com/a/b.git than github.com/a/b.

:+1:

**Pull request closed without merging**
