### PR TITLE
Update v8 to v4.9.385.28

### PR DESCRIPTION
**Pull request by sscotth**
Tracking Chrome Stable v49.0.2623.75

### All Submissions:

- [X] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew/blob/master/.github/CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew/pulls) for the same update/change?

### CODE REVIEW

**Comment by dunn** [comment]
gjstest may need its `revision` bumped: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/gjstest.rb#L6

**Comment by DomT4** [comment]
:+1: on @dunn's comment.

**Comment by sscotth** [comment]
As in 'Revision 1.02'?

**Comment by DomT4** [comment]
```diff
  url "https://github.com/google/gjstest/archive/v1.0.2.tar.gz"
  sha256 "7bf0de1c4b880b771a733c9a5ce07c71b93f073e6acda09bec7e400c91c2057c"
- revision 1
+ revision 2
```

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/4371f3dd14f7139ddb3bb3a86bd6dd6fc2c832c3 & https://github.com/Homebrew/homebrew/commit/aa8569002018bd956caf263aa522e3ecb8425d73. Thank you for your contributions to Homebrew @sscotth; we appreciate them! :smiley_cat:

**Pull request closed without merging**
