### PR TITLE
update consul-template to 0.11.1

### PR DESCRIPTION
**Pull request by grepnull**
updated to newest version of consul-template. The build scripts have
changed which required some changes to the formula.

### CODE REVIEW

**Comment by grepnull** [comment]
Let me know if there's anything else you need here. I'd really like to get this merged! Thanks!

**Comment by DomT4** [comment]
Why the need for so many less dependencies? Is there still no remote fetching happening during compile?

**Comment by grepnull** [comment]
The build script is grabbing all the dependencies it needs, it just needs gox to bootstrap.

**Comment by DomT4** [comment]
Is that a yes or a no on remote fetching not specified in the formula file, for clarity?

**Comment by grepnull** [comment]
Sorry, but I guess I don't really understand your question.

**Comment by grepnull** [comment]
I can re-add the resources if that helps. I simply don't really understand why they'd be needed or what you mean by "remote fetching happening during compile". I've only done a few homebrew updates and just getting my feet wet with Go as well.

If you could help me out with this merge, I'd really appreciate it. Thanks!

**Comment by dunn** [comment]
The Makefile is running `go get`: https://github.com/hashicorp/consul-template/blob/master/scripts/build.sh#L23-L24

We might have to run the `gox` command manually.

**Comment by grepnull** [comment]
@dunn, I don't think that's necessary. `make bin` is calling that `build.sh` script and so it is grabbing all the compile dependencies it needs.

I've been using this locally for the past week with no problem. The tests all pass in Travis here (and there's an actual real, albeit simple, check in the formula that uses the built binary).

I also tested by running this PR's template: 
```
brew install https://raw.githubusercontent.com/grepnull/homebrew/consul-template-0.11.1/Library/Formula/consul-template.rb
``` 
on another mac of mine that never even had Go installed and it installed Go and then built fine and passed the test.

As I understand Go, these are compile-time dependencies, not run-time dependencies so they shouldn't be needed to use the built binary.

If I'm mistaken in any of this, please let me know.

Thanks again.

**Comment by dunn** [comment]
We don't like letting build scripts download dependencies because it's a security risk (we can't verify the checksum) and we can't cache them, so if a build fails the user has to download them all again.

**Comment by grepnull** [comment]
Got it. I can put the dependencies back then, call `gox` and update the PR.

**Comment by dunn** [comment]
Thanks so much!

**Comment by grepnull** [comment]
Hopefully good to merge now... let me know if there are any other changes you want. Thanks!

**Comment by dunn** [comment]
Looks great, thanks so much! Merged in e648ed1b1a717a1e9dc8d85c5f4e533c656bf5d2.

**Pull request closed without merging**
