### PR TITLE
gtk+3: quartz relocation off by default

### PR DESCRIPTION
**Pull request by tschoonj**
introduced an option to activate it

### CODE REVIEW

**Comment by mikemcquaid** [comment]
What does this do?

**Comment by tschoonj** [comment]
This disables default quartz-relocation support, which should only be turned on when the goal is to put gtk and its dependencies in an app bundle. If not, then this option might actually break things, especially when the homebrew prefix is not /usr/local.

**Comment by mikemcquaid** [comment]
Maybe it's worth not even making it an option?

**Comment by tschoonj** [comment]
I guess for people who know what they are doing, this could actually turn out to be quite a useful option.

**Comment by mikemcquaid** [comment]
If that's you personally I'm happy to add this. Otherwise I suspect people who don't know what they are doing might try it out and break things.

**Comment by tschoonj** [comment]
I would indeed be a user of this option :-)

By the way: the same option is present in the `gtk+` formula.

**Comment by mikemcquaid** [comment]
:cool:

**Comment by mikemcquaid** [comment]
Thanks @tschoonj!

**Pull request closed without merging**
