### PR TITLE
libquicktime: use https url in a comment

### PR DESCRIPTION
**Pull request by vszakats**

### CODE REVIEW

**Comment by DomT4** [comment]
This is impressive attention to HTTPS-related detail.

Will merge, but will wait for Jenkins to get around to this so we can generate new bottles, including one for El Cap.

**Comment by vszakats** [comment]
Yes, I feel slightly bad about it since it creates churn, but couldn't help it. On the brighter side it's good for the stats:
```bash
( grep https:// * | wc -l ) && ( grep -E '(http|git|ftp|svn)://' * | wc -l )
```

**Comment by bfontaine** [comment]
@vszakats You can have stats using `brew irb` too, e.g.:

```
>> Formula.count { |f| f.homepage.start_with? "https://" } / Formula.count.to_f
=> 0.4668486739469579
```

If you want the core only:

```
>>> ff = Foruma.reject { |f| f.tap? }
>> ff.count { |f| f.homepage.start_with? "https://" } / ff.count.to_f
=> 0.4812538414259373
```

etc.

**Comment by vszakats** [comment]
Nice, I didn't know about this facility, thanks for the tip!
(found a formula problem in homebrew-apache with it)

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/6255e409f1a2ecf49414e7b9a9b1760231ba764e with new :baby_bottle:s. Thanks @vszakats! :smiley:

**Comment by vszakats** [comment]
Great :) Thank you so much @DomT4!

**Pull request closed without merging**
