### PR TITLE
install: don't warn if modified formulae don’t have bottles

### PR DESCRIPTION
**Pull request by bfontaine**
I also re-ordered the conditions to have the `file_modified?` check done last.

### CODE REVIEW

**Comment by dunn** [comment]
Thanks for picking this up, I've been having trouble nailing down the problem behaviors.  Would adding `!build_bottle?` to the conditions be redundant?

**Comment by mikemcquaid** [comment]
This is good but we also need to handle the bot's case somehow; even if it's just setting a stupid environment variable there to disable this check. Eventually I'd also like this to not get trigger if I e.g. checkout old versions of formulae.

**Comment by bfontaine** [comment]
@dunn the condition already has `!build_from_source?`, is it possible for `!build_from_source? && !build_bottle?` to be true?

**Comment by mikemcquaid** [comment]
Another failure case: shallow clones.

**Comment by DomT4** [comment]
Another niche failure case: local testing of `def pour_bottle` blocks.

```ruby
  bottle do
    sha256 "17ed246b275ce29226ea244eb46b91a5d79979368323dcbc4a143083291af84d" => :yosemite
  end

  def pour_bottle?
    return false unless which("python") == HOMEBREW_PREFIX/"bin/python"
    return false unless which("ruby") == HOMEBREW_PREFIX/"bin/ruby"
    return false unless Formula["perl"].installed?
  end
```

```
~> brew install -v vim
Warning: Formula file is modified!
Building from source because Library/Formula/vim.rb has local changes
To install from a bottle instead, run with --force-bottle
```

You can't pass `--force-bottle` in this situation because it installs the things necessary to fulfil the `pour_bottle` conditions, which means you never get the chance to test the `return false` conditions:

```
==> Installing dependencies for vim: perl
==> Installing vim dependency: perl
==> Downloading https://homebrew.bintray.com/bottles/perl-5.22.0.yosemite.bottle.tar.gz
```

**Pull request closed without merging**
