### PR TITLE
libmicrohttpd 0.9.47

### PR DESCRIPTION
**Pull request by wingyplus**

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Looks like the test is flaky and `brew uses --recursive libmicrohttpd` need their `revision`s added (`revision 1`) or incremented.

**Comment by wingyplus** [comment]
@mikemcquaid Thanks. I added.

**Comment by DomT4** [comment]
Sorry, not a revision to this formula but the ones that use it and are failing:

* libhttpserver
* ola

**Comment by wingyplus** [comment]
It seem `ola` build with old version of `libmicrohttpd`. When build with `--HEAD` it work fine.

**Comment by DomT4** [comment]
That would suggest we either need to backport fixes or wait here.

**Comment by apjanke** [comment]
No, just doing the revision bump in `ola` and `libhttpserver` should work. This might be just a communication issue.

The old `libmicrohttpd` version installed dylib version `libmicrohttpd.10.dylib`. This new one installs `libmicrohttpd.12.dylib`.  Rebuilding `ola` and `libhttpserver` from source after installing `libmicrohttpd` from this PR was enough to get it to work for me.

Before:
```
$ otool -L olad | grep micro
	/usr/local/lib/libmicrohttpd.10.dylib (compatibility version 43.0.0, current version 43.0.0)
```

After:
```
$ otool -L olad | grep micro
	/usr/local/opt/libmicrohttpd/lib/libmicrohttpd.12.dylib (compatibility version 48.0.0, current version 48.0.0)
[/usr/local on ⇄ pr-46911]
$ brew test ola
Testing ola
==> Using the sandbox
==> /usr/local/Cellar/ola/0.9.8/bin/ola_plugin_info
[/usr/local on ⇄ pr-46911]
$
```

Installing `ola` from `--HEAD` will have the side effect of building it from source (instead of pouring it from a bottle), and I think it's the building from source that matters, not the code changes between our current version and `HEAD`. 

That's what the revision bump in the dependent formulae is for; it'll force a recompile that picks up the newer dylib version. So, remove [this `revision` line from `libmicrohttpd`](https://github.com/wingyplus/homebrew/blob/666841bfd0e43f6e4d2b5188f288ae8b0e54cc88/Library/Formula/libmicrohttpd.rb#L7) and add `revision 1` lines to `ola.rb` and `libhttpserver`, as part of this PR.

**Comment by mikemcquaid** [comment]
> No, just doing the revision bump in ola and libhttpserver should work. This might be just a communication issue.

:+1:

**Comment by wingyplus** [comment]
Thanks, I will bump revision and send pr.

**Comment by mikemcquaid** [comment]
@wingyplus Sorry, can you bump their revisions inside this PR instead? Thanks!

**Comment by wingyplus** [comment]
@mikemcquaid I picked commit from closed pr to this branch.

Thanks.

**Comment by mikemcquaid** [comment]
@wingyplus Great, thanks. In case you're curious the reason for that is that we can verify the PR is working by the green build.

**Comment by wingyplus** [comment]
Thanks for your guide @mikemcquaid.

**Pull request closed without merging**
