### PR TITLE
guilt moved to the boneyard

### PR DESCRIPTION
**Pull request by bfontaine**
I’m not sure this is the right way to do this. The upstream homepage gives a 404 and I can’t find any version higher than `0.35` in a `tgz` format, only this Debian package. I did it anyway because the actual version doesn’t support `git` 2.x. This one works fine.

Should we move it to the boneyard instead?

### CODE REVIEW

**Comment by asparagui** [comment]
No dev since 2013, +1 on boneyard.

**Comment by mikemcquaid** [comment]
Yeh, let's boneyard :+1:

**Comment by bfontaine** [comment]
Thanks to both of you, I updated the PR.

**Comment by mikemcquaid** [comment]
Thanks @bfontaine!

**Pull request closed without merging**
