### PR TITLE
haskell-stack 1.0.4

### PR DESCRIPTION
**Pull request by superlukas**

### CODE REVIEW

**Comment by superlukas** [comment]
```
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20160220-10603-1e120ha.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Library/Homebrew -- /usr/local/Library/Homebrew/test.rb /usr/local/Library/Formula/haskell-stack.rb --verbose
==> /usr/local/Cellar/haskell-stack/1.0.4/bin/stack new test
Downloading template "new-template" to create project "test" in test/ ...
TlsExceptionHostPort (HandshakeFailed (Error_Packet_unexpected "Alert [(AlertLevel_Fatal,BadRecordMac)]" " expected: change cipher")) "raw.githubusercontent.com" 443
Error: haskell-stack: failed
Failed executing: /usr/local/Cellar/haskell-stack/1.0.4/bin/stack new test
/usr/local/Library/Homebrew/formula.rb:1483:in `block in system'
/usr/local/Library/Homebrew/formula.rb:1420:in `open'
/usr/local/Library/Homebrew/formula.rb:1420:in `system'
/usr/local/Library/Formula/haskell-stack.rb:25:in `block in <class:HaskellStack>'
/usr/local/Library/Homebrew/formula.rb:1329:in `block in run_test'
/usr/local/Library/Homebrew/extend/fileutils.rb:35:in `mktemp'
/usr/local/Library/Homebrew/formula.rb:1325:in `run_test'
/usr/local/Library/Homebrew/test.rb:28:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/usr/local/Library/Homebrew/test.rb:27:in `<main>'
```
Any ideas @borsboom? Quickly browsing through stack's issue tracker brought a couple of similar issues up.

**Comment by superlukas** [comment]
@BrewTestBot test this please

**Comment by superlukas** [comment]
Okay so apparently building a second time fixed the TLS issue. (I've deleted the at-reply to the brew test bot because I though I need to be a member of the homebrew org for it to work.) I'm now going to try to trigger a second Travis build by closing and reopening the PR.

Whether it works or not, I think it would be a good idea to change the test to something that doesn't require access to the internet (e.g., the canonical "does `stack --version` print something to stdout").

**Comment by borsboom** [comment]
I've seen the github.com error a couple of times on our CI system as well.  One of my to-dos for next week is to harden this a bit (e.g. by adding retries).  That said, `stack new test` isn't really a great test since it doesn't actually use much of Stack's core functionality (like building code).  `stack --version` probably makes more sense, unless we want to have it run the full test suite.

Regarding the timeout, it looks like it is building all the dependencies so it's not too surprising that it could time out sometimes.

**Comment by superlukas** [comment]
Hi there,

let's see what the homebrew team has to say about the timeouts. Maybe it's not a deal-breaker since the test-bot build succeeded. I was about to change the test but then I found a paragraph in the docs that said something along the lines of "despite its widespread use, `foo --version` is not a good test." (and if you want to add retries to stack anyway I guess there's no need to change it right now.)

Anyway, I hope we're lucky and this gets merged as is. Have a great weekend (and thanks for 1.0.4)!

**Comment by DomT4** [comment]
If you pass on the CI labeled "default", which you did the second time around, don't worry about Travis. Travis is still pretty experimental on our side.

The first CI failure on Jenkins was:
```
==> /usr/local/Cellar/haskell-stack/1.0.4/bin/stack new test
Downloading template "new-template" to create project "test" in test/ ...
TlsExceptionHostPort (HandshakeFailed (Error_Packet_unexpected "Alert [(AlertLevel_Fatal,BadRecordMac)]" " expected: change cipher")) "raw.githubusercontent.com" 443
Error: haskell-stack: failed
```
You probably just got unlucky there.

**Comment by superlukas** [comment]
> If you pass on the CI labeled "default", which you did the second time around, don't worry about Travis.

That's good to know, thanks!

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/4129ffd1a9d644b877e2a61f8ef82a93e06dd5df. Thank you for another contribution to Homebrew @superlukas! :smiley:

**Pull request closed without merging**
