### PR TITLE
Dependency.expand: ensure pop stack

### LINKED ISSUE #48834: Dependencies in other taps not tapped soon enough
This issue does not affect Homebrew core because it has no formula in core that depend on formula in other taps. This issue may affect formula in other taps, but I don't know of a real-world case.

The formula `rtorrent` depends on `autoconf` which on Linuxbrew depends on `homebrew/dupes/m4`.

`brew install rtorrent` fails with
```
Error: /home/linuxbrew/.linuxbrew/opt/m4 not present or broken
Please reinstall homebrew/dupes/m4. Sorry :(
```

However `brew tap homebrew/dupes && brew install rtorrent` succeeds. See below.

To recreate this issue solely for testing purpose, edit `autoconf` and add `depends_on "homebrew/dupes/m4"`, then `brew install rtorrent`.

#### Does not work
```
❯❯❯ brew install rtorrrent
==> Installing dependencies for rtorrent: automake, libtool, pkg-config, cppunit, makedepend, zlib, openssl, libtorrent
…
Error: /home/linuxbrew/.linuxbrew/opt/m4 not present or broken
Please reinstall homebrew/dupes/m4. Sorry :(
```

#### Works
```
❯❯❯ brew tap homebrew/dupes
❯❯❯ brew install rtorrent
==> Installing dependencies for rtorrent: homebrew/dupes/m4, autoconf, automake, libtool, pkg-config, cppunit, makedepend, zlib, openssl, libtorrent
```

Originally reported here: https://github.com/Linuxbrew/linuxbrew/issues/742

### PR DESCRIPTION
**Pull request by xu-cheng**
During the dependencies expansion, there may be errors (e.g. FormulaUnavaiableError).
As result, some deps will be left behind in the stack and interfere afterwards
dependencies expansion.

So let's ensure stack clean for each expansions.

Fixes #48834.

cc @sjackman

### CODE REVIEW

**Comment by mistydemeo** [comment]
:+1:

**Comment by mistydemeo** [comment]
Do you think it's feasible to add a unit test for this specific case?

**Comment by xu-cheng** [comment]
> Do you think it's feasible to add a unit test for this specific case?

Done.

**Comment by UniqMartin** [comment]
Nice find! :+1:

**Pull request closed without merging**
