### PR TITLE
cgrep 6.5.10

### PR DESCRIPTION
**Pull request by bfontaine**

### CODE REVIEW

**Comment by bfontaine** [comment]
Weird that it fails on the CI but works locally.

**Comment by dunn** [comment]
¯\(´o｀)/¯ #42701

**Comment by bfontaine** [comment]
:see_no_evil:

**Comment by bfontaine** [comment]
I’m trying a few different things; adding `--debug=3` to `cgrep` in the test prints some info on my machine but only a dot on Travis :confused: :
```
==> /usr/local/Cellar/cgrep/6.5.8/bin/cgrep --debug=3 --count --comment test /private/tmp/cgrep20151029-9296-17495us/test.rb
.
```

**Comment by xu-cheng** [comment]
You can try using `Kernel.system` to show the log.

**Comment by bfontaine** [comment]
Thanks @xu-cheng

**Comment by bfontaine** [comment]
Interesting. On my machine it gives:
```
pattern   : ["test"]
files     : ["/private/tmp/cgrep20151029-78197-b638c4/test.rb"]
```

While on Travis the file becomes a pattern:
```
pattern   : ["test","/private/tmp/cgrep20151029-9297-19pj6d9/test.rb"]
files     : []
```

**Comment by apjanke** [comment]
Same here.

```
Cgrep 6.5.10!
options   : Options {file = "", word_match = False, prefix_match = False, suffix_match = False, edit_dist = False, regex_posix = False, regex_pcre = False, ignore_case = False, code = False, comment = True, literal = False, semantic = False, identifier = False, keyword = False, directive = False, header = False, number = False, string = False, char = False, oper = False, no_filename = False, no_linenumber = False, lang = [], lang_maps = False, force_language = Nothing, multiline = 1, recursive = False, prune_dir = [], deference_recursive = False, invert_match = False, max_count = 9223372036854775807, count = True, show_match = False, color = False, format = Nothing, json = False, xml = False, jobs = 1, cores = 0, chunk = 16, asynch = False, debug = 3, no_turbo = False, others = ["test","/private/tmp/cgrep20151111-16773-dupbnw/test.rb"]}
languages : []
pattern   : ["test"]
files     : ["/private/tmp/cgrep20151111-16773-dupbnw/test.rb"]
isTermIn  : True
isTermOut : True
strategy  : running Boyer-Moore search on /private/tmp/cgrep20151111-16773-dupbnw/test.rb...
tokens    : [(7,"test")]
tokens'   : [(7,"test")]
```

The "options" line seems exactly the same. Both locally and CI, it's `others = ["test","/private/tmp/cgrep20151111-16773-dupbnw/test.rb"]` for those last two arguments.

Possible clue: my local:

```
isTermIn  : True
isTermOut : True
```

CI log:
```
isTermIn  : False
isTermOut : False
```

Maybe a non-tty `stdin` (b/c it's connected to the CI infrastructure?) makes it assume that the search target is `stdin`, and changes the interpretation of the command line?

I can induce what looks like the same error locally by redirecting stdin.

```
$ echo foo | brew test cgrep
Testing cgrep
==> Using the sandbox
Cgrep 6.5.10!
options   : Options {file = "", word_match = False, prefix_match = False, suffix_match = False, edit_dist = False, regex_posix = False, regex_pcre = False, ignore_case = False, code = False, comment = True, literal = False, semantic = False, identifier = False, keyword = False, directive = False, header = False, number = False, string = False, char = False, oper = False, no_filename = False, no_linenumber = False, lang = [], lang_maps = False, force_language = Nothing, multiline = 1, recursive = False, prune_dir = [], deference_recursive = False, invert_match = False, max_count = 9223372036854775807, count = True, show_match = False, color = False, format = Nothing, json = False, xml = False, jobs = 1, cores = 0, chunk = 16, asynch = False, debug = 3, no_turbo = False, others = ["test","/private/tmp/cgrep20151111-16884-1q1o2in/test.rb"]}
languages : []
pattern   : ["test","/private/tmp/cgrep20151111-16884-1q1o2in/test.rb"]
files     : []
isTermIn  : False
isTermOut : True
strategy  : running Boyer-Moore search on <STDIN>...
==> /usr/local/Cellar/cgrep/6.5.10/bin/cgrep --count --comment test /private/tmp/cgrep20151111-16884-1q1o2in/test.rb
Error: cgrep: failed
Expected /:1/ to match "".
[✘ /usr/local on ⇄ pr-45423]
$
```

This sounds like an upstream arg parsing bug or design flaw, IMHO.

Here's a snippet from the source that seems consistent. (`Main.hs` lines 216-218.) I dunno; I can't read Haskell much.

```
    -- load files to parse:

    let paths = getFilePaths (not $ null (file opts)) isTermIn (others opts)
```

**Comment by dunn** [comment]
Maybe the `script -q /dev/null` trick will work here?

**Comment by bfontaine** [comment]
Indeed! :clap:

**Comment by dunn** [comment]
:ok_woman:

**Pull request closed without merging**
