### PR TITLE
coq: audit fixes

### PR DESCRIPTION
**Pull request by nijikon**

### CODE REVIEW

**Comment by DomT4** [comment]
Be a little careful on filing more than a few of these when the build queue is quite extensive already. The CI can be grumpy :smile:.

**Comment by nijikon** [comment]
No worries, when it fails for a weird reason, a rebase on top of master and push with force which starts the build again :)

**Comment by DomT4** [comment]
It's less that it might fail in a weird way and more that the CI doesn't handle heavy loads entirely elegantly :wink:. We've done a lot of work to improve how it handles these things in the last 6 months but it still keeps me up at night sometimes.

**Comment by DomT4** [comment]
In this case since we don't need bottles updated we can punt it off the Jenkins build queue and just use the passing Travis build as justification to merge.

Merged in https://github.com/Homebrew/homebrew/commit/819cc84787e0ad489a8dc2895da0dfe34aa92e52. Thanks @nijikon!

**Pull request closed without merging**
