### PR TITLE
juju 1.23

### PR DESCRIPTION
**Pull request by dunn**
(the Go build process remains a continual source of delight)

### CODE REVIEW

**Comment by mikemcquaid** [comment]
A failing checkout it seems :sob:: http://bot.brew.sh/job/Homebrew%20Pull%20Requests/25037/version=yosemite/testReport/junit/brew-test-bot/yosemite/fetch_juju/

**Comment by dunn** [comment]
Weird, that one doesn't cause problems locally:
```
==> Cloning lp:gnuflag
/usr/local/opt/bazaar/bin/bzr checkout --lightweight lp:gnuflag /Library/Caches/Homebrew/juju--launchpad.net-gnuflag--bzr
Not checking SSL certificate for xmlrpc.launchpad.net.
You have not informed bzr of your Launchpad ID, and you must do this to
write to Launchpad or access private data.  See "bzr help launchpad-login".
```

**Comment by mikemcquaid** [comment]
Trying it again.

**Comment by dunn** [comment]
Oh, does it need `depends_on "bazaar" => :build`?

**Comment by mikemcquaid** [comment]
Oh, yes, maybe.

**Comment by dunn** [comment]
Looks like it's not actually finding bazaar, and so instead of `bzr checkout` it's trying to just run `checkout` as a command:
```
==> Cloning lp:gnuflag
==> Retrying download
==> Cloning lp:gnuflag
Error: Failed to download resource "juju--launchpad.net-gnuflag"
Failure while executing:  checkout --lightweight lp:gnuflag /Library/Caches/Homebrew/juju--launchpad.net-gnuflag--bzr
```

**Comment by dunn** [comment]
Actually looks like 1.23 is still devel, so this can sit for a bit <https://jujucharms.com/docs/stable/reference-releases>

**Comment by sinzui** [comment]
The Juju docs site can be stale by 12 hours. I made the official release of 1.23.2 a few hours ago at
    https://launchpad.net/juju-core/+milestone/1.23.2

Could Lp be failing to provide the code. We test releases similar to the homebrew process and we know that Lp fails about every two weeks.

**Comment by dunn** [comment]
Oh, great!

No, it's not a LP problem; I build juju locally without a problem.  Something's causing the test-bot to return an empty string when it looks for the path to `bzr`, so instead of running `/usr/local/opt/bazaar/bin/bzr checkout --lightweight lp:gnuflag` it tries to run `checkout --lightweight lp:gnuflag`, which of course fails.

**Comment by sinzui** [comment]
There might be something we can for to the formula to tell go build that it should not fetch dependencies. Ubuntu requires the Juju release tarball to contain every dependency since it is statically built. Ubuntu builds juju without network access. The ubuntu package script untars the file, sets the GOPATH to the new dir, then calls go install to make each command.

Can we instruct Go to not do a "go get" after the tarfile is unpacked?

**Comment by dunn** [comment]
Yeah, if you package all the dependencies yourself that saves them from having to be vendored by the formula.  Should I go ahead and close this PR in favor of yours?

**Comment by sinzui** [comment]
Yes please close it. When Juju is in devel and even proposed, it doesn't "just work". Users need to configure juju to work with the streams we seed in the clouds. I never make a pull request until I have verified ever clouds has the agents the juju client needs.

**Comment by sinzui** [comment]
Think this alternate means of building juju tries to do to much, and it can break users who upgrade before the version is in the "released" streams that the Juju Release team seeds in the clouds.

But I can explain how anyone can make a tarfile just like I do for Juju QA and Release team. We use this script to make a tarfile that only contains the required deps and removes non-free or undistributable data that some of the dependencies contain. The tarfile contains everything needed to build without a network.
http://bazaar.launchpad.net/~sinzui/juju-release-tools/trunk/view/head:/make-release-tarball.bash

The only binaries that OSX needs (and can run) are juju and juju-metadata. The backup and restore binaries are vestigial. The native "backups" feature in the juju binary is superior. The jujud only runs on Linux (and in a limited way on Windows)

Juju QA tests the OS X binaries made from the tarfile we build. When we first announce a release, the agents required to bootstrap and upgrade in the clouds are only available in the "proposed" streams. An unsuspecting user who get the client will be surprised that "juju bootstrap" no longer works. The user needs to reconfigure all the envs with "agent-stream: proposed". I create the branch for homebrew at this time, but I do not create the pull request until the agents in all the clouds are copied from "proposed" streams to "released". I make the Pull request about few minutes later.

We could have a devel stanza in the formula for the devel and proposed juju. I think we want to show a message though that explains the extra step need to use the non-default streams.

**Comment by dunn** [comment]
Thanks for the detailed explanation!

I'm not a maintainer, but the level of control you need over the distribution makes me wonder if a [Homebrew tap](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/brew-tap.md) wouldn't be a better release channel than the Homebrew core repository.

**Pull request closed without merging**
