### PR TITLE
GEOS 3.5.0

### PR DESCRIPTION
**Pull request by gfairchild**
This PR is identical to https://github.com/Homebrew/homebrew/pull/44157. @nijikon has been unresponsive, and I'd really like this merged, so I'm submitting my own PR.

### CODE REVIEW

**Comment by nijikon** [comment]
Nice! Thanks for this, I did not have time recently to follow up on opened issues. <3

**Comment by gfairchild** [comment]
My pleasure! :D

**Comment by gfairchild** [comment]
Hm, I don't quite follow why this build failed. It's totally up to date with the master.

**Comment by mikemcquaid** [comment]
@gfairchild Squash commits by running `brew update; git checkout $YOUR_BRANCH; git rebase --interactive origin/master` and then mark each commit other than the first as `squash` or `fixup` then `git push -f`. Thanks!

**Comment by gfairchild** [comment]
Ok, I believe we're good to go...well, once it passes the tests.

**Comment by gfairchild** [comment]
Hm, there seems to be an error when building spatialite-gui. A quick search shows that this is related to #44003. I'm not quite sure how to fix this yet.

**Comment by gfairchild** [comment]
I believe that once #46375 is accepted, this PR will build properly.

**Comment by DomT4** [comment]
@BrewTestBot test this please

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/cac54f8a48c814f3b51f5363981b23bdd214222a & https://github.com/Homebrew/homebrew/commit/9b110ca971c2553b7ed292622e61250168719fad. 

Thank you for the determined work here @gfairchild & @nijikon :heart:.

Minor future note - We prefer individual commits per formula changed, but will take this as-is.

**Pull request closed without merging**
