### PR TITLE
Feature: `brew ls --taps`

### LINKED ISSUE #29586: request: brew ls for taps
`brew ls` shows me all installed formulae. I'd very much like to see the installed formulae from a certain tap, e.g. `homebrew/python`. Maybe `brew ls --tapped <tapname>`?

### PR DESCRIPTION
**Pull request by davidfokkema**
This option to the `ls` command shows the source of the installed formulae. If a formula is included in the core repository, just print the name.  If the formula is installed from a tapped repository, print user/repo/name:
```
$ brew ls|grep numpy
numpy
$ brew ls --taps|grep numpy
homebrew/python/numpy
```
Sufficiently fixes #29586.

### CODE REVIEW

**Comment by bfontaine** [comment]
This PR needs rebasing.

I’m personally :+1: on the feature but I find the flag confusing: maybe use `--full-name` instead? cc @Homebrew/owners

**Comment by davidfokkema** [comment]
Or ``--show-tap``?

**Comment by mikemcquaid** [comment]
Or perhaps this should maybe even by the default CC @xu-cheng

**Comment by davidfokkema** [comment]
I like that even better.

**Comment by bfontaine** [comment]
Yes it’d be great to have this by default.

**Comment by xu-cheng** [comment]
I prefer to keep original behavior. The reasons are (a) old `ls` based implementation can accept custom flags which it's useful and we don't want to break existing tools rely on that. (b) `ls` approach is fast and robust since it doesn't require to load actually formula. And this benefits shell complete. 

As for implementing `--full-name`, it should be easy using current API, like this:

```ruby
...
elsif ARGV.include? "--full-name"
  puts_columns Formula.installed.map(&:full_name)
...
```

**Comment by davidfokkema** [comment]
@xu-cheng, it is already implemented using a flag. Right now it's ``--taps``, but it can be anything. I'm ok with keeping the original behavior; your reasoning is sound.

**Comment by DomT4** [comment]
`brew uses` already kicks out full formula names (Tap included) so I think there's justification for equalling that out here, even if behind an option.

**Comment by chdiza** [comment]
Please leave this behind an option, and not the default behavior of `brew list`.

The output will be harder to read, because inclusion of the tap name will force there to be fewer columns, which means each column will be "taller", which means it's less likely that the output of `brew ls` will fit on one standard terminal window without scrolling.

**Pull request closed without merging**
