### PR TITLE
mdds 1.0.0

### PR DESCRIPTION
**Pull request by luzpaz**
"multi-dimensional data structure and indexing algorithm"
a dependency for Document Liberation lib libetonyek 1.3 and possible future libs as well.

### CODE REVIEW

**Comment by DomT4** [comment]
Test is dying.

```
==> /usr/bin/clang++ test.cpp -o test
test.cpp:1:10: fatal error: 'mdds/flat_segment_tree.hpp' file not found
#include <mdds/flat_segment_tree.hpp>
         ^
1 error generated.
Error: mdds: failed
```

**Comment by luzpaz** [comment]
It's working on locally for me. Confused as to why?!

**Comment by luzpaz** [comment]
Here are the gist logs: https://gist.github.com/luzpaz/cafed019ac971a17173d

**Comment by luzpaz** [comment]
I'm on it.. getting it fixed

**Comment by luzpaz** [comment]
How do i tell the formula to compile with c++11, like this ? 

```
  def install
    ENV.cxx11
    system "./configure", "--prefix=#{prefix}"
    system "make", "install"
  end
```

**Comment by dunn** [comment]
You may also need `needs :cxx11` above the install block.

**Comment by bfontaine** [comment]
Thank you for your contribution to Homebrew @luzpaz; we appreciate it! :tada:

**Pull request closed without merging**
