### PR TITLE
Update chisel formula to 1.3.0

### PR DESCRIPTION
**Pull request by kastiglione**
This updates the formula for [chisel](https://github.com/facebook/chisel) to 1.3.0. Release info can be found here: https://github.com/facebook/chisel/releases/tag/1.3.0

thanks!

### CODE REVIEW

**Comment by DomT4** [comment]
The checksum is off apparently?

```
==> Downloading https://github.com/facebook/chisel/archive/1.3.0.tar.gz
==> Downloading from https://codeload.github.com/facebook/chisel/tar.gz/1.3.0
Warning: Formula reports different SHA256: 7feed485053a2ee1a245be6f6fa43bda9565f936f36aa63309467812135e515b
Downloaded to: /Library/Caches/Homebrew/chisel-1.3.0.tar.gz
SHA1: 7b20c9d755b5a9c63bc8493b8499ef5471ceca2f
SHA256: 6e8f64a1cb48b0937a98a7d62dc0c6de8cea5afa0040088b426d166e188a6f59
```

**Comment by kastiglione** [comment]
Thanks @DomT4 I'll double check that.

**Comment by bfontaine** [comment]
Thank you for your contribution to Homebrew @kastiglione; we appreciate it! :tada: 

One tiny note for the future: the preferred commit message format for version bumps is “`chisel 1.3.0`”, i.e. “`<name> <version>`”.

**Comment by kastiglione** [comment]
Thanks @bfontaine I'll be sure to do that next time!

**Pull request closed without merging**
