### PR TITLE
Use 'formulae' instead of 'brews' everywhere

### PR DESCRIPTION
**Pull request by bfontaine**
From what I understand, “brews” is the old way to speak of “formulae”. This PR only changes the wording in text and comments, not in the code (I didn’t rename `outdated_brews` nor `check_for_linked_keg_only_brews`. Should I?).

### CODE REVIEW

**Comment by xu-cheng** [comment]
:+1:

**Comment by DomT4** [comment]
WFM :+1:. Think formulae is a better term than ` brews ` generally, happy to see the latter flushed out a little more.

**Comment by mikemcquaid** [comment]
CC @Homebrew/owners. I believe technically the formulae is just the description of how to install a package rather than the package itself.

**Comment by DomT4** [comment]
Heh, I think this goes back a little to the discussion a while back on the 'fun' lexicon. I long-presumed installed packages were ` kegs `, as ` keg_only ` meant sealed into its prefix, so consequently ` keg ` = the installed package.

Formulae = The packages name/etc, what you type to audit/install/fetch the package.
Keg = The installed package/directory.
Brews = ...?

**Comment by bfontaine** [comment]
This “brews vs formulae” thing confuses me, for example one doctor check says:

> You may wish to `brew unlink` these brews

But the manpage only mentions formulae:

```
unlink formula
              Remove symlinks for formula from the Homebrew prefix. This can be
              useful for temporarily disabling a formula: brew  unlink  foo  &&
              commands && brew link foo.
```

**Comment by jacknagel** [comment]
>I believe technically the formulae is just the description of how to install a package rather than the package itself.

Yeah, exactly.

So a formula can't really be outdated, or unlinked, etc.

I'm not defending "brew" as a term, but we already had a [pretty long discussion](https://github.com/Homebrew/homebrew/pull/32473) about how figuring out the correctly terminology to use is not easy.

**Comment by mikemcquaid** [comment]
My concern is that we let "perfect" be the enemy of "good" (or even "better") here. I realise I went too far in that PR but I think it would be good if we could perhaps define these terms somewhere and then be consistent. If we don't wish to rename then it would be good to at least differentiate between e.g. formulae and kegs/packages correctly.

**Comment by chdiza** [comment]
Please at least use "formulas" instead of "formulae".  Both are correct English; the former is more natural.  I doubt anyone here says "stadia" instead of "stadiums", e.g, or "datum" for one piece of information.

**Comment by bfontaine** [comment]
> but I think it would be good if we could perhaps define these terms somewhere and then be consistent

Yes that would be really helpful.

**Comment by mikemcquaid** [comment]
> Please at least use "formulas" instead of "formulae". Both are correct English; the former is more natural. I doubt anyone here says "stadia" instead of "stadiums", e.g, or "datum" for one piece of information.

British versus American English here and it was created by another Brit so should stay as formulae.

**Comment by asparagui** [comment]
I like formulae, fwiw.

**Comment by tdsmith** [comment]
I say stadia and datum and enjoy "formulæ" but I am generally regarded as hopeless.

This was probably mentioned before but the Homebrew lexicon is partially defined here: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md#terminology---homebrew-speak

Fleshing it out and making it more visible would be nice.

**Comment by tdsmith** [comment]
Closing this, then, I think? Let me know if you'd rather I did something else. Thanks!

**Pull request closed without merging**
