### PR TITLE
xonsh

### PR DESCRIPTION
**Pull request by internaught**
xonsh 0.1.5 (new formula)

### CODE REVIEW

**Comment by asparagui** [comment]
Committing to master means you're going to have merge issues every time you `brew update` in the future.  I would suggest that you:

1) save xonsh.rb to a local file
2) reset your homebrew back to before where you added xonsh (`git reset --hard SHA1_OF_AN_OLDER_COMMIT`) (can be found with gitx/gitk)
3) update your homebrew to match master (`brew update`)
4) copy xonsh back to library/formula
5) make a new branch   `git checkout -b xonsh_submit`
6) add/commit xonsh
7) push the xonsh_submit branch to github, and open a pull request with that

**Comment by internaught** [comment]
I'm not sure why it's giving me a 403 error when I try that:

[ realeyes@psyche /usr/local ]$ cp Library/Formula/xonsh.rb ~/devel/brew/
[ realeyes@psyche /usr/local ]$ git reset --hard 9cfa753b24514d491c5ad01ac7ad08d9b7f8e281
HEAD is now at 9cfa753 git 2.4.0
[ realeyes@psyche /usr/local ]$ brew update
Updated Homebrew from 9cfa753b to 74b1031a.
==> New Formulae
kotlin-compiler
==> Updated Formulae
arangodb	 dpkg		  keybase	   metaproxy	    muparser	     ruby-build	      utimer
awscli		 emscripten	  libmspub	   minimodem	    mytop	     safe-rm	      wine
bullet		 git		  lua		   minised	    pazpar2	     saltstack	      xml-security-c
couchdb		 gpgme		  lua51		   mitmproxy	    primesieve	     sqlitebrowser    zebra
cryptol		 hbase		  megatools	   mksh		    protobuf	     tbb
deheader	 jython		  memcached	   mkvalidator	    purescript	     tcpflow
[ realeyes@psyche /usr/local ]$ cp ~/devel/brew/xonsh.rb Library/Formula/xonsh.rb
[ realeyes@psyche /usr/local ]$ git checkout -b xonsh_submit
Switched to a new branch 'xonsh_submit'
[ realeyes@psyche /usr/local ]$ git add Library/Formula/xonsh.rb
[ realeyes@psyche /usr/local ]$ git commit -m "xonsh 0.1.5 (new formula)"
[xonsh_submit 4c3b27d] xonsh 0.1.5 (new formula)
 1 file changed, 38 insertions(+)
 create mode 100644 Library/Formula/xonsh.rb
[ realeyes@psyche /usr/local ]$ git push
fatal: The current branch xonsh_submit has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin xonsh_submit

[ realeyes@psyche /usr/local ]$ git push --set-upstream origin xonsh_submit
Username for 'https://github.com': internaught
Password for 'https://internaught@github.com':
remote: Permission to Homebrew/homebrew.git denied to internaught.
fatal: unable to access 'https://github.com/Homebrew/homebrew/': The requested URL returned error: 403

**Comment by xu-cheng** [comment]
You need to run command like this:
```
git remote add YOUR_USERNAME https://github.com/YOUR_USERNAME/homebrew.git
git push --set-upstream YOUR_USERNAME YOUR_BRANCH_NAME
```
For more details, you can read this [document](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged).

**Comment by asparagui** [comment]
What @xu-cheng said, you're trying to push to homebrew/your_branch_name, when you should be pushing to internaught/your_branch_name and then making the PR from there.

**Comment by internaught** [comment]
Going to close this request and start over...

**Pull request closed without merging**
