### PR TITLE
inspircd: fix bottle inreplace

### PR DESCRIPTION
**Pull request by DomT4**
Will fix the CI error caused by https://github.com/Homebrew/homebrew/commit/b75af6b13036b6208f4448e6bdc424bbc2bbdc53

The username in the bottles is still `brew`, which causes the error.

### CODE REVIEW

**Comment by xu-cheng** [comment]
Thanks. However, I also filed a test build http://bot.brew.sh/job/Homebrew%20Testing/867/, maybe I should cancel it?

**Comment by DomT4** [comment]
Na, yours is further ahead than mine. Feel free to pull your bottles when ready.

I submitted a PR here to tidy up the few style nits as well, but I can just commit those without updated bottle later.

**Comment by xu-cheng** [comment]
> Feel free to pull your bottles when ready.

The honor is yours. I have no computer access until tomorrow. Reply from my iPad now. :wink:

**Comment by DomT4** [comment]
You mean you don't keep a copy of the Homebrew repo on your iPad? :wink:.

Will pull one set or another of the new bottles relatively soon then, Thanks!

**Pull request closed without merging**
