### PR TITLE
internetarchive 0.9.8

### PR DESCRIPTION
**Pull request by dunn**

### CODE REVIEW

**Comment by dunn** [comment]
¯\\(´o｀)/¯ 
```
libev/ev.c:935:42: error: '_Noreturn' keyword must precede function declarator
  ecb_inline void ecb_unreachable (void) ecb_noreturn;
                                         ^~~~~~~~~~~~
  _Noreturn 
libev/ev.c:738:26: note: expanded from macro 'ecb_noreturn'
  #define ecb_noreturn   _Noreturn
                         ^
1 error generated.

**Comment by DomT4** [comment]
You may find https://github.com/Homebrew/homebrew/pull/42852 interesting.

**Comment by dunn** [comment]
Aha, thanks!

**Comment by geoff-codes** [comment]
Merged into #42852.

**Comment by dunn** [comment]
Thanks!

**Pull request closed without merging**
