### PR TITLE
config: show all installed JDK

### PR DESCRIPTION
**Pull request by xu-cheng**
Per https://github.com/Homebrew/homebrew/issues/43568#issuecomment-138808054

### CODE REVIEW

**Comment by mikemcquaid** [comment]
:+1:

**Comment by mikemcquaid** [comment]
Although it'd be good to ensure the first in the PATH is the first displayed maybe?

**Comment by xu-cheng** [comment]
The question is do we want to show all JDK. (I'd like to considering there are formulae requiring specific java version)

Otherwise we can do `/usr/libexec/java_home --exec java -version` to get JDK version.

**Comment by mikemcquaid** [comment]
Showing all versions sounds good :+1:

**Comment by xu-cheng** [comment]
> Although it'd be good to ensure the first in the PATH is the first displayed maybe?

It seems it is this case already. It's ordered by version which will be the same order to determine java_home. c.f. http://stackoverflow.com/a/20994919

**Comment by mikemcquaid** [comment]
:+1: :shipit:

**Pull request closed without merging**
