### PR TITLE
Gems,-Eggs-and-Perl-Modules: rework Perl doc; add plenv

### PR DESCRIPTION
**Pull request by dolmen**
More perl doc. Add link to [`plenv`](//tokuhirom/plenv/).

### CODE REVIEW

**Comment by mikemcquaid** [comment]
I'd rather we just referenced `local::lib` and `plenv` by name rather than adding more instructions here but  I don't mind if other @Homebrew/owners prefer the new version.

**Comment by DomT4** [comment]
Closing here as there hasn't been other maintainer interest. Thanks for the submission though, we appreciate the help keeping on top of the documentation!

**Comment by dolmen** [comment]
There has not been either strong points against this patch.
> Closing here as there hasn't been other maintainer interest.
In fact, I suspect than none of @Homebrew/owners are interested in Perl. Is it really a good reason to ignore doc patches on this subject?

**Comment by mikemcquaid** [comment]
@dolmen If you can address my comments I'm happy to merge this but there was no response to my comment for several months.

**Comment by DomT4** [comment]
Ping?

**Comment by bfontaine** [comment]
Ping?

**Comment by dolmen** [comment]
As I'm not a Mac user, and I'm not a Perl beginner either, I have absolutely no interest in working further on this patch.

**Pull request closed without merging**
