### PR TITLE
dub 0.9.24

### PR DESCRIPTION
**Pull request by John-Colvin**
latest stable

### CODE REVIEW

**Comment by John-Colvin** [comment]
Ok, so this didn't get merged as it was, so now the latest version is released, here it is

**Comment by DomT4** [comment]
Is this supposed to be `dub 0.9.24-rc4` or `dub 0.9.24`? The commit hints that `dub 0.9.24` is stable but the URL is `dub 0.9.24-rc4`?

**Comment by John-Colvin** [comment]
woops, fixed now

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/c3220e9b6cd908939a92a3ab71e932271a344ccf. Thank you @John-Colvin!

**Pull request closed without merging**
