### PR TITLE
Use exec instead of system in fork block

### PR DESCRIPTION
**Pull request by guoxiao**
Use exec instead of system to avoid forking, because we need to kill it via pid afterwards.

### CODE REVIEW

**Comment by dunn** [comment]
The test failures are from a resource that's 404ing. I think I added it, so I'll try to find a replacement.

**Comment by xu-cheng** [comment]
This PR need to be rebase.

**Comment by guoxiao** [comment]
@xu-cheng done.

**Comment by xu-cheng** [comment]
Thanks for the pull request! 🎉 Homebrew depends on contributions from community members like you and we're grateful for your support.

**Pull request closed without merging**
