### PR TITLE
AWS cli 1.7.25

### PR DESCRIPTION
**Pull request by darend**
Updating AWS CLI to 1.7.25

### CODE REVIEW

**Comment by ms-ati** [comment]
Hey just so I can do this correctly next time rather than asking: how do you get the full set of python dependencies to update here? Do you manually look at all the setup.py files starting at the top, or some easier way?

**Comment by darend** [comment]
Truthfully, I installed via pip and looked at the set of dependencies.

**Comment by ms-ati** [comment]
Ah! Well, I supposed I could do that. But might defeat the point ;) Thanks for doing it for the rest of us.

**Comment by tdsmith** [comment]
[homebrew-pypi-poet](https://github.com/tdsmith/homebrew-pypi-poet) can automate the "see what pip does" process a little.

**Comment by tdsmith** [comment]
Thanks for the pull request! 🎉 Homebrew depends on contributions from community members like you and we're grateful for your support.

**Comment by ms-ati** [comment]
@tdsmith that's fascinating. I wonder if it would make sense to wrap homebrew-pypi-poet in a virtualized environment and a script, so that it became truly a one-click affair to update homebrew? Or even automated?

**Pull request closed without merging**
