### PR TITLE
leiningen 2.5.3

### PR DESCRIPTION
**Pull request by brunchboy**
Upgrade Leiningen to the latest 2.5.3. Fixes a regression with respect to GPG integration.

### CODE REVIEW

**Comment by brunchboy** [comment]
I’m baffled as to why the Travis CI build failed; I just tried building it locally again and all seems well?

**Comment by DomT4** [comment]
It's not the build that's failing. It's `brew test --verbose --sandbox leiningen` that's failing.

**Comment by brunchboy** [comment]
How can I recreate that locally? When I try running that I get:
```
brew test --verbose --sandbox leiningen
Error: Testing requires the latest version of leiningen
```

**Comment by brunchboy** [comment]
And when I said “all seems well”, I meant that I am able to run Leiningen and it it is the correct version.

**Comment by DomT4** [comment]
You're seeing `Error: Testing requires the latest version of leiningen` because you need to install the version you want to test.

>  I meant that I am able to run Leiningen and it it is the correct version.

Outside of `brew test` this would be expected, as we don't sandbox what people do with the software after it has been installed; we only sandbox the install and test on our side.

**Comment by brunchboy** [comment]
But I did install that version, by pointing at the formula in my fork. At this point I am stuck as far as how to proceed, I’ve tried to follow the steps in the online documentation, and this has always worked fine with previous times I tried to update the formula.

Can you point me at instructions about how I can install things in a way the sandbox environment can test them so I can see what it is unhappy about? Or shall I close this pull request and stop using Homebrew to deliver Leiningen? The fix in 2.5.3 is important enough that I need it now (I was running a prerelease version with the fix until shortly after 2.5.2 was released). But I would rather figure out how we can get Homebrew to deliver 2.5.3 to everyone who would benefit from it.

**Comment by brunchboy** [comment]
When I make sure to run the version of brew in my fork, the test seems to succeed:

```
homebrew git:(update-leiningen-to-2-5-3) 
bin/brew install /Users/jim/git/homebrew/Library/Formula/leiningen.rb 
==> Downloading https://homebrew.bintray.com/bottles/leiningen-2.5.3.yosemite.bo

curl: (22) The requested URL returned error: 401 Unauthorized
Error: Failed to download resource "leiningen"
Download failed: https://homebrew.bintray.com/bottles/leiningen-2.5.3.yosemite.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://github.com/technomancy/leiningen/archive/2.5.3.tar.gz
Already downloaded: /Library/Caches/Homebrew/leiningen-2.5.3.tar.gz
==> Downloading https://github.com/technomancy/leiningen/releases/download/2.5.3
Already downloaded: /Library/Caches/Homebrew/leiningen--jar-2.5.3.zip
==> Caveats
Dependencies will be installed to:
  $HOME/.m2/repository
To play around with Clojure run `lein repl` or `lein help`.

Bash completion has been installed to:
  /Users/jim/git/homebrew/etc/bash_completion.d

zsh completion has been installed to:
  /Users/jim/git/homebrew/share/zsh/site-functions
==> Summary
🍺  /Users/jim/git/homebrew/Cellar/leiningen/2.5.3: 8 files, 15M, built in 2 seconds
➜ homebrew git:(update-leiningen-to-2-5-3) 
bin/brew test /Users/jim/git/homebrew/Library/Formula/leiningen.rb 
Testing leiningen
==> /Users/jim/git/homebrew/Cellar/leiningen/2.5.3/bin/lein test
➜
```

**Comment by mikemcquaid** [comment]
You need to `brew edit leiningen` such that it matches the version you want to test.

**Comment by mikemcquaid** [comment]
or `brew test --verbose --sandbox your/fork/leiningen`

**Comment by brunchboy** [comment]
Ah, thank you! That `--sandbox` was the piece I was missing. Using it;

```
➜ homebrew git:(update-leiningen-to-2-5-3) 
brew test --verbose --sandbox ~/git/homebrew/Library/Formula/leiningen.rb 
Testing leiningen
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20150923-15699-1abltjn.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Library/Homebrew -- /usr/local/Library/Homebrew/test.rb /Users/jim/git/homebrew/Library/Formula/leiningen.rb --verbose --sandbox
==> /usr/local/Cellar/leiningen/2.5.3/bin/lein test

lein test brew-test.core-test

Ran 1 tests containing 1 assertions.
0 failures, 0 errors.
```

So perhaps something was unstable when Travis tried to run this before?

**Comment by DomT4** [comment]
It still fails here. It'll pass locally if you already have the directories it's trying to create present:

```
==> /usr/local/Cellar/leiningen/2.5.3/bin/lein test
Could not transfer artifact org.clojure:clojure:pom:1.5.1 from/to central (https://repo1.maven.org/maven2/): Specified destination directory cannot be created: /Users/Dominyk/.m2/repository/org/clojure/clojure/1.5.1
Could not transfer artifact org.clojure:tools.nrepl:pom:0.2.10 from/to central (https://repo1.maven.org/maven2/): Specified destination directory cannot be created: /Users/Dominyk/.m2/repository/org/clojure/tools.nrepl/0.2.10
Could not transfer artifact clojure-complete:clojure-complete:pom:0.2.3 from/to clojars (https://clojars.org/repo/): Specified destination directory cannot be created: /Users/Dominyk/.m2/repository/clojure-complete/clojure-complete/0.2.3
This could be due to a typo in :dependencies or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
Tests failed.
==> Sandbox log
Sep 23 20:03:28 sandboxd[62351]: java(68619) deny file-write-create /Users/Dominyk/.oracle_jre_usage
Sep 23 20:03:28 sandboxd[62351]: java(68619) deny file-write-create /Users/Dominyk/.oracle_jre_usage
Sep 23 20:03:30 sandboxd[62351]: java(68619) deny file-write-create /Users/Dominyk/.m2
```

And so on.

**Comment by brunchboy** [comment]
Well, that looks like something in the sandbox is denying the ability to download and install Maven repository objects, which would certainly make Leiningen unable to work. But that would surely have been an issue with all former Leiningen releases as well. What has changed?

**Comment by DomT4** [comment]
> What has changed?

We turned the sandbox feature on for the CI.

This fixes it:

```diff
test do
+ ENV["_JAVA_OPTIONS"] = "-Duser.home=#{ENV["HOME"]}"
```

**Comment by brunchboy** [comment]
Ah! That explains much, thanks. Does that get added to the `test do` section of the recipe, or somewhere else? Is this something you need me to add to the pull request, or can you take it from here?

**Comment by DomT4** [comment]
Aye. The first line inside the `test do` block. If you could make the change & push here just to double check it works on the CI as well as sandboxed locally, that'd be great. After that it should pass (and keep passing in future) and we can merge.

**Comment by brunchboy** [comment]
OK, thanks, now I can see that you had posted basically a context diff for me, I didn’t recognize what you meant by the `test do` line at the top of your comment when I first saw it. (It's been a while since I worked with Ruby. :) )

Having made the change you described, the test pulled the Maven components to /private/tmp for me, and passed. So I’ve pushed that, and am eagerly waiting for Travis to try it.

**Comment by brunchboy** [comment]
Well, shoot, this time it failed trying to test `netpbm` which has nothing to do with my change, and then was killed for taking too long. Any idea what is up now?

**Comment by mikemcquaid** [comment]
You can ignore Travis and wait for Jenkins (`default`) instead.

**Comment by DomT4** [comment]
I fixed the `netpbm` audit failure it was complaining about in https://github.com/Homebrew/homebrew/commit/ba89810498feff7708f12e83004d5e1636ced167.

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
