### PR TITLE
libb2: pass strict audit

### PR DESCRIPTION
**Pull request by vszakats**

### CODE REVIEW

**Comment by DomT4** [comment]
We don't really do style/checksum changes only :cry:

**Comment by vszakats** [comment]
Protecting a formula implementing a secure hash with a less secure hash looked odd, hence my update ;)

**Comment by vszakats** [comment]
Just found this article from @sneves &ndash; author of the very source code included in this formula &ndash;:
[SHA-1 Considered Harmful Today](https://eden.dei.uc.pt/~sneves/sha1.html)

**Comment by bfontaine** [comment]
@DomT4 We don’t do style-only but I think we accept sha1→sha256 -only changes. I got a lot of PRs merged just for that.

**Comment by vszakats** [comment]
I got a hash update accepted just recently as well. It was in a formula where a single resource (of several) was overlooked and stuck at `sha1`. I understand that purely upping `sha1` to `sha256` with no other reason is not encouraged though.

[ it would be _nice_ to up them all in batch, like `desc` was added :o - it also wouldn't pollute the `brew update` output after c010cc8a8cadfe2e29f541570b70e62b6d735fb9 - but I may be banging open doors here, seeing the efforts done in https://github.com/Homebrew/homebrew/issues/40392 ]

**Comment by vszakats** [comment]
As an aside, I contacted the author team via e-mail about an argument check typo/bug in one of the reference implementation.

If their team decide to release a new version just for that, we could do a version bump. I'm somewhat sceptic though, because the reference code is continued to be updated [here](https://github.com/BLAKE2/BLAKE2), with none of those updates retrofitted into the official download `url` as of yet. We'll see.

**Comment by DomT4** [comment]
>  author of the very source code included in this formula: SHA-1 Considered Harmful Today

I'm aware SHA1 isn't great. I wouldn't have pushed the bottle change many months ago otherwise, but to date at least Mike and Xu have been reluctant to merge in checksum only changes.

Can one of @Homebrew/owners weigh in on this? Are we :+1: / :-1: on checksum-only changes?

**Comment by vszakats** [comment]
Should this be a hard-rule? I understand that a landslide of hash-only updates are something not encouraged due to the load it'd put on maintainers, but is there anything fundamentally wrong (or else) with it to deny committing them in cases where it could make sense? (to recap, here we're protecting a superior hash - BLAKE2 - with an inferior one - SHA1 -, which just doesn't make much sense from a pure security POV, even if we assume that it likely won't cause any harm in practice)

**Comment by DomT4** [comment]
There's likely to be a broader decision on this soon, in regards to the future of SHA1 in Homebrew's core. Please wait on that.

**Comment by vszakats** [comment]
Okay 👍

**Comment by DomT4** [comment]
Have :rocket: this in https://github.com/Homebrew/homebrew/commit/f3a06bba5640a2413b81f4df8577b16efb249768. We'll make a fuller decision relatively soon.

**Comment by vszakats** [comment]
Thank you @DomT4, looking forward for the decision.

**Pull request closed without merging**
