### PR TITLE
wget: add metalink/gpgme support

### PR DESCRIPTION
**Pull request by DomT4**
Had a Twitter request from upstream, as well as from antbryan.

### CODE REVIEW

**Comment by antbryan** [comment]
aha, thank you sir!

it was the

````
  depends_on "pkg-config" => :build
````
that I didn't have, that was messing me up. thanks a bunch & have a good one. :)

**Comment by DomT4** [comment]
Yeah, turns out the only way `wget` wants to detect `libmetalink` is via `pkg-config`. Since it tries to use `pkg-config` for the build regardless, making it an unconditional build dependency was the simplest way to resolve that.

All seems to work locally from testing. Apologies for the delay on the reply to you - I've been moving Macs which didn't go as smoothly as hoped, heh.

**Comment by antbryan** [comment]
is that worth contacting upstream about? (do wget's other dependencies behave that way, or are they detected another way?)

oh, please don't apologize, I appreciate the help!

**Comment by DomT4** [comment]
You *can* pass direct paths to `wget` for some other dependencies; it accepts `--with-libssl-prefix` and `--with-gpgme-prefix`. Looks like the rest are either searched for by `pkg-config` or searched for in default locations.

I'm not quite sure whether they've moving towards or away from being able to pass direct paths to dependencies prefix, but if upstream are interested being able to pass a direct path rather than throwing out to `pkg-config` would be an upside.

**Pull request closed without merging**
