### PR TITLE
dos2unix 7.2.3

### PR DESCRIPTION
**Pull request by nijikon**

### CODE REVIEW

**Comment by DomT4** [comment]
Need to kill off the devel block:

```
Error: 1 problem in 1 formula
dos2unix:
 * devel version 7.2.3-beta1 is older than stable version 7.2.3
```

**Comment by dunn** [comment]
Better yet, update the devel version as well, to 7.3-beta3.

**Comment by DomT4** [comment]
^ :+1:

**Comment by xu-cheng** [comment]
Thanks for the pull request! 🎉 Homebrew depends on contributions from community members like you and we're grateful for your support.

**Pull request closed without merging**
