### PR TITLE
git-annex 5.20150731

### PR DESCRIPTION
**Pull request by carlmod**
Separate make to generate man pages is no longer needed.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Failing to build on 10.8/9.

**Comment by carlmod** [comment]
Seems that the relevant lines in the logs for mavericks are:

    fatal error:
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: can't write to output file (No space left on device)

Any tip on how to deal with low space?

**Comment by mikemcquaid** [comment]
Restarted the job.

**Comment by dunn** [comment]
Merged in 9d551a9794688a141cdc172f0f852c55cf4bfec5, thanks again!

**Pull request closed without merging**
