### PR TITLE
open-mpi: SSL/TLS URLs

### PR DESCRIPTION
**Pull request by vszakats**

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Mind cleaning up `brew audit --strict` here too?

**Comment by vszakats** [comment]
There is a pending update on hold (reverted) that modernized, I opted not to ruin it. Should I proceed?

**Comment by mikemcquaid** [comment]
Yeh, ruin it.

**Comment by vszakats** [comment]
Updated.

**Comment by mikemcquaid** [comment]
Thansk again @vszakats!

**Pull request closed without merging**
