### PR TITLE
move more deprecated methods to compat folder

### PR DESCRIPTION
**Pull request by xu-cheng**

### CODE REVIEW

**Comment by mikemcquaid** [comment]
`Stdenv` should maybe be marked both private and deprecated. It is deprecated.

**Comment by mikemcquaid** [comment]
Otherwise :+1:

**Comment by xu-cheng** [comment]
> Stdenv should maybe be marked both private and deprecated. It is deprecated.

Isn't still using heavily in `test`?

**Comment by mikemcquaid** [comment]
Yeh, it should be deprecated for non-test usage.

**Comment by xu-cheng** [comment]
Currently it's only used in test while it's tagged as private. I don't think we need to worry the wrong use case. Also, it feels weird to me to deprecate codes we are still actively using.

**Comment by DomT4** [comment]
>  Also, it feels weird to me to deprecate codes we are still actively using.

```ruby
# deprecated... soon... hopefully
# private
```
:wink:

**Comment by xu-cheng** [comment]
Thanks for advice. However, in current context, we are unlikely to deprecate `Stdenv`. If I recall correctly, we deliberately want to test the formula in `Stdenv` to best simulate user env.

**Comment by DomT4** [comment]
Well, from Mike's wording above, `stdenv` is already deprecated in *most* aspects?

Given all the problems with `stdenv` I'm happy enough seeing it tagged as deprecated with the eventual idea that we iron out enough `superenv` bugs to have everything using that, even if `stdenv` sticks around exclusively for testing formulae.

**Comment by xu-cheng** [comment]
> the eventual idea that we iron out enough superenv bugs to have everything using that, even if stdenv sticks around exclusively for testing formulae.

This is already the case now. I don't see there is any problem in current `Stdenv/Superenv` use case. 

On the contrary, tagging it as deprecate can be quite misleading as it feels like we will completely remove `Stdenv` code eventually. As you can see in this PR, I'm moving all of *deprecate* codes into `compat` folder and offer option to use Homebrew without loading any deprecate code. 

Overall, what I want to express is deprecate has unique semantically meaning. And we shouldn't missive it.

**Comment by mikemcquaid** [comment]
> On the contrary, tagging it as deprecate can be quite misleading as it feels like we will completely remove Stdenv code eventually.

We should probably do that. Instead of using `Stdenv` we should be just shelling out in test.

**Comment by DomT4** [comment]
> This is already the case now.

Well, apart from the formula we've allowed to keep `:std`? There's some pretty major exceptions in there.

**Comment by xu-cheng** [comment]
> We should probably do that. Instead of using Stdenv we should be just shelling out in test.

Good idea. I think we can still keep Stdenv but remove all compiling related codes. so Stdenv will be a basic utility extend from ruby's `ENV`.

Added the note to reflect current discussion in PR. Let me know whether there is anything need to be changed before merging it.

**Comment by mikemcquaid** [comment]
> Good idea. I think we can still keep Stdenv but remove all compiling related codes. so Stdenv will be a basic utility extend from ruby's ENV.

I'd rather introduce a new class and change the name, honestly.

**Comment by xu-cheng** [comment]
> I'd rather introduce a new class and change the name, honestly.

Anyhow that should belong to future PR.

**Comment by mikemcquaid** [comment]
:ok: :+1:

**Pull request closed without merging**
