### PR TITLE
poppler 0.34.0

### PR DESCRIPTION
**Pull request by nijikon**

### CODE REVIEW

**Comment by bfontaine** [comment]
Sorry, there’s already a PR for poppler 0.34.0 here: #37280.

**Comment by nijikon** [comment]
@bfontaine I saw that but thought that we can squeeze this before that one is finished.

**Comment by bfontaine** [comment]
We have a few formulae depending on Poppler and the 0.31.0 update broke some of them, this is why #37280 has been staying for a long time. Most of the issues are solved now, we’re still waiting for pdf2htmlex to update and it’ll be merged.

**Comment by nijikon** [comment]
@bfontaine Crystal clear :)

**Pull request closed without merging**
