### PR TITLE
SourceKitten 0.4.3

### PR DESCRIPTION
**Pull request by jpsim**
Thanks!

### CODE REVIEW

**Comment by mistydemeo** [comment]
Looks like the build is failing on 10.10.

**Comment by jpsim** [comment]
Seems to fail with the following error:

```
cp: directory /usr/local/Cellar/sourcekitten/0.4.2/bin does not exist
```

Could this failure be unrelated to this formula?

**Comment by jpsim** [comment]
Nevermind, the problem is with this formula. I found the culprit and will be updating the PR with a new tag including the fix.

**Comment by mistydemeo** [comment]
Thanks!

**Pull request closed without merging**
