### PR TITLE
glew 1.13.0

### PR DESCRIPTION
**Pull request by xpicox**
Updated the link to the latest version of glew following the guidelines.

### CODE REVIEW

**Comment by dunn** [comment]
The test for glew itself and two of its dependencies are failing since we're running them in a sandbox now and they're trying to write outside it: http://bot.brew.sh/job/Homebrew%20Pull%20Requests/31775/

Would you mind seeing if you can update the tests, too? Thanks!

**Comment by xpicox** [comment]
How can I emulate your sandbox on my computer?

**Comment by dunn** [comment]
Add the `--sandbox` flag when testing (`brew test -v --sandbox glew`), or set the environmental variable `HOMEBREW_SANDBOX` to `1`.

**Comment by xpicox** [comment]
The sandbox.test.log is empty, does it mean that the test wasn't trying to write outside the sandbox
?

**Comment by dunn** [comment]
Not sure. Does the test fail locally, and if so what is the output of the `brew test`?

**Comment by xpicox** [comment]
The output is:
Testing glew
==> /usr/local/Cellar/glew/1.13.0/bin/glewinfo

**Comment by xpicox** [comment]
On your sandbox the glewinfo test was failing because was unable to create an OpenGL context.

**Comment by DomT4** [comment]
@BrewTestBot test this please

**Comment by xu-cheng** [comment]
I think the test fails because the headless env rather than sandbox. Rerun it now. If it's sandbox to blame,   it should show something in logs.

**Comment by mikemcquaid** [comment]
@xpicox Can you try to replace the test with a simpler one that doesn't use an OpenGL context? Thanks!

**Comment by bfontaine** [comment]
Ping?

**Comment by xpicox** [comment]
An OpenGL context is required for this library. It would be nice if the test would give us more details about the failure, but i'm not the maintainer of the library. Moreover, on my machine i can't reproduce the error.

**Comment by dunn** [comment]
This seems to work as a test, but it would mean an X11 dependency:
```
  test do
    (testpath/"test.c").write <<-EOS.undent
      #include <GL/glew.h>
      #include <GL/glut.h>

      int main(int argc, char** argv) {
        glutInit(&argc, argv);
        glutCreateWindow("GLEW Test");
        GLenum err = glewInit();
        if (GLEW_OK != err) {
          return 1;
        }
        return 0;
      }
    EOS
    system ENV.cc, "-I/opt/X11/include", "-L/opt/X11/lib",
           "-lglew", "-lglut", testpath/"test.c", "-o", "test"
    system "./test"
  end
```

**Comment by mikemcquaid** [comment]
@xpicox Could you try to rebase this on `master`? Thanks!

**Pull request closed without merging**
