### PR TITLE
libodbc++: boneyard

### PR DESCRIPTION
**Pull request by ilovezfs**
Fixes "error: No ODBC driver manager configured."

### CODE REVIEW

**Comment by ilovezfs** [comment]
@DomT4 A boneyard-formula-pr command would be handy :)

**Comment by DomT4** [comment]
@ilovezfs Probably best to glance nicely in Mike's direction :smile:. He's less on the fence about providing automated commands; my experience has been somewhat soured by people submitted automated PRs and then not tracking them for feedback/issues, heh.

**Comment by ilovezfs** [comment]
@DomT4 Yeah it should be a pretty straightforward extension to bump-formula-pr now that he's shown the way! But I hear you. Automating a bunch of git commands is probably somewhat of an anti-pattern, but in the case of boneyarding it should be literally the same thing every time.

**Comment by mikemcquaid** [comment]
:+1: to boneyard.

**Comment by ilovezfs** [comment]
@DomT4 PR transformed into :skull: Cf. Homebrew/homebrew-boneyard#99

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/e1c8965ca9ec7d3f23c1d01c5655e2eb20c5fd0b. Thanks @ilovezfs!

**Pull request closed without merging**
