### PR TITLE
influxdb v0.10.0-beta2 (devel)

### PR DESCRIPTION
**Pull request by fxstein**

### CODE REVIEW

**Comment by apjanke** [comment]
Merged. Thank you for your contribution to Homebrew!

For future reference, PRs should be made from a branch in your repo, not from its `master`. Doing PRs from `master` makes them difficult to work with if they stay open long or if you wanted to do multiple PRs.

**Comment by fxstein** [comment]
Thank you for the feedback. Will do on future PRs.

**Comment by DomT4** [comment]
Another tiny nit for the future:

The syntax for commit messages should also be
```
influxdb 0.10.0-beta2 (devel)
```
In this case. It makes the tree kind of tricky to read when we differ from that radically.

**Comment by fxstein** [comment]
Will do. Thanks for taking the time to sharing the feedback!

**Pull request closed without merging**
