### PR TITLE
Make warnings yellow (previously red)

### PR DESCRIPTION
**Pull request by radeksimko**
Similar to https://github.com/caskroom/homebrew-cask/pull/12067

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Makes sense to me but other @Homebrew/owners may have thoughts.

**Comment by bfontaine** [comment]
Yes that makes sense.

**Comment by DomT4** [comment]
No objections. Helps create a difference between *"This could be a problem"* and *"This is a problem"* which is something we've seen confusing people before.

**Comment by xu-cheng** [comment]
:+1:

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/681b438398f028eaf00c644bc4a8df64435a937a. Thanks @radeksimko!

**Pull request closed without merging**
