### PR TITLE
jenkins 1.635

### PR DESCRIPTION
**Pull request by asaph**

### CODE REVIEW

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/55458372c0c2c2a42e20d508188640bf48ebfa58. Thanks once more @asaph! :smiley:

**Comment by asaph** [comment]
Thanks @DomT4. It seems updating the jenkins formula in Homebrew has become part of my Monday routine. It makes me think I should automate it. (Don't worry. I won't :smiley:).

**Comment by DomT4** [comment]
We do have some automated PRs. As long as people respond if there are issues we don't have any huge objection to contributor automation :wink:

**Comment by asaph** [comment]
@DomT4 Well now I *have to* automate it. :wink:

**Pull request closed without merging**
