### PR TITLE
libgit2 0.22.0

### PR DESCRIPTION
**Pull request by DomT4**
Version bump, fixed the now unrecognised don’t build tests option.

The API has been broken here, and other packages that use libgit2 now can’t find the correct dylibs, so updates to those will follow in this PR.

Closes #35954.

### CODE REVIEW

**Comment by DomT4** [comment]
Updated here as per comments in #36082.

**Comment by mikemcquaid** [comment]
Thanks @DomT4!

**Comment by mikemcquaid** [comment]
The `gitfs` test is failing but otherwise looks good: http://bot.brew.sh/job/Homebrew%20Pull%20Requests/20663/version=mavericks/testReport/junit/brew-test-bot/mavericks/test_gitfs/

**Comment by DomT4** [comment]
Ah, yeah, silly mistake. I forgot to include the other half of the ` PYTHONPATH ` necessary for the test to pass. Fixing now.

**Comment by DomT4** [comment]
Should pass now.

**Pull request closed without merging**
