### PR TITLE
Derrick 0.3 (new formula)

### PR DESCRIPTION
**Pull request by rieck**
Formula for Derrick, a simple network stream recorder based on libnids

### CODE REVIEW

**Comment by mikemcquaid** [comment]
This is maybe a little too niche for us; we generally frown on author-submitted projects unless they are really notable.

**Comment by rieck** [comment]
Okay, is there any tap for network related tools?

**Comment by mikemcquaid** [comment]
You could create your own tap?

**Comment by rieck** [comment]
An own tap sounds like overkill for a single formula. I was hoping that there is something similar to `homebrew-science` for network analysis.

**Comment by mikemcquaid** [comment]
It makes it easier for you to distribute updates for your own project as users can just `brew install rieck/derrick/derrick` or similar.

**Pull request closed without merging**
