### PR TITLE
use more https links (in docs)

### PR DESCRIPTION
**Pull request by vszakats**

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Excuse the rude question but: you verified these all work, yeh? Thanks!

**Comment by DomT4** [comment]
All of these should be fine. The two that may cause trouble are ` StackExchange ` because although the main website is SSL/TLS secured, they roll mixed content all over their source code, which can cause some browsers to flag warnings.

The other is ` apache.org ` because Apache server their headers and borders over ` http ` which either breaks the SSL/TLS, or breaks the webpage and doesn't render entirely properly. IMO, We should probably hold off on ` apache ` until SSL/TLS doesn't make their website function in unexpected ways, but I have no qualms about SE going in.

**Comment by vszakats** [comment]
Yes, with the exception of obvious known ones, f.e. github.com / twitter.com / youtube.com / wikipedia which all support https.

stackoverflow.com still has no complete official https support, though the https links do work.

**Comment by vszakats** [comment]
@DomT4: stackoverflow: as you say.
apache.org is indeed broken, thanks for the note, I missed that one.

**Comment by vszakats** [comment]
Fixed the apache link, added some more minor updates. If no more issues come up, please consider this pull done.

**Comment by jacknagel** [comment]
The links in the man page need to be changed first in `Library/Homebrew/manpages/brew.1.md` and then `brew.1` regenerated using `brew man`.

After that, please squash to a single commit, thanks!

**Comment by vszakats** [comment]
Fixed the man page, but totally messed up the squash (it's my first time). I'll delete my fork and reapply all changes in a new pull.

**Comment by DomT4** [comment]
It looks like your PR was from ` Master ` into ` Master `? If so, you'll have an easier time rebasing from a branch, i.e. ` git checkout -b ssldoc `.

**Comment by vszakats** [comment]
I thought to be working in `patch-1` branch. Thanks for the tips, for now I just recreated this pull by reapplying the squashed patch (`git format-patch -1 bfd60b43b292320d3838da120d2465e618c1374d`), see https://github.com/Homebrew/homebrew/pull/35529

**Comment by DomT4** [comment]
Looks good, cheers :+1:

**Pull request closed without merging**
