### PR TITLE
8.2

### PR DESCRIPTION
**Pull request by hutchkintoot**
BaseX 8.2

### CODE REVIEW

**Comment by DomT4** [comment]
If you could bump the checksum to `sha256` instead of `sha1` that'd be awesome. Not mandatory though!

**Comment by hutchkintoot** [comment]
Is it ok if i switch to sha256 next version?

**Comment by DomT4** [comment]
Sure. As I said, not mandatory for existing formula, just nice to have.

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

For future reference the preferred commit message format for simple version updates is `basex 8.2`.

**Pull request closed without merging**
