### PR TITLE
mvnvm 1.0.7

### PR DESCRIPTION
**Pull request by furgin**
mvnvm upgrade to 1.0.7

### CODE REVIEW

**Comment by dunn** [comment]
http://bot.brew.sh/job/Homebrew%20Pull%20Requests/32874/version=yosemite/testReport/junit/brew-test-bot/yosemite/test_mvnvm/
```
[WARNING] Failed to create parent directories for tracking file /Users/brew/.m2/repository/org/apache/maven/plugins/maven-resources-plugin/2.6/maven-resources-plugin-2.6.pom.lastUpdated
```
We run the installation and test in a sandbox—we don't allow writing outside the formula's `prefix`.  Can a different directory location be specified?

**Comment by furgin** [comment]
Yeah I should be able to do that, at least for the tests.  How can I run these tests locally?

**Comment by furgin** [comment]
I can run the tests ok, but not sure how to set up the sandbox correctly.  It may still give me enough to fix it though.

**Comment by dunn** [comment]
You can use the sandbox locally with `brew test --sandbox mvnvm`; probably want to add the `--verbose` flag too to see all the details.

**Comment by furgin** [comment]
Thanks, I think I've got this working and will update the PR shortly.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/f3f147c294229ee491633a1a33f9dea68f948713. Thank you for your contribution to Homebrew; we appreciate it! :smiley_cat:

**Pull request closed without merging**
