### PR TITLE
Redis 3.0.0

### PR DESCRIPTION
**Pull request by plashchynski**
Redis 3.0.0

### CODE REVIEW

**Comment by leepa** [comment]
Should put 2.8.x into versions possibly?

**Comment by mikemcquaid** [comment]
@leepa Sounds good. Can you submit a PR there?

**Comment by mikemcquaid** [comment]
Regardless probably want this to sit for a little bit given how important it is for many people.

**Comment by leepa** [comment]
FYI Hombrew/homebrew-versions#746

**Comment by DomT4** [comment]
^ Merged in versions :+1:

**Comment by ilkkao** [comment]
3.0.0 has been out now two, maybe it's time to merge? Salvatore Sanfilippo takes quality seriously and there was a long beta/rc phase before the final 3.0.0 release.

**Comment by mikemcquaid** [comment]
Good call thanks @ilkkao!

**Pull request closed without merging**
