### PR TITLE
influxdb 0.11.0

### PR DESCRIPTION
**Pull request by gunnaraasen**
### All Submissions:

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew/pulls) for the same update/change?

### CODE REVIEW

**Comment by DomT4** [comment]
Test is trying to escape the sandbox:
```
2016/03/22 22:50:23 InfluxDB starting, version 0.11.0, branch 0.11, commit 1572060c6890f5c6f6e540155d99238aca8617e3
2016/03/22 22:50:23 Go version go1.6, GOMAXPROCS set to 4
2016/03/22 22:50:23 Using configuration at: /private/tmp/influxdb20160322-84355-2nbu5x/config.toml
[meta] 2016/03/22 22:50:23 Starting meta service
[meta] 2016/03/22 22:50:23 Listening on HTTP: [::]:8091
[metastore] 2016/03/22 22:50:23 Using data dir: /private/tmp/influxdb20160322-84355-2nbu5x/influxdb/meta
[metastore] 2016/03/22 22:50:23 Node at localhost:8088 [Follower]
[metastore] 2016/03/22 22:50:24 Node at localhost:8088 [Leader]. peers=[localhost:8088]
[store] 2016/03/22 22:50:24 Using data dir: /private/tmp/influxdb20160322-84355-2nbu5x/influxdb/data
[handoff] 2016/03/22 22:50:24 Starting hinted handoff service
[monitor] 2016/03/22 22:50:24 'hh' registered for diagnostics monitoring
[handoff] 2016/03/22 22:50:24 Using data dir: /Users/brew/.influxdb/hh
run: open server: open hinted handoff: mkdir all: mkdir /Users/brew/.influxdb: operation not permitted
```

**Comment by gunnaraasen** [comment]
Is `unless build.head?` supposed to work when running `brew test influxdb --HEAD`?

**Comment by DomT4** [comment]
Possibly not. I believe our official position is that we support stable/devel testing in `test do` but `HEAD` in general isn't worth the hassle because they often break freely.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/0d9f8d045f6a0f4fb9d4e418e08355c1aa93755e. Thanks again @gunnaraasen! :smiley:

**Comment by gunnaraasen** [comment]
Thanks @DomT4. Good to know `HEAD` is not tested.

**Pull request closed without merging**
