### PR TITLE
libgit2-glib 0.22.8

### PR DESCRIPTION
**Pull request by tschoonj**
version bump

### CODE REVIEW

**Comment by DomT4** [comment]
Can you bump `libgit2` in the same PR here please? The both need doing and one has a dep on the other so there's less room for things to go wrong if we do them together :smile_cat:

**Comment by tschoonj** [comment]
done! but there seems to be something very wrong with the buildbot...

**Comment by DomT4** [comment]
We're looking at this now. Will re-queue any builds necessary once we've ironed it out. Thanks!

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/d9fa71e53379ec379175540af2bddde3d27b6086 & https://github.com/Homebrew/homebrew/commit/70d232588fe131db0393342dc28be6f57617485d. Thanks @tschoonj!

**Pull request closed without merging**
