### PR TITLE
Improve `brew` script robustness

### PR DESCRIPTION
**Pull request by adrfer**
##### [Update script hashbang to a more robust version](https://github.com/Homebrew/homebrew/commit/4a745d10c247579abb10d1a0d2a819225f1a8c69)

Given the variety of operating systems and configurations, there's not any good certainty about where `bash` is installed. That's why this use the `env` program to find it, resulting in a bit more robust script. A great explanation via [Bash.academy](http://guide.bash.academy/02.commands.html).

##### [Update obsolete test expression syntax \[ to \[\[](https://github.com/Homebrew/homebrew/commit/4a745d10c247579abb10d1a0d2a819225f1a8c69)
`[[` is an improved version of `[`, and it's a keyword, not a program. Besides, it's easier to use, more powerful, and maintains consistency with other scripts in the repo such as [brew_bash_completion.sh](https://github.com/Homebrew/homebrew/blob/master/Library/Contributions/brew_bash_completion.sh). More details via [Bash Hacker](http://wiki.bash-hackers.org/scripting/obsolete).

### CODE REVIEW

**Comment by mikemcquaid** [comment]
> Given the large variety of operating systems and configurations

We don't support a large variety of operating systems and configurations, just OS X.

> [[ is an improved version of [, and it's a keyword, not a program. Besides, it's easier to use and more powerful.

We're not using any of these features that make it more powerful in these cases.

**Comment by adrfer** [comment]
Fair enough @mikemcquaid and thanks for your swift consideration.

Well, I thought it'd be nice to have these since we'll never know whether Apple will change where bash is currently installed of even provide and updated version in future releases that is not backwards compatible.

Anyways, even though these suggestions might be considered best practices in bash scripting, it could be seen as premature optimization as well.

**Comment by DomT4** [comment]
Odds on Apple providing an updated `bash` in future, at least a significantly updated one, are slim to none; the newer versions are GPLv3, which Apple refuses to touch with a bargepole.

**Comment by UniqMartin** [comment]
I agree that we don't have to worry about Apple updating `bash` (and even if, it will most likely not break compatibility). At this point it is probably more likely that Apple will remove `bash` completely, which would make the more portable `#!/bin/sh` shebang and sticking with the more restricted possibilities of a POSIX-compliant shell a good thing.

**Comment by mikemcquaid** [comment]
Passing on this as explained. Thanks for the PR anyway, I hope we'll accept another in future!

**Pull request closed without merging**
