### PR TITLE
nanomsg: upgrade to 0.6-beta

### PR DESCRIPTION
**Pull request by ianliu**
This pull request updates the nanomsg library URL to version 0.6-beta and its SHA256 sum

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Is there a stable version we can use?

**Comment by ianliu** [comment]
@mikemcquaid unfortunately no, the software is still in beta.

**Comment by DomT4** [comment]
Given we accepted this in the past I won't grumble too much about the `beta` tag, but it would be nice to enable man documentation & `make test` by default, unless the documentation is huge or the `make test` takes 5+ minutes. I'm pretty bleh about making people compile stuff from source just for manpages.

**Comment by mikemcquaid** [comment]
@DomT4 It's `cellar :any` so that seems like a win. Gonna pull this as-is for now, though.

**Comment by DomT4** [comment]
Alright, I'll chase you in with a follow-up PR.

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

For future reference the preferred commit message format for simple version updates is `nanomsg 0.6-beta`.

**Pull request closed without merging**
