### PR TITLE
datamash 1.0.6: Move to Homebrew/science

### PR DESCRIPTION
**Pull request by sjackman**
Change SHA1 to SHA256
Update test

### CODE REVIEW

**Comment by sjackman** [comment]
Should this formula be moved to Homebrew/science?

**Comment by mikemcquaid** [comment]
If you think it should and nothing depends on it I'm :+1:

**Comment by sjackman** [comment]
Sounds good to me. Would you like to merge this PR, then we'll move the formula in a second PR?

**Comment by sjackman** [comment]
I forget how to do a move, frankly. Do I simply open one PR here to delete the formula and a second PR at Homebrew-sci to add the formula?

**Comment by mikemcquaid** [comment]
Yep (and link them in each other).

**Comment by sjackman** [comment]
Done. See Homebrew/homebrew-science#2261

**Comment by DomT4** [comment]
Needs to be added to `tap_migrations.rb` as well, I'd presume.

**Comment by sjackman** [comment]
Thanks for the tip, Dominyk. Done.

**Comment by mikemcquaid** [comment]
Thanks @sjackman!

**Pull request closed without merging**
