### PR TITLE
boot2docker 1.7.0

### PR DESCRIPTION
**Pull request by amochtar**
Updated docker and boot2docker to 1.7.0

### CODE REVIEW

**Comment by DomT4** [comment]
Can you drop `docker` from this PR and leave `boot2docker`? That way I can merge #40867 and then merge this back-to-back.

**Comment by amochtar** [comment]
@DomT4 I've dropped the docker commit

**Comment by DomT4** [comment]
Will merge this in ~25 minutes.

**Comment by DomT4** [comment]
And merged in https://github.com/Homebrew/homebrew/commit/23e9f7c60e0583bbbb428d9cd161998d275a32ec. Thank you for your contribution to Homebrew, we appreciate it! :smiley_cat:

**Pull request closed without merging**
