### PR TITLE
Gradle: update to v2.10

### PR DESCRIPTION
**Pull request by psibre**

### CODE REVIEW

**Comment by DomT4** [comment]
Test is failing:
```
==> /usr/local/Cellar/gradle/2.10/bin/gradle --version

FAILURE: Build failed with an exception.

* What went wrong:
Failed to load native library 'libnative-platform.dylib' for Mac OS X x86_64.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Error: gradle: failed
<0> expected but was
<1>.
```

**Comment by psibre** [comment]
This might be related/identical to [this SO question](http://stackoverflow.com/q/34238782), although I have no idea why it's occurring now and not with [previous](46077) [PRs](45180)...

Maybe something random is going wrong with the CI environment, maybe the cache needs to be cleared.

Or maybe setting `GRADLE_USER_HOME` explicitly for the test may work.

**Comment by psibre** [comment]
OK, indeed [the logs](https://travis-ci.org/Homebrew/homebrew/jobs/98388365#L575-L576) confirm that the error is triggered by `/Users/travis/.gradle` not being writeable for the test process (which I suspect may be running under a different user).

**Comment by DomT4** [comment]
Oh. If it's a permission issue you might have some luck setting `ENV.java_cache` inside `test do` before the command is run. We do run the tests under sandboxing these days.

**Comment by psibre** [comment]
OK, now it passes like before, with only kafka failing, which is apparently normal.

@DomT4 should I `git revert f35bb0fee598d46ee953be24df3d9cfea5c62ad5` for good measure (i.e., remove the `--stacktrace` option again)?

**Comment by DomT4** [comment]
:+1:. You can if you wish to; otherwise I can pluck it out on merge and squash before push.

**Comment by psibre** [comment]
@DomT4 squash away! =) Thanks for your help!

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/10fbe95067b555df6bd41fbfe1108e4f7154bab1. Thank you for another contribution to Homebrew @psibre; we appreciate it! :santa: :christmas_tree:

**Pull request closed without merging**
