### PR TITLE
audit: enforce new https url style for gnome downloads

### PR DESCRIPTION
**Pull request by vszakats**
also delete extra closing parenthesis in two problem messages

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Thanks again @vszakats!

**Comment by jacknagel** [comment]
Was there a discussion about what URL to recommend? This is https, yes, but it redirects to an http mirror.

```
$ curl -LI https://download.gnome.org/sources/cogl/1.20/cogl-1.20.0.tar.xz
HTTP/1.1 302 Found
Date: Sun, 19 Apr 2015 16:42:37 GMT
Server: Apache/2.2.15 (Red Hat)
X-MirrorBrain-Mirror: mirror.umd.edu
X-MirrorBrain-Realm: country
Link: <http://download.gnome.org/sources/cogl/1.20/cogl-1.20.0.tar.xz.meta4>; rel=describedby; type="application/metalink4+xml"
Link: <http://mirror.umd.edu/gnome/sources/cogl/1.20/cogl-1.20.0.tar.xz>; rel=duplicate; pri=1; geo=us
Link: <http://ftp1.nluug.nl/windowing/gnome/sources/cogl/1.20/cogl-1.20.0.tar.xz>; rel=duplicate; pri=2; geo=nl
Link: <http://fr2.rpmfind.net/linux/gnome.org/sources/cogl/1.20/cogl-1.20.0.tar.xz>; rel=duplicate; pri=3; geo=fr
Link: <http://mirrors.ustc.edu.cn/gnome/sources/cogl/1.20/cogl-1.20.0.tar.xz>; rel=duplicate; pri=4; geo=cn
Link: <http://ftp.sunet.se/pub/X11/GNOME/sources/cogl/1.20/cogl-1.20.0.tar.xz>; rel=duplicate; pri=5; geo=se
Digest: MD5=WyiJcZTZ/3aldKlJPR9+4A==
Digest: SHA=RqC/yjDEQK1LansH7Xqj5kPVdAE=
Digest: SHA-256=cp41SVgp59Mfr6M1jke3Q7ohorCP+bbNKPt0wN6RGSs=
Location: http://mirror.umd.edu/gnome/sources/cogl/1.20/cogl-1.20.0.tar.xz
Content-Type: text/html; charset=iso-8859-1
Connection: close

HTTP/1.1 200 OK
Server: nginx/1.4.6 (Ubuntu)
Date: Sun, 19 Apr 2015 16:42:37 GMT
Content-Type: application/octet-stream
Content-Length: 1669620
Last-Modified: Mon, 23 Feb 2015 20:47:26 GMT
Connection: keep-alive
ETag: "54eb91de-1979f4"
Accept-Ranges: bytes
```

**Comment by DomT4** [comment]
> This is https, yes, but it redirects to an http mirror.

Similar situation to Sourceforge, and Apache `dyn`, to be fair. I hadn't written it into the audit yet because of this, but using ` https ` that redirects to ` http ` has precedence, for better or worse.

**Comment by jacknagel** [comment]
I think this gives the false impression that the download is happening over https when it isn't.

I would like there to be more discussion before making this a recommendation.

**Comment by jacknagel** [comment]
Reverted for now.

**Comment by vszakats** [comment]
Yes, it is a redirector, it's one step into the right direction IMO.

**Comment by vszakats** [comment]
There is at least one HTTPS mirror, so it is not necessarily useless, and GNOME may populate their list with more. It is also the exact same case with sourceforge.net URLs, and apache.org. I don't understand the revert :(

**Comment by jacknagel** [comment]
>It is also the exact same case with sourceforge.net URLs, and apache.org. 

I wish I had known that before we started changing everything.

If the download isn't actually happening over https, what is the point? It's just as insecure.

**Comment by vszakats** [comment]
That's the only point we _can_ control. It's up to the link to do the rest properly. So it's one step of the many to get right. Even with HTTPS mirrors we cannot control how the mirror is pulling the data from the uplink, so even that can be a "false" sense of security.

**Comment by DomT4** [comment]
Theoretically, it provides *some* minor protection. It makes it harder for someone's initial redirect to be nefariously thrown to another domain. But yes, the actual download and everything after the redirect is done over plaintext.

**Comment by jacknagel** [comment]
>I don't understand the revert :(

I would prefer that the process for large-scale changes allow more than two hours for review.

**Comment by vszakats** [comment]
Not necessarily plaintext, see their `https://www.mirrorservice.org/` mirror, which does do HTTPS. (I don't know if their redirect uses it, but the mirror for sure supports it)

**Comment by vszakats** [comment]
For someone minding these sorts of things, a network monitor like Little Snitch will show what is going on in the background, clearing any false assumptions about security.

**Comment by DomT4** [comment]
FWIW, If we're going to have a discussion about it, I'll throw in a general preference that we actually *show* the redirect. That would solve Jack's worries about misleading users, as well.

Something like this:

```ruby
brew install ccd2iso
Downloading https://downloads.sourceforge.net/project/ccd2iso/ccd2iso/ccd2iso-0.3/ccd2iso-0.3.tar.gz
Downloading http://netcologne.dl.sourceforge.net/project/ccd2iso/ccd2iso/ccd2iso-0.3/ccd2iso-0.3.tar.gz
```

**Comment by vszakats** [comment]
@DomT4 That would be very nice.

**Comment by jacknagel** [comment]
Unfortunately we don't have that type of control over the downloader.

To be clear, my primary issue is that the PR was merged too quickly without any discussion. I just want there to be a discussion where the consequences of making the change are weighed against the status quo. If we end up merging this, so be it. I'm trying to argue from the other side because nobody else has.

**Comment by mikemcquaid** [comment]
Apologies @jacknagel.

**Comment by vszakats** [comment]
Besides the https versus http issue, I think it is useful to steer urls to the new scheme, because it appears to be the canonical url scheme for `gnome.org` downloads (see https://www.gnome.org/getting-gnome/), as opposed to the obsolete `ftp.gnome.org` one currently used in formulae. They even link it to it explicitly via https protocol. `gnome.org` has a wildcard certificate for `*.gnome.org`, yet they didn't implement https support for the old `ftp.gnome.org` subdomain, but they did so for `download.gnome.org`. I considered these before submitting this PR.

**Comment by mikemcquaid** [comment]
Also, in terms of my take on this PR: I do personally think a https URL that redirects to http is more favourable as it'll likely be updated to https-only in future and not require updating then.

**Comment by vszakats** [comment]
@mikemcquaid It is my thinking as well.

**Comment by vszakats** [comment]
Some potentially relevant links:

Someone successfully requesting an _https_/http mirror to be added to the gnome mirror list:
https://www.mail-archive.com/gnome-infrastructure@gnome.org/msg05387.html

Message about gnome.org maintainers' intention with the new subdomain:
https://www.mail-archive.com/gnome-infrastructure%40gnome.org/msg05024.html

The way mirrors can sync:
https://wiki.gnome.org/Sysadmin/Mirrors

(unfortunately I can't find the list of mirrors, even though I remember seeing it today once already)

**Comment by DomT4** [comment]
> Unfortunately we don't have that type of control over the downloader.

That's a shame. `wget` is more verbose by default on redirects, but less verbose than ` curl `'s verbose option, but given it's not default on OS X no dice. We could always print a warning on SF, Apache and GNOME urls that the redirect is to plaintext? Don't know if you'd find that any less misleading.

Agree with Mike and Viktor on the ` https ` situation here though. Some extremely minor protection on the initial step, with the hope people make upstream mirrors SSL/TLS by default over time, is better than plaintext everywhere. Either option is likely to become the unspoken default for relevant formulae over time, and difficult to change en-mass later.

**Comment by vszakats** [comment]
There is a way to query `curl` about the effective URL:
```bash
curl "${url}" -s -L -I -o /dev/null -w '%{url_effective}'
echo "${url_effective}"
```

**Comment by DomT4** [comment]
Yeah, I looked at that. Sadly it seems to rapidly change, at least for SF:

```
curl https://downloads.sourceforge.net/project/ccd2iso/ccd2iso/ccd2iso-0.3/ccd2iso-0.3.tar.gz -s -L -I -o /dev/null -w '%{url_effective}'
```

Gets:

* http://netcologne.dl.sourceforge.net/project/ccd2iso/ccd2iso/ccd2iso-0.3/ccd2iso-0.3.tar.gz
* http://freefr.dl.sourceforge.net/project/ccd2iso/ccd2iso/ccd2iso-0.3/ccd2iso-0.3.tar.gz
* http://garr.dl.sourceforge.net/project/ccd2iso/ccd2iso/ccd2iso-0.3/ccd2iso-0.3.tar.gz
* http://freefr.dl.sourceforge.net/project/ccd2iso/ccd2iso/ccd2iso-0.3/ccd2iso-0.3.tar.gz
* http://garr.dl.sourceforge.net/project/ccd2iso/ccd2iso/ccd2iso-0.3/ccd2iso-0.3.tar.gz
* http://cznic.dl.sourceforge.net/project/ccd2iso/ccd2iso/ccd2iso-0.3/ccd2iso-0.3.tar.gz

That lack of consistency is probably an issue.

**Comment by vszakats** [comment]
It seems mirroring + load balancing. I can't see an issue with that if our point is just to show the user what is the actual download URL. In fact our point is to show the _protocol_, so it'd enough to display either http or https (or ftp), without the details of the mirror link.

**Comment by DomT4** [comment]
Welcome everyone's views on #38835.

**Pull request closed without merging**
