### PR TITLE
flow 0.15.0

### PR DESCRIPTION
**Pull request by gabelevi**

### CODE REVIEW

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/1ba8b27d6f3bcde03b076453dc55380b64ecae97. Thank you for your contribution to Homebrew; we appreciate it! :smiley_cat:

**Comment by bfontaine** [comment]
Hey @DomT4 I had this PR waiting in a tab but you went faster :smile:

**Comment by DomT4** [comment]
@bfontaine Sorry! :speak_no_evil:

**Comment by bfontaine** [comment]
@DomT4 No worries :+1:

**Comment by DomT4** [comment]
@bfontaine I changed my `Homebrew, we appreciate it!` to `Homebrew; we appreciate it!` message for you though :wink:

**Pull request closed without merging**
