### PR TITLE
Updating the sha256 to match the file.

### PR DESCRIPTION
**Pull request by onewheelskyward**

### CODE REVIEW

**Comment by DomT4** [comment]
Any idea why the SHA changed?

**Comment by onewheelskyward** [comment]
I'm not 100% sure, but according to github there were two separate 3.0.9 commits, the second of which handled copyright dates.  I tested the install and all seems well.

**Comment by DomT4** [comment]
Ah. Probably a repack then. If there's anyone upstream you can nudge just to check it was an intentional repack and not someone going rogue that'd be awesome.

**Comment by mikemcquaid** [comment]
@onewheelskyward Could you contact upstream and check they weren't hacked and, if they weren't, ask them not to do this in future?

**Comment by onewheelskyward** [comment]
Can do.

**Comment by onewheelskyward** [comment]
Contact made.

**Comment by onewheelskyward** [comment]
Joedog claims it never changed.

**Comment by mikemcquaid** [comment]
Worth telling them it has and in that case they may have been hacked.

**Comment by jacknagel** [comment]
headers say it was modified on Feb. 26:

```
$ curl -I http://download.joedog.org/siege/siege-3.0.9.tar.gz
HTTP/1.1 200 OK
Date: Sun, 22 Mar 2015 15:21:06 GMT
Server: Apache/2.4.6 (Red Hat) PHP/5.4.16
Last-Modified: Thu, 26 Feb 2015 20:35:53 GMT
ETag: "7a5d3-51003b2c1c9cf"
Accept-Ranges: bytes
Content-Length: 501203
Content-Type: application/x-gzip
```

we merged 3.0.9 at the end of January: e1188cc7cc44af89af4ecb729907e38cf4f68a26

**Comment by asparagui** [comment]
Getting the old sha256 here.  Closing.

**Pull request closed without merging**
