### PR TITLE
minimodem 0.22.1

### PR DESCRIPTION
**Pull request by nijikon**

### CODE REVIEW

**Comment by bfontaine** [comment]
Thank you @nijikon! :tada:

**Comment by DomT4** [comment]
@bfontaine I may have just accidentally stolen this from under you in https://github.com/Homebrew/homebrew/commit/d3a7fffaff1133a7a52dd081c4c39dd0d1505629. Sorry about that! :cry:

**Comment by bfontaine** [comment]
@DomT4 Yeah I pulled it at the same time but you pushed it first :wink:

**Comment by DomT4** [comment]
@bfontaine We have too active a maintainer team; three of us online trying to pull and push various PRs :grinning:

**Pull request closed without merging**
