### PR TITLE
ansible: update bundled python libraries.

### PR DESCRIPTION
**Pull request by pwnall**
This PR updates the bundled python eggs used by openstack / rackspace (resource stanzas generated with homebrew-pypi-poet).

In particular, shade's bugfixes are needed to be able to create images on OpenStack.

### CODE REVIEW

**Comment by tdsmith** [comment]
There's a bunch of major-version changes here; do you think things still work?

**Comment by pwnall** [comment]
I tested it with a pretty complex Ansible playbook that uses most of the os_ modules. I created images, networks, machines, security groups and volumes.

I haven't tested pyrax (for Rackspace), but the egg docs have a big warning that it's being deprecated in favor of the OpenStack API. So, I'd rather not hold back the OpenStack updates for a stale pyrax.

What do you think?

**Comment by tdsmith** [comment]
Works for me. I wish we had a more comprehensive way of testing this in CI or that there was an authoritative requirements.txt or something; let me know if you know of something. In the meantime, I'll close my eyes, cross my fingers, and hit merge. :p

Thanks very much for the PR!

**Comment by pwnall** [comment]
Thank you for the confidence!

I agree, it would be nice to be able to test this! Sadly, that requires an OpenStack cluster, which is not so easy to get a hold of. I have an account on trystack.org, but I don't have the resources to figure out how to protect the credentials for CI usage.

That being said, if someone else were to figure out the OpenStack situation, I'd be happy to try to write a playbook that tests out stuff.

**Pull request closed without merging**
