### PR TITLE
Add patch to fix scdaemon bug with yubikey.

### PR DESCRIPTION
**Pull request by metaspace**

### CODE REVIEW

**Comment by asparagui** [comment]
Has this been reported upstream/is there an issue to link to?

**Comment by DomT4** [comment]
Would definitely prefer Werner's OK on this before we merge it personally. GPGTools haven't always had a strong track record of upstreaming these things.

**Comment by metaspace** [comment]
Reported upstream here: https://bugs.gnupg.org/gnupg/issue1969
Reported in gpg-tools here: http://support.gpgtools.org/discussions/problems/28634-gpg-agent-stops-working-after-osx-upgrade-to-yosemite

**Comment by DomT4** [comment]
Werner closed upstream with [wontfix](https://bugs.gnupg.org/gnupg/msg6252) so we won't be carrying this, Sorry!

Thanks for the submission!

**Comment by bruno-** [comment]
I had this issue, and it seems it's not related to yubikey only - it happens with any smartcard!

This patch fixed the problem (I manually edited `gnupg2` formula on my local machine).

This was done on OSX Yosemite with `gpg2` version `2.0.29`. Hopefully new OSX version will bring improvements.

**Pull request closed without merging**
