### PR TITLE
tidy-html5 5.1.25

### PR DESCRIPTION
**Pull request by zmwangx**
https://github.com/htacg/tidy-html5/releases/tag/5.1.25.

### CODE REVIEW

**Comment by joeheyming** [comment]
how do I get this updated recipe?  I did brew upgrade tidy-html5, and still got 5.0.0

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Comment by geoffmcl** [comment]
@zmwangx, @mikemcquaid wow, sorry! Did not mean anything rude! Was just perhaps a too casual observation... as @joeheyming said, the stats are **awesome**!

As we discussed back in [September](https://github.com/htacg/tidy-html5/issues/224) I have been trying to get the tagging **right**... As you pointed out back then for 5.0.0, [v5.1.25](https://github.com/htacg/tidy-html5/releases/tag/5.1.25) does have a green **latest release** tag... Should I be doing more here? 

We also published a [quickref](http://api.html-tidy.org/tidy/quickref_5.1.25.html), [binaries](http://binaries.html-tidy.org/), etc, etc... What more do we need to do, if anything?

But I do understand that was just over two weeks ago, so no real problem... checking deeper, you are keeping what? over 3000, formula up-to-date, with each version, and that must take time and effort... congrats on that ;=))

And just a heads up, we are considering a new release soon... are working towards that... and are probably going to use the current simple Semantic versioning, rather that the even/odd versioning written here and there in some docs, comments... but that remains to be seen...

We will add a tag, binaries, api docs, quickref, etc, etc, but is there something else specific to alert homebrew that we should do?

Just very thankful that tidy is updated ;=)) fast work!

**Comment by zmwangx** [comment]
> As we discussed back in September I have been trying to get the tagging right... As you pointed out back then for 5.0.0, v5.1.25 does have a green latest release tag... Should I be doing more here?

Actually I do subscribe to your releases feed https://github.com/htacg/tidy-html5/releases.atom (technically speaking that's a tag feed). I guess the reason I didn't update the formula as soon as 5.1.25 was released was because it wasn't marked as a GitHub release at the time I checked (which might be seconds after the tag's pushed, in which case you wouldn't even have time to draft a release). Since I only read each feed entry once, I would't be aware if the status changed after I checked.

> We also published a quickref, binaries, etc, etc... What more do we need to do, if anything?

The source code with a clean build system is basically all we need. `tidy-html5` uses the standard CMake procedure with no need for any tweaks, so that's great, thanks for that.

> Is there something else specific to alert homebrew that we should do?

As I said I follow the release/tag feed, so it would help tremendously if every tag pushed (and on the master branch) is actually a packageable release.

Also, it would be more predictable if version strings are continuous, rather than jumping from 5.0.0 to 5.1.8 then to 5.1.24... That made me hesitate. But no obligation here, just one thing to consider.

One last thing: In case you need to alert someone to update the Homebrew formula, feel free to ping me. No need to bring a Homebrew maintain there, they already have enough on their shoulders.

**Comment by zmwangx** [comment]
@geoffmcl Alternatively, do you want me to update the formula here for every tag (i.e., also for 5.1.8, 5.1.24, etc.)? Updating this formula is very easy so I'm happy to do that. And releasing more frequently is certainly a good thing.

**Comment by mikemcquaid** [comment]
> @zmwangx, @mikemcquaid wow, sorry! Did not mean anything rude! Was just perhaps a too casual observation... as @joeheyming said, the stats are awesome!

No worries @geoffmcl, appreciate the apology and thanks for the kind words.

Homebrew differs from most package managers in that our community keeps most packages up-to-date and the maintainers are responsible for reviewing and merging community contributions. In this case e.g. we'll pull a new update when @zmwangx or someone else interested submits one.

**Pull request closed without merging**
