### PR TITLE
cmd: autoupdate

### PR DESCRIPTION
**Pull request by DomT4**
I’ve been using this locally for a while, because I’m lazy. It's not super-pretty, but it is quietly functional.

Thought it may be useful to others due to the recurring problem we have of people forgetting to update their `brew` more than once every 3 months ;). Easy interface, start, stop, delete.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Probably don't want to add more core commands but you should totally set this up as a tap command. Relatedly I had a friend asking me today why we keep telling people to `brew update` when we could do it automatically at e.g. `brew install` or `brew upgrade` time.

**Comment by DomT4** [comment]
Sure. Happy to do so. Still trying to get to grips with tap ` cmd `s. I haven't found them as workable as Homebrew's regular commands; still haven't managed to get the [killmyhomebrew](https://github.com/DomT4/homebrew-killmyhomebrew/blob/master/cmd/selfdestruct.rb) cmd from the other day working externally. Tried ` brew selfdestruct ` but it just fires back ` Erp, nope, no idea what that is ` :smile_cat:. Have been hunting around for some examples as to why it may suddenly have ceased working outside of Homebrew's actual ` cmd ` directory.

**Comment by mikemcquaid** [comment]
They are in a different format; you declare a method and have it called but need running the script to call the method e.g. like https://github.com/Homebrew/homebrew-brewdler/blob/master/cmd/brew-brewdle.rb

**Comment by DomT4** [comment]
Can I get away with just wrapping it in the call to Ruby, or do I have to manually separate it out into many chunks? I seem to recall managing to get it to somewhat work by wrapping the ` cmd ` in a call to ` /usr/bin/env brew `, and then just doing ` brew path/to/selfdestruct.rb ` but that's not hugely user friendly. At that point my headache won and I wandered off for a few days :smile_cat:

**Comment by mikemcquaid** [comment]
You can just add a call to the method as it won't be called for you.

**Comment by mikemcquaid** [comment]
Actually in this case it just needs to be named `brew-selfdestruct.rb`

**Comment by DomT4** [comment]
Apologies - Forgot this was still open. Moved to https://github.com/DomT4/homebrew-autoupdate.

**Pull request closed without merging**
