### PR TITLE
Homepage/URL fixes, https addition

### PR DESCRIPTION
**Pull request by vszakats**

### CODE REVIEW

**Comment by vszakats** [comment]
wxPython:
```
creating /usr/local/Cellar/wxmac/3.0.2/include/wx-3.0/wx/wxPython
error: could not create '/usr/local/Cellar/wxmac/3.0.2/include/wx-3.0/wx/wxPython': Operation not permitted
```

lbdb:
```
==> brew install ./lbdb-0.38.2.el_capitan.bottle.tar.gz
==> FAILED
Error: undefined method `bottle' for Formulary::FormulaNamespacecd68327fef9faebe25ed5865aade109c:Module
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Formula/lbdb.rb:4:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:22:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:22:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:35:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:84:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:75:in `klass'
/usr/local/Library/Homebrew/formulary.rb:71:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:97:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:206:in `factory'
/usr/local/Library/Homebrew/extend/ARGV.rb:18:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:44:in `install'
/usr/local/Library/brew.rb:143:in `<main>'
==> brew uninstall --force lbdb
==> brew uses --recursive libfreenect
==> git checkout master -f
==> git reset --hard
==> brew cleanup --prune=7
==> git clean -ffdx
Error: No available formula with the name "undefined method `bottle' for Formulary::FormulaNamespacecd68327fef9faebe25ed5865aade109c:Module" 
Build step 'Execute shell' marked build as failure
Recording test results
ERROR: Step ‘Publish JUnit test result report’ failed: No test report files were found. Configuration error?
Archiving artifacts
Started calculate disk usage of build
Finished Calculation of disk usage of build in 0 seconds
Started calculate disk usage of workspace
Finished Calculation of disk usage of workspace in 0 seconds
[WS-CLEANUP] Deleting project workspace...[WS-CLEANUP] done
Finished: FAILURE
```

**Comment by DomT4** [comment]
Working on the `wx` problem in https://github.com/Homebrew/homebrew/pull/47187. Not sure what's going on with `lbdb` - That potentially looks like an internal issue.

I'll merge this sooner rather than later, but was hoping to fix the `wx` problem, ask you to rebase this on the master and then pull new bottles for the things that don't have them/don't have El Cap ones.

**Comment by vszakats** [comment]
Thanks @DomT4! I'll do the rebase shortly.

**Comment by DomT4** [comment]
Don't rebase yet :wink:. The `wx` fix needs to be merged first or you'll run into that again, heh.

**Comment by DomT4** [comment]
In regards to the `lbdb` failure, appreciate this goes against 99% of what we've probably told you in the past, but post-rebase if you add an empty `bottle do` block into that formula it should pass. h/t Xu for the suggested workaround.

**Comment by vszakats** [comment]
Ah okay, got it! Will wait for `wx` and do the `bottle do` thing. Thanks to you both!

**Comment by DomT4** [comment]
Just gonna merge this as-is, bottles be damned.

Thanks @vszakats, and Merry Christmas. Appreciate all you've done for Homebrew this year.

**Comment by vszakats** [comment]
Thanks for the kind words @DomT4, I'm wishing you the same, along with some days away from the repository! Keep up the fantastic work you're doing &mdash; I wish other systems like Linux or FreeBSD had such a great package manager :)

**Comment by DomT4** [comment]
> along with some days away from the repository!

I should be so lucky :stuck_out_tongue_winking_eye:. I'm *hoping* to step away for 3/4 days from Wednesday evening. Probably won't stop people pinging me for questions/help/etc, heh.

I don't know if we have much on `apt` but I'll certainly take the compliment. Thank you!

**Comment by vszakats** [comment]
:beers:

**Pull request closed without merging**
