### PR TITLE
msktutil 1.0rc2

### PR DESCRIPTION
**Pull request by oflebbe**
Hi I am one of the upstream maintainers of msktutil.

I like to get the homepage and the version updated, since it is fixing a lot of bugs.

### CODE REVIEW

**Comment by DomT4** [comment]
> msktutil-1.0rc2.tar.bz2

Is that stable, despite the `rc` tag?

**Comment by oflebbe** [comment]
Yes. But we plan to ship 1.0 soon with some minor changes

**Comment by DomT4** [comment]
Is it worth waiting for that?

**Comment by DomT4** [comment]
Closing as dead. Please feel free to resubmit as fresh with the comments above addressed and audit passing, if you'd like to. Thanks for the submission to Homebrew!

**Pull request closed without merging**
