### PR TITLE
Update android-sdk to 24.3.2

### PR DESCRIPTION
**Pull request by 1zaman**

### CODE REVIEW

**Comment by 1zaman** [comment]
This does result in an error upon upgrading:

> Error: Failed to fix install names
The formula built, but you may encounter issues using it or linking other
formula against it.

Not sure what the issue is...

**Comment by DomT4** [comment]
^ See #40227. We don't know either, yet.

**Comment by 1zaman** [comment]
This seems to be related to the qemu binaries included in the tools as of version 24.3. When I remove them then this error goes away.

**Comment by jacknagel** [comment]
If you run with `--debug` you can see the real exception. Fixed in 9ffe108ec805ae412b8f39adbc653d43430fc6d3. This is fallout from ef6d160ec95cfd2517f92ed40b7e15427f91d8dd (prior to that we didn't try to fix the install names in these files).

Note that it is still going to issue a few warnings:

```
Warning: Could not fix /tmp/android-build-build-temp-50661/install-darwin-x86_64/lib/libz.1.dylib in /usr/local/Cellar/android-sdk/24.3.2/tools/qemu/darwin-x86_64/qemu-system-aarch64
Warning: Could not fix /tmp/android-build-build-temp-50661/install-darwin-x86_64/lib/libz.1.dylib in /usr/local/Cellar/android-sdk/24.3.2/tools/qemu/darwin-x86_64/qemu-system-mips64el
Warning: Could not fix /tmp/android-build-build-temp-50661/install-darwin-x86_64/lib/libz.1.dylib in /usr/local/Cellar/android-sdk/24.3.2/tools/qemu/darwin-x86_64/qemu-system-x86_64
```

Not much we can do about that as the referenced zlib is not present in the package.

**Comment by jacknagel** [comment]
@BrewTestBot test this please

**Comment by 1zaman** [comment]
@jacknagel: Sorry, I'm a newbie to Homebrew (and Mac OS X). Could you explain the context here? What is the purpose of the keg_fix_install_names.rb file, what did ef6d160ec95cfd2517f92ed40b7e15427f91d8dd achieve, what was the issue, and what was the fix? Is there still some issue remaining, and if so what is it?

**Comment by jacknagel** [comment]
My comments were really directed at the other maintainers. I fixed the immediate bug and merged this PR; you don't need to take any further action. The rest of your questions would take a while to answer completely.

**Comment by jacknagel** [comment]
If you're truly interested, a good place to start would be looking at the PRs referenced in the commit history for that file.

**Pull request closed without merging**
