### PR TITLE
node: bump npm to 3.5.3

### PR DESCRIPTION
**Pull request by bfontaine**

### CODE REVIEW

**Comment by jonbjornn** [comment]
Does this fix issue #48083?

**Comment by bfontaine** [comment]
@jonbjornn It appears so; I was able to run `npm -g update` without any error.

**Comment by jonbjornn** [comment]
Great, thanks for the quick fix!

**Comment by DomT4** [comment]
I can't reproduce the original error, and as far as I know upstream didn't update `npm` in their binaries with this release so not sure what the root cause would be.

I'm not opposed to updating our internal `npm` though; we used to do so much more regularly before the decision was made to track Node as closely as possible. If it works, feel free.

**Pull request closed without merging**
