### PR TITLE
Update to Riak 2.1.3

### PR DESCRIPTION
**Pull request by JeetKunDoug**

### CODE REVIEW

**Comment by dunn** [comment]
Anything we can do about this?
```
riak:
 * object files were linked against system openssl
These object files were linked against the deprecated system OpenSSL.
Adding `depends_on "openssl"` to the formula may help.
  /usr/local/Cellar/riak/2.1.3/libexec/lib/crypto-3.1/priv/lib/crypto.so

**Comment by dunn** [comment]
If you're feeling ambitious you could try switching the source to the GitHub tarball and doing a proper compile.  (Ambitious because the build system is Rebar https://github.com/basho/riak/blob/develop/rebar.config, which takes some pushing to cooperate with Homebrew.  See [`ejabberd.rb`](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/ejabberd.rb) for an example of how to vendor Rebar dependencies.)

**Comment by JeetKunDoug** [comment]
Yea - so I didn't create the original recipe, but what it's installing is the official releases for OS X from Basho (I work there)... we (Basho) don't want to depend on non-system OpenSSL, so for us, linking against the system OpenSSL isn't a bad thing per se.

As mentioned, you could pull from Git and do a build, but we build with a custom Erlang as well, which you'd have to install and/or build as well, which most people wouldn't necessarily want just to install Riak.

**Comment by mikemcquaid** [comment]
@JeetKunDoug it'd be good if we can try and have a from-source build. The system OpenSSL is officially deprecated on OS X 10.11 (no headers are provided) and has various security vulnerabilities.

**Comment by JeetKunDoug** [comment]
@mikemcquaid understood - unfortunately I'm personally not in a position to put one together right now given the additional complexities of using our custom Erlang as well... we'd really need to have both a riak and a "basho-erlang" recipe in order to get it off the ground at all.

**Comment by mikemcquaid** [comment]
@JeetKunDoug You can use a custom Erlang within the formula itself as a `resource` as it's not needed at runtime. It'd be great if you or someone at Basho could address this. Thanks!

**Comment by DomT4** [comment]
Will merge this because constantly reviewing open PRs is the bane of my life, but would really love a from-source build on this if possible.

Merged in https://github.com/Homebrew/homebrew/commit/28e1872b4bfb9347d11ebfbd8c7ddaa309b8027b. Thank you for another contribution to Homebrew @JeetKunDoug! :smiley_cat:

**Comment by JeetKunDoug** [comment]
I'll try to get a from-source build on our roadmap, but no promises.

**Pull request closed without merging**
